---
title: "To John William Parker, Jr."
letter_iso_date: "1860-01-13"
letter_date: "Jany 13th 1860"
location: "Otterbourne, Winchester."
manuscript: "Princeton Univeristy, Parrish Collection, C0171: Box 29"
post_id: 1781
letter_id: "to-john-william-parker-jr-8"
citation:
  type: personal_communication
  author:
    - family: Yonge
      given: Charlotte Mary
  editor:
    - family: Mitchell
      given: Charlotte
    - family: Jordan
      given: Ellen
    - family: Schinske
      given: Helen
  title: "To John William Parker, Jr."
  container-title: "The Letters of Charlotte Mary Yonge"
  issued: "1860-01-13"
  url: "https://cmyonge.github.io/letters/1781-to-john-william-parker-jr-8"
---

::: {.letter-metadata}
**Date:** Jany 13th 1860  
**From:** Otterbourne, Winchester.  
**Manuscript:** Princeton Univeristy, Parrish Collection, C0171: Box 29
:::

My dear [Sir](people/person_1143.qmd),

Some time ago you told me you could make arrangement for the publication of my books in America more satisfactory than the present with [Messrs Appleton](organizations/other_142.qmd).

I could not, neither can I now, avail myself of your kindness for myself, but I think it would be worth while to make arrangement for [Miss Roberts](people/person_1244.qmd)’ book, [Mlle Mori](other_books/otherbook_270.qmd)[^1]; I suppose there would still be time to send sheets to thei agent [sic] of an American house, and I believe that Italian liberty is sufficiently interesting in the States to make the tale likely to be popular there.

The more I see of it in the course of correcting the press,[^2] the more I think it likely to be successful, the latter part is full of interest, and all to whom I have shown any portion think well of it.

I hope the [review](other_books/otherbook_274.qmd) of [Aggesden Vicarage](other_books/otherbook_268.qmd) in the [Saturday](organizations/other_99.qmd) was not damaging - It has considerable irony but not ill natured[^3]

Yours faithfully

C.M. Yonge

---

[^1]: *Mademoiselle Mori : A Tale of Modern Rome*. 2 vols (London: John W. Parker and Son 1860).
[^2]: In CMY’s letter to Parker in October 1859 she asked him to reconsider publishing *Mademoiselle Mori*, Roberts having  “left it in my hands, to endeavour to procure its publication” while she was abroad. It seems that Parker had accepted the book and Yonge was now correcting the proofs.
[^3]: See letters to Ann Carter Smith of 6 and 10 January 1860.
