---
title: "To John William Parker, Jr."
letter_iso_date: "1860-07-03"
letter_date: "July 3d 1860"
location: "Otterbourne, Winchester."
manuscript: "MS Princeton University, Parrish Collection, C0171: Box 29"
post_id: 1794
letter_id: "to-john-william-parker-jr-11"
citation:
  type: personal_communication
  author:
    - family: Yonge
      given: Charlotte Mary
  editor:
    - family: Mitchell
      given: Charlotte
    - family: Jordan
      given: Ellen
    - family: Schinske
      given: Helen
  title: "To John William Parker, Jr."
  container-title: "The Letters of Charlotte Mary Yonge"
  issued: "1860-07-01"
  url: "https://cmyonge.github.io/letters/1794-to-john-william-parker-jr-11"
---

::: {.letter-metadata}
**Date:** July 3d 1860  
**From:** Otterbourne, Winchester.  
**Manuscript:** MS Princeton University, Parrish Collection, C0171: Box 29
:::

[To [John William Parker](people/person_1143.qmd), jr.] 

I wish to consult you on a question of publishing. Rather more than a year ago, I consented at the request of Messrs [Saunders and Otley](organizations/other_144.qmd) to let my tale <u>[Hopes and Fears](cmy_books/cmybook_37.qmd)</u> appear in their periodical the [Constitutional Press](organizations/other_65.qmd)[^1], reserving to myself the copy right, and intimating to them my intention of putting the tale when completed into your hands for publication. I have just heard that the Magazine has proved a failure (which did not greatly surprise me) and that the present is the last number. My story had reached the 15th chapter; and is finished as far as the 23d in M S. I hope to complete it in two or three months.

I had already mentioned to you that I propose to bring out my tale of the <u>[Young Stepmother](cmy_books/cmybook_38.qmd)</u>, now in course of publication in the <u>[Monthly Packet](organizations/other_52.qmd)</u> next December. I had then calculated that <u>Hopes and Fears</u> would be completed by the <u>Constitutional Press</u> a year or so after the other. 

This failure however has thrown me out, and I want to ask your advice if you will kindly favour me with it. It will of course be inexpedient to bring out both stories nearly at the same time. They should at least have a years’ interval between them, and I should be glad to know which, under the circumstances, you think ought to have the precedence. I am inclined to believe that it should be <u>Hopes and Fears</u> as the readers have now broken short off in the midst, and as it can be proceeded with at once, whereas <u>Young Stepmother</u> must not appear before December. On the other hand, I am doubtful as to the <u>prestige</u> of immediately bringing out a story connected with an abortive periodical, it is a matter on which you can better judge than I, and I should be glad if I could hear from you on the subject

Yours faithfully

C.M. Yonge

---

[^1]: A magazine published by William Tweedie, which ran as a weekly from July 1858 to March 1859, and then as a monthly to March 1860.
