---
title: "To Ann Maria Carter Smith"
letter_iso_date: "1861-03-05"
letter_date: "March 5th 1861"
location: "Otterbourne, Winchester."
manuscript: "MS Westcountry Studies Library, Exeter/ 1861/2"
post_id: 1821
letter_id: "to-ann-maria-carter-smith-41"
citation:
  type: article
  author:
    - family: Yonge
      given: Charlotte Mary
  editor:
    - family: Mitchell
      given: Charlotte
    - family: Jordan
      given: Ellen
    - family: Schinske
      given: Helen
  title: "To Ann Maria Carter Smith"
  container-title: "The Letters of Charlotte Mary Yonge"
  issued: "1861-03-05"
  url: "https://cmyonge.github.io/letters/1821-to-ann-maria-carter-smith-41"
---

::: {.letter-metadata}
**Date:** March 5th 1861  
**From:** Otterbourne, Winchester.  
**Manuscript:** MS Westcountry Studies Library, Exeter/ 1861/2
:::

My dear [Miss Smith](people/person_263.qmd)

Thanks many - not that I meant to be paid when I mentioned it only to avoid the loss of MSS - I shall be very glad to have them as they are ready, and if you write with them, I will not answer without occasion. I believe an odd number of stamps is always wrong - but 4 will carry almost anything one wants to send. You are right that one author takes Margaret, the other Blanch, and I think you can guess for whose sake I accepted [the whole](other_books/otherbook_278.qmd). It is an odd device, and one that I should not advise anyone to follow, but ‘Henrietta’ is a most comical device.

My ‘Old Subscriber’ only asks in general for information how to set up a sewing school  I think if your friend would kindly set down as shortly as possible how she began, whether with only lady superintendent, or paid help, how she got a room, what she did about materials, what became of the work or if the people brought their own, if she was there each night, how often in the week, if anything were paid, and if reading to the workers answered, it would make a foundation. If I cannot get up the information in time for April, I will answer promising it for May, so do not hurry, though I shall be very thankful for some help if your friends will kindly answer these questions.[^1]I am glad [Aggesden](other_books/otherbook_268.qmd) has turned out a good speculation I hope the [Wynnes](other_books/otherbook_267.qmd) may do the same, and I think you sacrifice something to the [non-identification](organizations/other_106.qmd), for in these things there is a great deal in a name.[^2]

yours sincerely

C M Yonge

---

[^1]: Articles on 'Sewing schools' appeared in *MP* in May and June 1861.
[^2]: Both *Aggesden Vicarage, or, Bridget Storey’s First Charge* (London, Parker 1859) and

*The Wynnes, or, Many Men, Many Minds: A Tale of Every-day Life* (London, Masters1861) were published without any “by the author of…” statement. Carter Smith seems, however, to have talken CMY’s advice. Her next book (1863) was *Mildred’s Last Night: or, The Franklyns*. By the Author of *Aggesden Vicarage*.
