---
title: "To Ann Maria Carter Smith"
letter_iso_date: "1862-01-22"
letter_date: "Jan 22d [1862]"
location: "Otterbourne, Winchester"
manuscript: "MS Westcountry Studies Library, Exeter/ Yonge 1862/1"
post_id: 1854
letter_id: "to-ann-maria-carter-smith-51"
citation:
  type: personal_communication
  author:
    - family: Yonge
      given: Charlotte Mary
  editor:
    - family: Mitchell
      given: Charlotte
    - family: Jordan
      given: Ellen
    - family: Schinske
      given: Helen
  title: "To Ann Maria Carter Smith"
  container-title: "The Letters of Charlotte Mary Yonge"
  issued: "1862-01-01"
  url: "https://cmyonge.github.io/letters/1854-to-ann-maria-carter-smith-51"
---

::: {.letter-metadata}
**Date:** Jan 22d [1862]  
**From:** Otterbourne, Winchester  
**Manuscript:** MS Westcountry Studies Library, Exeter/ Yonge 1862/1[^1]
:::

My dear [Miss Smith](people/person_263.qmd),

I enclose your cheque. I am very sorry to have kept you waiting so long, but [Mr Mozley](people/person_1065.qmd) has not paid me yet, and as I sent him an appeal the other day to see if I could not get our [pay raised](organizations/other_102.qmd), I was waiting for his answer though even if it were to raise our terms it would hardly be for this year that is past. I feel very cross every morning when the post comes with no letter from him, and I think how many expectants are abusing me!

I hope you have a great punishment in store for your [three Ks](other_books/otherbook_317.qmd)- otherwise I shall be much scandalized, Rosamond is bad enough but I cannot understand Rachel and Marion being shocked and the father not more angry. I recognized Frank, I wish you had given him his own surname. I think you must be as much tormented by time as I am in [continuing the Daisies](cmy_books/cmybook_53.qmd)[^2], perhaps more as you have married two stories. I see your heart is with Frank & Elizabeth much more than at Fair Elms, and I acquiesce, provided you will make that terrible Rosamond repent. I know a girl so like her that I can’t bear to see her so naughty

yours sincerely

C M Yonge

---

[^1]: Envelope addressed to Miss Ann Smith/ Rectory/ Old Charlton/ SE and postmarked Winchester 22 January 1862 and London SE 23 January 1862.
[^2]: *The Trial*, the sequel to *The Daisy Chain*, began serial pulication in the *MP* in January 1862.
