---
title: "To Charlotte Sophia Fursdon"
letter_iso_date: "1862-03-24"
letter_date: "March 24th 1862"
location: "Otterbourne, Winchester."
manuscript: "MS Mrs Katherine Wykes-Sneyd"
post_id: 1857
letter_id: "to-charlotte-sophia-fursdon"
citation:
  type: article
  author:
    - family: Yonge
      given: Charlotte Mary
  editor:
    - family: Mitchell
      given: Charlotte
    - family: Jordan
      given: Ellen
    - family: Schinske
      given: Helen
  title: "To Charlotte Sophia Fursdon"
  container-title: "The Letters of Charlotte Mary Yonge"
  issued: "1862-03-24"
  url: "https://cmyonge.github.io/letters/1857-to-charlotte-sophia-fursdon"
---

::: {.letter-metadata}
**Date:** March 24th 1862  
**From:** Otterbourne, Winchester.  
**Manuscript:** MS Mrs Katherine Wykes-Sneyd
:::

My dear [Glow worm](people/person_534.qmd),

Let us have the Redan[^1] then though I am a little puzzled about the greater proportion of [Goslings](organizations/other_104.qmd) having brothers in the army – if you counted [Humble Bee](people/person_81.qmd) as one[,] your Army List misled you for the [Alfred Moberly](people/person_1860.qmd) there is only a cousin. I spent Saturday evening with her, and told her all your questions, and she shuddered at the notion of the Redan. However that is no reason against it, for the majority may like it. I write now to advise you to specify that the Trial Scene in the Merchant of Venice should begin with Portia’s entrance, and to make it quite clear what you mean to have done, for I am not quite certain nor do I see many allusions in that scene. There are many more in the Lorenzo and Jessica scenes Troilus, Thisbe, Medea, Dido, the music of the spheres, Orpheus, Erebus, Endymion, the cuckoo, and then there is the controversy about the “Gatines”. On the whole if you do not think me an unbearable Mother Goose, I would ask you to choose that scene and frame the question thus. I know [Gurgoyle](people/person_327.qmd) and Humble Bee at least will like this much, and the telling the story of the play will be very amusing, I think. As I have given you your Redan you may let me this much interfere. I enclose the question instead of copying it again, as I think it will stand best.

Thank [Irene](people/person_538.qmd) for her little notes. When she thinks it good for her Egg I shall be glad to see any semi goslingisms. I sometimes get droll ones from other quarters. So we have two changes instead of one in the Gosling world. I think both the new nominations sound promising. 

your affectionate

Mother Goose

---

[^1]: A battle in the Crimean War.
