---
title: "To Frances Mary Peard"
letter_iso_date: "1863-00-00"
letter_date: "[1863]"
manuscript: "MS location unknown. This fragment printed in. Mary J. Y. Harris, <i>[Memoirs of Frances Mary Peard](other_books/otherbook_318.qmd)</i>, (1903) 49."
post_id: 1910
letter_id: "to-frances-mary-peard-7"
citation:
  type: personal_communication
  author:
    - family: Yonge
      given: Charlotte Mary
  editor:
    - family: Mitchell
      given: Charlotte
    - family: Jordan
      given: Ellen
    - family: Schinske
      given: Helen
  title: "To Frances Mary Peard"
  container-title: "The Letters of Charlotte Mary Yonge"
  issued: "1863-01-01"
  url: "https://cmyonge.github.io/letters/1910-to-frances-mary-peard-7"
---

::: {.letter-metadata}
**Date:** [1863]  
**Manuscript:** MS location unknown. This fragment printed in. Mary J. Y. Harris, <i>[Memoirs of Frances Mary Peard](other_books/otherbook_318.qmd)</i>, (1903) 49.
:::

My dear [Miss Peard](people/person_1160.qmd),

I am so sorry I did not come to the full perception of what I had done till I got home, but I was stupid enough when at Puslinch to take your St. Sebastian for your Book of Joshua, and pack it and send it off with the [Monthly Paper](organizations/other_81.qmd) things, and then I took (or fear I took) Joshua for a letter and made away with it. At least I cannot find it anywhere at home among the papers put, at Puslinch, into a reserve box. Instead of that I found a bundle of proofs, and the need of Joshua immediately, so I have been obliged to write it myself, and no doubt have not given it half the grace yours had .....[^1]	

I do not know whether I should have been ashamed to ask you to do it again for me. However, Ruth is quite safe, and in the home place where such things do not happen to MSS. I like her very much indeed and am very glad it is not she who I fear has come to grief. Pray forgive me for I have been punished for it.

Yours sincerely,

---

[^1]: Harris adds ‘This letter goes on to give directions as to the course to be taken in further papers through most of the books of the Old Testament . . It is a relief to find from a letter a few weeks after, that “Joshua came to light .... with some cards wrapt up in him”.’
