---
title: "To Ann Maria Carter Smith"
letter_iso_date: "1863-10-29"
letter_date: "Oct 29th [1863]"
location: "Elderfield, Otterbourne, Winchester."
manuscript: "MS Westcountry Studies Library, Exeter/ Yonge 1863/7"
post_id: 1911
letter_id: "to-ann-maria-carter-smith-64"
citation:
  type: personal_communication
  author:
    - family: Yonge
      given: Charlotte Mary
  editor:
    - family: Mitchell
      given: Charlotte
    - family: Jordan
      given: Ellen
    - family: Schinske
      given: Helen
  title: "To Ann Maria Carter Smith"
  container-title: "The Letters of Charlotte Mary Yonge"
  issued: "1863-10-29"
  url: "https://cmyonge.github.io/letters/1911-to-ann-maria-carter-smith-64"
---

::: {.letter-metadata}
**Date:** Oct 29th [1863]  
**From:** Elderfield, Otterbourne, Winchester.  
**Manuscript:** MS Westcountry Studies Library, Exeter/ Yonge 1863/7[^1]
:::

My dear [Miss Smith](people/person_263.qmd)

I have kept your French journal a terrible time, and I am sorry to say I cannot get it in after all. It is rather too much trodden ground, and even you cannot make it new enough. I think you will soon get a huge piece of the [Banks of the Thorne](other_books/otherbook_275.qmd) to finish them with the year if possible, and then we begin on our new principles. I hope the enclosed yellow paper[^2] will attract subscribers. I have been getting the attempt made, and the [Editor](people/person_1073.qmd) will I think manage it very well, as a sort of [newspaper magazine](organizations/other_69.qmd), to be safe to let schoolroom girls read. If you can contribute any descriptions of great popular days like some you have sometimes sent me it will be very grateful

yours sincerely

C M Yonge

---

[^1]: Envelope addressed to Miss Smith/ 8 Wellington Road/ Old Charlton/ SE and postmarked Winchester 29 October 1863 and London SE 30 October 1863.
[^2]: The envelope for this letter also contains a single sheet of yellow paper printed on both sides with an advertisement for “*Events of the Month: A Magazine of News, Literature, Science, and General Information; Designed for Youthful Readers* to be published by John and Charles Mozley, starting January 1st, 1864. Price sixpence.” It was edited by Henrietta Murray and ran from Jan. 1864 to Jan. . 1865. CMY later described it to Macmillan (3 June 1864) as “a sort of school room Athenaeum”, and tried unsuccessfully to get him to take it over when the Mozleys abandoned it.(see Macmillan to CMY  17 January 1865).
