---
title: "To Henrietta Elizabeth Fursdon"
letter_iso_date: "1863-12-05"
letter_date: "Decr 5th [1863]"
location: "Elderfield Otterbourne, Winchester."
manuscript: "MS Mrs Katherine Wykes-Sneyd"
post_id: 1921
letter_id: "to-henrietta-elizabeth-fursdon-9"
citation:
  type: article
  author:
    - family: Yonge
      given: Charlotte Mary
  editor:
    - family: Mitchell
      given: Charlotte
    - family: Jordan
      given: Ellen
    - family: Schinske
      given: Helen
  title: "To Henrietta Elizabeth Fursdon"
  container-title: "The Letters of Charlotte Mary Yonge"
  issued: "1863-12-05"
  url: "https://cmyonge.github.io/letters/1921-to-henrietta-elizabeth-fursdon-9"
---

::: {.letter-metadata}
**Date:** Decr 5th [1863]  
**From:** Elderfield Otterbourne, Winchester.  
**Manuscript:** MS Mrs Katherine Wykes-Sneyd
:::

My dear [Henrietta](people/person_538.qmd)

You have indeed had much sorrow during these two years, and you must be feeling it deeply, a kind aunt is such a treasure in ones life.[^1] It has been a strange year of death – the same post brought me tidings of the death of a little [godson](people/person_170.qmd) of mine who had long been hovering between life and death from the remains of scarlet fever, - his little [sister](people/person_169.qmd) two years younger previously died. She was about six years old, and was born after her [father](people/person_168.qmd)’s death. I don’t know whether you knew them, the Bogues of Tenbury.

I wonder what piece you are transcribing of [Marco Visconti](other_books/otherbook_77.qmd), it is a very interesting but a very melancholy book.[^2] I hear of many promising things for this [Barnacle](organizations/other_89.qmd).

I am not sure of the Fursdon post town so I must send this to Dawlish.

[signature cut out]

---

[^1]: The people referred to are the Reverend John Richard Bogue (1808-1857) and his children Edith Elizabeth Bogue (1857-1863) and Francis Reginald Bogue (1855-1863). They were cousins of CMY's through the Bargus family. The condolences are therefore probably on the death of Henrietta’s aunt [Elisabeth Fursdon](people/person_537.qmd) (1805-1863).
[^2]: This was presumably in connection with the [Gosling Society](organizations/other_104.qmd).
