---
title: "To Henrietta Elizabeth Fursdon"
letter_iso_date: "1863-12-18"
letter_date: "Dec 18th [1863]"
location: "Elderfield"
manuscript: "MS Mrs Katherine Wykes-Sneyd"
post_id: 1923
letter_id: "to-henrietta-elizabeth-fursdon-10"
citation:
  type: article
  author:
    - family: Yonge
      given: Charlotte Mary
  editor:
    - family: Mitchell
      given: Charlotte
    - family: Jordan
      given: Ellen
    - family: Schinske
      given: Helen
  title: "To Henrietta Elizabeth Fursdon"
  container-title: "The Letters of Charlotte Mary Yonge"
  issued: "1863-12-18"
  url: "https://cmyonge.github.io/letters/1923-to-henrietta-elizabeth-fursdon-10"
---

::: {.letter-metadata}
**Date:** Dec 18th [1863]  
**From:** Elderfield  
**Manuscript:** MS Mrs Katherine Wykes-Sneyd
:::

My dear [Henrietta](people/person_538.qmd)

You have a very nice set of [questions](organizations/other_104.qmd) this time and I think the best to choose among them will be the distinguished Christian characters of Milan, and the monuments, but I think you should call them sepulchral monuments, as I suppose you mean only those that mark the actual place of the remains - as I imagine you don’t wish to include *the* Monument par excellence. I think you may allot four sheets to Milan and six to the Monuments.

Did I send you this advertisement before.[^1] I hope you will take the thing in - it is in good hands, and I think will have a good deal that is pleasant and useful in it.

I am glad you have your aunts; though yours will be a sad subdued Christmas, it is such a comfort to be all together.[^2]

your affectionate

Mother Goose

---

[^1]: Black-edged paper.
[^2]: This was probably the flyer for *[Events of the Month](organizations/other_69.qmd)* which CMY also sent to Ann Carter Smith on 29 October 1863.
[^3]: Henrietta's aunt [Elizabeth Fursdon](people/person_537.qmd) had recently died.
