---
title: "Alexander Macmillan to Charlotte Mary Yonge"
letter_iso_date: "1864-03-09"
letter_date: "March 9.1864"
manuscript: "Copy outletter book British Library Add MSS.55382 P. 267"
post_id: 1943
letter_id: "alexander-macmillan-to-charlotte-mary-yonge-9"
citation:
  type: personal_communication
  author:
    - family: Yonge
      given: Charlotte Mary
  editor:
    - family: Mitchell
      given: Charlotte
    - family: Jordan
      given: Ellen
    - family: Schinske
      given: Helen
  title: "Alexander Macmillan to Charlotte Mary Yonge"
  container-title: "The Letters of Charlotte Mary Yonge"
  issued: "1864-03-09"
  url: "https://cmyonge.github.io/letters/1943-alexander-macmillan-to-charlotte-mary-yonge-9"
---

::: {.letter-metadata}
**Date:** March 9.1864  
**Manuscript:** Copy outletter book British Library Add MSS.55382 P. 267
:::

Dear Miss Yonge	.

What you received is an <u>original</u> drawing - not a proof. [I](people/person_939.qmd) am glad you like it so far. I want to reproduce it by the photolithographic process which is at once cheap and accurate. The [artist](people/person_500.qmd) is a very promising young man who is almost self taught & who has done some charming oil[sic].[^1] He wanted to try his hand on book[illustrations](organizations/other_167.qmd), and this seemed a good chance for him, if it did not please you, no matter, and if it did then we could have something to make this new [edition](cmy_books/cmybook_20.qmd) look lively. Will you kindly send me back the drawing, I shall send him your criticism.

I am dear Miss Yonge	
 Yours very faithfully
 A. Macmillan

---

[^1]: Robert B. Farren (b. 1832), later an artist and illustrator but at that date working as curator of a geological museum in Cambridge. There are many letters to him in this volume of Macmillan’s correspondence, and, as later letters reveal, Macmillan pressed CMY to allow him to illustrate a number of her books.
