---
title: "Alexander Macmillan to Charlotte Mary Yonge"
letter_iso_date: "1866-11-22"
letter_date: "Nov. 22 1866"
manuscript: "Copy outletter book British Library Add MSS.55386 (2) P.654"
post_id: 19659
letter_id: "alexander-macmillan-to-charlotte-mary-yonge"
citation:
  type: article
  author:
    - family: Yonge
      given: Charlotte Mary
  editor:
    - family: Mitchell
      given: Charlotte
    - family: Jordan
      given: Ellen
    - family: Schinske
      given: Helen
  title: "Alexander Macmillan to Charlotte Mary Yonge"
  container-title: "The Letters of Charlotte Mary Yonge"
  issued: "1866-11-22"
  url: "https://cmyonge.github.io/letters/19659-alexander-macmillan-to-charlotte-mary-yonge"
---

::: {.letter-metadata}
**Date:** Nov. 22 1866  
**Manuscript:** Copy outletter book British Library Add MSS.55386 (2) P.654
:::

Dear Miss Yonge,                                                                  

How do you like this? I think a [illegible] ly cheap book [illegible] [illegible]  made a profit.

Yours very f’lly

[A. Macmillan](people/person_939.qmd)

Alexander Macmillan to Charlotte Mary Yonge

Copy outletter book British Library Add MSS.55386 (2) P.701

&nbsp;

Dear Miss Yonge,                                           Dec. 3. 1866

&nbsp;

I have received some copies of Dynevor Terrace. Shall I send them to you or to some place inBrighton? I can probably add a book or two of my own if you say the cause is worthy.

&nbsp;

I will anyway see about the Cameos very soon and also about Miss Peard. The pre-Christmas weeks are rather pressing.

&nbsp;

I liked Miss Sewell’s title very well. It might be slightly modified. Have you got the leave [illegible]  from all the authors?

&nbsp;

I will write very soon,

&nbsp;

Yours faithfully,

	Macmillan

So the Chaplet finished?

&nbsp;

&nbsp;
