---
title: "To Alexander Macmillan"
letter_iso_date: "1865-07-28"
letter_date: "July 28th [1865]"
location: "Elderfield, Otterbourne, Winchester."
manuscript: "MS British Library Add MSS 54920: 103-4"
post_id: 2058
letter_id: "to-alexander-macmillan-54"
citation:
  type: personal_communication
  author:
    - family: Yonge
      given: Charlotte Mary
  editor:
    - family: Mitchell
      given: Charlotte
    - family: Jordan
      given: Ellen
    - family: Schinske
      given: Helen
  title: "To Alexander Macmillan"
  container-title: "The Letters of Charlotte Mary Yonge"
  issued: "1865-07-28"
  url: "https://cmyonge.github.io/letters/2058-to-alexander-macmillan-54"
---

::: {.letter-metadata}
**Date:** July 28th [1865]  
**From:** Elderfield, Otterbourne, Winchester.  
**Manuscript:** MS British Library Add MSS 54920: 103-4
:::

My dear [Mr Macmillan](people/person_939.qmd)
I send the rest of the MS of the [Dove in the Eagle’s Nest](cmy_books/cmybook_62.qmd) as it is all finished now, and I shall be going from home about the beginning of September into Devonshire first, and then perhaps to London some time in October - when I hope I may see you.

How soon will the last chapters of the [Prince and the Page](cmy_books/cmybook_61.qmd) be wanted? Since it began to come out I have found that Simon de Montfort really had a son called Richard who is unaccounted for. I suspect Wilfred’s name ought to be changed all through, but I am not sure whether this is of consequence enough to make it worth while.[^1]

People did not mind such things when [Sir Walter Scott](people/person_1672.qmd) called Aubrey de Vere Arthur, but they are more particular now.[^2]

If the Dove is ever published alone, I wonder how it would be to put in some of the woodcuts from [Theurdanck](other_books/otherbook_419.qmd), Maximilian’s own queer illustrated allegory of his life,[^3] from which I have taken some adventures. I have the book here now and his killing the bear, and leaping the chasm are quaint beyond description

Are your party going to make an expedition this year-?

Yours sincerely
C M Yonge

---

[^1]: This was done.
[^2]: Scott did this in *Anne of Geierstein*.
[^3]: The book, first printed in 1517, now attributed in part to Maximilian’s chaplain Melchior Pfintzing, appears under various titles; CMY used more than one edition.
