---
title: "Alexander Macmillan to Charlotte Mary Yonge"
letter_iso_date: "1865-08-01"
letter_date: "Aug 1. 1865"
manuscript: "Copy outletter book British Library Add MSS. 55384 (2): P. 718"
post_id: 2060
letter_id: "alexander-macmillan-to-charlotte-mary-yonge-39"
citation:
  type: article
  author:
    - family: Yonge
      given: Charlotte Mary
  editor:
    - family: Mitchell
      given: Charlotte
    - family: Jordan
      given: Ellen
    - family: Schinske
      given: Helen
  title: "Alexander Macmillan to Charlotte Mary Yonge"
  container-title: "The Letters of Charlotte Mary Yonge"
  issued: "1865-08-01"
  url: "https://cmyonge.github.io/letters/2060-alexander-macmillan-to-charlotte-mary-yonge-39"
---

::: {.letter-metadata}
**Date:** Aug 1. 1865  
**Manuscript:** Copy outletter book British Library Add MSS. 55384 (2): P. 718
:::

My dear Miss Yonge	
The MS. reached us safely. [I](people/person_939.qmd)will [*illegible*] distribution in the months[^1]

We shall be very glad to see you when you come to town. It is just possible that I may be gone to America, but my [wife](people/person_940.qmd) & [sister](people/person_941.qmd) are at home; and we recently made a valuable addition to our neighbourhood , 'the [author](people/person_378.qmd)of [John Halifax](other_books/otherbook_418.qmd)',whose husband [Mr Craik](people/person_379.qmd), has become my partner, has taken a house quite near us.[^2]  I think you will like to meet her.

I daresay [Mr Farren](people/person_500.qmd) would like to have the whole of the [Prince and the Page](cmy_books/cmybook_61.qmd) as soon as possible. Those little changes you speak of could be made before printing if you think them of any consequence. I suppose it is as well to be correct when you can, though the great mass of the reading public dont care about it.

Where could one see those illustrations you think might be suitable to the Dove?[^3] Some piquancy might be given to it by such [illustration](organizations/other_167.qmd). I am getting a little tired of the common two & three volume form novels are published in[.] I would be delighted to get an [*illegible*]      

We’re all well and the merry boys at home, we look formidable to a casual visitor.[^4] I hope your mother & brother are quite well.

Yours faithfully
Alex Macmillan		

I enclose the cheque

---

[^1]: CMY had sent him the remaining chapters of *The Dove in the Eagle's Nest* which was being serialized in *[Macmillan's Magazine](organizations/other_78.qmd)*, so the sense of this must be 'I will divide the chapters up suitably for monthly publication'.
[^2]: The Craiks married in April 1865 and lived at Chilchester Lodge, Wickham Road, Beckenham.
[^3]: CMY had suggested that illustrations could be based on those in *Der Theuerdank*.
[^4]: Macmillan had three sons, two daughters, a niece and three nephews under his roof, all under the age of 15.
