---
title: "To Alexander Macmillan"
letter_iso_date: "1865-08-02"
letter_date: "Aug 2nd 1865"
location: "Elderfield, Otterbourne, Winchester."
manuscript: "MS British Library Add MSS 54920: 105-6"
post_id: 2061
letter_id: "to-alexander-macmillan-55"
citation:
  type: article
  author:
    - family: Yonge
      given: Charlotte Mary
  editor:
    - family: Mitchell
      given: Charlotte
    - family: Jordan
      given: Ellen
    - family: Schinske
      given: Helen
  title: "To Alexander Macmillan"
  container-title: "The Letters of Charlotte Mary Yonge"
  issued: "1865-08-02"
  url: "https://cmyonge.github.io/letters/2061-to-alexander-macmillan-55"
---

::: {.letter-metadata}
**Date:** Aug 2nd 1865  
**From:** Elderfield, Otterbourne, Winchester.  
**Manuscript:** MS British Library Add MSS 54920: 105-6
:::

Dear [Mr Macmillan](people/person_939.qmd),
Thanks for the [cheque](organizations/other_160.qmd). I enclose the receipt.

I do not know whether the British Museum has a copy of [Theurdanck](other_books/otherbook_419.qmd) - probably it would I think, but if you should be in Oxford, there is a beauty at the Bodleian, a much better one than that which I have here, which is only lent to me.[^1]

You should also look at the wonderful wood cuts in ‘[Der Weise König](other_books/otherbook_420.qmd).’[^2] There is a demon sitting on the shoulder of the witch who is teaching Maximilian the black art who is extremely comical.

The proper name of Theurdanck is Die Allerdurch Leuchtigiste Reise ........Maximilian I ....... unter dem Nahmen Theurdanck The illustrations that might give ideas to be copied would be the 22d the 27th and 56th; I think few even heard of the book. The illustration belonging to his exploit on Ulm Cathedral was evidently too much for the designer who has made it much more absurd than frightful. But these would not illustrate the whole story, as the events only come in incidentally

I will get the rest of the [Prince & Page](cmy_books/cmybook_61.qmd) put in type and send it as soon as I can.[^3]

Yours sincerely
C M Yonge

I quite agree on the weariness of the 3 vol novel - indeed I believe the [Dove](cmy_books/cmybook_62.qmd) would only make one vol.

---

[^1]: The Bodleian Library has several editions of *Der Theuerdank*, including two early ones published in Frankfurt in 1563 and 1596, neither of which has the title in the form given in this letter. CMY wanted to [illustrate](organizations/other_167.qmd) *The Dove in the Eagle's Nest* with pictures from this book.
[^2]: *Der Weisskunig*, another fictionalized autobiography or biography of Maximilian I, published from fragments in 1775.
[^3]: *The Prince and the Page* was being serialized in *MP*, and Macmillan, who was going to publish it as a Christmas book, had asked her to send the rest of the story to the illustrator.
