---
title: "To the Reverend John Frewen Moor"
letter_iso_date: "1867-01-03"
letter_date: "Jan 3d [1867]"
location: "Elderfield, Otterbourne, Winchester."
manuscript: "MS Bodleian Library, Oxford: MS English Letters: e 86."
post_id: 2143
letter_id: "to-the-reverend-john-frewen-moor-11"
citation:
  type: personal_communication
  author:
    - family: Yonge
      given: Charlotte Mary
  editor:
    - family: Mitchell
      given: Charlotte
    - family: Jordan
      given: Ellen
    - family: Schinske
      given: Helen
  title: "To the Reverend John Frewen Moor"
  container-title: "The Letters of Charlotte Mary Yonge"
  issued: "1867-01-01"
  url: "https://cmyonge.github.io/letters/2143-to-the-reverend-john-frewen-moor-11"
---

::: {.letter-metadata}
**Date:** Jan 3d [1867]  
**From:** Elderfield, Otterbourne, Winchester.  
**Manuscript:** MS Bodleian Library, Oxford: MS English Letters: e 86.
:::

My dear [Mr Moor](people/person_1046.qmd)
Your opinion so entirely coincides with ours that I almost had my pen in my hand to write to you to say that we had only ten girls and five boys at school yesterday, and that I could conceive no variety of weather that will make the way passable for you and your spectators between this and tomorrow evening, and so that I had sent out messages to say the Lantern was adjourned.[^1] I am a little afraid of fixing the 15th because it <u>may</u> be the servants’ evening at the Park to which they invite [Mary Plumridge](people/person_1178.qmd), and on the whole I think it will be wise to leave the day unfixed till we see our way a little more clearly, and have it in the week after that - I think I never saw such an impassable snow, hardly any vehicles manage to go by, and no one but the postman and [Mr Wither](people/person_1544.qmd) contrive to stir

Yours sincerely
C M Yonge

---

[^1]: Envelope addressed to 'The Revd/ J F Moor/Ampfield Parsonage/ Romsey.' and postmarked Winchester Ja 3/67.
[^2]: The parish entertainment being arranged in letter to Moor, 28 December 1866.
