---
title: "Frances Martin to Alexander Macmillan"
letter_iso_date: "1867-04-02"
letter_date: "April 2d, 1867"
manuscript: "MS British Library Add MSS.54974/5-8"
post_id: 2162
letter_id: "frances-martin-to-alexander-macmillan-3"
citation:
  type: article
  author:
    - family: Yonge
      given: Charlotte Mary
  editor:
    - family: Mitchell
      given: Charlotte
    - family: Jordan
      given: Ellen
    - family: Schinske
      given: Helen
  title: "Frances Martin to Alexander Macmillan"
  container-title: "The Letters of Charlotte Mary Yonge"
  issued: "1867-04-02"
  url: "https://cmyonge.github.io/letters/2162-frances-martin-to-alexander-macmillan-3"
---

::: {.letter-metadata}
**Date:** April 2d, 1867  
**Manuscript:** MS British Library Add MSS.54974/5-8
:::

Dear [Mr Macmillan](people/person_939.qmd)
I believe we agreed that except to those who know [me](people/person_971.qmd) my name shall not be mentioned as Editor of the [Sunday Library](organizations/other_145.qmd). I think this, as you say, wise & desirable, but my difficulty with regard to Miss Yonge is that she says there is to be no editor. This of course is quite another thing & would be a very grave misunderstanding & one that would seriously affect me.

For all cases where you have spoken to possible contributors I think that after the first they should be referred me & that either with or without a name I should at once enter into correspondence with them & go into all the details which must be discussed & to which it is impossible that you can give time and attention; whilst I am, quite seriously, wretched at having undertaken work which it seems impossible for me to approach.

. . . . .

I am sure that we shall do wisely to give Miss Yonge definite biographies which she will do well & in which the fact that she represents only one sect in the Church will be of no consequence. That very important volume of the Preparation for the Gospel requires not only great erudition & insight but a wider and more comprehensive view than she would take. It should be done by a Philosopher - not by a Novelist; but her biographies are excellent & I always think of her with gratitude as the Author of the [Little Duke](cmy_books/cmybook_20.qmd). She could do anything in No 8 and it offers a wide choice. 

. . . . . . .

I have a cold again but will go down for a talk to Bedford Sq whenever you think it desirable

very truly yours
Frances Martin
