---
title: "Alexander Macmillan to Charlotte Mary Yonge"
letter_iso_date: "1867-05-10"
letter_date: "May 10 1867"
manuscript: "Copy outletter book British Library Add MSS.55387 (1) P. 168"
post_id: 2168
letter_id: "alexander-macmillan-to-charlotte-mary-yonge-47"
citation:
  type: personal_communication
  author:
    - family: Yonge
      given: Charlotte Mary
  editor:
    - family: Mitchell
      given: Charlotte
    - family: Jordan
      given: Ellen
    - family: Schinske
      given: Helen
  title: "Alexander Macmillan to Charlotte Mary Yonge"
  container-title: "The Letters of Charlotte Mary Yonge"
  issued: "1867-05-10"
  url: "https://cmyonge.github.io/letters/2168-alexander-macmillan-to-charlotte-mary-yonge-47"
---

::: {.letter-metadata}
**Date:** May 10 1867  
**Manuscript:** Copy outletter book British Library Add MSS.55387 (1) P. 168
:::

Dear Miss Yonge,
[*First page largely indecipherable, but seems to be concerned with*[The Danvers Papers](cmy_books/cmybook_63.qmd) ] 

The [Sunday Library](organizations/other_145.qmd) is making progress I hope. . .[I](people/person_939.qmd) have found it useful to have someone to depute the correspondence to and combat the kind of [*illegible*] on the spot to take matters over. A lady friend of [Mrs Craik](people/person_378.qmd), a [Miss Martin](people/person_971.qmd), has undertaken this.[^1] She is a lady of quite exceptional poise & cultivation, with extensive historical knowlege, so much so that Dr B [*illegible*], professor at Kings College, quite looks on her as an authority. I am sure you would like her. 

[*Next paragraph illegible*]

Yours faithfully
A. Macmillan

Are you to be in London soon? I should much like to have a meeting at my house, with the parties [*illegible] [illegible*] & Miss Martin.

---

[^1]: The novelist Dinah Craik (1826-1887), who had married Macmillan’s partner in 1865, had shared lodgings with Frances Martin in 1850 when both were in their early twenties.
