---
title: "To Christabel Rose Coleridge"
letter_iso_date: "1867-05-25"
letter_date: "May 25 th [1867]"
manuscript: "MS Mrs Clare Roels"
post_id: 2173
letter_id: "to-christabel-rose-coleridge-10"
citation:
  type: article
  author:
    - family: Yonge
      given: Charlotte Mary
  editor:
    - family: Mitchell
      given: Charlotte
    - family: Jordan
      given: Ellen
    - family: Schinske
      given: Helen
  title: "To Christabel Rose Coleridge"
  container-title: "The Letters of Charlotte Mary Yonge"
  issued: "1867-05-25"
  url: "https://cmyonge.github.io/letters/2173-to-christabel-rose-coleridge-10"
---

::: {.letter-metadata}
**Date:** May 25 th [1867]  
**Manuscript:** MS Mrs Clare Roels
:::

My dear [Christabel](people/person_329.qmd)
I send you the [Barnacle](organizations/other_89.qmd). I had thought of keeping it for [May](people/person_351.qmd), but as she does not come till the 6th, it would be too long. After all the sheets of the [Caged Lion](cmy_books/cmybook_81.qmd) have got bound up wrong by my fault, for I forgot to number the pages. I have now numbered them and put a notice that the reader must manage accordingly The difficulty in keeping always the same order is that Authors vary, and sometimes residences too - N B [Bog Oak](people/person_28.qmd) is gone for good to live at Wiverton, Plymton [sic] and there is the [new Gosling](people/person_1008.qmd) whom [Alice](people/person_327.qmd)will in ?sense you about- I think if you could let the Londoners have it first it would do best- then May and [Milly](people/person_17.qmd) would be killed off together, and then the Torquay ones, and consult Milly about [Magpie](people/person_896.qmd)- [Heather](people/person_1387.qmd) might perhaps come just before or just after Devonshire, and I count [Cricket](people/person_1603.qmd) as a Londoner - it is better too to make sure of her before the Eton holidays- I hope you have something for the next Barnacle.

Tell [Edith](people/person_331.qmd) that an [East Grinstead](organizations/other_45.qmd) sister has illustrated much of the [Lyra](other_books/otherbook_232.qmd), and they have been photographed. [Mr Wither](people/person_1544.qmd) got the book, but the poor children are allowed only monks and abbesses instead of fathers and mothers, and it altogether was so surprising to ordinary eyes that he was afraid to give it away, and so gave it to us, and we have supplied ourselves with many of the scenes that were not too unnatural

---

**Note:** Black-edged paper. Christabel Coleridge had taken over supervision of the distribution of the *Barnacle* from CMY who is warning her of some of the problems in getting the members of the [Gosling Society](organizations/other_104.qmd) to pass it from one to another.
