---
title: "To Christabel Rose Coleridge"
letter_iso_date: "1867-09-24"
letter_date: "Sept 24th [1867]"
location: "Elderfield, Otterbourne, Winchester."
manuscript: "MS Mrs Clare Roels"
post_id: 2207
letter_id: "to-christabel-rose-coleridge-13"
citation:
  type: personal_communication
  author:
    - family: Yonge
      given: Charlotte Mary
  editor:
    - family: Mitchell
      given: Charlotte
    - family: Jordan
      given: Ellen
    - family: Schinske
      given: Helen
  title: "To Christabel Rose Coleridge"
  container-title: "The Letters of Charlotte Mary Yonge"
  issued: "1867-09-24"
  url: "https://cmyonge.github.io/letters/2207-to-christabel-rose-coleridge-13"
---

::: {.letter-metadata}
**Date:** Sept 24th [1867]  
**From:** Elderfield, Otterbourne, Winchester.  
**Manuscript:** MS Mrs Clare Roels[^1]
:::

My dear [Christabel](people/person_329.qmd)
Here is the September [Barnacle](organizations/other_89.qmd) – the binder has really made it so, though it ought to be the Midsummer one. I suppose that great MS ought to go round with it as I suppose no one would have patience to copy it out in the right size[^2] It was very stupid and this thin Barnacle would be much the better for it. Will you put in a note to that effect when you write the orders. I have only the conclusion of [Two and Two](other_books/otherbook_507.qmd)[^3] towards another and I go to Ottery on Monday and to Puslinch on Wednesday next for a month, so the answers should come to me at Puslinch (Yealmpton) if they are not ready before Monday –

In haste
yours sincerely
C M Yonge

[Giftie](other_books/otherbook_500.qmd) I shall be glad of whenever you can send her – or wherever.

I have two old Barnacles here waiting

---

[^1]: Endorsed ‘1867’.
[^2]: The copies of the *Barnacle* were assembled from material written by contributors on their own paper, and though member of the [Gosling Society](organizations/other_104.qmd) were begged and exhorted to use a standard size, the pages vary a good deal in size and shape.
[^3]: *Two and Two*, a story by Frances Peard (Fern Seed) features in the last extant volume of the *Barnacle* (Michaelmas 1867).
