---
title: "Alexander Macmillan to Charlotte Mary Yonge"
letter_iso_date: "1867-11-21"
letter_date: "###############################################################################################################################################################################################################################################################"
manuscript: "Copy outletter book British Library Add MSS.55387 (2): P. 705"
post_id: 2219
letter_id: "alexander-macmillan-to-charlotte-mary-yonge-61"
citation:
  type: article
  author:
    - family: Yonge
      given: Charlotte Mary
  editor:
    - family: Mitchell
      given: Charlotte
    - family: Jordan
      given: Ellen
    - family: Schinske
      given: Helen
  title: "Alexander Macmillan to Charlotte Mary Yonge"
  container-title: "The Letters of Charlotte Mary Yonge"
  issued: "1867-11-21"
  url: "https://cmyonge.github.io/letters/2219-alexander-macmillan-to-charlotte-mary-yonge-61"
---

::: {.letter-metadata}
**Date:** ###############################################################################################################################################################################################################################################################  
**Manuscript:** Copy outletter book British Library Add MSS.55387 (2): P. 705
:::

My dear Miss Yonge	
[I](people/person_939.qmd) am afraid I omitted to tell you that our intention in publishing the <u>parts</u> is that the parts should not even seem complete, but end at the end of a sheet, or given number of pages quite irrespective of whether a sentence or chapter ends or not. The <u>volumes</u> are to be complete works. Our only motive in publishing extracts is to enable people to pay a little bit at a time. Many will pay 1/- a month who hesitate about 2/6 or 4/- a quarter[^1]

[Miss Martin](people/person_971.qmd) tells me that you want another proof on which to make certain corrections. I send you one of the parts again as it is the only form I have by me. You may use it for your corrections, and tear it up or add to it in any. The first part will consist of 112 pages. If you add more some of the present matter will go into the next. I hope your changes will not [*illegible*] diminution.

May I just say that I would be glad that the next two numbers should have as much story in them as possible. Our home friends will be disappointed if we sermonize them too much. And we want to give them <u>noble lives</u> to contemplate - and noble deaths:- the best of all sermons I think. It has struck me that we may call the volume the [Pupils of St John the Divine](cmy_books/cmybook_72.qmd) & some other early martyrs. You can make a nexus of some sort I am sure. I am under a sort of half promise to give Justin to a man who I think could treat it well and in a way you would like.

We want to publish quite by the 10th & 12th of February so that people may have a look of [*illegible*] before the ruck of Magazines come on them. You will kindly let me have it if you can by the middle of next week

believe me dear Miss Yonge	
Yours faithfully
A. Macmillan

---

[^1]: CMY was contributing a volume to [Macmillan's Sunday Library](organizations/other_145.qmd).
