---
title: "Alexander Macmillan to Charlotte Mary Yonge"
letter_iso_date: "1867-12-31"
letter_date: "Dec.31. 1867."
manuscript: "Copy outletter book British Library Add MSS.55387 (2): P. 827"
post_id: 2226
letter_id: "alexander-macmillan-to-charlotte-mary-yonge-62"
citation:
  type: article
  author:
    - family: Yonge
      given: Charlotte Mary
  editor:
    - family: Mitchell
      given: Charlotte
    - family: Jordan
      given: Ellen
    - family: Schinske
      given: Helen
  title: "Alexander Macmillan to Charlotte Mary Yonge"
  container-title: "The Letters of Charlotte Mary Yonge"
  issued: "1867-12-31"
  url: "https://cmyonge.github.io/letters/2226-alexander-macmillan-to-charlotte-mary-yonge-62"
---

::: {.letter-metadata}
**Date:** Dec.31. 1867.  
**Manuscript:** Copy outletter book British Library Add MSS.55387 (2): P. 827
:::

My dear Miss Yonge	
Thanks for your latest letter.[^1][I](people/person_939.qmd)will have the setting up of the Epistle seen to at once. 

Indeed you are a valuable ally for us, in our scheme. The man after all is never very far from the Child, and however much we <u>learn</u> we cannot <u>un</u>learn what is worth all the <u>learning</u> in the world, the common humanity the recognition and expression of which in words is what we call genius. Indeed it was no concise instinct that led me to ask you to open our [series](organizations/other_145.qmd). But it is absurd for me to speak as if you were not learned even in the sense I mean. No learnedest man could have put in the touches with such [*illegible*] & delicate truth than you, had we only had a clearer understanding.

About the translation I dont think there can be much difficulty. I will cut it up as you prefer, and you can easily give it the antiquarian air you speak of. I will ask a friend to look over it.

All best New Year blessings be with you
Yours faithfully
Alex. Macmillan

---

[^1]: There are no letters from CMY in the Macmillan archives between December 4 1867 and May 5 1868, even though there are copies in the outletter book of 11 written by Macmillan on issues relating to the final publication of *The Pupils of St John* (the opening volume in Macmillan's Sunday Library series), and to the progress of her *Cameos from English History* and of the *Historical Selections* she was editing with[Elizabeth Sewell](people/person_1301.qmd).  One possibility is that Macmillan gave the letters to [Frances Martin](people/person_971.qmd).
