---
title: "To George Lillie Craik"
letter_iso_date: "1868-09-09"
letter_date: "Sept 9th [1868]"
location: "Elderfield, Otterbourne, Winchester."
manuscript: "MS British Library Add MSS 54920: 210-11"
post_id: 2266
letter_id: "to-george-lillie-craik-6"
citation:
  type: article
  author:
    - family: Yonge
      given: Charlotte Mary
  editor:
    - family: Mitchell
      given: Charlotte
    - family: Jordan
      given: Ellen
    - family: Schinske
      given: Helen
  title: "To George Lillie Craik"
  container-title: "The Letters of Charlotte Mary Yonge"
  issued: "1868-09-09"
  url: "https://cmyonge.github.io/letters/2266-to-george-lillie-craik-6"
---

::: {.letter-metadata}
**Date:** Sept 9th [1868]  
**From:** Elderfield, Otterbourne, Winchester.  
**Manuscript:** MS British Library Add MSS 54920: 210-11
:::

Dear [Mr Craik](people/person_379.qmd)
I send the lacking [Cameo](cmy_books/cmybook_73.qmd).[^1] I have found things needing correction in three sheets of the [Chaplet of Pearls](cmy_books/cmybook_69.qmd), and I am searching for a sentence that I know was spoilt for want of a <u>not</u> - but the whereabouts of which I can in no wise as yet discover. If I do not find it before tomorrow’s post, I shall send the sheets to you which I have corrected for you to judge as to the importance of the matter.

The unlucky thing was that none of the books I had told me Sir Francis Walsingham’s age, and thus I made him an elderly man when he was but six and thirty and his daughters young ladies instead of small children. I antedated Sidney’s knighthood, too, and in these days any anachronism does not do. I have only just got Fox Bourne’s Sidney which cleared it up[^2]

Yours truly
C M Yonge

---

[^1]: The Cameo concerning the Edward I's conquest of Wales had accidentally been omitted from the book version.
[^2]: In the end she dealt with this problem by adding an apologetic preface to *The Chaplet of Pearls*, in which Sidney and Walsingham are characters.
