---
title: "To Edith Sophia Jacob"
letter_iso_date: "1868-09-21"
letter_date: "Sept 21 [1868]"
location: "Elderfield"
manuscript: "MS Charlotte Mitchell"
post_id: 2268
letter_id: "to-edith-sophia-jacob-16"
citation:
  type: personal_communication
  author:
    - family: Yonge
      given: Charlotte Mary
  editor:
    - family: Mitchell
      given: Charlotte
    - family: Jordan
      given: Ellen
    - family: Schinske
      given: Helen
  title: "To Edith Sophia Jacob"
  container-title: "The Letters of Charlotte Mary Yonge"
  issued: "1868-09-21"
  url: "https://cmyonge.github.io/letters/2268-to-edith-sophia-jacob-16"
---

::: {.letter-metadata}
**Date:** Sept 21 [1868][^1]  
**From:** Elderfield  
**Manuscript:** MS Charlotte Mitchell
:::

My dear [Edith](people/person_749.qmd)
I am so glad to have heard from you though I wish I could hear that Malvern was invigorating you, to say nothing of [Dr Gully.](people/person_599.qmd) [Miss Dyson](people/person_2016.qmd) is the niece of [my friend](people/person_464.qmd); I have only once seen her. She, ie Miss Dyson of Malvern is the daughter [of] old [Mr Frank Dyson](people/person_1774.qmd) of Tidworth whose name I think you must know and do not take it as a bad omen, has never been able to leave Malvern since she went there some twenty years ago. I found that after all the little notice of the ‘[Gates of Paradise](other_books/otherbook_483.qmd)’ which I had written for the [Monthly Packet](organizations/other_52.qmd) is coming in October. I thought it had been long ago, I hope the [Literary Churchman](organizations/other_76.qmd) has turned up. I will send you the Octr M Packet as soon as it comes out, but it is a stupid little bit. Are you able to think, though you cannot read, or have you banished thought It would be hard on your [brother](people/person_748.qmd)’s Ordination day.  I am wishing I could be at the Natal meeting on Thursday, but I shall be quite alone that day, and I do not think I can be spared. Being able to take hold of my hand is the thing [Mamma](people/person_1606.qmd) seems most to care for. I have left off this note many times to take hold of her hand.[^2] Yet - and there my note came to an end, between [Miss Wilbraham](people/person_1513.qmd)’s [nephew](people/person_2017.qmd) coming for leave out and all other interruptions so my yet - remains unsolved!

yours affectionately
C M Yonge

---

[^1]: The year date has been added in pencil in another hand, and the words ‘The first year of my illness.’
[^2]: Annotated ‘It was in answer to this I said that our Blessed Lord seemed to know this human instinct in us when he instituted the Blessed Sacrament by which we might touch Him, to which CY alludes in her next’.
