---
title: "To Mary Ann Moberly"
letter_iso_date: "1868-09-30"
letter_date: "Sept. 30, 1868"
location: "Otterbourne"
manuscript: "MS location unknown. This fragment printed in <i>[Dulce Domum](other_books/otherbook_122.qmd)</i> 206-7"
post_id: 2270
letter_id: "to-mary-anne-moberly-3"
citation:
  type: personal_communication
  author:
    - family: Yonge
      given: Charlotte Mary
  editor:
    - family: Mitchell
      given: Charlotte
    - family: Jordan
      given: Ellen
    - family: Schinske
      given: Helen
  title: "To Mary Ann Moberly"
  container-title: "The Letters of Charlotte Mary Yonge"
  issued: "1868-09-30"
  url: "https://cmyonge.github.io/letters/2270-to-mary-anne-moberly-3"
---

::: {.letter-metadata}
**Date:** Sept. 30, 1868  
**From:** Otterbourne  
**Manuscript:** MS location unknown. This fragment printed in <i>[Dulce Domum](other_books/otherbook_122.qmd)</i> 206-7
:::

My dear [Mrs. Moberly](people/person_1019.qmd),

Thank you for your kind, sweet, cheering note. It does seem to me truly that it is the burden of the flesh [she](people/person_1606.qmd) is freed from, so entirely labour and weariness had the mere act of living been to her for months past; but with what sweet smiles![^1] I am glad your dear [Alice](people/person_1025.qmd) so thoroughly shared the peacefulness of the earlier watch, as well as that last trying day, which I trust will have done her no harm. I hope she and the [Goddaughter](people/person_81.qmd) may be with us on Friday. She, with [George Yonge](people/person_1611.qmd) and (perhaps) [Duke](people/person_1599.qmd) and [Anne](people/person_1582.qmd), are the only ones to be with us here now who were with us before.[^2] The others have ‘all passed into the world of light,’[^2] - the dear [Kebles](people/person_798.qmd), [Lord Seaton](people/person_313.qmd), [Warden Barter](people/person_118.qmd), my cousins [James](people/person_1615.qmd) and [John](people/person_1618.qmd). All Alice’s life I think she was the most loved and cheering young thing, out of the family, to both my [father](people/person_1631.qmd) and mother; and how she helped us in 1854!  . . . I have been really alone for some time, so the loneliness does not press so much as no doubt it will.

---

[^1]: CMY’s mother Frances Mary Yonge had died on 28 September 1868.
[^2]: *i. e*. at WCY's funeral.

**Note:** Henry Vaughan (1621-1695): ‘They are all gone into the world of light!/ And I alone sit lingring here’.
