---
title: "To Christabel Rose Coleridge"
letter_iso_date: "1868-12-03"
letter_date: "Decr 3d [1868]"
location: "Puslinch Yealmpton"
manuscript: "MS Mrs Clare Roels"
post_id: 2294
letter_id: "to-christabel-rose-coleridge-19"
citation:
  type: article
  author:
    - family: Yonge
      given: Charlotte Mary
  editor:
    - family: Mitchell
      given: Charlotte
    - family: Jordan
      given: Ellen
    - family: Schinske
      given: Helen
  title: "To Christabel Rose Coleridge"
  container-title: "The Letters of Charlotte Mary Yonge"
  issued: "1868-12-03"
  url: "https://cmyonge.github.io/letters/2294-to-christabel-rose-coleridge-19"
---

::: {.letter-metadata}
**Date:** Decr 3d [1868]  
**From:** Puslinch Yealmpton  
**Manuscript:** MS Mrs Clare Roels
:::

My dear [Christabel](people/person_329.qmd)
Thank you and [Edith](people/person_331.qmd) for taking the Bandits’ Bride[^1], I hope your collections will prosper. We have £163, and want £700 if we build a masters house, £400 if we content ourselves with a school

Have you written to [Miss Arnold](people/person_1467.qmd), or shall I accepting [Miss Clarke](people/person_300.qmd) I find [Grace Latham](people/person_2024.qmd) has not time, so perhaps we had better accept [Miss Budd](people/person_219.qmd) and [Miss Llewellyn](people/person_2025.qmd). Scotland has sunk away from us, so I suppose Wales is coming instead The other perhaps we had better reject on the grounds of not being a round dozen. I think twelve is the right number.

Since September December is begun I shall send you Mother Goose’s own questions, to save one writing out of them.[^2]

‘Give a history of the art of letter-writing with an account of the most noted letters and correspondents ancient and modern.

What are the synonyms of Beauty – give their derivation, history and shades of meaning

your affectionate
Mother Goose

This ought to have gone yesterday

---

[^1]: Black-edged paper.
[^2]: A reference to the photograph of CMY which she was selling in aid of the proposed school in connection with the [Church of the Resurrection](organizations/other_188.qmd), Eastleigh.
[^3]: The letter is concerned with the administration of the [Gosling Society](organizations/other_104.qmd), of which Coleridge was secretary.
