---
title: "To Arthur John Butler"
letter_iso_date: "1869-06-18"
letter_date: "June 18th [1869]"
location: "Elderfield, Otterbourne, Winchester."
manuscript: "MS Mrs Caroline Fairclough/18"
post_id: 2322
letter_id: "to-arthur-john-butler-3"
citation:
  type: article
  author:
    - family: Yonge
      given: Charlotte Mary
  editor:
    - family: Mitchell
      given: Charlotte
    - family: Jordan
      given: Ellen
    - family: Schinske
      given: Helen
  title: "To Arthur John Butler"
  container-title: "The Letters of Charlotte Mary Yonge"
  issued: "1869-06-18"
  url: "https://cmyonge.github.io/letters/2322-to-arthur-john-butler-3"
---

::: {.letter-metadata}
**Date:** June 18th [1869]  
**From:** Elderfield, Otterbourne, Winchester.  
**Manuscript:** MS Mrs Caroline Fairclough/18
:::

My dear [Arthur](people/person_238.qmd)
Thank you much These thanks would have come sooner but that just as I was going to study and profit by your notes, a Yankee walked in with a letter of introduction, and I had to perform my civilities to him - alas he came just as the mutton was half cold and the pease all gone

I shall set to work and doctor up the chapter incorporating what you have done to it.[^1] I think Clark’s [comparative grammar](other_books/otherbook_552.qmd) is pretty good so far as I understand it, and I am pretty well off for Greek, French and English, but I am not satisfied with my Latin lights, and the next is a good deal light of nature I am sorry for the Agnus but no doubt you are right. I am going to rewrite and work your corrections in, and then most probably I shall molest /you\\ again.

My photograph looks as if - under certain conditions it might have turned out rather good, for such an unphotographable person as I know myself to be - at any rate ‘smiling at grief’ as I appear to be is better than frowning like a sepoy’s daughter or bandit’s bride as I generally do.[^2] [Emma](people/person_822.qmd) will think you unusually successful when she has seen the portrait gallery here!

Pray thank your [mother](people/person_240.qmd) and [aunt](people/person_113.qmd) for their letters and the latter for her hint about the Dolomites, by which I hope the [Packet](organizations/other_52.qmd) may profit.

yours sincerely
C M Yonge

---

[^1]: Black-edged paper.
[^2]: This correspondence with Arthur Butler relates to a series in *MP* on which they were collaborating entitled 'Polyglott Parsing', which traced the connections between several ancient and modern languages.
[^3]: CMY felt that she photographed badly, and had nicknamed some taken by her cousin Duke Yonge 'the Bandit's Bride', perhaps after *The Bandit's Bride; or, The Maid of Saxony.: A romance*  by Louisa Sidney Stanhope (London: Minerva Press 1807).  'smiling at grief' is from *Twelfth Night* II, 4.
