---
title: "To Charlotte Cordelia Yonge"
letter_iso_date: "1869-09-06"
letter_date: "Sept 6th [1869]"
location: "Elderfield, Otterbourne, Winchester."
manuscript: "MS West Devon Area Record Office Ac 1092/35"
post_id: 2340
letter_id: "to-charlotte-cordelia-yonge-2"
citation:
  type: personal_communication
  author:
    - family: Yonge
      given: Charlotte Mary
  editor:
    - family: Mitchell
      given: Charlotte
    - family: Jordan
      given: Ellen
    - family: Schinske
      given: Helen
  title: "To Charlotte Cordelia Yonge"
  container-title: "The Letters of Charlotte Mary Yonge"
  issued: "1869-09-06"
  url: "https://cmyonge.github.io/letters/2340-to-charlotte-cordelia-yonge-2"
---

::: {.letter-metadata}
**Date:** Sept 6th [1869]  
**From:** Elderfield, Otterbourne, Winchester.  
**Manuscript:** MS West Devon Area Record Office Ac 1092/35[^1]
:::

My dear [Charlotte](people/person_1587.qmd)
I have never thanked you for that kind note that told me so much and made me able to understand more of how the grievous scene went on, and how that [dearest one](people/person_1582.qmd) was taken and now I am wishing to know whether you think [uncle James](people/person_1614.qmd) or [Mr Rogers](people/person_2049.qmd) had at all apprehended that all the distressing symptoms of some years past were tending that way, as I now suppose they did. I was very anxious about her last year, and only said nothing (except to [Elizabeth Colborne](people/person_320.qmd)) because I thought [Mary](people/person_1626.qmd) could not bear to talk it over, and she certainly said things that shewed her to think that life was in a way over for her. How Mary is to bear up against all that must fall on her now I cannot think. I long to be of some help to her, and yet I fear no one can help her, [Duke](people/person_1599.qmd) does more than anyone else. I remember last year dear Anne saying that when once Duke was in the house things seemed off one’s mind. I am glad [Katharine](people/person_1365.qmd) is old enough to have a distinct remembrance of her aunt. I hope [Helen](people/person_1613.qmd) will have the same – you cannot think how good and gentle she is to me now.[^3] how did you get through Sunday, I hope [John Morshead](people/person_43.qmd) came to help Duke. - I am imagining that the Organ must have been silent. It will be very hard to you to begin to play it. Whenever you can write to me I shall be very thankful, I feel as if I hardly knew myself without Anne to turn to and think of

your affectionate cousin
C M Yonge

Thank Duke for his letter I wrote to Mary yesterday when I found I could not come. I am better today, but I know he is right &amp; that it is better not.

---

[^1]: Black-edged paper.
[^3]: Katherine (b. 1863) was the eldest of  Duke and Cordelia Yonge's children, and Helen (b.1860) was the eldest of CMY's brother's children.

**Note:** CMY had asked Charlotte Cordelia Yonge for an account of the death of Anne Yonge.
