---
title: "To Alexander Macmillan"
letter_iso_date: "1869-12-29"
letter_date: "Decr 29th [1869]"
location: "Elderfield, Otterbourne, Winchester."
manuscript: "MS British Library Add MSS 54920: 242-3"
post_id: 2363
letter_id: "to-alexander-macmillan-113"
citation:
  type: personal_communication
  author:
    - family: Yonge
      given: Charlotte Mary
  editor:
    - family: Mitchell
      given: Charlotte
    - family: Jordan
      given: Ellen
    - family: Schinske
      given: Helen
  title: "To Alexander Macmillan"
  container-title: "The Letters of Charlotte Mary Yonge"
  issued: "1869-12-29"
  url: "https://cmyonge.github.io/letters/2363-to-alexander-macmillan-113"
---

::: {.letter-metadata}
**Date:** Decr 29th [1869]  
**From:** Elderfield, Otterbourne, Winchester.  
**Manuscript:** MS British Library Add MSS 54920: 242-3
:::

My dear [Mr Macmillan](people/person_939.qmd)
You will think there is no end to the irons we have in the fire. But the [Population of an Old Pear Tree](cmy_books/cmybook_84.qmd) would be finished if we had not lost a number, and had to renew it. I send you the earlier chapters. The places for the woodcuts are marked in the margin.

But my chief reason for writing is to ask if you have heard of Beugnot’s [memoirs](cmy_books/cmybook_92.qmd) - he was employed under [Napoleon I](people/person_2207.qmd)and under the two or three ensuing kings, and has left two most amusing and spirited volumes of memoirs, including his experiences in the Conciergerie.[^1] They would make one English volume, which I think would take with the libraries.

Shall we - ie - my [brother](people/person_1624.qmd) and I undertake to translate it - I should go over it as I do the Population of a pear tree? I think

[last sheet is blank but letter ends here with no signature]

---

[^1]: Black-edged paper.
[^2]: The book CMY and JBY were offering to translate was Comte Jacques-Claude Beugnot, *Mémoires du comte Beugnot, ancien ministre (1783-1815*) 2 vols (Paris: Dentu 1866). The translation, edited by CMY, was published by Hurst and Blackett in 1871.
