---
title: "To Jane Mary Dampier"
letter_iso_date: "1870-07-05"
letter_date: "July 5th [1870]"
location: "Elderfield, Otterbourne, Winchester."
manuscript: "MS Princeton University, Parrish Collection C0171: Box 29"
post_id: 2383
letter_id: "to-jane-mary-dampier-2"
citation:
  type: personal_communication
  author:
    - family: Yonge
      given: Charlotte Mary
  editor:
    - family: Mitchell
      given: Charlotte
    - family: Jordan
      given: Ellen
    - family: Schinske
      given: Helen
  title: "To Jane Mary Dampier"
  container-title: "The Letters of Charlotte Mary Yonge"
  issued: "1870-07-05"
  url: "https://cmyonge.github.io/letters/2383-to-jane-mary-dampier-2"
---

::: {.letter-metadata}
**Date:** July 5th [1870]  
**From:** Elderfield, Otterbourne, Winchester.  
**Manuscript:** MS Princeton University, Parrish Collection C0171: Box 29
:::

My dear [Miss Dampier](people/person_1345.qmd)
I must tell you and [your sister](people/person_404.qmd) how sincerely I grieve for you. [^1]  I think the bereavement of the last parent is the sorrow that an unmarried woman always feels most, it seems so entirely to end the sense of being a child at home to be thought for and cared for, and to leave one so desolate, without shelter from the world.

I suppose it is that having been trained in trust we may be able to lift it higher when the time comes, and by knowing what our earthly parents have been learn to look up and feel what our Heavenly Father always is.  But I think the first return to daily life after the excitement of the first shock is over is the most trying time of all.

I hope you are both well and your [brother](people/person_2266.qmd). I shall hope to see you, but hardly I suppose before I leave home on the 18th. How you must like to think of your dear mother’s pleasure and exultation in that little book [^2]

Yours most sincerely

C M Yonge

---

[^1]: Black-edged paper.
[^2]: [Margaret Sarah Dampier](people/person_403.qmd) (1802/3-June 1870) was the mother of Jane, Emily and William John Dampier.
[^3]: Probably her novel *Lady Beatrix Graham*.
