---
title: "To Christabel Rose Coleridge"
letter_iso_date: "1871-10-12"
letter_date: "Oct 12th [1871?]"
location: "Elderfield, Otterbourne, Winchester."
manuscript: "MS Mrs Clare Roels"
post_id: 2421
letter_id: "to-christabel-rose-coleridge-68"
citation:
  type: article
  author:
    - family: Yonge
      given: Charlotte Mary
  editor:
    - family: Mitchell
      given: Charlotte
    - family: Jordan
      given: Ellen
    - family: Schinske
      given: Helen
  title: "To Christabel Rose Coleridge"
  container-title: "The Letters of Charlotte Mary Yonge"
  issued: "1871-10-12"
  url: "https://cmyonge.github.io/letters/2421-to-christabel-rose-coleridge-68"
---

::: {.letter-metadata}
**Date:** Oct 12th [1871?]  
**From:** Elderfield, Otterbourne, Winchester.  
**Manuscript:** MS Mrs Clare Roels
:::

My dear [Christabel](people/person_329.qmd)
[Goslings](organizations/other_104.qmd) <u>do</u> multiply overmuch, but I cannot refuse to make a two headed one, like [Double daisy](people/person_1161.qmd) out of these two damsels of [Miss Keary](people/person_793.qmd)’s about whom I send her letter.[^1] Will you send them the Gosling list, and standing orders  I am sending them the rules.  Who asks questions next – none have come to me to choose from for December-  and it is January that is the holiday.

I have given up the cats in grey. I find they come from Moliere and may have an objectionable meaning.[^2]

Can you write another story upon the Eagle and goose text, I do not think any will do as well, and no one but yourself has done it before.[^3]  I mean to make the connecting link be an Essay Society

your affectionate
Mother Goose

---

[^1]: Perhaps the Goslings called York and Lancaster Rose, who joined the society after 1869 and left it in November 1872.
[^2]: ‘ La nuit tous les chats sont gris’ is proverbial in French.
[^3]: Christabel Coleridge had published a story in 1864 entitled 'The eagle of one house is the goose of another'.  CMY was proposing to make this proverb the theme of the *MP* Christmas number for 1872.
