---
title: "To Janetta Sewell"
letter_iso_date: "1871-00-00"
letter_date: "[1871?]"
location: "Elderfield,  Otterbourne, Winchester."
manuscript: "MS fragment UCLA: collection 100: box 95"
post_id: 2430
letter_id: "to-janetta-sewell"
citation:
  type: article
  author:
    - family: Yonge
      given: Charlotte Mary
  editor:
    - family: Mitchell
      given: Charlotte
    - family: Jordan
      given: Ellen
    - family: Schinske
      given: Helen
  title: "To Janetta Sewell"
  container-title: "The Letters of Charlotte Mary Yonge"
  issued: "1871-00-00"
  url: "https://cmyonge.github.io/letters/2430-to-janetta-sewell"
---

::: {.letter-metadata}
**Date:** [1871?]  
**From:** Elderfield,  Otterbourne, Winchester.  
**Manuscript:** MS fragment UCLA: collection 100: box 95
:::

My dear [Miss Sewell](people/person_1305.qmd)[^1]

I have been from home or I would have answered sooner. I send you a pound for the poor woman—which I hope may help her on a little while.

Pray thank [the Warden](people/person_1304.qmd) greatly for his very kind messages through [Mr Wither](people/person_1544.qmd). If my friend [Miss Peard](people/person_1160.qmd)[^2] can come, I am sure you will like her. She is an excellent singer among other perfections, and full of life and brightness. I think you will like her book [One Year](other_books/otherbook_815.qmd). Her home is Torquay, I believe the family is Cornish and the [Garibaldi man](people/person_1159.qmd) is her uncle. [^3] Did you ever try how many words can be made out of the letters of Triangle? and do you know the

[part of letter missing]

I am hoping soon to see [your sister](people/person_1301.qmd)
Yours very sincerely
C M Yonge

---

[^1]: Black-edged paper.
[^2]: Name partly erased.
[^3]: Name partly erased.
[^4]: John Whitehead Peard (1811-1880), known as 'Garibaldi's Englishman', who had fought with Garibaldi in Italy, was Peard’s uncle and lived in Cornwall.
