---
title: "To Mary Ann Moberly"
letter_iso_date: "1872-01-01"
letter_date: "Jan. 1, 1872."
manuscript: "MS location unknown.  This fragment printed in [<i>Dulce Domum</i>](other_books/otherbook_122.qmd), 245-6."
post_id: 2432
letter_id: "to-mary-ann-moberly-6-3"
citation:
  type: article
  author:
    - family: Yonge
      given: Charlotte Mary
  editor:
    - family: Mitchell
      given: Charlotte
    - family: Jordan
      given: Ellen
    - family: Schinske
      given: Helen
  title: "To Mary Ann Moberly"
  container-title: "The Letters of Charlotte Mary Yonge"
  issued: "1872-01-01"
  url: "https://cmyonge.github.io/letters/2432-to-mary-ann-moberly-6-3"
---

::: {.letter-metadata}
**Date:** Jan. 1, 1872.  
**Manuscript:** MS location unknown.  This fragment printed in [<i>Dulce Domum</i>](other_books/otherbook_122.qmd), 245-6.
:::

[[To [Mary Ann Moberly](people/person_1019.qmd)]

There is a full detail of all that is known in a letter from [Mr. Brooke](people/person_1981.qmd) in the new number of [*Mission Life*](organizations/other_80.qmd) . . .  both bring out more of the pain and grief than the first, which rests on one like a vision of the crystal sea and the palm.[^1]  But the sweet smile bears one on through it all.  I go to Lichfield on Monday;  [Mrs. Selwyn](people/person_1297.qmd) says that [her Bishop](people/person_1295.qmd) is overflowing with recollections of the early days of the mission.  . . .  Some islands have been quite depopulated by those wretches.  I believe Satan always does stir up something dreadful when his kingdom is being taken from him, but when he can only make martyrs it is well. . .

---

[^1]: CMY refers to the reports of the death of the Rt. Rev. [John Coleridge Patteson](people/person_1155.qmd), and to her visit to Lichfield to research the biography she was writing.  The Bishop of Lichfield, George Augustus Selwyn, had formerly been Bishop of New Zealand and had appointed Patteson Missionary Bishop of Melanesia.
