---
title: "To Sir William Heathcote, Bt."
letter_iso_date: "1872-04-08"
letter_date: "April 8, 1872"
location: "Elderfield, Otterbourne, Winchester"
manuscript: "MS location unknown.  Printed in Coleridge, [<i>Life</i>](other_books/otherbook_40.qmd), 301-2"
post_id: 2442
letter_id: "to-sir-william-heathcote-bt-6"
citation:
  type: article
  author:
    - family: Yonge
      given: Charlotte Mary
  editor:
    - family: Mitchell
      given: Charlotte
    - family: Jordan
      given: Ellen
    - family: Schinske
      given: Helen
  title: "To Sir William Heathcote, Bt."
  container-title: "The Letters of Charlotte Mary Yonge"
  issued: "1872-04-08"
  url: "https://cmyonge.github.io/letters/2442-to-sir-william-heathcote-bt-6"
---

::: {.letter-metadata}
**Date:** April 8, 1872  
**From:** Elderfield, Otterbourne, Winchester  
**Manuscript:** MS location unknown.  Printed in Coleridge, [<i>Life</i>](other_books/otherbook_40.qmd), 301-2
:::

My dear [Sir William](people/person_669.qmd)
Would you be so kind as to look at page 9 of the 'Gleanings' at the beginning of the [*Musings on the Christian Year*](cmy_books/cmybook_88.qmd), and tell me whether you have any recollection of telling [Mr. Keble](people/person_798.qmd) anything about your opinion of [King Charles](people/person_1768.qmd)'s truth?[^1]

There is a new edition called for, and [Miss Dyson](people/person_464.qmd) wants me to take it out.  Her letter coming while I was at Salisbury, I asked whether it was there thought that I ought, as it was not according to my impression lightly thrown out, and I put it in because I thought it disproved blind admiration, while showing the real tenderness.

[The Bishop](people/person_1015.qmd) advised me to ask whether you remembered having said anything of the kind to him - if you did, to leave it; if not, to take it out. So I am acting by order in troubling you about it.

Your affectionate
C. M. Yonge

---

[^1]: The cult of Charles I was very significant to the Tractarians.  In the case of the Hursley group their intense historical consciousness was stimulated by the fact that Richard Cromwell had inhabited the village.
