---
title: "To Christabel Rose Coleridge"
letter_iso_date: "1875-07-31"
letter_date: "July 31st 1875"
location: "Elderfield, Otterbourne, Winchester."
manuscript: "MS Mrs Clare Roels"
post_id: 2533
letter_id: "to-christabel-rose-coleridge-82"
citation:
  type: personal_communication
  author:
    - family: Yonge
      given: Charlotte Mary
  editor:
    - family: Mitchell
      given: Charlotte
    - family: Jordan
      given: Ellen
    - family: Schinske
      given: Helen
  title: "To Christabel Rose Coleridge"
  container-title: "The Letters of Charlotte Mary Yonge"
  issued: "1875-07-31"
  url: "https://cmyonge.github.io/letters/2533-to-christabel-rose-coleridge-82"
---

::: {.letter-metadata}
**Date:** July 31st 1875  
**From:** Elderfield, Otterbourne, Winchester.  
**Manuscript:** MS Mrs Clare Roels[^1]
:::

My dear [Christabel](people/person_329.qmd)

Writing about cheerfulness with a heavy cold in one’s head on a summer day, may be as hard as writing in the midst of a wet cricket match but I am trying to do it.  I shall direct this to Hanwell, not knowing where you are at Chiddingfold I suppose with the [Humberts](people/person_730.qmd).  Have you heard that Mr [Trant Bramston](people/person_196.qmd) is going to be married, and so [Miss Bramston](people/person_198.qmd)’s occupation comes to an end.  Luckily the lady, a [Miss Adey](people/person_2303.qmd) is her dearest friend.  

Your [book](other_books/otherbook_865.qmd) will come I suppose in that October batch will [sic?] calls itself the next years[^2]

your affectionate
C M Yonge

---

[^1]: The envelope also engraved on flap with address, postmarked Winchester 31 July 1875 and addressed to ‘Miss C.R.Coleridge/ Hanwell Rectory/Middlesex’.
[^2]: Coleridge's novel *Hugh Crichton's Romance* was published in November 1875.
