---
title: "To Mary Yonge"
letter_iso_date: "1876-07-03"
letter_date: "July 3d [1876]"
location: "Elderfield"
manuscript: "MS Plymouth and West Devon Record Office  308/260"
post_id: 2556
letter_id: "to-mary-yonge-45"
citation:
  type: article
  author:
    - family: Yonge
      given: Charlotte Mary
  editor:
    - family: Mitchell
      given: Charlotte
    - family: Jordan
      given: Ellen
    - family: Schinske
      given: Helen
  title: "To Mary Yonge"
  container-title: "The Letters of Charlotte Mary Yonge"
  issued: "1876-07-03"
  url: "https://cmyonge.github.io/letters/2556-to-mary-yonge-45"
---

::: {.letter-metadata}
**Date:** July 3d [1876]  
**From:** Elderfield  
**Manuscript:** MS Plymouth and West Devon Record Office  308/260
:::

My dear [Mary,](people/person_1626.qmd)

I did not like to write to you all this time because we were in a a great state of uncertainty.  However [Julian](people/person_1624.qmd) got a letter yesterday from the ‘liquidator’ to say that the creditors will take £2000 now and £500 six months hence which will cover everything, and is much better than at one time we expected  I do think it is a comfort ones fears go too far for it makes what would be bad news at first seem quite a relief.  It was like being in a state of siege all the time.  [Frances](people/person_1604.qmd)would not even have the chimneys swept for fear the creditors should benefit by it.  I am sure all together it has shewn the kindness of friends!  [Gertrude](people/person_1462.qmd) is gone out for her visits, and is in Sussex now, and since she went I have had [Mary Coleridge](people/person_351.qmd) for nearly a week, but she has not as much time to give me as I hoped, as [Alethea Mackarness](people/person_923.qmd) wants her help so much in the preparations for the double wedding which falls severely on her, as the other two girls are only 14 and 7.  It is hard to lose [Eleanor](people/person_2305.qmd) the most effective of all the girls at 20, but they like her marriage exceedingly, though they much dread the other.[^1] [Bernard](people/person_2143.qmd) and [Mary](people/person_927.qmd) are to live at [his father](people/person_343.qmd)’s and will be very badly off for the present.  [Alethea](people/person_182.qmd) is to go to her school on the 5th of August.  It is at Liverpool a most inconvenient distance, but we know the lady, which is the attraction.   I am afraid [Uncle Yonge](people/person_1623.qmd) must feel this great heat very much.  I have more to say but I have so many needful letters to write that I must end this one

your most affectionate
C M Yonge

---

[^1]: On 3 August 1876 Mary Alethea Mackarness (1851-1940) married her cousin the Hon. Bernard Coleridge and her sister Eleanor Victoria Mackarness (1855-1936) married the Hon. and Rev. Randal Parsons (1848-1936).  Alethea Mackarness and her husband perhaps disapproved of [first cousins marrying](organizations/other_101.qmd), or perhaps they disliked the fact that Bernard Coleridge was still reading for the bar and financially dependent on his father, Lord Coleridge, then chief justice of the common pleas and subsequently Lord Chief Justice.
