---
title: "To the Parishioners of Otterbourne"
letter_iso_date: "1876-11-18"
letter_date: "November 1876"
manuscript: "Printed in the <i>Otterbourne Parish Magazine</i>  - Hampshire Record Office 109m95/1-2"
post_id: 2565
letter_id: "to-the-parishioners-of-otterbourne-4"
citation:
  type: article
  author:
    - family: Yonge
      given: Charlotte Mary
  editor:
    - family: Mitchell
      given: Charlotte
    - family: Jordan
      given: Ellen
    - family: Schinske
      given: Helen
  title: "To the Parishioners of Otterbourne"
  container-title: "The Letters of Charlotte Mary Yonge"
  issued: "1876-11-18"
  url: "https://cmyonge.github.io/letters/2565-to-the-parishioners-of-otterbourne-4"
---

::: {.letter-metadata}
**Date:** November 1876  
**Manuscript:** Printed in the <i>Otterbourne Parish Magazine</i>  - Hampshire Record Office 109m95/1-2
:::

Dear Sir[^1]

I would be glad to make use of your pages to explain to children and parents the system of Sunday school tickets, which some younger ones seem not to understand properly. The ticket is made the reward for a special lesson repeated by heart or a fixed number of answers in writing to questions because these are better tests of diligence than answering aloud which may depend only on quickness and readiness. But some children try to take up many more lessons than they can properly learn and think themselves badly treated if they are turned back and do not receive a ticket for an ill said lesson. It ought then be understood that ill repeated lessons do not deserve a ticket and that it is unfair and unjust to give one not properly earned. No more lessons should be attempted than can be thoroughly learnt.

Some children can learn more easily than others but the amount must be proportioned to their capacity by their teachers. The Collects and Gospels being learned from the first, become very easy after a few years. Then more may be added but not before and learning fragments of many lessons is not the right way of gaining tickets as some children seem to think. Nor should children be sent to school to say ‘their lessons’ and then get their tickets and go away without any of the after teaching which is really the most important point.

Tickets are encouragement not so much coin to be purchased by repeating anything however badly, as some little girls seem to think.

C.M. Yonge

---

[^1]: The letter is addressed ostensibly to the editor of the *Otterbourne Parish Magazine*, the Rev. [Walter Elgie](people/person_478.qmd).
