---
title: "To the Reverend Bartholomew Price"
letter_iso_date: "1877-06-01"
letter_date: "June 1st 1877"
location: "Elderfield, Otterbourne, Winchester."
manuscript: "MS Pembroke College Oxford 60/14/86"
post_id: 2582
letter_id: "to-the-reverend-bartholomew-price-2"
citation:
  type: personal_communication
  author:
    - family: Yonge
      given: Charlotte Mary
  editor:
    - family: Mitchell
      given: Charlotte
    - family: Jordan
      given: Ellen
    - family: Schinske
      given: Helen
  title: "To the Reverend Bartholomew Price"
  container-title: "The Letters of Charlotte Mary Yonge"
  issued: "1877-06-01"
  url: "https://cmyonge.github.io/letters/2582-to-the-reverend-bartholomew-price-2"
---

::: {.letter-metadata}
**Date:** June 1st 1877  
**From:** Elderfield, Otterbourne, Winchester.  
**Manuscript:** MS Pembroke College Oxford 60/14/86
:::

My dear [Mr Price](people/person_1208.qmd)

I think I may venture to write to you upon [Julian’](people/person_1624.qmd)s behalf in this matter of the Secretaryship for I am sure your old friendship for him would make you inclined to help him, and I think there are qualifications which he has in a high degree, and on which I can really be an unpartial witness - i.e. - I have always seen that his military training made him well able to deal with men, and in all his career as a magistrate and county man he has been able to hold his own, and yet be friendly with those he had to do with.  He knows a good deal about land and letting of farms &c and also about matters of repairs and buildings and seems to be just fit for an agency from his various kinds of experiences.  It is very important to him to get some such employment chiefly for the sake of the educating of his boys.  He has been much cramped since last year when the failure of a coal mine brought so much loss on him, and to take this work while the boys are being educated would just be the thing to right him[^1]

yours very sincerely
C M Yonge

---

[^1]: As a result of his recent financial crisis CMY's brother Julian Yonge had applied for the post of Secretary of [Winchester College](organizations/other_50.qmd).
