---
title: "To Florence Wilford"
letter_iso_date: "1878-10-01"
letter_date: "October 1, 1878"
location: "Elderfield, Otterbourne, Winchester"
manuscript: "MS Miss Barbara Dennis.  Part facsimile in Dennis, [<i>Charlotte Yonge</i>](other_books/otherbook_55.qmd) following 45.   Printed in Coleridge, <i>Life</i> 319"
post_id: 2644
letter_id: "to-florence-wilford-8"
citation:
  type: article
  author:
    - family: Yonge
      given: Charlotte Mary
  editor:
    - family: Mitchell
      given: Charlotte
    - family: Jordan
      given: Ellen
    - family: Schinske
      given: Helen
  title: "To Florence Wilford"
  container-title: "The Letters of Charlotte Mary Yonge"
  issued: "1878-10-01"
  url: "https://cmyonge.github.io/letters/2644-to-florence-wilford-8"
---

::: {.letter-metadata}
**Date:** October 1, 1878  
**From:** Elderfield, Otterbourne, Winchester  
**Manuscript:** MS Miss Barbara Dennis.  Part facsimile in Dennis, [<i>Charlotte Yonge</i>](other_books/otherbook_55.qmd) following 45.   Printed in Coleridge, <i>Life</i> 319
:::

My dear [Florence](people/person_1520.qmd)

I am glad you finished your journey prosperously, and I hope you have brought home a store of strength for the winter and for the trials.

How one sometimes wishes that one's people may never have another worry, and yet I suppose it is all right!  I have just lost my most good and wise friend [Marianne Dyson](people/person_464.qmd).  For more than a year she had been in so utterly feeble and broken a state that one could only dread further loss of faculties, and there was a good deal of wearing though not acute suffering, so that it was really thankworthy to know that rest had come on St. Michael's morning.  I have known her 35 years, and she has been a great help and blessing throughout my life.  Scarcely a story of mine but has been read and discussed with her, and I don't know any one I owe so much to after my [Father](people/person_1631.qmd) and [Mother](people/person_1606.qmd) and [Mr. Keble](people/person_798.qmd).  [Anna Bramston](people/person_195.qmd) was there, being a friend of her companion [Miss Leroy](people/person_869.qmd).  [Mary Bramston](people/person_198.qmd) spent last evening here, her farewell before going to Truro.[^1]  [Gertrude](people/person_1462.qmd) is better, but cannot walk at all now.  I am so glad you are able to 'take up your pen,' as poor people's letters say.  I hope the ideas will flow if you do not call them <u>too</u> hard.

Your affectionate
C. M. Yonge

---

[^1]: Mary Bramston went to Truro as governess to the daughters of the new Bishop, the Rt. Rev. [Edward White Benson](people/person_140.qmd).
