---
title: "To Mrs Curteis"
letter_iso_date: "1878-10-03"
letter_date: "Oct 3d [1878]"
location: "Elderfield"
manuscript: "MS Princeton University, Parrish Collection C0171: Box 29"
post_id: 2645
letter_id: "to-mrs-curteis"
citation:
  type: personal_communication
  author:
    - family: Yonge
      given: Charlotte Mary
  editor:
    - family: Mitchell
      given: Charlotte
    - family: Jordan
      given: Ellen
    - family: Schinske
      given: Helen
  title: "To Mrs Curteis"
  container-title: "The Letters of Charlotte Mary Yonge"
  issued: "1878-10-01"
  url: "https://cmyonge.github.io/letters/2645-to-mrs-curteis"
---

::: {.letter-metadata}
**Date:** Oct 3d [1878]  
**From:** Elderfield  
**Manuscript:** MS Princeton University, Parrish Collection C0171: Box 29
:::

My dear [Mrs Curteis](people/person_2034.qmd)

First I must tell you of what perhaps you have seen in the [Guardian](organizations/other_75.qmd), my dear [Miss Dyson](people/person_464.qmd)’s death. She had been growing feebler and feebler for the last two years and had for months been wholly confined to bed, and unable to read even a letter, though she was constantly read to for the last fortnight she was almost unconscious, and slept herself away. She leaves a great blank behind her!

I am afraid it is too late to protest against [Helen’s babies](other_books/otherbook_907.qmd), except by word of mouth as I have done, for I can’t bear them[^1]  But I think they have had their day - and the bad imitation will do more to disgust with them than my protest. Armine does not by any means die so you need not be afraid for him.[^2] I have him now in the midst of a naughty fit, quite sufficient to save his life.

Thank you so much for your kind thoughts about the game

Yours sincerely
C M Yonge

---

[^1]: John Habberton *Helen's Babies* (1876), a best-selling work for young people. CMY may perhaps have considered that it treated religion irreverently.
[^2]: Armine is a character in CMY's *Magnum Bonum* (1879), serialized in *MP* January 1877-December 1879..
