---
title: "To Ellen Julia Johns"
letter_iso_date: "1870-00-00"
letter_date: "[1870-2?]"
manuscript: "MS Mitchell Library, Sydney. ML A27 1-275 (Microfilmed Sept 1993, Reel CY2846 )"
post_id: 2688
letter_id: "to-ellen-julia-johns-16"
citation:
  type: personal_communication
  author:
    - family: Yonge
      given: Charlotte Mary
  editor:
    - family: Mitchell
      given: Charlotte
    - family: Jordan
      given: Ellen
    - family: Schinske
      given: Helen
  title: "To Ellen Julia Johns"
  container-title: "The Letters of Charlotte Mary Yonge"
  issued: "1870-01-02"
  url: "https://cmyonge.github.io/letters/2688-to-ellen-julia-johns-16"
---

::: {.letter-metadata}
**Date:** [1870-2?]  
**Manuscript:** MS Mitchell Library, Sydney. ML A27 1-275 (Microfilmed Sept 1993, Reel CY2846 )
:::

My dear [Mrs Johns](people/person_772.qmd), 

It shall not be my fault but my misfortune if I do not see the diversions of Winton House on Tuesday - I was going from home on Monday, but I have just put it off.

I wish [Mr Johns](people/person_769.qmd)’s lectures had been after noon ones. Then I could have come! The Skeleton seems waiting till publishing matters are less dead.

I hope this great evening is a sign that you are pretty well again

Yours sincerely
C M Yonge

---

**Note:** Two letters are folded together in an envelope addressed to 'Mrs Johns, Winton House, Winchester', andpostmarked 1Winchester/D/ DE 5/70.' This letter evidently dates between the foundation of the [Winchester Literary and Scientific Society](organizations/other_208.qmd) and the death of the Rev. Charles Alexander Johns in 1874.  It probably dates from the earlier part of that period, since his death seems to have been preceded by illness.
