---
title: "To Christabel Rose Coleridge"
letter_iso_date: "1881-04-23"
letter_date: "April 23d [1881]"
location: "Elderfield"
manuscript: "MS Mrs Clare Roels"
post_id: 2723
letter_id: "to-christabel-rose-coleridge-102"
citation:
  type: personal_communication
  author:
    - family: Yonge
      given: Charlotte Mary
  editor:
    - family: Mitchell
      given: Charlotte
    - family: Jordan
      given: Ellen
    - family: Schinske
      given: Helen
  title: "To Christabel Rose Coleridge"
  container-title: "The Letters of Charlotte Mary Yonge"
  issued: "1881-04-01"
  url: "https://cmyonge.github.io/letters/2723-to-christabel-rose-coleridge-102"
---

::: {.letter-metadata}
**Date:** April 23d [1881]  
**From:** Elderfield  
**Manuscript:** MS Mrs Clare Roels
:::

My dear [Christabel](people/person_329.qmd)

It certainly used to be considered the thing to give the publisher of the magazine the refusal of the story but there is so much more free trade in publishing now that I do not know whether this is still necessary. I think most likely [Masters](people/person_981.qmd) would say he did not want to have it particularly.  

No, I think Miss Ingelow has diverged plentifully from you, except in the original idea.[^1]  Here is another suggestion-  make a general drawing, and have the babies both stripped while their belongings are insensible.  You might have let the mother of the bad one die at his birth, and quite drawn one or both nurses- then if the mother did not recover for some weeks, I think the identifying would be impossible, especially as you have the further advantage of the family likeness being all the same.

I was interrupted by a call from [Mr Walter Brock](people/person_210.qmd) whose whole desire seems to be to alter as little as possible.[^2]  I believe he will begin about the first week in June, only avoiding the having to inflict the 39 articles on us on Whitsunday.  I have been staying with the Awdrys at Chichester in [Canon Ashwell](people/person_68.qmd)’s house.[^3]  [Mrs Ashwell](people/person_2329.qmd) is going back to live at Chichester

your affectionate
C M Yonge

---

[^1]: Christabel Coleridge's  *A Lot with a Crook in it*, serialized in *MP* from January 1884 to May 1885, and Jean Ingelow's *Don John* (1881) both had plots depending on babies being switched in childhood.  But the book which Coleridge is considering whether to offer to Joseph Masters is probably *Kingsworth, or, The Aim of a Life* (London: Masters 1882).
[^2]: The Rev. Walter Brock (1849-1919)  succeeded the Rev. Walter Elgie as Vicar of Otterbourne after the latter's death in February 1881.
[^3]: The Rev. [William Awdry](people/person_85.qmd) was head of the Chichester Theological College, succeeding the Rev. Canon Arthur Rawson Ashwell (1824-23 October 1879). Christabel Coleridge would have known the latter because he had been vice-principal of St. Mark’s College, Chelsea (1851-3) under her father.  His widow was born Elizabeth Fixsen.
