---
title: "To Caroline Elizabeth Cooke Trench"
letter_iso_date: "1881-08-21"
letter_date: "Aug 21st [1881]"
location: "Elderfield"
manuscript: "MS Hampshire Record Office: Heathcote Family Scrapbooks: 63M84/234/49"
post_id: 2732
letter_id: "to-caroline-elizabeth-cooke-trench"
citation:
  type: article
  author:
    - family: Yonge
      given: Charlotte Mary
  editor:
    - family: Mitchell
      given: Charlotte
    - family: Jordan
      given: Ellen
    - family: Schinske
      given: Helen
  title: "To Caroline Elizabeth Cooke Trench"
  container-title: "The Letters of Charlotte Mary Yonge"
  issued: "1881-08-21"
  url: "https://cmyonge.github.io/letters/2732-to-caroline-elizabeth-cooke-trench"
---

::: {.letter-metadata}
**Date:** Aug 21st [1881]  
**From:** Elderfield  
**Manuscript:** MS Hampshire Record Office: Heathcote Family Scrapbooks: 63M84/234/49
:::

My dear [Caroline](people/person_367.qmd)

Somehow I must write for one can easier do that than say, all that my mind is full of .

It is very very kind of [Lady Heathcote](people/person_665.qmd) to send me that message and of you to think of me. I shall be there at the house on Tuesday - and as it is [Gertrude](people/person_1462.qmd)’s Communion day, it will be a fit beginning and will chime with you.

I hope to come over on Thursday, and meet with you at Church - or if I am prevented that day I will come Friday.

Truly I have been thinking again and again over the kindnesses that have come again and again all through these years, and that deep perfect confidence that made me look up to him. The tenderness of a strong nature is above all beautiful and precious, and I think that made me love and admire him all the more.

And then so much was inherited. Those happiest and brightest days when my home was all together - were full of consistent reference to him. My [father](people/person_1631.qmd) keeping the postman to write off notes on all the work they did together - and good work it was! I wonder if it is wrong to think of such friends having met in Paradise. Their generation of friends is nearly all gone thither - ‘ in sure and certain hope’ [^1] It is as if among all the grief, the great thought was to give thanks for having been allowed to watch something of so pure and high and noble a life

Your loving
C M Y

---

[^1]: The message was perhaps an invitation to attend some gathering associated with Sir [William Heathcote](people/person_669.qmd)'s funeral on Tuesday 23 August 1881.
[^2]: The quotation is from 'The Order for the Burial of the Dead' in *The Book of Common Prayer*: 'earth to earth, ashes to ashes, dust to dust;  in sure and certain hope of the Resurrection to eternal life . . .'
