---
title: "To Percy Harris"
letter_iso_date: "1882-03-27"
letter_date: "March 27th 1882"
location: "Elderfield, Otterbourne, Winchester."
manuscript: "MS Bodleian Library, Oxford: Ms. Eng. lett. e.100 ff161-2"
post_id: 2745
letter_id: "to-percy-harris"
citation:
  type: article
  author:
    - family: Yonge
      given: Charlotte Mary
  editor:
    - family: Mitchell
      given: Charlotte
    - family: Jordan
      given: Ellen
    - family: Schinske
      given: Helen
  title: "To Percy Harris"
  container-title: "The Letters of Charlotte Mary Yonge"
  issued: "1882-03-27"
  url: "https://cmyonge.github.io/letters/2745-to-percy-harris"
---

::: {.letter-metadata}
**Date:** March 27th 1882  
**From:** Elderfield, Otterbourne, Winchester.  
**Manuscript:** MS Bodleian Library, Oxford: Ms. Eng. lett. e.100 ff161-2
:::

My dear [Percy](people/person_631.qmd)

The houses I should prefer for a boy are 

the Revd [J H DuBoulay](people/person_446.qmd)’s
Southgate Hill	or

the Revd[J T Bramston](people/person_196.qmd)’s
Culvers’ Close[^1]

I have a weakness for a clergyman’s house, and besides, I think so highly of both the men and their wives - [Mrs DuBoulay](people/person_2343.qmd) as I daresay you know was Alice Cornish sister to the [Bishop of Madagascar](people/person_2344.qmd). Both she and [Mrs Bramston](people/person_2303.qmd) are very nice about the boys. Mrs Bramston’s father is [Archdeacon Adey](people/person_2342.qmd) he /Mr B\\ is [the Dean](people/person_197.qmd)’s son. I should certainly try to get [George](people/person_2340.qmd) into one of their houses, though of course it must be a chance. Preference has really so little to do with it that I do not suppose it would be of any use for me to say anything. They had not, when I last heard, discovered anything in [Mr Fearon](people/person_502.qmd)s house to account for the illness, but I think there must have been, as three boys were ill, the butler died, and the doctor who attended them like wise.[^2] I suppose it will be thoroughly  investigated when Mr Fearon leaves it. I hope George may get in to College, and that we may be able to meet when you come with him at Election . I think you are quite right in deciding against Harrow

Yours affectionately
C M Yonge

---

[^1]: Percy (Primrose) Harris (b. !839/40), the widow of CMY's cousin the Rev. George Collyer Harris (1833-1874), Vicar of St. Luke's Torquay, was evidently proposing to send her son George Newton Harris (b. 1868/9) to [Winchester College](organizations/other_50.qmd).
[^2]: If he does not get an academic scholarship (‘into College’) he must board with one of the housemasters.
[^3]: The Rev. William Andrewes Fearon, subsequently (1884-1901), headmaster of Winchester College.
