---
title: "To George Lillie Craik"
letter_iso_date: "1882-05-20"
letter_date: "May 20th 1882"
location: "Elderfield, Otterbourne, Winchester."
manuscript: "MS British Library Add MSS 54921: 111-112"
post_id: 2748
letter_id: "to-george-lillie-craik-53"
citation:
  type: article
  author:
    - family: Yonge
      given: Charlotte Mary
  editor:
    - family: Mitchell
      given: Charlotte
    - family: Jordan
      given: Ellen
    - family: Schinske
      given: Helen
  title: "To George Lillie Craik"
  container-title: "The Letters of Charlotte Mary Yonge"
  issued: "1882-05-20"
  url: "https://cmyonge.github.io/letters/2748-to-george-lillie-craik-53"
---

::: {.letter-metadata}
**Date:** May 20th 1882  
**From:** Elderfield, Otterbourne, Winchester.  
**Manuscript:** MS British Library Add MSS 54921: 111-112
:::

Dear [Mr Craik](people/person_379.qmd)

Thank you for your letter, and your kind promise of [£200](organizations/other_160.qmd) for this edition of [<u>Unknown to History</u>](cmy_books/cmybook_157.qmd). I hope the cheap movement will be successful. I own I should like to see [the Heir of Redclyffe](cmy_books/cmybook_15.qmd) and [Heartsease](cmy_books/cmybook_19.qmd) in shilling and sixpenny editions  I think they would have a great sale.

Please let a copy of ‘Unknown to History’ go to 

[Miss Coleridge](people/person_351.qmd)
Manor House
Ottery St Mary

I thought it would have come while she was staying with me or I should have set it down before.

It is curious that the Cavendish and Talbot families should come so much to the front in it just now[^1]

Yours truly
C M Yonge

---

[^1]: Lord Frederick Cavendish (1836-6 May 1882) had recently been assassinated in Phoenix Park by Irish nationalists.  He and the Rev. Edward Stuart Talbot, Warden of Keble College Oxford, had married sisters.  *Unknown to History* is concerned with the captivity of Mary, Queen of Scots, at the hands of Bess of Hardwick, who married successively into the Cavendish and Talbot families.
