---
title: "To Catharine Elgie"
letter_iso_date: "1883-01-27"
letter_date: "Jany 27th [?1883]"
location: "Elderfield, Otterbourne, Winchester."
manuscript: "MS Charlotte Mary Yonge Society/9"
post_id: 2769
letter_id: "to-catharine-elgie"
citation:
  type: article
  author:
    - family: Yonge
      given: Charlotte Mary
  editor:
    - family: Mitchell
      given: Charlotte
    - family: Jordan
      given: Ellen
    - family: Schinske
      given: Helen
  title: "To Catharine Elgie"
  container-title: "The Letters of Charlotte Mary Yonge"
  issued: "1883-01-27"
  url: "https://cmyonge.github.io/letters/2769-to-catharine-elgie"
---

::: {.letter-metadata}
**Date:** Jany 27th [?1883]  
**From:** Elderfield, Otterbourne, Winchester.  
**Manuscript:** MS Charlotte Mary Yonge Society/9
:::

My dear [Mrs Elgie](people/person_475.qmd)

The weather is not kind, and it is unlucky, as the last days of the week are so occupied, and on Tuesday I have to be at the [GFS](organizations/other_23.qmd)working committee meeting  I will try to come by your way, and bring [Packet](organizations/other_52.qmd) and other matters.

I wanted to tell you about poor [Mrs Jewell](people/person_767.qmd).[^1]  That miserable man cannot or will not get anything to do- and she is reduced to going out to service again, putting out the children for it is mere starving now, and she can only get a little needlework.  He might go to sea.  She is fit to be either cook or nurse, and her needlework is very good.  Could you find anything that would do for her?   [Ada Hoskins’](people/person_717.qmd)s poor baby was ill taken care of, and was sent home to her mother so ill that it died last Saturday[^2]   It was hard on [Mrs Hoskings](people/person_2154.qmd) after having done all she could to keep it from the girls

yours affectionately
C M Yonge

---

[^1]: Perhaps Mary Jewell (b. 1852/3), wife of William Jewell, of Otterbourne, labourer, and mother of Rose (b. 1877/8) and Percy (b. 1879/80).  MS Hampshire Record Office 70M92W/60/228, a copy outletter from Charles Wooldridge, solicitor (29 January 1896), refers to a Mrs Jewell living in a house owned by CMY.
[^2]: Ada Hoskins (b. 1862/3) was the daughter of James Hoskins, carpenter and his wife Eliza, of Otterbourne Hill. She was kitchenmaid to Mr Jones Bateman in 1881, and is perhaps the Rose Hoskins (b. Otterbourne 1862/3) who was a housemaid in Stoke Newington in 1891. It sounds as if she might have had an illegitimate baby and that her mother had concealed the fact.  The death of an infant William James Hoskins was registered at Winchester in the January quarter of 1883.
