---
title: "To George Lillie Craik"
letter_iso_date: "1884-07-10"
letter_date: "July 10th 1884"
location: "Elderfield"
manuscript: "MS British Library Add MSS 54921: 128-9:"
post_id: 2793
letter_id: "to-george-lillie-craik-58"
citation:
  type: personal_communication
  author:
    - family: Yonge
      given: Charlotte Mary
  editor:
    - family: Mitchell
      given: Charlotte
    - family: Jordan
      given: Ellen
    - family: Schinske
      given: Helen
  title: "To George Lillie Craik"
  container-title: "The Letters of Charlotte Mary Yonge"
  issued: "1884-07-10"
  url: "https://cmyonge.github.io/letters/2793-to-george-lillie-craik-58"
---

::: {.letter-metadata}
**Date:** July 10th 1884  
**From:** Elderfield  
**Manuscript:** MS British Library Add MSS 54921: 128-9:
:::

Dear [Mr Craik](people/person_379.qmd)

I shall have a child’s book called ‘[The Two Sides of the Shield](cmy_books/cmybook_184.qmd)' ready to come out about next Easter as it will be finished in the <u>[Monthly Packet](organizations/other_52.qmd)</u> about that time.

I feel as if I ought to express my great regret that there has been such a story as [the Author of Beltraffio](other_books/otherbook_972.qmd) in the [Eng Illustrated Magazine](organizations/other_68.qmd). [^1]

Surely it will only tend to make sceptically inclined people averse from devout faith - of which they will take Mrs Ambient as a representative and even apart from that most serious evil, it is terribly painful.

Please forgive me for speaking out but I am shocked and grieved and am inclined to cut out the story before lending it. I was sorry for [the poem](other_books/otherbook_973.qmd) about the man dying without prayer but that seemed an accident, and I am more sorry that it is followed up with this[^2]

Yours truly
C M Yonge

---

[^1]: Henry James’s story ‘The Author of “Beltraffio”’ appeared in Macmillan’s new periodical, the *English Illustrated Magazine* 1 (June-July 1884), alongside  CMY's ‘The Armourer’s ‘Prentices’.  Its central character is an English novelist, Mark Ambient, at loggerheads with his wife who ‘thinks a work of art ought to have a \\"purpose”' while he takes a more aesthetic view.  She lets their child die so he should not be contaminated by his father’s works.
[^2]: The same issue of the magazine also included George du Maurier, ‘Der Tod als Freund: A Poem. (from the French of Madame Necker)’.
