---
title: "To Christabel Rose Coleridge"
letter_iso_date: "1885-01-02"
letter_date: "Jan 2d [1885]"
location: "Elderfield, Otterbourne, Winchester."
manuscript: "MS Mrs Clare Roels/66"
post_id: 2797
letter_id: "to-christabel-rose-coleridge-111"
citation:
  type: article
  author:
    - family: Yonge
      given: Charlotte Mary
  editor:
    - family: Mitchell
      given: Charlotte
    - family: Jordan
      given: Ellen
    - family: Schinske
      given: Helen
  title: "To Christabel Rose Coleridge"
  container-title: "The Letters of Charlotte Mary Yonge"
  issued: "1885-01-02"
  url: "https://cmyonge.github.io/letters/2797-to-christabel-rose-coleridge-111"
---

::: {.letter-metadata}
**Date:** Jan 2d [1885]  
**From:** Elderfield, Otterbourne, Winchester.  
**Manuscript:** MS Mrs Clare Roels/66
:::

My dear [Christabel](people/person_329.qmd)

I should think on the whole that it was intended to decline the book except at your expense.  I do think the resemblance to [Don John](other_books/otherbook_930.qmd) is a disadvantage though you have treated it in such a different way.[^1]  And had not [Low](people/person_1992.qmd) something to do with Don John, either through [Good Words](organizations/other_73.qmd) or [Miss Ingelow](people/person_741.qmd).  I am on the whole afraid that as I see in the [Guardian](organizations/other_75.qmd) that Mr Mallock says that the age has got past the spirituality of Tennyson, so it is getting past the quiet style of domestic Churchey novels– not that there is much of that in [the Lot](other_books/otherbook_964.qmd)- but it is the undercurrent.[^2]  [Amethyst](other_books/otherbook_663.qmd) may do better, but I wouldn’t begin her – the book I mean – with the Sisterhood scene.  Shall you try anywhere else?

I should think [S T C](people/person_1667.qmd) was horribly difficult to do properly.-  The old unmitigated hero worship was one thing, and the Froude & Carlyle method another and to strike the balance between the two is uncommonly hard.[^3]

We have and are having a course of diversions for Christmas here-  a Band of Hope[^4] Tree comes off this evening

your affectionate
C M Yonge

---

[^1]: With envelope addressed to Miss C R Coleridge/ Eldon Lodge/ Torquay and postmarked Winchester 2 January 1885.
[^2]: Jean Ingelow, *Don John* (London, Sampson Low 1881), the plot of which resembled Christabel Coleridge’s story *A Lot with a Crook in it*.
[^3]: CMY refers to the discussion of Tennyson's poetry in the context of Victorian cultural change in W. H. Mallock's *Atheism and the Value of Life* (1884).
[^4]: James Anthony Froude, *History of the First Forty Years of Carlyle’s Life*  (1882) and *History of Carlyle’s Life in London* (1884) had caused great scandal and set new standards of biographical frankness.
[^5]: The United Kingdom Band of Hope Union was a children’s temperance organisation founded in 1855.
