---
title: "To an Unknown Person"
letter_iso_date: "1885-09-18"
letter_date: "[September 1885?]"
manuscript: "MS Girton College Cambridge, Yonge IX 4"
post_id: 2812
letter_id: "to-an-unknown-person-11"
citation:
  type: personal_communication
  author:
    - family: Yonge
      given: Charlotte Mary
  editor:
    - family: Mitchell
      given: Charlotte
    - family: Jordan
      given: Ellen
    - family: Schinske
      given: Helen
  title: "To an Unknown Person"
  container-title: "The Letters of Charlotte Mary Yonge"
  issued: "1885-09-02"
  url: "https://cmyonge.github.io/letters/2812-to-an-unknown-person-11"
---

::: {.letter-metadata}
**Date:** [September 1885?]  
**Manuscript:** MS Girton College Cambridge, Yonge IX 4
:::

. . . August and very dreary it was to see the beautiful rooms at Heaths Court with no mistress. I still believe that there will be a great awakening from the present blindness, and [Mary](people/person_351.qmd) . . . 

I think Winchester is a rock that binds its limpets fast - not a good simile either for the limpets do go off, only perhaps it is their affections that stay there. I have not near so much to care about there now, as in old times, only perhaps the dear Salisbury people may come back there.[^1] I believe the elders wish it, but the younger feel more present interest where they are.

I am very sorry you are lame - but I dare say you have plenty of work to do from your sofa. I wish you could see our woods the autumn tints are wonderful this year - and the Virginian creepers are gorgeous

Yours very sincerely
C M Yonge

---

[^1]: The top of  the first page is cut away, probably because of some reference to the Coleridge scandal, and what is left of  he first side crossed out.
[^2]: The letter seems to be connected to [Mildred Coleridge](people/person_17.qmd)'s marriage on 24 June 1885 and [George Moberly](people/person_1015.qmd)'s death on 6 July 1885.
[^3]: The widow and daughters of George Moberly, headmaster of Winchester College 1835-1866, and Bishop of Salisbury from 1869.
