---
title: "To Mary Elizabeth (Wormeley) Latimer"
letter_iso_date: "1886-06-01"
letter_date: "June 1st [1886?]"
location: "Elderfield Otterbourne"
manuscript: "MS Historical Society of Pennsylvania: Gratz Collection: Case 11, Box 10:British Literary Misc"
post_id: 2832
letter_id: "to-mary-elizabeth-wormeley-latimer-3"
citation:
  type: article
  author:
    - family: Yonge
      given: Charlotte Mary
  editor:
    - family: Mitchell
      given: Charlotte
    - family: Jordan
      given: Ellen
    - family: Schinske
      given: Helen
  title: "To Mary Elizabeth (Wormeley) Latimer"
  container-title: "The Letters of Charlotte Mary Yonge"
  issued: "1886-06-01"
  url: "https://cmyonge.github.io/letters/2832-to-mary-elizabeth-wormeley-latimer-3"
---

::: {.letter-metadata}
**Date:** June 1st [1886?]  
**From:** Elderfield Otterbourne  
**Manuscript:** MS Historical Society of Pennsylvania: Gratz Collection: Case 11, Box 10:British Literary Misc
:::

My dear [Mrs Latimer](people/person_846.qmd)

Thank you very much for your pleasant [Shakespeare book](other_books/otherbook_1005.qmd). 

I have read the first three divisions of it and enjoyed it once [?]. You should suggest to your audience the series of Shakespeare Tableaux, which I once saw. They were got up by Lady [Laura Ridding](people/person_1238.qmd) wife to the [bishop of Southwell](people/person_1237.qmd), who was then headmaster of Winchester college.[^1] She assigned one play to each of a set of different families and each group was exhibited three times with a little advance in the action. The best of all was the unveiling of Hermione, whose drapery was wonderfully made of a linen sheet most statue like and with an exceedingly finely face Paulina to unveil her.  Then Juliet on her tomb was very good.

Yours sincerely
C M Yonge

By the by (in a second edition) it could not have been Drayton’s [Polyolbion](other_books/otherbook_1006.qmd) that coincided with Shakespeare as to fairies for that is about the Rivers of England, but you must mean his [Nymphidia](other_books/otherbook_1007.qmd), a very funny fairy poem where Oberon, whose queen is Mab, and not Titania, is jealous of her flirtation with Pigwiggin a fairy knight. When they are going to fight, Pigwiggin

puts him on a coat of mail
Which was of a fish’s scale
That when his foe should him assail
No point should be prevailing
His rapier was a hornet’s sting
It was a very dangerous thing
For if it chanced to hurt the king
It would be long in healing.

Drayton was not born till 1563, and I am much inclined to think that unless both went to folk lore, he was the borrower. They were exact contemporaries a year between them

---

[^1]: 
[^2]: Elizabeth Wormeley Latimer, *Familiar talks on some of Shakespeare's Comedies* (Boston: Roberts 1886).
[^3]: The Rev George Ridding  (1828-1904), became bishop of Southwell in 1884;  he had married (1876), as his second wife, Lady Laura Palmer (1849-1939).
