---
title: "To Christabel Rose Coleridge"
letter_iso_date: "1887-04-07"
letter_date: "April 7th [1887?]"
location: "Elderfield"
manuscript: "MS Mrs Clare Roels/70"
post_id: 2855
letter_id: "to-christabel-rose-coleridge-113"
citation:
  type: article
  author:
    - family: Yonge
      given: Charlotte Mary
  editor:
    - family: Mitchell
      given: Charlotte
    - family: Jordan
      given: Ellen
    - family: Schinske
      given: Helen
  title: "To Christabel Rose Coleridge"
  container-title: "The Letters of Charlotte Mary Yonge"
  issued: "1887-04-07"
  url: "https://cmyonge.github.io/letters/2855-to-christabel-rose-coleridge-113"
---

::: {.letter-metadata}
**Date:** April 7th [1887?]  
**From:** Elderfield  
**Manuscript:** MS Mrs Clare Roels/70
:::

My dear [Christabel](people/person_329.qmd)

Many thanks. It will be the printers own fault if we are late for they are to keep holiday till Tuesday.  I think you are right as to [GFS](organizations/other_23.qmd)chiefly because there is a continual conjugating of the verb to worry, active & passive   I wish the Central would learn <u>not</u>   Men’s Societies dont  They have made all clergymen hate the concern!  I wish I could draw up a warning about it that would not go abroad, to the many, an ‘Ad GFS’ – like Ad Clercum’.  I like your next generation it is a puzzler – and very invidious, the real hitch being the absence of instructive code of honour and propriety where there is not gentle blood, which leads to untrustworthiness  If you happen to read that queer Jewish novel [Victims](other_books/otherbook_1025.qmd) you will see it well shewn in poor Vera only the Jew girl had it which is not natural[^1]

I confess I care for Jane more than the rest!  Could you in marble works country help me to a catastrophe.  I want Alexis- mooning – to let Fergus occasion a catastrophe that nearly kills Lord Rotherwood & other spectators seeing the quarries.[^2]  I fancy Alexis managing the telephone & Fergus sending a wrong order to blow up the dynamite when he was not attending.  Is it possible.

I have got a <u>he</u> changeling in my head-[^3]  not too like yours, for he is to be a Gentleman- and have to do with Mary Beatrice’s escape  He was not changed as Elfrida was (really) but his beauty was spoilt by troubles at his birth & his old nurse imbued the children & himself with the notion that he was an imp

your affte
C M Yonge

---

[^1]: ‘Theo Gift’, *Victims* (1887).
[^2]: This refers to CMY's novel *Beechcroft at Rockstone*, published in *MP* January 1887-December 1888.
[^3]: C.M.Yonge, *A Reputed Changeling* (1889).  Coleridge's changeling was in her novel 'A Lot with a Crook in it'.
