---
title: "To Frances Awdry"
letter_iso_date: "1887-10-22"
letter_date: "Oct 22d [1887?]"
location: "Elderfield"
manuscript: "MS Princeton University, Parrish Collection"
post_id: 2863
letter_id: "to-frances-awdry"
citation:
  type: article
  author:
    - family: Yonge
      given: Charlotte Mary
  editor:
    - family: Mitchell
      given: Charlotte
    - family: Jordan
      given: Ellen
    - family: Schinske
      given: Helen
  title: "To Frances Awdry"
  container-title: "The Letters of Charlotte Mary Yonge"
  issued: "1887-10-22"
  url: "https://cmyonge.github.io/letters/2863-to-frances-awdry"
---

::: {.letter-metadata}
**Date:** Oct 22d [1887?]  
**From:** Elderfield  
**Manuscript:** MS Princeton University, Parrish Collection
:::

My dear [Frances](people/person_82.qmd)

All I know about Juliana Coningsby is in the [Cameo](cmy_books/cmybook_213.qmd)of December 1886.[^1] I got it out of [Carte’s history](other_books/otherbook_1029.qmd) also [Knight](other_books/otherbook_1031.qmd)s, and they both took it from [the King’s own account](other_books/otherbook_1060.qmd) which Pepys wrote down at the time. The adventures were really more curious than Jane Lane’s and I have always wondered whether there were anything not told which prevented them from being made more of.[^2]  But Carte is too old to mince matters, and nobody would know if there were anything amiss about her, so I think she is safe. She took Charles from Trent to Charmouth and she had a pension on his restoration like Jane Lane. I am glad George Harris is all right again.[^3] Six families in Winchester started scarlet fever the same day, it was all traced to one dairy, and nobody else has caught it, and they are all well again

Your affectionate
C M Yonge

Don’t set up a story concerned with the rejoicings for the 7 Bishops, and the flight of Mary Beatrice[^4]

---

[^1]: There is an account of the escape of the future Charles II from pursuing Roundheads after the battle of Worcester in 1651 in the part of Cameos from English History* serialized in  *MP* (December 1886), 544: ‘This time he was to be supposed to be a young gentleman running away with an heiress, escaping from a cruel guardian. The lady was represented by Juliana Coningsby, a relation of Colonel Wyndham; and the feelings of a widow at Charmouth were appealed to for the runaway couple, who appeared in due time with Wilmot riding beside them.’
[^2]: At another stage of his escape Charles pretended to be a servant to Jane Lane.
[^3]: Perhaps [George Montagu Harris](people/person_2340.qmd), the son of CMY's cousin George Collyer Harris (1833-1874).
[^4]: No doubt because she was herself planning *A Reputed Changeling* (1889).
