---
title: "To Charlotte Anne Elizabeth Moberly?"
letter_iso_date: "1888-10-18"
letter_date: "[October 1888]"
manuscript: "MS location unknown.  Printed in [<i>Dulce Domum</i>](other_books/otherbook_122.qmd), 301-2."
post_id: 2894
letter_id: "to-charlotte-anne-elizabeth-moberly-3"
citation:
  type: personal_communication
  author:
    - family: Yonge
      given: Charlotte Mary
  editor:
    - family: Mitchell
      given: Charlotte
    - family: Jordan
      given: Ellen
    - family: Schinske
      given: Helen
  title: "To Charlotte Anne Elizabeth Moberly?"
  container-title: "The Letters of Charlotte Mary Yonge"
  issued: "1888-10-01"
  url: "https://cmyonge.github.io/letters/2894-to-charlotte-anne-elizabeth-moberly-3"
---

::: {.letter-metadata}
**Date:** [October 1888]  
**Manuscript:** MS location unknown.  Printed in [<i>Dulce Domum</i>](other_books/otherbook_122.qmd), 301-2.
:::

[To [Charlotte Anne Elizabeth Moberly](people/person_1024.qmd)

I am exceedingly enjoying those dear old times.[^1]  It is such a living over again of the dear golden age of our lives.  I have made a few notes in pencil.  . .  I quite dreaded the first wedding.  I keep it for my last hour before going to bed.  I think I must put in when all the children were found on the landing killing Oliver Cromwell; and [Alice](people/person_1025.qmd)mourning for the *beauty* of the old Hursley church.  It was strange to be reading it just at the passing of almost the last of the friends of those good old times.  I wonder if I shall see any of your people at Rownhams to-morrow?  There is the earthly farewell to a very long precious friendship. I was a growing girl when [Mr. Wilson](people/person_1541.qmd) was Hursley curate, all fun and brightness, and my father was so fond of him. [^2]  Did you know that when he accepted the curacy of Hursley he was told that he must make up his mind to its being the prevention of all promotion?  and you see that the canonry of Salisbury was all he ever had . . .

---

[^1]: She had been sent the MS of *Dulce Domum*, a memoir of the Moberlys’ life in Winchester, compiled by Annie Moberly.
[^2]: The Rev. Robert Francis Wilson (1808/9-8 Oct 1888), Vicar of Rownhams.
