---
title: "To Edward Augustus Freeman"
letter_iso_date: "1889-07-04"
letter_date: "July 4th 1889"
location: "Elderfield"
manuscript: "MS John Rylands Library, Manchester, FA1/7/840"
post_id: 2910
letter_id: "to-edward-augustus-freeman-15"
citation:
  type: article
  author:
    - family: Yonge
      given: Charlotte Mary
  editor:
    - family: Mitchell
      given: Charlotte
    - family: Jordan
      given: Ellen
    - family: Schinske
      given: Helen
  title: "To Edward Augustus Freeman"
  container-title: "The Letters of Charlotte Mary Yonge"
  issued: "1889-07-04"
  url: "https://cmyonge.github.io/letters/2910-to-edward-augustus-freeman-15"
---

::: {.letter-metadata}
**Date:** July 4th 1889  
**From:** Elderfield  
**Manuscript:** MS John Rylands Library, Manchester, FA1/7/840
:::

My dear [Mr Freeman](people/person_523.qmd), 	

Your letter followed me, on an expedition to Salisbury, where I have been seeing ‘the moot’. They had a moot there with the speakers at the summer house, and the people on the terraces, before one of the Elections, and the voices were perfectly heard. The art of hearing has been lost or rather that of making places to be heard in. 

I have changed all the peas into pease.[^1] I wonder who put the E into peacock - it must have been under the impression that the eyes in the tail were glorified peas -  and the phonetic people would turn out the a and upset the connection with pavo. [Mrs Coode](people/person_2385.qmd) wrote to me that they are going to keep a centenary of Hannah at Cheddar on the 22d of August, so I have been spurring the [NS](organizations/other_32.qmd) to get the book out by that time. In my room at Salisbury there was a wardrobe which I flatter myself [Hannah More](people/person_1836.qmd)must have had when staying with Bishop Fisher.[^2]

[The Bishop](people/person_1567.qmd) is opening and refitting Bishop Poore’s old 13th century hall, with a central pillar.[^3] I am sorry Barrow was a JP. I thought him of a lower order 	

Yours sincerely
C M Yonge

---

[^1]: CMY had visited Freeman in Somerset to gather material about Hannah More for *The Cunning Woman's Grandson*, which is the book discussed here.  He had criticized the MS.
[^2]: John Fisher (1748–1825) was bishop of Salisbury from 1807.
[^3]: The Rt. Rev. John Wordsworth was bishop of Salisbury 1885-1911. Richard Poore (d.1237) was bishop of Salisbury 1217-28 and rebuilt the cathedral.
