---
title: "To Arthur Donald Innes"
letter_iso_date: "1889-07-13"
letter_date: "July 13th1889"
manuscript: "MS Girton College Cambridge, Yonge IV 12"
post_id: 2912
letter_id: "to-arthur-donald-innes-26"
citation:
  type: article
  author:
    - family: Yonge
      given: Charlotte Mary
  editor:
    - family: Mitchell
      given: Charlotte
    - family: Jordan
      given: Ellen
    - family: Schinske
      given: Helen
  title: "To Arthur Donald Innes"
  container-title: "The Letters of Charlotte Mary Yonge"
  issued: "1889-07-13"
  url: "https://cmyonge.github.io/letters/2912-to-arthur-donald-innes-26"
---

::: {.letter-metadata}
**Date:** July 13th1889  
**Manuscript:** MS Girton College Cambridge, Yonge IV 12
:::

Dear [Mr Innes](people/person_744.qmd)

Next year’s programme is my own [Two Penniless Princesses](cmy_books/cmybook_216.qmd) - historical longish chapters. Miss [Agnes Giberne](people/person_561.qmd) has promised a story - and the [Storm in a Teacup](other_books/otherbook_1085.qmd) has to go on another half year[^1]  I tried doubling the chapters, but there was not room. I think it is a mistake to sacrifice the story to the volume, as often in those I read, I see the development has been injured to get it to the prescribed length.

But I should like to see [the Molyneuxes](other_books/otherbook_1087.qmd) unless they are quite bound to begin in January.[^2]

I had been thinking of writing to you about translating and abridging Madame Necker De Saussure’s [Education Progressive](other_books/otherbook_1088.qmd) really the best book on Education I know. It is too long to be done entire, but it is admirable in the practical part and the [Mother’s Union](organizations/other_31.qmd) would recommend it I know, indeed it has been doing so by the cumbrous French edition I could undertake it easily, and get it into shape for use.

[The Guiding Principle in Art](other_books/otherbook_1086.qmd) is by 

[Mrs Evelyn Heathcote](people/person_662.qmd)[^3]
Sparsholt Rectory
Winchester

Yours truly
C M Yonge

---

[^1]: Agnes Giberne (1845-1939) was a prolific author of science textbooks and fiction, but she does not seemed to have contributed to *MP* at this time.
[^2]: ‘E.N. Leigh Fry’ [Ella Napier Lefroy], *Shreds and Patches, or, Passages from the Lives of the Molyneuxes* (London, W.Smith and Innes, 1890) was not serialized in *MP*.
[^3]: Grace Hussey married (1876) the Rev. Evelyn Dawsonne Heathcote (1844-1908), vicar of Sparsholt, fifth son of Sir William Heathcote.
