---
title: "To Anne Yonge"
letter_iso_date: "1837-00-00"
letter_date: "[1837]"
manuscript: "MS location unknown.  This fragment printed by Coleridge, <i>Life</i>, 140."
post_id: 2934
letter_id: "to-anne-yonge-3"
citation:
  type: personal_communication
  author:
    - family: Yonge
      given: Charlotte Mary
  editor:
    - family: Mitchell
      given: Charlotte
    - family: Jordan
      given: Ellen
    - family: Schinske
      given: Helen
  title: "To Anne Yonge"
  container-title: "The Letters of Charlotte Mary Yonge"
  issued: "1837-01-01"
  url: "https://cmyonge.github.io/letters/2934-to-anne-yonge-3"
---

::: {.letter-metadata}
**Date:** [1837]  
**Manuscript:** MS location unknown.  This fragment printed by Coleridge, <i>Life</i>, 140.
:::

I wish [you](people/person_1582.qmd) could see [my young ladies](cmy_books/cmybook_1.qmd), who have advanced to copy-books since they were at [Puslinch](organizations/other_123.qmd).  All their uncles, aunts, and cousins are staying with them, and in the midst of all poor Rosalie’s horse threw her, and she had a strain which is keeping her on the sofa.  One evening when everybody but her and her friend Isabella were gone to see the Eddystone, they heard a carriage come to the door, and after some time up came the man with a card on which was written Colonel Melville.  He was their Uncle Frederick who had gone out to India five years before, and in coming back was supposed to have been drowned, as nothing has been heard of him since.[^1]

---

[^1]: This was the story which was afterwards printed and sold as *Le Château de Melville* (1838).
