---
title: "To Mary Anne Dyson"
letter_iso_date: "1846-12-18"
letter_date: "Sunday [December] 1846."
manuscript: "MS location unknown.  Printed in Coleridge, <i>[Life](other_books/otherbook_40.qmd)</i> 156-157"
post_id: 2958
letter_id: "to-mary-anne-dyson-2"
citation:
  type: personal_communication
  author:
    - family: Yonge
      given: Charlotte Mary
  editor:
    - family: Mitchell
      given: Charlotte
    - family: Jordan
      given: Ellen
    - family: Schinske
      given: Helen
  title: "To Mary Anne Dyson"
  container-title: "The Letters of Charlotte Mary Yonge"
  issued: "1846-12-01"
  url: "https://cmyonge.github.io/letters/2958-to-mary-anne-dyson-2"
---

::: {.letter-metadata}
**Date:** Sunday [December] 1846.  
**Manuscript:** MS location unknown.  Printed in Coleridge, <i>[Life](other_books/otherbook_40.qmd)</i> 156-157
:::

My dear [Driver](people/person_464.qmd)[^1]
I never expected [Henrietta](cmy_books/cmybook_11.qmd)[^2]  to produce such pretty fruits. I am delighted with it. I wish you would give Linny[^3] *[Sintram](other_books/otherbook_102.qmd)*[^4] to read, and see what she would make of it. Ours are hearing it with great satisfaction. The Tree was very successful; the gentlemen would come to look on, which made the children very silent, but they were exceedingly happy. [Mr. Wither](people/person_1544.qmd) cut down the fruit, and there was much fun, They had *calf* manners exactly, merry and joyous, whispering to each other, and never pushing forward, altogether very nice. They had two pomegranates for tea, which Fanny told them came from Spain; then they looked at certain Indian birds of which they are never tired, and at my shells, some of which were so little that Lucy marvelled how a fish could be got into them. And the evening was filled up with dissected maps.

---

[^1]: CMY called Dyson ‘Driver’ and signed herself ‘Slave.’
[^2]: CMY’s story *Henrietta’s Wish, or, Domineering: A Tale*, which was serialized in the *Churchman’s Companion*, January 1849-May 1850, and published in volume form in 1850.
[^3]: One of Dyson’s pupils, who were nicknamed ‘the calves’.
[^4]: Friedrich, Baron de la Motte Fouqué, *Sintram und seine Gefährten* (1811).  The Tractarians had a cult of La Motte Fouqué;  Dyson’s own *Ivo and Verena, or, The Snowdrop* (London: Burns 1842) is a children’s version of of one of his allegorical romances.
