---
title: "To Mary Anne Dyson"
letter_iso_date: "1850-00-00"
letter_date: "[1850]"
manuscript: "MS location unknown.  Printed in Coleridge, <i>Life</i> 161."
post_id: 2968
letter_id: "to-mary-anne-dyson-8"
citation:
  type: personal_communication
  author:
    - family: Yonge
      given: Charlotte Mary
  editor:
    - family: Mitchell
      given: Charlotte
    - family: Jordan
      given: Ellen
    - family: Schinske
      given: Helen
  title: "To Mary Anne Dyson"
  container-title: "The Letters of Charlotte Mary Yonge"
  issued: "1850-01-01"
  url: "https://cmyonge.github.io/letters/2968-to-mary-anne-dyson-8"
---

::: {.letter-metadata}
**Date:** [1850]  
**Manuscript:** MS location unknown.  Printed in Coleridge, <i>Life</i> 161.
:::

I was thinking of the [Southey](people/person_1722.qmd) and [Scott](people/person_1672.qmd) controversy[^1], and wondering if the self-consciousness of the men had anything to do with the personality of their heroes, whether Sir Walter went any deeper into himself than into the rest of mankind, and whether Southey from looking at the outside of himself con amore did not get inside of other humans too.  I always do think it a strange thing how one can care so much personally for that Ladurlad in [Kehama](other_books/otherbook_220.qmd) in the midst of the impossibilities and verses I don't like at all.  As to [Thalaba](other_books/otherbook_151.qmd) I do like it almost every way; the opening scene dwells on one with a sort of horror that shows its power, and the Angel of Death, how very fine that is.  But I think Southey treated the Catholic faith, just as he did the idol mythology, as a framework, and not in the allegorical way in which [Fouqué](other_books/otherbook_102.qmd) makes the mythology serve to shadow truth, and therefore it does not satisfy me, there is a falseness about it all, he was not in earnest.

Yes, prejudices are very precious things, in Church matters especially I suppose, but I think history of England takes care of them because the R[oman]. C[atholic].'s are always the enemy, and the burnings and Gunpowder Plot will keep an English mind well prejudiced, so that I think you might afford to soften a little.

---

[^1]: This probably refers to a dispute among the Dysons and Yonges as to the relative merits of the two writers.  The cult of Scott’s novels and poetry was very important to the Tractarians;  Southey’s poetry was also much admired in [Hursley](organizations/other_127.qmd) and [Dogmersfield](organizations/other_121.qmd).  Mary Anne Dyson’s brother was known playfully in their circle as the Simorg and their house as the Simorg’s Nest or the Nest in allusion to Southey’s *Thalaba the Destroyer* (1801), VIII, 17: ‘In Kaf the Simorg hath his dwelling place, /The all-knowing Bird of Ages . . .’
