---
title: "The Reverend John Keble to Charlotte Mary Yonge"
letter_iso_date: "1851-06-30"
letter_date: "30 June, 1851."
location: "Hursley"
manuscript: "MS location unknown.  Printed in <i>Musings over the Christian Year</i> xxvi-xxvii."
post_id: 2976
letter_id: "the-reverend-john-keble-to-charlotte-mary-yonge-2"
citation:
  type: article
  author:
    - family: Yonge
      given: Charlotte Mary
  editor:
    - family: Mitchell
      given: Charlotte
    - family: Jordan
      given: Ellen
    - family: Schinske
      given: Helen
  title: "The Reverend John Keble to Charlotte Mary Yonge"
  container-title: "The Letters of Charlotte Mary Yonge"
  issued: "1851-06-30"
  url: "https://cmyonge.github.io/letters/2976-the-reverend-john-keble-to-charlotte-mary-yonge-2"
---

::: {.letter-metadata}
**Date:** 30 June, 1851.  
**From:** Hursley  
**Manuscript:** MS location unknown.  Printed in <i>Musings over the Christian Year</i> xxvi-xxvii.
:::

My dear Charlotte,
I hope I have not put you out by keeping [this](cmy_books/cmybook_33.qmd) so long.  I have been rather more busy than usual.  This is an interesting matter, and I wish I had more time and knowledge for it.[^1] It will do very well as you have put it.  But against a reprint, or with a view to a supplementary dialogue, it may be well to consider (what is implied in the word *Moral*, which I have inserted in one place) that Religion begins when we believe that *God is good*, and that the prevailing form of irreligion in the world has not been disbelief of a *natural* Governor, but a notion of an Evil Principle in one form or another.  See Bp. Butler’s [Analogy](other_books/otherbook_28.qmd), part i.[^2]

It occurred to me whether, when the ladies quote Greek, they had not better say they have heard their fathers and brothers say things.

Always yours affectionately
[J. K.](people/person_798.qmd)

---

[^1]: CMY introduced the letter as ‘called forth by that conversation on the first article of the Creed’, ‘The Creed’ No VII in the series ‘Conversations on the Catechism’, which appeared in *MP* 2 (July 1851)5-16.  It was her practice to submit these articles to Keble for approval.
[^2]: Joseph Butler, *The Analogy of Religion, Natural and Revealed, to the Constitution and Course of Nature* (1736).
