---
title: "To Alice Arbuthnot Moberly"
letter_iso_date: "1853-07-18"
letter_date: "[July 1853]"
manuscript: "MS location unknown.  Printed in <i>[Dulce Domum](other_books/otherbook_122.qmd)</i> 106-7."
post_id: 3013
letter_id: "to-alice-arbuthnot-moberly-5"
citation:
  type: article
  author:
    - family: Yonge
      given: Charlotte Mary
  editor:
    - family: Mitchell
      given: Charlotte
    - family: Jordan
      given: Ellen
    - family: Schinske
      given: Helen
  title: "To Alice Arbuthnot Moberly"
  container-title: "The Letters of Charlotte Mary Yonge"
  issued: "1853-07-18"
  url: "https://cmyonge.github.io/letters/3013-to-alice-arbuthnot-moberly-5"
---

::: {.letter-metadata}
**Date:** [July 1853]  
**Manuscript:** MS location unknown.  Printed in <i>[Dulce Domum](other_books/otherbook_122.qmd)</i> 106-7.
:::

My dear [Alice](people/person_1025.qmd),
The *Times* was quite right, [Lucien](people/person_1733.qmd) was at the camp,[^1] though I cannot remember him.  [Montebello](people/person_1735.qmd) told [Lord Seaton](people/person_313.qmd) that he is very sorry to see our troops in such excellent order.  [The Queen](people/person_1694.qmd) looked in great good-humour, and was determined to see the men have their dinner.  She came to Virginia Water with [Prince Albert](people/person_1736.qmd), who was sneezing and looking as if he had the measles.  Lord and [Lady Seaton](people/person_314.qmd) are at the Palace again to-night.[^2]  They have a great luncheon in  marquees to-morrow.  So much for camp news.   . . .We have had a famous party from Fieldhouse;  you should have seen [Robert](people/person_1021.qmd), [Johnnie](people/person_1017.qmd), [Emily](people/person_81.qmd)[^3], and Rover all at tea at the little round table.  I wish you could have been at Hursley yesterday.  We had a nice sight of the [Bishop](people/person_578.qmd) and [Mrs. Gray](people/person_579.qmd)[^4] in the Vicarage after service, and Mrs. Gray brought down some beautiful drawings of the Table Mountain  . . .

---

[^1]: In May 1853 an armed camp on Chobham Common, commanded by Field-Marshal Lord Seaton, was set up.  CMY herself visited it with several of her cousins.  *The Times* (4 July 1853) reported manoevres witnessed by the Queen, Prince Albert, the visiting Prince Lucien Bonaparte (1813-1891) and officers in his suite, who probably included Napoléon, second Duc de Montebello (1801-1874).
[^2]: There had been a State Ball on 1 July 1853.
[^3]: Robert Campbell Moberly (1845-1903), John Cornelius Moberly (b.1848 ) and Frances Emily Moberly (1844-1921).
[^4]: The Bishop of Cape Town, the Rt. Rev. Robert Gray (1809-1874), and his wife Sophia (Myddleton) Gray were visiting the Kebles.
