---
title: "Frances Mary Yonge to the Reverend John Yonge"
letter_iso_date: "1854-03-03"
letter_date: "Friday [3 March 1854]"
manuscript: "MS Plymouth and West Devon Record Office 308/255"
post_id: 3032
letter_id: "frances-mary-yonge-to-the-reverend-john-yonge-2"
citation:
  type: personal_communication
  author:
    - family: Yonge
      given: Charlotte Mary
  editor:
    - family: Mitchell
      given: Charlotte
    - family: Jordan
      given: Ellen
    - family: Schinske
      given: Helen
  title: "Frances Mary Yonge to the Reverend John Yonge"
  container-title: "The Letters of Charlotte Mary Yonge"
  issued: "1854-03-03"
  url: "https://cmyonge.github.io/letters/3032-frances-mary-yonge-to-the-reverend-john-yonge-2"
---

::: {.letter-metadata}
**Date:** Friday [3 March 1854]  
**Manuscript:** MS Plymouth and West Devon Record Office 308/255[^1]
:::

My dear [Mr. Yonge](people/person_1623.qmd)
Incapable as [I](people/person_1606.qmd) am of doing any thing today, to do nothing is worst of all, so I will try to thank you for sending me two comforters and for enduring for the sake of those who are anxious about you, the great grief and sorrow I know it is to you not to join the family and friends tomorrow[^2]

I have many obligations to you, and amongst them that of having given me lessons how to endure sorrow and now I am sure I can say that God’s Mercies have followed me all the days of my life and perhaps more sensibly through the last week than ever before.[^3]  The many things great and small that have been ordered so as to spare us as much as possible, and my having been able to wait upon [him](people/person_1631.qmd), to the last moment and not to have broken down yet make me hope yet to be helped in what is to come.

I think I can bear to have seen him cut down in his full strength and in the midst of his usefulness much better than to see him linger in broken health and depressed spirits, unable to do any thing to help and yet to be vexed when things went wrong.

Then that he lived to form Charlotte’s character and lift her such a sound and true helper to me, and spent his last strength in[Julian](people/person_1624.qmd)’s outfit and sending him away to see something of the realities of the profession he has chosen and which he will not quit with my approbation through any considerations for me, for I think it would be very bad for him to sit down here with just enough to be idle upon till some years have passed over his head.  I am very glad he had one last look upon his Father though it was not returned  

[Colonel Wilbraham](people/person_1515.qmd) has undertaken to seek him out and try to comfort him and it will be a balm to him to see one who knew what his home was.

With my children you have been always next to a father and they will not feel utterly desolate while you are spared to them, and to me you are most valuable

your affec Sister
F M Yonge

---

[^1]: Black-edged paper. Endorsed in another hand ‘Feby: 1854’.
[^2]: His children [Anne Yonge](people/person_1582.qmd) and [Duke Yonge](people/person_1599.qmd) had come to stay with the bereaved family in Otterbourne and attend the funeral of WCY which took place on Saturday 4 March 1854.
[^3]: John Yonge’s wife, [Alethea](people/person_1580.qmd), FMY’s half-sister, had died in 1844.
