---
title: "To Anna Butler"
letter_iso_date: "1854-04-20"
letter_date: "April 20th [1854]"
location: "Otterbourn"
manuscript: "MS Mrs Caroline Fairclough/4"
post_id: 3040
letter_id: "to-anna-butler-5"
citation:
  type: article
  author:
    - family: Yonge
      given: Charlotte Mary
  editor:
    - family: Mitchell
      given: Charlotte
    - family: Jordan
      given: Ellen
    - family: Schinske
      given: Helen
  title: "To Anna Butler"
  container-title: "The Letters of Charlotte Mary Yonge"
  issued: "1854-04-20"
  url: "https://cmyonge.github.io/letters/3040-to-anna-butler-5"
---

::: {.letter-metadata}
**Date:** April 20th [1854]  
**From:** Otterbourn  
**Manuscript:** MS Mrs Caroline Fairclough/4
:::

My dear [Miss Butler](people/person_237.qmd)
Many thanks for Basle[^1], which will do very well.  I am only sorry it had to be finished at an inconvenient time. And many thanks for[Aunt Louisa](other_books/otherbook_242.qmd) altogether.  She has been a very pretty pleasant portion of the [Monthly Packet](organizations/other_52.qmd).  I am sorry all the pages in the Packet were settled so that I could not get in even a verse of Gertrude, one of the people I most admire.

When you like to send me anything further, I shall be very glad, though I am afraid to promise speedy insertion, as there are some subjects that <u>must</u> be finished off in this next volume.  I will tell [Mr Mozley](people/person_1065.qmd) to send a proof of this as soon as possible.  

The errors in the names are a sore subject.  I generally look the revise over again with your corrections and sometimes find the printers have mistaken even these and an Ingeham for Ingelram we had both missed.

Thank you for the kind sympathy you express, there has been much soothing in the kind feeling so many have expressed[^2]

yours sincerely
C M Yonge

---

[^1]: The final chapter of *Aunt Louisa’s Travels*, published in MP 7 (June 1854) 461-72.
[^2]: [William Crawley Yonge](people/person_1631.qmd) died on 26 February 1854.
