---
title: "To Elizabeth Roberts"
letter_iso_date: "1855-02-16"
letter_date: "Febry 16th [1855]"
location: "Otterbourn"
manuscript: "MS Huntington Library: Yonge Letters"
post_id: 3059
letter_id: "to-elizabeth-roberts-37"
citation:
  type: personal_communication
  author:
    - family: Yonge
      given: Charlotte Mary
  editor:
    - family: Mitchell
      given: Charlotte
    - family: Jordan
      given: Ellen
    - family: Schinske
      given: Helen
  title: "To Elizabeth Roberts"
  container-title: "The Letters of Charlotte Mary Yonge"
  issued: "1855-02-16"
  url: "https://cmyonge.github.io/letters/3059-to-elizabeth-roberts-37"
---

::: {.letter-metadata}
**Date:** Febry 16th [1855]  
**From:** Otterbourn  
**Manuscript:** MS Huntington Library: Yonge Letters[^1]
:::

My dear [Madam](people/person_1243.qmd),
I have delayed thanking you for [Lichfield](other_books/otherbook_244.qmd) till I could send you the proof of Durham. Lichfield is exceedingly interesting, and quite a proof that it is our own Mother Church that we can best describe. The whole history and description of the town are delightful, and I am glad you did not leave out[Dr Johnson](people/person_1760.qmd) whom I do not think it is the habit of these days to respect as he deserves. I cannot remember whether you said Canterbury was one of the Cathedrals you know. If not, [a lady](people/person_567.qmd) has offered to undertake it, and though I should prefer having all the Cathedrals by one hand, it would be better to insert a different one than to leave out any so important as Canterbury. Winchester I could describe myself, as my own, and Salisbury I know just well enough to be able to get it up for the purpose. Exeter and Chichester I could also get done in case you do not know them well enough.

I could never feel that a Gothic Cathedral had any signification otherwise than that made out in Mr [Isaac Williams](people/person_1523.qmd)’ poem of ‘The Cathedral’, a sort of visible emblem of the Christian faith, and surely it is on this that the appropriateness of the different details depends. How far this was present to the minds of the architects is another question, which can hardly be answered. I do not suppose it was by any means consistent or conscious, but surely the Same who instructed Bezaleel and Solomon, may have guided our mediæval builders to raise allegories in stone as His Temples.[^2]

I am very sorry to hear that you are still suffering I fear this strangely lengthened frost is not in your favour. For my own part, I enjoy the clear bracing, and the power of taking long walks, but it is sad to think how much distress it must occasion. I suppose you cannot attempt going out, but I sincerely hope that this long nursing of yourself will ultimately prove beneficial. You must not hurry yourself with the Cathedrals, I have enough to last some time only please send this proof when corrected, on to Derby

Yours sincerely

C M Yonge

---

[^1]: Black-edged paper.
[^2]: 2 Chronicles 1:5.
