---
title: "The Reverend John Keble to Charlotte Mary Yonge"
letter_iso_date: "1855-06-29"
letter_date: "St. Peter’s Day [29 June], 1855."
location: "H.V.,"
manuscript: "MS location unknown.  These extracts printed in <i>[Musings over the Christian Year](cmy_books/cmybook_88.qmd)</i> xxxix."
post_id: 3069
letter_id: "the-reverend-john-keble-to-charlotte-mary-yonge-4"
citation:
  type: article
  author:
    - family: Yonge
      given: Charlotte Mary
  editor:
    - family: Mitchell
      given: Charlotte
    - family: Jordan
      given: Ellen
    - family: Schinske
      given: Helen
  title: "The Reverend John Keble to Charlotte Mary Yonge"
  container-title: "The Letters of Charlotte Mary Yonge"
  issued: "1855-06-29"
  url: "https://cmyonge.github.io/letters/3069-the-reverend-john-keble-to-charlotte-mary-yonge-4"
---

::: {.letter-metadata}
**Date:** St. Peter’s Day [29 June], 1855.  
**From:** H.V.,  
**Manuscript:** MS location unknown.  These extracts printed in <i>[Musings over the Christian Year](cmy_books/cmybook_88.qmd)</i> xxxix.
:::

My dear Charlotte,
We shall send [K.Charles](other_books/otherbook_249.qmd) back to-morrow or the next day, with many thanks.[^1]

It is very interesting, but [I](people/person_798.qmd) own I think the conclusion rather lame and impotent, and I think most people would consider the Marquis as the hero of the Conference.

I send 4 or 5 copies of our Missionary notice for Wednesday, for those who may be supposed likely to have interest enough in the work to make an offering . . .

Always [your Mother](people/person_1606.qmd)’s and yours very affly,
J. K.

---

[^1]: CMY glossed the letter thus in *Musings*: ‘There is one that reminds me of his having tried to find some book in which the Roman controversy was put in an easy and sound form.  There was some joking between us on the controversy Miss Olivia Primrose had read, being that between Will Atkins and his wife in ‘Robinson Crusoe,’  and it ended in my borrowing for him a book containing the curious argument between King Charles I. and the Marquis of Worcester.’   The reference is to Oliver Goldsmith, *The Vicar of Wakefield* (1766), Chapter 7: ‘ “I have read a great deal of controversy. I

have read the disputes between Thwackum and Square; the controversy between Robinson Crusoe and Friday the savage, and I am now employed in reading the controversy in Religious Courtship.”’   The borrowed book was  *Certamen Religiosum: or, a Conference between His late Majestie Charles King of England, and Henry late Marquess and Earl of Worcester, concerning religion; at His Majesties being at Raglan Castle, 1646. Wherein the maine differences, now in controversie, between the Papists and the Protestants is no lesse briefly than accuratly discuss’d and bandied* (1649);  and the supposed participants [Charles I](people/person_1768.qmd) and [Henry Somerset, fifth Earl and first Marquess of Worcester](people/person_1769.qmd) (1577–1646).
