---
title: "To Ann Maria Carter Smith"
letter_iso_date: "1856-12-09"
letter_date: "Decr 9th [1856]"
location: "Otterbourn"
manuscript: "MS Westcountry Studies Library, Exeter/ Yonge 1856/4"
post_id: 3090
letter_id: "to-ann-maria-carter-smith-7"
citation:
  type: personal_communication
  author:
    - family: Yonge
      given: Charlotte Mary
  editor:
    - family: Mitchell
      given: Charlotte
    - family: Jordan
      given: Ellen
    - family: Schinske
      given: Helen
  title: "To Ann Maria Carter Smith"
  container-title: "The Letters of Charlotte Mary Yonge"
  issued: "1856-12-09"
  url: "https://cmyonge.github.io/letters/3090-to-ann-maria-carter-smith-7"
---

::: {.letter-metadata}
**Date:** Decr 9th [1856]  
**From:** Otterbourn  
**Manuscript:** MS Westcountry Studies Library, Exeter/ Yonge 1856/4[^1]
:::

My dear [Madam](people/person_263.qmd)
When I wrote my first letter, I must have been under some hallucination that 52 shillings was £2 2. instead of  £2.12. but I am glad the mistake was there instead of in the cheque.  Your pretty [Household Record](other_books/otherbook_259.qmd) came safely this morning, and I have read nearly to the end with much pleasure. I think I like it better than [Wishop](other_books/otherbook_257.qmd) though not quite so well as the [Thorns and Roses](other_books/otherbook_253.qmd). Its charm is the seeming so very like life from the quietness and simplicity.  I hope Wishop [will begin](organizations/other_52.qmd) in April or March, but I cannot yet make quite sure.

The Copyright of all is your own, with [our small pay](organizations/other_102.qmd). I am sure it would not be sufficient to buy the copyright, and I hope some day, your tales may make a pretty volume.  Thanks for the permission to reveal the authorship to [Miss Emily Taylor](people/person_1397.qmd).  I have no doubt it will be safe with her.  I do not know whether I let you to suppose that I prefer short tales to longer ones.  I do not think that is the case, it only happened that the shorter one fitted the last number of the year better.  I never could write a short story myself, and so have perhaps the more respect for the art of getting much into brief space

yours truly
C M Yonge

---

[^1]: In envelope addressed to Miss A Carter Smith/ Stepney Rectory/ London and postmarked Winchester  9 December 1856 and 10 December 1856.
