---
title: "To Ann Maria Carter Smith"
letter_iso_date: "1856-12-22"
letter_date: "Decr 22d [1856]"
location: "Otterbourn"
manuscript: "MS Westcountry Studies Library, Exeter/ Yonge 1856/5"
post_id: 3092
letter_id: "to-ann-maria-carter-smith-8"
citation:
  type: personal_communication
  author:
    - family: Yonge
      given: Charlotte Mary
  editor:
    - family: Mitchell
      given: Charlotte
    - family: Jordan
      given: Ellen
    - family: Schinske
      given: Helen
  title: "To Ann Maria Carter Smith"
  container-title: "The Letters of Charlotte Mary Yonge"
  issued: "1856-12-01"
  url: "https://cmyonge.github.io/letters/3092-to-ann-maria-carter-smith-8"
---

::: {.letter-metadata}
**Date:** Decr 22d [1856]  
**From:** Otterbourn  
**Manuscript:** MS Westcountry Studies Library, Exeter/ Yonge 1856/5[^1]
:::

My dear [Madam](people/person_263.qmd)
Many thanks for [Wishop](other_books/otherbook_257.qmd), which looks much improved by the omissions.

The M P was [Sir William Heathcote](people/person_669.qmd) MP for Oxford, perhaps you will even better like to hear that [Mr Keble](people/person_798.qmd) could not help listening to the [Thorns and Roses](other_books/otherbook_253.qmd) with great interest in the middle of his work.  I have put out the beginning of Wishop for March, but I cannot make sure of it, as there is a short story which must come in in Lent, and I cannot tell what room there may be. Will you be kind enough to convey my thanks to [your sister](people/person_71.qmd) for the note and proof received this morning.  It is hardly worth while to trouble her with a note merely to express my thanks.

yours truly
C M Yonge

I forgot to add my thanks for the return of the postage stamps.

If ever Mrs Atkinson finds time for Tradition 6th it will be welcome, but I never reckon on contributors after marriage - like the inspectors of schools who complain that so many school-mistresses 'yearly are lost to the profession'  by marriage[^2]

---

[^1]: Envelope addressed to Miss Anne C Smith/ Stepney Rectory/ London and postmarked Winchester 23 Dec  and on reverse 1856
[^2]: Ann Carter Smith's recently-married sister Frances Atkinson,  paid for contributions to *MP*, was evidently  the author of the five articles on ‘Traditions of Norway’ *MP* (July1855-February 1857), signed 'S. R. L.'  The Carter Smiths had lived in Norway.
