---
title: "To Ann Maria Carter Smith"
letter_iso_date: "1857-12-07"
letter_date: "Decr 7th 1857"
manuscript: "MS Westcountry Studies Library, Exeter/ Yonge 1857/5"
post_id: 3114
letter_id: "to-ann-maria-carter-smith-14"
citation:
  type: personal_communication
  author:
    - family: Yonge
      given: Charlotte Mary
  editor:
    - family: Mitchell
      given: Charlotte
    - family: Jordan
      given: Ellen
    - family: Schinske
      given: Helen
  title: "To Ann Maria Carter Smith"
  container-title: "The Letters of Charlotte Mary Yonge"
  issued: "1857-12-07"
  url: "https://cmyonge.github.io/letters/3114-to-ann-maria-carter-smith-14"
---

::: {.letter-metadata}
**Date:** Decr 7th 1857  
**Manuscript:** MS Westcountry Studies Library, Exeter/ Yonge 1857/5[^1]
:::

My dear [Miss Smith](people/person_263.qmd)
It is very odd to send the money in two orders, but when I sent on Saturday the Post Office or I contrived to make a blunder, and the Order arrived for less than [your due](organizations/other_102.qmd), so I am afraid you must have the trouble of signing both of these.  £1.19 is for the [Royal Household](other_books/otherbook_262.qmd), with many thanks, and I have ventured to add a pound for your district if you will be kind enough so to apply it.  I dread to hear that the [Mrs Adams](people/person_11.qmd) in whom you fear a disappointment is the nice woman with the sons whom you call Mrs Thompson in the story.  I am inclined to think I had better send you the last chapter, and then you can judge for yourself what to do to lessen the abruptness.  I am not sure that if the festival at Greenwich had come last instead of penultimate, it would not have let it down more easily, instead of feeling oneself as boys would say brought up all standing, but I am sure you are the best judge of how to finish your own work as a work of art.

I own to thinking the funeral pall and its spangles a very awkward simile, but I believe that is the meaning.[^2]  Someday perhaps I may talk to [Mr Keble’s sister](people/person_796.qmd) about it, and get at more of the intention through her.

I am surprised at the proportion of blankets that come back usable again.  What a comfort they must be, and all the more from not being worn out in the summer

yours sincerely
C M Yonge

---

[^1]: With envelope addressed to Miss A Smith/ Stepney Rectory/ London and postmarked Winchester 8 December and London 9 December 1857.
[^2]: John Keble, *The Christian Year*  ‘Twenty-third Sunday after Trinity’, 29-32: ‘For dreary were this earth, if earth were all,/ Tho' brightened oft by dear Affection's kiss; -/ Who for the spangles wears the funeral pall?/ But catch a gleam beyond it, and 'tis bliss.’
