---
title: "To the Reverend William Upton Richards"
letter_iso_date: "1858-11-23"
letter_date: "Novr 23d 1858"
location: "Otterbourne, Winchester."
manuscript: "MS Columbia University Library, New York: Yonge Coll"
post_id: 3120
letter_id: "to-the-reverend-upton-richards"
citation:
  type: personal_communication
  author:
    - family: Yonge
      given: Charlotte Mary
  editor:
    - family: Mitchell
      given: Charlotte
    - family: Jordan
      given: Ellen
    - family: Schinske
      given: Helen
  title: "To the Reverend William Upton Richards"
  container-title: "The Letters of Charlotte Mary Yonge"
  issued: "1858-11-01"
  url: "https://cmyonge.github.io/letters/3120-to-the-reverend-upton-richards"
---

::: {.letter-metadata}
**Date:** Novr 23d 1858  
**From:** Otterbourne, Winchester.  
**Manuscript:** MS Columbia University Library, New York: Yonge Coll
:::

Dear [Sir](people/person_1232.qmd)[^1],
I hope I am not taking a great liberty in addressing you, but I am doing so in the hope that you will excuse me in the circumstances.

These will be best explained if you would glance at the paper entitled ‘[The Little Patient](other_books/otherbook_263.qmd)’ in the October number of the [Monthly Packet](organizations/other_52.qmd)  

The little girl there faithfully described is again in the hospital for Children with another attack of disease of the heart, now so far mitigated that she may live some time longer with care. She must be returned to her wretched home in a week’s time unless some asylum be found for her, and that in London, as her parents and her medical attendants both object to her being removed into the country. [Sister Ellen](people/person_1807.qmd) of [Clewer](organizations/other_20.qmd),[^2] suggested that it was possible that the Home attached to [All Saints](organizations/other_43.qmd) might afford a refuge for her, and in this hope I have ventured to apply directly to you upon the subject. If any <u>small</u> sum should be required towards her maintenance, I am encouraged to think that something could be raised towards it among those interested in the case

Yours respectfully
Charlotte M Yonge

---

[^1]: The Rev. Upton Richards, Vicar of All Saints, Margaret Street. The Society of All Saints’s Sisters of the Poor was founded in his parish in 1848 and run by Harriet Brownlow Byron.
[^2]: The Clewer sisterhood was founded in 1851 by the Rev. Thomas Thellusson Carter, and offered a refuge to prostitutes.
