---
title: "To Elizabeth Barnett"
letter_iso_date: "1859-09-18"
letter_date: "[September 1859]"
location: "[Puslinch]"
manuscript: "MS location unknown.  This fragment printed in Romanes, <i>[Appreciation](other_books/otherbook_241.qmd)</i>, 87."
post_id: 3134
letter_id: "to-elizabeth-barnett-8"
citation:
  type: personal_communication
  author:
    - family: Yonge
      given: Charlotte Mary
  editor:
    - family: Mitchell
      given: Charlotte
    - family: Jordan
      given: Ellen
    - family: Schinske
      given: Helen
  title: "To Elizabeth Barnett"
  container-title: "The Letters of Charlotte Mary Yonge"
  issued: "1859-09-01"
  url: "https://cmyonge.github.io/letters/3134-to-elizabeth-barnett-8"
---

::: {.letter-metadata}
**Date:** [September 1859]  
**From:** [Puslinch]  
**Manuscript:** MS location unknown.  This fragment printed in Romanes, <i>[Appreciation](other_books/otherbook_241.qmd)</i>, 87.
:::

[To [Elizabeth Barnett](people/person_113.qmd) 

It is nine years since I had been [here](organizations/other_123.qmd).   . . . All is much the same, and the ways of the house, sounds and sights, walks and church-going, are all unaltered. And there is all the exceeding pleasure of the old terms, the playful half teasing and scolding, and being set down for nonsense, and oh, above all, [Uncle Yonge](people/person_1623.qmd) - having more of the father to me than any one could have, though very, very different - but to him [Papa](people/person_1631.qmd) looked up, and of him I used to be more afraid than anyone;  and this makes it the most pleasant thing to be with him, and get the kind, merry words that are more to 'William's daughter' than to anything else,not at all to the authoress, for it is rather a joke here.  He has some elements of [Humfrey](cmy_books/cmybook_37.qmd) in him, chiefly the kindly common sense, and the sense of duty which is indeed a good heritage.[^1]  But it is the first time I ever saw his grey head here without the other silver head that used to be inseparable from it.  I have often been here without [Mamma](people/person_1606.qmd), but never without Papa, and you know how to him Devon was like a schoolboy's home, and we used *to be so very happy* together. . . . 

I have left all work behind, and feel as if I were living my own life instead of that of my people, and being the old original Charlotte instead of Miss Yonge.

---

[^1]: A character in her novel *Hopes and Fears*, an ideal English squire.
