---
title: "To Caroline Elizabeth Cooke-Trench"
letter_iso_date: "1859-11-03"
letter_date: "November 3, 1859"
location: "Otterbourne, Winchester"
manuscript: "MS location unknown.  Printed in Coleridge, <i>[Life](other_books/otherbook_40.qmd)</i> 296-7"
post_id: 3140
letter_id: "to-caroline-elizabeth-cooke-trench-3"
citation:
  type: personal_communication
  author:
    - family: Yonge
      given: Charlotte Mary
  editor:
    - family: Mitchell
      given: Charlotte
    - family: Jordan
      given: Ellen
    - family: Schinske
      given: Helen
  title: "To Caroline Elizabeth Cooke-Trench"
  container-title: "The Letters of Charlotte Mary Yonge"
  issued: "1859-11-03"
  url: "https://cmyonge.github.io/letters/3140-to-caroline-elizabeth-cooke-trench-3"
---

::: {.letter-metadata}
**Date:** November 3, 1859  
**From:** Otterbourne, Winchester  
**Manuscript:** MS location unknown.  Printed in Coleridge, <i>[Life](other_books/otherbook_40.qmd)</i> 296-7
:::

My dear [Caroline](people/person_367.qmd)
I find mamma is answering your questions and leaving me to tell you what I know you will wish to hear about our loss. I do so wish you could have seen our dear little [William](people/person_1632.qmd), with his large dark, soft eyes, and his merry smile, he was such an unusually intelligent and pretty creature, I suppose too much so, as if marked from the first for a brighter home.  Somehow I am half glad, though grieved, that [my father](people/person_1631.qmd)'s name and [Mr. Keble](people/person_798.qmd)'s godson should be safe from any stain or dimming.  It was well for [mamma](people/person_1606.qmd) to be spared the two nights and one day of his sinking, just kept up by wine as long as he could swallow, and then six hours of fading away, the last two upon [Frances](people/person_1604.qmd)'s lap.  They brought him home to us, in his little coffin looking so smiling and pretty, with violets in his hands, and on Monday we laid him at his grandfather's feet.  [Mrs. Keble](people/person_795.qmd) made his little white pall, and put a cross of myrtle leaves with arbutus flowers and holly berries.  Frances is so good and sweet and gentle that it is beautiful to watch her, and [Julian](people/person_1624.qmd) too, he feels it very deeply, for the little fellow was very fond of him, and always wanted his notice.  [Mr. Wither](people/person_1544.qmd) too has been very much grieved by it, he was so fond of the baby, and used to go down on the floor to make him laugh, as he lay upon his cushions on the floor at breakfast-time.

I believe many people thought him very delicate, but he was a happy little thing, and we hardly realised how frail was the tenure.  Julian and Frances go to her uncle's on Saturday for a fortnight;  it is a sort of second home to her, and will be very cheering, she hopes.

Yours affectionately
C. M. Yonge
