---
title: "To a member of the Moberly family"
letter_iso_date: "1890-02-18"
letter_date: "[February 1890]"
manuscript: "MS location unknown.  These two fragments, which may belong to two different letters, were published in <i>[Dulce Domum](other_books/otherbook_122.qmd)</i> 304 and 308."
post_id: 3152
letter_id: "to-a-member-of-the-moberly-family"
citation:
  type: personal_communication
  author:
    - family: Yonge
      given: Charlotte Mary
  editor:
    - family: Mitchell
      given: Charlotte
    - family: Jordan
      given: Ellen
    - family: Schinske
      given: Helen
  title: "To a member of the Moberly family"
  container-title: "The Letters of Charlotte Mary Yonge"
  issued: "1890-02-01"
  url: "https://cmyonge.github.io/letters/3152-to-a-member-of-the-moberly-family"
---

::: {.letter-metadata}
**Date:** [February 1890]  
**Manuscript:** MS location unknown.  These two fragments, which may belong to two different letters, were published in <i>[Dulce Domum](other_books/otherbook_122.qmd)</i> 304 and 308.
:::

One can only thank God for the beautiful, holy vision that your ‘sweet [mamma’](people/person_1019.qmd)[^1] has been to me all these fifty years or so – the looking-up friendship which was so precious.  There has been no presence for a long time more sweet and blessed to me;  and that last summer I specially enjoyed, when it had come to be almost the *bien-être*  of relationship, and all redolent of old times. . . .  Well, I don’t think there can be much to alter in her on the other side of the door of Paradise.  How blessed to have two such lives to dwell upon!

Truly, from the first time I saw her, nearly fifty years ago, with her baby on her knee, to my last look, there was no blemish of any kind;  and now, the fine Gold has received its final purification, and reflects perfectly the image of the Refiner.

---

[^1]: Mary Ann Moberly (1812-6 Feb 1890).
