---
title: "To Lady Frederick Bruce"
letter_iso_date: "1893-02-27"
letter_date: "February 27 [1893]"
location: "Elderfield, Otterbourne, Winchester"
manuscript: "MS location unknown.  Printed in Coleridge, <i>[Life](other_books/otherbook_40.qmd)</i> 327"
post_id: 3216
letter_id: "to-lady-frederick-bruce-3"
citation:
  type: personal_communication
  author:
    - family: Yonge
      given: Charlotte Mary
  editor:
    - family: Mitchell
      given: Charlotte
    - family: Jordan
      given: Ellen
    - family: Schinske
      given: Helen
  title: "To Lady Frederick Bruce"
  container-title: "The Letters of Charlotte Mary Yonge"
  issued: "1893-02-27"
  url: "https://cmyonge.github.io/letters/3216-to-lady-frederick-bruce-3"
---

::: {.letter-metadata}
**Date:** February 27 [1893]  
**From:** Elderfield, Otterbourne, Winchester  
**Manuscript:** MS location unknown.  Printed in Coleridge, <i>[Life](other_books/otherbook_40.qmd)</i> 327
:::

My dear [Lady Frederick](people/person_215.qmd)
I am afraid I cannot give you more than a week, and that the 6th must be the last possible day.  I believe I am going to look over the MSS. with [Mrs. Sumner](people/person_1381.qmd) and send them off on the 1st, but we can add your report at the end.  I hope you are really recovered from the influenza.  People are having it at Winchester, but rather slightly.[^1]

I always thought vaguely that the Mays lived somewhere between Malvern and Wales, but I was called to account for having put crayfish into their rivers.  I am always a little afraid of specifically localising unless I know a place intimately.  Nor am I sure where Bexley was (did I *say* Swindon for the junction[?]).  I meant the watering-place to be on the Dorset or Devon coast, and Rock Quay had Torquay in its eye.  I am sorry to say my coadjutors think it will not do to return thither in the [*Packet*.](organizations/other_52.qmd)[^3]  There are not enough kind old friends like you to make the publishers approve.  So when I have time I must finish it singly, but I am hurrying up a National Society story, and I want to do a mother's meeting set of readings on the services of the Sundays of the year.[^4]  Mrs. Sumner's energies are going into the school-boy education subject.

Yours sincerely
C. M. Yonge

---

[^1]: Evidently Margaret Bruce was due to submit a report to [*Mothers in Council*](organizations/other_82.qmd)
[^3]: The sense of this is that [Christabel Coleridge](people/person_329.qmd) and [A.D. Innes](people/person_744.qmd), now editing *MP*, will not allow her space in it to serialize *The Long Vacation* (London: Macmillan 1895).
[^4]: The books referred to here are *The Treasures in the Marshes* (London: National Society 1893) and *Chimes for the Mothers* (London: Wells, Gardner 1893).

**Note:** The May family appear in *The Daisy Chain* and its sequels; Bexley is the setting of *The Pillars of the House* and its sequels.  Rock Quay is resorted to by many of CMY's characters and is the setting of *Beechcroft at Rockstone*.
