---
title: "To the Reverend John Frederick Watkinson Bullock"
letter_iso_date: "1894-02-09"
letter_date: "Feb 9th 1894"
location: "Elderfield Otterbourne"
manuscript: "MS Bodleian Library, Oxford: MS English Letters: e.174 ff 133-4"
post_id: 3248
letter_id: "to-the-reverend-john-frederick-watkinson-bullock-10"
citation:
  type: article
  author:
    - family: Yonge
      given: Charlotte Mary
  editor:
    - family: Mitchell
      given: Charlotte
    - family: Jordan
      given: Ellen
    - family: Schinske
      given: Helen
  title: "To the Reverend John Frederick Watkinson Bullock"
  container-title: "The Letters of Charlotte Mary Yonge"
  issued: "1894-02-09"
  url: "https://cmyonge.github.io/letters/3248-to-the-reverend-john-frederick-watkinson-bullock-10"
---

::: {.letter-metadata}
**Date:** Feb 9th 1894  
**From:** Elderfield Otterbourne  
**Manuscript:** MS Bodleian Library, Oxford: MS English Letters: e.174 ff 133-4
:::

Dear [Mr Bullock](people/person_221.qmd),	
Here I send Archbishop Sancroft, hoping he is the right length. Miss Strickland’s [Seven Bishops](other_books/otherbook_689.qmd) made it rapid work.

Have you thought of Frampton - a non juror, though not in time to be added to the 7.  I have  a [life](other_books/otherbook_690.qmd) of him and could write it. I have just had your letter. I do not much incline to Sir R Fanshaw. I had his wife’s [book](other_books/otherbook_520.qmd) long ago, and lost sight of it. I think it was from the [London Library](organizations/other_29.qmd) but went on into vanities of political mission rather wearily. However, Lord Carnarvon who was killed at Newbury or Edmund Verney are more model Cavaliers.[^1]

Thank you for your card about Bp Andrews. I handed it to the Chairman of our society - Andrews’ [descendant](people/person_40.qmd) is Master of [St Cross](organizations/other_130.qmd)[^2]

Yours truly
C M Yonge

---

[^1]: Robert Dormer, Earl of Carnarvon (1610?-1643); Sir Edmund Verney (1616-1649).  These biographies were for the 'Biographies of Eminent Anglicans' series, of which CMY wrote several for Bullock's *Daily Lections* project, but which were not in fact published.
[^2]: W. G. Andrewes became Master of St. Cross Hospital in 1868.
