---
title: "To Ethel Romanes"
letter_iso_date: "1894-05-18"
letter_date: "[May 1894]"
manuscript: "MS location unknown.  Printed in Romanes, [<i>Appreciation</i>](other_books/otherbook_241.qmd), 191-2."
post_id: 3265
letter_id: "to-ethel-romanes-2"
citation:
  type: article
  author:
    - family: Yonge
      given: Charlotte Mary
  editor:
    - family: Mitchell
      given: Charlotte
    - family: Jordan
      given: Ellen
    - family: Schinske
      given: Helen
  title: "To Ethel Romanes"
  container-title: "The Letters of Charlotte Mary Yonge"
  issued: "1894-05-18"
  url: "https://cmyonge.github.io/letters/3265-to-ethel-romanes-2"
---

::: {.letter-metadata}
**Date:** [May 1894]  
**Manuscript:** MS location unknown.  Printed in Romanes, [<i>Appreciation</i>](other_books/otherbook_241.qmd), 191-2.
:::

[To [Ethel Romanes](people/person_1258.qmd)]

Will you allow one who is almost a stranger to you personally, to express my deep sympathy and sorrow when I saw the notice in the paper of the awful blow that has fallen on you?[^1] I know from [Annie Moberly](people/person_1024.qmd) of your great kindness on my birthday last year, and that leads me to hope that you will not feel a few words from an old woman an intrusion; though pray do not try to answer them, as I shall hear of you from Annie. I have thought of you in my prayers, and may you and your children have full comfort and joy in communion alike with those gone before and with the Comforter and great Head of the Church.

A very dear friend of mine, [Mrs. Gibbs](people/person_557.qmd), whose name you know in connection with [Keble College](organizations/other_5.qmd), used to say that the losses of her [husband](people/person_560.qmd) and several of her children had made ‘Therefore with Angels and Archangels,’ etc., more to her than ever. If you do not know William Tupper's sonnet, ‘Ye saints in Heaven, dear Jesu's Body Glorious, From Abel to the babe baptized but now,’ ask Annie to show it to you.[^2] [Mrs. Keble](people/person_795.qmd) used to keep a copy in her pocket.

Yours very sincerely,
C. M. YONGE.

---

[^1]: The early death of  her husband [George John Romanes](people/person_2136.qmd) (1848-23 May 1894).
[^2]: In *Musings over the Christian Year*, 341, CMY had attributed the poem to Thomas Ken.  It appears to have been the work of the Rev. William George Tupper, brother of the poet [Martin Tupper](people/person_1801.qmd).
