---
title: "Charles Wooldridge to Charlotte Mary Yonge"
letter_iso_date: "1895-04-10"
letter_date: "Apr 10 1895"
manuscript: "Copy outletter book,  Hampshire Record Office 70M92W/59/4"
post_id: 3293
letter_id: "charles-wooldridge-to-charlotte-mary-yonge-6"
citation:
  type: article
  author:
    - family: Yonge
      given: Charlotte Mary
  editor:
    - family: Mitchell
      given: Charlotte
    - family: Jordan
      given: Ellen
    - family: Schinske
      given: Helen
  title: "Charles Wooldridge to Charlotte Mary Yonge"
  container-title: "The Letters of Charlotte Mary Yonge"
  issued: "1895-04-10"
  url: "https://cmyonge.github.io/letters/3293-charles-wooldridge-to-charlotte-mary-yonge-6"
---

::: {.letter-metadata}
**Date:** Apr 10 1895  
**Manuscript:** Copy outletter book,  Hampshire Record Office 70M92W/59/4
:::

Dear Madam
Judging from your former letter that you do not expect [Mrs. Yonge](people/person_1604.qmd) to pay for the £1000 I think it will be best to have the policy transferred to you.  For that purpose it will be necessary that Mrs. Yonge should sign the transfer.  Will you kindly write to her & explain this & say that she may expect to hear from [me](people/person_2094.qmd).  I have duly recd the cheque for £1.15.  this includes some of the property but I think there is another smaller sum at another quarter for the rest of the property. The amt. is £1.19 bu I will pay the 4/- & add to my account

Please let me know Mrs Yonge’s address

I am yours faithy
Chas Wooldridge

If you instruct [Mr Houseman](people/person_2146.qmd) it will be well to tell him that the policy has become your absolute property
