---
title: "To Frederick Orridge Macmillan"
letter_iso_date: "1895-10-14"
letter_date: "Oct 14th [1895]"
location: "Elderfield Otterbourne"
manuscript: "MS British Library  Add MSS 54921: 218"
post_id: 3300
letter_id: "to-frederick-orridge-macmillan-or-alexander-macmillan-3"
citation:
  type: article
  author:
    - family: Yonge
      given: Charlotte Mary
  editor:
    - family: Mitchell
      given: Charlotte
    - family: Jordan
      given: Ellen
    - family: Schinske
      given: Helen
  title: "To Frederick Orridge Macmillan"
  container-title: "The Letters of Charlotte Mary Yonge"
  issued: "1895-10-14"
  url: "https://cmyonge.github.io/letters/3300-to-frederick-orridge-macmillan-or-alexander-macmillan-3"
---

::: {.letter-metadata}
**Date:** Oct 14th [1895]  
**From:** Elderfield Otterbourne  
**Manuscript:** MS British Library  Add MSS 54921: 218
:::

Dear [Mr Macmillan](people/person_942.qmd)
I have a story within three or four short chapters of completion, which I should like to mention in case it should come within the scope of any autumn arrangements.

I think the title might be ‘A Release’.[^1] It is founded on a story that [Guizot](people/person_597.qmd) once told me that [Mongolfier](people/person_1036.qmd), the  aëronaut gained the affections of a noble young lady, whose parents forced her to become a nun. She appealed to the Pope who absolved her, and they were married.

I asked [Madame de Witt](people/person_423.qmd) if I might use the story, and she said yes, but not the name as there are Mongolfiers still living.[^2]

It is about half as long as the [Long Vacation](cmy_books/cmybook_237.qmd) too long for the present arrangements of the [Monthly Packet](organizations/other_52.qmd), for which I began it. Had it better be published by you as it is, or go into any periodical first.

One title might be ‘Caroline’s French Kindred’ Caroline is English, but the moving spirit. When published in a volume it would begin with the Christmas number story ‘Caroline’s Defiance in which she first appeared - Christmas 1893.

Yours truly
C M Yonge

---

[^1]: *The Release, or, Caroline's French Kindred* (London: Macmillan 1896). Part 1 appeared in *MP* (Christmas 1894) under the title ‘Caroline's Defiance’.
[^2]: The story of the marriage between Jacques-Étienne Montgolfier (1745-1799) and Mademoiselle Brun (d.1845) who had been a nun, is told by Bessie Belloc, *In a Walled Garden* (London: Ward 1895), 119.
