---
title: "To Frederick Orridge Macmillan"
letter_iso_date: "1897-12-14"
letter_date: "Decr 14th 1897"
location: "Elderfield Otterbourne Winchester"
manuscript: "MS British Library  Add MSS 54921: 229-30"
post_id: 3363
letter_id: "to-frederick-orridge-macmillan-13"
citation:
  type: article
  author:
    - family: Yonge
      given: Charlotte Mary
  editor:
    - family: Mitchell
      given: Charlotte
    - family: Jordan
      given: Ellen
    - family: Schinske
      given: Helen
  title: "To Frederick Orridge Macmillan"
  container-title: "The Letters of Charlotte Mary Yonge"
  issued: "1897-12-14"
  url: "https://cmyonge.github.io/letters/3363-to-frederick-orridge-macmillan-13"
---

::: {.letter-metadata}
**Date:** Decr 14th 1897  
**From:** Elderfield Otterbourne Winchester  
**Manuscript:** MS British Library  Add MSS 54921: 229-30
:::

Dear [Mr Macmillan](people/person_942.qmd)

One of my very first ventures in publishing was [‘Kenneth: or the Rear Guard of the Grand Army’](cmy_books/cmybook_10.qmd). [J.H. Parker](people/person_1142.qmd) of Oxford published it, on the half profits system, I retaining the copyright. There were two or three editions but it has gone out of print, though I am sometimes asked how to get it.

Also, about 1850 and 52, [Masters](people/person_981.qmd) published[Henrietta’s Wish](cmy_books/cmybook_11.qmd), and [the Two Guardians](cmy_books/cmybook_13.qmd), republished from the [Churchman’s Companion](organizations/other_62.qmd). Both had fair success, and he gave me £20 and £25 for each successive edition I <u>think</u> three. I have heard no more of them for many years and now I learn that his successor has given up the publishing business and I believe the stock is handed to Mowbray. The Copyright is mine.

I hear of enquiries for the books at times. Would it be worth while for you to try to recover them?

The [Bishop of Quebec](people/person_456.qmd) has just asked me to let him have a former tale of mine for a Church paper. I have recommended him <u>Kenneth</u>, as there is much adventure but I have come to perceive that there are many mistakes, so that I do not so much care to have it revived as the other two, which I really think worth renewing

Yours truly
C M Yonge
