---
title: "To Beatrice Henrietta Heathcote"
letter_iso_date: "1898-02-11"
letter_date: "Feb 11 [1898]"
location: "Elderfield Otterbourne"
manuscript: "MS Hampshire Record Office: Heathcote Family Scrapbooks: 63M84/234/63"
post_id: 3371
letter_id: "to-beatrice-heathcote"
citation:
  type: article
  author:
    - family: Yonge
      given: Charlotte Mary
  editor:
    - family: Mitchell
      given: Charlotte
    - family: Jordan
      given: Ellen
    - family: Schinske
      given: Helen
  title: "To Beatrice Henrietta Heathcote"
  container-title: "The Letters of Charlotte Mary Yonge"
  issued: "1898-02-11"
  url: "https://cmyonge.github.io/letters/3371-to-beatrice-heathcote"
---

::: {.letter-metadata}
**Date:** Feb 11 [1898]  
**From:** Elderfield Otterbourne  
**Manuscript:** MS Hampshire Record Office: Heathcote Family Scrapbooks: 63M84/234/63
:::

My dear [Bea](people/person_655.qmd),
It must have been the Die and not the seal itself that was hidden in the wall. [Lottie Yonge](people/person_1588.qmd) has discovered at the Croft Vertue’s Cromwell seals and medals with Richard’s seal  - he is on horseback on one side and in parliament on the other. Also that Timbs in his [‘Abbeys and Castles’](other_books/otherbook_739.qmd)says that ‘Wllm Heathcote Esq found the die and sold it but <u>Sir</u> William Heathcote bought the die.[^1] This is on the authority of Vertue in 1760, but as he thought it was the die of the seal of the Long Parliament.

I do not much hold to his authority, and if the seal or die was bought back to Hursley, what could have become of it?

I think the actual seal is a flat thing, like a coin (only concave) and the die big and solid more like a weight.

[Anna](people/person_195.qmd) has sent me the rubbing and it is gone to [Edmund Morshead](people/person_42.qmd). The Frances White who erected the monument to Sir Charles Wyndham must have been the wife of the man with the Crease

I have written to [Mr Chamberlayne](people/person_2114.qmd) to ask after Sir Isaac Newton’s sun dial. I think - and so does [Alethea](people/person_182.qmd) that there used to be one at Cranbury on the slope above King’s Lane

Boyatt Lane and High bridge used to belong to Brambridge so I can get in the avenues being pollarded for gun stocks, and Mrs Fitzherbert whom my [mother](people/person_1606.qmd)saw there and remembered her eyebrows

Yours affectionately
C M Yonge

---

[^1]: The research material was being gathered for *John Keble's Parishes*, and the story of the discovery of the Great Seal of the Commonwealth appears on pp.50-1.  On page 74 there is a description of the monument to Thomas White 'with a blade waved like a Malay crease'.  Maria Fitzherbert, the supposed wife of George IV, belonged to the  Smythe family who owned Brambridge;  they are mentioned on pp. 85-7.
