---
title: "To Frederick Orridge Macmillan"
letter_iso_date: "1898-03-06"
letter_date: "Mar 6d [1898]"
location: "Elderfield Otterbourne"
manuscript: "MS British Library  Add MSS 54921: 232-3"
post_id: 3372
letter_id: "to-frederick-orridge-macmillan-15"
citation:
  type: article
  author:
    - family: Yonge
      given: Charlotte Mary
  editor:
    - family: Mitchell
      given: Charlotte
    - family: Jordan
      given: Ellen
    - family: Schinske
      given: Helen
  title: "To Frederick Orridge Macmillan"
  container-title: "The Letters of Charlotte Mary Yonge"
  issued: "1898-03-06"
  url: "https://cmyonge.github.io/letters/3372-to-frederick-orridge-macmillan-15"
---

::: {.letter-metadata}
**Date:** Mar 6d [1898]  
**From:** Elderfield Otterbourne  
**Manuscript:** MS British Library  Add MSS 54921: 232-3
:::

Dear [Mr Macmillan](people/person_942.qmd)
I have been so often asked for a cheaper edition of my novels that I am delighted to hear that you are beginning on one of them, and I hope it will answer so well that you may follow it up with others

I hope by the 1st of July to send you the ['Parishes of John Keble’](cmy_books/cmybook_247.qmd). It is being looked over by the Heathcote family now, and I shall not have it back till the 18th when I hope to put the last touches. A great deal of curious history has come out about the various old houses and the book will be of more general interest than I thought at first. I send another instalment of the [Cameos](cmy_books/cmybook_249.qmd) for the printers

Yours sincerely
C M Yonge
