---
title: "To Frederick Orridge Macmillan"
letter_iso_date: "1898-06-23"
letter_date: "June 23rd 1898"
location: "Elderfield Otterbourne"
manuscript: "MS British Library  Add MSS 54921: 234-5"
post_id: 3375
letter_id: "to-frederick-orridge-macmillan-16"
citation:
  type: article
  author:
    - family: Yonge
      given: Charlotte Mary
  editor:
    - family: Mitchell
      given: Charlotte
    - family: Jordan
      given: Ellen
    - family: Schinske
      given: Helen
  title: "To Frederick Orridge Macmillan"
  container-title: "The Letters of Charlotte Mary Yonge"
  issued: "1898-06-23"
  url: "https://cmyonge.github.io/letters/3375-to-frederick-orridge-macmillan-16"
---

::: {.letter-metadata}
**Date:** June 23rd 1898  
**From:** Elderfield Otterbourne  
**Manuscript:** MS British Library  Add MSS 54921: 234-5
:::

Dear [Mr Macmillan](people/person_942.qmd)
Herewith I send the MS of ‘[John Keble’s Parishes](cmy_books/cmybook_247.qmd)’ I shall be glad to know what you think the best way of dealing with it and what you think about illustrations.

There should be a map of the parishes which are <u>locked</u> together but I wait to get it  drawn out till I hear about the size of the page

What would be advisable as to illustrations. We had thought of

Ruins of Merdon Castle
Old house at Hursley
Cup and other relics found in a deep well
Great Seal of Richard Cromwell
Old Church of Hursley
Otterbourne Church 
Ampfield Church 
Hursley Church  
Portrait of [Sir William Heathcote](people/person_669.qmd)
& [Mr Keble](people/person_798.qmd)

Would these be too expensive?

What would be the terms

If possible the book should be out by the middle of October, as a Jubilee of the Church’s Consecration is to be kept on that day/24th

Yours sincerely
C M Yonge
