---
title: "To Mary Yonge"
letter_iso_date: "1899-01-26"
letter_date: "Jan 26th [1899]"
location: "Elderfield Otterbourne"
manuscript: "MS West Devon Area Record Office Acc No 308"
post_id: 3393
letter_id: "to-mary-yonge-3"
citation:
  type: article
  author:
    - family: Yonge
      given: Charlotte Mary
  editor:
    - family: Mitchell
      given: Charlotte
    - family: Jordan
      given: Ellen
    - family: Schinske
      given: Helen
  title: "To Mary Yonge"
  container-title: "The Letters of Charlotte Mary Yonge"
  issued: "1899-01-26"
  url: "https://cmyonge.github.io/letters/3393-to-mary-yonge-3"
---

::: {.letter-metadata}
**Date:** Jan 26th [1899]  
**From:** Elderfield Otterbourne  
**Manuscript:** MS West Devon Area Record Office Acc No 308
:::

My dear [Mary](people/person_1626.qmd)
St Paul has brought us nice brisk weather, I hope it is not too cold for you, but it is pleasant to have it clean.  We have had the excitement of hearing that [Capt Cromie](people/person_386.qmd) has been transferred to Algeciras in Spain, close to Gibraltar, so [Frances](people/person_1604.qmd) comes home with the whole family in March and will not miss the wedding -[^1] I do not know much more for the letters were to [Helen](people/person_1613.qmd), and so I had to direct them on, and she poor thing has a lame finger, she had the sash window shut down on her middle finger  She was alone in the room and could not reach the bell, so there she had to wait till the newspaper boy came by and she could call to him to send a maid from the kitchen.  It is still painful, though it happened nearly a week ago, so she writes as little as she can.  [Maude](people/person_1629.qmd) is going on very well, and the fear of [Maurice](people/person_1630.qmd) having carried the infection is over, I am thankful to say.

There was a burglary the other day, at that house on the Winchester road, looking towards the Hursley road, £250 worth of plate was carried off in the night, by the connivance it is supposed by the butler’s connivance but after two days, the most of it was found in the old Hollow, just above!  The thieves must have found it too heavy to carry far!

We have our Diocesan examination on Tuesday and Wednesday of next week.  We like [Mr Silver](people/person_2086.qmd), the examiner very much.

I have some snowdrops and there are hazel catkins, but I suppose everything will be wholesomely retarded.

If [Charlotte](people/person_1587.qmd) gets new books, she should see G Leslie’s [letters to Marco](other_books/otherbook_611.qmd)- ie Mr Marks  They are all about observations on birds and flowers

your most affectionate
C M Yonge

---

[^1]: The wedding of CMY's nephew [Maurice Yonge](people/person_1630.qmd) to Maude Woods on 19 April 1899.  CMY’s  youngest niece Joanna Angela Yonge had married (October 1894) Captain Charles Francis Cromie, H.M. Consul for French West Africa.
