---
title: "To Earl Nelson"
letter_iso_date: "1899-10-30"
letter_date: "Oct 30th 1899"
location: "Elderfield Otterbourne"
manuscript: "MS Princeton University, Parrish Collection"
post_id: 3432
letter_id: "to-earl-nelson-2"
citation:
  type: personal_communication
  author:
    - family: Yonge
      given: Charlotte Mary
  editor:
    - family: Mitchell
      given: Charlotte
    - family: Jordan
      given: Ellen
    - family: Schinske
      given: Helen
  title: "To Earl Nelson"
  container-title: "The Letters of Charlotte Mary Yonge"
  issued: "1899-10-30"
  url: "https://cmyonge.github.io/letters/3432-to-earl-nelson-2"
---

::: {.letter-metadata}
**Date:** Oct 30th 1899  
**From:** Elderfield Otterbourne  
**Manuscript:** MS Princeton University, Parrish Collection[^1]
:::

My dear [Lord Nelson](people/person_1081.qmd)
Thank you very heartily for your notes. It is very pleasant to see how much one’s contemporaries minds are to one’s own. I think all of that training in experience and principle that we have had must feel the expedience of submission in what is not a vital point, if a stand is to be made on what is important. Nor do I see, what the enemy aver, that yielding in these points leaves us open to attack in others that have long been conceded. The reasons/placus\\[?] are the weak point in the decisions, as every one agrees, but I fully believe that greater strength will come out of the struggle, as has so often happened before

Then there was almost nothing to be touched either by the decision or our own Diocesan’s own interpretation in [*illegible*] change, but thus far I see that we shall not have a special observance of All soul’s day tomorrow as we had last year though of course All Saints is specially marked.

I look up to Brickworth whenever I pass towards Salisbury, more seldom now than formerly and remember walks on the downs[^2]

I always enjoy meeting [Susan](people/person_164.qmd) at Winchester functions

Yours sincerely
C M Yonge

---

[^1]: Pasted on  the back is the front cover of a pamphlet called ‘The Anglo-Catholic Position in Re the Archbishops’ Decision on Lights and Incense’ by Horatio Earl Nelson.  The letter refers to the widespread public debate about ritualism, which had culminated in the pronouncement on 31 July 1899 by Frederick Temple, the Archbishop of Canterbury, that the liturgical use of candles and incense was forbidden by the Church of England.
[^2]: Lord Nelson lived at Brickworth, Wiltshire. He had inherited it from his mother, who had been a friend of FMY.  He and his sister Susan had known CMY since childhood.
