---
title: "To  Maria Edith Walker"
letter_iso_date: "1900-01-06"
letter_date: "Jan 6th 1900"
location: "Elderfield Otterbourne"
manuscript: "MS  West Sussex County Record Office/ Add. 16,944/6"
post_id: 3438
letter_id: "to-miss-e-m-walker-4"
citation:
  type: article
  author:
    - family: Yonge
      given: Charlotte Mary
  editor:
    - family: Mitchell
      given: Charlotte
    - family: Jordan
      given: Ellen
    - family: Schinske
      given: Helen
  title: "To  Maria Edith Walker"
  container-title: "The Letters of Charlotte Mary Yonge"
  issued: "1900-01-06"
  url: "https://cmyonge.github.io/letters/3438-to-miss-e-m-walker-4"
---

::: {.letter-metadata}
**Date:** Jan 6th 1900  
**From:** Elderfield Otterbourne  
**Manuscript:** MS  West Sussex County Record Office/ Add. 16,944/6
:::

My dear [Miss Walker](people/person_2234.qmd)
Did people in 1800 think as much about war as we do?  In fact I think they had a respite then, while the Peace of Amiens prevailed. I knew the old [Dean of Winchester](people/person_542.qmd)who had been at a levee of the [First Consul](people/person_2207.qmd) in that year with [Sir James Mackintosh](people/person_2208.qmd).  I made my niece look at him (the Dean) he was 90, by way of making a link

I have a [Peacock at Home](other_books/otherbook_752.qmd) with the badly painted pictures you describe /1807\\, but the drawings were [Mulready](people/person_2206.qmd)’s and are excellent  the poem is Mrs Dorset’s.

[Griffiths and Farran](organizations/other_233.qmd)republished it without the paint, and one sees how good they are.  The [Butterfly’s ball](other_books/otherbook_753.qmd) by Roscoe was the first but the Peacock is much cleverer.  The [Lion’s Masquerade](other_books/otherbook_754.qmd) is not quite equal to the others, nor is the [Elephant’s Ball](other_books/otherbook_755.qmd). They had all fallen into the way of imitations

yours sincerely
C M Yonge

---

**Note:** Catherine Dorset, *The Peacock ‘At Home’: A Sequel to The Butterfly’s Ball* (London: Harris 1807). William Caldwell Roscoe, *The Butterfly’s Ball and the Grasshopper’s Feast*  (London: Harris 1807); Catherine Dorset, *The Lion's Masquerade: A Sequel to The Peacock at Home* (London: Harris 1808); W.B, *The Elephant’s Ball  and Grand Fete Champetre* (London: Harris 1807).
