---
title: "To Elizabeth Barnett"
letter_iso_date: "1857-00-00"
letter_date: "[1857]"
manuscript: "MS location unknown.  This fragment printed in Romanes, <i>[Appreciation](other_books/otherbook_241.qmd)</i> p. 83."
post_id: 3518
letter_id: "to-elizabeth-barnett-10"
citation:
  type: personal_communication
  author:
    - family: Yonge
      given: Charlotte Mary
  editor:
    - family: Mitchell
      given: Charlotte
    - family: Jordan
      given: Ellen
    - family: Schinske
      given: Helen
  title: "To Elizabeth Barnett"
  container-title: "The Letters of Charlotte Mary Yonge"
  issued: "1857-01-01"
  url: "https://cmyonge.github.io/letters/3518-to-elizabeth-barnett-10"
---

::: {.letter-metadata}
**Date:** [1857]  
**Manuscript:** MS location unknown.  This fragment printed in Romanes, <i>[Appreciation](other_books/otherbook_241.qmd)</i> p. 83.
:::

[To [Elizabeth Barnett](people/person_113.qmd) 

The folk here, are quite on my side about ‘Debonnaire.’ In the first place, the King was so called as synonymous with Pious, according to [Sismondi](other_books/otherbook_271.qmd), and the proper original meaning of this word seems to have been  ‘gracious,’ in which sense it is constantly applied to the best of the knights. Modern French has debased it, and given it of late the sense of weakness.... In English it decidedly means graceful. .  . [Johnson](other_books/otherbook_272.qmd) calls it elegant, civil, wellbred, and no doubt it was such in the chivalrous vocabulary. Now, this was just what I wanted; if it had no foolish sense it would be flattery. . .

---

**Note:** Romanes associates this letter with the publication of *Dynevor Terrace* (1857), whose hero, Louis, is nicknamed after King Louis (778-840), of France. There was a discussion of Louis le Debonnaire’s sobriquet in the article ‘Preparation of Prayer Book Lessons’ *[MP](organizations/other_52.qmd)* (1 March 1887) 271.
