---
title: "To Elizabeth Missing Sewell"
letter_iso_date: "1853-00-00"
letter_date: "Easter Eve [<i>c</i>. 1853-1862]"
location: "Otterbourn"
manuscript: "MS Princeton University, Parrish Collection"
post_id: 3525
letter_id: "to-elizabeth-missing-sewell-3"
citation:
  type: article
  author:
    - family: Yonge
      given: Charlotte Mary
  editor:
    - family: Mitchell
      given: Charlotte
    - family: Jordan
      given: Ellen
    - family: Schinske
      given: Helen
  title: "To Elizabeth Missing Sewell"
  container-title: "The Letters of Charlotte Mary Yonge"
  issued: "1853-00-00"
  url: "https://cmyonge.github.io/letters/3525-to-elizabeth-missing-sewell-3"
---

::: {.letter-metadata}
**Date:** Easter Eve [<i>c</i>. 1853-1862]  
**From:** Otterbourn  
**Manuscript:** MS Princeton University, Parrish Collection
:::

My dear [Miss Sewell](people/person_1301.qmd),
You will think that this is to announce the Simeons but there is no news of them all this time, and the hyacinths are blowing for them in vain in their bay window at Winchester.[^1]

My present purpose is to pass on to you a question which a correspondent of mine - a clergyman’s wife in Cornwall[^2] - has sent me on the principle of a delusion of which I have known other instances, that authoresses must know of governesses. It will save time, of which I have little today if I send you the letter. It seems to me exactly the situation that sometimes one longs to hear of, but the ‘hour and the man’ seldom fit. The letter adds that the lady should be neither governess nor duenna but about 5 or 10 years the senior of the damsel who is about 20, and very silent. If you do not know of any thing likely to suit, pray burn the letter and do not trouble yourself with answering it would be too bad to take up your time for nothing. The Miss Yards are very well, [Miss Adelaide](people/person_1577.qmd) I think stronger than usual.[^3] I am glad to hear from [Mr Wither](people/person_1544.qmd) that he hopes soon to see Mr [Edwards Sewell](people/person_1304.qmd) here

Yours sincerely
C M Yonge

---

[^1]: Perhaps Captain [Charles Simeon](people/person_1322.qmd) (1816-1867) and his wife Sarah Jane Williams (d. 1903) who married in 1842, lived at Hursley and had 6 sons and 7 daughters.  He was born on the Isle of Wight., where Sewell lived.  This letter dates  before the move to Elderfield in March 1863.
[^2]: Perhaps [Charlotte Champion Pascoe](people/person_1146.qmd).
[^3]: Adelaide and [Eliza](people/person_1578.qmd) Yard came to live in Otterbourne in 1848 and then in the 1860s moved to Winchester, where  Elizabeth Sewell stayed with them in 1864.
