---
title: "To the Editor of the <i>Girls’ Friendly Society Associates’ Journal</i>"
letter_iso_date: "1893-09-00"
letter_date: "[September 1893]"
manuscript: "MS location unknown. Printed in the <i>[Girls’ Friendly Society Associates’ Journal and Advertiser](organizations/other_72.qmd)</i> (September  1893) 165."
post_id: 9374
letter_id: "to-the-editor-of-the-i-girls-friendly-society-associates-journal-i"
citation:
  type: article
  author:
    - family: Yonge
      given: Charlotte Mary
  editor:
    - family: Mitchell
      given: Charlotte
    - family: Jordan
      given: Ellen
    - family: Schinske
      given: Helen
  title: "To the Editor of the <i>Girls’ Friendly Society Associates’ Journal</i>"
  container-title: "The Letters of Charlotte Mary Yonge"
  issued: "1893-09-00"
  url: "https://cmyonge.github.io/letters/9374-to-the-editor-of-the-i-girls-friendly-society-associates-journal-i"
---

::: {.letter-metadata}
**Date:** [September 1893]  
**Manuscript:** MS location unknown. Printed in the <i>[Girls’ Friendly Society Associates’ Journal and Advertiser](organizations/other_72.qmd)</i> (September  1893) 165.
:::

HONOUR!

Madam,-
I should like to ask associates to try to instil notions of Honour towards employers into their Members and Candidates. Instances come before me continually of persons deserted by their servants without notice. One invalid was left alone in the house till the milkman called for help; another lady, a most kind one, found, on the day of a dinner-party, two raw chickens in the kitchen and nothing else by way of preparation- the maids gone! Two girls I have known, have, for some fancy gone off from their situations before a fortnight was over simply because they did not like them. The old idea of at least giving a month’s notice seems to be exploded. I do not believe these girls were [G.F.S.](organizations/other_23.qmd) Members: but I have known one who ran away from her first place, and very nearly did so from her second, for really no valid cause. The young things do not seem to understand that they are really pledged, and that having made an engagement they are bound by it. Associates are sometimes in difficulties, when an imprudent girl has hastily taken a situation, and it may be needful to free her from it, but she should be made to understand that the breaking of an engagement is a serious thing, and if a little hardship be the consequence, not evil associations, she should endure it for a month. Nor should she be allowed after acceptance of an offer to set it aside for one more tempting, though the refusal may be a trial to her Associate.	

C. M. Yonge.
