---
title: "To the Editor of the <i>Girls’ Friendly Society Associates’ Journal</i>"
letter_iso_date: "1890-10-00"
letter_date: "[October 1890]"
manuscript: "MS location unknown. Printed in the <i>[Girls’ Friendly Society Associates’ Journal and Advertiser](organizations/other_72.qmd)</i>  (October 1890) 175."
post_id: 9398
letter_id: "to-the-editor-of-the-i-girls-friendly-society-associates-journal-i"
citation:
  type: personal_communication
  author:
    - family: Yonge
      given: Charlotte Mary
  editor:
    - family: Mitchell
      given: Charlotte
    - family: Jordan
      given: Ellen
    - family: Schinske
      given: Helen
  title: "To the Editor of the <i>Girls’ Friendly Society Associates’ Journal</i>"
  container-title: "The Letters of Charlotte Mary Yonge"
  issued: "1890-10-01"
  url: "https://cmyonge.github.io/letters/9398-to-the-editor-of-the-i-girls-friendly-society-associates-journal-i"
---

::: {.letter-metadata}
**Date:** [October 1890]  
**Manuscript:** MS location unknown. Printed in the <i>[Girls’ Friendly Society Associates’ Journal and Advertiser](organizations/other_72.qmd)</i>  (October 1890) 175.
:::

CHARACTER OF SERVANTS

Dear Madam,-
May I give a hint- one, perhaps often given to Associates, but still often disregarded. A great number of really excellent ladies, naturally disposed to support [G.F.S.](organizations/other_23.qmd), have become averse to it, because in many places recommendations of servants are not to be depended upon. It is a rule in some Dioceses that the new employer should always be put in communication with the former one, and this should never be omitted. It is quite true that the girl ought to have another chance, and that the person she is leaving may have been harsh and hasty; but it is not right that these ordinary courtesies should be neglected, and the Associate is free to give her own view of the case. A feeling of offence remains with the first employer, and supposing that faults recur, the new mistress has good reason to complain that she has not been fairly treated. Nor can the Associate, however fond of the Member, be sure that she has heard from her ‘the truth, the whole truth, and nothing but the truth.’

I have reason to believe that these one-sided recommendations are one of the chief causes why to many mistresses G.F.S. is not a full testimonial to character. There is a conscience towards the employer that should be observed, as well as charity to the Member; nay partiality is not charity.

I remain, &c.,
C.M. Yonge.
