---
title: "Journal of the Lady Beatrix Graham, Sister of the Marquis of Montrose[Preface by CMY]"
book_id: 91
sort_title: "Journal of the Lady Beatrix Graham, Sister of the Marquis of Montrose"
---

## Publication Information

**Date:** 1871

**Genre:** Non-fiction: preface

**Publisher:** London: Bell and Daldy, York Street, Covent Garden

**Notes:** This was an anonymous novel by Jane Mary Dampier.  The preface is dated August 1870.  It was reviewed in ‘Hints on Reading’ <i>MP</i> (April 1871) 420: '<i>Journal of Lady Beatrix Graham</i> (Bell and Daldy) is a charming picture of the life of the great Marquis of Montrose and his loving admiring young sister, during the interval between his loyal exploits in Scotland and his death. We like it the best of all the imaginary diaries that have been so numerous.’ .

## Letters Mentioning This Work

- [Letter 2240](../2240-to-jane-mary-smith-dampier-2.qmd)
- [Letter 2368](../2368-to-jane-mary-dampier.qmd)
- [Letter 2383](../2383-to-jane-mary-dampier-2.qmd)
- [Letter 2504](../2504-to-sir-edward.qmd)
- [Letter 3539](../3539-to-emily-or-jane-dampier-2.qmd)

