---
title: "The Daisy Chain, or, Aspirations: A Family Chronicle. By the author of “The Heir of Redclyffe.” 2 Vols"
book_id: 24
sort_title: "Daisy Chain, or, Aspirations: A Family Chronicle"
---

## Publication Information

**Date:** 1856

**Genre:** Fiction (modern)

**Publisher:** John W Parker and Son, West Strand, London.

**Notes:** The May family appear again in <i>The Trial</i> and other novels.

## Letters Mentioning This Work

- [Letter 1829](../1829-to-frances-sophia-coleridge-patteson-3.qmd)
- [Letter 1836](../1836-to-frances-sophia-coleridge-patteson-4.qmd)
- [Letter 1847](../1847-to-elizabeth-barnett-or-edith-emma-butler.qmd)
- [Letter 1862](../1862-from-the-reverend-john-coleridge-patteson-to-charlotte-mary-yonge.qmd)
- [Letter 1907](../1907-to-alexander-macmillan-3.qmd)
- [Letter 1914](../1914-to-alexander-macmillan-5.qmd)
- [Letter 1927](../1927-alexander-macmillan-to-charlotte-mary-yonge-6.qmd)
- [Letter 1928](../1928-alexander-macmillan-to-charlotte-mary-yonge-7.qmd)
- [Letter 2094](../2094-to-francis-turner-palgrave.qmd)
- [Letter 2224](../2224-the-right-reverend-john-coleridge-patteson-to-charlotte-mary-yonge-6.qmd)
- [Letter 2331](../2331-to-mary-ann-dyson-12.qmd)
- [Letter 2436](../2436-the-rev-james-edward-austen-leigh-to-sir-william-heathcote.qmd)
- [Letter 2437](../2437-to-sir-william-heathcote-bt-5.qmd)
- [Letter 2607](../2607-to-elizabeth-wordsworth-9.qmd)
- [Letter 2652](../2652-to-messrs-macmillan-7.qmd)
- [Letter 2660](../2660-to-alexander-macmillan-135.qmd)
- [Letter 2897](../2897-to-lady-frederick-bruce.qmd)
- [Letter 2899](../2899-to-george-lillie-craik-74.qmd)
- [Letter 2938](../2938-to-anne-yonge-6.qmd)
- [Letter 2942](../2942-to-anne-yonge-10.qmd)
- [Letter 2954](../2954-to-anne-yonge-21.qmd)
- [Letter 2971](../2971-to-mary-anne-dyson-11.qmd)
- [Letter 3055](../3055-to-anne-yonge-31.qmd)
- [Letter 3067](../3067-to-alice-arbuthnot-moberly-6.qmd)
- [Letter 3071](../3071-to-alice-arbuthnot-moberly-8.qmd)
- [Letter 3076](../3076-to-alice-arbuthnot-moberly-9.qmd)
- [Letter 3080](../3080-to-jemima-blackburn-8.qmd)
- [Letter 3083](../3083-to-anna-butler-10.qmd)
- [Letter 3093](../3093-to-jemima-blackburn-9.qmd)
- [Letter 3127](../3127-to-ann-maria-carter-smith-16.qmd)
- [Letter 3216](../3216-to-lady-frederick-bruce-3.qmd)
- [Letter 3226](../3226-to-the-right-reverend-john-richardson-selwyn.qmd)
- [Letter 3263](../3263-to-anne-isabella-ritchie-2.qmd)
- [Letter 3333](../3333-to-mary-elizabeth-christie-2.qmd)
- [Letter 3339](../3339-to-elizabeth-wordsworth-3.qmd)
- [Letter 3343](../3343-to-mrs-wathen.qmd)
- [Letter 3391](../3391-to-frederick-orridge-macmillan-2.qmd)
- [Letter 3394](../3394-to-sir-walter-besant-2.qmd)
- [Letter 3406](../3406-to-lady-leconfield.qmd)
- [Letter 3411](../3411-to-charlotte-fortescue-yonge-3.qmd)
- [Letter 3416](../3416-to-christabel-rose-coleridge-22.qmd)
- [Letter 3441](../3441-to-mary-drew-2.qmd)
- [Letter 3489](../3489-to-margaret-helen-moberly-4.qmd)
- [Letter 7710](../7710-to-sir-john-taylor-coleridge.qmd)
- [Letter 7727](../7727-to-sir-john-taylor-coleridge.qmd)
- [Letter 19670](../19670-alexander-macmillan-to-charlotte-mary-yonge.qmd)
- [Letter 19816](../19816-to-miss-manning.qmd)
- [Letter 19905](../19905-to-john-william-parker-jr.qmd)

