---
title: "Modern Broods, or, Developments Unlooked For. "
book_id: 251
sort_title: "Modern Broods, or, Developments Unlooked For. "
---

## Publication Information

**Date:** 1900

**Genre:** Fiction (modern)

**Publisher:** London and New York: Macmillan and Company.

**Notes:** This includes characters from <i>The Castle Builders,</i> <i>The Daisy Chain, The Stokesley Secret, Hopes and Fears, The Pillars of the House, The Two Sides of the Shield, Beechcroft at Rockstone, The Long Vacation </i>and<i> </i>‘Come to her Kingdom’.

## Letters Mentioning This Work

- [Letter 2859](../2859-to-christabel-rose-coleridge-115.qmd)
- [Letter 3415](../3415-to-christabel-rose-coleridge-23.qmd)
- [Letter 3416](../3416-to-christabel-rose-coleridge-22.qmd)
- [Letter 3418](../3418-to-christabel-rose-coleridge-24.qmd)
- [Letter 3422](../3422-to-christabel-rose-coleridge-32.qmd)
- [Letter 3423](../3423-to-christabel-rose-coleridge-33.qmd)
- [Letter 3427](../3427-to-christabel-rose-coleridge-35.qmd)
- [Letter 3461](../3461-to-christabel-rose-coleridge-46.qmd)
- [Letter 3473](../3473-to-christabel-rose-coleridge-55.qmd)
- [Letter 3476](../3476-to-george-lillie-craik-16.qmd)
- [Letter 19000](../19000-to-john-st-loe-strachey.qmd)

