---
title: "History of France.Pt. 8 in A Historical Course for Schools, edited by E.A. Freeman"
book_id: 99
sort_title: "History of France."
---

## Publication Information

**Date:** 1879

**Genre:** Non-fiction: history

**Publisher:** London and New York: Macmillan and Company.

**Notes:** Although this book is dated 1872 both by Coleridge, <i>Life</i> and in <i>A Chaplet for Charlotte Yonge</i>, followed by <i>NCBEL</i>, that seems to be the date of the commencement of Freeman's 'Historical Course for Schools' series rather than of the publication of CMY's <i>France</i>. It was advertised as published 'this day' in <i>John Bull</i> (26 April 1879) 257.





It is to be distinguished from the work of the same title, published in 1878, also by Macmillan,  which CMY contributed to the 'History Primers' series edited by J. R. Green.  The latter has eight chapters rather than ten and is aimed at younger children.

## Letters Mentioning This Work

- [Letter 2514](../2514-to-edward-augustus-freeman-9.qmd)
- [Letter 2521](../2521-to-edward-augustus-freeman-10.qmd)
- [Letter 2522](../2522-to-alexander-macmillan-121.qmd)
- [Letter 2526](../2526-to-george-lillie-craik-19.qmd)
- [Letter 2531](../2531-to-george-lillie-craik-20.qmd)
- [Letter 2562](../2562-edward-augustus-freeman-to-charlotte-mary-yonge.qmd)
- [Letter 2571](../2571-to-george-lillie-craik-24.qmd)
- [Letter 2586](../2586-to-george-lillie-craik-27.qmd)
- [Letter 2591](../2591-to-alexander-macmillan-124.qmd)
- [Letter 2594](../2594-to-alexander-macmillan-125.qmd)
- [Letter 2597](../2597-to-alexander-macmillan-127.qmd)
- [Letter 2599](../2599-to-george-lillie-craik-30.qmd)
- [Letter 2603](../2603-to-edward-augustus-freeman-11.qmd)
- [Letter 2622](../2622-to-george-lillie-craik-37.qmd)
- [Letter 2629](../2629-to-george-lillie-craik-43.qmd)
- [Letter 2657](../2657-to-alexander-macmillan-134.qmd)
- [Letter 2664](../2664-to-george-lillie-craik-50.qmd)

