---
title: "The Prince and the Page: A Story of the Last CrusadeBy the author of “The Heir of Redclyffe.”"
book_id: 61
sort_title: "Prince and the Page: A Story of the Last Crusade"
---

## Publication Information

**Date:** 1866

**Genre:** Fiction (historical)

**Publisher:** London and Cambridge: Macmillan and Co.,

## Letters Mentioning This Work

- [Letter 1985](../1985-to-alexander-macmillan-25.qmd)
- [Letter 2047](../2047-to-alexander-macmillan-50.qmd)
- [Letter 2049](../2049-alexander-macmillan-to-charlotte-mary-yonge-35.qmd)
- [Letter 2050](../2050-to-alexander-macmillan-51.qmd)
- [Letter 2051](../2051-alexander-macmillan-to-charlotte-mary-yonge-36.qmd)
- [Letter 2053](../2053-alexander-macmillan-to-charlotte-mary-yonge-38.qmd)
- [Letter 2057](../2057-to-ellen-julia-johns-7.qmd)
- [Letter 2058](../2058-to-alexander-macmillan-54.qmd)
- [Letter 2060](../2060-alexander-macmillan-to-charlotte-mary-yonge-39.qmd)
- [Letter 2061](../2061-to-alexander-macmillan-55.qmd)
- [Letter 2065](../2065-to-alexander-macmillan-56.qmd)
- [Letter 2079](../2079-to-alexander-macmillan-60.qmd)
- [Letter 2080](../2080-to-alexander-macmillan-61.qmd)
- [Letter 2083](../2083-to-alexander-macmillan-62.qmd)
- [Letter 2084](../2084-to-alexander-macmillanm066-1865-12-08.qmd)
- [Letter 2085](../2085-to-alexander-macmillan-63.qmd)
- [Letter 2089](../2089-to-alexander-macmillan-66.qmd)
- [Letter 2095](../2095-to-alexander-macmillan-67.qmd)
- [Letter 2100](../2100-to-alexander-macmillan-69.qmd)
- [Letter 2119](../2119-to-alexander-macmillan-76.qmd)
- [Letter 2151](../2151-to-edward-augustus-freeman.qmd)
- [Letter 2660](../2660-to-alexander-macmillan-135.qmd)

