---
title: "Biographies of Good Women, chiefly by contributors to ‘The Monthly Packet’.Edited by the author of “The Heir of Redclyffe.” First Series."
book_id: 43
sort_title: "Biographies of Good Women, chiefly by contributors to ‘The Monthly Packet’."
---

## Publication Information

**Date:** 1862

**Genre:** Non-fiction: biography

**Publisher:** John and Charles Mozley, 6, Paternoster Row, London; Masters and Co., 78, New Bond Street, London.

**Notes:** The biographies of Lady Grisell Baillie, Lady Fanshawe, the Countess of Balcarres, Elizabeth Smith and Madame Swetchine are “By the author of ‘The Heir of Redclyffe’”. 





Olympia Morata and Amalie Sieveking are signed E.T. and the work of Emily Taylor. So, according to CMY, is the unsigned article on Mum Bet (perhaps unsigned because derivative of the work of Harriet Martineau). Anna Gurney is signed by Sarah Austin. Princess Galitzin is signed H. D.. Mrs Hutchinson, Caroline Perthes and Lady Russell are attributed to 'the author of Magdalen Stafford', who may have been Mrs Bromfield.   Elizabeth Carter and Anne Grant of Laggan are unsigned and the work of Ann Carter Smith.  Elizabeth Fry is unsigned.





 A second series of biographies was published in 1865.

## Letters Mentioning This Work

- [Letter 1810](../1810-to-ann-maria-carter-smith-38.qmd)
- [Letter 1824](../1824-to-ann-maria-carter-smith-44.qmd)
- [Letter 1826](../1826-to-ann-maria-carter-smith-45.qmd)
- [Letter 1841](../1841-to-ann-maria-carter-smith-48.qmd)
- [Letter 1843](../1843-to-ann-maria-carter-smith-49.qmd)
- [Letter 1858](../1858-to-henrietta-elizabeth-fursdon-5.qmd)
- [Letter 1859](../1859-to-ann-maria-carter-smith-52.qmd)
- [Letter 1865](../1865-to-ann-maria-carter-smith-53.qmd)
- [Letter 1887](../1887-to-ann-maria-carter-smith-60.qmd)
- [Letter 1894](../1894-to-francois-pierre-guillaume-guizot-2.qmd)
- [Letter 2101](../2101-to-alexander-macmillan-70.qmd)

