---
title: "The Life of John Coleridge Patteson, Missionary Bishop of the Melanesian Islands2 vols"
book_id: 102
sort_title: "Life of John Coleridge Patteson, Missionary Bishop of the Melanesian Islands"
---

## Publication Information

**Date:** 1873

**Genre:** Non-fiction: biography

**Publisher:** London and New York: Macmillan and Company.

## Letters Mentioning This Work

- [Letter 1829](../1829-to-frances-sophia-coleridge-patteson-3.qmd)
- [Letter 1840](../1840-from-the-reverend-john-coleridge-patteson-to-charlotte-mary-yonge-3.qmd)
- [Letter 1862](../1862-from-the-reverend-john-coleridge-patteson-to-charlotte-mary-yonge.qmd)
- [Letter 1885](../1885-from-the-right-reverend-john-coleridge-patteson-to-charlotte-mary-yonge-3.qmd)
- [Letter 1900](../1900-from-the-right-reverend-john-coleridge-patteson-to-charlotte-mary-yonge-4.qmd)
- [Letter 1951](../1951-from-the-right-reverend-john-coleridge-patteson-to-charlotte-mary-yonge-5.qmd)
- [Letter 1954](../1954-from-the-right-reverend-john-coleridge-patteson-to-charlotte-mary-yonge-6.qmd)
- [Letter 2059](../2059-from-the-right-reverend-john-coleridge-patteson-to-charlotte-mary-yonge-7.qmd)
- [Letter 2120](../2120-from-the-right-reverend-john-coleridge-patteson-to-charlotte-mary-yonge-8.qmd)
- [Letter 2127](../2127-from-the-right-reverend-john-coleridge-patteson-to-charlotte-mary-yonge.qmd)
- [Letter 2134](../2134-the-right-reverend-john-coleridge-patteson-to-charlotte-mary-yonge-2.qmd)
- [Letter 2138](../2138-the-right-reverend-john-coleridge-patteson-to-charlotte-mary-yonge-3.qmd)
- [Letter 2147](../2147-the-right-reverend-john-coleridge-patteson-to-charlotte-mary-yonge-4.qmd)
- [Letter 2154](../2154-the-right-reverend-john-coleridge-patteson-to-charlotte-mary-yonge-5.qmd)
- [Letter 2224](../2224-the-right-reverend-john-coleridge-patteson-to-charlotte-mary-yonge-6.qmd)
- [Letter 2230](../2230-the-right-reverend-john-coleridge-patteson-to-charlotte-mary-yonge-7.qmd)
- [Letter 2257](../2257-the-right-reverend-john-coleridge-patteson-to-charlotte-mary-yonge-8.qmd)
- [Letter 2273](../2273-the-right-reverend-john-coleridge-patteson-to-charlotte-mary-yonge-9.qmd)
- [Letter 2295](../2295-the-right-reverend-john-coleridge-patteson-to-charlotte-mary-yonge-10.qmd)
- [Letter 2355](../2355-the-right-reverend-john-coleridge-patteson-to-charlotte-mary-yonge-11.qmd)
- [Letter 2429](../2429-to-mary-anne-dyson-21.qmd)
- [Letter 2432](../2432-to-mary-ann-moberly-6-3.qmd)
- [Letter 2433](../2433-to-an-unknown-person-9.qmd)
- [Letter 2435](../2435-to-sir-william-heathcote-bt-4.qmd)
- [Letter 2444](../2444-to-sir-william-heathcote-bt-8.qmd)
- [Letter 2445](../2445-to-the-reverend-edward-coleridge.qmd)
- [Letter 2447](../2447-to-elizabeth-wordsworth-5.qmd)
- [Letter 2450](../2450-to-the-right-reverend-samuel-wilberforce-2.qmd)
- [Letter 2463](../2463-to-george-richmond.qmd)
- [Letter 2482](../2482-to-mary-caroline-coleridge.qmd)
- [Letter 2483](../2483-the-reverend-derwent-coleridge-to-charlotte-mary-yonge.qmd)
- [Letter 2484](../2484-to-the-reverend-john-frederick-lloyd.qmd)
- [Letter 2486](../2486-to-alexander-macmillan-118.qmd)
- [Letter 2493](../2493-to-alexander-macmillan-119.qmd)
- [Letter 2494](../2494-to-alexander-macmillan-120.qmd)
- [Letter 2496](../2496-to-an-unknown-woman-40.qmd)
- [Letter 2512](../2512-to-george-lillie-craik-18.qmd)
- [Letter 2529](../2529-to-henry-graves.qmd)
- [Letter 2621](../2621-to-george-lillie-craik-36.qmd)
- [Letter 2622](../2622-to-george-lillie-craik-37.qmd)
- [Letter 2806](../2806-to-frances-sophia-coleridge-patteson-7.qmd)
- [Letter 3078](../3078-to-an-unknown-man-3.qmd)
- [Letter 3144](../3144-from-the-reverend-john-coleridge-patteson-to-charlotte-mary-yonge-2.qmd)
- [Letter 3472](../3472-to-george-lillie-craik-17.qmd)
- [Letter 7783](../7783-to-sir-john-taylor-coleridge.qmd)
- [Letter 7831](../7831-to-the-reverend-edward-coleridge.qmd)
- [Letter 19453](../19453-to-arthur-duke-yonge.qmd)

