---
title: "The Pillars of the House, or, Under Wode, Under Rode. 4 vols."
book_id: 109
sort_title: "Pillars of the House, or, Under Wode, Under Rode"
---

## Publication Information

**Date:** 1874

**Genre:** Fiction (modern)

**Publisher:** London and New York: Macmillan and Company.

**Notes:** Characters from <i>Countess Kate</i>, <i>The Pillars of the House</i> and <i>The Castle Builders</i> appear in this novel.

## Letters Mentioning This Work

- [Letter 2369](../2369-to-christabel-rose-coleridge-61.qmd)
- [Letter 2378](../2378-to-ellen-julia-johns-12.qmd)
- [Letter 2437](../2437-to-sir-william-heathcote-bt-5.qmd)
- [Letter 2455](../2455-to-edward-augustus-freeman-4.qmd)
- [Letter 2489](../2489-to-elizabeth-wordsworth-6.qmd)
- [Letter 2652](../2652-to-messrs-macmillan-7.qmd)
- [Letter 2660](../2660-to-alexander-macmillan-135.qmd)
- [Letter 2906](../2906-to-an-unknown-man-21.qmd)
- [Letter 3216](../3216-to-lady-frederick-bruce-3.qmd)
- [Letter 3305](../3305-to-augusta-boevey-pode-2.qmd)
- [Letter 3333](../3333-to-mary-elizabeth-christie-2.qmd)
- [Letter 3334](../3334-to-mary-elizabeth-christie-3.qmd)
- [Letter 3339](../3339-to-elizabeth-wordsworth-3.qmd)
- [Letter 3343](../3343-to-mrs-wathen.qmd)
- [Letter 3345](../3345-to-a-member-of-the-bigg-wither-family.qmd)
- [Letter 3414](../3414-to-elizabeth-harcourt-mitchell.qmd)
- [Letter 3422](../3422-to-christabel-rose-coleridge-32.qmd)
- [Letter 19816](../19816-to-miss-manning.qmd)

