---
title: "A History of Christian Names. 2 vols. By the author of “The Heir of Redclyffe,” “Landmarks of History.”"
book_id: 48
sort_title: "History of Christian Names"
---

## Publication Information

**Date:** 1863

**Genre:** Non-fiction: history, onomastics.

**Publisher:** John W Parker and Son West Strand, London

**Notes:** A revised edition was published in 1884.  The book drew on a long-standing interest of CMY's, which she had expressed in a series of articles on 'Name-fancying', published in <i>MP</i> (May 1852-August 1862).

## Letters Mentioning This Work

- [Letter 1812](../1812-to-jemima-blackburn-11.qmd)
- [Letter 1814](../1814-to-susanna-warren-3.qmd)
- [Letter 1828](../1828-to-susanna-warren-4.qmd)
- [Letter 1832](../1832-to-william-butler-bourn.qmd)
- [Letter 1833](../1833-to-an-unknown-woman-11.qmd)
- [Letter 1848](../1848-to-the-reverend-william-george-henderson.qmd)
- [Letter 1874](../1874-to-john-william-parker-sr.qmd)
- [Letter 1880](../1880-to-the-reverend-henry-octavius-coxe-3.qmd)
- [Letter 1901](../1901-to-frederick-james-furnivall-2.qmd)
- [Letter 1908](../1908-to-an-unknown-man-7.qmd)
- [Letter 1917](../1917-to-alexander-macmillan-6.qmd)
- [Letter 1930](../1930-to-alexander-macmillan-9.qmd)
- [Letter 1990](../1990-to-an-unknown-man-9.qmd)
- [Letter 2014](../2014-to-alexander-macmillan-37.qmd)
- [Letter 2015](../2015-alexander-macmillan-to-charlotte-mary-yonge-21.qmd)
- [Letter 2030](../2030-to-alexander-macmillan-43.qmd)
- [Letter 2048](../2048-to-an-unknown-woman-75.qmd)
- [Letter 2376](../2376-to-edward-augustus-freeman-2.qmd)
- [Letter 2396](../2396-to-alexander-macmillan-117.qmd)
- [Letter 2402](../2402-to-arthur-john-butler-12.qmd)
- [Letter 2426](../2426-to-edward-augustus-freeman-3.qmd)
- [Letter 2589](../2589-to-george-lillie-craik-29.qmd)
- [Letter 2620](../2620-to-george-lillie-craik-35.qmd)
- [Letter 2768](../2768-to-george-lillie-craik-57.qmd)
- [Letter 3023](../3023-to-anna-butler-2.qmd)
- [Letter 3024](../3024-to-anna-butler-3.qmd)
- [Letter 3038](../3038-to-anna-butler-4.qmd)
- [Letter 3533](../3533-to-an-unknown-woman-47.qmd)
- [Letter 20002](../20002-to-edith-sophia-jacob.qmd)

