---
title: "The Pupils of St. John the DivineBy the author of “The Heir of Redclyffe.”"
book_id: 72
sort_title: "Pupils of St. John the Divine"
---

## Publication Information

**Date:** 1868

**Genre:** Non-fiction: history

**Publisher:** London and New York: Macmillan and Company.

**Notes:** Macmillan’s Sunday Library (originally the Sunday Library for Household Reading) was published in monthly parts at 1<i>s.</i> each (of which the <i>Pupils</i> formed the first 3 parts) and quarterly volumes at 4<i>s.</i> each (of which it formed volume I).

## Letters Mentioning This Work

- [Letter 2170](../2170-alexander-macmillan-to-charlotte-mary-yonge-48.qmd)
- [Letter 2172](../2172-alexander-macmillan-to-charlotte-mary-yonge-50.qmd)
- [Letter 2174](../2174-to-alexander-macmillan-86.qmd)
- [Letter 2175](../2175-alexander-macmillan-to-charlotte-mary-yonge-51.qmd)
- [Letter 2180](../2180-alexander-macmillan-to-charlotte-mary-yonge-52.qmd)
- [Letter 2181](../2181-to-alexander-macmillan-87.qmd)
- [Letter 2182](../2182-alexander-macmillan-to-charlotte-mary-yonge-53.qmd)
- [Letter 2183](../2183-to-alexander-macmillan-88.qmd)
- [Letter 2186](../2186-to-alexander-macmillan-89.qmd)
- [Letter 2191](../2191-alexander-macmillan-to-charlotte-mary-yonge-55.qmd)
- [Letter 2192](../2192-frances-martin-to-alexander-macmillan.qmd)
- [Letter 2193](../2193-to-alexander-macmillan-91.qmd)
- [Letter 2194](../2194-alexander-macmillan-to-charlotte-mary-yonge-56.qmd)
- [Letter 2200](../2200-to-alexander-macmillan-92.qmd)
- [Letter 2202](../2202-george-lillie-craik-to-charlotte-mary-yonge-3.qmd)
- [Letter 2204](../2204-george-lillie-craik-to-charlotte-mary-yonge.qmd)
- [Letter 2213](../2213-to-alexander-macmillan-93.qmd)
- [Letter 2214](../2214-alexander-macmillan-to-charlotte-mary-yonge-60.qmd)
- [Letter 2216](../2216-alexander-macmillan-to-frances-martin.qmd)
- [Letter 2219](../2219-alexander-macmillan-to-charlotte-mary-yonge-61.qmd)
- [Letter 2226](../2226-alexander-macmillan-to-charlotte-mary-yonge-62.qmd)
- [Letter 2228](../2228-alexander-macmillan-to-charlotte-mary-yonge-63.qmd)
- [Letter 2229](../2229-alexander-macmillan-to-charlotte-mary-yonge-64.qmd)
- [Letter 2237](../2237-alexander-macmillan-to-charlotte-mary-yonge-69.qmd)
- [Letter 2238](../2238-alexander-macmillan-to-charlotte-mary-yonge-70.qmd)
- [Letter 2242](../2242-alexander-macmillan-to-charlotte-mary-yonge.qmd)
- [Letter 2247](../2247-alexander-macmillan-to-charlotte-mary-yonge-73.qmd)
- [Letter 2308](../2308-to-alexander-macmillan-107.qmd)
- [Letter 2621](../2621-to-george-lillie-craik-36.qmd)
- [Letter 2652](../2652-to-messrs-macmillan-7.qmd)

