---
title: "Scripture Readings for Schools and Families. With comments by Charlotte M. Yonge. 5 vols"
book_id: 87
sort_title: "Scripture Readings for Schools and Families"
---

## Publication Information

**Date:** 1871-1879

**Genre:** Non-fiction: theology (bible selections)

**Publisher:** London and New York: Macmillan and Co

**Notes:** Two versions were available: the teacher's with comments at  3<i>s.</i> 6<i>d.</i> and a cheaper one for the pupils without comments at 1<i>s.</i> 6<i>d.</i>.  In the former the 'Reading' consists of about a page in small type;  the 'Comment' slightly more in larger type. 




## Letters Mentioning This Work

- [Letter 2356](../2356-to-louisa-anne-gibbs.qmd)
- [Letter 2381](../2381-to-an-unknown-woman-or-to-alexander-macmillan.qmd)
- [Letter 2388](../2388-to-alexander-macmillan-116.qmd)
- [Letter 2486](../2486-to-alexander-macmillan-118.qmd)
- [Letter 2521](../2521-to-edward-augustus-freeman-10.qmd)
- [Letter 2569](../2569-to-george-lillie-craik-23.qmd)
- [Letter 2621](../2621-to-george-lillie-craik-36.qmd)
- [Letter 2636](../2636-to-george-lillie-craik-45.qmd)
- [Letter 2652](../2652-to-messrs-macmillan-7.qmd)
- [Letter 2665](../2665-to-henriette-elizabeth-de-witt.qmd)
- [Letter 20015](../20015-to-an-unknown-man.qmd)

