---
title: "The Story of the Christians and the Moors in Spain."
book_id: 126
sort_title: "Story of the Christians and the Moors in Spain"
---

## Publication Information

**Date:** 1878

**Genre:** Non-fiction: history

**Publisher:** London and New York: Macmillan and Company.

## Letters Mentioning This Work

- [Letter 2604](../2604-to-george-lillie-craik-31.qmd)
- [Letter 2609](../2609-to-alexander-macmillan-128.qmd)
- [Letter 2611](../2611-to-alexander-macmillan-129.qmd)
- [Letter 2614](../2614-to-george-lillie-craik-32.qmd)
- [Letter 2615](../2615-to-george-lillie-craik-33.qmd)
- [Letter 2617](../2617-to-george-lillie-craik-34.qmd)
- [Letter 2620](../2620-to-george-lillie-craik-35.qmd)
- [Letter 2621](../2621-to-george-lillie-craik-36.qmd)
- [Letter 2622](../2622-to-george-lillie-craik-37.qmd)
- [Letter 2625](../2625-to-george-lillie-craik-39.qmd)
- [Letter 2626](../2626-to-george-lillie-craik-40.qmd)
- [Letter 2627](../2627-to-george-lillie-craik-41.qmd)
- [Letter 2628](../2628-to-george-lillie-craik-42.qmd)
- [Letter 2649](../2649-to-alexander-macmillan-132.qmd)
- [Letter 2651](../2651-to-alexander-macmillan-133.qmd)
- [Letter 2655](../2655-to-harper-bros-2.qmd)
- [Letter 2657](../2657-to-alexander-macmillan-134.qmd)
- [Letter 2658](../2658-to-messrs-macmillan.qmd)
- [Letter 2659](../2659-to-george-lillie-craik-49.qmd)
- [Letter 2664](../2664-to-george-lillie-craik-50.qmd)
- [Letter 2673](../2673-to-george-lillie-craik-51.qmd)
- [Letter 3257](../3257-to-george-lillie-craik-14.qmd)

