---
title: "Warne’s Victoria Tales and Stories series. Edited by the author of “The Heir of Redclyffe."
book_id: 211
sort_title: "Warne’s Victoria Tales and Stories series. Edited by the author of “The Heir of Redclyffe."
---

## Publication Information

**Date:** n.d. [1868-1871]

**Genre:** Edited fiction (by others)

**Publisher:** London: Frederick Warne and Co.

**Notes:** The volumes in this series are not by CMY, but are sometimes catalogued as by her.  Titles include <i>Ella’s Dream</i> [1870], <i>Mary, Mary, Quite Contrary</i> [1870], <i>Cloudland</i>, <i>Esther Stanhope, or, The Crowning Delight, Lost in the Lebanon, The Knight of the Feathery Sword,  Sarah Watkins, or, Crumbs for the Birds.</i> By E. E. G. B., <i>Hasty Harry, A Bit of Fun, The Old School-room Piano, The Virtue of Patience, Alice's Watch, Wax Matches and Wooden Ones, Carrie's Two Victories, Harry's Snow-shoes, Lost on the Line, Summer Arithmetic </i>and <i>The Flax Gatherers</i>.   The <i>MP</i> (April 1871), 418, recommended <i>Mrs Filby's Maria</i> and <i>Silvertongue</i> from the same series. The former is referred to in a letter by CMY and was probably by her correspondent Anne Mercier. Although neither of the latter has a separate entry in either COPAC or WorldCat, Cambridge University Library holds a group catalogued as 'Victoria Tales and Stories, Packet F', 12 volumes in paper wrapper, which consist of: <i>A Bit of Fun, Cloudland, Found in the Fog, Hasty Harry, Lost on the Line, The Flax Gatherers, Wax Matches and Wooden Ones, The Old Bottle, Mrs. Filley's Maria, The Hunt Ribbon, The story of Dog Acis, Silver Tongue</i> and <i>Responsibility</i>  It also holds a similar 'Packet N', consisting of <i>Alice's Watch, Carrie's Two Victories, Ella's Dream, The Old Schoolroom Piano, The Knight of the Feathery Sword, A Girl's Adventure, To-Morrow, The Virtue of Patience, Lost in the Lebanon, Henry's Snow-Shoes, Mary, Mary, quite Contrary and Summer Arithmetic</i>





See also Warne’s Star of Hope series, for another group of tales sometimes erroneously attributed to CMY.

## Letters Mentioning This Work

- [Letter 2282](../2282-to-alexander-macmillan-102.qmd)
- [Letter 2305](../2305-to-anne-mercier-7.qmd)
- [Letter 2318](../2318-to-anne-mercier-3.qmd)
- [Letter 2366](../2366-to-anne-mercier-8.qmd)
- [Letter 2694](../2694-to-anne-mercier.qmd)
- [Letter 3576](../3576-to-the-author-of-%e2%80%98ella%e2%80%99s-dream%e2%80%99.qmd)
- [Letter 18768](../18768-to-an-unknown-woman.qmd)

