---
title: "Bye-words: A Collection of Tales Old and New."
book_id: 135
sort_title: "Bye-words: A Collection of Tales Old and New."
---

## Publication Information

**Date:** 1880

**Genre:** Fiction

**Publisher:** London and New York: Macmillan and Company.

**Notes:** The stories included were ‘The Boy Bishop’ (first publishedin  <i>MP</i> Christmas 1878, 620-624); ‘One will and three ways’ (<i>MP</i> Christmas 1877) 124-8; ‘Kaspar's summer dream’ (<i>MP</i> Christmas 1876, 16-34); ‘Buy a Broom’; ‘The Travels of Two Kits’; Selma's secret sighs’ (published under the pseudonym 'Euphemia Arrowsmith' in <i>MP</i> Christmas 1874, 97-108); ‘Our ghost at Fantford; ‘Anna's Wedding Cake’;<i> </i>‘Autobiography of Patty Applecheeks’; and ‘A Holiday Engagement; or, The Campbells are Coming’

## Letters Mentioning This Work

- [Letter 2678](../2678-to-alexander-macmillan-137.qmd)
- [Letter 2679](../2679-to-alexander-macmillan-138.qmd)
- [Letter 2680](../2680-to-alexander-macmillan-139.qmd)
- [Letter 2681](../2681-to-alexander-macmillan-140.qmd)
- [Letter 2682](../2682-to-alexander-macmillan-141.qmd)
- [Letter 2683](../2683-to-george-lillie-craik-52.qmd)
- [Letter 2684](../2684-to-alexander-macmillan-142.qmd)
- [Letter 2712](../2712-to-the-commissioners-of-customs-and-excise.qmd)

