---
title: "The Heir of RedclyffeBy the author of “The Two Guardians,” “Henrietta’s Wish,” “The Kings of England.” 2 vols."
book_id: 15
sort_title: "Heir of Redclyffe"
---

## Publication Information

**Date:** 1853

**Genre:** Fiction (modern)

**Publisher:** John W Parker and Son, West Strand, London.

## Letters Mentioning This Work

- [Letter 1778](../1778-to-ann-maria-carter-smith-27.qmd)
- [Letter 1905](../1905-to-alexander-macmillan-2.qmd)
- [Letter 1907](../1907-to-alexander-macmillan-3.qmd)
- [Letter 1914](../1914-to-alexander-macmillan-5.qmd)
- [Letter 1916](../1916-alexander-macmillan-to-charlotte-mary-yonge-4.qmd)
- [Letter 1991](../1991-to-ann-maria-carter-smith-70.qmd)
- [Letter 2010](../2010-alexander-macmillan-to-charlotte-mary-yonge-19.qmd)
- [Letter 2095](../2095-to-alexander-macmillan-67.qmd)
- [Letter 2156](../2156-to-alexander-macmillan-85.qmd)
- [Letter 2330](../2330-to-mary-ann-dyson-2.qmd)
- [Letter 2337](../2337-to-messrs-macmillan-5.qmd)
- [Letter 2506](../2506-william-francis-cowper-temple-to-charlotte-mary-yonge.qmd)
- [Letter 2579](../2579-to-messrs-macmillan-6.qmd)
- [Letter 2581](../2581-to-george-lillie-craik-26.qmd)
- [Letter 2652](../2652-to-messrs-macmillan-7.qmd)
- [Letter 2678](../2678-to-alexander-macmillan-137.qmd)
- [Letter 2748](../2748-to-george-lillie-craik-53.qmd)
- [Letter 2766](../2766-to-john-duke-pode.qmd)
- [Letter 2909](../2909-to-arthur-llewelyn-roberts.qmd)
- [Letter 2918](../2918-james-augustus-henry-murray-to-charlotte-mary-yonge.qmd)
- [Letter 2919](../2919-to-james-augustus-henry-murray.qmd)
- [Letter 2966](../2966-to-mary-anne-dyson-6.qmd)
- [Letter 2967](../2967-to-mary-anne-dyson-7.qmd)
- [Letter 2969](../2969-to-mary-anne-dyson-9.qmd)
- [Letter 2971](../2971-to-mary-anne-dyson-11.qmd)
- [Letter 2972](../2972-to-mary-anne-dyson-12.qmd)
- [Letter 2975](../2975-to-elizabeth-barnett-3.qmd)
- [Letter 2979](../2979-to-anne-yonge-25.qmd)
- [Letter 3006](../3006-to-mary-anne-dyson-13.qmd)
- [Letter 3007](../3007-to-mary-anne-dyson-14.qmd)
- [Letter 3015](../3015-to-anne-yonge-28.qmd)
- [Letter 3018](../3018-to-elizabeth-roberts-29.qmd)
- [Letter 3019](../3019-to-mary-anne-dyson-15.qmd)
- [Letter 3020](../3020-to-elizabeth-barnett-4.qmd)
- [Letter 3025](../3025-to-elizabeth-roberts-32.qmd)
- [Letter 3030](../3030-to-mary-anne-dyson-18.qmd)
- [Letter 3037](../3037-to-john-william-parker-jr.qmd)
- [Letter 3048](../3048-to-mary-anne-dyson-19.qmd)
- [Letter 3050](../3050-to-john-william-parker-jr-3.qmd)
- [Letter 3053](../3053-to-elizabeth-barnett-6.qmd)
- [Letter 3054](../3054-to-elizabeth-roberts-35.qmd)
- [Letter 3055](../3055-to-anne-yonge-31.qmd)
- [Letter 3073](../3073-to-john-william-parker-jr-6.qmd)
- [Letter 3077](../3077-to-anna-butler-7.qmd)
- [Letter 3097](../3097-sir-william-heathcote-to-caroline-elizabeth-heathcote.qmd)
- [Letter 3127](../3127-to-ann-maria-carter-smith-16.qmd)
- [Letter 3147](../3147-to-elizabeth-barnett-13.qmd)
- [Letter 3333](../3333-to-mary-elizabeth-christie-2.qmd)
- [Letter 3343](../3343-to-mrs-wathen.qmd)
- [Letter 3394](../3394-to-sir-walter-besant-2.qmd)
- [Letter 3493](../3493-the-reverend-john-mason-neale-to-charlotte-mary-yonge.qmd)
- [Letter 3579](../3579-to-an-unknown-woman-22.qmd)
- [Letter 7691](../7691-to-sir-john-taylor-coleridge.qmd)
- [Letter 7710](../7710-to-sir-john-taylor-coleridge.qmd)
- [Letter 7852](../7852-to-john-duke-coleridge.qmd)
- [Letter 19394](../19394-to-mary-anne-dyson.qmd)
- [Letter 19670](../19670-alexander-macmillan-to-charlotte-mary-yonge.qmd)

