---
title: "Cameos from English History: I. From Rollo to Edward.By the author of “The Heir of Redclyffe.”"
book_id: 73
sort_title: "Cameos from English History: I. From Rollo to Edward."
---

## Publication Information

**Date:** 1868

**Genre:** Non-fiction: history

**Publisher:** London and New York: Macmillan and Company.

## Letters Mentioning This Work

- [Letter 2053](../2053-alexander-macmillan-to-charlotte-mary-yonge-38.qmd)
- [Letter 2054](../2054-to-alexander-macmillan-52.qmd)
- [Letter 2139](../2139-to-alexander-macmillan-82.qmd)
- [Letter 2146](../2146-to-alexander-macmillan-84.qmd)
- [Letter 2175](../2175-alexander-macmillan-to-charlotte-mary-yonge-51.qmd)
- [Letter 2226](../2226-alexander-macmillan-to-charlotte-mary-yonge-62.qmd)
- [Letter 2236](../2236-alexander-macmillan-to-charlotte-mary-yonge-68.qmd)
- [Letter 2238](../2238-alexander-macmillan-to-charlotte-mary-yonge-70.qmd)
- [Letter 2241](../2241-alexander-macmillan-to-charlotte-mary-yonge-72.qmd)
- [Letter 2242](../2242-alexander-macmillan-to-charlotte-mary-yonge.qmd)
- [Letter 2247](../2247-alexander-macmillan-to-charlotte-mary-yonge-73.qmd)
- [Letter 2248](../2248-to-alexander-macmillan-97.qmd)
- [Letter 2258](../2258-to-alexander-macmillan-98.qmd)
- [Letter 2265](../2265-to-george-lillie-craik-5.qmd)
- [Letter 2266](../2266-to-george-lillie-craik-6.qmd)
- [Letter 2278](../2278-to-alexander-macmillan-101.qmd)
- [Letter 2286](../2286-to-alexander-macmillan-104.qmd)
- [Letter 2308](../2308-to-alexander-macmillan-107.qmd)
- [Letter 2456](../2456-to-edward-augustus-freeman-5.qmd)
- [Letter 2960](../2960-to-mary-anne-dyson-3.qmd)
- [Letter 2972](../2972-to-mary-anne-dyson-12.qmd)
- [Letter 3315](../3315-to-frederick-orridge-macmillan-9.qmd)
- [Letter 19655](../19655-alexander-macmillan-to-charlotte-mary-yonge.qmd)
- [Letter 19661](../19661-alexander-macmillan-to-charlotte-mary-yonge.qmd)
- [Letter 19664](../19664-alexander-macmillan-to-charlotte-mary-yonge.qmd)
- [Letter 19670](../19670-alexander-macmillan-to-charlotte-mary-yonge.qmd)
- [Letter 19672](../19672-alexander-macmillan-to-charlotte-mary-yonge.qmd)
- [Letter 19674](../19674-alexander-macmillan-to-charlotte-mary-yonge.qmd)

