---
title: "The Trial: More Links of the Daisy Chain2 vols. By the author of “The Heir of Redclyffe.”"
book_id: 53
sort_title: "Trial: More Links of the Daisy Chain"
---

## Publication Information

**Date:** 1864

**Genre:** Fiction (modern)

**Publisher:** London and Cambridge: Macmillan and Company.

**Notes:** This is a sequel to <i>The Daisy Chain.</i> Characters reappear in <i>Modern Broods</i> and <i>The Long Vacation.</i>

## Letters Mentioning This Work

- [Letter 1847](../1847-to-elizabeth-barnett-or-edith-emma-butler.qmd)
- [Letter 1854](../1854-to-ann-maria-carter-smith-51.qmd)
- [Letter 1884](../1884-to-ann-maria-carter-smith-59.qmd)
- [Letter 1890](../1890-to-an-unknown-person-perhaps-elizabeth-barnett.qmd)
- [Letter 1907](../1907-to-alexander-macmillan-3.qmd)
- [Letter 1913](../1913-to-alexander-macmillan-4.qmd)
- [Letter 1916](../1916-alexander-macmillan-to-charlotte-mary-yonge-4.qmd)
- [Letter 1919](../1919-to-alexander-macmillan-7.qmd)
- [Letter 1926](../1926-to-alexander-macmillan-8.qmd)
- [Letter 1927](../1927-alexander-macmillan-to-charlotte-mary-yonge-6.qmd)
- [Letter 1930](../1930-to-alexander-macmillan-9.qmd)
- [Letter 1932](../1932-to-alexander-macmillan-10.qmd)
- [Letter 1933](../1933-to-alexander-macmillan-11.qmd)
- [Letter 1936](../1936-to-alexander-macmillan-12.qmd)
- [Letter 1939](../1939-alexander-macmillan-to-charlotte-mary-yonge-8.qmd)
- [Letter 1940](../1940-to-alexander-macmillan-14.qmd)
- [Letter 1944](../1944-to-alexander-macmillan-15.qmd)
- [Letter 1953](../1953-to-messrs-macmillan-2.qmd)
- [Letter 1955](../1955-alexander-macmillan-to-charlotte-mary-yonge-10.qmd)
- [Letter 1956](../1956-to-messrs-macmillan-3.qmd)
- [Letter 1957](../1957-alexander-macmillan-to-charlotte-mary-yonge-11.qmd)
- [Letter 1958](../1958-to-alexander-macmillan-16.qmd)
- [Letter 1971](../1971-to-alexander-macmillan-17.qmd)
- [Letter 1985](../1985-to-alexander-macmillan-25.qmd)
- [Letter 1987](../1987-alexander-macmillan-to-charlotte-mary-yonge-16.qmd)
- [Letter 2002](../2002-alexander-macmillan-to-charlotte-mary-yonge-17.qmd)
- [Letter 2007](../2007-alexander-macmillan-to-charlotte-mary-yonge-18.qmd)
- [Letter 2652](../2652-to-messrs-macmillan-7.qmd)
- [Letter 2660](../2660-to-alexander-macmillan-135.qmd)
- [Letter 2899](../2899-to-george-lillie-craik-74.qmd)
- [Letter 2906](../2906-to-an-unknown-man-21.qmd)
- [Letter 3226](../3226-to-the-right-reverend-john-richardson-selwyn.qmd)
- [Letter 3343](../3343-to-mrs-wathen.qmd)
- [Letter 7727](../7727-to-sir-john-taylor-coleridge.qmd)
- [Letter 19816](../19816-to-miss-manning.qmd)

