---
title: "The Dove In The Eagle’s Nest. 2 vols. By the author of  “The Heir of Redclyffe.”"
book_id: 62
sort_title: "Dove In The Eagle’s Nest"
---

## Publication Information

**Date:** 1866

**Genre:** Fiction (historical)

**Publisher:** Cambridge and London: Macmillan and Company.

## Letters Mentioning This Work

- [Letter 1985](../1985-to-alexander-macmillan-25.qmd)
- [Letter 1992](../1992-to-the-reverend-henry-octavius-coxe-2.qmd)
- [Letter 1994](../1994-to-alexander-macmillan-28.qmd)
- [Letter 1995](../1995-to-alexander-macmillan-29.qmd)
- [Letter 1997](../1997-to-alexander-macmillan-30.qmd)
- [Letter 2006](../2006-to-alexander-macmillan-34.qmd)
- [Letter 2013](../2013-alexander-macmillan-to-charlotte-mary-yonge-20.qmd)
- [Letter 2014](../2014-to-alexander-macmillan-37.qmd)
- [Letter 2015](../2015-alexander-macmillan-to-charlotte-mary-yonge-21.qmd)
- [Letter 2017](../2017-to-alexander-macmillan-38.qmd)
- [Letter 2018](../2018-alexander-macmillan-to-charlotte-mary-yonge-23.qmd)
- [Letter 2019](../2019-to-alexander-macmillan-39.qmd)
- [Letter 2022](../2022-alexander-macmillan-to-charlotte-mary-yonge-25.qmd)
- [Letter 2026](../2026-to-alexander-macmillan-41.qmd)
- [Letter 2028](../2028-to-alexander-macmillan-42.qmd)
- [Letter 2030](../2030-to-alexander-macmillan-43.qmd)
- [Letter 2032](../2032-alexander-macmillan-to-charlotte-mary-yonge-28.qmd)
- [Letter 2041](../2041-to-alexander-macmillan-47.qmd)
- [Letter 2047](../2047-to-alexander-macmillan-50.qmd)
- [Letter 2049](../2049-alexander-macmillan-to-charlotte-mary-yonge-35.qmd)
- [Letter 2050](../2050-to-alexander-macmillan-51.qmd)
- [Letter 2051](../2051-alexander-macmillan-to-charlotte-mary-yonge-36.qmd)
- [Letter 2058](../2058-to-alexander-macmillan-54.qmd)
- [Letter 2060](../2060-alexander-macmillan-to-charlotte-mary-yonge-39.qmd)
- [Letter 2061](../2061-to-alexander-macmillan-55.qmd)
- [Letter 2062](../2062-alexander-macmillan-to-charlotte-mary-yonge-40.qmd)
- [Letter 2065](../2065-to-alexander-macmillan-56.qmd)
- [Letter 2068](../2068-alexander-macmillan-to-charlotte-mary-yonge-42.qmd)
- [Letter 2072](../2072-alexander-macmillan-to-charlotte-mary-yonge-43.qmd)
- [Letter 2073](../2073-to-alexander-macmillan-57.qmd)
- [Letter 2076](../2076-to-alexander-macmillan-59.qmd)
- [Letter 2079](../2079-to-alexander-macmillan-60.qmd)
- [Letter 2084](../2084-to-alexander-macmillanm066-1865-12-08.qmd)
- [Letter 2096](../2096-to-alexander-macmillan-68.qmd)
- [Letter 2104](../2104-to-alexander-macmillan-72.qmd)
- [Letter 2108](../2108-to-alexander-macmillan-73.qmd)
- [Letter 2109](../2109-to-alexander-macmillan-74.qmd)
- [Letter 2118](../2118-to-alexander-macmillan-75.qmd)
- [Letter 2119](../2119-to-alexander-macmillan-76.qmd)
- [Letter 2121](../2121-to-alexander-macmillanm081-1866-04-26.qmd)
- [Letter 2128](../2128-to-alexander-macmillan-77.qmd)
- [Letter 2631](../2631-to-george-lillie-craik-44.qmd)
- [Letter 2907](../2907-to-george-lillie-craik.qmd)
- [Letter 3225](../3225-to-george-lillie-craik-13.qmd)
- [Letter 3416](../3416-to-christabel-rose-coleridge-22.qmd)
- [Letter 3430](../3430-to-christabel-rose-coleridge-36.qmd)
- [Letter 3441](../3441-to-mary-drew-2.qmd)
- [Letter 3442](../3442-to-christabel-rose-coleridge-37.qmd)
- [Letter 19551](../19551-george-lillie-craik-to-charlotte-mary-yonge.qmd)
- [Letter 19563](../19563-alexander-macmillan-to-charlotte-mary-yonge.qmd)

