---
title: "John Keble’s Parishes: A History of Hursley and Otterbourne.By Charlotte M. Yonge, An Old Inhabitant."
book_id: 247
sort_title: "John Keble’s Parishes: A History of Hursley and Otterbourne."
---

## Publication Information

**Date:** 1898

**Genre:** Non-fiction: history, topography

**Publisher:** London and New York: Macmillan and Co.

## Letters Mentioning This Work

- [Letter 2939](../2939-to-anne-yonge-7.qmd)
- [Letter 3355](../3355-to-helena-heathcote-4.qmd)
- [Letter 3356](../3356-to-beatrice-heathcote-2.qmd)
- [Letter 3360](../3360-to-amelie-claire-leroy.qmd)
- [Letter 3362](../3362-to-frederick-orridge-macmillan-12.qmd)
- [Letter 3368](../3368-to-beatrice-heathcote-3.qmd)
- [Letter 3369](../3369-to-edmund-doidge-anderson-morshead-2.qmd)
- [Letter 3370](../3370-to-helena-heathcote-5.qmd)
- [Letter 3371](../3371-to-beatrice-heathcote.qmd)
- [Letter 3372](../3372-to-frederick-orridge-macmillan-15.qmd)
- [Letter 3375](../3375-to-frederick-orridge-macmillan-16.qmd)
- [Letter 3377](../3377-to-frederick-orridge-macmillan.qmd)
- [Letter 3378](../3378-to-frederick-orridge-macmillan.qmd)
- [Letter 3382](../3382-to-frederick-orridge-macmillan-5.qmd)
- [Letter 3397](../3397-to-matthew-r-bigge.qmd)
- [Letter 3440](../3440-to-mrs-belfield-2.qmd)

