---
title: "John William Parker jr."
person_id: 1143
---

## Biographical Information

(1820-9 Nov 1860)

publisher

In partnership with his father, John William Parker, sr., he published CMY’s early bestsellers of the 1850s such as <i>The Heir of Redclyffe</i>. The firm should not be confused with that of John Henry Parker of Oxford, who published <i>Kenneth</i>. [DLB 106]

## Letters Mentioning This Person

- [Letter 1781](../1781-to-john-william-parker-jr-8.qmd)
- [Letter 1783](../1783-to-john-william-parker-jr.qmd)
- [Letter 1786](../1786-to-john-william-parker-jr-9.qmd)
- [Letter 1793](../1793-to-john-william-parker-jr-10.qmd)
- [Letter 1794](../1794-to-john-william-parker-jr-11.qmd)
- [Letter 1796](../1796-to-john-william-parker-jr-12.qmd)
- [Letter 1799](../1799-to-john-william-parker-jr-13.qmd)
- [Letter 1806](../1806-to-anna-butler.qmd)
- [Letter 1808](../1808-to-william-butler-bourn.qmd)
- [Letter 1826](../1826-to-ann-maria-carter-smith-45.qmd)
- [Letter 1879](../1879-to-ann-maria-carter-smith-56.qmd)
- [Letter 3007](../3007-to-mary-anne-dyson-14.qmd)
- [Letter 3022](../3022-to-elizabeth-roberts-31.qmd)
- [Letter 3025](../3025-to-elizabeth-roberts-32.qmd)
- [Letter 3037](../3037-to-john-william-parker-jr.qmd)
- [Letter 3049](../3049-to-john-william-parker-jr-2.qmd)
- [Letter 3050](../3050-to-john-william-parker-jr-3.qmd)
- [Letter 3051](../3051-to-john-william-parker-jr-4.qmd)
- [Letter 3072](../3072-to-john-william-parker-jr-5.qmd)
- [Letter 3073](../3073-to-john-william-parker-jr-6.qmd)
- [Letter 3080](../3080-to-jemima-blackburn-8.qmd)
- [Letter 3093](../3093-to-jemima-blackburn-9.qmd)
- [Letter 3126](../3126-to-ann-maria-carter-smith-15.qmd)
- [Letter 3127](../3127-to-ann-maria-carter-smith-16.qmd)
- [Letter 3128](../3128-to-ann-maria-carter-smith-17.qmd)
- [Letter 3129](../3129-to-ann-maria-carter-smith-18.qmd)
- [Letter 3131](../3131-to-ann-maria-carter-smith-20.qmd)
- [Letter 3136](../3136-to-ann-maria-carter-smith-23.qmd)
- [Letter 3139](../3139-to-john-william-parker-jr-7.qmd)
- [Letter 3142](../3142-to-ann-maria-carter-smith-25.qmd)
- [Letter 3394](../3394-to-sir-walter-besant-2.qmd)
- [Letter 10615](../10615-to-john-william-parker-jr.qmd)
- [Letter 19905](../19905-to-john-william-parker-jr.qmd)

