---
title: "Anne Yonge"
person_id: 1582
---

## Biographical Information

(28 March 1825-1 Sept 1869)

cousin of CMY

Closest friend of CMY, she shared her birthday with her sister Alethea [Coleridge, <i>Life</i>, 66]

## Letters Mentioning This Person

- [Letter 1787](../1787-to-ann-maria-carter-smith-33.qmd)
- [Letter 1864](../1864-to-charlotte-cordelia-pode.qmd)
- [Letter 1895](../1895-to-anne-yonge-38.qmd)
- [Letter 1896](../1896-to-anne-yonge-39.qmd)
- [Letter 1897](../1897-to-anne-yonge-40.qmd)
- [Letter 1898](../1898-to-anne-yonge-41.qmd)
- [Letter 1899](../1899-to-anne-yonge-42.qmd)
- [Letter 1944](../1944-to-alexander-macmillan-15.qmd)
- [Letter 1956](../1956-to-messrs-macmillan-3.qmd)
- [Letter 1995](../1995-to-alexander-macmillan-29.qmd)
- [Letter 2110](../2110-to-anne-yonge-43.qmd)
- [Letter 2111](../2111-to-anne-yonge-44.qmd)
- [Letter 2117](../2117-to-anne-yonge-45.qmd)
- [Letter 2264](../2264-to-the-reverend-duke-yonge-2.qmd)
- [Letter 2270](../2270-to-mary-anne-moberly-3.qmd)
- [Letter 2271](../2271-to-mary-ann-dyson-6.qmd)
- [Letter 2275](../2275-to-mary-ann-dyson-7.qmd)
- [Letter 2276](../2276-to-mary-anne-moberly-4.qmd)
- [Letter 2280](../2280-to-caroline-elizabeth-cooke-trench-4.qmd)
- [Letter 2281](../2281-to-ann-maria-carter-smith-79.qmd)
- [Letter 2285](../2285-to-anne-yonge.qmd)
- [Letter 2296](../2296-to-anne-elizabeth-mary-anderson-morshead-2.qmd)
- [Letter 2338](../2338-to-the-reverend-duke-yonge.qmd)
- [Letter 2339](../2339-to-mary-yonge-7.qmd)
- [Letter 2340](../2340-to-charlotte-cordelia-yonge-2.qmd)
- [Letter 2342](../2342-to-florence-wilford-5.qmd)
- [Letter 2345](../2345-to-alexander-macmillan-111.qmd)
- [Letter 2347](../2347-to-anne-elizabeth-mary-anderson-morshead-3.qmd)
- [Letter 2352](../2352-to-mary-yonge-9.qmd)
- [Letter 2358](../2358-to-mary-yonge-10.qmd)
- [Letter 2372](../2372-to-mary-yonge-36.qmd)
- [Letter 2881](../2881-to-jean-ingelow.qmd)
- [Letter 2932](../2932-to-anne-yonge.qmd)
- [Letter 2933](../2933-to-anne-yonge-2.qmd)
- [Letter 2934](../2934-to-anne-yonge-3.qmd)
- [Letter 2935](../2935-william-crawley-yonge-to-the-rev-john-yonge-including-charlotte-mary-yonge-to-anne-yonge.qmd)
- [Letter 2936](../2936-to-anne-yonge-4.qmd)
- [Letter 2938](../2938-to-anne-yonge-6.qmd)
- [Letter 2939](../2939-to-anne-yonge-7.qmd)
- [Letter 2940](../2940-to-anne-yonge-8.qmd)
- [Letter 2942](../2942-to-anne-yonge-10.qmd)
- [Letter 2943](../2943-to-anne-yonge-11.qmd)
- [Letter 2945](../2945-to-anne-yonge-12.qmd)
- [Letter 2946](../2946-to-anne-yonge-13.qmd)
- [Letter 2947](../2947-to-anne-yonge-14.qmd)
- [Letter 2948](../2948-to-anne-yonge-15.qmd)
- [Letter 2949](../2949-to-anne-yonge-16.qmd)
- [Letter 2950](../2950-to-anne-yonge-17.qmd)
- [Letter 2951](../2951-to-anne-yonge-18.qmd)
- [Letter 2952](../2952-to-anne-yonge-19.qmd)
- [Letter 2953](../2953-to-anne-yonge-20.qmd)
- [Letter 2954](../2954-to-anne-yonge-21.qmd)
- [Letter 2955](../2955-to-anne-yonge-22.qmd)
- [Letter 2956](../2956-to-anne-yonge-23.qmd)
- [Letter 2957](../2957-anne-yonge-to-mary-yonge-2.qmd)
- [Letter 2977](../2977-to-anne-yonge-24.qmd)
- [Letter 2979](../2979-to-anne-yonge-25.qmd)
- [Letter 2987](../2987-to-anne-yonge-26.qmd)
- [Letter 3015](../3015-to-anne-yonge-28.qmd)
- [Letter 3017](../3017-to-anne-yonge-29.qmd)
- [Letter 3027](../3027-to-anne-yonge-30.qmd)
- [Letter 3032](../3032-frances-mary-yonge-to-the-reverend-john-yonge-2.qmd)
- [Letter 3033](../3033-frances-mary-yonge-to-the-reverend-john-yonge.qmd)
- [Letter 3034](../3034-frances-mary-yonge-to-mary-yonge.qmd)
- [Letter 3036](../3036-anne-yonge-to-the-rev-john-yonge.qmd)
- [Letter 3039](../3039-anne-yonge-to-mary-yonge-3.qmd)
- [Letter 3048](../3048-to-mary-anne-dyson-19.qmd)
- [Letter 3055](../3055-to-anne-yonge-31.qmd)
- [Letter 3060](../3060-to-anne-yonge-32.qmd)
- [Letter 3061](../3061-to-anne-yonge-33.qmd)
- [Letter 3062](../3062-to-anne-yonge-34.qmd)
- [Letter 3063](../3063-to-anne-yonge-35.qmd)
- [Letter 3064](../3064-to-anne-yonge-36.qmd)
- [Letter 3107](../3107-anne-yonge-to-the-rev-john-yonge-2.qmd)
- [Letter 3109](../3109-to-frances-mary-yonge-2.qmd)
- [Letter 3110](../3110-anne-yonge-to-mary-yonge.qmd)
- [Letter 3119](../3119-to-anne-yonge-37.qmd)

