---
title: "The Rt. Rev. George Moberly"
person_id: 1015
---

## Biographical Information

(1803-6 July 1885)

Bishop of Salisbury

He married (22 December 1834) Mary Anne Crokat (1812-1890).  He was headmaster of Winchester College 1835-66;  in 1866 he became Rector of Brighstone, Isle of Wight, then in 1868 Canon of Chester.  He was consecrated bishop of Salisbury 28 Oct 1869. [ODNB; <i>Dulce Domum</i>]

## Letters Mentioning This Person

- [Letter 1809](../1809-to-alice-arbuthnot-moberly-10.qmd)
- [Letter 1817](../1817-to-anne-sturges-bourne-6.qmd)
- [Letter 1840](../1840-from-the-reverend-john-coleridge-patteson-to-charlotte-mary-yonge-3.qmd)
- [Letter 1885](../1885-from-the-right-reverend-john-coleridge-patteson-to-charlotte-mary-yonge-3.qmd)
- [Letter 1900](../1900-from-the-right-reverend-john-coleridge-patteson-to-charlotte-mary-yonge-4.qmd)
- [Letter 2067](../2067-to-fanny.qmd)
- [Letter 2112](../2112-frances-mary-yonge-to-mary-anne-moberly.qmd)
- [Letter 2146](../2146-to-alexander-macmillan-84.qmd)
- [Letter 2166](../2166-to-edith-sophia-jacob-7.qmd)
- [Letter 2176](../2176-to-edith-sophia-jacob-8.qmd)
- [Letter 2215](../2215-to-mary-ann-dyson-5.qmd)
- [Letter 2280](../2280-to-caroline-elizabeth-cooke-trench-4.qmd)
- [Letter 2333](../2333-to-mary-anne-dyson-10-3.qmd)
- [Letter 2347](../2347-to-anne-elizabeth-mary-anderson-morshead-3.qmd)
- [Letter 2352](../2352-to-mary-yonge-9.qmd)
- [Letter 2358](../2358-to-mary-yonge-10.qmd)
- [Letter 2372](../2372-to-mary-yonge-36.qmd)
- [Letter 2390](../2390-to-the-reverend-william-john-butler.qmd)
- [Letter 2398](../2398-the-right-reverend-john-coleridge-patteson-to-charlotte-mary-yonge.qmd)
- [Letter 2410](../2410-to-edith-sophia-jacob-19.qmd)
- [Letter 2442](../2442-to-sir-william-heathcote-bt-6.qmd)
- [Letter 2443](../2443-to-sir-william-heathcote-bt-7.qmd)
- [Letter 2468](../2468-to-elizabeth-barnett-16.qmd)
- [Letter 2490](../2490-to-arthur-john-butler-14.qmd)
- [Letter 2547](../2547-to-mary-yonge-40.qmd)
- [Letter 2695](../2695-to-mary-yonge-49.qmd)
- [Letter 2788](../2788-to-the-hon-mrs-montgomery-moore-3.qmd)
- [Letter 2812](../2812-to-an-unknown-person-11.qmd)
- [Letter 2847](../2847-to-the-very-reverend-william-john-butler-3.qmd)
- [Letter 2953](../2953-to-anne-yonge-20.qmd)
- [Letter 2956](../2956-to-anne-yonge-23.qmd)
- [Letter 2957](../2957-anne-yonge-to-mary-yonge-2.qmd)
- [Letter 2990](../2990-to-the-reverend-dr-george-moberly.qmd)
- [Letter 3033](../3033-frances-mary-yonge-to-the-reverend-john-yonge.qmd)
- [Letter 3036](../3036-anne-yonge-to-the-rev-john-yonge.qmd)
- [Letter 3044](../3044-frances-mary-yonge-to-alice-arbuthnot-moberly-2.qmd)
- [Letter 3048](../3048-to-mary-anne-dyson-19.qmd)
- [Letter 3060](../3060-to-anne-yonge-32.qmd)
- [Letter 3070](../3070-to-alice-arbuthnot-moberly-7.qmd)
- [Letter 3100](../3100-to-miss-moorsom.qmd)
- [Letter 3268](../3268-to-the-reverend-john-frederick-watkinson-bullock-23.qmd)
- [Letter 3333](../3333-to-mary-elizabeth-christie-2.qmd)
- [Letter 7710](../7710-to-sir-john-taylor-coleridge.qmd)
- [Letter 19462](../19462-to-george-lillie-craik.qmd)

