---
title: "The Hon. Mildred Mary (Coleridge) Adams"
person_id: 17
---

## Biographical Information

(1847-14 January 1929)

member of the Gosling Society as ‘Ladybird’

The only daughter of John Duke Coleridge, later 1st Lord Coleridge, and Jane Fortescue Seymour (d. 1878), she married (24 June 1885) Charles Warren Adams.  She had a  row with her father about her marriage which was made public because Adams sued her brother Bernard for libel.  She was a  Gosling as Ladybird 1859- <i>c.</i> 1866;   [PB, Coleridge, <i>Story of a Devonshire House</i>; <i>The Times</i> reports of the libel trial 21, 22 November 1884, 5, 25 June 1885.]

## Letters Mentioning This Person

- [Letter 1844](../1844-to-henrietta-elizabeth-fursdon-3.qmd)
- [Letter 1849](../1849-to-katharine-olive-helmore-4.qmd)
- [Letter 1995](../1995-to-alexander-macmillan-29.qmd)
- [Letter 2078](../2078-to-christabel-rose-coleridge-7.qmd)
- [Letter 2093](../2093-to-frances-mary-peard-9.qmd)
- [Letter 2173](../2173-to-christabel-rose-coleridge-10.qmd)
- [Letter 2352](../2352-to-mary-yonge-9.qmd)
- [Letter 2440](../2440-to-mary-yonge-37.qmd)
- [Letter 2487](../2487-to-the-hon-laura-elizabeth-palmer.qmd)
- [Letter 2637](../2637-to-the-hon-sophia-matilda-palmer-6.qmd)
- [Letter 2782](../2782-to-christabel-rose-coleridge-109.qmd)
- [Letter 2783](../2783-to-christabel-rose-coleridge-110.qmd)
- [Letter 2804](../2804-to-the-reverend-william-harris-walter-bigg-wither.qmd)
- [Letter 2812](../2812-to-an-unknown-person-11.qmd)
- [Letter 3164](../3164-to-florence-wilford-6.qmd)
- [Letter 7691](../7691-to-sir-john-taylor-coleridge.qmd)
- [Letter 7727](../7727-to-sir-john-taylor-coleridge.qmd)
- [Letter 7883](../7883-to-john-duke-coleridge.qmd)

