---
title: "Henry Hucks Gibbs"
person_id: 558
---

## Biographical Information

1st Lord Aldenham

(1819-1907)

cousin of CMY, philologist

He was created (1896) 1st Lord Aldenham.  He married (1845) Louisa Anne Adams (d. 1895).  He was son of George Henry Gibbs (1785-1842), elder brother of William Gibbs of Tyntesfield.  His parents were first cousins, his mother being Caroline, sixth daughter of the Rev. Charles Crawley (1756-1849), Rector of Stowe Nine Churches, Northants., and Mary Gibbs (d.1819).  He was thus CMY’s second cousin. [ODNB, PB 1952]

## Letters Mentioning This Person

- [Letter 1790](../1790-to-anna-butler-18.qmd)
- [Letter 1846](../1846-to-henry-hucks-gibbs.qmd)
- [Letter 1848](../1848-to-the-reverend-william-george-henderson.qmd)
- [Letter 1895](../1895-to-anne-yonge-38.qmd)
- [Letter 1897](../1897-to-anne-yonge-40.qmd)
- [Letter 1964](../1964-to-alexander-macmillan-33.qmd)
- [Letter 1965](../1965-to-frederick-james-furnivall-4.qmd)
- [Letter 1969](../1969-alexander-macmillan-to-charlotte-mary-yonge-12.qmd)
- [Letter 2065](../2065-to-alexander-macmillan-56.qmd)
- [Letter 2409](../2409-to-laura-valentine-3.qmd)
- [Letter 2801](../2801-to-gertrude-mary-ireland-blackburne-3.qmd)
- [Letter 3122](../3122-to-the-reverend-edward-coleridge-3.qmd)
- [Letter 3218](../3218-to-john-athelstan-laurie-riley-2.qmd)

