---
title: "Caroline Elizabeth (Heathcote) Cooke Trench"
person_id: 367
---

## Biographical Information

(1833-24 Nov 1910)

daughter of Sir William Heathcote

Only daughter of the first marriage of Sir William Heathcote, she married (17 Aug 1858) Thomas Richard Frederick Cooke Trench (18 Aug 1829-26 Nov 1902), an Anglo-Irish landowner, and they set about creating a Tractarian country house in Ireland. [Awdry, <i>A Country Gentleman</i>]

## Letters Mentioning This Person

- [Letter 2280](../2280-to-caroline-elizabeth-cooke-trench-4.qmd)
- [Letter 2559](../2559-to-mary-yonge-46.qmd)
- [Letter 2732](../2732-to-caroline-elizabeth-cooke-trench.qmd)
- [Letter 2788](../2788-to-the-hon-mrs-montgomery-moore-3.qmd)
- [Letter 2945](../2945-to-anne-yonge-12.qmd)
- [Letter 2953](../2953-to-anne-yonge-20.qmd)
- [Letter 3097](../3097-sir-william-heathcote-to-caroline-elizabeth-heathcote.qmd)
- [Letter 3112](../3112-to-caroline-elizabeth-heathcote.qmd)
- [Letter 3124](../3124-to-caroline-elizabeth-cooke-trench-2.qmd)
- [Letter 3140](../3140-to-caroline-elizabeth-cooke-trench-3.qmd)
- [Letter 3210](../3210-to-sarah-angelina-acland.qmd)

