---
title: "Ann Catherine (Johns) Lloyd"
person_id: 887
---

## Biographical Information

(Helston 1847/8-1903 Benares)

artist, member of the Gosling Society

Known as Katie, she was an artist and illustrator, daughter of the Rev. [Charles Alexander Johns](person_769.qmd).  She was a Gosling as Kittiwake in 1864-5.  She married in 1873 the Rev. John Henry Lloyd, curate of Wormleighton and subsequently Vicar of Fotheringay.  He was curate to the Rev. William Harrison, Vicar of Wormleighton, who was married to Mary Kingsley (1852-1931), daughter of Charles Kingsley and a friend of Katie Johns.  Both marriages seem to have come to grief.  In 1891 she was living apart from her husband and was matron of Annie Besant’s Women’s Home at 193 Bow Road, a kind of club for girls in the East End, with a few resident matchmakers.  A.H.Nethercot <i>The First Five Lives of Annie Besant</i> (Chicago, U of C P 1960) 337, calls her ‘Mrs Kitty Lloyd’ and describes her as ‘a devoted Theosophist’.  Later her health broke down and she was sent to Ceylon and then to Benares, where she ended her days as the much-loved Matron of the Central Hindu College Boarding House. She is mentioned in her mother’s will (1895), along with her brother Charles, as having brought her to poverty.[ [census returns 1881, 1891; marriage index;  clergy lists; Nethercot, <i>First Five Lives of Annie Besant; Theosophical Yearbook 1933</i>; Obituary in <i>The Theosophist</i>, 1903; info from Professor Joy Dixon]

## Letters Mentioning This Person

- [Letter 1942](../1942-to-ann-catherine-johns.qmd)
- [Letter 1984](../1984-to-alexander-macmillan-24.qmd)
- [Letter 1995](../1995-to-alexander-macmillan-29.qmd)
- [Letter 2003](../2003-to-christabel-rose-coleridge-6.qmd)
- [Letter 2009](../2009-to-ellen-julia-johns-4.qmd)
- [Letter 2050](../2050-to-alexander-macmillan-51.qmd)
- [Letter 2051](../2051-alexander-macmillan-to-charlotte-mary-yonge-36.qmd)
- [Letter 2052](../2052-alexander-macmillan-to-charlotte-mary-yonge-37.qmd)
- [Letter 2053](../2053-alexander-macmillan-to-charlotte-mary-yonge-38.qmd)
- [Letter 2088](../2088-to-ellen-julia-johns-8.qmd)
- [Letter 2209](../2209-to-florence-wilford-3.qmd)
- [Letter 2255](../2255-to-christabel-rose-coleridge-16.qmd)
- [Letter 2279](../2279-to-ellen-julia-johns.qmd)
- [Letter 2345](../2345-to-alexander-macmillan-111.qmd)
- [Letter 2416](../2416-to-christabel-rose-coleridge-66.qmd)
- [Letter 2475](../2475-to-christabel-rose-coleridge-79.qmd)
- [Letter 2587](../2587-to-christabel-rose-coleridge-88.qmd)
- [Letter 2856](../2856-to-christabel-rose-coleridge-114.qmd)
- [Letter 3164](../3164-to-florence-wilford-6.qmd)
- [Letter 3484](../3484-to-ellen-julia-johns-2.qmd)
- [Letter 19875](../19875-to-anna-maria-keary.qmd)

