---
title: "Charlotte (Warren) Latham"
person_id: 840
---

## Biographical Information

(b.Sussex 1801/2)

mother of Margaret Roberts

According to George Ormerod, <i>Parentalia</i> (privately printed 1851), she was the daughter of the Rev. Henry Warren, prebendary of Bangor.  She married, first, the Rev. Ellis Roberts, Vicar of Llanynys, and, secondly (1848), as his second wife, the Rev. Henry Latham.  She was living with the latter at Fittleworth in the 1851 census;  at Tormoham, Torquay in 1871 with her stepdaughter Dina [sic] Latham, daughter Margaret Roberts, and stepgranddaughters Margaret and Katharine Mary Hutchingstone, 11 and 7;  in the 1881 census again at Tormoham with Diana Latham and Margaret Roberts and granddaughter Helen M Latham, 13.  





 See under Grace Latham for the implication that there was a blood relationship between either Charlotte Latham or her first husband and some members of the Latham family.

## Letters Mentioning This Person

- [Letter 2249](../2249-to-edith-sophia-jacob-12.qmd)

