---
title: "The Rev. Charles Alexander Johns"
person_id: 769
---

## Biographical Information

(1811-1874)

naturalist

He taught at Helston Grammar School, when Derwent Coleridge was headmaster, and later ran a prep school at Winton House, Winchester.  He was founder and president of the Winchester Literary and Scientific Society.  He married (1843) Ellen Julia Field (b. Bath 1821/2) Beenham in 1851 census, Watford in 1861.  His father was a Plymouth banker, whose firm had collapsed in 1825. His most famous book was the very popular <i>Flowers of the Field</i> (1851). [ODNB]

## Letters Mentioning This Person

- [Letter 2050](../2050-to-alexander-macmillan-51.qmd)
- [Letter 2057](../2057-to-ellen-julia-johns-7.qmd)
- [Letter 2088](../2088-to-ellen-julia-johns-8.qmd)
- [Letter 2148](../2148-to-edith-coleridge.qmd)
- [Letter 2185](../2185-to-christabel-rose-coleridge-11.qmd)
- [Letter 2201](../2201-to-christabel-rose-coleridge-12.qmd)
- [Letter 2209](../2209-to-florence-wilford-3.qmd)
- [Letter 2438](../2438-to-christabel-rose-coleridge-71.qmd)
- [Letter 2685](../2685-to-mary-rogers.qmd)
- [Letter 2688](../2688-to-ellen-julia-johns-16.qmd)
- [Letter 19064](../19064-to-margaret-julia-argles.qmd)

