---
title: "The Rt.Rev. William Awdry"
person_id: 85
---

## Biographical Information

(14 Jan 1842-4 Jan 1910)

Vicar of Amport, later Bishop of Osaka

Successively Vicar of Amport, suffragan bishop of Southampton (1895),  Bishop of Osaka (1896-8) and South Tokyo (1898-1908), he married (4 August 1868) (Frances) Emily Moberly. Son of Sir John Wither Awdry (1795-1878), chief justice of Bombay, he was brother of Frances Awdry,  Charles Awdry and the Rev. Vere Awdry. His brother Charles Awdry married Margaret Helen Moberly. Sir John Awdry’s mother Jane Bigg was the sister of Sir William Heathcote’s mother Elizabeth (Bigg) Heathcote, and he was therefore cousin to Sir William and to the Rev. William Bigg Wither.  [WWW]

## Letters Mentioning This Person

- [Letter 2440](../2440-to-mary-yonge-37.qmd)
- [Letter 2465](../2465-to-christabel-rose-coleridge-77.qmd)
- [Letter 2469](../2469-to-anne-mercier-6.qmd)
- [Letter 2723](../2723-to-christabel-rose-coleridge-102.qmd)
- [Letter 9109](../9109-to-sarah-harriet-selwyn.qmd)

