---
title: "The Rt. Rev. Samuel Wilberforce"
person_id: 1512
---

## Biographical Information

(1805-1873)

Bishop of Winchester

He married (1828) Emily Sargent (1807-1841);  he served as Bishop of Oxford from December 1845 and, Bishop of Winchester from 1869 to his death [ODNB]

## Letters Mentioning This Person

- [Letter 2215](../2215-to-mary-ann-dyson-5.qmd)
- [Letter 2225](../2225-to-the-right-reverend-samuel-wilberforce.qmd)
- [Letter 2347](../2347-to-anne-elizabeth-mary-anderson-morshead-3.qmd)
- [Letter 2352](../2352-to-mary-yonge-9.qmd)
- [Letter 2358](../2358-to-mary-yonge-10.qmd)
- [Letter 2360](../2360-to-mary-anne-dyson-20.qmd)
- [Letter 2362](../2362-to-mary-yonge-11.qmd)
- [Letter 2372](../2372-to-mary-yonge-36.qmd)
- [Letter 2390](../2390-to-the-reverend-william-john-butler.qmd)
- [Letter 2398](../2398-the-right-reverend-john-coleridge-patteson-to-charlotte-mary-yonge.qmd)
- [Letter 2401](../2401-to-elizabeth-missing-sewell-16.qmd)
- [Letter 2450](../2450-to-the-right-reverend-samuel-wilberforce-2.qmd)
- [Letter 2468](../2468-to-elizabeth-barnett-16.qmd)
- [Letter 2478](../2478-to-gertrude-louisa-legrand-jacob.qmd)
- [Letter 2525](../2525-to-mary-anne-dyson.qmd)
- [Letter 3012](../3012-to-elizabeth-roberts-27.qmd)
- [Letter 19419](../19419-to-florence-wilford.qmd)

