---
title: "The Rt. Rev. John Coleridge Patteson"
person_id: 1155
---

## Biographical Information

(1827-20 Sept 1871)

missionary Bishop of Melanesia

He was killed in the Santa Cruz or Queen Charlotte Islands, the outer part of the New Hebrides, now administratively part of the Solomon Islands  [ILN 9 Dec 1871 559 text 561 picture;  Oxford Hammond Atlas of the World; Sir John Gutch <i>Martyr of the Islands</i> (1971); ODNB]

## Letters Mentioning This Person

- [Letter 1797](../1797-to-sir-john-patteson.qmd)
- [Letter 1836](../1836-to-frances-sophia-coleridge-patteson-4.qmd)
- [Letter 1840](../1840-from-the-reverend-john-coleridge-patteson-to-charlotte-mary-yonge-3.qmd)
- [Letter 1862](../1862-from-the-reverend-john-coleridge-patteson-to-charlotte-mary-yonge.qmd)
- [Letter 1900](../1900-from-the-right-reverend-john-coleridge-patteson-to-charlotte-mary-yonge-4.qmd)
- [Letter 1951](../1951-from-the-right-reverend-john-coleridge-patteson-to-charlotte-mary-yonge-5.qmd)
- [Letter 2059](../2059-from-the-right-reverend-john-coleridge-patteson-to-charlotte-mary-yonge-7.qmd)
- [Letter 2090](../2090-the-reverend-john-keble-to-charlotte-mary-yonge-5.qmd)
- [Letter 2091](../2091-the-reverend-john-keble-to-charlotte-mary-yonge.qmd)
- [Letter 2096](../2096-to-alexander-macmillan-68.qmd)
- [Letter 2120](../2120-from-the-right-reverend-john-coleridge-patteson-to-charlotte-mary-yonge-8.qmd)
- [Letter 2127](../2127-from-the-right-reverend-john-coleridge-patteson-to-charlotte-mary-yonge.qmd)
- [Letter 2138](../2138-the-right-reverend-john-coleridge-patteson-to-charlotte-mary-yonge-3.qmd)
- [Letter 2147](../2147-the-right-reverend-john-coleridge-patteson-to-charlotte-mary-yonge-4.qmd)
- [Letter 2154](../2154-the-right-reverend-john-coleridge-patteson-to-charlotte-mary-yonge-5.qmd)
- [Letter 2164](../2164-to-an-unknown-woman-15.qmd)
- [Letter 2224](../2224-the-right-reverend-john-coleridge-patteson-to-charlotte-mary-yonge-6.qmd)
- [Letter 2230](../2230-the-right-reverend-john-coleridge-patteson-to-charlotte-mary-yonge-7.qmd)
- [Letter 2257](../2257-the-right-reverend-john-coleridge-patteson-to-charlotte-mary-yonge-8.qmd)
- [Letter 2273](../2273-the-right-reverend-john-coleridge-patteson-to-charlotte-mary-yonge-9.qmd)
- [Letter 2293](../2293-to-mary-anne-moberly-5.qmd)
- [Letter 2295](../2295-the-right-reverend-john-coleridge-patteson-to-charlotte-mary-yonge-10.qmd)
- [Letter 2365](../2365-to-the-reverend-fielder.qmd)
- [Letter 2372](../2372-to-mary-yonge-36.qmd)
- [Letter 2424](../2424-to-mary-ann-moberly-6.qmd)
- [Letter 2425](../2425-to-frances-sophia-coleridge-patteson-6.qmd)
- [Letter 2428](../2428-to-mary-ann-moberly-6-2.qmd)
- [Letter 2432](../2432-to-mary-ann-moberly-6-3.qmd)
- [Letter 2433](../2433-to-an-unknown-person-9.qmd)
- [Letter 2434](../2434-to-christabel-rose-coleridge-70.qmd)
- [Letter 2435](../2435-to-sir-william-heathcote-bt-4.qmd)
- [Letter 2439](../2439-to-charlotte-cordelia-yonge.qmd)
- [Letter 2444](../2444-to-sir-william-heathcote-bt-8.qmd)
- [Letter 2445](../2445-to-the-reverend-edward-coleridge.qmd)
- [Letter 2447](../2447-to-elizabeth-wordsworth-5.qmd)
- [Letter 2450](../2450-to-the-right-reverend-samuel-wilberforce-2.qmd)
- [Letter 2463](../2463-to-george-richmond.qmd)
- [Letter 2494](../2494-to-alexander-macmillan-120.qmd)
- [Letter 2529](../2529-to-henry-graves.qmd)
- [Letter 2546](../2546-to-elizabeth-missing-sewell-22.qmd)
- [Letter 2792](../2792-to-mary-anne-moberly-6.qmd)
- [Letter 2952](../2952-to-anne-yonge-19.qmd)
- [Letter 3096](../3096-to-the-reverend-edward-coleridge-2.qmd)
- [Letter 3144](../3144-from-the-reverend-john-coleridge-patteson-to-charlotte-mary-yonge-2.qmd)
- [Letter 3593](../3593-to-florence-gertrude-norsworthy.qmd)
- [Letter 6729](../6729-to-elizabeth-lush.qmd)
- [Letter 7727](../7727-to-sir-john-taylor-coleridge.qmd)
- [Letter 7783](../7783-to-sir-john-taylor-coleridge.qmd)
- [Letter 18775](../18775-to-frances-maria-wilbraham.qmd)

