---
title: "Louisa Alethea (Yonge) Bowles"
person_id: 182
---

## Biographical Information

(1863-28 September 1941)

niece of CMY

Known as Alethea or Alley, she married (7 August 1884) the Rev. Henry Albany Bowles jr. (1859/60-1943).

## Letters Mentioning This Person

- [Letter 2249](../2249-to-edith-sophia-jacob-12.qmd)
- [Letter 2364](../2364-to-mary-yonge-34.qmd)
- [Letter 2420](../2420-to-charlotte-cordelia-yonge-4.qmd)
- [Letter 2552](../2552-to-mary-yonge-42.qmd)
- [Letter 2553](../2553-to-mary-yonge-44.qmd)
- [Letter 2556](../2556-to-mary-yonge-45.qmd)
- [Letter 2788](../2788-to-the-hon-mrs-montgomery-moore-3.qmd)
- [Letter 2831](../2831-to-sophia-jane-harrison-2.qmd)
- [Letter 2881](../2881-to-jean-ingelow.qmd)
- [Letter 2916](../2916-to-mary-yonge-53.qmd)
- [Letter 3177](../3177-to-the-hon-mrs-montgomery-moore-2.qmd)
- [Letter 3200](../3200-to-hannah-carey.qmd)
- [Letter 3342](../3342-to-mary-yonge-18.qmd)
- [Letter 3346](../3346-to-mary-yonge-19.qmd)
- [Letter 3348](../3348-to-mary-yonge-20.qmd)
- [Letter 3354](../3354-to-mary-yonge-23.qmd)
- [Letter 3357](../3357-to-mary-yonge-24.qmd)
- [Letter 3371](../3371-to-beatrice-heathcote.qmd)
- [Letter 3408](../3408-to-mary-yonge-6.qmd)
- [Letter 3411](../3411-to-charlotte-fortescue-yonge-3.qmd)
- [Letter 3421](../3421-to-christabel-rose-coleridge-31.qmd)
- [Letter 3427](../3427-to-christabel-rose-coleridge-35.qmd)
- [Letter 3430](../3430-to-christabel-rose-coleridge-36.qmd)
- [Letter 3435](../3435-to-mary-yonge-27.qmd)
- [Letter 3437](../3437-to-louisa-alethea-bowles.qmd)
- [Letter 3443](../3443-to-christabel-rose-coleridge-38.qmd)
- [Letter 3463](../3463-to-christabel-rose-coleridge-47.qmd)
- [Letter 3481](../3481-to-charlotte-fortescue-yonge.qmd)
- [Letter 3587](../3587-to-charlotte-fortescue-yonge-2.qmd)

