---
title: "Helen Emma Yonge"
person_id: 1613
---

## Biographical Information

(24 October 1860-16 June 1941)

niece of CMY

[Birth register; <i>Morning Post</i> 30 October 1860;


<i>Times</i> 19 June 1941].

## Letters Mentioning This Person

- [Letter 1846](../1846-to-henry-hucks-gibbs.qmd)
- [Letter 2160](../2160-to-emma-frances-yonge-2.qmd)
- [Letter 2249](../2249-to-edith-sophia-jacob-12.qmd)
- [Letter 2275](../2275-to-mary-ann-dyson-7.qmd)
- [Letter 2329](../2329-to-mary-ann-dyson-11.qmd)
- [Letter 2340](../2340-to-charlotte-cordelia-yonge-2.qmd)
- [Letter 2341](../2341-to-mary-yonge-8.qmd)
- [Letter 2344](../2344-to-ellen-julia-johns-10.qmd)
- [Letter 2356](../2356-to-louisa-anne-gibbs.qmd)
- [Letter 2364](../2364-to-mary-yonge-34.qmd)
- [Letter 2377](../2377-to-arthur-john-butler-11.qmd)
- [Letter 2409](../2409-to-laura-valentine-3.qmd)
- [Letter 2420](../2420-to-charlotte-cordelia-yonge-4.qmd)
- [Letter 2525](../2525-to-mary-anne-dyson.qmd)
- [Letter 2710](../2710-to-an-unknown-woman-52.qmd)
- [Letter 2788](../2788-to-the-hon-mrs-montgomery-moore-3.qmd)
- [Letter 2804](../2804-to-the-reverend-william-harris-walter-bigg-wither.qmd)
- [Letter 2881](../2881-to-jean-ingelow.qmd)
- [Letter 3194](../3194-to-helen-emma-yonge-2.qmd)
- [Letter 3204](../3204-to-helen-emma-yonge.qmd)
- [Letter 3279](../3279-to-mary-yonge-14.qmd)
- [Letter 3320](../3320-to-mary-yonge-16.qmd)
- [Letter 3336](../3336-to-edith-emma-knight.qmd)
- [Letter 3354](../3354-to-mary-yonge-23.qmd)
- [Letter 3357](../3357-to-mary-yonge-24.qmd)
- [Letter 3370](../3370-to-helena-heathcote-5.qmd)
- [Letter 3380](../3380-to-marianne-bigg-wither-2.qmd)
- [Letter 3385](../3385-to-mary-yonge-4.qmd)
- [Letter 3411](../3411-to-charlotte-fortescue-yonge-3.qmd)
- [Letter 3416](../3416-to-christabel-rose-coleridge-22.qmd)
- [Letter 3421](../3421-to-christabel-rose-coleridge-31.qmd)
- [Letter 3423](../3423-to-christabel-rose-coleridge-33.qmd)
- [Letter 3425](../3425-to-christabel-rose-coleridge-34.qmd)
- [Letter 3427](../3427-to-christabel-rose-coleridge-35.qmd)
- [Letter 3443](../3443-to-christabel-rose-coleridge-38.qmd)
- [Letter 3448](../3448-to-mary-yonge-28.qmd)
- [Letter 3450](../3450-to-christabel-rose-coleridge-41.qmd)
- [Letter 3451](../3451-to-mary-yonge-30.qmd)
- [Letter 3454](../3454-to-mary-yonge-31.qmd)
- [Letter 3455](../3455-to-mary-yonge-32.qmd)
- [Letter 3456](../3456-to-mary-yonge-33.qmd)
- [Letter 3460](../3460-to-christabel-rose-coleridge-45.qmd)
- [Letter 3469](../3469-to-christabel-rose-coleridge-52.qmd)
- [Letter 3476](../3476-to-george-lillie-craik-16.qmd)
- [Letter 3477](../3477-to-christabel-rose-coleridge-56.qmd)
- [Letter 3480](../3480-to-christabel-rose-coleridge-59.qmd)
- [Letter 3481](../3481-to-charlotte-fortescue-yonge.qmd)
- [Letter 3510](../3510-to-ellen-julia-johns-11.qmd)
- [Letter 3550](../3550-to-hannah-carey.qmd)
- [Letter 3563](../3563-to-emma-frances-yonge-3.qmd)
- [Letter 3572](../3572-to-gertrude-walter.qmd)

