---
title: "Louisa (Walter) Halliday"
person_id: 616
---

## Biographical Information

(Hyderabad 11 Dec 1840-1916)

sister of Gertrude Walter and Frances (Walter) Yonge

Daughter of Lt- Col Edward Walter, she married (1866) Francis Edward Halliday (1834-1911).  She was sister of Gertrude Walter, Frances Yonge and Mary (Walter) Woollcombe.  She had a large family of whom CMY most often mentions her daughter Georgina Frances (Halliday) Mansfield (b.1868/9) who was three in 1871. [India Office, Bombay Baptisms, 1871 census when they were staying at Medstead with cousins]

## Letters Mentioning This Person

- [Letter 2117](../2117-to-anne-yonge-45.qmd)
- [Letter 2249](../2249-to-edith-sophia-jacob-12.qmd)
- [Letter 2352](../2352-to-mary-yonge-9.qmd)
- [Letter 2364](../2364-to-mary-yonge-34.qmd)
- [Letter 2440](../2440-to-mary-yonge-37.qmd)
- [Letter 2881](../2881-to-jean-ingelow.qmd)
- [Letter 2925](../2925-to-mary-yonge.qmd)
- [Letter 3119](../3119-to-anne-yonge-37.qmd)
- [Letter 3430](../3430-to-christabel-rose-coleridge-36.qmd)
- [Letter 3463](../3463-to-christabel-rose-coleridge-47.qmd)
- [Letter 3478](../3478-to-christabel-rose-coleridge-57.qmd)
- [Letter 3539](../3539-to-emily-or-jane-dampier-2.qmd)
- [Letter 3555](../3555-to-isabel-mary-warburton-3.qmd)

