---
title: "Jemima (Wedderburn) Blackburn"
person_id: 159
---

## Biographical Information

(1823-1909)

artist and naturalist

Jemima (Wedderburn) Blackburn (1823-1909), a Scottish naturalist and painter, met CMY through [Frederic Rogers](person_1252.qmd) (1811-1889), later Lord Blachford, a Devon Tractarian who was married to her cousin Georgina Colvile (d.1900). Blackburn’s memories of CMY are printed in Robert Fairley, <i>[Jemima: Paintings and Memoirs of a Victorian Lady](../other_books/otherbook_63.qmd)</i> (Edinburgh : Canongate, 1988), 128:  ‘Charlotte Yonge was a friend of the Rogers and was asked to stay while I was visiting them. It was a very small house and we were lodged in two little garrets next one another, and used to brush out our hair together before going to bed, and so soon became friends. She was very good looking with dark hair and fine eyes, spoke pleasantly and was a little above middle height. We talked of many things. I found her not at all formidable, as one feared she might be, being so well informed; one might almost say learned.  . . . I kept up the friendship as long as she lived, and got a good many letters from her while I was illustrating her books.’   She married Hugh Blackburn, Professor of Mathematics at Edinburgh University. 





Jemima Blackburn discovered the habits of the cuckoo.

## Letters Mentioning This Person

- [Letter 1793](../1793-to-john-william-parker-jr-10.qmd)
- [Letter 1812](../1812-to-jemima-blackburn-11.qmd)
- [Letter 1827](../1827-to-florence-wilford-2.qmd)
- [Letter 1861](../1861-to-jemima-blackburn-10.qmd)
- [Letter 1919](../1919-to-alexander-macmillan-7.qmd)
- [Letter 1930](../1930-to-alexander-macmillan-9.qmd)
- [Letter 1932](../1932-to-alexander-macmillan-10.qmd)
- [Letter 1933](../1933-to-alexander-macmillan-11.qmd)
- [Letter 1938](../1938-to-alexander-macmillan-13.qmd)
- [Letter 1939](../1939-alexander-macmillan-to-charlotte-mary-yonge-8.qmd)
- [Letter 1940](../1940-to-alexander-macmillan-14.qmd)
- [Letter 2798](../2798-to-jemima-blackburn.qmd)
- [Letter 3026](../3026-to-jemima-blackburn-7.qmd)
- [Letter 3041](../3041-to-jemima-blackburn-2.qmd)
- [Letter 3042](../3042-to-jemima-blackburn-3.qmd)
- [Letter 3045](../3045-to-jemima-blackburn-4.qmd)
- [Letter 3052](../3052-to-jemima-blackburn-5.qmd)
- [Letter 3056](../3056-to-jemima-blackburn-6.qmd)
- [Letter 3080](../3080-to-jemima-blackburn-8.qmd)
- [Letter 3093](../3093-to-jemima-blackburn-9.qmd)
- [Letter 3277](../3277-to-jemima-blackburn-12.qmd)
- [Letter 3303](../3303-to-jemima-blackburn-13.qmd)

