---
title: "Elizabeth Wordsworth"
person_id: 1566
---

## Biographical Information

(23 June 1840-30 Nov 1932)

contributor to <i>MP</i> (1871-1893), principal of Lady Margaret Hall

Daughter of the Rt. Rev. Christopher Wordsworth, she was appointed Lady Principal of Lady Margaret Hall in 1878.  She contributed a poem to <i>MP</i> in 1871 under the name 'VERITAS' and probably was the author of another 16 poems which appeared under that pseudonym to February 1883.  





 [Battiscombe, <i>Reluctant Pioneer</i>]

## Letters Mentioning This Person

- [Letter 2408](../2408-to-elizabeth-wordsworth-2.qmd)
- [Letter 2415](../2415-to-elizabeth-wordsworth-4.qmd)
- [Letter 2446](../2446-to-mary-anne-dyson-22.qmd)
- [Letter 2447](../2447-to-elizabeth-wordsworth-5.qmd)
- [Letter 2489](../2489-to-elizabeth-wordsworth-6.qmd)
- [Letter 2515](../2515-to-elizabeth-wordsworth-7.qmd)
- [Letter 2517](../2517-to-elizabeth-wordsworth-8.qmd)
- [Letter 2607](../2607-to-elizabeth-wordsworth-9.qmd)
- [Letter 2608](../2608-to-elizabeth-wordsworth-10.qmd)
- [Letter 2612](../2612-to-elizabeth-wordsworth-11.qmd)
- [Letter 2667](../2667-to-christabel-rose-coleridge-100.qmd)
- [Letter 2734](../2734-to-elizabeth-wordsworth-12.qmd)
- [Letter 2756](../2756-to-elizabeth-wordsworth.qmd)
- [Letter 2788](../2788-to-the-hon-mrs-montgomery-moore-3.qmd)
- [Letter 3339](../3339-to-elizabeth-wordsworth-3.qmd)
- [Letter 3414](../3414-to-elizabeth-harcourt-mitchell.qmd)
- [Letter 19064](../19064-to-margaret-julia-argles.qmd)

