---
title: "Ellen Julia (Field) Johns"
person_id: 772
---

## Biographical Information

(Bath 1821-1895 Winchester)

wife of the Rev. Charles Alexander Johns

She married (Chelsea 1843) the Rev. Charles Alexander Johns, naturalist and schoolmaster.  She seems to have been related to the Keary sisters, possibly  through their mother, daughter of Hall Plumer of Bilston Hall, brother of Sir Thomas Hall Plumer. [1881 census; information from Melissa Hardie;  census]

## Letters Mentioning This Person

- [Letter 1942](../1942-to-ann-catherine-johns.qmd)
- [Letter 1989](../1989-to-ellen-julia-johns-5.qmd)
- [Letter 2005](../2005-to-ellen-julia-johns-3.qmd)
- [Letter 2009](../2009-to-ellen-julia-johns-4.qmd)
- [Letter 2011](../2011-to-ellen-julia-johns-6.qmd)
- [Letter 2057](../2057-to-ellen-julia-johns-7.qmd)
- [Letter 2088](../2088-to-ellen-julia-johns-8.qmd)
- [Letter 2220](../2220-to-ellen-julia-johns-9.qmd)
- [Letter 2279](../2279-to-ellen-julia-johns.qmd)
- [Letter 2344](../2344-to-ellen-julia-johns-10.qmd)
- [Letter 2378](../2378-to-ellen-julia-johns-12.qmd)
- [Letter 2405](../2405-to-ellen-julia-johns-13.qmd)
- [Letter 2422](../2422-to-christabel-rose-coleridge-69.qmd)
- [Letter 2439](../2439-to-charlotte-cordelia-yonge.qmd)
- [Letter 2469](../2469-to-anne-mercier-6.qmd)
- [Letter 2475](../2475-to-christabel-rose-coleridge-79.qmd)
- [Letter 2606](../2606-to-ellen-julia-johns-14.qmd)
- [Letter 2635](../2635-to-ellen-julia-johns-15.qmd)
- [Letter 2688](../2688-to-ellen-julia-johns-16.qmd)
- [Letter 3484](../3484-to-ellen-julia-johns-2.qmd)
- [Letter 3510](../3510-to-ellen-julia-johns-11.qmd)
- [Letter 19875](../19875-to-anna-maria-keary.qmd)

