---
title: "Selina (Shirley), Lady Heathcote"
person_id: 665
---

## Biographical Information

(1814/5-1901)

second wife of Sir William Heathcote

She married Sir William Heathcote 5th Bt. as his second wife (18 May 1841).

## Letters Mentioning This Person

- [Letter 2112](../2112-frances-mary-yonge-to-mary-anne-moberly.qmd)
- [Letter 2732](../2732-to-caroline-elizabeth-cooke-trench.qmd)
- [Letter 2844](../2844-to-isabella-margaretta-elizabeth-heathcote.qmd)
- [Letter 2945](../2945-to-anne-yonge-12.qmd)
- [Letter 3007](../3007-to-mary-anne-dyson-14.qmd)
- [Letter 3029](../3029-to-mary-anne-dyson-17.qmd)
- [Letter 3055](../3055-to-anne-yonge-31.qmd)
- [Letter 3097](../3097-sir-william-heathcote-to-caroline-elizabeth-heathcote.qmd)
- [Letter 3124](../3124-to-caroline-elizabeth-cooke-trench-2.qmd)
- [Letter 3210](../3210-to-sarah-angelina-acland.qmd)
- [Letter 3355](../3355-to-helena-heathcote-4.qmd)
- [Letter 3368](../3368-to-beatrice-heathcote-3.qmd)
- [Letter 3376](../3376-to-frederick-orridge-macmillan-17.qmd)
- [Letter 3377](../3377-to-frederick-orridge-macmillan.qmd)
- [Letter 3379](../3379-to-frederick-orridge-macmillan-19.qmd)

