---
title: "The Rev. Edmund Doidge Anderson Morshead"
person_id: 42
---

## Biographical Information

(1849-1912)

cousin of CMY, schoolmaster

Third son of Rev. John Philip Anderson Morshead and Alethea Yonge, he was a brilliant child and educated at Winchester and New College, Oxford 1867-72.  He got a  double first and returned to serve as assistant master at Winchester College 1872-1904.  He married (1 Aug 1878) Mary, fourth sister of William Andrewes Fearon, headmaster of Winchester College 1884-91.  He died of General Paralysis of the Insane after having spent some months in Holloway Sanatorium [Winchester College Register;  Wainewright, <i>Winchester College</i>; ODNB; LG 1871 Morshead; Hants RO MS 67M922W/82/21]

## Letters Mentioning This Person

- [Letter 1899](../1899-to-anne-yonge-42.qmd)
- [Letter 2275](../2275-to-mary-ann-dyson-7.qmd)
- [Letter 2554](../2554-to-mary-yonge-43.qmd)
- [Letter 2559](../2559-to-mary-yonge-46.qmd)
- [Letter 2979](../2979-to-anne-yonge-25.qmd)
- [Letter 3224](../3224-to-mary-yonge-13.qmd)
- [Letter 3368](../3368-to-beatrice-heathcote-3.qmd)
- [Letter 3369](../3369-to-edmund-doidge-anderson-morshead-2.qmd)
- [Letter 3371](../3371-to-beatrice-heathcote.qmd)
- [Letter 3408](../3408-to-mary-yonge-6.qmd)
- [Letter 3449](../3449-to-mary-yonge-29.qmd)
- [Letter 3567](../3567-to-edmund-doidge-anderson-morshead.qmd)

