---
title: "Anne Sturges Bourne"
person_id: 1379
---

## Biographical Information

(1809-9 Dec 1891)

landowner

Daughter of William Sturges Bourne (1769-1845), she was a rich philanthropic spinster.  A lifelong friend of [Mary Anne Dyson](person_464.qmd), they shared interests in educational and charitable work. Their very copious correspondence, with much detail on Tractarian projects and much gossip, survives in Hampshire Record Office.  Together they encouraged the young CMY’s philanthropic and literary work.  Anne Sturges Bourne appears to have been the author of the review of <i>My Life and What Shall I Do With It</i>? which appeared in 1861.   [Her death aged 92 was reported in the <i>Daily News</i> 15 Dec 1891]

## Letters Mentioning This Person

- [Letter 1791](../1791-to-anne-sturges-bourne-4.qmd)
- [Letter 1792](../1792-to-anne-sturges-bourne-5.qmd)
- [Letter 1815](../1815-from-frances-mary-yonge-to-anne-sturges-bourne.qmd)
- [Letter 1817](../1817-to-anne-sturges-bourne-6.qmd)
- [Letter 1818](../1818-to-anne-sturges-bourne-7.qmd)
- [Letter 1971](../1971-to-alexander-macmillan-17.qmd)
- [Letter 2337](../2337-to-messrs-macmillan-5.qmd)
- [Letter 2399](../2399-to-anne-sturges-bourne-8.qmd)
- [Letter 2410](../2410-to-edith-sophia-jacob-19.qmd)
- [Letter 2561](../2561-to-mary-yonge-48.qmd)
- [Letter 2564](../2564-to-priscilla-johnston.qmd)
- [Letter 2641](../2641-to-elizabeth-barnett-17.qmd)
- [Letter 2867](../2867-to-elizabeth-barnett-20.qmd)
- [Letter 2886](../2886-to-anne-sturges-bourne-9.qmd)
- [Letter 2890](../2890-to-anne-sturges-bourne.qmd)
- [Letter 3087](../3087-to-anne-sturges-bourne-2.qmd)
- [Letter 3091](../3091-to-anna-butler-14.qmd)
- [Letter 3095](../3095-frances-mary-yonge-to-anne-sturges-bourne.qmd)
- [Letter 3125](../3125-to-anne-sturges-bourne-3.qmd)
- [Letter 3181](../3181-to-penelope-packe-3.qmd)
- [Letter 3317](../3317-to-mary-elizabeth-wormeley-latimer.qmd)
- [Letter 3352](../3352-to-helena-heathcote-3.qmd)
- [Letter 3405](../3405-to-penelope-packe-2.qmd)
- [Letter 7883](../7883-to-john-duke-coleridge.qmd)

