---
title: "Arthur John Butler"
person_id: 238
---

## Biographical Information

(21 June 1844-26 Feb 1910)

contributor to <i>MP</i>, Italian scholar, son of the Very Rev. William John Butler

He married (6 April 1875) Mary Caroline Humphry. He was a fellow of Trinity College, Cambridge until 1870, worked in education office until 1887, became a partner in Rivington then Cassell, in 1894 became assistant commissioner on secondary education.  In 1899 joined PRO as editor of foreign state papers.  Translator. In 1898 he also became professor of Italian literature at UCL. [ODNB]

## Letters Mentioning This Person

- [Letter 2320](../2320-to-arthur-john-butler-2.qmd)
- [Letter 2322](../2322-to-arthur-john-butler-3.qmd)
- [Letter 2325](../2325-to-arthur-john-butler-4.qmd)
- [Letter 2326](../2326-to-arthur-john-butler.qmd)
- [Letter 2354](../2354-to-arthur-john-butler-5.qmd)
- [Letter 2357](../2357-to-arthur-john-butler-6.qmd)
- [Letter 2375](../2375-to-arthur-john-butler-10.qmd)
- [Letter 2377](../2377-to-arthur-john-butler-11.qmd)
- [Letter 2402](../2402-to-arthur-john-butler-12.qmd)
- [Letter 2488](../2488-to-arthur-john-butler-13.qmd)
- [Letter 2490](../2490-to-arthur-john-butler-14.qmd)
- [Letter 2847](../2847-to-the-very-reverend-william-john-butler-3.qmd)
- [Letter 3201](../3201-to-arthur-john-butler-7.qmd)
- [Letter 3202](../3202-to-arthur-john-butler-8.qmd)
- [Letter 3266](../3266-to-arthur-john-butler-9.qmd)
- [Letter 3336](../3336-to-edith-emma-knight.qmd)
- [Letter 3403](../3403-to-mary-caroline-butler.qmd)
- [Letter 3480](../3480-to-christabel-rose-coleridge-59.qmd)

