---
title: "The Rev. William Harris Walter Bigg Wither"
person_id: 1544
---

## Biographical Information

(1809-1899)

curate of Otterbourne to 1871 and subsequently Rector of Hardwick, Bucks.

His father Harris Bigg Wither had proposed to Jane Austen. [R. F. Bigg-Wither, <i>Materials for a History of the Wither Family</i> Winchester, Warren 1907]

## Letters Mentioning This Person

- [Letter 1802](../1802-to-ann-maria-carter-smith-37.qmd)
- [Letter 1839](../1839-to-the-reverend-henry-octavius-coxe.qmd)
- [Letter 2111](../2111-to-anne-yonge-44.qmd)
- [Letter 2143](../2143-to-the-reverend-john-frewen-moor-11.qmd)
- [Letter 2161](../2161-to-edith-sophia-jacob-5.qmd)
- [Letter 2173](../2173-to-christabel-rose-coleridge-10.qmd)
- [Letter 2203](../2203-to-margaret-helen-moberly.qmd)
- [Letter 2249](../2249-to-edith-sophia-jacob-12.qmd)
- [Letter 2264](../2264-to-the-reverend-duke-yonge-2.qmd)
- [Letter 2271](../2271-to-mary-ann-dyson-6.qmd)
- [Letter 2275](../2275-to-mary-ann-dyson-7.qmd)
- [Letter 2280](../2280-to-caroline-elizabeth-cooke-trench-4.qmd)
- [Letter 2287](../2287-to-the-reverend-john-frewen-moor-4.qmd)
- [Letter 2333](../2333-to-mary-anne-dyson-10-3.qmd)
- [Letter 2404](../2404-to-mr-west.qmd)
- [Letter 2429](../2429-to-mary-anne-dyson-21.qmd)
- [Letter 2430](../2430-to-janetta-sewell.qmd)
- [Letter 2447](../2447-to-elizabeth-wordsworth-5.qmd)
- [Letter 2471](../2471-to-the-reverend-james-edwards-sewell-2.qmd)
- [Letter 2472](../2472-to-gertrude-louisa-legrand-jacob-3.qmd)
- [Letter 2476](../2476-to-the-reverend-john-frewen-moor.qmd)
- [Letter 2695](../2695-to-mary-yonge-49.qmd)
- [Letter 2730](../2730-to-ann-maria-carter-smith-86.qmd)
- [Letter 2741](../2741-to-annie-louise-cazenove-3.qmd)
- [Letter 2744](../2744-to-the-reverend-william-harris-bigg-wither.qmd)
- [Letter 2804](../2804-to-the-reverend-william-harris-walter-bigg-wither.qmd)
- [Letter 2936](../2936-to-anne-yonge-4.qmd)
- [Letter 2938](../2938-to-anne-yonge-6.qmd)
- [Letter 2939](../2939-to-anne-yonge-7.qmd)
- [Letter 2940](../2940-to-anne-yonge-8.qmd)
- [Letter 2945](../2945-to-anne-yonge-12.qmd)
- [Letter 2946](../2946-to-anne-yonge-13.qmd)
- [Letter 2952](../2952-to-anne-yonge-19.qmd)
- [Letter 2953](../2953-to-anne-yonge-20.qmd)
- [Letter 2956](../2956-to-anne-yonge-23.qmd)
- [Letter 2957](../2957-anne-yonge-to-mary-yonge-2.qmd)
- [Letter 2958](../2958-to-mary-anne-dyson-2.qmd)
- [Letter 2986](../2986-to-elizabeth-roberts-8.qmd)
- [Letter 2987](../2987-to-anne-yonge-26.qmd)
- [Letter 3036](../3036-anne-yonge-to-the-rev-john-yonge.qmd)
- [Letter 3039](../3039-anne-yonge-to-mary-yonge-3.qmd)
- [Letter 3048](../3048-to-mary-anne-dyson-19.qmd)
- [Letter 3055](../3055-to-anne-yonge-31.qmd)
- [Letter 3060](../3060-to-anne-yonge-32.qmd)
- [Letter 3062](../3062-to-anne-yonge-34.qmd)
- [Letter 3063](../3063-to-anne-yonge-35.qmd)
- [Letter 3067](../3067-to-alice-arbuthnot-moberly-6.qmd)
- [Letter 3124](../3124-to-caroline-elizabeth-cooke-trench-2.qmd)
- [Letter 3125](../3125-to-anne-sturges-bourne-3.qmd)
- [Letter 3140](../3140-to-caroline-elizabeth-cooke-trench-3.qmd)
- [Letter 3320](../3320-to-mary-yonge-16.qmd)
- [Letter 3331](../3331-to-the-reverend-william-harris-bigg-wither-2.qmd)
- [Letter 3348](../3348-to-mary-yonge-20.qmd)
- [Letter 3380](../3380-to-marianne-bigg-wither-2.qmd)
- [Letter 3399](../3399-to-marianne-bigg-wither-3.qmd)
- [Letter 3401](../3401-to-the-reverend-john-frewen-moor-7.qmd)
- [Letter 3525](../3525-to-elizabeth-missing-sewell-3.qmd)
- [Letter 3592](../3592-to-charlotte-anne-elizabeth-moberly-2.qmd)
- [Letter 19419](../19419-to-florence-wilford.qmd)

