---
title: "The Very Rev. William John Butler"
person_id: 244
---

## Biographical Information

(10 February 1818-14 January 1894)

Vicar of Wantage and Dean of Lincoln

He was ordained in 1841 and served as curate of Dogmersfield under Mary Anne Dyson’s brother. He served (1846-1880) as Vicar of Wantage, where he embarked on Tractarian improvements on a very large scale, including the establishment of the sisterhood of St. Mary the Virgin.  He married (1843) Emma Barnett, who was his second cousin.  She and her sister Elizabeth Barnett were close friends of CMY. In 1880 he moved to become a canon of Worcester, and in 1885 Dean of Lincoln;  he was made DD in 1886.  [ODNB; <i>Life and Letters of Dean Butler</i>]

## Letters Mentioning This Person

- [Letter 1874](../1874-to-john-william-parker-sr.qmd)
- [Letter 2123](../2123-to-mary-anne-moberly-2.qmd)
- [Letter 2288](../2288-to-the-reverend-william-john-butler-2.qmd)
- [Letter 2317](../2317-to-mary-ann-dyson-9.qmd)
- [Letter 2330](../2330-to-mary-ann-dyson-2.qmd)
- [Letter 2381](../2381-to-an-unknown-woman-or-to-alexander-macmillan.qmd)
- [Letter 2390](../2390-to-the-reverend-william-john-butler.qmd)
- [Letter 2813](../2813-to-the-very-reverend-william-john-butler-2.qmd)
- [Letter 2847](../2847-to-the-very-reverend-william-john-butler-3.qmd)
- [Letter 2911](../2911-to-the-very-reverend-william-john-butler.qmd)
- [Letter 2970](../2970-to-mary-anne-dyson-10.qmd)
- [Letter 3156](../3156-to-arthur-donald-innes-7.qmd)
- [Letter 3244](../3244-to-the-reverend-arthur-roland-maddison.qmd)
- [Letter 3246](../3246-to-the-reverend-john-frederick-watkinson-bullock-9.qmd)

