---
title: "Maurice Edward Yonge"
person_id: 1630
---

## Biographical Information

(1867-6 Apr 1940)

nephew of CMY

He seems to have trained as an engineer.  He married (19 Apr 1899) Maude Woods (d.1938).  He died at St Faiths, Merdon Avenue, Chandlers Ford, Eastleigh, Probate was granted at Bristol 5 June 1940 to George Hubert Woods and Henry Jex Woods  for £221 4s. He went to Stubbington House school, near Fareham, a naval preparatory school. [1881 census; will]

## Letters Mentioning This Person

- [Letter 2249](../2249-to-edith-sophia-jacob-12.qmd)
- [Letter 2358](../2358-to-mary-yonge-10.qmd)
- [Letter 2364](../2364-to-mary-yonge-34.qmd)
- [Letter 2420](../2420-to-charlotte-cordelia-yonge-4.qmd)
- [Letter 2552](../2552-to-mary-yonge-42.qmd)
- [Letter 2553](../2553-to-mary-yonge-44.qmd)
- [Letter 2560](../2560-to-mary-yonge-47.qmd)
- [Letter 2619](../2619-to-christabel-rose-coleridge-92.qmd)
- [Letter 2733](../2733-to-christabel-rose-coleridge-104.qmd)
- [Letter 2805](../2805-to-mary-yonge-51.qmd)
- [Letter 3153](../3153-to-arthur-donald-innes-4.qmd)
- [Letter 3279](../3279-to-mary-yonge-14.qmd)
- [Letter 3393](../3393-to-mary-yonge-3.qmd)
- [Letter 3416](../3416-to-christabel-rose-coleridge-22.qmd)
- [Letter 3446](../3446-to-christabel-rose-coleridge-40.qmd)
- [Letter 3451](../3451-to-mary-yonge-30.qmd)
- [Letter 3455](../3455-to-mary-yonge-32.qmd)

