---
title: "Harriet Lucy Cox"
person_id: 375
---

## Biographical Information

(b.1825/6)

A Miss H. L. Cox was the recipient of payments from CMY from 1857.





Harriet Lucy Cox, who later  married the Rev. Arthur Baker, was presented with a copy of <i>The Daisy Chain</i> by CMY (10 June 1858), inscribed 'H.L. Cox, from her sincere friend C M Yonge'.  Mrs Baker transcribed books into Braille, and it is possible that the payments relate to that, but it seems more likely that she was a contributor. [Information from Ms Delia Twamley, who owns the book.]  





The census returns show a Harriet E. L. Cox (b. Waddesdon Bucks. 1825/6), daughter of the Rev. Frederick Cox, Vicar of Upper Winchendon, who married the Rev. Arthur Baker (1817-1868), and is presumed to be this person.  Since ['Sunlight in the Clouds'](../other_books/otherbook_8.qmd) was signed H.L.C. when it appeared in <i>MP</i> it is possible that she was the author of that work and therefore also of '[An Object in Life'](../other_books/otherbook_5.qmd).

## Letters Mentioning This Person

- [Letter 3102](../3102-to-anna-butler-16.qmd)
- [Letter 3608](../3608-to-agnes-cox.qmd)

