---
title: "John William Parker sr."
person_id: 1144
---

## Biographical Information

(1792-1870)

publisher

He was  printer to Cambridge University Press and the publisher of CMY's early bestsellers of the 1850s.  After the death of his son John William Parker, jr.,  in 1860 he continued in partnership with William Butler Bourn but then sold the firm to Longmans in 1863. The firm should not be confused with that of John Henry Parker of Oxford, who published <i>Kenneth</i>. [DLB 106]

## Letters Mentioning This Person

- [Letter 1806](../1806-to-anna-butler.qmd)
- [Letter 1808](../1808-to-william-butler-bourn.qmd)
- [Letter 1874](../1874-to-john-william-parker-sr.qmd)
- [Letter 1878](../1878-to-ann-maria-carter-smith-55.qmd)
- [Letter 1879](../1879-to-ann-maria-carter-smith-56.qmd)
- [Letter 1881](../1881-to-ann-maria-carter-smith-57.qmd)
- [Letter 1901](../1901-to-frederick-james-furnivall-2.qmd)
- [Letter 1905](../1905-to-alexander-macmillan-2.qmd)
- [Letter 1906](../1906-alexander-macmillan-to-charlotte-mary-yonge-2.qmd)
- [Letter 1907](../1907-to-alexander-macmillan-3.qmd)
- [Letter 1930](../1930-to-alexander-macmillan-9.qmd)
- [Letter 3080](../3080-to-jemima-blackburn-8.qmd)

