---
title: "Walter Smith"
person_id: 1344
---

## Biographical Information

publisher

He ‘took the Mozleys’ business when John Mozley died . . . trained at Macmillans . . . a gentleman and pleasant to deal with in all ways’ (1882). He was associated with CMY 1874-1887.  He moved the office from 6 Paternoster Row to 34 King Street Covent Garden, in 1881.  The note (MS Ewelme Cottage Museum) accompanying payment for Annie Lush's article 'A Trip to Norfolk Island' has the printed address in Paternoster Row crossed out and the new address written in;  it is dated 24 May 1881.

## Letters Mentioning This Person

- [Letter 2762](../2762-to-the-reverend-bartholomew-price.qmd)
- [Letter 2790](../2790-to-constance-frederica-gordon-cumming-3.qmd)
- [Letter 2794](../2794-to-george-lillie-craik-59.qmd)
- [Letter 2795](../2795-to-george-lillie-craik-60.qmd)
- [Letter 2802](../2802-to-the-reverend-richard-st-john-tyrwhitt-3.qmd)
- [Letter 2872](../2872-to-arthur-donald-innes-18.qmd)
- [Letter 2875](../2875-to-walter-smith.qmd)
- [Letter 3168](../3168-to-arthur-donald-innes-10.qmd)
- [Letter 3391](../3391-to-frederick-orridge-macmillan-2.qmd)

