---
title: "The Rt. Rev. John Richardson Selwyn"
person_id: 1296
---

## Biographical Information

(1844-12 Feb 1898)

son of the Rt. Rev. George Augustus Selwyn

He was educated at St John's College Auckland, Eton, Trinity College Cambridge (BA 1866). He was ordained in 1869 and married, first (1872), Clara Innes.  He succeeded Patteson as Bishop of Melanesia (1877).  He married, secondly (1885), Annie Catherine Mort, retired and became Master of Selwyn Coll Cambridge [DNZB, ODNB] His biography makes it clear he was in England June 1889-January 1890, and then returned for good to Europe in September 1891;  this is obscured in ODNB.

## Letters Mentioning This Person

- [Letter 2215](../2215-to-mary-ann-dyson-5.qmd)
- [Letter 2806](../2806-to-frances-sophia-coleridge-patteson-7.qmd)
- [Letter 2811](../2811-to-an-unknown-woman-62.qmd)
- [Letter 3048](../3048-to-mary-anne-dyson-19.qmd)
- [Letter 3096](../3096-to-the-reverend-edward-coleridge-2.qmd)
- [Letter 3226](../3226-to-the-right-reverend-john-richardson-selwyn.qmd)
- [Letter 3236](../3236-to-anne-elizabeth-mary-anderson-morshead-4.qmd)
- [Letter 3381](../3381-to-the-countess-of-glasgow.qmd)
- [Letter 3588](../3588-to-frances-sophia-coleridge-patteson-2.qmd)
- [Letter 3589](../3589-to-lucy-yonge.qmd)
- [Letter 9097](../9097-to-sarah-harriet-selwyn.qmd)

