---
title: "Emily Caroline (Garnier) Papillon"
person_id: 1136
---

## Biographical Information

(1839-1917)

Granddaughter of the Rev. Thomas Garnier (1776-1873), the aged dean of Winchester

 she married (1862) Philip Oxenden Papillon (1826-1899) and had Pelham Rawstorn Papillon (1864-1940), Godfrey Keppel Papillon and Harold Garnier Papillon, (twins born 26 Sept 1867), Beatrice Emily Papillon, (1863/4-1870),  Muriel Caroline Papillon (b.1866), goddaughter of CMY (who married in 1897 the Rev. H. C. Lenox Tindall), Cicely Gertrude Papillon (alive 1952) and Bertha Sybil Papillon (alive 1952), who married Reginald Eves A.R.A.  Emily Caroline Papillon is presumably the E. C. Papillon who was a contributor to <i>MP</i> (1894).  Mrs Philip Papillon was on the Central Council of the GFS in 1878. [<i>The Times</i>, 13 January 1917; LG 1871, 1906, 1952, Papillon and Garnier ]

## Letters Mentioning This Person

- [Letter 2367](../2367-to-mary-yonge-35.qmd)
- [Letter 2426](../2426-to-edward-augustus-freeman-3.qmd)
- [Letter 3513](../3513-to-emily-caroline-papillon.qmd)

