---
title: "The Rt. Rev. Henry Lascelles Jenner"
person_id: 758
---

## Biographical Information

(1820-1898)

Bishop of Dunedin, Vicar of Preston

His appointment to the bishopric of Dunedin, New Zealand, was abortive, but he was active there 1866-71.  Later he was Bishop of the Eglise Catholique Gallicane 1882-93.  His address was Preston Vicarage, Dover.  He married Mary Isabel, eldest daughter of Capt Finlaison RN, sister of Marion Finlaison, sub-editor of <i>MP</i>. He was a contributor to <i>MP</i> (1884), and perhaps also the Bishop contributing to <i>MP</i>  in 1878 as 'H. L. J.'  He was son of Sir Herbert Jenner-Fust, the judge in  the Gorham case.  It seems probable that he was ‘Vertumnus I’, whose address was Preston Vicarage, Sandwich, who conducted the ‘Monthly Packet Botanical Society’ between June 1879 and November 1882, and who subsequently took part in the Spider competitions as ‘Vertumnus I’. [WWW]

## Letters Mentioning This Person

- [Letter 2700](../2700-to-a-member-of-the-neale-family.qmd)
- [Letter 2813](../2813-to-the-very-reverend-william-john-butler-2.qmd)
- [Letter 2884](../2884-to-arthur-donald-innes-21.qmd)
- [Letter 3267](../3267-to-the-reverend-john-frederick-watkinson-bullock-24.qmd)

