---
title: "The Rt. Rev. George Augustus Selwyn"
person_id: 1295
---

## Biographical Information

(1809-11 Apr 1878)

Bishop of New Zealand and subsequently of Lichfield

He married (1839) Sarah Harriet Richardson (d. 25 Mar 1907).  He was educated at Eton and St John’s College, Cambridge (BA 1831);  he became Bishop of New Zealand in  1841 and Bishop of Lichfield in 1868.

## Letters Mentioning This Person

- [Letter 1797](../1797-to-sir-john-patteson.qmd)
- [Letter 1876](../1876-from-the-right-reverend-john-coleridge-patteson-to-charlotte-mary-yonge-2.qmd)
- [Letter 1951](../1951-from-the-right-reverend-john-coleridge-patteson-to-charlotte-mary-yonge-5.qmd)
- [Letter 1954](../1954-from-the-right-reverend-john-coleridge-patteson-to-charlotte-mary-yonge-6.qmd)
- [Letter 2059](../2059-from-the-right-reverend-john-coleridge-patteson-to-charlotte-mary-yonge-7.qmd)
- [Letter 2215](../2215-to-mary-ann-dyson-5.qmd)
- [Letter 2273](../2273-the-right-reverend-john-coleridge-patteson-to-charlotte-mary-yonge-9.qmd)
- [Letter 2295](../2295-the-right-reverend-john-coleridge-patteson-to-charlotte-mary-yonge-10.qmd)
- [Letter 2428](../2428-to-mary-ann-moberly-6-2.qmd)
- [Letter 2429](../2429-to-mary-anne-dyson-21.qmd)
- [Letter 2432](../2432-to-mary-ann-moberly-6-3.qmd)
- [Letter 2433](../2433-to-an-unknown-person-9.qmd)
- [Letter 2435](../2435-to-sir-william-heathcote-bt-4.qmd)
- [Letter 2439](../2439-to-charlotte-cordelia-yonge.qmd)
- [Letter 2445](../2445-to-the-reverend-edward-coleridge.qmd)
- [Letter 2450](../2450-to-the-right-reverend-samuel-wilberforce-2.qmd)
- [Letter 2494](../2494-to-alexander-macmillan-120.qmd)
- [Letter 3018](../3018-to-elizabeth-roberts-29.qmd)
- [Letter 3044](../3044-frances-mary-yonge-to-alice-arbuthnot-moberly-2.qmd)
- [Letter 3046](../3046-to-elizabeth-roberts-34.qmd)
- [Letter 3048](../3048-to-mary-anne-dyson-19.qmd)
- [Letter 3054](../3054-to-elizabeth-roberts-35.qmd)
- [Letter 3061](../3061-to-anne-yonge-33.qmd)
- [Letter 3062](../3062-to-anne-yonge-34.qmd)
- [Letter 3064](../3064-to-anne-yonge-36.qmd)
- [Letter 3226](../3226-to-the-right-reverend-john-richardson-selwyn.qmd)
- [Letter 7783](../7783-to-sir-john-taylor-coleridge.qmd)
- [Letter 7798](../7798-to-sir-john-taylor-coleridge.qmd)

