---
title: "Julian Bargus Yonge"
person_id: 1624
---

## Biographical Information

(31 Jan 1830-17 October 1891)

brother of CMY

He was educated at Eton and Balliol College Oxford (BA 1853).  He joined the Rifle Brigade 1851, entered the Middle Temple 1855.  He married (9 Sept 1858) Emma Frances Walter (1839-1913).  He was a J.P. for Hampshire;  sold Otterbourne House to Major Robert Scarlett in 1891 and died ‘a few days later’ (<i>John Keble’s Parishes</i>, 149), at 70 Kensington Gardens Square in the presence of his son Maurice [death certificate] but according to the probate of his will at 2 Radnor Place Hyde Park.

## Letters Mentioning This Person

- [Letter 1802](../1802-to-ann-maria-carter-smith-37.qmd)
- [Letter 1812](../1812-to-jemima-blackburn-11.qmd)
- [Letter 1815](../1815-from-frances-mary-yonge-to-anne-sturges-bourne.qmd)
- [Letter 1817](../1817-to-anne-sturges-bourne-6.qmd)
- [Letter 1887](../1887-to-ann-maria-carter-smith-60.qmd)
- [Letter 1888](../1888-to-frances-mary-peard-5.qmd)
- [Letter 1917](../1917-to-alexander-macmillan-6.qmd)
- [Letter 1918](../1918-alexander-macmillan-to-charlotte-mary-yonge-5.qmd)
- [Letter 1919](../1919-to-alexander-macmillan-7.qmd)
- [Letter 1920](../1920-to-the-reverend-algernon-wodehouse.qmd)
- [Letter 1926](../1926-to-alexander-macmillan-8.qmd)
- [Letter 1942](../1942-to-ann-catherine-johns.qmd)
- [Letter 1967](../1967-alexander-macmillan-to-julian-bargus-yonge.qmd)
- [Letter 1973](../1973-to-alexander-macmillan-18.qmd)
- [Letter 2014](../2014-to-alexander-macmillan-37.qmd)
- [Letter 2054](../2054-to-alexander-macmillan-52.qmd)
- [Letter 2055](../2055-to-alexander-macmillan-53.qmd)
- [Letter 2079](../2079-to-alexander-macmillan-60.qmd)
- [Letter 2084](../2084-to-alexander-macmillanm066-1865-12-08.qmd)
- [Letter 2089](../2089-to-alexander-macmillan-66.qmd)
- [Letter 2271](../2271-to-mary-ann-dyson-6.qmd)
- [Letter 2275](../2275-to-mary-ann-dyson-7.qmd)
- [Letter 2278](../2278-to-alexander-macmillan-101.qmd)
- [Letter 2281](../2281-to-ann-maria-carter-smith-79.qmd)
- [Letter 2304](../2304-to-sir-william-heathcote-bt-2.qmd)
- [Letter 2328](../2328-to-mary-ann-dyson-10.qmd)
- [Letter 2329](../2329-to-mary-ann-dyson-11.qmd)
- [Letter 2330](../2330-to-mary-ann-dyson-2.qmd)
- [Letter 2331](../2331-to-mary-ann-dyson-12.qmd)
- [Letter 2333](../2333-to-mary-anne-dyson-10-3.qmd)
- [Letter 2335](../2335-to-mary-ann-dyson-12.qmd)
- [Letter 2361](../2361-to-alexander-macmillan-112.qmd)
- [Letter 2363](../2363-to-alexander-macmillan-113.qmd)
- [Letter 2367](../2367-to-mary-yonge-35.qmd)
- [Letter 2394](../2394-to-francois-pierre-guillaume-guizot-3.qmd)
- [Letter 2427](../2427-to-miss-cassell.qmd)
- [Letter 2440](../2440-to-mary-yonge-37.qmd)
- [Letter 2542](../2542-to-george-lillie-craik-21.qmd)
- [Letter 2544](../2544-to-mary-yonge-39.qmd)
- [Letter 2547](../2547-to-mary-yonge-40.qmd)
- [Letter 2550](../2550-to-mary-yonge-41.qmd)
- [Letter 2552](../2552-to-mary-yonge-42.qmd)
- [Letter 2553](../2553-to-mary-yonge-44.qmd)
- [Letter 2554](../2554-to-mary-yonge-43.qmd)
- [Letter 2556](../2556-to-mary-yonge-45.qmd)
- [Letter 2559](../2559-to-mary-yonge-46.qmd)
- [Letter 2574](../2574-to-hezekiah-butterworth.qmd)
- [Letter 2580](../2580-to-the-reverend-edward-atkinson.qmd)
- [Letter 2582](../2582-to-the-reverend-bartholomew-price-2.qmd)
- [Letter 2587](../2587-to-christabel-rose-coleridge-88.qmd)
- [Letter 2762](../2762-to-the-reverend-bartholomew-price.qmd)
- [Letter 2766](../2766-to-john-duke-pode.qmd)
- [Letter 2815](../2815-to-mary-yonge-52.qmd)
- [Letter 2831](../2831-to-sophia-jane-harrison-2.qmd)
- [Letter 2881](../2881-to-jean-ingelow.qmd)
- [Letter 2929](../2929-to-mary-isabel-yonge.qmd)
- [Letter 2936](../2936-to-anne-yonge-4.qmd)
- [Letter 2938](../2938-to-anne-yonge-6.qmd)
- [Letter 2939](../2939-to-anne-yonge-7.qmd)
- [Letter 2940](../2940-to-anne-yonge-8.qmd)
- [Letter 2950](../2950-to-anne-yonge-17.qmd)
- [Letter 2952](../2952-to-anne-yonge-19.qmd)
- [Letter 2953](../2953-to-anne-yonge-20.qmd)
- [Letter 2956](../2956-to-anne-yonge-23.qmd)
- [Letter 2957](../2957-anne-yonge-to-mary-yonge-2.qmd)
- [Letter 2977](../2977-to-anne-yonge-24.qmd)
- [Letter 2979](../2979-to-anne-yonge-25.qmd)
- [Letter 2987](../2987-to-anne-yonge-26.qmd)
- [Letter 3007](../3007-to-mary-anne-dyson-14.qmd)
- [Letter 3017](../3017-to-anne-yonge-29.qmd)
- [Letter 3025](../3025-to-elizabeth-roberts-32.qmd)
- [Letter 3027](../3027-to-anne-yonge-30.qmd)
- [Letter 3028](../3028-to-mary-anne-dyson-16.qmd)
- [Letter 3031](../3031-to-elizabeth-barnett-5.qmd)
- [Letter 3032](../3032-frances-mary-yonge-to-the-reverend-john-yonge-2.qmd)
- [Letter 3033](../3033-frances-mary-yonge-to-the-reverend-john-yonge.qmd)
- [Letter 3034](../3034-frances-mary-yonge-to-mary-yonge.qmd)
- [Letter 3035](../3035-to-elizabeth-roberts-33.qmd)
- [Letter 3036](../3036-anne-yonge-to-the-rev-john-yonge.qmd)
- [Letter 3041](../3041-to-jemima-blackburn-2.qmd)
- [Letter 3048](../3048-to-mary-anne-dyson-19.qmd)
- [Letter 3052](../3052-to-jemima-blackburn-5.qmd)
- [Letter 3054](../3054-to-elizabeth-roberts-35.qmd)
- [Letter 3055](../3055-to-anne-yonge-31.qmd)
- [Letter 3057](../3057-to-elizabeth-roberts-36.qmd)
- [Letter 3058](../3058-to-mrs-harris.qmd)
- [Letter 3060](../3060-to-anne-yonge-32.qmd)
- [Letter 3061](../3061-to-anne-yonge-33.qmd)
- [Letter 3062](../3062-to-anne-yonge-34.qmd)
- [Letter 3063](../3063-to-anne-yonge-35.qmd)
- [Letter 3064](../3064-to-anne-yonge-36.qmd)
- [Letter 3093](../3093-to-jemima-blackburn-9.qmd)
- [Letter 3095](../3095-frances-mary-yonge-to-anne-sturges-bourne.qmd)
- [Letter 3099](../3099-to-ann-maria-carter-smith-10.qmd)
- [Letter 3103](../3103-to-mr-owen.qmd)
- [Letter 3109](../3109-to-frances-mary-yonge-2.qmd)
- [Letter 3110](../3110-anne-yonge-to-mary-yonge.qmd)
- [Letter 3111](../3111-to-frances-mary-yonge.qmd)
- [Letter 3115](../3115-to-anna-butler-17.qmd)
- [Letter 3119](../3119-to-anne-yonge-37.qmd)
- [Letter 3122](../3122-to-the-reverend-edward-coleridge-3.qmd)
- [Letter 3140](../3140-to-caroline-elizabeth-cooke-trench-3.qmd)
- [Letter 3177](../3177-to-the-hon-mrs-montgomery-moore-2.qmd)
- [Letter 3204](../3204-to-helen-emma-yonge.qmd)
- [Letter 3307](../3307-to-charles-wooldridge-5.qmd)
- [Letter 3309](../3309-to-charles-wooldridge-6.qmd)
- [Letter 3370](../3370-to-helena-heathcote-5.qmd)
- [Letter 3514](../3514-to-an-unknown-person-4.qmd)
- [Letter 3548](../3548-to-frances-sophia-coleridge-patteson.qmd)
- [Letter 3555](../3555-to-isabel-mary-warburton-3.qmd)
- [Letter 3587](../3587-to-charlotte-fortescue-yonge-2.qmd)
- [Letter 3590](../3590-to-julian-bargus-yonge.qmd)
- [Letter 7759](../7759-to-sir-william-heathcote-bt.qmd)

