---
title: "The Rev. Robert Francis Wilson"
person_id: 1541
---

## Biographical Information

(1808/9-8 Oct 1888)

Vicar of Rownhams

He married (6 May 1847) Maria Trench (1820/1-7 Dec 1908).  He was educated at Oriel College, Oxford, and served as curate of Hursley, then curate of Ampfield from April 1841;  he resigned Ampfield in October 1853;  he was perpetual curate of Baldersby Yorks 1858-63, and vicar of Rownhams 1863; he left issue [PB 1914 Ashtown; <i>Clergy List</i>]

## Letters Mentioning This Person

- [Letter 1838](../1838-to-margaret-gatty-2.qmd)
- [Letter 1846](../1846-to-henry-hucks-gibbs.qmd)
- [Letter 1868](../1868-to-frances-mary-peard-12.qmd)
- [Letter 2215](../2215-to-mary-ann-dyson-5.qmd)
- [Letter 2275](../2275-to-mary-ann-dyson-7.qmd)
- [Letter 2280](../2280-to-caroline-elizabeth-cooke-trench-4.qmd)
- [Letter 2288](../2288-to-the-reverend-william-john-butler-2.qmd)
- [Letter 2297](../2297-to-an-unknown-woman-32.qmd)
- [Letter 2329](../2329-to-mary-ann-dyson-11.qmd)
- [Letter 2429](../2429-to-mary-anne-dyson-21.qmd)
- [Letter 2495](../2495-to-misey-2.qmd)
- [Letter 2616](../2616-to-christabel-rose-coleridge-90.qmd)
- [Letter 2618](../2618-to-christabel-rose-coleridge-91.qmd)
- [Letter 2619](../2619-to-christabel-rose-coleridge-92.qmd)
- [Letter 2663](../2663-to-christabel-rose-coleridge-99.qmd)
- [Letter 2894](../2894-to-charlotte-anne-elizabeth-moberly-3.qmd)
- [Letter 2956](../2956-to-anne-yonge-23.qmd)
- [Letter 3336](../3336-to-edith-emma-knight.qmd)

