---
title: "Arthur Donald Innes"
person_id: 744
---

## Biographical Information

(Simla 1863/4-1938)

editor and publisher

He graduated from Oriel College Oxford in 1887, was publisher of <i>MP</i> and of some of CMY’s books, contributor (1892-8), took over from CMY as coeditor of <i>MP</i> in 1894. After the collapse of his publishing business, he seems to have worked for Cassell’s and later lectured in Indian history at SOAS.  He came from a family of Indian administrators and civil servants.  [WWW]

## Letters Mentioning This Person

- [Letter 2872](../2872-to-arthur-donald-innes-18.qmd)
- [Letter 2873](../2873-to-arthur-donald-innes-19.qmd)
- [Letter 2883](../2883-to-arthur-donald-innes-20.qmd)
- [Letter 2884](../2884-to-arthur-donald-innes-21.qmd)
- [Letter 2887](../2887-to-arthur-donald-innes-22.qmd)
- [Letter 2888](../2888-to-arthur-donald-innes-23.qmd)
- [Letter 2892](../2892-to-an-unknown-woman-65.qmd)
- [Letter 2895](../2895-to-arthur-donald-innes-24.qmd)
- [Letter 2896](../2896-to-arthur-donald-innes-25.qmd)
- [Letter 2912](../2912-to-arthur-donald-innes-26.qmd)
- [Letter 2913](../2913-to-arthur-donald-innes-27.qmd)
- [Letter 2914](../2914-to-arthur-donald-innes-28.qmd)
- [Letter 2921](../2921-to-frances-mary-peard-10.qmd)
- [Letter 2922](../2922-to-arthur-donald-innes-29.qmd)
- [Letter 3151](../3151-to-arthur-donald-innes-3.qmd)
- [Letter 3153](../3153-to-arthur-donald-innes-4.qmd)
- [Letter 3154](../3154-to-arthur-donald-innes-5.qmd)
- [Letter 3155](../3155-to-arthur-donald-innes-6.qmd)
- [Letter 3156](../3156-to-arthur-donald-innes-7.qmd)
- [Letter 3157](../3157-to-arthur-donald-innes-8.qmd)
- [Letter 3158](../3158-to-arthur-donald-innes-2.qmd)
- [Letter 3166](../3166-to-arthur-donald-innes-9.qmd)
- [Letter 3168](../3168-to-arthur-donald-innes-10.qmd)
- [Letter 3174](../3174-to-arthur-donald-innes-11.qmd)
- [Letter 3175](../3175-to-arthur-donald-innes-12.qmd)
- [Letter 3176](../3176-to-arthur-donald-innes-13.qmd)
- [Letter 3178](../3178-to-arthur-donald-innes-14.qmd)
- [Letter 3185](../3185-to-arthur-donald-innes-15.qmd)
- [Letter 3189](../3189-to-arthur-donald-innes-16.qmd)
- [Letter 3190](../3190-to-christabel-rose-coleridge-29.qmd)
- [Letter 3206](../3206-to-arthur-donald-innes.qmd)
- [Letter 3208](../3208-to-oscar-fay-adams.qmd)
- [Letter 3209](../3209-to-arthur-donald-innes-17.qmd)
- [Letter 3210](../3210-to-sarah-angelina-acland.qmd)
- [Letter 3216](../3216-to-lady-frederick-bruce-3.qmd)
- [Letter 3218](../3218-to-john-athelstan-laurie-riley-2.qmd)
- [Letter 3236](../3236-to-anne-elizabeth-mary-anderson-morshead-4.qmd)
- [Letter 3301](../3301-to-frederick-orridge-macmillan-or-alexander-macmillan.qmd)
- [Letter 3344](../3344-to-mrs-walker.qmd)
- [Letter 3391](../3391-to-frederick-orridge-macmillan-2.qmd)
- [Letter 3409](../3409-to-mary-yonge-12.qmd)
- [Letter 3411](../3411-to-charlotte-fortescue-yonge-3.qmd)
- [Letter 3412](../3412-to-christabel-rose-coleridge-28.qmd)
- [Letter 3416](../3416-to-christabel-rose-coleridge-22.qmd)
- [Letter 3420](../3420-to-christabel-rose-coleridge-26.qmd)
- [Letter 3421](../3421-to-christabel-rose-coleridge-31.qmd)
- [Letter 3423](../3423-to-christabel-rose-coleridge-33.qmd)
- [Letter 3425](../3425-to-christabel-rose-coleridge-34.qmd)
- [Letter 3427](../3427-to-christabel-rose-coleridge-35.qmd)
- [Letter 3468](../3468-to-christabel-rose-coleridge-51.qmd)
- [Letter 3470](../3470-to-christabel-rose-coleridge-53.qmd)
- [Letter 3472](../3472-to-george-lillie-craik-17.qmd)
- [Letter 3480](../3480-to-christabel-rose-coleridge-59.qmd)
- [Letter 3600](../3600-to-miss-higginbotham.qmd)
- [Letter 3611](../3611-to-an-unknown-woman-5.qmd)
- [Letter 19450](../19450-to-arthur-donald-innes.qmd)

