---
title: "Sir John Patteson"
person_id: 1156
---

## Biographical Information

(1790-1861)

judge, brother-in-law of Sir John Taylor Coleridge

He married first (1818) his cousin Elizabeth Lee (d. 1820) and, secondly (1824), Frances Duke Coleridge (d.1842).  He was father of the Rt. Rev. John Coleridge Patteson, Frances Patteson and (by his first marriage) of Joanna Patteson.

## Letters Mentioning This Person

- [Letter 1797](../1797-to-sir-john-patteson.qmd)
- [Letter 1836](../1836-to-frances-sophia-coleridge-patteson-4.qmd)
- [Letter 1840](../1840-from-the-reverend-john-coleridge-patteson-to-charlotte-mary-yonge-3.qmd)
- [Letter 2120](../2120-from-the-right-reverend-john-coleridge-patteson-to-charlotte-mary-yonge-8.qmd)
- [Letter 2154](../2154-the-right-reverend-john-coleridge-patteson-to-charlotte-mary-yonge-5.qmd)
- [Letter 2444](../2444-to-sir-william-heathcote-bt-8.qmd)
- [Letter 2955](../2955-to-anne-yonge-22.qmd)
- [Letter 2961](../2961-william-crawley-yonge-to-the-reverend-john-yonge.qmd)
- [Letter 3144](../3144-from-the-reverend-john-coleridge-patteson-to-charlotte-mary-yonge-2.qmd)
- [Letter 3593](../3593-to-florence-gertrude-norsworthy.qmd)
- [Letter 7798](../7798-to-sir-john-taylor-coleridge.qmd)

