---
title: "Marion Finlaison"
person_id: 512
---

## Biographical Information

(b. London 1834/5-1914)

schoolmistress, subeditor of <i>MP</i>

CMY's neighbour Marion Finlaison (1834/5-1914) is described in Coleridge, <i>[Life](../other_books/otherbook_40.qmd)</i>, 272, 280. She ran a small boarding-school in Otterbourne and acted as sub-editor of <i>MP</i>. Although Marion is what she wrote on the census forms, it appears she was actually baptised Catherine Jane.  She was the daughter of William Finlaison (1789-1852), Captain RN (he was brother of the actuary and was on the <i>Beagle</i>, briefly also governor of Ascension I) and Mary Anne Ovenden.  In 1861, calling herself Marion C. C [or J?]. Finlaison,  she was living with her mother in the household of her sister Mary Isobell (1819-1900)  and brother-in-law, the Rev. [Henry Jenner](person_758.qmd) (1820-1898), Rector of Preston, Kent.  Jenner  was later made Bishop of Dunedin New Zealand (though rejected as too High) and Bishop of the Eglise Catholique Gallicane. Marion Finlaison acted as subeditor of the <i>MP</i> and  ran a small boarding school in Otterbourne from late 1870s, probably successor of the school run by Mary Adams.  She was evidently known by her family as Kate.  She lived at Wingham between Preston and Otterbourne.  [Not in PO Directory 1875, listed in White's Directory 1878; Finlaison letters; geocities.]

## Letters Mentioning This Person

- [Letter 2488](../2488-to-arthur-john-butler-13.qmd)
- [Letter 2501](../2501-to-florence-freeman.qmd)
- [Letter 2538](../2538-to-augusta-boevey-pode-3.qmd)
- [Letter 2572](../2572-to-christabel-rose-coleridge-86.qmd)
- [Letter 2643](../2643-to-christabel-rose-coleridge-96.qmd)
- [Letter 2672](../2672-to-mary-eliza-bramston-2.qmd)
- [Letter 2717](../2717-to-christabel-rose-coleridge-101.qmd)
- [Letter 2741](../2741-to-annie-louise-cazenove-3.qmd)
- [Letter 2846](../2846-to-anna-meredith-barrett-lennard-3.qmd)
- [Letter 2872](../2872-to-arthur-donald-innes-18.qmd)
- [Letter 3166](../3166-to-arthur-donald-innes-9.qmd)
- [Letter 3168](../3168-to-arthur-donald-innes-10.qmd)
- [Letter 3176](../3176-to-arthur-donald-innes-13.qmd)
- [Letter 3194](../3194-to-helen-emma-yonge-2.qmd)
- [Letter 3219](../3219-to-mr-moore.qmd)
- [Letter 3342](../3342-to-mary-yonge-18.qmd)
- [Letter 3367](../3367-to-anna-meredith-barrett-lennard.qmd)
- [Letter 3385](../3385-to-mary-yonge-4.qmd)
- [Letter 3386](../3386-to-christabel-rose-coleridge-25.qmd)
- [Letter 3404](../3404-to-mary-yonge-5.qmd)
- [Letter 3411](../3411-to-charlotte-fortescue-yonge-3.qmd)
- [Letter 3427](../3427-to-christabel-rose-coleridge-35.qmd)
- [Letter 3443](../3443-to-christabel-rose-coleridge-38.qmd)
- [Letter 3448](../3448-to-mary-yonge-28.qmd)
- [Letter 3463](../3463-to-christabel-rose-coleridge-47.qmd)
- [Letter 3464](../3464-to-christabel-rose-coleridge-48.qmd)
- [Letter 3465](../3465-to-christabel-rose-coleridge-49.qmd)
- [Letter 3467](../3467-to-mrs-c-e-barrett-lennard.qmd)
- [Letter 3468](../3468-to-christabel-rose-coleridge-51.qmd)
- [Letter 3469](../3469-to-christabel-rose-coleridge-52.qmd)
- [Letter 3479](../3479-to-christabel-rose-coleridge-58.qmd)
- [Letter 3480](../3480-to-christabel-rose-coleridge-59.qmd)

