---
title: "Harriet Poole"
person_id: 1187
---

## Biographical Information

(b. Mansfield, Nottingham 1843/4)

governess

She was governess at the time of the 1871 census to the children of the Rev. Robert Hughes at Wyelands House, Matherne, Wales;  by 1881 she was living in London with her sister [Alice](person_1188.qmd), both governesses.  In the 1901 census she is a Sister of Charity at the sisterhood of St. Thomas, Oxford. CMY implies that Mary Anne Dyson knew her, which increases the probability that she was the Elgies’ governess, who had previously worked in Miss Dyson’s school, and read German with Gertrude. Probably the Miss Poole who offered 'Rosa's Dream' in 1867.

## Letters Mentioning This Person

- [Letter 2187](../2187-to-harriet-poole.qmd)
- [Letter 2439](../2439-to-charlotte-cordelia-yonge.qmd)
- [Letter 2446](../2446-to-mary-anne-dyson-22.qmd)
- [Letter 2461](../2461-to-christabel-rose-coleridge-76.qmd)
- [Letter 2480](../2480-to-harriet-poole-2.qmd)
- [Letter 2499](../2499-to-mary-anne-dyson-23.qmd)

