---
title: "Alice Mary Coleridge"
person_id: 327
---

## Biographical Information

(1846-1907)

member of the Gosling Society, cousin of CMY

Much the youngest daughter of Francis Coleridge (1794-1854); her mother sank into depression after her birth and she was brought up by her elder sister Harriet Duke (Coleridge) Lowe (b.1829/30), wife of the Rev. Edward Clarke Lowe (1823-1912) one of the moving spirits in the Woodard Schools movement for the education of the middle classes.  She lived with them at The College, Hurstpierpoint, and was a Gosling as ‘Gurgoyle’ 1863-after 1869.  She became Lady Warden of St. Anne's Abbot's Bromley, a Woodard girls' school, <i>c</i>. 1874 and spent the rest of her life there.  Her brother Arthur Duke Coleridge was father of Mary E. Coleridge, the poet.  She was CMY's goddaughter.  It looks from the <i>Barnacle</i> as if she spent some time living with Mildred and/or Mary Coleridge.  [ODNB; Rice, <i>Story of St. Mary's Abbot's Bromley</i>; Coleridge, <i>Story of a Devonshire House</i>]

## Letters Mentioning This Person

- [Letter 1857](../1857-to-charlotte-sophia-fursdon.qmd)
- [Letter 1995](../1995-to-alexander-macmillan-29.qmd)
- [Letter 2057](../2057-to-ellen-julia-johns-7.qmd)
- [Letter 2078](../2078-to-christabel-rose-coleridge-7.qmd)
- [Letter 2093](../2093-to-frances-mary-peard-9.qmd)
- [Letter 2132](../2132-to-edith-sophia-jacob-2.qmd)
- [Letter 2173](../2173-to-christabel-rose-coleridge-10.qmd)
- [Letter 2185](../2185-to-christabel-rose-coleridge-11.qmd)
- [Letter 2201](../2201-to-christabel-rose-coleridge-12.qmd)
- [Letter 2369](../2369-to-christabel-rose-coleridge-61.qmd)
- [Letter 3588](../3588-to-frances-sophia-coleridge-patteson-2.qmd)

