---
title: "Francis Arthur Yonge"
person_id: 1607
---

## Biographical Information

(1861- 3 Jan 1918)

nephew of CMY

He emigrated to the U.S.A. and married (1892) Edith Louise Isabel Shortride; they adopted a daughter Gwendolene Violet Yonge, who married – Jones. (two says Ian Yonge)

## Letters Mentioning This Person

- [Letter 1846](../1846-to-henry-hucks-gibbs.qmd)
- [Letter 2218](../2218-to-laura-valentine-2.qmd)
- [Letter 2249](../2249-to-edith-sophia-jacob-12.qmd)
- [Letter 2292](../2292-to-alexander-macmillan-105.qmd)
- [Letter 2356](../2356-to-louisa-anne-gibbs.qmd)
- [Letter 2364](../2364-to-mary-yonge-34.qmd)
- [Letter 2420](../2420-to-charlotte-cordelia-yonge-4.qmd)
- [Letter 2440](../2440-to-mary-yonge-37.qmd)
- [Letter 2559](../2559-to-mary-yonge-46.qmd)
- [Letter 2595](../2595-to-augusta-boevey-pode.qmd)
- [Letter 2881](../2881-to-jean-ingelow.qmd)
- [Letter 2906](../2906-to-an-unknown-man-21.qmd)
- [Letter 2917](../2917-to-mary-elizabeth-wormeleylatimer.qmd)
- [Letter 3321](../3321-to-mary-elizabeth-wormeley-latimer-2.qmd)
- [Letter 3342](../3342-to-mary-yonge-18.qmd)
- [Letter 3456](../3456-to-mary-yonge-33.qmd)

