---
title: "George Lillie Craik"
person_id: 379
---

## Biographical Information

(1837-1905)

publisher

A partner in Macmillan, he married (29 April 1865) the novelist Dinah Maria Mulock (1826-1887).

## Letters Mentioning This Person

- [Letter 2060](../2060-alexander-macmillan-to-charlotte-mary-yonge-39.qmd)
- [Letter 2068](../2068-alexander-macmillan-to-charlotte-mary-yonge-42.qmd)
- [Letter 2069](../2069-to-george-lillie-craik-2.qmd)
- [Letter 2071](../2071-george-lillie-craik-to-charlotte-mary-yonge-2.qmd)
- [Letter 2072](../2072-alexander-macmillan-to-charlotte-mary-yonge-43.qmd)
- [Letter 2119](../2119-to-alexander-macmillan-76.qmd)
- [Letter 2128](../2128-to-alexander-macmillan-77.qmd)
- [Letter 2202](../2202-george-lillie-craik-to-charlotte-mary-yonge-3.qmd)
- [Letter 2204](../2204-george-lillie-craik-to-charlotte-mary-yonge.qmd)
- [Letter 2211](../2211-to-george-lillie-craik-3.qmd)
- [Letter 2222](../2222-to-george-lillie-craik-4.qmd)
- [Letter 2229](../2229-alexander-macmillan-to-charlotte-mary-yonge-64.qmd)
- [Letter 2265](../2265-to-george-lillie-craik-5.qmd)
- [Letter 2266](../2266-to-george-lillie-craik-6.qmd)
- [Letter 2345](../2345-to-alexander-macmillan-111.qmd)
- [Letter 2512](../2512-to-george-lillie-craik-18.qmd)
- [Letter 2526](../2526-to-george-lillie-craik-19.qmd)
- [Letter 2529](../2529-to-henry-graves.qmd)
- [Letter 2531](../2531-to-george-lillie-craik-20.qmd)
- [Letter 2542](../2542-to-george-lillie-craik-21.qmd)
- [Letter 2545](../2545-to-george-lillie-craik-22.qmd)
- [Letter 2569](../2569-to-george-lillie-craik-23.qmd)
- [Letter 2571](../2571-to-george-lillie-craik-24.qmd)
- [Letter 2581](../2581-to-george-lillie-craik-26.qmd)
- [Letter 2583](../2583-to-george-lillie-craik-25.qmd)
- [Letter 2586](../2586-to-george-lillie-craik-27.qmd)
- [Letter 2588](../2588-to-george-lillie-craik-28.qmd)
- [Letter 2589](../2589-to-george-lillie-craik-29.qmd)
- [Letter 2591](../2591-to-alexander-macmillan-124.qmd)
- [Letter 2599](../2599-to-george-lillie-craik-30.qmd)
- [Letter 2604](../2604-to-george-lillie-craik-31.qmd)
- [Letter 2609](../2609-to-alexander-macmillan-128.qmd)
- [Letter 2614](../2614-to-george-lillie-craik-32.qmd)
- [Letter 2615](../2615-to-george-lillie-craik-33.qmd)
- [Letter 2617](../2617-to-george-lillie-craik-34.qmd)
- [Letter 2620](../2620-to-george-lillie-craik-35.qmd)
- [Letter 2621](../2621-to-george-lillie-craik-36.qmd)
- [Letter 2622](../2622-to-george-lillie-craik-37.qmd)
- [Letter 2623](../2623-to-george-lillie-craik-38.qmd)
- [Letter 2625](../2625-to-george-lillie-craik-39.qmd)
- [Letter 2627](../2627-to-george-lillie-craik-41.qmd)
- [Letter 2628](../2628-to-george-lillie-craik-42.qmd)
- [Letter 2629](../2629-to-george-lillie-craik-43.qmd)
- [Letter 2631](../2631-to-george-lillie-craik-44.qmd)
- [Letter 2636](../2636-to-george-lillie-craik-45.qmd)
- [Letter 2640](../2640-to-george-lillie-craik-46.qmd)
- [Letter 2654](../2654-to-george-lillie-craik-47.qmd)
- [Letter 2656](../2656-to-george-lillie-craik-48.qmd)
- [Letter 2659](../2659-to-george-lillie-craik-49.qmd)
- [Letter 2664](../2664-to-george-lillie-craik-50.qmd)
- [Letter 2673](../2673-to-george-lillie-craik-51.qmd)
- [Letter 2683](../2683-to-george-lillie-craik-52.qmd)
- [Letter 2699](../2699-to-an-unknown-woman-50.qmd)
- [Letter 2748](../2748-to-george-lillie-craik-53.qmd)
- [Letter 2754](../2754-to-george-lillie-craik-54.qmd)
- [Letter 2764](../2764-to-george-lillie-craik-55.qmd)
- [Letter 2765](../2765-to-george-lillie-craik-56.qmd)
- [Letter 2768](../2768-to-george-lillie-craik-57.qmd)
- [Letter 2793](../2793-to-george-lillie-craik-58.qmd)
- [Letter 2794](../2794-to-george-lillie-craik-59.qmd)
- [Letter 2795](../2795-to-george-lillie-craik-60.qmd)
- [Letter 2820](../2820-to-george-lillie-craik-61.qmd)
- [Letter 2824](../2824-to-george-lillie-craik-62.qmd)
- [Letter 2826](../2826-mary-louisa-molesworth-to-charlotte-mary-yonge.qmd)
- [Letter 2828](../2828-to-george-lillie-craik-63.qmd)
- [Letter 2829](../2829-to-george-lillie-craik-64.qmd)
- [Letter 2830](../2830-to-george-lillie-craik-65.qmd)
- [Letter 2833](../2833-to-george-lillie-craik-66.qmd)
- [Letter 2834](../2834-to-george-lillie-craik-67.qmd)
- [Letter 2835](../2835-to-george-lillie-craik-68.qmd)
- [Letter 2836](../2836-to-george-lillie-craik-69.qmd)
- [Letter 2837](../2837-to-george-lillie-craik-70.qmd)
- [Letter 2838](../2838-to-george-lillie-craik-71.qmd)
- [Letter 2839](../2839-to-george-lillie-craik-72.qmd)
- [Letter 2899](../2899-to-george-lillie-craik-74.qmd)
- [Letter 2900](../2900-to-george-lillie-craik-75.qmd)
- [Letter 2901](../2901-to-george-lillie-craik-76.qmd)
- [Letter 2907](../2907-to-george-lillie-craik.qmd)
- [Letter 3160](../3160-to-george-lillie-craik-7.qmd)
- [Letter 3162](../3162-to-george-lillie-craik-8.qmd)
- [Letter 3211](../3211-to-george-lillie-craik-9.qmd)
- [Letter 3212](../3212-to-george-lillie-craik-10.qmd)
- [Letter 3213](../3213-to-george-lillie-craik-11.qmd)
- [Letter 3214](../3214-to-george-lillie-craik-12.qmd)
- [Letter 3218](../3218-to-john-athelstan-laurie-riley-2.qmd)
- [Letter 3225](../3225-to-george-lillie-craik-13.qmd)
- [Letter 3257](../3257-to-george-lillie-craik-14.qmd)
- [Letter 3271](../3271-to-george-lillie-craik-15.qmd)
- [Letter 3315](../3315-to-frederick-orridge-macmillan-9.qmd)
- [Letter 3472](../3472-to-george-lillie-craik-17.qmd)
- [Letter 3476](../3476-to-george-lillie-craik-16.qmd)
- [Letter 19282](../19282-to-george-lillie-craik.qmd)
- [Letter 19462](../19462-to-george-lillie-craik.qmd)
- [Letter 19551](../19551-george-lillie-craik-to-charlotte-mary-yonge.qmd)
- [Letter 19572](../19572-alexander-macmillan-to-charlotte-mary-yonge.qmd)
- [Letter 19598](../19598-alexander-macmillan-to-charlotte-mary-yonge.qmd)

