---
title: "Nina Cole"
person_id: 326
---

## Biographical Information

correspondent, evidently a friend of the Colborne family.

If the book she sent CMY in 1874 was Nina Cole, <i>Meditations on the Song of Songs</i> (London: Hayes 1874), an anonymous volume identified by Halkett and Laing, that may have been her name.   A person of this name was a committee member of the Church and Stage Guild (founded 1879).  Its objects, according to an advertisement in <i>The Era</i> (13 July 1879) were 'to promote religious and social sympathy between the members of the Church and of the Stage'. 





However, another possible candidate is Anna Cole (1832/3-1909), daughter of the Rev. John Francis Cole, Vicar of Kirdford, near Petworth, Sussex, who was a subscriber to <i>MP</i> and appears in its correspondence column (December 1877) 592.

## Letters Mentioning This Person

- [Letter 2310](../2310-to-miss-cole.qmd)
- [Letter 2516](../2516-to-nina-cole.qmd)
- [Letter 2677](../2677-to-nina-cole-2.qmd)

