---
title: "The Rev. Robert Henry Codrington"
person_id: 312
---

## Biographical Information

(1830-1922)

head of the Melanesian mission 1871-7

He succeeded the Rt. Rev. John Coleridge Patteson as head of the mission to Melanesia;  he was author of a <i>Mota Dictionary</i> and ethnographical works on Melanesia.

## Letters Mentioning This Person

- [Letter 1954](../1954-from-the-right-reverend-john-coleridge-patteson-to-charlotte-mary-yonge-6.qmd)
- [Letter 2147](../2147-the-right-reverend-john-coleridge-patteson-to-charlotte-mary-yonge-4.qmd)
- [Letter 2224](../2224-the-right-reverend-john-coleridge-patteson-to-charlotte-mary-yonge-6.qmd)
- [Letter 2295](../2295-the-right-reverend-john-coleridge-patteson-to-charlotte-mary-yonge-10.qmd)
- [Letter 2355](../2355-the-right-reverend-john-coleridge-patteson-to-charlotte-mary-yonge-11.qmd)
- [Letter 2398](../2398-the-right-reverend-john-coleridge-patteson-to-charlotte-mary-yonge.qmd)
- [Letter 2439](../2439-to-charlotte-cordelia-yonge.qmd)
- [Letter 2447](../2447-to-elizabeth-wordsworth-5.qmd)
- [Letter 2806](../2806-to-frances-sophia-coleridge-patteson-7.qmd)

