---
title: "Blanche Catherine Medhurst"
person_id: 988
---

## Biographical Information

(London 1848- Barnstaple 1925)

social worker and contributor to <i>MP</i> (1873-5)

She was daughter of Francis Hastings Medhurst (d.1852), of Kippax Hall, near Leeds, and Mary Anne Bushnan;  a friend of Mrs Mercier and patroness of Emmeline Spratt. She published a study of workhouses, <i>The Idle Room</i> (1886). [LG 1871, census] The 1861 census shows Mary Anne Medhurst with two other daughters and her mother Anne Bushman (d.1878) living at 29 Dorset Square;  in the 1871 census Blanche is there too.  Hers is an odd story, because her father killed another boy while a private pupil at school and got three years for manslaughter in 1839, coming up before Mr Justice Coleridge; his grandfather, a rich stockbroker, had murdered his wife while insane and was at that time in an asylum. [<i>Times</i>].  She wrote an article in <i>MP</i> (1886) about the Associated Workers League, of which she was evidently a member.

## Letters Mentioning This Person

- [Letter 2464](../2464-to-blanche-catherine-medhurst-2.qmd)
- [Letter 2467](../2467-to-blanche-catherine-medhurst-3.qmd)
- [Letter 2473](../2473-to-blanche-catherine-medhurst-4.qmd)
- [Letter 2479](../2479-to-blanche-catherine-medhurst-5.qmd)
- [Letter 2523](../2523-to-blanche-catherine-medhurst-6.qmd)
- [Letter 2584](../2584-to-blanche-catherine-medhurst-7.qmd)
- [Letter 2642](../2642-to-blanche-catherine-medhurst-8.qmd)
- [Letter 2690](../2690-to-blanche-catherine-medhurst-9.qmd)
- [Letter 3509](../3509-to-blanche-catherine-medhurst.qmd)

