---
title: "Annie Louise Cazenove"
person_id: 274
---

## Biographical Information

(29 Dec 1854-18 Dec 1933)

contributor to <i>MP</i> (1882-8)

She first seems to have entered CMY’s life as an enthusiastic member of the Spider society, writing as the 'Muffin Man'.  Subsequently she assisted Lady Brabazon (later the Countess of Meath) in her charities; she lived at Ravensleigh, Betchworth, Surrey, daughter of Alfred Parr Cazenove and Louise.   [LG Cazenove]

## Letters Mentioning This Person

- [Letter 2536](../2536-to-annie-louise-cazenove-2.qmd)
- [Letter 2741](../2741-to-annie-louise-cazenove-3.qmd)
- [Letter 2808](../2808-to-annie-louise-cazenove-4.qmd)
- [Letter 2859](../2859-to-christabel-rose-coleridge-115.qmd)
- [Letter 2873](../2873-to-arthur-donald-innes-19.qmd)
- [Letter 3409](../3409-to-mary-yonge-12.qmd)
- [Letter 3430](../3430-to-christabel-rose-coleridge-36.qmd)
- [Letter 3465](../3465-to-christabel-rose-coleridge-49.qmd)
- [Letter 3499](../3499-to-annie-louise-cazenove.qmd)
- [Letter 3541](../3541-to-miss-hutchins.qmd)
- [Letter 19829](../19829-to-the-countess-of-meath.qmd)

