---
title: "Sarah Harriet (Richardson) Selwyn"
person_id: 1297
---

## Biographical Information

(1809/10-25 March 1907)

wife of the Rt. Rev. George Augustus Selwyn

Daughter of Sir John Richardson and Harriet Palmer, she was Caroline Abraham's first cousin;  she married (1839) the  Rt. Rev. George Augustus Selwyn.

## Letters Mentioning This Person

- [Letter 1836](../1836-to-frances-sophia-coleridge-patteson-4.qmd)
- [Letter 1845](../1845-to-ann-maria-carter-smith-50.qmd)
- [Letter 1856](../1856-to-harriet-dyke-acland-troyte.qmd)
- [Letter 2215](../2215-to-mary-ann-dyson-5.qmd)
- [Letter 2432](../2432-to-mary-ann-moberly-6-3.qmd)
- [Letter 3044](../3044-frances-mary-yonge-to-alice-arbuthnot-moberly-2.qmd)
- [Letter 3048](../3048-to-mary-anne-dyson-19.qmd)
- [Letter 3054](../3054-to-elizabeth-roberts-35.qmd)
- [Letter 3061](../3061-to-anne-yonge-33.qmd)
- [Letter 3096](../3096-to-the-reverend-edward-coleridge-2.qmd)
- [Letter 3098](../3098-to-harriet-dyke-acland-troyte.qmd)
- [Letter 3226](../3226-to-the-right-reverend-john-richardson-selwyn.qmd)
- [Letter 3588](../3588-to-frances-sophia-coleridge-patteson-2.qmd)
- [Letter 3589](../3589-to-lucy-yonge.qmd)
- [Letter 9097](../9097-to-sarah-harriet-selwyn.qmd)
- [Letter 9109](../9109-to-sarah-harriet-selwyn.qmd)

