---
title: "Harriet Catherine (Sweet) Carr"
person_id: 259
---

## Biographical Information

(1804/5-1895)

contributor to <i>MP</i> (1861)

She married (1825) James Joshua Carr and was the mother of Harriet Catherine (Carr) Romanoff. A friend and neighbour of Ann Carter Smith, she lived at the Warren, Charlton. She contributed an Easter story to <i>MP</i> (1861). A monument in St. George’s Beckenham commemorates James Joshua CARR of Old Charlton Kent 22 May 1865 aged 67. Harriet Catherine Carr widow of above 27 August 1895 aged 90. Samuel Sidney Carr 13 August 1842 aged 1 year 9 months. Captain James Sweet Carr of H M Bombay Staff Corps 28 February 1864 aged 31 sons of James Joshua and Harriet Catherine Carr. Also Janet Susan Carr youngest daughter of J J and H C Carr 16 July 1919 aged 75. Also Harriet Catherine ROMANOFF daughter of J J and H C Carr 10 August 1897 aged 69 at Kishinieff Russia.

## Letters Mentioning This Person

- [Letter 1820](../1820-to-ann-maria-carter-smith-40.qmd)
- [Letter 1837](../1837-to-ann-maria-carter-smith-47.qmd)
- [Letter 2030](../2030-to-alexander-macmillan-43.qmd)

