---
title: "Henriette Elizabeth (Guizot) De Witt"
person_id: 423
---

## Biographical Information

(1829-1908)

novelist and translator

Eldest daughter of the French politician Francois Guizot (1787-1874), she married (1850) Conrad de Witt (1824-1909). [<i>Lettres à sa fille Henriette</i>]

## Letters Mentioning This Person

- [Letter 1953](../1953-to-messrs-macmillan-2.qmd)
- [Letter 1956](../1956-to-messrs-macmillan-3.qmd)
- [Letter 1971](../1971-to-alexander-macmillan-17.qmd)
- [Letter 1995](../1995-to-alexander-macmillan-29.qmd)
- [Letter 2004](../2004-to-elizabeth-missing-sewell-4.qmd)
- [Letter 2006](../2006-to-alexander-macmillan-34.qmd)
- [Letter 2014](../2014-to-alexander-macmillan-37.qmd)
- [Letter 2015](../2015-alexander-macmillan-to-charlotte-mary-yonge-21.qmd)
- [Letter 2034](../2034-to-alexander-macmillan-44.qmd)
- [Letter 2146](../2146-to-alexander-macmillan-84.qmd)
- [Letter 2248](../2248-to-alexander-macmillan-97.qmd)
- [Letter 2286](../2286-to-alexander-macmillan-104.qmd)
- [Letter 2304](../2304-to-sir-william-heathcote-bt-2.qmd)
- [Letter 2328](../2328-to-mary-ann-dyson-10.qmd)
- [Letter 2329](../2329-to-mary-ann-dyson-11.qmd)
- [Letter 2330](../2330-to-mary-ann-dyson-2.qmd)
- [Letter 2331](../2331-to-mary-ann-dyson-12.qmd)
- [Letter 2332](../2332-to-mary-anne-dyson-13-2.qmd)
- [Letter 2333](../2333-to-mary-anne-dyson-10-3.qmd)
- [Letter 2334](../2334-to-mary-ann-dyson-10.qmd)
- [Letter 2336](../2336-to-frances-awdry-2.qmd)
- [Letter 2394](../2394-to-francois-pierre-guillaume-guizot-3.qmd)
- [Letter 2395](../2395-to-bell-and-daldy.qmd)
- [Letter 2409](../2409-to-laura-valentine-3.qmd)
- [Letter 2451](../2451-to-christabel-rose-coleridge-73.qmd)
- [Letter 2499](../2499-to-mary-anne-dyson-23.qmd)
- [Letter 2658](../2658-to-messrs-macmillan.qmd)
- [Letter 2665](../2665-to-henriette-elizabeth-de-witt.qmd)
- [Letter 3300](../3300-to-frederick-orridge-macmillan-or-alexander-macmillan-3.qmd)
- [Letter 3547](../3547-to-margaret-gatty.qmd)
- [Letter 7142](../7142-to-margaret-benson.qmd)
- [Letter 19282](../19282-to-george-lillie-craik.qmd)

