---
title: "Charlotte Fortescue Yonge"
person_id: 1588
---

## Biographical Information

(d. 19 Jan 1940)

cousin of CMY, contributor to <i>MP</i> (1891)

Daughter of the Rev. John Eyre Yonge, her address at death was Cotswold, Station Road, Brading Isle of Wight; probate was granted to Catherine Mildred Leser wife of Karl Frederick Leser [will]

## Letters Mentioning This Person

- [Letter 2005](../2005-to-ellen-julia-johns-3.qmd)
- [Letter 2931](../2931-to-anne-elizabeth-mary-anderson-morshead-7.qmd)
- [Letter 3259](../3259-to-charlotte-anne-elizabeth-moberly.qmd)
- [Letter 3357](../3357-to-mary-yonge-24.qmd)
- [Letter 3366](../3366-to-arthur-duke-coleridge.qmd)
- [Letter 3371](../3371-to-beatrice-heathcote.qmd)
- [Letter 3385](../3385-to-mary-yonge-4.qmd)
- [Letter 3411](../3411-to-charlotte-fortescue-yonge-3.qmd)
- [Letter 3434](../3434-to-mary-yonge-26.qmd)
- [Letter 3470](../3470-to-christabel-rose-coleridge-53.qmd)
- [Letter 3471](../3471-to-christabel-rose-coleridge-54.qmd)
- [Letter 3473](../3473-to-christabel-rose-coleridge-55.qmd)
- [Letter 3478](../3478-to-christabel-rose-coleridge-57.qmd)
- [Letter 3481](../3481-to-charlotte-fortescue-yonge.qmd)
- [Letter 3587](../3587-to-charlotte-fortescue-yonge-2.qmd)

