---
title: "The Rev. John Frewen Moor jr."
person_id: 1046
---

## Biographical Information

(1823-1906)

Vicar of Ampfield

He was perpetual curate of Ampfield from 12 January 1853, and later Vicar of Ampfield. The only son of the Rev. John Frewen Moor, sr. (1798-1879), of Bradfield, and his first wife Mary Stevens (d. 1823), he married Frances Dorothy Grimston (1825/6-1913)  [<i>Alumni Oxonienses</i>; 1861 census]

## Letters Mentioning This Person

- [Letter 1864](../1864-to-charlotte-cordelia-pode.qmd)
- [Letter 1929](../1929-to-the-reverend-john-frewen-moor-17.qmd)
- [Letter 1931](../1931-to-the-reverend-john-frewen-moor-16.qmd)
- [Letter 1960](../1960-to-the-reverend-john-frewen-moor-15.qmd)
- [Letter 1986](../1986-to-the-reverend-john-frewen-moor-14.qmd)
- [Letter 1996](../1996-to-the-reverend-john-frewen-moor-13.qmd)
- [Letter 2056](../2056-to-the-reverend-john-frewen-moor-3.qmd)
- [Letter 2141](../2141-to-the-reverend-john-frewen-moor-12.qmd)
- [Letter 2143](../2143-to-the-reverend-john-frewen-moor-11.qmd)
- [Letter 2176](../2176-to-edith-sophia-jacob-8.qmd)
- [Letter 2287](../2287-to-the-reverend-john-frewen-moor-4.qmd)
- [Letter 2315](../2315-to-the-reverend-john-frewen-moor-10.qmd)
- [Letter 2346](../2346-to-the-reverend-john-frewen-moor-9.qmd)
- [Letter 2350](../2350-to-the-reverend-john-frewen-moor-8.qmd)
- [Letter 2476](../2476-to-the-reverend-john-frewen-moor.qmd)
- [Letter 2706](../2706-to-the-reverend-john-frewen-moor-18.qmd)
- [Letter 2707](../2707-to-the-reverend-john-frewen-moor-19.qmd)
- [Letter 2857](../2857-to-the-reverend-john-frewen-moor-20.qmd)
- [Letter 2925](../2925-to-mary-yonge.qmd)
- [Letter 3219](../3219-to-mr-moore.qmd)
- [Letter 3322](../3322-to-the-reverend-john-frewen-moor-6.qmd)
- [Letter 3323](../3323-to-the-reverend-john-frewen-moor-5.qmd)
- [Letter 3377](../3377-to-frederick-orridge-macmillan.qmd)
- [Letter 3401](../3401-to-the-reverend-john-frewen-moor-7.qmd)
- [Letter 3591](../3591-to-the-reverend-john-frewen-moor-2.qmd)

