---
title: "Elizabeth P. Roberts"
person_id: 1243
---

## Biographical Information

contributor to <i>MP</i> (1852-9)

The author of the ‘Garland for the Year’, who preserved the letters which shed such a useful light on the early history of <i>MP</i>, signed her contributions E. P. R. or Elizabeth P. Roberts.  She may perhaps be identified with Elizabeth Piddocke Roberts (b. Kingswinford, Staffs. 1821) who published a book of verse in 1845. That person was the daughter of John Piddocke Roberts (b.1794/5) and his wife Susannah Maria Morris (b. 1789/90), who had been married at Kingswinford in 1819;  he is described in the 1841 census of Armitage, Staffs. as a land agent, and in the 1851 Isle of Man census as a landed proprietor.  By 1861 Elizabeth and her widowed mother were staying in West Bromwich, and she is described as a governess.  Since the 'Garland' author's father evidently died in 1859 it is likely they are one and the same.





According to the IGI records  she was one of at least ten children, of whom several died young.  Survivors included Rebecca Surgy Roberts (b. 1831) who acted as a companion to a cousin in the Isle of Wight (1851, 1861 census), Phoebe Cordelia Roberts (1828-after 1881) and Martha Sarah Roberts (1835-1909) who married (1852) Thomas Oxenbould, a banker’s clerk.  





Roberts’s ‘Garland for the Year’ may possibly be the ‘semi botanical papers’ of which CMY wrote ‘I used to repent  - of admitting them’. 





[1841 census, Armitage with Handsacre, Staffs.;  parents Isle of Man 1851 census; 1861 census with cousin Lydia Morris, chemist, at West Bromwich;  Oxenboulds, 1871, 1891 census, Handsworth;  BMD indexes; IGI]

## Letters Mentioning This Person

- [Letter 1804](../1804-to-susanna-warren-2.qmd)
- [Letter 1805](../1805-to-elizabeth-roberts.qmd)
- [Letter 2978](../2978-to-elizabeth-roberts-2.qmd)
- [Letter 2980](../2980-to-elizabeth-roberts-3.qmd)
- [Letter 2981](../2981-to-elizabeth-roberts-4.qmd)
- [Letter 2983](../2983-to-elizabeth-roberts-5.qmd)
- [Letter 2984](../2984-to-elizabeth-roberts-6.qmd)
- [Letter 2985](../2985-to-elizabeth-roberts-7.qmd)
- [Letter 2986](../2986-to-elizabeth-roberts-8.qmd)
- [Letter 2988](../2988-to-elizabeth-roberts-9.qmd)
- [Letter 2989](../2989-to-elizabeth-roberts-10.qmd)
- [Letter 2991](../2991-to-elizabeth-roberts-11.qmd)
- [Letter 2992](../2992-to-elizabeth-roberts-12.qmd)
- [Letter 2993](../2993-to-elizabeth-roberts-13.qmd)
- [Letter 2994](../2994-to-elizabeth-roberts-14.qmd)
- [Letter 2995](../2995-to-elizabeth-roberts-15.qmd)
- [Letter 2996](../2996-to-elizabeth-roberts-16.qmd)
- [Letter 2997](../2997-to-elizabeth-roberts-17.qmd)
- [Letter 2998](../2998-to-elizabeth-roberts-18.qmd)
- [Letter 2999](../2999-to-elizabeth-roberts-19.qmd)
- [Letter 3000](../3000-to-elizabeth-roberts-20.qmd)
- [Letter 3001](../3001-to-elizabeth-roberts-21.qmd)
- [Letter 3002](../3002-to-elizabeth-roberts-22.qmd)
- [Letter 3003](../3003-to-elizabeth-roberts-23.qmd)
- [Letter 3004](../3004-to-elizabeth-roberts-24.qmd)
- [Letter 3008](../3008-to-elizabeth-roberts-25.qmd)
- [Letter 3010](../3010-to-elizabeth-roberts-26.qmd)
- [Letter 3012](../3012-to-elizabeth-roberts-27.qmd)
- [Letter 3014](../3014-to-elizabeth-roberts-28.qmd)
- [Letter 3018](../3018-to-elizabeth-roberts-29.qmd)
- [Letter 3021](../3021-to-elizabeth-roberts-30.qmd)
- [Letter 3035](../3035-to-elizabeth-roberts-33.qmd)
- [Letter 3046](../3046-to-elizabeth-roberts-34.qmd)
- [Letter 3054](../3054-to-elizabeth-roberts-35.qmd)
- [Letter 3057](../3057-to-elizabeth-roberts-36.qmd)
- [Letter 3059](../3059-to-elizabeth-roberts-37.qmd)
- [Letter 3100](../3100-to-miss-moorsom.qmd)
- [Letter 3116](../3116-to-elizabeth-roberts-38.qmd)
- [Letter 3146](../3146-to-elizabeth-roberts-39.qmd)
- [Letter 19373](../19373-to-an-unknown-woman.qmd)

