---
title: "The Rev. John Keble"
person_id: 798
---

## Biographical Information

(1792-29 March 1866)

Vicar of Hursley

He was ordained in 1816;  he married (10 Oct 1835) Charlotte Clarke;  he was buried 6 April 1866; he left under £16,000: she left under £45,000 [wills index].

## Letters Mentioning This Person

- [Letter 1791](../1791-to-anne-sturges-bourne-4.qmd)
- [Letter 1801](../1801-from-the-reverend-john-keble-to-frances-mary-yonge-and-charlotte-mary-yonge.qmd)
- [Letter 1804](../1804-to-susanna-warren-2.qmd)
- [Letter 1827](../1827-to-florence-wilford-2.qmd)
- [Letter 1840](../1840-from-the-reverend-john-coleridge-patteson-to-charlotte-mary-yonge-3.qmd)
- [Letter 1862](../1862-from-the-reverend-john-coleridge-patteson-to-charlotte-mary-yonge.qmd)
- [Letter 1885](../1885-from-the-right-reverend-john-coleridge-patteson-to-charlotte-mary-yonge-3.qmd)
- [Letter 1898](../1898-to-anne-yonge-41.qmd)
- [Letter 1900](../1900-from-the-right-reverend-john-coleridge-patteson-to-charlotte-mary-yonge-4.qmd)
- [Letter 2059](../2059-from-the-right-reverend-john-coleridge-patteson-to-charlotte-mary-yonge-7.qmd)
- [Letter 2090](../2090-the-reverend-john-keble-to-charlotte-mary-yonge-5.qmd)
- [Letter 2091](../2091-the-reverend-john-keble-to-charlotte-mary-yonge.qmd)
- [Letter 2105](../2105-to-jean-ingelow-2.qmd)
- [Letter 2110](../2110-to-anne-yonge-43.qmd)
- [Letter 2111](../2111-to-anne-yonge-44.qmd)
- [Letter 2112](../2112-frances-mary-yonge-to-mary-anne-moberly.qmd)
- [Letter 2114](../2114-to-elizabeth-missing-sewell-14.qmd)
- [Letter 2115](../2115-to-jemima-charlotte-mozley.qmd)
- [Letter 2120](../2120-from-the-right-reverend-john-coleridge-patteson-to-charlotte-mary-yonge-8.qmd)
- [Letter 2123](../2123-to-mary-anne-moberly-2.qmd)
- [Letter 2130](../2130-to-mrs-elizabeth-jane-keble.qmd)
- [Letter 2134](../2134-the-right-reverend-john-coleridge-patteson-to-charlotte-mary-yonge-2.qmd)
- [Letter 2138](../2138-the-right-reverend-john-coleridge-patteson-to-charlotte-mary-yonge-3.qmd)
- [Letter 2140](../2140-to-anne-mackenzie.qmd)
- [Letter 2147](../2147-the-right-reverend-john-coleridge-patteson-to-charlotte-mary-yonge-4.qmd)
- [Letter 2167](../2167-to-ann-maria-carter-smith-75.qmd)
- [Letter 2224](../2224-the-right-reverend-john-coleridge-patteson-to-charlotte-mary-yonge-6.qmd)
- [Letter 2270](../2270-to-mary-anne-moberly-3.qmd)
- [Letter 2275](../2275-to-mary-ann-dyson-7.qmd)
- [Letter 2295](../2295-the-right-reverend-john-coleridge-patteson-to-charlotte-mary-yonge-10.qmd)
- [Letter 2300](../2300-to-mary-ann-dyson-8.qmd)
- [Letter 2304](../2304-to-sir-william-heathcote-bt-2.qmd)
- [Letter 2316](../2316-to-the-reverend-henry-parry-liddon.qmd)
- [Letter 2391](../2391-to-susanna-warren-7.qmd)
- [Letter 2415](../2415-to-elizabeth-wordsworth-4.qmd)
- [Letter 2442](../2442-to-sir-william-heathcote-bt-6.qmd)
- [Letter 2443](../2443-to-sir-william-heathcote-bt-7.qmd)
- [Letter 2452](../2452-to-william-garrett-horder-2.qmd)
- [Letter 2453](../2453-to-william-garrett-horder-3.qmd)
- [Letter 2481](../2481-to-an-unknown-woman-38.qmd)
- [Letter 2618](../2618-to-christabel-rose-coleridge-91.qmd)
- [Letter 2641](../2641-to-elizabeth-barnett-17.qmd)
- [Letter 2644](../2644-to-florence-wilford-8.qmd)
- [Letter 2691](../2691-to-the-reverend-william-parsons-warburton-6.qmd)
- [Letter 2783](../2783-to-christabel-rose-coleridge-110.qmd)
- [Letter 2887](../2887-to-arthur-donald-innes-22.qmd)
- [Letter 2902](../2902-to-c-t-hiatt.qmd)
- [Letter 2936](../2936-to-anne-yonge-4.qmd)
- [Letter 2937](../2937-to-anne-yonge-5.qmd)
- [Letter 2938](../2938-to-anne-yonge-6.qmd)
- [Letter 2939](../2939-to-anne-yonge-7.qmd)
- [Letter 2940](../2940-to-anne-yonge-8.qmd)
- [Letter 2942](../2942-to-anne-yonge-10.qmd)
- [Letter 2944](../2944-to-alethea-yonge.qmd)
- [Letter 2945](../2945-to-anne-yonge-12.qmd)
- [Letter 2947](../2947-to-anne-yonge-14.qmd)
- [Letter 2948](../2948-to-anne-yonge-15.qmd)
- [Letter 2952](../2952-to-anne-yonge-19.qmd)
- [Letter 2957](../2957-anne-yonge-to-mary-yonge-2.qmd)
- [Letter 2960](../2960-to-mary-anne-dyson-3.qmd)
- [Letter 2961](../2961-william-crawley-yonge-to-the-reverend-john-yonge.qmd)
- [Letter 2970](../2970-to-mary-anne-dyson-10.qmd)
- [Letter 2972](../2972-to-mary-anne-dyson-12.qmd)
- [Letter 2976](../2976-the-reverend-john-keble-to-charlotte-mary-yonge-2.qmd)
- [Letter 2994](../2994-to-elizabeth-roberts-14.qmd)
- [Letter 2995](../2995-to-elizabeth-roberts-15.qmd)
- [Letter 2997](../2997-to-elizabeth-roberts-17.qmd)
- [Letter 3002](../3002-to-elizabeth-roberts-22.qmd)
- [Letter 3007](../3007-to-mary-anne-dyson-14.qmd)
- [Letter 3011](../3011-the-reverend-john-keble-to-charlotte-mary-yonge-3.qmd)
- [Letter 3012](../3012-to-elizabeth-roberts-27.qmd)
- [Letter 3030](../3030-to-mary-anne-dyson-18.qmd)
- [Letter 3033](../3033-frances-mary-yonge-to-the-reverend-john-yonge.qmd)
- [Letter 3035](../3035-to-elizabeth-roberts-33.qmd)
- [Letter 3048](../3048-to-mary-anne-dyson-19.qmd)
- [Letter 3055](../3055-to-anne-yonge-31.qmd)
- [Letter 3060](../3060-to-anne-yonge-32.qmd)
- [Letter 3061](../3061-to-anne-yonge-33.qmd)
- [Letter 3065](../3065-from-the-reverend-john-keble-to-charlotte-mary-yonge-2.qmd)
- [Letter 3069](../3069-the-reverend-john-keble-to-charlotte-mary-yonge-4.qmd)
- [Letter 3070](../3070-to-alice-arbuthnot-moberly-7.qmd)
- [Letter 3092](../3092-to-ann-maria-carter-smith-8.qmd)
- [Letter 3096](../3096-to-the-reverend-edward-coleridge-2.qmd)
- [Letter 3104](../3104-to-emma-butler.qmd)
- [Letter 3119](../3119-to-anne-yonge-37.qmd)
- [Letter 3121](../3121-from-the-reverend-john-keble-to-charlotte-mary-yonge.qmd)
- [Letter 3122](../3122-to-the-reverend-edward-coleridge-3.qmd)
- [Letter 3124](../3124-to-caroline-elizabeth-cooke-trench-2.qmd)
- [Letter 3140](../3140-to-caroline-elizabeth-cooke-trench-3.qmd)
- [Letter 3147](../3147-to-elizabeth-barnett-13.qmd)
- [Letter 3183](../3183-to-an-unknown-person-8.qmd)
- [Letter 3207](../3207-to-the-reverend-vere-awdry.qmd)
- [Letter 3231](../3231-to-the-very-reverend-george-david-boyle.qmd)
- [Letter 3282](../3282-to-miss-hale.qmd)
- [Letter 3333](../3333-to-mary-elizabeth-christie-2.qmd)
- [Letter 3336](../3336-to-edith-emma-knight.qmd)
- [Letter 3337](../3337-to-mary-elizabeth-christie-4.qmd)
- [Letter 3362](../3362-to-frederick-orridge-macmillan-12.qmd)
- [Letter 3375](../3375-to-frederick-orridge-macmillan-16.qmd)
- [Letter 3376](../3376-to-frederick-orridge-macmillan-17.qmd)
- [Letter 3378](../3378-to-frederick-orridge-macmillan.qmd)
- [Letter 3381](../3381-to-the-countess-of-glasgow.qmd)
- [Letter 3443](../3443-to-christabel-rose-coleridge-38.qmd)
- [Letter 3496](../3496-to-an-unknown-woman-46.qmd)
- [Letter 3574](../3574-to-an-unknown-person-6.qmd)
- [Letter 3592](../3592-to-charlotte-anne-elizabeth-moberly-2.qmd)
- [Letter 3605](../3605-to-an-unknown-woman-6.qmd)
- [Letter 7749](../7749-to-sir-john-taylor-coleridge.qmd)
- [Letter 7759](../7759-to-sir-william-heathcote-bt.qmd)
- [Letter 7852](../7852-to-john-duke-coleridge.qmd)

