---
title: "Dr. James Yonge M.R.C.P., M.D."
person_id: 1614
---

## Biographical Information

(11 March 1793-3 Jan 1870)

uncle of CMY, physician

He married, first (12 Jan 1820), his cousin Margaret Crawley (d. 22 Apr 1867), daughter of Sir Thomas Crawley-Boevey, 3rd Bt.  He married secondly (25 Aug 1868), Anna Susanna Couch (1801-1894).  The children of his first marriage, James 'a few months older than myself, Eleonora, and Edward, the last born in 1827' all died in 1830. [DNB, LG, Coleridge, <i>Life</i> 67, Death index, census returns]

## Letters Mentioning This Person

- [Letter 1945](../1945-to-ann-maria-carter-smith-67.qmd)
- [Letter 2264](../2264-to-the-reverend-duke-yonge-2.qmd)
- [Letter 2340](../2340-to-charlotte-cordelia-yonge-2.qmd)
- [Letter 2349](../2349-to-james-yonge-or-the-rev-john-yonge.qmd)
- [Letter 2364](../2364-to-mary-yonge-34.qmd)
- [Letter 2367](../2367-to-mary-yonge-35.qmd)
- [Letter 2561](../2561-to-mary-yonge-48.qmd)
- [Letter 2956](../2956-to-anne-yonge-23.qmd)
- [Letter 2961](../2961-william-crawley-yonge-to-the-reverend-john-yonge.qmd)
- [Letter 2972](../2972-to-mary-anne-dyson-12.qmd)
- [Letter 3027](../3027-to-anne-yonge-30.qmd)
- [Letter 3028](../3028-to-mary-anne-dyson-16.qmd)
- [Letter 3029](../3029-to-mary-anne-dyson-17.qmd)
- [Letter 3031](../3031-to-elizabeth-barnett-5.qmd)

