---
title: "James John Arnold"
person_id: 62
---

## Biographical Information

(b. Peckham 1834/5)

of Boyatt, surveyor and engineer

He married, first, Sarah (Vine) Arnold (Otterbourne 1821/2-1896).  In the 1861 census she is a spinster farmer of 39 with a companion niece Marianna Vine (b.1843/4) and he is her boarder, aged 26.  He married, secondly in Chelsea in the fourth quarter of 1896, Ellen Vine. He was keeping a hotel in Colchester with his wife Ellen (b. Hargham, Norfolk 1853/4) in 1901.  However, since his second wife seems to be the  Ellen (Drane) Vine (b. Hargham, Norfolk 1853/4), widow and milliner, living with her father in London in 1881 and 1891, it looks as if CMY’s suspicions that he had married within the forbidden limits were unfounded.  Marriage with a deceased wife’s niece was illegal in England and Wales until the passing of the Marriage (Prohibited Degrees) Relationship Act (1931).

## Letters Mentioning This Person

- [Letter 2350](../2350-to-the-reverend-john-frewen-moor-8.qmd)
- [Letter 3331](../3331-to-the-reverend-william-harris-bigg-wither-2.qmd)
- [Letter 3467](../3467-to-mrs-c-e-barrett-lennard.qmd)

