---
title: "The Rev. John Yonge"
person_id: 1623
---

## Biographical Information

(4 Nov 1788-23 Aug 1877)

uncle by marriage of CMY

Rector of Newton Ferrars and squire of Puslinch, he was first cousin once removed and uncle by marriage of CMY.  His father was uncle to WCY, and he married (25 March 1813) Alethea Henrietta Bargus, half-sister of FMY.

## Letters Mentioning This Person

- [Letter 1814](../1814-to-susanna-warren-3.qmd)
- [Letter 1860](../1860-to-frances-mary-peard-2.qmd)
- [Letter 1895](../1895-to-anne-yonge-38.qmd)
- [Letter 1896](../1896-to-anne-yonge-39.qmd)
- [Letter 1897](../1897-to-anne-yonge-40.qmd)
- [Letter 1898](../1898-to-anne-yonge-41.qmd)
- [Letter 1899](../1899-to-anne-yonge-42.qmd)
- [Letter 2041](../2041-to-alexander-macmillan-47.qmd)
- [Letter 2065](../2065-to-alexander-macmillan-56.qmd)
- [Letter 2125](../2125-to-anna-maria-keary.qmd)
- [Letter 2190](../2190-to-edith-sophia-jacob-10.qmd)
- [Letter 2338](../2338-to-the-reverend-duke-yonge.qmd)
- [Letter 2341](../2341-to-mary-yonge-8.qmd)
- [Letter 2342](../2342-to-florence-wilford-5.qmd)
- [Letter 2349](../2349-to-james-yonge-or-the-rev-john-yonge.qmd)
- [Letter 2352](../2352-to-mary-yonge-9.qmd)
- [Letter 2358](../2358-to-mary-yonge-10.qmd)
- [Letter 2420](../2420-to-charlotte-cordelia-yonge-4.qmd)
- [Letter 2440](../2440-to-mary-yonge-37.qmd)
- [Letter 2541](../2541-to-mary-yonge-38.qmd)
- [Letter 2543](../2543-to-augusta-boevey-pode-4.qmd)
- [Letter 2556](../2556-to-mary-yonge-45.qmd)
- [Letter 2561](../2561-to-mary-yonge-48.qmd)
- [Letter 2726](../2726-to-ann-maria-carter-smith-84.qmd)
- [Letter 2815](../2815-to-mary-yonge-52.qmd)
- [Letter 2935](../2935-william-crawley-yonge-to-the-rev-john-yonge-including-charlotte-mary-yonge-to-anne-yonge.qmd)
- [Letter 2948](../2948-to-anne-yonge-15.qmd)
- [Letter 2949](../2949-to-anne-yonge-16.qmd)
- [Letter 2951](../2951-to-anne-yonge-18.qmd)
- [Letter 2957](../2957-anne-yonge-to-mary-yonge-2.qmd)
- [Letter 2961](../2961-william-crawley-yonge-to-the-reverend-john-yonge.qmd)
- [Letter 3027](../3027-to-anne-yonge-30.qmd)
- [Letter 3032](../3032-frances-mary-yonge-to-the-reverend-john-yonge-2.qmd)
- [Letter 3033](../3033-frances-mary-yonge-to-the-reverend-john-yonge.qmd)
- [Letter 3034](../3034-frances-mary-yonge-to-mary-yonge.qmd)
- [Letter 3036](../3036-anne-yonge-to-the-rev-john-yonge.qmd)
- [Letter 3039](../3039-anne-yonge-to-mary-yonge-3.qmd)
- [Letter 3064](../3064-to-anne-yonge-36.qmd)
- [Letter 3107](../3107-anne-yonge-to-the-rev-john-yonge-2.qmd)
- [Letter 3110](../3110-anne-yonge-to-mary-yonge.qmd)
- [Letter 3134](../3134-to-elizabeth-barnett-8.qmd)
- [Letter 3135](../3135-to-elizabeth-barnett-9.qmd)
- [Letter 3563](../3563-to-emma-frances-yonge-3.qmd)

