---
title: "Joanna Elizabeth Patteson"
person_id: 1154
---

## Biographical Information

(1818/9-23 June 1884)

half-sister of the Rt. Rev. John Coleridge Patteson

She was daughter of Sir John Patteson by his first wife Elizabeth Lee (d.1820) and half-sister of Fanny Patteson;  she died at Andover, and was buried at Feniton 28 June 1884. [will],.

## Letters Mentioning This Person

- [Letter 1829](../1829-to-frances-sophia-coleridge-patteson-3.qmd)
- [Letter 1862](../1862-from-the-reverend-john-coleridge-patteson-to-charlotte-mary-yonge.qmd)
- [Letter 2123](../2123-to-mary-anne-moberly-2.qmd)
- [Letter 2154](../2154-the-right-reverend-john-coleridge-patteson-to-charlotte-mary-yonge-5.qmd)
- [Letter 2299](../2299-to-henrietta-elizabeth-fursdon-11.qmd)
- [Letter 2425](../2425-to-frances-sophia-coleridge-patteson-6.qmd)
- [Letter 2449](../2449-to-christabel-rose-coleridge-72.qmd)
- [Letter 2737](../2737-to-the-marchioness-of-salisbury-3.qmd)
- [Letter 2792](../2792-to-mary-anne-moberly-6.qmd)
- [Letter 7798](../7798-to-sir-john-taylor-coleridge.qmd)
- [Letter 19162](../19162-to-frances-mary-peard.qmd)

