---
title: "The Rev. Walter Francis Elgie"
person_id: 478
---

## Biographical Information

(12 Oct 1837-25 Feb 1881)

curate, then Vicar of Otterbourne

He married (1869) Catharine, daughter of Colonel F. Hammond and widow of Captain Webber.  He was a scholar of Lancing 1853, MA St. Edmund Hall 1859, curate of Otterbourne 1870-6, vicar of Otterbourne 1876-81 [Lancing Register]

## Letters Mentioning This Person

- [Letter 2429](../2429-to-mary-anne-dyson-21.qmd)
- [Letter 2440](../2440-to-mary-yonge-37.qmd)
- [Letter 2447](../2447-to-elizabeth-wordsworth-5.qmd)
- [Letter 2519](../2519-to-catharine-elgie-3.qmd)
- [Letter 2547](../2547-to-mary-yonge-40.qmd)
- [Letter 2557](../2557-to-catharine-elgie-4.qmd)
- [Letter 2565](../2565-to-the-parishioners-of-otterbourne-4.qmd)
- [Letter 2695](../2695-to-mary-yonge-49.qmd)
- [Letter 2701](../2701-to-the-reverend-william-parsons-warburton-8.qmd)
- [Letter 2717](../2717-to-christabel-rose-coleridge-101.qmd)
- [Letter 2718](../2718-to-the-reverend-william-parsons-warburton-10.qmd)
- [Letter 2720](../2720-to-ann-maria-carter-smith-82.qmd)
- [Letter 2729](../2729-to-florence-wilford-10.qmd)
- [Letter 2730](../2730-to-ann-maria-carter-smith-86.qmd)

