---
title: "Sir Frederick Orridge Macmillan"
person_id: 942
---

## Biographical Information

(1851-1936)

nephew and partner of Alexander Macmillan

Son of Daniel Macmillan,  he married (1874) Georgiana Elizabeth Warrin, an American;  he returned in 1876 from the U.S. to be partner in firm; he had no children; he was knighted in 1909.  [DNB]

## Letters Mentioning This Person

- [Letter 3180](../3180-to-william-john-woollcombe.qmd)
- [Letter 3188](../3188-to-frederick-orridge-macmillan-6.qmd)
- [Letter 3273](../3273-to-frederick-orridge-macmillan-or-alexander-macmillan-2.qmd)
- [Letter 3278](../3278-to-frederick-orridge-macmillan-7.qmd)
- [Letter 3281](../3281-to-frederick-orridge-macmillan-8.qmd)
- [Letter 3300](../3300-to-frederick-orridge-macmillan-or-alexander-macmillan-3.qmd)
- [Letter 3301](../3301-to-frederick-orridge-macmillan-or-alexander-macmillan.qmd)
- [Letter 3315](../3315-to-frederick-orridge-macmillan-9.qmd)
- [Letter 3316](../3316-to-frederick-orridge-macmillan-10.qmd)
- [Letter 3338](../3338-to-frederick-orridge-macmillan-11.qmd)
- [Letter 3362](../3362-to-frederick-orridge-macmillan-12.qmd)
- [Letter 3363](../3363-to-frederick-orridge-macmillan-13.qmd)
- [Letter 3364](../3364-to-frederick-orridge-macmillan-14.qmd)
- [Letter 3372](../3372-to-frederick-orridge-macmillan-15.qmd)
- [Letter 3375](../3375-to-frederick-orridge-macmillan-16.qmd)
- [Letter 3376](../3376-to-frederick-orridge-macmillan-17.qmd)
- [Letter 3377](../3377-to-frederick-orridge-macmillan.qmd)
- [Letter 3378](../3378-to-frederick-orridge-macmillan.qmd)
- [Letter 3379](../3379-to-frederick-orridge-macmillan-19.qmd)
- [Letter 3382](../3382-to-frederick-orridge-macmillan-5.qmd)
- [Letter 3391](../3391-to-frederick-orridge-macmillan-2.qmd)
- [Letter 3398](../3398-to-frederick-orridge-macmillan-3.qmd)
- [Letter 3400](../3400-to-frederick-orridge-macmillan-4.qmd)
- [Letter 3469](../3469-to-christabel-rose-coleridge-52.qmd)
- [Letter 3470](../3470-to-christabel-rose-coleridge-53.qmd)

