---
title: "Mary Frances Keble Coleridge"
person_id: 351
---

## Biographical Information

(1824-25 March 1898)

daughter of Sir [John Taylor Coleridge](person_344.qmd), cousin and lifelong friend of CMY, member of the Gosling Society

The intimacy between CMY and Mary Coleridge is not well documented  because the letters to her were, Christabel Coleridge states, burnt in an accident, but she is very frequently referred to in letters to others.  Her 1845 engagement to Roundell Palmer, later 1st Earl of Selborne, was broken off, and she never married.  She was devoted to her niece Mildred, daughter of Lord Coleridge, and encouraged CMY to found the Gosling Society partly in order to find an outlet for Mildred's intellectual interests. Her Gosling name was The Old Secretary, but when Mildred lost interest in the society, she did likewise.  She was devastated by the furore over Mildred's 1885 marriage to Charles Warren Adams, who had sued Bernard Coleridge for libel.  In the same year her brother Lord Coleridge had married Amy Lawford, who had previously lived as the wife of her first cousin, but had then had their Gretna Green marriage declared invalid.  It appears that Mary Coleridge, like CMY, consequently disapproved of the second Lady Coleridge, and deplored her influence on her husband. [PB: Coleridge, <i>Story of a Devonshire House</i>]





A portrait of her and her sister Alethea as girls sold in 2006 is illustrated at www.artnet.com/Artists/LotDetailPage.aspx?lot_id=5830456F7F89012700A33CFAA5D

## Letters Mentioning This Person

- [Letter 1795](../1795-to-miss-erskine-2.qmd)
- [Letter 1819](../1819-to-katharine-olive-helmore-2.qmd)
- [Letter 1842](../1842-to-henrietta-elizabeth-fursdon-2.qmd)
- [Letter 1844](../1844-to-henrietta-elizabeth-fursdon-3.qmd)
- [Letter 1849](../1849-to-katharine-olive-helmore-4.qmd)
- [Letter 1895](../1895-to-anne-yonge-38.qmd)
- [Letter 1944](../1944-to-alexander-macmillan-15.qmd)
- [Letter 1956](../1956-to-messrs-macmillan-3.qmd)
- [Letter 1995](../1995-to-alexander-macmillan-29.qmd)
- [Letter 2066](../2066-to-mary-ann-dyson-3.qmd)
- [Letter 2070](../2070-to-katharine-olive-helmore-8.qmd)
- [Letter 2093](../2093-to-frances-mary-peard-9.qmd)
- [Letter 2126](../2126-to-miss-erskine.qmd)
- [Letter 2169](../2169-to-elizabeth-missing-sewell-7.qmd)
- [Letter 2173](../2173-to-christabel-rose-coleridge-10.qmd)
- [Letter 2253](../2253-to-elizabeth-missing-sewell-8.qmd)
- [Letter 2304](../2304-to-sir-william-heathcote-bt-2.qmd)
- [Letter 2352](../2352-to-mary-yonge-9.qmd)
- [Letter 2358](../2358-to-mary-yonge-10.qmd)
- [Letter 2425](../2425-to-frances-sophia-coleridge-patteson-6.qmd)
- [Letter 2554](../2554-to-mary-yonge-43.qmd)
- [Letter 2556](../2556-to-mary-yonge-45.qmd)
- [Letter 2573](../2573-to-christabel-rose-coleridge-87.qmd)
- [Letter 2587](../2587-to-christabel-rose-coleridge-88.qmd)
- [Letter 2663](../2663-to-christabel-rose-coleridge-99.qmd)
- [Letter 2665](../2665-to-henriette-elizabeth-de-witt.qmd)
- [Letter 2667](../2667-to-christabel-rose-coleridge-100.qmd)
- [Letter 2748](../2748-to-george-lillie-craik-53.qmd)
- [Letter 2782](../2782-to-christabel-rose-coleridge-109.qmd)
- [Letter 2783](../2783-to-christabel-rose-coleridge-110.qmd)
- [Letter 2804](../2804-to-the-reverend-william-harris-walter-bigg-wither.qmd)
- [Letter 2812](../2812-to-an-unknown-person-11.qmd)
- [Letter 2880](../2880-to-elizabeth-barnett-22.qmd)
- [Letter 2881](../2881-to-jean-ingelow.qmd)
- [Letter 2923](../2923-to-elizabeth-barnett-23.qmd)
- [Letter 2931](../2931-to-anne-elizabeth-mary-anderson-morshead-7.qmd)
- [Letter 2945](../2945-to-anne-yonge-12.qmd)
- [Letter 2952](../2952-to-anne-yonge-19.qmd)
- [Letter 2953](../2953-to-anne-yonge-20.qmd)
- [Letter 2955](../2955-to-anne-yonge-22.qmd)
- [Letter 2957](../2957-anne-yonge-to-mary-yonge-2.qmd)
- [Letter 2960](../2960-to-mary-anne-dyson-3.qmd)
- [Letter 2971](../2971-to-mary-anne-dyson-11.qmd)
- [Letter 3061](../3061-to-anne-yonge-33.qmd)
- [Letter 3109](../3109-to-frances-mary-yonge-2.qmd)
- [Letter 3320](../3320-to-mary-yonge-16.qmd)
- [Letter 3425](../3425-to-christabel-rose-coleridge-34.qmd)
- [Letter 3480](../3480-to-christabel-rose-coleridge-59.qmd)
- [Letter 3588](../3588-to-frances-sophia-coleridge-patteson-2.qmd)
- [Letter 7691](../7691-to-sir-john-taylor-coleridge.qmd)
- [Letter 7710](../7710-to-sir-john-taylor-coleridge.qmd)
- [Letter 7783](../7783-to-sir-john-taylor-coleridge.qmd)
- [Letter 7798](../7798-to-sir-john-taylor-coleridge.qmd)
- [Letter 7864](../7864-to-john-duke-coleridge.qmd)

