---
title: "François-Pierre-Guillaume Guizot"
person_id: 597
---

## Biographical Information

(4 Oct 1787-12 Sept 1874)

French statesman

## Letters Mentioning This Person

- [Letter 1894](../1894-to-francois-pierre-guillaume-guizot-2.qmd)
- [Letter 1953](../1953-to-messrs-macmillan-2.qmd)
- [Letter 2146](../2146-to-alexander-macmillan-84.qmd)
- [Letter 2286](../2286-to-alexander-macmillan-104.qmd)
- [Letter 2304](../2304-to-sir-william-heathcote-bt-2.qmd)
- [Letter 2328](../2328-to-mary-ann-dyson-10.qmd)
- [Letter 2329](../2329-to-mary-ann-dyson-11.qmd)
- [Letter 2330](../2330-to-mary-ann-dyson-2.qmd)
- [Letter 2331](../2331-to-mary-ann-dyson-12.qmd)
- [Letter 2332](../2332-to-mary-anne-dyson-13-2.qmd)
- [Letter 2333](../2333-to-mary-anne-dyson-10-3.qmd)
- [Letter 2334](../2334-to-mary-ann-dyson-10.qmd)
- [Letter 2335](../2335-to-mary-ann-dyson-12.qmd)
- [Letter 2336](../2336-to-frances-awdry-2.qmd)
- [Letter 2394](../2394-to-francois-pierre-guillaume-guizot-3.qmd)
- [Letter 2414](../2414-to-francois-pierre-guillaume-guizot.qmd)
- [Letter 2499](../2499-to-mary-anne-dyson-23.qmd)
- [Letter 2612](../2612-to-elizabeth-wordsworth-11.qmd)
- [Letter 2798](../2798-to-jemima-blackburn.qmd)
- [Letter 3300](../3300-to-frederick-orridge-macmillan-or-alexander-macmillan-3.qmd)
- [Letter 3333](../3333-to-mary-elizabeth-christie-2.qmd)
- [Letter 19672](../19672-alexander-macmillan-to-charlotte-mary-yonge.qmd)

