---
title: "Henrietta Robertson"
person_id: 1952
---

## Biographical Information

(d.1864)

missionary in Africa

She was first married to a Mr Woodrow, and then to the Rev. R. I Robertson, who worked with Charles Frederick Mackenzie in central Africa.





Henrietta Robertson was the subject of  Anne Mackenzie's book [<i>Mission Life among the Zulu-Kafirs: Memorials of Henrietta Robertson wife of the Rev. R. Robertson compiled chiefly from letters and journals written to the late Bishop Mackenzie and his sisters</i>](../other_books/otherbook_417.qmd) (Cambridge: Deighton 1866) and she also figures in CMY’s [<i>Pioneers and Founders, or, Recent Workers in the Mission Field</i>](../cmy_books/cmybook_90.qmd)  (London: Macmillan 1871).

## Letters Mentioning This Person

- [Letter 2059](../2059-from-the-right-reverend-john-coleridge-patteson-to-charlotte-mary-yonge-7.qmd)
- [Letter 2147](../2147-the-right-reverend-john-coleridge-patteson-to-charlotte-mary-yonge-4.qmd)
- [Letter 3246](../3246-to-the-reverend-john-frederick-watkinson-bullock-9.qmd)

