---
title: "Mary Sophia Paulina Martyn"
person_id: 973
---

## Biographical Information

(1843-1887)

member of the Gosling Society

A Gosling as ‘Pena’, 1859-63, ‘Pena’ was her nickname in real life as well. She was the only child of the Rev. Thomas Waddon Martyn (1808-1846), Rector of Lifton and Vicar of Thorverton, and his wife Sophia (1815/6-1898), daughter of the Rev. Dr. James Coleridge (1789-1857) and his wife Sophia, daughter of Col. Stanhope Badcock. In the 1861 census she was living with this grandmother in Dawlish.  She was a cousin of CMY’s, and also of Bishop Patteson's, and he seems to have made a pet of her before his departure for New Zealand, mentioning her in his letters. [Vivian, <i>Visitations of Cornwall</i>;  1851 census;  PO Devon 1866;  1881 census with mother at Harleston, Cary Crescent, Torquay]

## Letters Mentioning This Person

- [Letter 1851](../1851-to-henrietta-elizabeth-fursdon-4.qmd)
- [Letter 1867](../1867-to-henrietta-elizabeth-fursdon-6.qmd)
- [Letter 2078](../2078-to-christabel-rose-coleridge-7.qmd)
- [Letter 2150](../2150-to-christabel-rose-coleridge-9.qmd)
- [Letter 2811](../2811-to-an-unknown-woman-62.qmd)
- [Letter 3388](../3388-to-christabel-rose-coleridge-27.qmd)
- [Letter 19162](../19162-to-frances-mary-peard.qmd)

