---
title: "Anne Mackenzie"
person_id: 930
---

## Biographical Information

(1813-11 Feb 1877)

writer on missions

Second daughter of Colin Mackenzie (d. 1835),of Portmore,and Elizabeth (d. 1852), daughter of Sir William Forbes of Pitsligo 6th Bt., she edited <i>The Net Cast in Many Waters: Sketches from the Lives of Missionaries</i>;  and cared for her invalid nephew George Ralph Dundas (1844-1869).  [F. Awdry, <i>An Elder Sister</i>; ODNB]

## Letters Mentioning This Person

- [Letter 1883](../1883-to-ann-maria-carter-smith-58.qmd)
- [Letter 1896](../1896-to-anne-yonge-39.qmd)
- [Letter 2014](../2014-to-alexander-macmillan-37.qmd)
- [Letter 2059](../2059-from-the-right-reverend-john-coleridge-patteson-to-charlotte-mary-yonge-7.qmd)
- [Letter 2092](../2092-to-the-reverend-orby-shipley.qmd)
- [Letter 2110](../2110-to-anne-yonge-43.qmd)
- [Letter 2114](../2114-to-elizabeth-missing-sewell-14.qmd)
- [Letter 2115](../2115-to-jemima-charlotte-mozley.qmd)
- [Letter 2120](../2120-from-the-right-reverend-john-coleridge-patteson-to-charlotte-mary-yonge-8.qmd)
- [Letter 2140](../2140-to-anne-mackenzie.qmd)
- [Letter 2147](../2147-the-right-reverend-john-coleridge-patteson-to-charlotte-mary-yonge-4.qmd)
- [Letter 2150](../2150-to-christabel-rose-coleridge-9.qmd)
- [Letter 2164](../2164-to-an-unknown-woman-15.qmd)
- [Letter 2176](../2176-to-edith-sophia-jacob-8.qmd)
- [Letter 2190](../2190-to-edith-sophia-jacob-10.qmd)
- [Letter 2203](../2203-to-margaret-helen-moberly.qmd)
- [Letter 2263](../2263-to-miss-finchcliffe.qmd)
- [Letter 2293](../2293-to-mary-anne-moberly-5.qmd)
- [Letter 2328](../2328-to-mary-ann-dyson-10.qmd)
- [Letter 2347](../2347-to-anne-elizabeth-mary-anderson-morshead-3.qmd)
- [Letter 2348](../2348-to-edith-sophia-jacob-18.qmd)
- [Letter 2480](../2480-to-harriet-poole-2.qmd)
- [Letter 2555](../2555-to-an-unknown-woman-41.qmd)
- [Letter 2584](../2584-to-blanche-catherine-medhurst-7.qmd)
- [Letter 2618](../2618-to-christabel-rose-coleridge-91.qmd)
- [Letter 2796](../2796-to-mary-ann-moberly.qmd)
- [Letter 3245](../3245-to-the-reverend-john-frederick-watkinson-bullock-2.qmd)
- [Letter 3246](../3246-to-the-reverend-john-frederick-watkinson-bullock-9.qmd)
- [Letter 3522](../3522-to-miss-butler.qmd)
- [Letter 19419](../19419-to-florence-wilford.qmd)

