---
title: "Frances Mary Peard"
person_id: 1160
---

## Biographical Information

(1835-1923)

member of the Gosling Society,  novelist, contributor to <i>MP</i> (1866-85) and to the <i>Monthly Paper of Sunday Teaching</i>

She was a Gosling as ‘Fernseed’ from about 1865.  She was the daughter of Captain Peard, RN, and lived at Sparnow, Torquay.  She was  sister of Charlotte (Peard) Kekewich. [Harris, <i>F. M. Peard</i>]

## Letters Mentioning This Person

- [Letter 1860](../1860-to-frances-mary-peard-2.qmd)
- [Letter 1868](../1868-to-frances-mary-peard-12.qmd)
- [Letter 1872](../1872-to-frances-mary-peard-3.qmd)
- [Letter 1873](../1873-to-frances-mary-peard-4.qmd)
- [Letter 1888](../1888-to-frances-mary-peard-5.qmd)
- [Letter 1909](../1909-to-frances-mary-peard-6.qmd)
- [Letter 1910](../1910-to-frances-mary-peard-7.qmd)
- [Letter 1934](../1934-to-frances-mary-peard-8.qmd)
- [Letter 2093](../2093-to-frances-mary-peard-9.qmd)
- [Letter 2098](../2098-to-christabel-rose-coleridge-8.qmd)
- [Letter 2101](../2101-to-alexander-macmillan-70.qmd)
- [Letter 2104](../2104-to-alexander-macmillan-72.qmd)
- [Letter 2119](../2119-to-alexander-macmillan-76.qmd)
- [Letter 2136](../2136-to-alexander-macmillan-80.qmd)
- [Letter 2139](../2139-to-alexander-macmillan-82.qmd)
- [Letter 2150](../2150-to-christabel-rose-coleridge-9.qmd)
- [Letter 2291](../2291-to-christabel-rose-coleridge-18.qmd)
- [Letter 2296](../2296-to-anne-elizabeth-mary-anderson-morshead-2.qmd)
- [Letter 2299](../2299-to-henrietta-elizabeth-fursdon-11.qmd)
- [Letter 2331](../2331-to-mary-ann-dyson-12.qmd)
- [Letter 2336](../2336-to-frances-awdry-2.qmd)
- [Letter 2419](../2419-to-christabel-rose-coleridge-67.qmd)
- [Letter 2430](../2430-to-janetta-sewell.qmd)
- [Letter 2475](../2475-to-christabel-rose-coleridge-79.qmd)
- [Letter 2478](../2478-to-gertrude-louisa-legrand-jacob.qmd)
- [Letter 2547](../2547-to-mary-yonge-40.qmd)
- [Letter 2574](../2574-to-hezekiah-butterworth.qmd)
- [Letter 2750](../2750-to-christabel-rose-coleridge-106.qmd)
- [Letter 2765](../2765-to-george-lillie-craik-56.qmd)
- [Letter 2891](../2891-to-miss-kirke.qmd)
- [Letter 2921](../2921-to-frances-mary-peard-10.qmd)
- [Letter 3416](../3416-to-christabel-rose-coleridge-22.qmd)
- [Letter 3418](../3418-to-christabel-rose-coleridge-24.qmd)
- [Letter 3419](../3419-to-christabel-rose-coleridge-2.qmd)
- [Letter 3420](../3420-to-christabel-rose-coleridge-26.qmd)
- [Letter 3487](../3487-to-frances-mary-peard.qmd)
- [Letter 3511](../3511-to-frederick-james-furnivall-6.qmd)
- [Letter 3528](../3528-to-frances-mary-peard-11.qmd)
- [Letter 19162](../19162-to-frances-mary-peard.qmd)
- [Letter 19354](../19354-to-frances-mary-peard.qmd)
- [Letter 19419](../19419-to-florence-wilford.qmd)
- [Letter 19653](../19653-alexander-macmillan-to-charlotte-mary-yonge.qmd)
- [Letter 19661](../19661-alexander-macmillan-to-charlotte-mary-yonge.qmd)
- [Letter 19667](../19667-alexander-macmillan-to-charlotte-mary-yonge.qmd)

