---
title: "William Crawley Yonge"
person_id: 1631
---

## Biographical Information

(2 June 1795-26 Feb 1854)

father of CMY

He married (25 Oct 1822) Frances Mary Bargus.


His funeral was held on Saturday 4 March 1854.

## Letters Mentioning This Person

- [Letter 1802](../1802-to-ann-maria-carter-smith-37.qmd)
- [Letter 1836](../1836-to-frances-sophia-coleridge-patteson-4.qmd)
- [Letter 1898](../1898-to-anne-yonge-41.qmd)
- [Letter 1961](../1961-to-alice-arbuthnot-moberly.qmd)
- [Letter 1991](../1991-to-ann-maria-carter-smith-70.qmd)
- [Letter 2167](../2167-to-ann-maria-carter-smith-75.qmd)
- [Letter 2270](../2270-to-mary-anne-moberly-3.qmd)
- [Letter 2275](../2275-to-mary-ann-dyson-7.qmd)
- [Letter 2280](../2280-to-caroline-elizabeth-cooke-trench-4.qmd)
- [Letter 2330](../2330-to-mary-ann-dyson-2.qmd)
- [Letter 2385](../2385-to-sir-william-heathcote-bt-3.qmd)
- [Letter 2641](../2641-to-elizabeth-barnett-17.qmd)
- [Letter 2644](../2644-to-florence-wilford-8.qmd)
- [Letter 2732](../2732-to-caroline-elizabeth-cooke-trench.qmd)
- [Letter 2821](../2821-to-gertrude-mary-ireland-blackburne-6.qmd)
- [Letter 2881](../2881-to-jean-ingelow.qmd)
- [Letter 2908](../2908-to-edward-augustus-freeman-14.qmd)
- [Letter 2935](../2935-william-crawley-yonge-to-the-rev-john-yonge-including-charlotte-mary-yonge-to-anne-yonge.qmd)
- [Letter 2936](../2936-to-anne-yonge-4.qmd)
- [Letter 2939](../2939-to-anne-yonge-7.qmd)
- [Letter 2945](../2945-to-anne-yonge-12.qmd)
- [Letter 2946](../2946-to-anne-yonge-13.qmd)
- [Letter 2949](../2949-to-anne-yonge-16.qmd)
- [Letter 2951](../2951-to-anne-yonge-18.qmd)
- [Letter 2952](../2952-to-anne-yonge-19.qmd)
- [Letter 2955](../2955-to-anne-yonge-22.qmd)
- [Letter 2956](../2956-to-anne-yonge-23.qmd)
- [Letter 2957](../2957-anne-yonge-to-mary-yonge-2.qmd)
- [Letter 2961](../2961-william-crawley-yonge-to-the-reverend-john-yonge.qmd)
- [Letter 2972](../2972-to-mary-anne-dyson-12.qmd)
- [Letter 2979](../2979-to-anne-yonge-25.qmd)
- [Letter 2987](../2987-to-anne-yonge-26.qmd)
- [Letter 3007](../3007-to-mary-anne-dyson-14.qmd)
- [Letter 3008](../3008-to-elizabeth-roberts-25.qmd)
- [Letter 3017](../3017-to-anne-yonge-29.qmd)
- [Letter 3019](../3019-to-mary-anne-dyson-15.qmd)
- [Letter 3025](../3025-to-elizabeth-roberts-32.qmd)
- [Letter 3027](../3027-to-anne-yonge-30.qmd)
- [Letter 3028](../3028-to-mary-anne-dyson-16.qmd)
- [Letter 3029](../3029-to-mary-anne-dyson-17.qmd)
- [Letter 3031](../3031-to-elizabeth-barnett-5.qmd)
- [Letter 3032](../3032-frances-mary-yonge-to-the-reverend-john-yonge-2.qmd)
- [Letter 3033](../3033-frances-mary-yonge-to-the-reverend-john-yonge.qmd)
- [Letter 3035](../3035-to-elizabeth-roberts-33.qmd)
- [Letter 3036](../3036-anne-yonge-to-the-rev-john-yonge.qmd)
- [Letter 3040](../3040-to-anna-butler-5.qmd)
- [Letter 3053](../3053-to-elizabeth-barnett-6.qmd)
- [Letter 3093](../3093-to-jemima-blackburn-9.qmd)
- [Letter 3134](../3134-to-elizabeth-barnett-8.qmd)
- [Letter 3140](../3140-to-caroline-elizabeth-cooke-trench-3.qmd)
- [Letter 3146](../3146-to-elizabeth-roberts-39.qmd)
- [Letter 3161](../3161-to-an-unknown-man-12.qmd)
- [Letter 3163](../3163-to-the-reverend-john-julian.qmd)
- [Letter 3231](../3231-to-the-very-reverend-george-david-boyle.qmd)
- [Letter 3317](../3317-to-mary-elizabeth-wormeley-latimer.qmd)
- [Letter 3328](../3328-to-clifford-wyndham-holgate.qmd)
- [Letter 3333](../3333-to-mary-elizabeth-christie-2.qmd)
- [Letter 3417](../3417-to-mrs-swinton-2.qmd)
- [Letter 3429](../3429-to-miss-e-m-walker-5.qmd)
- [Letter 3585](../3585-to-gertrude-mary-ireland-blackburne-2.qmd)
- [Letter 7691](../7691-to-sir-john-taylor-coleridge.qmd)
- [Letter 7759](../7759-to-sir-william-heathcote-bt.qmd)
- [Letter 7852](../7852-to-john-duke-coleridge.qmd)
- [Letter 7864](../7864-to-john-duke-coleridge.qmd)

