---
title: "Anna Butler"
person_id: 237
---

## Biographical Information

(b.1825/6)

sister of the Very Rev. William John Butler, contributor to <i>MP</i> (1852)

An obscure figure but an important early contributor to <i>MP</i>, she seems to have shared the family scholarly interests, being a student of German and Danish and author of a book CMY refers to as your 'Scandinavian book'  in early 1856.   The letters in the Fairclough collection are clearly addressed to a sister of William Butler, who had two, Frances, who married in 1843 and died in 1851, and Anna (b.1825/6), who was still alive in 1892, author of <i>Likes and Dislikes: Some Passages in the Life of Emily Marsden</i> (1858) and several other works published as by ‘The author of Likes and Dislikes', viz., <i>Philip Bezant, or, Is Revenge Sweet</i>?  (1859), <i>The Brotherhood of St. John the Evangelist at Berlin</i> (1859),  <i>Chilcote Park, or, The Sisters</i> (1860) and <i>The Post Office Window, Being a Tale of the Night School</i> (1862).  The identification is confirmed by payments to Miss A. Butler in the bank account.

## Letters Mentioning This Person

- [Letter 1790](../1790-to-anna-butler-18.qmd)
- [Letter 1806](../1806-to-anna-butler.qmd)
- [Letter 2877](../2877-to-anna-butler-19.qmd)
- [Letter 3023](../3023-to-anna-butler-2.qmd)
- [Letter 3024](../3024-to-anna-butler-3.qmd)
- [Letter 3038](../3038-to-anna-butler-4.qmd)
- [Letter 3040](../3040-to-anna-butler-5.qmd)
- [Letter 3068](../3068-to-anna-butler-6.qmd)
- [Letter 3077](../3077-to-anna-butler-7.qmd)
- [Letter 3079](../3079-to-anna-butler-8.qmd)
- [Letter 3082](../3082-to-anna-butler-9.qmd)
- [Letter 3083](../3083-to-anna-butler-10.qmd)
- [Letter 3084](../3084-to-anna-butler-11.qmd)
- [Letter 3085](../3085-to-anna-butler-12.qmd)
- [Letter 3086](../3086-to-anna-butler-13.qmd)
- [Letter 3091](../3091-to-anna-butler-14.qmd)
- [Letter 3101](../3101-to-anna-butler-15.qmd)
- [Letter 3102](../3102-to-anna-butler-16.qmd)
- [Letter 3115](../3115-to-anna-butler-17.qmd)
- [Letter 3522](../3522-to-miss-butler.qmd)

