---
title: "Frances Emily (Moberly) Awdry"
person_id: 81
---

## Biographical Information

(30 May 1844-24 November 1921)

author of elementary science textbooks

  She was a member of the Gosling Society as ‘Humble Bee’ approximately 1859-1868. Always known as Emily, she was goddaughter to CMY's mother FMY.  Daughter of the Rt. Rev. George Moberly, she married (4 August 1868) the Rt. Rev. William Awdry (1842-1910). While he was a schoolmaster at Winchester, they both promoted the extension lectures.

## Letters Mentioning This Person

- [Letter 1825](../1825-to-katharine-olive-helmore-3.qmd)
- [Letter 1842](../1842-to-henrietta-elizabeth-fursdon-2.qmd)
- [Letter 1850](../1850-to-katharine-olive-helmore-5.qmd)
- [Letter 1857](../1857-to-charlotte-sophia-fursdon.qmd)
- [Letter 1867](../1867-to-henrietta-elizabeth-fursdon-6.qmd)
- [Letter 1960](../1960-to-the-reverend-john-frewen-moor-15.qmd)
- [Letter 2270](../2270-to-mary-anne-moberly-3.qmd)
- [Letter 2275](../2275-to-mary-ann-dyson-7.qmd)
- [Letter 2276](../2276-to-mary-anne-moberly-4.qmd)
- [Letter 2352](../2352-to-mary-yonge-9.qmd)
- [Letter 2410](../2410-to-edith-sophia-jacob-19.qmd)
- [Letter 2465](../2465-to-christabel-rose-coleridge-77.qmd)
- [Letter 2469](../2469-to-anne-mercier-6.qmd)
- [Letter 2646](../2646-to-frances-emily-awdry.qmd)
- [Letter 2982](../2982-to-alice-arbuthnot-moberly-4.qmd)
- [Letter 3013](../3013-to-alice-arbuthnot-moberly-5.qmd)
- [Letter 3047](../3047-frances-mary-yonge-to-alice-arbuthnot-moberly.qmd)
- [Letter 3048](../3048-to-mary-anne-dyson-19.qmd)
- [Letter 3197](../3197-to-elizabeth-barnett-14.qmd)
- [Letter 3355](../3355-to-helena-heathcote-4.qmd)
- [Letter 3380](../3380-to-marianne-bigg-wither-2.qmd)

