---
title: "Mary Anne Frances Martin"
person_id: 971
---

## Biographical Information

(1829-1922)

teacher and author

She was head of the junior school of Bedford College from its foundation 1853 until its closure 1868, editor of the Sunday Library for Household Reading from 1867, involved in the Working Womens College, later named after her Frances Martin College, friend and flatmate of Dinah Mulock 1850-9.

## Letters Mentioning This Person

- [Letter 2159](../2159-frances-martin-to-alexander-macmillan-2.qmd)
- [Letter 2162](../2162-frances-martin-to-alexander-macmillan-3.qmd)
- [Letter 2165](../2165-frances-martin-to-alexander-macmillan-4.qmd)
- [Letter 2168](../2168-alexander-macmillan-to-charlotte-mary-yonge-47.qmd)
- [Letter 2170](../2170-alexander-macmillan-to-charlotte-mary-yonge-48.qmd)
- [Letter 2172](../2172-alexander-macmillan-to-charlotte-mary-yonge-50.qmd)
- [Letter 2181](../2181-to-alexander-macmillan-87.qmd)
- [Letter 2182](../2182-alexander-macmillan-to-charlotte-mary-yonge-53.qmd)
- [Letter 2191](../2191-alexander-macmillan-to-charlotte-mary-yonge-55.qmd)
- [Letter 2192](../2192-frances-martin-to-alexander-macmillan.qmd)
- [Letter 2193](../2193-to-alexander-macmillan-91.qmd)
- [Letter 2194](../2194-alexander-macmillan-to-charlotte-mary-yonge-56.qmd)
- [Letter 2202](../2202-george-lillie-craik-to-charlotte-mary-yonge-3.qmd)
- [Letter 2204](../2204-george-lillie-craik-to-charlotte-mary-yonge.qmd)
- [Letter 2213](../2213-to-alexander-macmillan-93.qmd)
- [Letter 2214](../2214-alexander-macmillan-to-charlotte-mary-yonge-60.qmd)
- [Letter 2216](../2216-alexander-macmillan-to-frances-martin.qmd)
- [Letter 2219](../2219-alexander-macmillan-to-charlotte-mary-yonge-61.qmd)
- [Letter 2226](../2226-alexander-macmillan-to-charlotte-mary-yonge-62.qmd)
- [Letter 2328](../2328-to-mary-ann-dyson-10.qmd)
- [Letter 2330](../2330-to-mary-ann-dyson-2.qmd)
- [Letter 2331](../2331-to-mary-ann-dyson-12.qmd)
- [Letter 2332](../2332-to-mary-anne-dyson-13-2.qmd)
- [Letter 2333](../2333-to-mary-anne-dyson-10-3.qmd)
- [Letter 2361](../2361-to-alexander-macmillan-112.qmd)
- [Letter 2381](../2381-to-an-unknown-woman-or-to-alexander-macmillan.qmd)
- [Letter 2396](../2396-to-alexander-macmillan-117.qmd)
- [Letter 3212](../3212-to-george-lillie-craik-10.qmd)

