---
title: "Edward Augustus Freeman"
person_id: 523
---

## Biographical Information

(1823-1892)

historian

Friend and collaborator of CMY, father of Margaret and Florence Freeman. [ODNB]

## Letters Mentioning This Person

- [Letter 2151](../2151-to-edward-augustus-freeman.qmd)
- [Letter 2376](../2376-to-edward-augustus-freeman-2.qmd)
- [Letter 2426](../2426-to-edward-augustus-freeman-3.qmd)
- [Letter 2455](../2455-to-edward-augustus-freeman-4.qmd)
- [Letter 2456](../2456-to-edward-augustus-freeman-5.qmd)
- [Letter 2457](../2457-to-edward-augustus-freeman-6.qmd)
- [Letter 2474](../2474-to-edward-augustus-freeman-7.qmd)
- [Letter 2497](../2497-to-edward-augustus-freeman-8.qmd)
- [Letter 2511](../2511-to-the-hon-laura-elizabeth-palmer-4.qmd)
- [Letter 2514](../2514-to-edward-augustus-freeman-9.qmd)
- [Letter 2521](../2521-to-edward-augustus-freeman-10.qmd)
- [Letter 2526](../2526-to-george-lillie-craik-19.qmd)
- [Letter 2562](../2562-edward-augustus-freeman-to-charlotte-mary-yonge.qmd)
- [Letter 2563](../2563-to-anna-rachel-bramston-4.qmd)
- [Letter 2586](../2586-to-george-lillie-craik-27.qmd)
- [Letter 2591](../2591-to-alexander-macmillan-124.qmd)
- [Letter 2594](../2594-to-alexander-macmillan-125.qmd)
- [Letter 2597](../2597-to-alexander-macmillan-127.qmd)
- [Letter 2599](../2599-to-george-lillie-craik-30.qmd)
- [Letter 2603](../2603-to-edward-augustus-freeman-11.qmd)
- [Letter 2629](../2629-to-george-lillie-craik-43.qmd)
- [Letter 2657](../2657-to-alexander-macmillan-134.qmd)
- [Letter 2664](../2664-to-george-lillie-craik-50.qmd)
- [Letter 2868](../2868-to-edward-augustus-freeman-13.qmd)
- [Letter 2890](../2890-to-anne-sturges-bourne.qmd)
- [Letter 2908](../2908-to-edward-augustus-freeman-14.qmd)
- [Letter 2910](../2910-to-edward-augustus-freeman-15.qmd)
- [Letter 2915](../2915-to-edward-augustus-freeman-16.qmd)
- [Letter 3201](../3201-to-arthur-john-butler-7.qmd)
- [Letter 3442](../3442-to-christabel-rose-coleridge-37.qmd)
- [Letter 3543](../3543-to-edward-augustus-freeman-12.qmd)

