---
title: "Sir John Duke Coleridge"
person_id: 343
---

## Biographical Information

1st Lord Coleridge

(3 Dec 1820-14 June 1894)

Lord Chief Justice, contributor to <i>MP</i> (1878)

He married first (11 Aug 1846), Jane Fortescue Seymour (1824/5-1878); and, secondly (1885) Amy Augusta Jackson Lawford (1853-1933), who had previously passed for some years as the wife of her cousin John Davies, but whose Gretna Green marriage had been declared void in 1878.  He was knighted in December 1868 on becoming solicitor general; he was created (1874) Lord Coleridge on being made chief justice of the common pleas; he became Lord Chief Justice in 1880.  [ODNB]

## Letters Mentioning This Person

- [Letter 1950](../1950-sir-william-heathcote-to-charlotte-mary-yonge.qmd)
- [Letter 1956](../1956-to-messrs-macmillan-3.qmd)
- [Letter 2077](../2077-to-elizabeth-missing-sewell-5.qmd)
- [Letter 2357](../2357-to-arthur-john-butler-6.qmd)
- [Letter 2440](../2440-to-mary-yonge-37.qmd)
- [Letter 2444](../2444-to-sir-william-heathcote-bt-8.qmd)
- [Letter 2556](../2556-to-mary-yonge-45.qmd)
- [Letter 2637](../2637-to-the-hon-sophia-matilda-palmer-6.qmd)
- [Letter 2665](../2665-to-henriette-elizabeth-de-witt.qmd)
- [Letter 2676](../2676-to-alexander-macmillan-136.qmd)
- [Letter 2710](../2710-to-an-unknown-woman-52.qmd)
- [Letter 2782](../2782-to-christabel-rose-coleridge-109.qmd)
- [Letter 2783](../2783-to-christabel-rose-coleridge-110.qmd)
- [Letter 2952](../2952-to-anne-yonge-19.qmd)
- [Letter 2955](../2955-to-anne-yonge-22.qmd)
- [Letter 2966](../2966-to-mary-anne-dyson-6.qmd)
- [Letter 3015](../3015-to-anne-yonge-28.qmd)
- [Letter 3425](../3425-to-christabel-rose-coleridge-34.qmd)
- [Letter 7852](../7852-to-john-duke-coleridge.qmd)
- [Letter 7864](../7864-to-john-duke-coleridge.qmd)
- [Letter 7883](../7883-to-john-duke-coleridge.qmd)

