---
title: "Frances Eliza (Orridge) Macmillan"
person_id: 941
---

## Biographical Information

(1821-1867)

sister-in-law and partner of Alexander Macmillan

She married (1850) Daniel Macmillan (1813-1857) [ODNB]

## Letters Mentioning This Person

- [Letter 1927](../1927-alexander-macmillan-to-charlotte-mary-yonge-6.qmd)
- [Letter 1928](../1928-alexander-macmillan-to-charlotte-mary-yonge-7.qmd)
- [Letter 1930](../1930-to-alexander-macmillan-9.qmd)
- [Letter 1939](../1939-alexander-macmillan-to-charlotte-mary-yonge-8.qmd)
- [Letter 1940](../1940-to-alexander-macmillan-14.qmd)
- [Letter 1955](../1955-alexander-macmillan-to-charlotte-mary-yonge-10.qmd)
- [Letter 1957](../1957-alexander-macmillan-to-charlotte-mary-yonge-11.qmd)
- [Letter 1958](../1958-to-alexander-macmillan-16.qmd)
- [Letter 1964](../1964-to-alexander-macmillan-33.qmd)
- [Letter 1971](../1971-to-alexander-macmillan-17.qmd)
- [Letter 1994](../1994-to-alexander-macmillan-28.qmd)
- [Letter 2010](../2010-alexander-macmillan-to-charlotte-mary-yonge-19.qmd)
- [Letter 2016](../2016-alexander-macmillan-to-charlotte-mary-yonge-22.qmd)
- [Letter 2040](../2040-alexander-macmillan-to-charlotte-mary-yonge-32.qmd)
- [Letter 2043](../2043-alexander-macmillan-to-charlotte-mary-yonge-33.qmd)
- [Letter 2060](../2060-alexander-macmillan-to-charlotte-mary-yonge-39.qmd)
- [Letter 2084](../2084-to-alexander-macmillanm066-1865-12-08.qmd)
- [Letter 2133](../2133-to-alexander-macmillan-79.qmd)
- [Letter 2381](../2381-to-an-unknown-woman-or-to-alexander-macmillan.qmd)
- [Letter 19563](../19563-alexander-macmillan-to-charlotte-mary-yonge.qmd)
- [Letter 19598](../19598-alexander-macmillan-to-charlotte-mary-yonge.qmd)
- [Letter 19674](../19674-alexander-macmillan-to-charlotte-mary-yonge.qmd)

