---
title: "Margaret (Scott) Gatty"
person_id: 549
---

## Biographical Information

(1809-1873)

children’s writer and naturalist

She married (8 July 1839) the Rev. Alfred Gatty (1813-1903), Vicar of Ecclesfield; she was the mother of Juliana Horatia (Gatty) Ewing, and a contributor to <i>MP</i> (1857-69).   Gatty’s <i>Aunt Judy’s Tales</i> (1859) and <i>Aunt Judy’s Letters</i> (1862) were made up of contributions to the <i>MP</i> from 1858 to 1865. 'Aunt Judy' was there represented as an older sister telling stories to her younger brothers and sisters, and was based on Gatty’s daughter [Juliana Horatia Gatty](person_494.qmd) (1841-1885), later Ewing, who herself began to contribute to the <i>MP</i> in 1861. In 1866 Gatty began to edit a periodical for George Bell called <i>[Aunt Judy’s Magazine](../organizations/other_54.qmd)</i> and most of the later fiction of both mother and daughter appeared there.

## Letters Mentioning This Person

- [Letter 1804](../1804-to-susanna-warren-2.qmd)
- [Letter 1838](../1838-to-margaret-gatty-2.qmd)
- [Letter 1852](../1852-to-margaret-gatty-3.qmd)
- [Letter 1871](../1871-to-george-bell-and-sons-2.qmd)
- [Letter 1881](../1881-to-ann-maria-carter-smith-57.qmd)
- [Letter 1922](../1922-to-margaret-gatty-4.qmd)
- [Letter 2013](../2013-alexander-macmillan-to-charlotte-mary-yonge-20.qmd)
- [Letter 2014](../2014-to-alexander-macmillan-37.qmd)
- [Letter 2102](../2102-to-margaret-gatty-5.qmd)
- [Letter 2218](../2218-to-laura-valentine-2.qmd)
- [Letter 2392](../2392-margaret-gatty-to-charlotte-mary-yonge.qmd)
- [Letter 3524](../3524-to-an-unknown-woman-20.qmd)
- [Letter 3536](../3536-to-mrs-elder.qmd)
- [Letter 3547](../3547-to-margaret-gatty.qmd)
- [Letter 3574](../3574-to-an-unknown-person-6.qmd)
- [Letter 9411](../9411-to-horatia-sophia-elder.qmd)

