---
title: "Emma Frances (Walter) Yonge"
person_id: 1604
---

## Biographical Information

(Dehra Dun 18 Feb 1839-5 Aug 1913)

sister-in-law of CMY

Known as Frances, she married (9 Sept 1858) Julian Bargus Yonge (1830-1891). [India Office, Bombay Baptisms]

## Letters Mentioning This Person

- [Letter 1920](../1920-to-the-reverend-algernon-wodehouse.qmd)
- [Letter 1946](../1946-to-ann-maria-carter-smith-68.qmd)
- [Letter 2074](../2074-to-alexander-macmillan-58.qmd)
- [Letter 2090](../2090-the-reverend-john-keble-to-charlotte-mary-yonge-5.qmd)
- [Letter 2106](../2106-to-elizabeth-missing-sewell-6.qmd)
- [Letter 2264](../2264-to-the-reverend-duke-yonge-2.qmd)
- [Letter 2271](../2271-to-mary-ann-dyson-6.qmd)
- [Letter 2275](../2275-to-mary-ann-dyson-7.qmd)
- [Letter 2280](../2280-to-caroline-elizabeth-cooke-trench-4.qmd)
- [Letter 2281](../2281-to-ann-maria-carter-smith-79.qmd)
- [Letter 2304](../2304-to-sir-william-heathcote-bt-2.qmd)
- [Letter 2328](../2328-to-mary-ann-dyson-10.qmd)
- [Letter 2329](../2329-to-mary-ann-dyson-11.qmd)
- [Letter 2330](../2330-to-mary-ann-dyson-2.qmd)
- [Letter 2331](../2331-to-mary-ann-dyson-12.qmd)
- [Letter 2332](../2332-to-mary-anne-dyson-13-2.qmd)
- [Letter 2333](../2333-to-mary-anne-dyson-10-3.qmd)
- [Letter 2334](../2334-to-mary-ann-dyson-10.qmd)
- [Letter 2341](../2341-to-mary-yonge-8.qmd)
- [Letter 2369](../2369-to-christabel-rose-coleridge-61.qmd)
- [Letter 2399](../2399-to-anne-sturges-bourne-8.qmd)
- [Letter 2427](../2427-to-miss-cassell.qmd)
- [Letter 2461](../2461-to-christabel-rose-coleridge-76.qmd)
- [Letter 2538](../2538-to-augusta-boevey-pode-3.qmd)
- [Letter 2547](../2547-to-mary-yonge-40.qmd)
- [Letter 2553](../2553-to-mary-yonge-44.qmd)
- [Letter 2556](../2556-to-mary-yonge-45.qmd)
- [Letter 2566](../2566-to-mrs-alfred-wigan.qmd)
- [Letter 2798](../2798-to-jemima-blackburn.qmd)
- [Letter 2804](../2804-to-the-reverend-william-harris-walter-bigg-wither.qmd)
- [Letter 2805](../2805-to-mary-yonge-51.qmd)
- [Letter 2809](../2809-to-the-hon-mrs-joyce.qmd)
- [Letter 2831](../2831-to-sophia-jane-harrison-2.qmd)
- [Letter 3119](../3119-to-anne-yonge-37.qmd)
- [Letter 3122](../3122-to-the-reverend-edward-coleridge-3.qmd)
- [Letter 3125](../3125-to-anne-sturges-bourne-3.qmd)
- [Letter 3140](../3140-to-caroline-elizabeth-cooke-trench-3.qmd)
- [Letter 3194](../3194-to-helen-emma-yonge-2.qmd)
- [Letter 3195](../3195-to-emma-frances-yonge.qmd)
- [Letter 3204](../3204-to-helen-emma-yonge.qmd)
- [Letter 3279](../3279-to-mary-yonge-14.qmd)
- [Letter 3283](../3283-charles-wooldridge-to-charlotte-mary-yonge-3.qmd)
- [Letter 3289](../3289-charles-wooldridge-to-charlotte-mary-yonge-4.qmd)
- [Letter 3290](../3290-to-charles-wooldridge-2.qmd)
- [Letter 3291](../3291-charles-wooldridge-to-charlotte-mary-yonge-5.qmd)
- [Letter 3292](../3292-to-charles-wooldridge-3.qmd)
- [Letter 3293](../3293-charles-wooldridge-to-charlotte-mary-yonge-6.qmd)
- [Letter 3294](../3294-to-charles-wooldridge-4.qmd)
- [Letter 3296](../3296-charles-wooldridge-to-charlotte-mary-yonge-7.qmd)
- [Letter 3297](../3297-charles-wooldridge-to-charlotte-mary-yonge-8.qmd)
- [Letter 3298](../3298-charles-wooldridge-to-emma-frances-yonge.qmd)
- [Letter 3307](../3307-to-charles-wooldridge-5.qmd)
- [Letter 3309](../3309-to-charles-wooldridge-6.qmd)
- [Letter 3350](../3350-to-mary-yonge-21.qmd)
- [Letter 3351](../3351-to-mary-yonge-22.qmd)
- [Letter 3393](../3393-to-mary-yonge-3.qmd)
- [Letter 3409](../3409-to-mary-yonge-12.qmd)
- [Letter 3411](../3411-to-charlotte-fortescue-yonge-3.qmd)
- [Letter 3421](../3421-to-christabel-rose-coleridge-31.qmd)
- [Letter 3430](../3430-to-christabel-rose-coleridge-36.qmd)
- [Letter 3431](../3431-to-mary-yonge-25.qmd)
- [Letter 3434](../3434-to-mary-yonge-26.qmd)
- [Letter 3435](../3435-to-mary-yonge-27.qmd)
- [Letter 3443](../3443-to-christabel-rose-coleridge-38.qmd)
- [Letter 3454](../3454-to-mary-yonge-31.qmd)
- [Letter 3456](../3456-to-mary-yonge-33.qmd)
- [Letter 3469](../3469-to-christabel-rose-coleridge-52.qmd)
- [Letter 3470](../3470-to-christabel-rose-coleridge-53.qmd)
- [Letter 3476](../3476-to-george-lillie-craik-16.qmd)
- [Letter 3510](../3510-to-ellen-julia-johns-11.qmd)
- [Letter 3550](../3550-to-hannah-carey.qmd)
- [Letter 3563](../3563-to-emma-frances-yonge-3.qmd)
- [Letter 3569](../3569-to-mary.qmd)

