---
title: "Jane Mary (Dampier) Smith-Dampier"
person_id: 1345
---

## Biographical Information

(1836/7-Dec 1906)

novelist, neighbour of CMY

Jane Mary Dampier and her sister Emily Dampier (b.1838/9) lived at Twyford House, Twyford. This accounts for her visiting (1870) with Mrs Buston, the wife of the vicar of Twyford.  Jane married (1873) Alfred Fowler Smith and adopted the surname Smith-Dampier: she was the author of a novel, <i>Journal of Lady Beatrix Graham</i> (1870) which was published with an introduction by CMY.  Some of her work was published as by Mrs Fowler Smith. In the 1871 census Jane Mary Dampier was living unmarried at Twyford House with her sister Emily Dampier (b.1838/9), describes her occupation as 'keeping things in order'. By the time of her death she was calling herself Smith-Dampier. They were daughters of John L. Dampier and Margaret Dampier;  he was Vice-Warden of the Stannaries, and died 1851-61. [COPAC; 1871 census; 1841 census; death register]

## Letters Mentioning This Person

- [Letter 2240](../2240-to-jane-mary-smith-dampier-2.qmd)
- [Letter 2368](../2368-to-jane-mary-dampier.qmd)
- [Letter 2383](../2383-to-jane-mary-dampier-2.qmd)
- [Letter 3535](../3535-to-jane-mary-smith-dampier.qmd)
- [Letter 3538](../3538-to-emily-or-jane-dampier.qmd)
- [Letter 3539](../3539-to-emily-or-jane-dampier-2.qmd)

