---
title: "Edith Emma (Butler) Knight"
person_id: 822
---

## Biographical Information

(4? March 1851-1936)

member of the Gosling Society, daughter of the Very Rev. William John Butler

Known as Emma Butler, she was the daughter of CMY’s great friends the Rev. William Butler, Vicar of Wantage and later Dean of Lincoln and his wife Emma Barnett (1813-1894).  A member of the Gosling Society as ‘Frog’,  she married (Oct-Dec 1877) as his third wife, Edward Lewis Knight (1817-1882), of Hornacott Manor, Cornwall.  She was an associate of the Wantage sisterhood.  She inherited her aunt Elizabeth Barnett's letters from CMY and lent them to both Coleridge and Romanes. [LG 1906 Knight of Wolverley, will, <i>Life and Letters of Dean Butler; Memoirs of Arthur John Butler</i>]

## Letters Mentioning This Person

- [Letter 1847](../1847-to-elizabeth-barnett-or-edith-emma-butler.qmd)
- [Letter 2288](../2288-to-the-reverend-william-john-butler-2.qmd)
- [Letter 2289](../2289-to-christabel-rose-coleridge-60.qmd)
- [Letter 2291](../2291-to-christabel-rose-coleridge-18.qmd)
- [Letter 2322](../2322-to-arthur-john-butler-3.qmd)
- [Letter 2326](../2326-to-arthur-john-butler.qmd)
- [Letter 2369](../2369-to-christabel-rose-coleridge-61.qmd)
- [Letter 2379](../2379-to-christabel-rose-coleridge-63.qmd)
- [Letter 2382](../2382-to-christabel-rose-coleridge-64.qmd)
- [Letter 2411](../2411-to-christabel-rose-coleridge-65.qmd)
- [Letter 2510](../2510-to-christabel-rose-coleridge-80.qmd)
- [Letter 2520](../2520-to-edith-emma-butler.qmd)
- [Letter 2590](../2590-to-christabel-rose-coleridge-89.qmd)
- [Letter 2923](../2923-to-elizabeth-barnett-23.qmd)
- [Letter 3336](../3336-to-edith-emma-knight.qmd)
- [Letter 3403](../3403-to-mary-caroline-butler.qmd)
- [Letter 3557](../3557-to-mrs-white.qmd)

