---
title: "Frances Mary (Bargus) Yonge"
person_id: 1606
---

## Biographical Information

(1795-28 Sept 1868)

mother of CMY

FMY married (25 Oct 1822) William Crawley Yonge.  [Hampshire: - Marriage License allegations, Bishop of Winchester, 1689-1837 has: Yonge, William-Crawley, of Cornwood, co. Devon, gent., b., s. of Duke & Catherine Yonge, bap. 26 Jun 1795 , at C., by affidavit of John Yonge, of Puslink, co. Devon, clerk, & Frances-Mary Bargus, of Otterbourne, dau. of Thomas and Mary Bargus, b. 13 Jan , bap. 14 Jan 1793 , at St. Michael's, Winchester, at O., 23 Oct 1822.]

## Letters Mentioning This Person

- [Letter 1789](../1789-to-frances-dorothy-moor.qmd)
- [Letter 1801](../1801-from-the-reverend-john-keble-to-frances-mary-yonge-and-charlotte-mary-yonge.qmd)
- [Letter 1815](../1815-from-frances-mary-yonge-to-anne-sturges-bourne.qmd)
- [Letter 1817](../1817-to-anne-sturges-bourne-6.qmd)
- [Letter 1824](../1824-to-ann-maria-carter-smith-44.qmd)
- [Letter 1838](../1838-to-margaret-gatty-2.qmd)
- [Letter 1848](../1848-to-the-reverend-william-george-henderson.qmd)
- [Letter 1888](../1888-to-frances-mary-peard-5.qmd)
- [Letter 1895](../1895-to-anne-yonge-38.qmd)
- [Letter 1896](../1896-to-anne-yonge-39.qmd)
- [Letter 1897](../1897-to-anne-yonge-40.qmd)
- [Letter 1901](../1901-to-frederick-james-furnivall-2.qmd)
- [Letter 1931](../1931-to-the-reverend-john-frewen-moor-16.qmd)
- [Letter 1942](../1942-to-ann-catherine-johns.qmd)
- [Letter 1946](../1946-to-ann-maria-carter-smith-68.qmd)
- [Letter 1952](../1952-to-frederick-james-furnivall-3.qmd)
- [Letter 1996](../1996-to-the-reverend-john-frewen-moor-13.qmd)
- [Letter 2005](../2005-to-ellen-julia-johns-3.qmd)
- [Letter 2009](../2009-to-ellen-julia-johns-4.qmd)
- [Letter 2036](../2036-to-alexander-macmillan-45.qmd)
- [Letter 2066](../2066-to-mary-ann-dyson-3.qmd)
- [Letter 2080](../2080-to-alexander-macmillan-61.qmd)
- [Letter 2091](../2091-the-reverend-john-keble-to-charlotte-mary-yonge.qmd)
- [Letter 2111](../2111-to-anne-yonge-44.qmd)
- [Letter 2112](../2112-frances-mary-yonge-to-mary-anne-moberly.qmd)
- [Letter 2124](../2124-to-charles-lutwidge-dodgson.qmd)
- [Letter 2132](../2132-to-edith-sophia-jacob-2.qmd)
- [Letter 2136](../2136-to-alexander-macmillan-80.qmd)
- [Letter 2176](../2176-to-edith-sophia-jacob-8.qmd)
- [Letter 2179](../2179-to-an-unknown-man-11.qmd)
- [Letter 2203](../2203-to-margaret-helen-moberly.qmd)
- [Letter 2217](../2217-frances-mary-yonge-to-edith-sophia-jacob.qmd)
- [Letter 2220](../2220-to-ellen-julia-johns-9.qmd)
- [Letter 2225](../2225-to-the-right-reverend-samuel-wilberforce.qmd)
- [Letter 2240](../2240-to-jane-mary-smith-dampier-2.qmd)
- [Letter 2243](../2243-to-alexander-macmillan-94.qmd)
- [Letter 2249](../2249-to-edith-sophia-jacob-12.qmd)
- [Letter 2250](../2250-to-edith-sophia-jacob-13.qmd)
- [Letter 2251](../2251-to-edith-sophia-jacob-14.qmd)
- [Letter 2255](../2255-to-christabel-rose-coleridge-16.qmd)
- [Letter 2260](../2260-to-edith-sophia-jacob-15.qmd)
- [Letter 2261](../2261-to-miss-north.qmd)
- [Letter 2263](../2263-to-miss-finchcliffe.qmd)
- [Letter 2264](../2264-to-the-reverend-duke-yonge-2.qmd)
- [Letter 2267](../2267-to-christabel-rose-coleridge-17.qmd)
- [Letter 2268](../2268-to-edith-sophia-jacob-16.qmd)
- [Letter 2270](../2270-to-mary-anne-moberly-3.qmd)
- [Letter 2272](../2272-to-alexander-macmillan-100.qmd)
- [Letter 2273](../2273-the-right-reverend-john-coleridge-patteson-to-charlotte-mary-yonge-9.qmd)
- [Letter 2274](../2274-to-gertrude-louisa-legrand-jacob-2.qmd)
- [Letter 2277](../2277-to-edith-sophia-jacob-17.qmd)
- [Letter 2279](../2279-to-ellen-julia-johns.qmd)
- [Letter 2281](../2281-to-ann-maria-carter-smith-79.qmd)
- [Letter 2293](../2293-to-mary-anne-moberly-5.qmd)
- [Letter 2295](../2295-the-right-reverend-john-coleridge-patteson-to-charlotte-mary-yonge-10.qmd)
- [Letter 2454](../2454-to-william-garrett-horder.qmd)
- [Letter 2601](../2601-to-the-reverend-richard-st-john-tyrwhitt.qmd)
- [Letter 2644](../2644-to-florence-wilford-8.qmd)
- [Letter 2685](../2685-to-mary-rogers.qmd)
- [Letter 2798](../2798-to-jemima-blackburn.qmd)
- [Letter 2835](../2835-to-george-lillie-craik-68.qmd)
- [Letter 2908](../2908-to-edward-augustus-freeman-14.qmd)
- [Letter 2932](../2932-to-anne-yonge.qmd)
- [Letter 2935](../2935-william-crawley-yonge-to-the-rev-john-yonge-including-charlotte-mary-yonge-to-anne-yonge.qmd)
- [Letter 2938](../2938-to-anne-yonge-6.qmd)
- [Letter 2939](../2939-to-anne-yonge-7.qmd)
- [Letter 2944](../2944-to-alethea-yonge.qmd)
- [Letter 2945](../2945-to-anne-yonge-12.qmd)
- [Letter 2946](../2946-to-anne-yonge-13.qmd)
- [Letter 2947](../2947-to-anne-yonge-14.qmd)
- [Letter 2948](../2948-to-anne-yonge-15.qmd)
- [Letter 2949](../2949-to-anne-yonge-16.qmd)
- [Letter 2954](../2954-to-anne-yonge-21.qmd)
- [Letter 2955](../2955-to-anne-yonge-22.qmd)
- [Letter 2956](../2956-to-anne-yonge-23.qmd)
- [Letter 2957](../2957-anne-yonge-to-mary-yonge-2.qmd)
- [Letter 2961](../2961-william-crawley-yonge-to-the-reverend-john-yonge.qmd)
- [Letter 2962](../2962-frances-mary-yonge-to-mary-anne-dyson.qmd)
- [Letter 2964](../2964-to-mary-anne-dyson-5.qmd)
- [Letter 2969](../2969-to-mary-anne-dyson-9.qmd)
- [Letter 2971](../2971-to-mary-anne-dyson-11.qmd)
- [Letter 2972](../2972-to-mary-anne-dyson-12.qmd)
- [Letter 2974](../2974-to-alice-arbuthnot-moberly-3.qmd)
- [Letter 2977](../2977-to-anne-yonge-24.qmd)
- [Letter 2979](../2979-to-anne-yonge-25.qmd)
- [Letter 2987](../2987-to-anne-yonge-26.qmd)
- [Letter 2990](../2990-to-the-reverend-dr-george-moberly.qmd)
- [Letter 3006](../3006-to-mary-anne-dyson-13.qmd)
- [Letter 3007](../3007-to-mary-anne-dyson-14.qmd)
- [Letter 3024](../3024-to-anna-butler-3.qmd)
- [Letter 3027](../3027-to-anne-yonge-30.qmd)
- [Letter 3028](../3028-to-mary-anne-dyson-16.qmd)
- [Letter 3029](../3029-to-mary-anne-dyson-17.qmd)
- [Letter 3030](../3030-to-mary-anne-dyson-18.qmd)
- [Letter 3032](../3032-frances-mary-yonge-to-the-reverend-john-yonge-2.qmd)
- [Letter 3033](../3033-frances-mary-yonge-to-the-reverend-john-yonge.qmd)
- [Letter 3034](../3034-frances-mary-yonge-to-mary-yonge.qmd)
- [Letter 3036](../3036-anne-yonge-to-the-rev-john-yonge.qmd)
- [Letter 3039](../3039-anne-yonge-to-mary-yonge-3.qmd)
- [Letter 3044](../3044-frances-mary-yonge-to-alice-arbuthnot-moberly-2.qmd)
- [Letter 3048](../3048-to-mary-anne-dyson-19.qmd)
- [Letter 3052](../3052-to-jemima-blackburn-5.qmd)
- [Letter 3053](../3053-to-elizabeth-barnett-6.qmd)
- [Letter 3055](../3055-to-anne-yonge-31.qmd)
- [Letter 3060](../3060-to-anne-yonge-32.qmd)
- [Letter 3061](../3061-to-anne-yonge-33.qmd)
- [Letter 3062](../3062-to-anne-yonge-34.qmd)
- [Letter 3063](../3063-to-anne-yonge-35.qmd)
- [Letter 3066](../3066-to-an-unknown-woman-8.qmd)
- [Letter 3069](../3069-the-reverend-john-keble-to-charlotte-mary-yonge-4.qmd)
- [Letter 3071](../3071-to-alice-arbuthnot-moberly-8.qmd)
- [Letter 3077](../3077-to-anna-butler-7.qmd)
- [Letter 3095](../3095-frances-mary-yonge-to-anne-sturges-bourne.qmd)
- [Letter 3107](../3107-anne-yonge-to-the-rev-john-yonge-2.qmd)
- [Letter 3109](../3109-to-frances-mary-yonge-2.qmd)
- [Letter 3110](../3110-anne-yonge-to-mary-yonge.qmd)
- [Letter 3111](../3111-to-frances-mary-yonge.qmd)
- [Letter 3119](../3119-to-anne-yonge-37.qmd)
- [Letter 3122](../3122-to-the-reverend-edward-coleridge-3.qmd)
- [Letter 3126](../3126-to-ann-maria-carter-smith-15.qmd)
- [Letter 3128](../3128-to-ann-maria-carter-smith-17.qmd)
- [Letter 3134](../3134-to-elizabeth-barnett-8.qmd)
- [Letter 3140](../3140-to-caroline-elizabeth-cooke-trench-3.qmd)
- [Letter 3148](../3148-to-dorothea-beale-2.qmd)
- [Letter 3149](../3149-dorothea-beale-to-charlotte-mary-yonge.qmd)
- [Letter 3163](../3163-to-the-reverend-john-julian.qmd)
- [Letter 3232](../3232-to-the-parishioners-of-otterbourne-2.qmd)
- [Letter 3328](../3328-to-clifford-wyndham-holgate.qmd)
- [Letter 3358](../3358-to-louisa-fanny-field.qmd)
- [Letter 3371](../3371-to-beatrice-heathcote.qmd)
- [Letter 3385](../3385-to-mary-yonge-4.qmd)
- [Letter 3386](../3386-to-christabel-rose-coleridge-25.qmd)
- [Letter 3428](../3428-to-miss-e-m-walker-6.qmd)
- [Letter 3429](../3429-to-miss-e-m-walker-5.qmd)
- [Letter 3434](../3434-to-mary-yonge-26.qmd)
- [Letter 3451](../3451-to-mary-yonge-30.qmd)
- [Letter 3492](../3492-to-an-unknown-woman-10.qmd)
- [Letter 3587](../3587-to-charlotte-fortescue-yonge-2.qmd)
- [Letter 7710](../7710-to-sir-john-taylor-coleridge.qmd)
- [Letter 7749](../7749-to-sir-john-taylor-coleridge.qmd)
- [Letter 7759](../7759-to-sir-william-heathcote-bt.qmd)
- [Letter 7864](../7864-to-john-duke-coleridge.qmd)
- [Letter 7883](../7883-to-john-duke-coleridge.qmd)
- [Letter 19162](../19162-to-frances-mary-peard.qmd)
- [Letter 19258](../19258-to-frances-jane-dodgson.qmd)

