---
title: "Alethea (Yonge) Anderson Morshead"
person_id: 27
---

## Biographical Information

(28 March 1815-22 July 1863)

cousin of CMY

The eldest daughter of the Rev. John Yonge of Puslinch and Alethea Henrietta Bargus, she married (1845) John Philip Anderson Morshead of Widey Court, her second cousin, whose paternal grandmother was Elizabeth Yonge of Puslinch.  They had six sons. She and her younger sister Anne were known as ‘great A and little a’, after a nursery rhyme.  [LG 1871 Morshead]

## Letters Mentioning This Person

- [Letter 1895](../1895-to-anne-yonge-38.qmd)
- [Letter 1896](../1896-to-anne-yonge-39.qmd)
- [Letter 1897](../1897-to-anne-yonge-40.qmd)
- [Letter 1898](../1898-to-anne-yonge-41.qmd)
- [Letter 1899](../1899-to-anne-yonge-42.qmd)
- [Letter 2338](../2338-to-the-reverend-duke-yonge.qmd)
- [Letter 2936](../2936-to-anne-yonge-4.qmd)
- [Letter 2938](../2938-to-anne-yonge-6.qmd)
- [Letter 2939](../2939-to-anne-yonge-7.qmd)
- [Letter 2944](../2944-to-alethea-yonge.qmd)
- [Letter 2945](../2945-to-anne-yonge-12.qmd)
- [Letter 2949](../2949-to-anne-yonge-16.qmd)
- [Letter 2951](../2951-to-anne-yonge-18.qmd)
- [Letter 2955](../2955-to-anne-yonge-22.qmd)
- [Letter 2957](../2957-anne-yonge-to-mary-yonge-2.qmd)
- [Letter 2977](../2977-to-anne-yonge-24.qmd)
- [Letter 2979](../2979-to-anne-yonge-25.qmd)
- [Letter 3036](../3036-anne-yonge-to-the-rev-john-yonge.qmd)
- [Letter 3062](../3062-to-anne-yonge-34.qmd)
- [Letter 3110](../3110-anne-yonge-to-mary-yonge.qmd)

