---
title: "Mary Yonge"
person_id: 1626
---

## Biographical Information

(1816/7-2 April 1910)

cousin of CMY

Second daughter of the Rev. John Yonge and Alethea Henrietta Bargus, she was the last surviving of their ten children.

## Letters Mentioning This Person

- [Letter 1864](../1864-to-charlotte-cordelia-pode.qmd)
- [Letter 1895](../1895-to-anne-yonge-38.qmd)
- [Letter 1897](../1897-to-anne-yonge-40.qmd)
- [Letter 1898](../1898-to-anne-yonge-41.qmd)
- [Letter 1899](../1899-to-anne-yonge-42.qmd)
- [Letter 2264](../2264-to-the-reverend-duke-yonge-2.qmd)
- [Letter 2338](../2338-to-the-reverend-duke-yonge.qmd)
- [Letter 2339](../2339-to-mary-yonge-7.qmd)
- [Letter 2340](../2340-to-charlotte-cordelia-yonge-2.qmd)
- [Letter 2341](../2341-to-mary-yonge-8.qmd)
- [Letter 2342](../2342-to-florence-wilford-5.qmd)
- [Letter 2345](../2345-to-alexander-macmillan-111.qmd)
- [Letter 2352](../2352-to-mary-yonge-9.qmd)
- [Letter 2358](../2358-to-mary-yonge-10.qmd)
- [Letter 2362](../2362-to-mary-yonge-11.qmd)
- [Letter 2364](../2364-to-mary-yonge-34.qmd)
- [Letter 2367](../2367-to-mary-yonge-35.qmd)
- [Letter 2372](../2372-to-mary-yonge-36.qmd)
- [Letter 2420](../2420-to-charlotte-cordelia-yonge-4.qmd)
- [Letter 2440](../2440-to-mary-yonge-37.qmd)
- [Letter 2541](../2541-to-mary-yonge-38.qmd)
- [Letter 2543](../2543-to-augusta-boevey-pode-4.qmd)
- [Letter 2544](../2544-to-mary-yonge-39.qmd)
- [Letter 2547](../2547-to-mary-yonge-40.qmd)
- [Letter 2550](../2550-to-mary-yonge-41.qmd)
- [Letter 2552](../2552-to-mary-yonge-42.qmd)
- [Letter 2553](../2553-to-mary-yonge-44.qmd)
- [Letter 2554](../2554-to-mary-yonge-43.qmd)
- [Letter 2556](../2556-to-mary-yonge-45.qmd)
- [Letter 2559](../2559-to-mary-yonge-46.qmd)
- [Letter 2560](../2560-to-mary-yonge-47.qmd)
- [Letter 2561](../2561-to-mary-yonge-48.qmd)
- [Letter 2595](../2595-to-augusta-boevey-pode.qmd)
- [Letter 2695](../2695-to-mary-yonge-49.qmd)
- [Letter 2746](../2746-to-mary-yonge-50.qmd)
- [Letter 2805](../2805-to-mary-yonge-51.qmd)
- [Letter 2815](../2815-to-mary-yonge-52.qmd)
- [Letter 2916](../2916-to-mary-yonge-53.qmd)
- [Letter 2925](../2925-to-mary-yonge.qmd)
- [Letter 2931](../2931-to-anne-elizabeth-mary-anderson-morshead-7.qmd)
- [Letter 2945](../2945-to-anne-yonge-12.qmd)
- [Letter 2949](../2949-to-anne-yonge-16.qmd)
- [Letter 2951](../2951-to-anne-yonge-18.qmd)
- [Letter 2954](../2954-to-anne-yonge-21.qmd)
- [Letter 2955](../2955-to-anne-yonge-22.qmd)
- [Letter 2957](../2957-anne-yonge-to-mary-yonge-2.qmd)
- [Letter 2961](../2961-william-crawley-yonge-to-the-reverend-john-yonge.qmd)
- [Letter 2979](../2979-to-anne-yonge-25.qmd)
- [Letter 2987](../2987-to-anne-yonge-26.qmd)
- [Letter 3017](../3017-to-anne-yonge-29.qmd)
- [Letter 3034](../3034-frances-mary-yonge-to-mary-yonge.qmd)
- [Letter 3039](../3039-anne-yonge-to-mary-yonge-3.qmd)
- [Letter 3060](../3060-to-anne-yonge-32.qmd)
- [Letter 3061](../3061-to-anne-yonge-33.qmd)
- [Letter 3064](../3064-to-anne-yonge-36.qmd)
- [Letter 3110](../3110-anne-yonge-to-mary-yonge.qmd)
- [Letter 3224](../3224-to-mary-yonge-13.qmd)
- [Letter 3240](../3240-to-dorothea-yonge.qmd)
- [Letter 3260](../3260-to-anne-elizabeth-mary-anderson-morshead-5.qmd)
- [Letter 3279](../3279-to-mary-yonge-14.qmd)
- [Letter 3287](../3287-to-mary-yonge-15.qmd)
- [Letter 3320](../3320-to-mary-yonge-16.qmd)
- [Letter 3340](../3340-to-mary-yonge-17.qmd)
- [Letter 3342](../3342-to-mary-yonge-18.qmd)
- [Letter 3346](../3346-to-mary-yonge-19.qmd)
- [Letter 3348](../3348-to-mary-yonge-20.qmd)
- [Letter 3350](../3350-to-mary-yonge-21.qmd)
- [Letter 3351](../3351-to-mary-yonge-22.qmd)
- [Letter 3354](../3354-to-mary-yonge-23.qmd)
- [Letter 3357](../3357-to-mary-yonge-24.qmd)
- [Letter 3374](../3374-to-misey.qmd)
- [Letter 3385](../3385-to-mary-yonge-4.qmd)
- [Letter 3388](../3388-to-christabel-rose-coleridge-27.qmd)
- [Letter 3393](../3393-to-mary-yonge-3.qmd)
- [Letter 3404](../3404-to-mary-yonge-5.qmd)
- [Letter 3408](../3408-to-mary-yonge-6.qmd)
- [Letter 3409](../3409-to-mary-yonge-12.qmd)
- [Letter 3431](../3431-to-mary-yonge-25.qmd)
- [Letter 3434](../3434-to-mary-yonge-26.qmd)
- [Letter 3435](../3435-to-mary-yonge-27.qmd)
- [Letter 3436](../3436-to-miss-e-m-walker-3.qmd)
- [Letter 3448](../3448-to-mary-yonge-28.qmd)
- [Letter 3449](../3449-to-mary-yonge-29.qmd)
- [Letter 3451](../3451-to-mary-yonge-30.qmd)
- [Letter 3454](../3454-to-mary-yonge-31.qmd)
- [Letter 3455](../3455-to-mary-yonge-32.qmd)
- [Letter 3456](../3456-to-mary-yonge-33.qmd)
- [Letter 3595](../3595-to-mary-yonge-2.qmd)

