---
title: "The Rev. Henry Walter Brock"
person_id: 201
---

## Biographical Information

(17 May 1849-Oct 1919)

Vicar of Otterbourne 1881-1892

He married (3 Jan 1882) Amy Gabrielle Powell (d. 10 Feb 1947). He served as vicar of Otterbourne from 1881, resigned 1892 and until his death was Rector of St Pierre-du-Bois, Guernsey (succeeding his father, the Very Rev Carey Brock, 1824-1892, dean of Guernsey). [<i>John Keble’s Parishes</i>; LG 1952 Brock]

## Letters Mentioning This Person

- [Letter 2723](../2723-to-christabel-rose-coleridge-102.qmd)
- [Letter 2729](../2729-to-florence-wilford-10.qmd)
- [Letter 2733](../2733-to-christabel-rose-coleridge-104.qmd)
- [Letter 2739](../2739-to-an-unknown-woman-54.qmd)
- [Letter 2783](../2783-to-christabel-rose-coleridge-110.qmd)
- [Letter 2788](../2788-to-the-hon-mrs-montgomery-moore-3.qmd)
- [Letter 2867](../2867-to-elizabeth-barnett-20.qmd)
- [Letter 2878](../2878-to-anne-elizabeth-mary-anderson-morshead.qmd)
- [Letter 3194](../3194-to-helen-emma-yonge-2.qmd)
- [Letter 3197](../3197-to-elizabeth-barnett-14.qmd)
- [Letter 3204](../3204-to-helen-emma-yonge.qmd)

