---
title: "Gertrude Walter"
person_id: 1462
---

## Biographical Information

(Shotapoor 24 May 1849-20 May 1897)

housemate of CMY, sister-in-law of JBY

Daughter of Edward Walter and Mary Emma Coulthard.  Her sister Frances married (1858) CMY's only brother Julian Bargus Yonge.  She moved into Elderfield with CMY in about 1872.  Her illness began 8 years before 1871.


 [Bombay Baptisms N/3/24/118; 'she would have been 48 on the 24th']   





CMY described her movingly in ‘Our Tender Ones’ <i>Mothers in Council</i> 9 (January 1899) 20-27, 26:





‘Let me draw the picture of a real invalid not long passed away.  She was a bright active girl of fourteen when rheumatic fever set in, followed by arthritis.  Gradually, during nearly twenty years, every power was taken from her;  first one knee was affected, then the other, then she could no longer sit at the piano, she moved on crutches, and drove in a donkey chaise;  but in time, always after severe illness and pain, these pleasures failed her, she could only be carried from one room to another or to church on a couch.  She lost her voice, and next the use of her right arm, and for several years was entirely confined to bed.’

## Letters Mentioning This Person

- [Letter 2249](../2249-to-edith-sophia-jacob-12.qmd)
- [Letter 2328](../2328-to-mary-ann-dyson-10.qmd)
- [Letter 2334](../2334-to-mary-ann-dyson-10.qmd)
- [Letter 2364](../2364-to-mary-yonge-34.qmd)
- [Letter 2367](../2367-to-mary-yonge-35.qmd)
- [Letter 2368](../2368-to-jane-mary-dampier.qmd)
- [Letter 2369](../2369-to-christabel-rose-coleridge-61.qmd)
- [Letter 2372](../2372-to-mary-yonge-36.qmd)
- [Letter 2420](../2420-to-charlotte-cordelia-yonge-4.qmd)
- [Letter 2427](../2427-to-miss-cassell.qmd)
- [Letter 2439](../2439-to-charlotte-cordelia-yonge.qmd)
- [Letter 2440](../2440-to-mary-yonge-37.qmd)
- [Letter 2446](../2446-to-mary-anne-dyson-22.qmd)
- [Letter 2458](../2458-to-christabel-rose-coleridge-74.qmd)
- [Letter 2459](../2459-to-christabel-rose-coleridge-75.qmd)
- [Letter 2461](../2461-to-christabel-rose-coleridge-76.qmd)
- [Letter 2487](../2487-to-the-hon-laura-elizabeth-palmer.qmd)
- [Letter 2510](../2510-to-christabel-rose-coleridge-80.qmd)
- [Letter 2517](../2517-to-elizabeth-wordsworth-8.qmd)
- [Letter 2527](../2527-to-florence-freeman-4.qmd)
- [Letter 2538](../2538-to-augusta-boevey-pode-3.qmd)
- [Letter 2543](../2543-to-augusta-boevey-pode-4.qmd)
- [Letter 2547](../2547-to-mary-yonge-40.qmd)
- [Letter 2550](../2550-to-mary-yonge-41.qmd)
- [Letter 2552](../2552-to-mary-yonge-42.qmd)
- [Letter 2554](../2554-to-mary-yonge-43.qmd)
- [Letter 2556](../2556-to-mary-yonge-45.qmd)
- [Letter 2559](../2559-to-mary-yonge-46.qmd)
- [Letter 2560](../2560-to-mary-yonge-47.qmd)
- [Letter 2593](../2593-to-frederick-james-furnivall.qmd)
- [Letter 2595](../2595-to-augusta-boevey-pode.qmd)
- [Letter 2606](../2606-to-ellen-julia-johns-14.qmd)
- [Letter 2607](../2607-to-elizabeth-wordsworth-9.qmd)
- [Letter 2608](../2608-to-elizabeth-wordsworth-10.qmd)
- [Letter 2612](../2612-to-elizabeth-wordsworth-11.qmd)
- [Letter 2619](../2619-to-christabel-rose-coleridge-92.qmd)
- [Letter 2644](../2644-to-florence-wilford-8.qmd)
- [Letter 2648](../2648-to-christabel-rose-coleridge-98.qmd)
- [Letter 2729](../2729-to-florence-wilford-10.qmd)
- [Letter 2732](../2732-to-caroline-elizabeth-cooke-trench.qmd)
- [Letter 2778](../2778-to-christabel-rose-coleridge-108.qmd)
- [Letter 2783](../2783-to-christabel-rose-coleridge-110.qmd)
- [Letter 2788](../2788-to-the-hon-mrs-montgomery-moore-3.qmd)
- [Letter 2798](../2798-to-jemima-blackburn.qmd)
- [Letter 2804](../2804-to-the-reverend-william-harris-walter-bigg-wither.qmd)
- [Letter 2805](../2805-to-mary-yonge-51.qmd)
- [Letter 2806](../2806-to-frances-sophia-coleridge-patteson-7.qmd)
- [Letter 2809](../2809-to-the-hon-mrs-joyce.qmd)
- [Letter 2840](../2840-to-emily-dampier.qmd)
- [Letter 2844](../2844-to-isabella-margaretta-elizabeth-heathcote.qmd)
- [Letter 2851](../2851-to-edith-sophia-jacob.qmd)
- [Letter 2857](../2857-to-the-reverend-john-frewen-moor-20.qmd)
- [Letter 2866](../2866-to-anna-georgina-macaulay.qmd)
- [Letter 2921](../2921-to-frances-mary-peard-10.qmd)
- [Letter 2923](../2923-to-elizabeth-barnett-23.qmd)
- [Letter 2925](../2925-to-mary-yonge.qmd)
- [Letter 3119](../3119-to-anne-yonge-37.qmd)
- [Letter 3159](../3159-to-miss-bowles.qmd)
- [Letter 3197](../3197-to-elizabeth-barnett-14.qmd)
- [Letter 3204](../3204-to-helen-emma-yonge.qmd)
- [Letter 3209](../3209-to-arthur-donald-innes-17.qmd)
- [Letter 3224](../3224-to-mary-yonge-13.qmd)
- [Letter 3305](../3305-to-augusta-boevey-pode-2.qmd)
- [Letter 3331](../3331-to-the-reverend-william-harris-bigg-wither-2.qmd)
- [Letter 3340](../3340-to-mary-yonge-17.qmd)
- [Letter 3342](../3342-to-mary-yonge-18.qmd)
- [Letter 3346](../3346-to-mary-yonge-19.qmd)
- [Letter 3348](../3348-to-mary-yonge-20.qmd)
- [Letter 3349](../3349-to-marianne-bigg-wither-5.qmd)
- [Letter 3350](../3350-to-mary-yonge-21.qmd)
- [Letter 3351](../3351-to-mary-yonge-22.qmd)
- [Letter 3361](../3361-to-mary-elizabeth-christie.qmd)
- [Letter 3367](../3367-to-anna-meredith-barrett-lennard.qmd)
- [Letter 3512](../3512-to-catharine-elgie-5.qmd)
- [Letter 3546](../3546-to-isabella-margaretta-elizabeth-heathcote-2.qmd)
- [Letter 3548](../3548-to-frances-sophia-coleridge-patteson.qmd)
- [Letter 3573](../3573-to-caroline-jeannette-beck.qmd)
- [Letter 3588](../3588-to-frances-sophia-coleridge-patteson-2.qmd)
- [Letter 3604](../3604-to-cordelia-elizabeth-yonge.qmd)
- [Letter 18775](../18775-to-frances-maria-wilbraham.qmd)
- [Letter 19419](../19419-to-florence-wilford.qmd)
- [Letter 19816](../19816-to-miss-manning.qmd)
- [Letter 19875](../19875-to-anna-maria-keary.qmd)

