---
title: "Sir William Heathcote 5th Bt."
person_id: 669
---

## Biographical Information

(17 May 1801-17 Aug 1881)

landowner

He married, first (8 Nov 1825) the Hon. Caroline Frances Perceval (d. 3 Mar 1835) and secondly (18 May 1841) Selina Shirley (d. 1901).

## Letters Mentioning This Person

- [Letter 1817](../1817-to-anne-sturges-bourne-6.qmd)
- [Letter 1944](../1944-to-alexander-macmillan-15.qmd)
- [Letter 1950](../1950-sir-william-heathcote-to-charlotte-mary-yonge.qmd)
- [Letter 1956](../1956-to-messrs-macmillan-3.qmd)
- [Letter 2112](../2112-frances-mary-yonge-to-mary-anne-moberly.qmd)
- [Letter 2117](../2117-to-anne-yonge-45.qmd)
- [Letter 2275](../2275-to-mary-ann-dyson-7.qmd)
- [Letter 2280](../2280-to-caroline-elizabeth-cooke-trench-4.qmd)
- [Letter 2304](../2304-to-sir-william-heathcote-bt-2.qmd)
- [Letter 2372](../2372-to-mary-yonge-36.qmd)
- [Letter 2385](../2385-to-sir-william-heathcote-bt-3.qmd)
- [Letter 2426](../2426-to-edward-augustus-freeman-3.qmd)
- [Letter 2435](../2435-to-sir-william-heathcote-bt-4.qmd)
- [Letter 2436](../2436-the-rev-james-edward-austen-leigh-to-sir-william-heathcote.qmd)
- [Letter 2437](../2437-to-sir-william-heathcote-bt-5.qmd)
- [Letter 2442](../2442-to-sir-william-heathcote-bt-6.qmd)
- [Letter 2443](../2443-to-sir-william-heathcote-bt-7.qmd)
- [Letter 2444](../2444-to-sir-william-heathcote-bt-8.qmd)
- [Letter 2554](../2554-to-mary-yonge-43.qmd)
- [Letter 2559](../2559-to-mary-yonge-46.qmd)
- [Letter 2560](../2560-to-mary-yonge-47.qmd)
- [Letter 2616](../2616-to-christabel-rose-coleridge-90.qmd)
- [Letter 2731](../2731-to-helena-mary-heathcote.qmd)
- [Letter 2732](../2732-to-caroline-elizabeth-cooke-trench.qmd)
- [Letter 2734](../2734-to-elizabeth-wordsworth-12.qmd)
- [Letter 2868](../2868-to-edward-augustus-freeman-13.qmd)
- [Letter 2935](../2935-william-crawley-yonge-to-the-rev-john-yonge-including-charlotte-mary-yonge-to-anne-yonge.qmd)
- [Letter 2936](../2936-to-anne-yonge-4.qmd)
- [Letter 2945](../2945-to-anne-yonge-12.qmd)
- [Letter 2948](../2948-to-anne-yonge-15.qmd)
- [Letter 2956](../2956-to-anne-yonge-23.qmd)
- [Letter 3007](../3007-to-mary-anne-dyson-14.qmd)
- [Letter 3020](../3020-to-elizabeth-barnett-4.qmd)
- [Letter 3039](../3039-anne-yonge-to-mary-yonge-3.qmd)
- [Letter 3053](../3053-to-elizabeth-barnett-6.qmd)
- [Letter 3055](../3055-to-anne-yonge-31.qmd)
- [Letter 3088](../3088-to-ann-maria-carter-smith-5.qmd)
- [Letter 3092](../3092-to-ann-maria-carter-smith-8.qmd)
- [Letter 3097](../3097-sir-william-heathcote-to-caroline-elizabeth-heathcote.qmd)
- [Letter 3147](../3147-to-elizabeth-barnett-13.qmd)
- [Letter 3362](../3362-to-frederick-orridge-macmillan-12.qmd)
- [Letter 3375](../3375-to-frederick-orridge-macmillan-16.qmd)
- [Letter 3376](../3376-to-frederick-orridge-macmillan-17.qmd)
- [Letter 3377](../3377-to-frederick-orridge-macmillan.qmd)
- [Letter 3413](../3413-to-helena-heathcote-2.qmd)
- [Letter 3574](../3574-to-an-unknown-person-6.qmd)
- [Letter 3612](../3612-to-catherine-england.qmd)
- [Letter 7710](../7710-to-sir-john-taylor-coleridge.qmd)
- [Letter 7759](../7759-to-sir-william-heathcote-bt.qmd)

