---
title: "Laura Belinda Charlotte (Jewry) Valentine"
person_id: 1437
---

## Biographical Information

(1816?-1899)

contributor to <i>MP</i>, publishers’ editor

She was born at Portsea, Hants., and gave different ages in several census returns. A governess in 1841;  she married (1853) the Rev. Richard John Scobell Valentine (d.1853/4), curate in charge of St. Mary, Portsea.  The birth to her of a posthumous stillborn son was reported in the <i>Morning Chronicle</i> (1 July 1854).  By 1861 she was living with her mother (widow of a lieutenant RN) at the Naval Asylum, Battersea, with her unmarried sister Mary Jewry. She worked for Warne as a children’s books editor.

## Letters Mentioning This Person

- [Letter 2218](../2218-to-laura-valentine-2.qmd)
- [Letter 2256](../2256-to-laura-valentine.qmd)
- [Letter 2267](../2267-to-christabel-rose-coleridge-17.qmd)
- [Letter 2282](../2282-to-alexander-macmillan-102.qmd)
- [Letter 2286](../2286-to-alexander-macmillan-104.qmd)
- [Letter 2409](../2409-to-laura-valentine-3.qmd)

