---
title: "Field Marshal Sir John Colborne"
person_id: 313
---

## Biographical Information

1st Lord Seaton

(16 Feb 1778-17 April 1863)

stepbrother of FMY

He married (21 June 1814) Elizabeth Yonge (7 March 1790-28 Nov 1872).  He was created a peer in 1839, and  made Field Marshal in 1860.  WCY was in his regiment, was first cousin to his wife, and married his stepsister.

## Letters Mentioning This Person

- [Letter 1789](../1789-to-frances-dorothy-moor.qmd)
- [Letter 2270](../2270-to-mary-anne-moberly-3.qmd)
- [Letter 2952](../2952-to-anne-yonge-19.qmd)
- [Letter 2957](../2957-anne-yonge-to-mary-yonge-2.qmd)
- [Letter 3013](../3013-to-alice-arbuthnot-moberly-5.qmd)
- [Letter 3036](../3036-anne-yonge-to-the-rev-john-yonge.qmd)
- [Letter 3107](../3107-anne-yonge-to-the-rev-john-yonge-2.qmd)
- [Letter 3108](../3108-to-elizabeth-barnett-7.qmd)
- [Letter 3109](../3109-to-frances-mary-yonge-2.qmd)
- [Letter 3110](../3110-anne-yonge-to-mary-yonge.qmd)
- [Letter 3148](../3148-to-dorothea-beale-2.qmd)
- [Letter 3317](../3317-to-mary-elizabeth-wormeley-latimer.qmd)
- [Letter 3328](../3328-to-clifford-wyndham-holgate.qmd)
- [Letter 3417](../3417-to-mrs-swinton-2.qmd)
- [Letter 3428](../3428-to-miss-e-m-walker-6.qmd)
- [Letter 7727](../7727-to-sir-john-taylor-coleridge.qmd)
- [Letter 7783](../7783-to-sir-john-taylor-coleridge.qmd)

