---
title: "Charlotte (Clarke) Keble"
person_id: 795
---

## Biographical Information

(1806/7-11 May 1866)

wife of the Rev. John Keble

She married (10 Oct 1835) the Rev. John Keble.

## Letters Mentioning This Person

- [Letter 1801](../1801-from-the-reverend-john-keble-to-frances-mary-yonge-and-charlotte-mary-yonge.qmd)
- [Letter 1809](../1809-to-alice-arbuthnot-moberly-10.qmd)
- [Letter 1836](../1836-to-frances-sophia-coleridge-patteson-4.qmd)
- [Letter 2066](../2066-to-mary-ann-dyson-3.qmd)
- [Letter 2090](../2090-the-reverend-john-keble-to-charlotte-mary-yonge-5.qmd)
- [Letter 2110](../2110-to-anne-yonge-43.qmd)
- [Letter 2111](../2111-to-anne-yonge-44.qmd)
- [Letter 2112](../2112-frances-mary-yonge-to-mary-anne-moberly.qmd)
- [Letter 2114](../2114-to-elizabeth-missing-sewell-14.qmd)
- [Letter 2115](../2115-to-jemima-charlotte-mozley.qmd)
- [Letter 2134](../2134-the-right-reverend-john-coleridge-patteson-to-charlotte-mary-yonge-2.qmd)
- [Letter 2138](../2138-the-right-reverend-john-coleridge-patteson-to-charlotte-mary-yonge-3.qmd)
- [Letter 2224](../2224-the-right-reverend-john-coleridge-patteson-to-charlotte-mary-yonge-6.qmd)
- [Letter 2230](../2230-the-right-reverend-john-coleridge-patteson-to-charlotte-mary-yonge-7.qmd)
- [Letter 2270](../2270-to-mary-anne-moberly-3.qmd)
- [Letter 2330](../2330-to-mary-ann-dyson-2.qmd)
- [Letter 2348](../2348-to-edith-sophia-jacob-18.qmd)
- [Letter 2391](../2391-to-susanna-warren-7.qmd)
- [Letter 2587](../2587-to-christabel-rose-coleridge-88.qmd)
- [Letter 2685](../2685-to-mary-rogers.qmd)
- [Letter 2936](../2936-to-anne-yonge-4.qmd)
- [Letter 2938](../2938-to-anne-yonge-6.qmd)
- [Letter 2939](../2939-to-anne-yonge-7.qmd)
- [Letter 2944](../2944-to-alethea-yonge.qmd)
- [Letter 2945](../2945-to-anne-yonge-12.qmd)
- [Letter 2956](../2956-to-anne-yonge-23.qmd)
- [Letter 2957](../2957-anne-yonge-to-mary-yonge-2.qmd)
- [Letter 2960](../2960-to-mary-anne-dyson-3.qmd)
- [Letter 2997](../2997-to-elizabeth-roberts-17.qmd)
- [Letter 3007](../3007-to-mary-anne-dyson-14.qmd)
- [Letter 3029](../3029-to-mary-anne-dyson-17.qmd)
- [Letter 3033](../3033-frances-mary-yonge-to-the-reverend-john-yonge.qmd)
- [Letter 3035](../3035-to-elizabeth-roberts-33.qmd)
- [Letter 3048](../3048-to-mary-anne-dyson-19.qmd)
- [Letter 3060](../3060-to-anne-yonge-32.qmd)
- [Letter 3061](../3061-to-anne-yonge-33.qmd)
- [Letter 3062](../3062-to-anne-yonge-34.qmd)
- [Letter 3063](../3063-to-anne-yonge-35.qmd)
- [Letter 3065](../3065-from-the-reverend-john-keble-to-charlotte-mary-yonge-2.qmd)
- [Letter 3095](../3095-frances-mary-yonge-to-anne-sturges-bourne.qmd)
- [Letter 3096](../3096-to-the-reverend-edward-coleridge-2.qmd)
- [Letter 3100](../3100-to-miss-moorsom.qmd)
- [Letter 3104](../3104-to-emma-butler.qmd)
- [Letter 3124](../3124-to-caroline-elizabeth-cooke-trench-2.qmd)
- [Letter 3140](../3140-to-caroline-elizabeth-cooke-trench-3.qmd)
- [Letter 3207](../3207-to-the-reverend-vere-awdry.qmd)
- [Letter 3265](../3265-to-ethel-romanes-2.qmd)
- [Letter 3333](../3333-to-mary-elizabeth-christie-2.qmd)

