---
title: "Mary Eliza Bramston"
person_id: 198
---

## Biographical Information

(1841-2 February 1912)

contributor to <i>MP</i> (1870-96), novelist

Daughter of the Rev. John Bramston by his first marriage and half-sister of Anna Bramston, she was a  prolific writer of fiction and non-fiction, generally for young women: she collaborated with CMY and others on <i>Astray</i>. She seems to have acted for some years as governess to the daughters of Archbishop Benson.  Several of her works, such as <i>Everingham Girls</i> (1886)and <i>Apples of Sodom</i> (1889), portray intense same-sex relationships. She died at Kinshot Street Cross, Winchester, and left £8253. [<i>Journal of Clarissa Trant</i>, NUC, wills index]

## Letters Mentioning This Person

- [Letter 2423](../2423-to-mary-eliza-bramston.qmd)
- [Letter 2469](../2469-to-anne-mercier-6.qmd)
- [Letter 2517](../2517-to-elizabeth-wordsworth-8.qmd)
- [Letter 2532](../2532-to-christabel-rose-coleridge-81.qmd)
- [Letter 2533](../2533-to-christabel-rose-coleridge-82.qmd)
- [Letter 2563](../2563-to-anna-rachel-bramston-4.qmd)
- [Letter 2592](../2592-to-miss-cleveland-4.qmd)
- [Letter 2644](../2644-to-florence-wilford-8.qmd)
- [Letter 2672](../2672-to-mary-eliza-bramston-2.qmd)
- [Letter 2765](../2765-to-george-lillie-craik-56.qmd)
- [Letter 2771](../2771-to-christabel-rose-coleridge-107.qmd)
- [Letter 2778](../2778-to-christabel-rose-coleridge-108.qmd)
- [Letter 2825](../2825-to-florence-wilford-11.qmd)
- [Letter 2873](../2873-to-arthur-donald-innes-19.qmd)
- [Letter 2921](../2921-to-frances-mary-peard-10.qmd)
- [Letter 2923](../2923-to-elizabeth-barnett-23.qmd)
- [Letter 3388](../3388-to-christabel-rose-coleridge-27.qmd)
- [Letter 3423](../3423-to-christabel-rose-coleridge-33.qmd)
- [Letter 3453](../3453-to-christabel-rose-coleridge-42.qmd)
- [Letter 3458](../3458-to-christabel-rose-coleridge-43.qmd)
- [Letter 3469](../3469-to-christabel-rose-coleridge-52.qmd)
- [Letter 9418](../9418-to-the-editor-of-the-i-girls-friendly-society-associates-journal-i.qmd)

