---
title: "Ann Maria Carter Smith"
person_id: 263
---

## Biographical Information

(Kentish Town 1835-15 Oct 1909 Chislehurst)

contributor to <i>MP</i> (1856-90), novelist

Daughter of the Reverend Richard Carter Smith (1802-1864) and Mary Williamson. The letters indicate that at some point Ann Carter Smith had lived in Norway and that she had a brother in the navy. [wills index, left £40,997, probate to Cecil Newton Goodhall; parish register]

## Letters Mentioning This Person

- [Letter 1778](../1778-to-ann-maria-carter-smith-27.qmd)
- [Letter 1779](../1779-to-ann-maria-carter-smith-28.qmd)
- [Letter 1780](../1780-to-ann-maria-carter-smith-29.qmd)
- [Letter 1782](../1782-to-ann-maria-carter-smith-30.qmd)
- [Letter 1784](../1784-to-ann-maria-carter-smith-31.qmd)
- [Letter 1785](../1785-to-ann-maria-carter-smith-32.qmd)
- [Letter 1787](../1787-to-ann-maria-carter-smith-33.qmd)
- [Letter 1788](../1788-to-ann-maria-carter-smith-34.qmd)
- [Letter 1798](../1798-to-ann-maria-carter-smith-35.qmd)
- [Letter 1800](../1800-to-ann-maria-carter-smith-36.qmd)
- [Letter 1802](../1802-to-ann-maria-carter-smith-37.qmd)
- [Letter 1810](../1810-to-ann-maria-carter-smith-38.qmd)
- [Letter 1811](../1811-to-ann-maria-carter-smith-39.qmd)
- [Letter 1820](../1820-to-ann-maria-carter-smith-40.qmd)
- [Letter 1821](../1821-to-ann-maria-carter-smith-41.qmd)
- [Letter 1822](../1822-to-ann-maria-carter-smith-42.qmd)
- [Letter 1823](../1823-to-ann-maria-carter-smith-43.qmd)
- [Letter 1824](../1824-to-ann-maria-carter-smith-44.qmd)
- [Letter 1826](../1826-to-ann-maria-carter-smith-45.qmd)
- [Letter 1834](../1834-to-ann-maria-carter-smith-46.qmd)
- [Letter 1837](../1837-to-ann-maria-carter-smith-47.qmd)
- [Letter 1841](../1841-to-ann-maria-carter-smith-48.qmd)
- [Letter 1843](../1843-to-ann-maria-carter-smith-49.qmd)
- [Letter 1845](../1845-to-ann-maria-carter-smith-50.qmd)
- [Letter 1854](../1854-to-ann-maria-carter-smith-51.qmd)
- [Letter 1859](../1859-to-ann-maria-carter-smith-52.qmd)
- [Letter 1865](../1865-to-ann-maria-carter-smith-53.qmd)
- [Letter 1869](../1869-to-ann-maria-carter-smith-54.qmd)
- [Letter 1878](../1878-to-ann-maria-carter-smith-55.qmd)
- [Letter 1879](../1879-to-ann-maria-carter-smith-56.qmd)
- [Letter 1881](../1881-to-ann-maria-carter-smith-57.qmd)
- [Letter 1883](../1883-to-ann-maria-carter-smith-58.qmd)
- [Letter 1884](../1884-to-ann-maria-carter-smith-59.qmd)
- [Letter 1887](../1887-to-ann-maria-carter-smith-60.qmd)
- [Letter 1892](../1892-to-ann-maria-carter-smith-61.qmd)
- [Letter 1893](../1893-to-ann-maria-carter-smith-62.qmd)
- [Letter 1903](../1903-to-ann-maria-carter-smith-63.qmd)
- [Letter 1911](../1911-to-ann-maria-carter-smith-64.qmd)
- [Letter 1937](../1937-to-ann-maria-carter-smith-66.qmd)
- [Letter 1945](../1945-to-ann-maria-carter-smith-67.qmd)
- [Letter 1946](../1946-to-ann-maria-carter-smith-68.qmd)
- [Letter 1991](../1991-to-ann-maria-carter-smith-70.qmd)
- [Letter 2000](../2000-to-ann-maria-carter-smith-71.qmd)
- [Letter 2099](../2099-to-ann-maria-carter-smith-72.qmd)
- [Letter 2122](../2122-to-ann-maria-carter-smith-73.qmd)
- [Letter 2131](../2131-to-ann-maria-carter-smith-74.qmd)
- [Letter 2167](../2167-to-ann-maria-carter-smith-75.qmd)
- [Letter 2177](../2177-to-ann-maria-carter-smith-76.qmd)
- [Letter 2231](../2231-to-ann-maria-carter-smith-77.qmd)
- [Letter 2250](../2250-to-edith-sophia-jacob-13.qmd)
- [Letter 2262](../2262-to-ann-maria-carter-smith-78.qmd)
- [Letter 2281](../2281-to-ann-maria-carter-smith-79.qmd)
- [Letter 2301](../2301-to-ann-maria-carter-smith.qmd)
- [Letter 2602](../2602-to-ann-maria-carter-smith-80.qmd)
- [Letter 2605](../2605-to-ann-maria-carter-smith-81.qmd)
- [Letter 2636](../2636-to-george-lillie-craik-45.qmd)
- [Letter 2720](../2720-to-ann-maria-carter-smith-82.qmd)
- [Letter 2725](../2725-to-ann-maria-carter-smith-83.qmd)
- [Letter 2726](../2726-to-ann-maria-carter-smith-84.qmd)
- [Letter 2727](../2727-to-christabel-rose-coleridge-103.qmd)
- [Letter 2728](../2728-to-ann-maria-carter-smith-85.qmd)
- [Letter 2730](../2730-to-ann-maria-carter-smith-86.qmd)
- [Letter 2742](../2742-to-ann-maria-carter-smith-87.qmd)
- [Letter 2758](../2758-to-ann-maria-carter-smith-88.qmd)
- [Letter 2767](../2767-to-ann-maria-carter-smith-89.qmd)
- [Letter 2789](../2789-to-ann-maria-carter-smith-91.qmd)
- [Letter 2861](../2861-to-ann-maria-carter-smith-92.qmd)
- [Letter 3074](../3074-to-ann-maria-carter-smith-3.qmd)
- [Letter 3081](../3081-to-ann-maria-carter-smith-4.qmd)
- [Letter 3088](../3088-to-ann-maria-carter-smith-5.qmd)
- [Letter 3089](../3089-to-ann-maria-carter-smith-6.qmd)
- [Letter 3090](../3090-to-ann-maria-carter-smith-7.qmd)
- [Letter 3092](../3092-to-ann-maria-carter-smith-8.qmd)
- [Letter 3094](../3094-to-ann-maria-carter-smith-9.qmd)
- [Letter 3099](../3099-to-ann-maria-carter-smith-10.qmd)
- [Letter 3105](../3105-to-ann-maria-carter-smith-11.qmd)
- [Letter 3106](../3106-to-ann-maria-carter-smith-12.qmd)
- [Letter 3113](../3113-to-ann-maria-carter-smith-13.qmd)
- [Letter 3114](../3114-to-ann-maria-carter-smith-14.qmd)
- [Letter 3126](../3126-to-ann-maria-carter-smith-15.qmd)
- [Letter 3127](../3127-to-ann-maria-carter-smith-16.qmd)
- [Letter 3128](../3128-to-ann-maria-carter-smith-17.qmd)
- [Letter 3129](../3129-to-ann-maria-carter-smith-18.qmd)
- [Letter 3130](../3130-to-ann-maria-carter-smith-19.qmd)
- [Letter 3131](../3131-to-ann-maria-carter-smith-20.qmd)
- [Letter 3132](../3132-to-ann-maria-carter-smith-21.qmd)
- [Letter 3133](../3133-to-ann-maria-carter-smith-22.qmd)
- [Letter 3136](../3136-to-ann-maria-carter-smith-23.qmd)
- [Letter 3138](../3138-to-ann-maria-carter-smith-24.qmd)
- [Letter 3142](../3142-to-ann-maria-carter-smith-25.qmd)
- [Letter 3143](../3143-to-ann-maria-carter-smith-26.qmd)
- [Letter 3601](../3601-to-ann-maria-carter-smith-2.qmd)

