---
title: "The Rev. John Frederick Watkinson Bullock"
person_id: 221
---

## Biographical Information

(1840-1918)

He succeeded his father and grandfather as Rector of Radwinter 1865-1916.  In 1902 he published the first three volumes of a projected six volume work called <i>Daily Lections for every Morning and Evening throughout the Year</i> (London: Rivington 1902).  Volume V of this work, described in his preface, was to have consisted of 'Lections on Anglican Worthies, arranged as additional Readings for Sunday'.  These 'Biographies of Eminent Anglicans' exist in MS and are catalogued under that name among the Bullock papers in the Bodleian Library, Oxford, but were never published, since no more of the <i>Daily Lections</i> ever appeared.  The biographies were contributed by various authors, including CMY, Elizabeth Rundle Charles and Florence Wilford.  [ Burke LG 1862, Venn, <i>Alumni Cantabrigienses</i>.  N.B. Venn's statement that there is an obituary in the <i>Guardian</i> 11 April 1918 seems to be inaccurate.]

## Letters Mentioning This Person

- [Letter 3241](../3241-to-the-reverend-john-frederick-watkinson-bullock-12.qmd)
- [Letter 3242](../3242-to-the-reverend-john-frederick-watkinson-bullock-7.qmd)
- [Letter 3243](../3243-to-the-reverend-john-frederick-watkinson-bullock-8.qmd)
- [Letter 3245](../3245-to-the-reverend-john-frederick-watkinson-bullock-2.qmd)
- [Letter 3246](../3246-to-the-reverend-john-frederick-watkinson-bullock-9.qmd)
- [Letter 3248](../3248-to-the-reverend-john-frederick-watkinson-bullock-10.qmd)
- [Letter 3249](../3249-to-the-reverend-john-frederick-watkinson-bullock-15.qmd)
- [Letter 3251](../3251-to-the-reverend-john-frederick-watkinson-bullock-13.qmd)
- [Letter 3252](../3252-to-the-reverend-john-frederick-watkinson-bullock-17.qmd)
- [Letter 3253](../3253-to-the-reverend-john-frederick-watkinson-bullock-19.qmd)
- [Letter 3254](../3254-to-the-reverend-john-frederick-watkinson-bullock-18.qmd)
- [Letter 3255](../3255-to-the-reverend-john-frederick-watkinson-bullock-22.qmd)
- [Letter 3261](../3261-to-the-reverend-john-frederick-watkinson-bullock-16.qmd)
- [Letter 3264](../3264-to-the-reverend-john-frederick-watkinson-bullock-25.qmd)
- [Letter 3267](../3267-to-the-reverend-john-frederick-watkinson-bullock-24.qmd)
- [Letter 3268](../3268-to-the-reverend-john-frederick-watkinson-bullock-23.qmd)
- [Letter 3270](../3270-to-the-reverend-john-frederick-watkinson-bullock-20.qmd)
- [Letter 3274](../3274-to-the-reverend-john-frederick-watkinson-bullock-21.qmd)
- [Letter 3275](../3275-to-the-reverend-john-frederick-watkinson-bullock-14.qmd)
- [Letter 3276](../3276-to-the-reverend-john-frederick-watkinson-bullock-6.qmd)
- [Letter 3280](../3280-to-the-reverend-john-frederick-watkinson-bullock-5.qmd)
- [Letter 3286](../3286-to-the-reverend-john-frederick-watkinson-bullock-4.qmd)
- [Letter 3392](../3392-to-the-reverend-john-frederick-watkinson-bullock-11.qmd)
- [Letter 3597](../3597-to-the-reverend-john-frederick-watkinson-bullock-3.qmd)

