---
title: "The Rev. Duke Yonge"
person_id: 1599
---

## Biographical Information

(21 June 1823-7 Oct 1881)

cousin of CMY

The fourth and only surviving of the five sons of the Rev. John Yonge of Puslinch, and Alethea Henrietta (Bargus) Yonge, he inherited Puslinch in 1877 (John, James, John Bargus and Edmund Charles having predeceased him).  He was curate of Newton Ferrars in 1849, and subsequently Rector of Newton Ferrars like his father.  He married (26 Aug 1862) Charlotte Cordelia Pode (1839/40-7 Sept 1929), who was his second cousin (she was CMY's first cousin).  He shared two of her eight great-grandparents, whereas he shared four of CMY's eight great-grandparents.  According to a letter of his youngest daughter Alethea’s, he had wished to marry CMY.

## Letters Mentioning This Person

- [Letter 1864](../1864-to-charlotte-cordelia-pode.qmd)
- [Letter 1899](../1899-to-anne-yonge-42.qmd)
- [Letter 2264](../2264-to-the-reverend-duke-yonge-2.qmd)
- [Letter 2270](../2270-to-mary-anne-moberly-3.qmd)
- [Letter 2275](../2275-to-mary-ann-dyson-7.qmd)
- [Letter 2290](../2290-to-sophia-jane-harrison.qmd)
- [Letter 2338](../2338-to-the-reverend-duke-yonge.qmd)
- [Letter 2339](../2339-to-mary-yonge-7.qmd)
- [Letter 2340](../2340-to-charlotte-cordelia-yonge-2.qmd)
- [Letter 2342](../2342-to-florence-wilford-5.qmd)
- [Letter 2352](../2352-to-mary-yonge-9.qmd)
- [Letter 2420](../2420-to-charlotte-cordelia-yonge-4.qmd)
- [Letter 2538](../2538-to-augusta-boevey-pode-3.qmd)
- [Letter 2561](../2561-to-mary-yonge-48.qmd)
- [Letter 2643](../2643-to-christabel-rose-coleridge-96.qmd)
- [Letter 2881](../2881-to-jean-ingelow.qmd)
- [Letter 2932](../2932-to-anne-yonge.qmd)
- [Letter 2938](../2938-to-anne-yonge-6.qmd)
- [Letter 2957](../2957-anne-yonge-to-mary-yonge-2.qmd)
- [Letter 2972](../2972-to-mary-anne-dyson-12.qmd)
- [Letter 2977](../2977-to-anne-yonge-24.qmd)
- [Letter 2979](../2979-to-anne-yonge-25.qmd)
- [Letter 2987](../2987-to-anne-yonge-26.qmd)
- [Letter 3032](../3032-frances-mary-yonge-to-the-reverend-john-yonge-2.qmd)
- [Letter 3033](../3033-frances-mary-yonge-to-the-reverend-john-yonge.qmd)
- [Letter 3034](../3034-frances-mary-yonge-to-mary-yonge.qmd)
- [Letter 3036](../3036-anne-yonge-to-the-rev-john-yonge.qmd)
- [Letter 3039](../3039-anne-yonge-to-mary-yonge-3.qmd)
- [Letter 3060](../3060-to-anne-yonge-32.qmd)
- [Letter 3107](../3107-anne-yonge-to-the-rev-john-yonge-2.qmd)
- [Letter 3110](../3110-anne-yonge-to-mary-yonge.qmd)
- [Letter 3119](../3119-to-anne-yonge-37.qmd)

