---
title: "Charlotte Anne Elizabeth Moberly"
person_id: 1024
---

## Biographical Information

(16 Sept 1846-7 May 1937)

seventh daughter of the Rt. Rev. George Moberly

Always known as Annie, she became first principal of St. Hugh’s College, Oxford. She left £3155, probate to Elspeth Milford widow and Dora Caroline Martin spinsters [LG 1975 Moberly;  will; ODNB]

## Letters Mentioning This Person

- [Letter 2719](../2719-to-catharine-elgie-6.qmd)
- [Letter 2894](../2894-to-charlotte-anne-elizabeth-moberly-3.qmd)
- [Letter 2955](../2955-to-anne-yonge-22.qmd)
- [Letter 2956](../2956-to-anne-yonge-23.qmd)
- [Letter 2982](../2982-to-alice-arbuthnot-moberly-4.qmd)
- [Letter 3047](../3047-frances-mary-yonge-to-alice-arbuthnot-moberly.qmd)
- [Letter 3067](../3067-to-alice-arbuthnot-moberly-6.qmd)
- [Letter 3259](../3259-to-charlotte-anne-elizabeth-moberly.qmd)
- [Letter 3260](../3260-to-anne-elizabeth-mary-anderson-morshead-5.qmd)
- [Letter 3265](../3265-to-ethel-romanes-2.qmd)
- [Letter 3357](../3357-to-mary-yonge-24.qmd)
- [Letter 3412](../3412-to-christabel-rose-coleridge-28.qmd)
- [Letter 3414](../3414-to-elizabeth-harcourt-mitchell.qmd)
- [Letter 3418](../3418-to-christabel-rose-coleridge-24.qmd)
- [Letter 3420](../3420-to-christabel-rose-coleridge-26.qmd)
- [Letter 3423](../3423-to-christabel-rose-coleridge-33.qmd)
- [Letter 3425](../3425-to-christabel-rose-coleridge-34.qmd)
- [Letter 3427](../3427-to-christabel-rose-coleridge-35.qmd)
- [Letter 3468](../3468-to-christabel-rose-coleridge-51.qmd)
- [Letter 3523](../3523-to-anna-rachel-bramston-3.qmd)
- [Letter 3592](../3592-to-charlotte-anne-elizabeth-moberly-2.qmd)

