---
title: "Mary Elizabeth (Wormeley) Latimer"
person_id: 846
---

## Biographical Information

(1822-1904)

American historian, contributor to <i>MP</i> (1879-93)

She lived in Baltimore, Maryland, and published two novels as Elizabeth Wormeley: <i>Amabel: A Family History</i> (1853) and <i>Our Cousin Veronica, or, Scenes and Adventures Over the Blue Ridge</i> (1855). In the 1880s she began writing again, publishing three novels under the name Elizabeth Wormeley Latimer:  <i>Salvage</i> (1880), <i>My Wife and My Wife's Sister</i>, 1881, and <i>Princess Amélie: A Fragment of Autobiography</i> (1883). In 1888 she published three translations from the French: <i>History of the People of Israel</i>, by Ernest Renan, and <i>For Fifteen Years</i> and <i>Steel Hammer</i>, both  by Louis Ulbach and in 1890 George Sand’s <i>Nanon</i>. In the 1890s and early 1900s she published a series of books on the history of various European nations, and on the colonisation of Africa, three more translations and a final novel,  <i>Prince Incognito</i> (1902).

## Letters Mentioning This Person

- [Letter 2832](../2832-to-mary-elizabeth-wormeley-latimer-3.qmd)
- [Letter 2917](../2917-to-mary-elizabeth-wormeleylatimer.qmd)
- [Letter 3317](../3317-to-mary-elizabeth-wormeley-latimer.qmd)
- [Letter 3321](../3321-to-mary-elizabeth-wormeley-latimer-2.qmd)
- [Letter 18751](../18751-to-susan-dabney-smedes.qmd)

