---
title: "The Rev.Canon William Parsons Warburton"
person_id: 1466
---

## Biographical Information

(1824/5-1913)

school inspector

He was educated at Balliol College, Oxford, and was a Fellow of All Souls 1849-53.  He served as HM Inspector of Schools 1851-81, and of training schools 1881-5.  He was an honorary Canon of Winchester 1878-81, and was made a Canon in 1885.  He had three daughters Mary A. (b.1859/60), Katharine (b. 1861/2), and Charlotte (b. 1864/5) [<i>Rugby School Register, Alumni Oxonienses</i>]

## Letters Mentioning This Person

- [Letter 2025](../2025-to-the-reverend-w-p-warburton.qmd)
- [Letter 2528](../2528-to-isabel-mary-warburton-4.qmd)
- [Letter 2691](../2691-to-the-reverend-william-parsons-warburton-6.qmd)
- [Letter 2692](../2692-to-the-reverend-william-parsons-warburton-7.qmd)
- [Letter 2701](../2701-to-the-reverend-william-parsons-warburton-8.qmd)
- [Letter 2713](../2713-to-the-reverend-william-parsons-warburton-9.qmd)
- [Letter 2718](../2718-to-the-reverend-william-parsons-warburton-10.qmd)
- [Letter 2896](../2896-to-arthur-donald-innes-25.qmd)
- [Letter 2903](../2903-to-the-reverend-william-parsons-warburton.qmd)
- [Letter 3192](../3192-to-the-reverend-william-parsons-warburton-3.qmd)
- [Letter 3227](../3227-to-the-reverend-william-parsons-warburton-4.qmd)
- [Letter 3365](../3365-to-the-reverend-william-parsons-warburton-5.qmd)
- [Letter 3413](../3413-to-helena-heathcote-2.qmd)
- [Letter 3610](../3610-to-the-reverend-william-parsons-warburton-2.qmd)

