---
title: "Jane (Colborne), the Hon. Mrs Montgomery Moore"
person_id: 1042
---

## Biographical Information

(1826/7-1919)

cousin of CMY

Daughter of the 1st Lord Seaton, she married (1857) General Sir Alexander George Montgomery Moore (1833-17 January 1919).  He was created KCB in 1900. They were childless and administration of both estates was granted  to Percy Frederick Higham Hodge:  he left £22,796, she £6083 [WWW; PB 1914; wills index]

## Letters Mentioning This Person

- [Letter 1897](../1897-to-anne-yonge-40.qmd)
- [Letter 2242](../2242-alexander-macmillan-to-charlotte-mary-yonge.qmd)
- [Letter 2358](../2358-to-mary-yonge-10.qmd)
- [Letter 2367](../2367-to-mary-yonge-35.qmd)
- [Letter 2489](../2489-to-elizabeth-wordsworth-6.qmd)
- [Letter 2516](../2516-to-nina-cole.qmd)
- [Letter 2547](../2547-to-mary-yonge-40.qmd)
- [Letter 2552](../2552-to-mary-yonge-42.qmd)
- [Letter 2677](../2677-to-nina-cole-2.qmd)
- [Letter 2788](../2788-to-the-hon-mrs-montgomery-moore-3.qmd)
- [Letter 2815](../2815-to-mary-yonge-52.qmd)
- [Letter 2952](../2952-to-anne-yonge-19.qmd)
- [Letter 2953](../2953-to-anne-yonge-20.qmd)
- [Letter 2983](../2983-to-elizabeth-roberts-5.qmd)
- [Letter 3039](../3039-anne-yonge-to-mary-yonge-3.qmd)
- [Letter 3107](../3107-anne-yonge-to-the-rev-john-yonge-2.qmd)
- [Letter 3108](../3108-to-elizabeth-barnett-7.qmd)
- [Letter 3110](../3110-anne-yonge-to-mary-yonge.qmd)
- [Letter 3119](../3119-to-anne-yonge-37.qmd)
- [Letter 3124](../3124-to-caroline-elizabeth-cooke-trench-2.qmd)
- [Letter 3177](../3177-to-the-hon-mrs-montgomery-moore-2.qmd)
- [Letter 3346](../3346-to-mary-yonge-19.qmd)
- [Letter 3348](../3348-to-mary-yonge-20.qmd)
- [Letter 3385](../3385-to-mary-yonge-4.qmd)
- [Letter 3451](../3451-to-mary-yonge-30.qmd)
- [Letter 3452](../3452-to-earl-nelson.qmd)
- [Letter 3455](../3455-to-mary-yonge-32.qmd)
- [Letter 3559](../3559-to-the-hon-mrs-montgomery-moore.qmd)
- [Letter 3584](../3584-to-the-hon-lady-montgomery-moore.qmd)
- [Letter 7691](../7691-to-sir-john-taylor-coleridge.qmd)

