---
title: "Elizabeth Birt Alice (Holmes, then Reed) Yonge"
person_id: 1723
---

## Biographical Information

(1799/1800-1863)

cousin-in-law of CMY

Elizabeth (Holmes) Reed married, as her third  husband, CMY's cousin Dr. John Francis Duke Yonge, son of the Rev. Duke Yonge of Antony, who was about 14 years her junior:  they had three sons: Francis Arthur Holmes Yonge, James Frederick Moore Yonge, and Stephen Duke Yonge.  He became a Roman Catholic in the late 1840s, to the consternation of his family, but according to CMY, she did not. [ Her marriage, under the name Elizabeth Bird Alice Reed, is recorded in Brussels, 1839 by the IGI; advertisement for administration of estate of J.V.C. Reed in the <i>Morning Post</i> 16 April 1864, 1]





She was the daughter of Richard Holmes, of Westcott, St. Dominick, Cornwall, and Elizabeth Nash.





She was first married (18 November 1815), aged not quite 16, in the church at Antony, Cornwall, to Cavalie Shorthouse Mercer (1789-1819), with whom she had two children, Theodosia Alice Sterling Mercer (1817-1832) and Henrietta Fyers (Mercer) Muller (1818-1839). He died in Bermuda, leaving her a widow of 19.  She remarried (1822) Captain John Reed (d. 1835) with whom she had at least six children, including Eliza Holmes Reed, who married Thomas C. Watson, and John Vaughan Carden Reed (d. 1858) Lieutenant in the Royal Marine Light Infantry.  She had perhaps known the much younger John Francis Duke Yonge since his childhood, since he had been brought up in Antony.





Information from Mr Graeme Hicks.

## Letters Mentioning This Person

- [Letter 2970](../2970-to-mary-anne-dyson-10.qmd)
- [Letter 3036](../3036-anne-yonge-to-the-rev-john-yonge.qmd)

