---
title: "Mary Ann (Crokat) Moberly"
person_id: 1019
---

## Biographical Information

(29 Sept 1812-6 Feb 1890)

wife of the Rt. Rev. George Moberly

She married (22 Dec 1834) the Rt. Rev. George Moberly.

## Letters Mentioning This Person

- [Letter 1809](../1809-to-alice-arbuthnot-moberly-10.qmd)
- [Letter 1889](../1889-to-margaret-helen-moberly-6.qmd)
- [Letter 2067](../2067-to-fanny.qmd)
- [Letter 2112](../2112-frances-mary-yonge-to-mary-anne-moberly.qmd)
- [Letter 2123](../2123-to-mary-anne-moberly-2.qmd)
- [Letter 2270](../2270-to-mary-anne-moberly-3.qmd)
- [Letter 2276](../2276-to-mary-anne-moberly-4.qmd)
- [Letter 2293](../2293-to-mary-anne-moberly-5.qmd)
- [Letter 2333](../2333-to-mary-anne-dyson-10-3.qmd)
- [Letter 2352](../2352-to-mary-yonge-9.qmd)
- [Letter 2358](../2358-to-mary-yonge-10.qmd)
- [Letter 2424](../2424-to-mary-ann-moberly-6.qmd)
- [Letter 2428](../2428-to-mary-ann-moberly-6-2.qmd)
- [Letter 2429](../2429-to-mary-anne-dyson-21.qmd)
- [Letter 2432](../2432-to-mary-ann-moberly-6-3.qmd)
- [Letter 2561](../2561-to-mary-yonge-48.qmd)
- [Letter 2792](../2792-to-mary-anne-moberly-6.qmd)
- [Letter 2796](../2796-to-mary-ann-moberly.qmd)
- [Letter 2916](../2916-to-mary-yonge-53.qmd)
- [Letter 2955](../2955-to-anne-yonge-22.qmd)
- [Letter 2956](../2956-to-anne-yonge-23.qmd)
- [Letter 2957](../2957-anne-yonge-to-mary-yonge-2.qmd)
- [Letter 2990](../2990-to-the-reverend-dr-george-moberly.qmd)
- [Letter 3041](../3041-to-jemima-blackburn-2.qmd)
- [Letter 3047](../3047-frances-mary-yonge-to-alice-arbuthnot-moberly.qmd)
- [Letter 3048](../3048-to-mary-anne-dyson-19.qmd)
- [Letter 3063](../3063-to-anne-yonge-35.qmd)
- [Letter 3067](../3067-to-alice-arbuthnot-moberly-6.qmd)
- [Letter 3075](../3075-to-margaret-helen-moberly-2.qmd)
- [Letter 3076](../3076-to-alice-arbuthnot-moberly-9.qmd)
- [Letter 3145](../3145-to-margaret-helen-moberly-3.qmd)
- [Letter 3152](../3152-to-a-member-of-the-moberly-family.qmd)

