---
title: "Captain Charles Francis Cromie"
person_id: 386
---

## Biographical Information

(1858-1907)

nephew-in-law of CMY

He entered the 37th Hampshire Regiment in 1878;  he became captain in 1884; went to Staff College 1890-1891;  and retired from the army in 1892.  He married, first (1881) Mary Grace Webb Bowen, and had at least one son born in 1882.  He petitioned for divorce on the grounds of her adultery with Captain Coddington, RN, commander of the ship <i>Duke of Wellington</i>;  this was granted 11 May 1892.  He married, secondly (1894), CMY’s niece Joanna Angela Yonge.  He served as Vice-Consul at Dar-al-Baida, Morocco, 1894-1899;  and Algeciras, 1899-1902; and was Consul at Dakar and for the Republic of Liberia, 1902-1905. The <i>Who’s Who</i> entry of his son by his first wife calls her Mrs Lennard;  she seems to have remarried John Milner Lennard in 1905.  [<i>Daily News</i> (12 May 1892); WWW C.F. Cromie and Francis Cromie (1882-1918]]

## Letters Mentioning This Person

- [Letter 3393](../3393-to-mary-yonge-3.qmd)
- [Letter 3402](../3402-to-the-marchioness-of-salisbury-2.qmd)
- [Letter 3476](../3476-to-george-lillie-craik-16.qmd)

