---
title: "Frances Sophia Coleridge Patteson"
person_id: 1151
---

## Biographical Information

(1825/6-27 April 1913)

sister of the Rt. Rev. J. C. Patteson

She was daughter of Sir John Patteson by his second marriage to Frances Coleridge, and thus related to CMY. She died at 74 Via della Croce, Rome, and probate was granted to Arthur John Coleridge Mackarness; she left £16,044 [census, will]

## Letters Mentioning This Person

- [Letter 1829](../1829-to-frances-sophia-coleridge-patteson-3.qmd)
- [Letter 1836](../1836-to-frances-sophia-coleridge-patteson-4.qmd)
- [Letter 1862](../1862-from-the-reverend-john-coleridge-patteson-to-charlotte-mary-yonge.qmd)
- [Letter 1870](../1870-to-frances-sophia-coleridge-patteson-5.qmd)
- [Letter 1944](../1944-to-alexander-macmillan-15.qmd)
- [Letter 2107](../2107-to-katharine-olive-helmore.qmd)
- [Letter 2120](../2120-from-the-right-reverend-john-coleridge-patteson-to-charlotte-mary-yonge-8.qmd)
- [Letter 2123](../2123-to-mary-anne-moberly-2.qmd)
- [Letter 2215](../2215-to-mary-ann-dyson-5.qmd)
- [Letter 2224](../2224-the-right-reverend-john-coleridge-patteson-to-charlotte-mary-yonge-6.qmd)
- [Letter 2425](../2425-to-frances-sophia-coleridge-patteson-6.qmd)
- [Letter 2449](../2449-to-christabel-rose-coleridge-72.qmd)
- [Letter 2737](../2737-to-the-marchioness-of-salisbury-3.qmd)
- [Letter 2783](../2783-to-christabel-rose-coleridge-110.qmd)
- [Letter 2792](../2792-to-mary-anne-moberly-6.qmd)
- [Letter 2806](../2806-to-frances-sophia-coleridge-patteson-7.qmd)
- [Letter 2854](../2854-to-christabel-rose-coleridge-112.qmd)
- [Letter 2867](../2867-to-elizabeth-barnett-20.qmd)
- [Letter 2952](../2952-to-anne-yonge-19.qmd)
- [Letter 3096](../3096-to-the-reverend-edward-coleridge-2.qmd)
- [Letter 3386](../3386-to-christabel-rose-coleridge-25.qmd)
- [Letter 3388](../3388-to-christabel-rose-coleridge-27.qmd)
- [Letter 3404](../3404-to-mary-yonge-5.qmd)
- [Letter 3460](../3460-to-christabel-rose-coleridge-45.qmd)
- [Letter 3548](../3548-to-frances-sophia-coleridge-patteson.qmd)
- [Letter 3588](../3588-to-frances-sophia-coleridge-patteson-2.qmd)
- [Letter 7798](../7798-to-sir-john-taylor-coleridge.qmd)
- [Letter 7831](../7831-to-the-reverend-edward-coleridge.qmd)
- [Letter 9097](../9097-to-sarah-harriet-selwyn.qmd)
- [Letter 9109](../9109-to-sarah-harriet-selwyn.qmd)
- [Letter 19162](../19162-to-frances-mary-peard.qmd)

