---
title: "Christabel Rose Coleridge"
person_id: 329
---

## Biographical Information

(1843-14 Nov 1921)

biographer of CMY

Daughter of the Rev. Derwent Coleridge (1800-1883), headmaster (1826-41) of Helston Grammar School, Principal (1841-64) of St Mark's College, Chelsea, and Rector (1864-80) of Hanwell, Middlesex, and his wife Mary Simpson Pridham;  she was granddaughter of S. T. Coleridge.  The longest-serving member of the Gosling Society, she was called Chelsea Delf to 1863 and Chelsea China thereafter;  she acted as secretary and many members seem to have been recruited by her;  she was first cousin to Cobweb and Hedgerose; Ladybird, Gurgoyle, Pena and Cricket were more distant relations.  The move to Hanwell took place in August 1864. In 1873 she was evidently helping her brother Ernest run a school in his house at Chiddingfold.    Contributor to (including Debatable Ground) and later editor of <i>MP</i>.  From 1890 she was editor of <i>Friendly Leaves</i> (Jan 1876 to June 1917) a magazine, originally edited by Anne Mercier,  produced by the Girls' Friendly Society (founded 1875). Will proved £4615 [Hainton, <i>Unknown Coleridge</i>;  DNB; will]

## Letters Mentioning This Person

- [Letter 1849](../1849-to-katharine-olive-helmore-4.qmd)
- [Letter 1855](../1855-to-christabel-rose-coleridge-4.qmd)
- [Letter 1882](../1882-to-henrietta-elizabeth-fursdon-7.qmd)
- [Letter 1924](../1924-to-christabel-rose-coleridge-5.qmd)
- [Letter 1995](../1995-to-alexander-macmillan-29.qmd)
- [Letter 2003](../2003-to-christabel-rose-coleridge-6.qmd)
- [Letter 2023](../2023-to-katharine-olive-helmore-7.qmd)
- [Letter 2070](../2070-to-katharine-olive-helmore-8.qmd)
- [Letter 2078](../2078-to-christabel-rose-coleridge-7.qmd)
- [Letter 2088](../2088-to-ellen-julia-johns-8.qmd)
- [Letter 2093](../2093-to-frances-mary-peard-9.qmd)
- [Letter 2098](../2098-to-christabel-rose-coleridge-8.qmd)
- [Letter 2148](../2148-to-edith-coleridge.qmd)
- [Letter 2150](../2150-to-christabel-rose-coleridge-9.qmd)
- [Letter 2173](../2173-to-christabel-rose-coleridge-10.qmd)
- [Letter 2185](../2185-to-christabel-rose-coleridge-11.qmd)
- [Letter 2201](../2201-to-christabel-rose-coleridge-12.qmd)
- [Letter 2207](../2207-to-christabel-rose-coleridge-13.qmd)
- [Letter 2212](../2212-to-christabel-rose-coleridge-14.qmd)
- [Letter 2234](../2234-to-christabel-rose-coleridge-15.qmd)
- [Letter 2255](../2255-to-christabel-rose-coleridge-16.qmd)
- [Letter 2267](../2267-to-christabel-rose-coleridge-17.qmd)
- [Letter 2288](../2288-to-the-reverend-william-john-butler-2.qmd)
- [Letter 2289](../2289-to-christabel-rose-coleridge-60.qmd)
- [Letter 2291](../2291-to-christabel-rose-coleridge-18.qmd)
- [Letter 2294](../2294-to-christabel-rose-coleridge-19.qmd)
- [Letter 2299](../2299-to-henrietta-elizabeth-fursdon-11.qmd)
- [Letter 2306](../2306-to-christabel-rose-coleridge-20.qmd)
- [Letter 2307](../2307-to-the-members-of-the-gosling-society.qmd)
- [Letter 2327](../2327-to-henrietta-elizabeth-fursdon.qmd)
- [Letter 2369](../2369-to-christabel-rose-coleridge-61.qmd)
- [Letter 2374](../2374-to-christabel-rose-coleridge-62.qmd)
- [Letter 2379](../2379-to-christabel-rose-coleridge-63.qmd)
- [Letter 2382](../2382-to-christabel-rose-coleridge-64.qmd)
- [Letter 2411](../2411-to-christabel-rose-coleridge-65.qmd)
- [Letter 2416](../2416-to-christabel-rose-coleridge-66.qmd)
- [Letter 2419](../2419-to-christabel-rose-coleridge-67.qmd)
- [Letter 2421](../2421-to-christabel-rose-coleridge-68.qmd)
- [Letter 2422](../2422-to-christabel-rose-coleridge-69.qmd)
- [Letter 2427](../2427-to-miss-cassell.qmd)
- [Letter 2434](../2434-to-christabel-rose-coleridge-70.qmd)
- [Letter 2438](../2438-to-christabel-rose-coleridge-71.qmd)
- [Letter 2449](../2449-to-christabel-rose-coleridge-72.qmd)
- [Letter 2451](../2451-to-christabel-rose-coleridge-73.qmd)
- [Letter 2458](../2458-to-christabel-rose-coleridge-74.qmd)
- [Letter 2459](../2459-to-christabel-rose-coleridge-75.qmd)
- [Letter 2461](../2461-to-christabel-rose-coleridge-76.qmd)
- [Letter 2465](../2465-to-christabel-rose-coleridge-77.qmd)
- [Letter 2466](../2466-to-christabel-rose-coleridge-78.qmd)
- [Letter 2475](../2475-to-christabel-rose-coleridge-79.qmd)
- [Letter 2483](../2483-the-reverend-derwent-coleridge-to-charlotte-mary-yonge.qmd)
- [Letter 2487](../2487-to-the-hon-laura-elizabeth-palmer.qmd)
- [Letter 2510](../2510-to-christabel-rose-coleridge-80.qmd)
- [Letter 2532](../2532-to-christabel-rose-coleridge-81.qmd)
- [Letter 2533](../2533-to-christabel-rose-coleridge-82.qmd)
- [Letter 2549](../2549-to-christabel-rose-coleridge-83.qmd)
- [Letter 2568](../2568-to-christabel-rose-coleridge-84.qmd)
- [Letter 2570](../2570-to-christabel-rose-coleridge-85.qmd)
- [Letter 2572](../2572-to-christabel-rose-coleridge-86.qmd)
- [Letter 2573](../2573-to-christabel-rose-coleridge-87.qmd)
- [Letter 2587](../2587-to-christabel-rose-coleridge-88.qmd)
- [Letter 2590](../2590-to-christabel-rose-coleridge-89.qmd)
- [Letter 2600](../2600-from-charlotte-mary-yonge-and-christabel-rose-coleridge-to-mary-penelope-fursdon-and-the-other-members-of-the-gosling-society.qmd)
- [Letter 2607](../2607-to-elizabeth-wordsworth-9.qmd)
- [Letter 2616](../2616-to-christabel-rose-coleridge-90.qmd)
- [Letter 2618](../2618-to-christabel-rose-coleridge-91.qmd)
- [Letter 2619](../2619-to-christabel-rose-coleridge-92.qmd)
- [Letter 2630](../2630-to-christabel-rose-coleridge-93.qmd)
- [Letter 2634](../2634-to-christabel-rose-coleridge-94.qmd)
- [Letter 2639](../2639-to-christabel-rose-coleridge-95.qmd)
- [Letter 2643](../2643-to-christabel-rose-coleridge-96.qmd)
- [Letter 2647](../2647-to-christabel-rose-coleridge-97.qmd)
- [Letter 2648](../2648-to-christabel-rose-coleridge-98.qmd)
- [Letter 2663](../2663-to-christabel-rose-coleridge-99.qmd)
- [Letter 2667](../2667-to-christabel-rose-coleridge-100.qmd)
- [Letter 2717](../2717-to-christabel-rose-coleridge-101.qmd)
- [Letter 2723](../2723-to-christabel-rose-coleridge-102.qmd)
- [Letter 2727](../2727-to-christabel-rose-coleridge-103.qmd)
- [Letter 2733](../2733-to-christabel-rose-coleridge-104.qmd)
- [Letter 2735](../2735-to-christabel-rose-coleridge-105.qmd)
- [Letter 2750](../2750-to-christabel-rose-coleridge-106.qmd)
- [Letter 2765](../2765-to-george-lillie-craik-56.qmd)
- [Letter 2771](../2771-to-christabel-rose-coleridge-107.qmd)
- [Letter 2778](../2778-to-christabel-rose-coleridge-108.qmd)
- [Letter 2782](../2782-to-christabel-rose-coleridge-109.qmd)
- [Letter 2783](../2783-to-christabel-rose-coleridge-110.qmd)
- [Letter 2797](../2797-to-christabel-rose-coleridge-111.qmd)
- [Letter 2827](../2827-to-elizabeth-barnett-18.qmd)
- [Letter 2854](../2854-to-christabel-rose-coleridge-112.qmd)
- [Letter 2855](../2855-to-christabel-rose-coleridge-113.qmd)
- [Letter 2856](../2856-to-christabel-rose-coleridge-114.qmd)
- [Letter 2859](../2859-to-christabel-rose-coleridge-115.qmd)
- [Letter 2873](../2873-to-arthur-donald-innes-19.qmd)
- [Letter 2891](../2891-to-miss-kirke.qmd)
- [Letter 2923](../2923-to-elizabeth-barnett-23.qmd)
- [Letter 3157](../3157-to-arthur-donald-innes-8.qmd)
- [Letter 3164](../3164-to-florence-wilford-6.qmd)
- [Letter 3165](../3165-to-florence-wilford-7.qmd)
- [Letter 3174](../3174-to-arthur-donald-innes-11.qmd)
- [Letter 3175](../3175-to-arthur-donald-innes-12.qmd)
- [Letter 3176](../3176-to-arthur-donald-innes-13.qmd)
- [Letter 3189](../3189-to-arthur-donald-innes-16.qmd)
- [Letter 3190](../3190-to-christabel-rose-coleridge-29.qmd)
- [Letter 3197](../3197-to-elizabeth-barnett-14.qmd)
- [Letter 3199](../3199-to-alice-may-gordon-2.qmd)
- [Letter 3208](../3208-to-oscar-fay-adams.qmd)
- [Letter 3209](../3209-to-arthur-donald-innes-17.qmd)
- [Letter 3210](../3210-to-sarah-angelina-acland.qmd)
- [Letter 3212](../3212-to-george-lillie-craik-10.qmd)
- [Letter 3213](../3213-to-george-lillie-craik-11.qmd)
- [Letter 3216](../3216-to-lady-frederick-bruce-3.qmd)
- [Letter 3236](../3236-to-anne-elizabeth-mary-anderson-morshead-4.qmd)
- [Letter 3245](../3245-to-the-reverend-john-frederick-watkinson-bullock-2.qmd)
- [Letter 3359](../3359-to-christabel-rose-coleridge-30.qmd)
- [Letter 3386](../3386-to-christabel-rose-coleridge-25.qmd)
- [Letter 3388](../3388-to-christabel-rose-coleridge-27.qmd)
- [Letter 3407](../3407-to-lady-leconfield.qmd)
- [Letter 3409](../3409-to-mary-yonge-12.qmd)
- [Letter 3412](../3412-to-christabel-rose-coleridge-28.qmd)
- [Letter 3415](../3415-to-christabel-rose-coleridge-23.qmd)
- [Letter 3416](../3416-to-christabel-rose-coleridge-22.qmd)
- [Letter 3418](../3418-to-christabel-rose-coleridge-24.qmd)
- [Letter 3419](../3419-to-christabel-rose-coleridge-2.qmd)
- [Letter 3420](../3420-to-christabel-rose-coleridge-26.qmd)
- [Letter 3421](../3421-to-christabel-rose-coleridge-31.qmd)
- [Letter 3422](../3422-to-christabel-rose-coleridge-32.qmd)
- [Letter 3423](../3423-to-christabel-rose-coleridge-33.qmd)
- [Letter 3425](../3425-to-christabel-rose-coleridge-34.qmd)
- [Letter 3427](../3427-to-christabel-rose-coleridge-35.qmd)
- [Letter 3430](../3430-to-christabel-rose-coleridge-36.qmd)
- [Letter 3442](../3442-to-christabel-rose-coleridge-37.qmd)
- [Letter 3443](../3443-to-christabel-rose-coleridge-38.qmd)
- [Letter 3446](../3446-to-christabel-rose-coleridge-40.qmd)
- [Letter 3450](../3450-to-christabel-rose-coleridge-41.qmd)
- [Letter 3453](../3453-to-christabel-rose-coleridge-42.qmd)
- [Letter 3456](../3456-to-mary-yonge-33.qmd)
- [Letter 3458](../3458-to-christabel-rose-coleridge-43.qmd)
- [Letter 3459](../3459-to-christabel-rose-coleridge-44.qmd)
- [Letter 3460](../3460-to-christabel-rose-coleridge-45.qmd)
- [Letter 3461](../3461-to-christabel-rose-coleridge-46.qmd)
- [Letter 3464](../3464-to-christabel-rose-coleridge-48.qmd)
- [Letter 3465](../3465-to-christabel-rose-coleridge-49.qmd)
- [Letter 3466](../3466-to-christabel-rose-coleridge-50.qmd)
- [Letter 3468](../3468-to-christabel-rose-coleridge-51.qmd)
- [Letter 3469](../3469-to-christabel-rose-coleridge-52.qmd)
- [Letter 3470](../3470-to-christabel-rose-coleridge-53.qmd)
- [Letter 3471](../3471-to-christabel-rose-coleridge-54.qmd)
- [Letter 3473](../3473-to-christabel-rose-coleridge-55.qmd)
- [Letter 3477](../3477-to-christabel-rose-coleridge-56.qmd)
- [Letter 3478](../3478-to-christabel-rose-coleridge-57.qmd)
- [Letter 3479](../3479-to-christabel-rose-coleridge-58.qmd)
- [Letter 3480](../3480-to-christabel-rose-coleridge-59.qmd)
- [Letter 3481](../3481-to-charlotte-fortescue-yonge.qmd)
- [Letter 3545](../3545-to-miss-merriman.qmd)
- [Letter 3556](../3556-to-christabel-rose-coleridge.qmd)
- [Letter 3562](../3562-to-christabel-rose-coleridge-21.qmd)
- [Letter 3586](../3586-to-an-unknown-man-2.qmd)
- [Letter 3594](../3594-to-christabel-rose-coleridge-3.qmd)
- [Letter 3601](../3601-to-ann-maria-carter-smith-2.qmd)
- [Letter 3608](../3608-to-agnes-cox.qmd)
- [Letter 3611](../3611-to-an-unknown-woman-5.qmd)
- [Letter 18956](../18956-to-mary-elizabeth-hawker.qmd)
- [Letter 19875](../19875-to-anna-maria-keary.qmd)

