---
title: "John Mozley"
person_id: 1065
---

## Biographical Information

(1805-1872)

publisher

A partner in the publishing firm of John and Charles Mozley, he married (1835) Jemima Newman.

## Letters Mentioning This Person

- [Letter 1824](../1824-to-ann-maria-carter-smith-44.qmd)
- [Letter 1854](../1854-to-ann-maria-carter-smith-51.qmd)
- [Letter 1879](../1879-to-ann-maria-carter-smith-56.qmd)
- [Letter 1912](../1912-alexander-macmillan-to-charlotte-mary-yonge-3.qmd)
- [Letter 2762](../2762-to-the-reverend-bartholomew-price.qmd)
- [Letter 2960](../2960-to-mary-anne-dyson-3.qmd)
- [Letter 2992](../2992-to-elizabeth-roberts-12.qmd)
- [Letter 3002](../3002-to-elizabeth-roberts-22.qmd)
- [Letter 3003](../3003-to-elizabeth-roberts-23.qmd)
- [Letter 3014](../3014-to-elizabeth-roberts-28.qmd)
- [Letter 3018](../3018-to-elizabeth-roberts-29.qmd)
- [Letter 3021](../3021-to-elizabeth-roberts-30.qmd)
- [Letter 3022](../3022-to-elizabeth-roberts-31.qmd)
- [Letter 3040](../3040-to-anna-butler-5.qmd)
- [Letter 3084](../3084-to-anna-butler-11.qmd)
- [Letter 3085](../3085-to-anna-butler-12.qmd)
- [Letter 3086](../3086-to-anna-butler-13.qmd)
- [Letter 3098](../3098-to-harriet-dyke-acland-troyte.qmd)
- [Letter 3126](../3126-to-ann-maria-carter-smith-15.qmd)
- [Letter 7864](../7864-to-john-duke-coleridge.qmd)

