---
title: "Maria (Trench) Wilson"
person_id: 1539
---

## Biographical Information

(1820/1-7 Dec 1908)

wife of the Rev. Robert Francis Wilson

She married (6 May 1847) the Rev. Robert Francis Wilson, Vicar of Rownhams (d. 1888).  The <i>Court and Lady’s Magazine</i> (April 1847) 57 has ‘Trench, Maria, d. of the rev. Frederick S. Trench and lady Helen Trench, of Kilmorony, to the rev. Francis Wilson, son of Thomas Wilson esq. formerly M. P. for the city of London;  at the parish church of Athy, by the rev. John Keble, vicar of Hursley Hants, May 6 [1847]’ She was 1st cousin of T.R.F. Cooke Trench and, through her mother, of Sir William Heathcote's children by his first marriage. Frances Dorothy (Grimston) Moor was her first cousin, daughter of her aunt Jane Trench.  [PB 1914 Ashtown; <i>Erminois</i>]

## Letters Mentioning This Person

- [Letter 1812](../1812-to-jemima-blackburn-11.qmd)
- [Letter 1902](../1902-to-francis-heathcote-wilson.qmd)
- [Letter 2117](../2117-to-anne-yonge-45.qmd)
- [Letter 2293](../2293-to-mary-anne-moberly-5.qmd)
- [Letter 2300](../2300-to-mary-ann-dyson-8.qmd)
- [Letter 2412](../2412-to-edith-sophia-jacob-20.qmd)
- [Letter 2429](../2429-to-mary-anne-dyson-21.qmd)
- [Letter 2495](../2495-to-misey-2.qmd)
- [Letter 3017](../3017-to-anne-yonge-29.qmd)
- [Letter 3112](../3112-to-caroline-elizabeth-heathcote.qmd)

