---
title: "The Rev. Henry Albany Bowles jr."
person_id: 184
---

## Biographical Information

(1859- 2 March 1943)

Vicar of Otterbourne and nephew-in-law of CMY

He married (7 August 1884) (Louisa) Alethea Yonge (1863-1941).  He was ordained in 1883 and served first (1889) as curate of St Matthew, Haberham Eaves, Burnley.  He was made Rector of Arlington, near Barnstaple in 1884 and in 1892 became Vicar of Otterbourne.  He left £26,505. [Clergy List, will]

## Letters Mentioning This Person

- [Letter 2788](../2788-to-the-hon-mrs-montgomery-moore-3.qmd)
- [Letter 2831](../2831-to-sophia-jane-harrison-2.qmd)
- [Letter 3279](../3279-to-mary-yonge-14.qmd)
- [Letter 3320](../3320-to-mary-yonge-16.qmd)
- [Letter 3331](../3331-to-the-reverend-william-harris-bigg-wither-2.qmd)
- [Letter 3340](../3340-to-mary-yonge-17.qmd)
- [Letter 3342](../3342-to-mary-yonge-18.qmd)
- [Letter 3345](../3345-to-a-member-of-the-bigg-wither-family.qmd)
- [Letter 3346](../3346-to-mary-yonge-19.qmd)
- [Letter 3348](../3348-to-mary-yonge-20.qmd)
- [Letter 3349](../3349-to-marianne-bigg-wither-5.qmd)
- [Letter 3350](../3350-to-mary-yonge-21.qmd)
- [Letter 3352](../3352-to-helena-heathcote-3.qmd)
- [Letter 3354](../3354-to-mary-yonge-23.qmd)
- [Letter 3359](../3359-to-christabel-rose-coleridge-30.qmd)
- [Letter 3383](../3383-to-anna-meredith-barrett-lennard.qmd)
- [Letter 3399](../3399-to-marianne-bigg-wither-3.qmd)
- [Letter 3411](../3411-to-charlotte-fortescue-yonge-3.qmd)
- [Letter 3423](../3423-to-christabel-rose-coleridge-33.qmd)
- [Letter 3431](../3431-to-mary-yonge-25.qmd)
- [Letter 3453](../3453-to-christabel-rose-coleridge-42.qmd)
- [Letter 3456](../3456-to-mary-yonge-33.qmd)
- [Letter 3461](../3461-to-christabel-rose-coleridge-46.qmd)
- [Letter 3463](../3463-to-christabel-rose-coleridge-47.qmd)
- [Letter 3599](../3599-to-an-unknown-woman-3.qmd)
- [Letter 3602](../3602-to-the-reverend-henry-albany-bowles.qmd)

