---
title: "Henrietta Elizabeth Fursdon"
person_id: 538
---

## Biographical Information

(1843-1928)

member of the Gosling Society

She was a Gosling as ‘Irene’ and second daughter of the Rev. Edward Fursdon. [LG 1952 Fursdon]

## Letters Mentioning This Person

- [Letter 1842](../1842-to-henrietta-elizabeth-fursdon-2.qmd)
- [Letter 1844](../1844-to-henrietta-elizabeth-fursdon-3.qmd)
- [Letter 1850](../1850-to-katharine-olive-helmore-5.qmd)
- [Letter 1851](../1851-to-henrietta-elizabeth-fursdon-4.qmd)
- [Letter 1857](../1857-to-charlotte-sophia-fursdon.qmd)
- [Letter 1858](../1858-to-henrietta-elizabeth-fursdon-5.qmd)
- [Letter 1867](../1867-to-henrietta-elizabeth-fursdon-6.qmd)
- [Letter 1882](../1882-to-henrietta-elizabeth-fursdon-7.qmd)
- [Letter 1886](../1886-to-henrietta-elizabeth-fursdon-8.qmd)
- [Letter 1921](../1921-to-henrietta-elizabeth-fursdon-9.qmd)
- [Letter 1923](../1923-to-henrietta-elizabeth-fursdon-10.qmd)
- [Letter 2299](../2299-to-henrietta-elizabeth-fursdon-11.qmd)
- [Letter 2327](../2327-to-henrietta-elizabeth-fursdon.qmd)
- [Letter 19298](../19298-to-henrietta-elizabeth-fursdon.qmd)

