---
title: "Florence Wilford"
person_id: 1520
---

## Biographical Information

(Woolwich 29 Feb 1836-?1897)

novelist, contributor to <i>MP</i> (1866-83), member of the Gosling Society

Daughter of Major-General Edmund Neal Wilford (1800-1881), RA, Governor of the Royal Military Academy, Woolwich, until his retirement, she was a Gosling as ‘Turkscap’ from June 1865; her address then was c/o Mrs Chrystall's,. St. Cross, Winchester. In the 1851 census, she was 15 and was staying at Bromley Kent, in the company of Maria Cristall, whom CMY describes as her aunt.  In 1881 she and her elder sister Emma, 48, were living with their father in St. Leonards; in 1891 she and Emma were staying in Bournemouth.  Her Royal Literary Fund file indicates that she had suffered from mental illness intermittently since 1883 and was in a private asylum in 1889 when CMY wrote a letter to them on her behalf.  (Her application was refused on the grounds ‘authorship insufficient’, which seems rather harsh since she had published sixteen books since 1858.)  CMY assured Bullock (16 March 1895) that she was well and at home with her sister.  She was probably the Florence Wilford who died at Keynsham, Glos. in 1897. [IGI; RLF application 2311, born at Woolwich]

## Letters Mentioning This Person

- [Letter 1810](../1810-to-ann-maria-carter-smith-38.qmd)
- [Letter 1827](../1827-to-florence-wilford-2.qmd)
- [Letter 1834](../1834-to-ann-maria-carter-smith-46.qmd)
- [Letter 1859](../1859-to-ann-maria-carter-smith-52.qmd)
- [Letter 1892](../1892-to-ann-maria-carter-smith-61.qmd)
- [Letter 1925](../1925-to-florence-wilford.qmd)
- [Letter 2078](../2078-to-christabel-rose-coleridge-7.qmd)
- [Letter 2093](../2093-to-frances-mary-peard-9.qmd)
- [Letter 2185](../2185-to-christabel-rose-coleridge-11.qmd)
- [Letter 2201](../2201-to-christabel-rose-coleridge-12.qmd)
- [Letter 2203](../2203-to-margaret-helen-moberly.qmd)
- [Letter 2205](../2205-to-mrs-donkin.qmd)
- [Letter 2209](../2209-to-florence-wilford-3.qmd)
- [Letter 2210](../2210-to-the-reverend-arthur-rawson-ashwell.qmd)
- [Letter 2220](../2220-to-ellen-julia-johns-9.qmd)
- [Letter 2244](../2244-to-florence-wilford-4.qmd)
- [Letter 2288](../2288-to-the-reverend-william-john-butler-2.qmd)
- [Letter 2289](../2289-to-christabel-rose-coleridge-60.qmd)
- [Letter 2296](../2296-to-anne-elizabeth-mary-anderson-morshead-2.qmd)
- [Letter 2299](../2299-to-henrietta-elizabeth-fursdon-11.qmd)
- [Letter 2342](../2342-to-florence-wilford-5.qmd)
- [Letter 2399](../2399-to-anne-sturges-bourne-8.qmd)
- [Letter 2416](../2416-to-christabel-rose-coleridge-66.qmd)
- [Letter 2419](../2419-to-christabel-rose-coleridge-67.qmd)
- [Letter 2466](../2466-to-christabel-rose-coleridge-78.qmd)
- [Letter 2475](../2475-to-christabel-rose-coleridge-79.qmd)
- [Letter 2549](../2549-to-christabel-rose-coleridge-83.qmd)
- [Letter 2644](../2644-to-florence-wilford-8.qmd)
- [Letter 2702](../2702-to-florence-wilford-9.qmd)
- [Letter 2729](../2729-to-florence-wilford-10.qmd)
- [Letter 2765](../2765-to-george-lillie-craik-56.qmd)
- [Letter 2782](../2782-to-christabel-rose-coleridge-109.qmd)
- [Letter 2825](../2825-to-florence-wilford-11.qmd)
- [Letter 2906](../2906-to-an-unknown-man-21.qmd)
- [Letter 2909](../2909-to-arthur-llewelyn-roberts.qmd)
- [Letter 3130](../3130-to-ann-maria-carter-smith-19.qmd)
- [Letter 3164](../3164-to-florence-wilford-6.qmd)
- [Letter 3165](../3165-to-florence-wilford-7.qmd)
- [Letter 3286](../3286-to-the-reverend-john-frederick-watkinson-bullock-4.qmd)
- [Letter 19419](../19419-to-florence-wilford.qmd)
- [Letter 19674](../19674-alexander-macmillan-to-charlotte-mary-yonge.qmd)

