---
title: "Charlotte Cordelia (Pode) Yonge"
person_id: 1587
---

## Biographical Information

(1839/40- 7 Sept 1929)

cousin and goddaughter of CMY

First cousin of CMY, she was daughter of WCY’s sister Anne (Yonge) Pode.  She married (26 Aug 1862) Rev. Duke Yonge (1823-1881), of Puslinch. [census, LG]

## Letters Mentioning This Person

- [Letter 1864](../1864-to-charlotte-cordelia-pode.qmd)
- [Letter 1895](../1895-to-anne-yonge-38.qmd)
- [Letter 1899](../1899-to-anne-yonge-42.qmd)
- [Letter 2264](../2264-to-the-reverend-duke-yonge-2.qmd)
- [Letter 2338](../2338-to-the-reverend-duke-yonge.qmd)
- [Letter 2339](../2339-to-mary-yonge-7.qmd)
- [Letter 2340](../2340-to-charlotte-cordelia-yonge-2.qmd)
- [Letter 2420](../2420-to-charlotte-cordelia-yonge-4.qmd)
- [Letter 2439](../2439-to-charlotte-cordelia-yonge.qmd)
- [Letter 2561](../2561-to-mary-yonge-48.qmd)
- [Letter 3240](../3240-to-dorothea-yonge.qmd)
- [Letter 3287](../3287-to-mary-yonge-15.qmd)
- [Letter 3288](../3288-to-charlotte-cordelia-yonge-3.qmd)
- [Letter 3388](../3388-to-christabel-rose-coleridge-27.qmd)
- [Letter 3393](../3393-to-mary-yonge-3.qmd)
- [Letter 3404](../3404-to-mary-yonge-5.qmd)
- [Letter 3431](../3431-to-mary-yonge-25.qmd)
- [Letter 3435](../3435-to-mary-yonge-27.qmd)
- [Letter 3454](../3454-to-mary-yonge-31.qmd)
- [Letter 3456](../3456-to-mary-yonge-33.qmd)
- [Letter 3481](../3481-to-charlotte-fortescue-yonge.qmd)

