---
title: "Sarah Anne (Northwood) Mercier"
person_id: 990
---

## Biographical Information

(Herts. 1842/3-1917)

contributor to <i>MP</i> (1869-84)

Known as Anne Mercier, she married (1868) the Rev. Jerome John Mercier, Rector of Kemerton, Glos.. A brief obituary in <i>The Times</i> (8 Feb 1917) says that ‘she helped to found the Girls’ Friendly Society as well as the Girls’ High School at Tewkesbury’ and that her son succeeded his father as Rector of Kemerton.  She was active in the GFS, and was editor at one time of <i>Friendly Leaves</i> (perhaps taking over from Christabel Coleridge in the twentieth century?).


[COPAC]

## Letters Mentioning This Person

- [Letter 2305](../2305-to-anne-mercier-7.qmd)
- [Letter 2314](../2314-to-anne-mercier-2.qmd)
- [Letter 2318](../2318-to-anne-mercier-3.qmd)
- [Letter 2323](../2323-to-anne-mercier-4.qmd)
- [Letter 2359](../2359-to-anne-mercier-5.qmd)
- [Letter 2366](../2366-to-anne-mercier-8.qmd)
- [Letter 2419](../2419-to-christabel-rose-coleridge-67.qmd)
- [Letter 2458](../2458-to-christabel-rose-coleridge-74.qmd)
- [Letter 2464](../2464-to-blanche-catherine-medhurst-2.qmd)
- [Letter 2469](../2469-to-anne-mercier-6.qmd)
- [Letter 2523](../2523-to-blanche-catherine-medhurst-6.qmd)
- [Letter 2694](../2694-to-anne-mercier.qmd)

