---
title: "Susanna Warren"
person_id: 1475
---

## Biographical Information

(b. Edmonton 1814/5)

author of fiction and non-fiction as ‘S.W.’

In the 1851 census she was living with her elder sister Selina Warren (b. 1812/3) at Hazlewood Farm, Hennock, near Bovey Tracey, Devon; she was staying with nephew William Henderson, woollen manufacturer, at 3 South Bailey Durham at the time of the 1861 census;  in the 1871 census she was again at Hazlewood, Hennock, with her eldest sister Charlotte Warren (b.1787/8).  It seems possible that in the 1860s she worked for the Rev. John Hawksley in Clifton as a governess.  She was author of fiction and non-fiction (tracts?) from 1860, under the initials S.W., for the SPCK.

## Letters Mentioning This Person

- [Letter 1804](../1804-to-susanna-warren-2.qmd)
- [Letter 1814](../1814-to-susanna-warren-3.qmd)
- [Letter 1828](../1828-to-susanna-warren-4.qmd)
- [Letter 1870](../1870-to-frances-sophia-coleridge-patteson-5.qmd)
- [Letter 1983](../1983-to-an-unknown-man-8.qmd)
- [Letter 2081](../2081-to-susanna-warren-5.qmd)
- [Letter 2353](../2353-to-susanna-warren-6.qmd)
- [Letter 2391](../2391-to-susanna-warren-7.qmd)
- [Letter 3491](../3491-to-susanna-warren.qmd)

