---
title: "Mary Elizabeth (Heywood) Sumner"
person_id: 1381
---

## Biographical Information

(31 Dec 1828-11 Aug 1921)

founder of the Mothers’ Union

She married (1848) the Rt. Rev. George Henry Sumner (1824-1909), Rector from 1851 of Old Arlesford and later Bishop of Guildford.  She founded the Mother's Union.  She was mother of Heywood Sumner the artist.

## Letters Mentioning This Person

- [Letter 2827](../2827-to-elizabeth-barnett-18.qmd)
- [Letter 2848](../2848-to-mary-elizabeth-sumner.qmd)
- [Letter 2858](../2858-to-mary-drew-3.qmd)
- [Letter 3162](../3162-to-george-lillie-craik-8.qmd)
- [Letter 3184](../3184-to-the-archdeacon-of.qmd)
- [Letter 3215](../3215-to-john-athelstan-laurie-riley.qmd)
- [Letter 3216](../3216-to-lady-frederick-bruce-3.qmd)
- [Letter 3358](../3358-to-louisa-fanny-field.qmd)
- [Letter 3365](../3365-to-the-reverend-william-parsons-warburton-5.qmd)
- [Letter 3396](../3396-to-mary-elizabeth-sumner-2.qmd)
- [Letter 3412](../3412-to-christabel-rose-coleridge-28.qmd)
- [Letter 3458](../3458-to-christabel-rose-coleridge-43.qmd)
- [Letter 3545](../3545-to-miss-merriman.qmd)
- [Letter 3594](../3594-to-christabel-rose-coleridge-3.qmd)

