---
title: "Anna Rachel Bramston"
person_id: 195
---

## Biographical Information

(Witham 1848/9-1931)

contributor to <i>MP</i> (1887)

She was the daughter of the Rev. John Bramston by his second wife, and half-sister of Mary Eliza Bramston.  In the 1891 census she was living at Witham Close, Kingsgate St., Winchester with her widowed mother Anna Bramston aged 84. She seems to have lived later with the novelist Amelie Claire Leroy, and they adopted a daughter called Juliette (perhaps a relation of Leroy’s?). The two of them published two books on the history of Winchester.  They were closely involved in the foundation of the Winchester High School (now St. Swithin’s School). She was on the Diocesan Council of the GFS in 1878, she and CMY in charge of the literature department.

## Letters Mentioning This Person

- [Letter 2563](../2563-to-anna-rachel-bramston-4.qmd)
- [Letter 2644](../2644-to-florence-wilford-8.qmd)
- [Letter 2711](../2711-to-anna-rachel-bramston-5.qmd)
- [Letter 3356](../3356-to-beatrice-heathcote-2.qmd)
- [Letter 3371](../3371-to-beatrice-heathcote.qmd)
- [Letter 3409](../3409-to-mary-yonge-12.qmd)
- [Letter 3416](../3416-to-christabel-rose-coleridge-22.qmd)
- [Letter 3464](../3464-to-christabel-rose-coleridge-48.qmd)
- [Letter 3523](../3523-to-anna-rachel-bramston-3.qmd)
- [Letter 3607](../3607-to-anna-rachel-bramston-2.qmd)
- [Letter 19268](../19268-to-anna-rachel-bramston.qmd)

