---
title: "Maria Edith Walker"
person_id: 2234
---

## Biographical Information

(Middlesex 1843-1938)

correspondent of CMY

The letters from CMY to Miss M. E. Walker were presented to West Sussex Record Office in 1975 by the latter's niece Bertha Yeats, who was then 91. [Information from Alison McCann, West Sussex Record Office]  Bertha Margaret F. Yeats (1883-1976) was the daughter of the Rev. George Yeats (b. Yorks. 1826/7), Vicar of Heworth, York, and Rosa Bertha Walker (1852-1900).  Mrs Yeats's sister, Maria Edith Walker, was therefore the recipient of the letters from CMY.   The Walker sisters were the daughters of Francis Walker (1809-1874), entomologist, and his wife and cousin Mary Elizabeth Ford (b. 1814/15), daughter of John Ford of Ellel Hall, Lancashire and Elizabeth Lawson.  Francis Walker, son of John Walker (1766-1824)  was a member of a family of rich and philanthropic brewers living at Arnos Grove, Southgate, Middlesex.  The Miss Lawrence referred to in the correspondence, grandmother of Maria Walker, who had been at school with Frances Mary Yonge, was perhaps the wife of John Walker.

## Letters Mentioning This Person

- [Letter 3424](../3424-to-miss-e-m-walker.qmd)
- [Letter 3426](../3426-to-maria-edith-walker-2-2.qmd)
- [Letter 3428](../3428-to-miss-e-m-walker-6.qmd)
- [Letter 3429](../3429-to-miss-e-m-walker-5.qmd)
- [Letter 3436](../3436-to-miss-e-m-walker-3.qmd)
- [Letter 3438](../3438-to-miss-e-m-walker-4.qmd)
- [Letter 3462](../3462-to-miss-e-m-walker-2.qmd)

