---
title: "Mary (Kingsman) Bargus"
person_id: 103
---

## Biographical Information

(1759?-1843)

maternal grandmother of CMY

Coleridge states, <i>[Life](../other_books/otherbook_40.qmd)</i>, 154 that CMY's grandmother died in 1848.  However, it seems more probable that she died in 1843, when the death was registered in Winchester of a person of that name. She was daughter of the Rev. Thomas Kingsman (1717-1779), Vicar of Botley, and married (1792), as his second wife, the Rev. Thomas Bargus.  'I think she was 89' when she died, wrote CMY.  The IGI records the christening of a Mary Kingsman at Botley in 1751, which would make her about 92 in 1843, and 44 at the time of FMY's birth in 1795. Her father's death is recorded in the <i>Town and Country Magazine</i> (1780), 55.

## Letters Mentioning This Person

- [Letter 2730](../2730-to-ann-maria-carter-smith-86.qmd)
- [Letter 2881](../2881-to-jean-ingelow.qmd)
- [Letter 2936](../2936-to-anne-yonge-4.qmd)
- [Letter 3034](../3034-frances-mary-yonge-to-mary-yonge.qmd)
- [Letter 3247](../3247-to-anne-isabella-ritchie.qmd)
- [Letter 3304](../3304-to-the-parishioners-of-otterbourne-3.qmd)
- [Letter 3385](../3385-to-mary-yonge-4.qmd)

