---
title: "Elizabeth Barnett"
person_id: 113
---

## Biographical Information

(28 Nov 1810-15 April 1900)

sister-in-law of the Very Rev. William John Butler

Second cousin of the Very Rev. William Butler, who was married to her younger sister Emma Barnett, she supported his good works at Wantage.  She lived with her father George Henry Barnett (d. 1871) and younger sister Louisa at Glympton and in Wilton Crescent. [H. Barnett, <i>Glympton</i>;  LG 1952 Barnett formerly of Glympton] 

## Letters Mentioning This Person

- [Letter 1790](../1790-to-anna-butler-18.qmd)
- [Letter 1818](../1818-to-anne-sturges-bourne-7.qmd)
- [Letter 2001](../2001-to-elizabeth-barnett-12.qmd)
- [Letter 2320](../2320-to-arthur-john-butler-2.qmd)
- [Letter 2322](../2322-to-arthur-john-butler-3.qmd)
- [Letter 2468](../2468-to-elizabeth-barnett-16.qmd)
- [Letter 2641](../2641-to-elizabeth-barnett-17.qmd)
- [Letter 2827](../2827-to-elizabeth-barnett-18.qmd)
- [Letter 2845](../2845-to-elizabeth-barnett-19.qmd)
- [Letter 2867](../2867-to-elizabeth-barnett-20.qmd)
- [Letter 2870](../2870-to-elizabeth-barnett-21.qmd)
- [Letter 2871](../2871-to-elizabeth-barnett.qmd)
- [Letter 2880](../2880-to-elizabeth-barnett-22.qmd)
- [Letter 2923](../2923-to-elizabeth-barnett-23.qmd)
- [Letter 2926](../2926-to-elizabeth-barnett-24.qmd)
- [Letter 2964](../2964-to-mary-anne-dyson-5.qmd)
- [Letter 2973](../2973-to-elizabeth-barnett-2.qmd)
- [Letter 2975](../2975-to-elizabeth-barnett-3.qmd)
- [Letter 3020](../3020-to-elizabeth-barnett-4.qmd)
- [Letter 3023](../3023-to-anna-butler-2.qmd)
- [Letter 3024](../3024-to-anna-butler-3.qmd)
- [Letter 3025](../3025-to-elizabeth-roberts-32.qmd)
- [Letter 3031](../3031-to-elizabeth-barnett-5.qmd)
- [Letter 3053](../3053-to-elizabeth-barnett-6.qmd)
- [Letter 3068](../3068-to-anna-butler-6.qmd)
- [Letter 3077](../3077-to-anna-butler-7.qmd)
- [Letter 3082](../3082-to-anna-butler-9.qmd)
- [Letter 3091](../3091-to-anna-butler-14.qmd)
- [Letter 3108](../3108-to-elizabeth-barnett-7.qmd)
- [Letter 3134](../3134-to-elizabeth-barnett-8.qmd)
- [Letter 3135](../3135-to-elizabeth-barnett-9.qmd)
- [Letter 3147](../3147-to-elizabeth-barnett-13.qmd)
- [Letter 3197](../3197-to-elizabeth-barnett-14.qmd)
- [Letter 3230](../3230-to-elizabeth-barnett-15.qmd)
- [Letter 3244](../3244-to-the-reverend-arthur-roland-maddison.qmd)
- [Letter 3336](../3336-to-edith-emma-knight.qmd)
- [Letter 3403](../3403-to-mary-caroline-butler.qmd)
- [Letter 3518](../3518-to-elizabeth-barnett-10.qmd)
- [Letter 3520](../3520-to-elizabeth-barnett.qmd)
- [Letter 3557](../3557-to-mrs-white.qmd)

