---
title: "Elizabeth Missing Sewell"
person_id: 1301
---

## Biographical Information

(19 Feb 1815-17 Aug 1906)

novelist, schoolmistress, contributor to <i>MP</i> (1871-94)

[ODNB]

## Letters Mentioning This Person

- [Letter 1787](../1787-to-ann-maria-carter-smith-33.qmd)
- [Letter 1816](../1816-to-elizabeth-missing-sewell-13.qmd)
- [Letter 1959](../1959-to-elizabeth-missing-sewell-12.qmd)
- [Letter 2004](../2004-to-elizabeth-missing-sewell-4.qmd)
- [Letter 2014](../2014-to-alexander-macmillan-37.qmd)
- [Letter 2042](../2042-to-alexander-macmillan-48.qmd)
- [Letter 2043](../2043-alexander-macmillan-to-charlotte-mary-yonge-33.qmd)
- [Letter 2044](../2044-to-alexander-macmillan-49.qmd)
- [Letter 2045](../2045-alexander-macmillan-to-charlotte-mary-yonge-34.qmd)
- [Letter 2047](../2047-to-alexander-macmillan-50.qmd)
- [Letter 2049](../2049-alexander-macmillan-to-charlotte-mary-yonge-35.qmd)
- [Letter 2050](../2050-to-alexander-macmillan-51.qmd)
- [Letter 2051](../2051-alexander-macmillan-to-charlotte-mary-yonge-36.qmd)
- [Letter 2077](../2077-to-elizabeth-missing-sewell-5.qmd)
- [Letter 2106](../2106-to-elizabeth-missing-sewell-6.qmd)
- [Letter 2114](../2114-to-elizabeth-missing-sewell-14.qmd)
- [Letter 2136](../2136-to-alexander-macmillan-80.qmd)
- [Letter 2137](../2137-to-alexander-macmillan-81.qmd)
- [Letter 2145](../2145-to-alexander-macmillan-83.qmd)
- [Letter 2169](../2169-to-elizabeth-missing-sewell-7.qmd)
- [Letter 2178](../2178-to-edith-sophia-jacob-9.qmd)
- [Letter 2183](../2183-to-alexander-macmillan-88.qmd)
- [Letter 2186](../2186-to-alexander-macmillan-89.qmd)
- [Letter 2188](../2188-to-alexander-macmillan-90.qmd)
- [Letter 2189](../2189-alexander-macmillan-to-charlotte-mary-yonge-54.qmd)
- [Letter 2226](../2226-alexander-macmillan-to-charlotte-mary-yonge-62.qmd)
- [Letter 2232](../2232-alexander-macmillan-to-charlotte-mary-yonge-65.qmd)
- [Letter 2239](../2239-alexander-macmillan-to-charlotte-mary-yonge-71.qmd)
- [Letter 2245](../2245-to-alexander-macmillan-95.qmd)
- [Letter 2246](../2246-to-alexander-macmillan-96.qmd)
- [Letter 2247](../2247-alexander-macmillan-to-charlotte-mary-yonge-73.qmd)
- [Letter 2248](../2248-to-alexander-macmillan-97.qmd)
- [Letter 2253](../2253-to-elizabeth-missing-sewell-8.qmd)
- [Letter 2254](../2254-alexander-macmillan-to-charlotte-mary-yonge-75.qmd)
- [Letter 2258](../2258-to-alexander-macmillan-98.qmd)
- [Letter 2284](../2284-to-elizabeth-missing-sewell-9.qmd)
- [Letter 2297](../2297-to-an-unknown-woman-32.qmd)
- [Letter 2344](../2344-to-ellen-julia-johns-10.qmd)
- [Letter 2361](../2361-to-alexander-macmillan-112.qmd)
- [Letter 2370](../2370-to-elizabeth-missing-sewell-15.qmd)
- [Letter 2380](../2380-to-alexander-macmillan-115.qmd)
- [Letter 2388](../2388-to-alexander-macmillan-116.qmd)
- [Letter 2390](../2390-to-the-reverend-william-john-butler.qmd)
- [Letter 2401](../2401-to-elizabeth-missing-sewell-16.qmd)
- [Letter 2403](../2403-to-elizabeth-missing-sewell.qmd)
- [Letter 2406](../2406-to-elizabeth-missing-sewell-17.qmd)
- [Letter 2407](../2407-to-elizabeth-missing-sewell-18.qmd)
- [Letter 2418](../2418-to-elizabeth-missing-sewell-19.qmd)
- [Letter 2426](../2426-to-edward-augustus-freeman-3.qmd)
- [Letter 2430](../2430-to-janetta-sewell.qmd)
- [Letter 2431](../2431-to-elizabeth-missing-sewell-20.qmd)
- [Letter 2514](../2514-to-edward-augustus-freeman-9.qmd)
- [Letter 2546](../2546-to-elizabeth-missing-sewell-22.qmd)
- [Letter 2598](../2598-to-elizabeth-missing-sewell-23.qmd)
- [Letter 2722](../2722-to-miss-cleveland.qmd)
- [Letter 2756](../2756-to-elizabeth-wordsworth.qmd)
- [Letter 2953](../2953-to-anne-yonge-20.qmd)
- [Letter 3067](../3067-to-alice-arbuthnot-moberly-6.qmd)
- [Letter 3094](../3094-to-ann-maria-carter-smith-9.qmd)
- [Letter 3525](../3525-to-elizabeth-missing-sewell-3.qmd)
- [Letter 3564](../3564-to-elizabeth-missing-sewell-11.qmd)
- [Letter 3571](../3571-to-elizabeth-missing-sewell-2.qmd)
- [Letter 19643](../19643-alexander-macmillan-to-charlotte-mary-yonge.qmd)
- [Letter 19653](../19653-alexander-macmillan-to-charlotte-mary-yonge.qmd)
- [Letter 19670](../19670-alexander-macmillan-to-charlotte-mary-yonge.qmd)
- [Letter 19672](../19672-alexander-macmillan-to-charlotte-mary-yonge.qmd)
- [Letter 19905](../19905-to-john-william-parker-jr.qmd)

