---
title: "Anne Elizabeth Mary Anderson Morshead"
person_id: 28
---

## Biographical Information

(1845/6-1928)

missionary and schoolmistress

Always called Mary, she was the daughter of Pentire Anderson Morshead and Charlotte Story; her paternal grandmother was a Yonge which made her a cousin of CMY.  She joined the Gosling Society as ‘Bog Oak’ and was one of the liveliest contributors to <i>The Barnacle</i>, she left when she went to South Africa to do missionary and social work in 1868; she later wrote a history of the <i>Universities Mission to Central Africa 1859-1896</i> (1897) and  <i>A Pioneer and Founder . . . Robert Gray, first Bishop of Cape Town</i> (1905).  She  also edited <i>Eikon Basilike</i> (1887). For many years, from at least 1881, she was a matron at Marlborough St Giles Industrial School for Girls, Andover. Many of her contributions to <i>MP</i> are signed ‘Bog Oak’.  <i>Jackson’s Oxford Journal</i> (30 May 1891) reports her speaking at a GFS conference as a member of the committee for the Winchester Diocese. She was first cousin to fellow-Goslings Mary Sunderland and Anne Baker.

## Letters Mentioning This Person

- [Letter 2173](../2173-to-christabel-rose-coleridge-10.qmd)
- [Letter 2234](../2234-to-christabel-rose-coleridge-15.qmd)
- [Letter 2255](../2255-to-christabel-rose-coleridge-16.qmd)
- [Letter 2267](../2267-to-christabel-rose-coleridge-17.qmd)
- [Letter 2291](../2291-to-christabel-rose-coleridge-18.qmd)
- [Letter 2296](../2296-to-anne-elizabeth-mary-anderson-morshead-2.qmd)
- [Letter 2347](../2347-to-anne-elizabeth-mary-anderson-morshead-3.qmd)
- [Letter 2434](../2434-to-christabel-rose-coleridge-70.qmd)
- [Letter 2765](../2765-to-george-lillie-craik-56.qmd)
- [Letter 2788](../2788-to-the-hon-mrs-montgomery-moore-3.qmd)
- [Letter 2878](../2878-to-anne-elizabeth-mary-anderson-morshead.qmd)
- [Letter 2931](../2931-to-anne-elizabeth-mary-anderson-morshead-7.qmd)
- [Letter 3236](../3236-to-anne-elizabeth-mary-anderson-morshead-4.qmd)
- [Letter 3245](../3245-to-the-reverend-john-frederick-watkinson-bullock-2.qmd)
- [Letter 3260](../3260-to-anne-elizabeth-mary-anderson-morshead-5.qmd)
- [Letter 3419](../3419-to-christabel-rose-coleridge-2.qmd)
- [Letter 3434](../3434-to-mary-yonge-26.qmd)
- [Letter 3440](../3440-to-mrs-belfield-2.qmd)
- [Letter 3444](../3444-to-mrs-belfield.qmd)
- [Letter 3464](../3464-to-christabel-rose-coleridge-48.qmd)
- [Letter 3465](../3465-to-christabel-rose-coleridge-49.qmd)
- [Letter 3466](../3466-to-christabel-rose-coleridge-50.qmd)
- [Letter 3468](../3468-to-christabel-rose-coleridge-51.qmd)
- [Letter 3469](../3469-to-christabel-rose-coleridge-52.qmd)
- [Letter 3471](../3471-to-christabel-rose-coleridge-54.qmd)
- [Letter 3477](../3477-to-christabel-rose-coleridge-56.qmd)
- [Letter 3478](../3478-to-christabel-rose-coleridge-57.qmd)
- [Letter 3479](../3479-to-christabel-rose-coleridge-58.qmd)
- [Letter 3521](../3521-to-miss-phillpotts.qmd)
- [Letter 3544](../3544-to-anne-elizabeth-mary-anderson-morshead-6.qmd)
- [Letter 3567](../3567-to-edmund-doidge-anderson-morshead.qmd)
- [Letter 7798](../7798-to-sir-john-taylor-coleridge.qmd)

