---
title: "Frances Awdry"
person_id: 82
---

## Biographical Information

(1845-19 March 1927)

contributor to <i>MP</i>

The  author of biographies of Patteson, William Heathcote and Anne Mackenzie, she is  not to be confused with her sister-in-law, (Frances) Emily (Moberly) Awdry. The daughter of Sir John Wither Awdry (1795-1878), chief justice of Bombay, sister of the Rt. Rev. William Awdry, Charles Awdry and the Rev. Vere Awdry, she lived with her mother at Notton. Sir John Awdry’s mother Jane Bigg was the sister of Sir William Heathcote’s mother Elizabeth (Bigg) Heathcote, and he was therefore cousin to Sir William and to the Rev. William Bigg Wither. Two of Frances Awdry's brothers married daughters of the Rt. Rev. Dr George Moberly.  





Photographs of the family appear at http://www.family-forest.co.uk/familytree/albums/awdry/awdry-photo.shtml

## Letters Mentioning This Person

- [Letter 2475](../2475-to-christabel-rose-coleridge-79.qmd)
- [Letter 2532](../2532-to-christabel-rose-coleridge-81.qmd)
- [Letter 2796](../2796-to-mary-ann-moberly.qmd)
- [Letter 2863](../2863-to-frances-awdry.qmd)
- [Letter 3246](../3246-to-the-reverend-john-frederick-watkinson-bullock-9.qmd)
- [Letter 3446](../3446-to-christabel-rose-coleridge-40.qmd)

