---
title: "Dr. John Francis Duke Yonge M.D."
person_id: 1622
---

## Biographical Information

(1814-25 Dec 1879)

cousin of CMY

The son of the Rev. Duke Yonge, Vicar of Antony, he married first (Brussels 12 August 1839) a widow with two children, Elizabeth Alice (Holmes) Reed (1799/1800-1863) and, secondly (1864) Mary Jones.  He seems to have converted to Roman Catholicism.  For that reason he was not welcome at WCY’s funeral. 





By his first marriage he had three sons, Francis Arthur Holmes Yonge, James Frederick Moore Yonge (b. Coblentz 1841/2?) and Stephen Duke Yonge (Coblentz 1844/5-1914).   In the 1871 census he and his second wife are living in Cornwall with three small grandsons, born in Mauritius, and probably the children of Francis, who had gone to live there.  The two younger sons had moved to Melbourne, Australia, by 1864. 





One of the 'grandsons', Eugene Yonge (b. Mauritius 1867/8) appears in the 1881 census in Plymstock with his uncle the Rev. Theophilus Jones (1822/3-1886), Vicar of Bradstone, and as a medical student in the 1891 census.  [census; <i>Alumni Oxonienses</i> An obituary of 'Eugene Stephen Yonge, M.D.Edin., Physician, Manchester Hospital For Consumption' appeared in the <i>The British Medical Journal</i> 1 (Feb. 3, 1912), p. 280;  advertisement <i>Morning Post</i> 16 April 1864, 1]

## Letters Mentioning This Person

- [Letter 1814](../1814-to-susanna-warren-3.qmd)
- [Letter 1899](../1899-to-anne-yonge-42.qmd)
- [Letter 2961](../2961-william-crawley-yonge-to-the-reverend-john-yonge.qmd)
- [Letter 2970](../2970-to-mary-anne-dyson-10.qmd)
- [Letter 3033](../3033-frances-mary-yonge-to-the-reverend-john-yonge.qmd)
- [Letter 3036](../3036-anne-yonge-to-the-rev-john-yonge.qmd)

