---
title: "Frances Maria Wilbraham"
person_id: 1513
---

## Biographical Information

(1816- 26 June 1905)

novelist, contributor to <i>MP</i> (1860-85)

She was the fifth of seven daughters (there were also four sons);  she was living in Chester with her mother and sisters in the 1861 and with her sisters in the 1881 census; a friend of Mrs Moberly;  she contributed to CMY’s <i>Musings over the Christian Year</i>. Her brother Richard Wilbraham was governor of the Royal Victoria Hospital, Netley. [LG 1906 Wilbraham of Delamere]

## Letters Mentioning This Person

- [Letter 1804](../1804-to-susanna-warren-2.qmd)
- [Letter 1970](../1970-to-miss-longueville.qmd)
- [Letter 2067](../2067-to-fanny.qmd)
- [Letter 2101](../2101-to-alexander-macmillan-70.qmd)
- [Letter 2156](../2156-to-alexander-macmillan-85.qmd)
- [Letter 2268](../2268-to-edith-sophia-jacob-16.qmd)
- [Letter 2729](../2729-to-florence-wilford-10.qmd)
- [Letter 3133](../3133-to-ann-maria-carter-smith-22.qmd)
- [Letter 18775](../18775-to-frances-maria-wilbraham.qmd)
- [Letter 19670](../19670-alexander-macmillan-to-charlotte-mary-yonge.qmd)

