---
title: "Harriet Catherine (Carr) Romanoff"
person_id: 1259
---

## Biographical Information

(1827/8-1897)

contributor to <i>MP</i> (1861-77)

CMY’s Russian correspondent, she came from a family who were friends and neighbours of Florence Wilford in Woolwich;  her mother Harriet Catherine Carr also contributed to <i>MP</i>. Monuments in St. George’s Beckenham include: James Joshua CARR of Old Charlton Kent 22 May 1865 aged 67. Harriet Catherine Carr widow of above 27 August 1895 aged 90. Samuel Sidney Carr 13 August 1842 aged 1 year 9 months. Captain James Sweet Carr of H M Bombay Staff Corps 28 February 1864 aged 31 sons of James Joshua and Harriet Catherine Carr. Also Janet Susan Carr youngest daughter of J J and H C Carr 16 July 1919 aged 75. Also Harriet Catherine ROMANOFF daughter of J J and H C Carr 10 August 1897 aged 69 at Kishinieff Russia. [This is now Kishinev, capital of Moldova, and was scene of a notorious pogrom in 1903]

## Letters Mentioning This Person

- [Letter 1820](../1820-to-ann-maria-carter-smith-40.qmd)
- [Letter 2030](../2030-to-alexander-macmillan-43.qmd)

