---
title: "Gertrude Mary Ireland Blackburne"
person_id: 160
---

## Biographical Information

(13 May 1861-28 November 1951)

journalist and church worker

Daughter of John Blackburne of Chester, wine merchant, and Mary Buchanan, she was co-editor of <i>The Churchwoman</i> (1897-1905) assistant editor of <i>The Sign</i> (1905-50) and contributor to <i>MP</i> (1889-1898).  It appears that her family may have originally used the spelling Blackburn. [WWW; wills index]

## Letters Mentioning This Person

- [Letter 2800](../2800-to-gertrude-mary-ireland-blackburnef.qmd)
- [Letter 2801](../2801-to-gertrude-mary-ireland-blackburne-3.qmd)
- [Letter 2816](../2816-to-gertrude-mary-ireland-blackburne-4.qmd)
- [Letter 2822](../2822-to-gertrude-mary-ireland-blackburne-5.qmd)
- [Letter 2823](../2823-to-gertrude-mary-ireland-blackburne.qmd)
- [Letter 3419](../3419-to-christabel-rose-coleridge-2.qmd)
- [Letter 3442](../3442-to-christabel-rose-coleridge-37.qmd)
- [Letter 3478](../3478-to-christabel-rose-coleridge-57.qmd)
- [Letter 3585](../3585-to-gertrude-mary-ireland-blackburne-2.qmd)

