---
title: "Alexander Macmillan"
person_id: 939
---

## Biographical Information

(1818-1896)

publisher

He married (1851) Caroline Brimley (d. 1871). The most important as well as the best documented of CMY’s publishers; he agreed 1877 her assignment of copyrights. [ODNB]

## Letters Mentioning This Person

- [Letter 1905](../1905-to-alexander-macmillan-2.qmd)
- [Letter 1906](../1906-alexander-macmillan-to-charlotte-mary-yonge-2.qmd)
- [Letter 1907](../1907-to-alexander-macmillan-3.qmd)
- [Letter 1913](../1913-to-alexander-macmillan-4.qmd)
- [Letter 1914](../1914-to-alexander-macmillan-5.qmd)
- [Letter 1917](../1917-to-alexander-macmillan-6.qmd)
- [Letter 1918](../1918-alexander-macmillan-to-charlotte-mary-yonge-5.qmd)
- [Letter 1919](../1919-to-alexander-macmillan-7.qmd)
- [Letter 1926](../1926-to-alexander-macmillan-8.qmd)
- [Letter 1927](../1927-alexander-macmillan-to-charlotte-mary-yonge-6.qmd)
- [Letter 1928](../1928-alexander-macmillan-to-charlotte-mary-yonge-7.qmd)
- [Letter 1930](../1930-to-alexander-macmillan-9.qmd)
- [Letter 1932](../1932-to-alexander-macmillan-10.qmd)
- [Letter 1933](../1933-to-alexander-macmillan-11.qmd)
- [Letter 1936](../1936-to-alexander-macmillan-12.qmd)
- [Letter 1938](../1938-to-alexander-macmillan-13.qmd)
- [Letter 1939](../1939-alexander-macmillan-to-charlotte-mary-yonge-8.qmd)
- [Letter 1940](../1940-to-alexander-macmillan-14.qmd)
- [Letter 1943](../1943-alexander-macmillan-to-charlotte-mary-yonge-9.qmd)
- [Letter 1944](../1944-to-alexander-macmillan-15.qmd)
- [Letter 1953](../1953-to-messrs-macmillan-2.qmd)
- [Letter 1955](../1955-alexander-macmillan-to-charlotte-mary-yonge-10.qmd)
- [Letter 1957](../1957-alexander-macmillan-to-charlotte-mary-yonge-11.qmd)
- [Letter 1958](../1958-to-alexander-macmillan-16.qmd)
- [Letter 1964](../1964-to-alexander-macmillan-33.qmd)
- [Letter 1967](../1967-alexander-macmillan-to-julian-bargus-yonge.qmd)
- [Letter 1969](../1969-alexander-macmillan-to-charlotte-mary-yonge-12.qmd)
- [Letter 1971](../1971-to-alexander-macmillan-17.qmd)
- [Letter 1973](../1973-to-alexander-macmillan-18.qmd)
- [Letter 1975](../1975-alexander-macmillan-to-charlotte-mary-yonge-13.qmd)
- [Letter 1976](../1976-to-alexander-macmillan-19.qmd)
- [Letter 1977](../1977-to-alexander-macmillan-20.qmd)
- [Letter 1978](../1978-to-alexander-macmillan-21.qmd)
- [Letter 1979](../1979-alexander-macmillan-to-charlotte-mary-yonge-14.qmd)
- [Letter 1981](../1981-to-alexander-macmillan-23.qmd)
- [Letter 1982](../1982-alexander-macmillan-to-charlotte-mary-yonge-15.qmd)
- [Letter 1984](../1984-to-alexander-macmillan-24.qmd)
- [Letter 1985](../1985-to-alexander-macmillan-25.qmd)
- [Letter 1987](../1987-alexander-macmillan-to-charlotte-mary-yonge-16.qmd)
- [Letter 1988](../1988-to-alexander-macmillan-26.qmd)
- [Letter 1993](../1993-to-alexander-macmillan-27.qmd)
- [Letter 1994](../1994-to-alexander-macmillan-28.qmd)
- [Letter 1995](../1995-to-alexander-macmillan-29.qmd)
- [Letter 1997](../1997-to-alexander-macmillan-30.qmd)
- [Letter 1998](../1998-to-alexander-macmillan-31.qmd)
- [Letter 1999](../1999-to-alexander-macmillan-32.qmd)
- [Letter 2002](../2002-alexander-macmillan-to-charlotte-mary-yonge-17.qmd)
- [Letter 2006](../2006-to-alexander-macmillan-34.qmd)
- [Letter 2008](../2008-to-alexander-macmillan-35.qmd)
- [Letter 2010](../2010-alexander-macmillan-to-charlotte-mary-yonge-19.qmd)
- [Letter 2012](../2012-to-alexander-macmillan-36.qmd)
- [Letter 2013](../2013-alexander-macmillan-to-charlotte-mary-yonge-20.qmd)
- [Letter 2014](../2014-to-alexander-macmillan-37.qmd)
- [Letter 2015](../2015-alexander-macmillan-to-charlotte-mary-yonge-21.qmd)
- [Letter 2016](../2016-alexander-macmillan-to-charlotte-mary-yonge-22.qmd)
- [Letter 2018](../2018-alexander-macmillan-to-charlotte-mary-yonge-23.qmd)
- [Letter 2019](../2019-to-alexander-macmillan-39.qmd)
- [Letter 2020](../2020-alexander-macmillan-to-charlotte-mary-yonge-24.qmd)
- [Letter 2021](../2021-to-alexander-macmillan-40.qmd)
- [Letter 2022](../2022-alexander-macmillan-to-charlotte-mary-yonge-25.qmd)
- [Letter 2026](../2026-to-alexander-macmillan-41.qmd)
- [Letter 2027](../2027-alexander-macmillan-to-charlotte-mary-yonge-26.qmd)
- [Letter 2028](../2028-to-alexander-macmillan-42.qmd)
- [Letter 2029](../2029-alexander-macmillan-to-charlotte-mary-yonge-27.qmd)
- [Letter 2030](../2030-to-alexander-macmillan-43.qmd)
- [Letter 2032](../2032-alexander-macmillan-to-charlotte-mary-yonge-28.qmd)
- [Letter 2033](../2033-alexander-macmillan-to-charlotte-mary-yonge-29.qmd)
- [Letter 2034](../2034-to-alexander-macmillan-44.qmd)
- [Letter 2035](../2035-alexander-macmillan-to-charlotte-mary-yonge-30.qmd)
- [Letter 2036](../2036-to-alexander-macmillan-45.qmd)
- [Letter 2039](../2039-to-alexander-macmillan-46.qmd)
- [Letter 2040](../2040-alexander-macmillan-to-charlotte-mary-yonge-32.qmd)
- [Letter 2041](../2041-to-alexander-macmillan-47.qmd)
- [Letter 2042](../2042-to-alexander-macmillan-48.qmd)
- [Letter 2043](../2043-alexander-macmillan-to-charlotte-mary-yonge-33.qmd)
- [Letter 2045](../2045-alexander-macmillan-to-charlotte-mary-yonge-34.qmd)
- [Letter 2047](../2047-to-alexander-macmillan-50.qmd)
- [Letter 2049](../2049-alexander-macmillan-to-charlotte-mary-yonge-35.qmd)
- [Letter 2050](../2050-to-alexander-macmillan-51.qmd)
- [Letter 2052](../2052-alexander-macmillan-to-charlotte-mary-yonge-37.qmd)
- [Letter 2053](../2053-alexander-macmillan-to-charlotte-mary-yonge-38.qmd)
- [Letter 2054](../2054-to-alexander-macmillan-52.qmd)
- [Letter 2055](../2055-to-alexander-macmillan-53.qmd)
- [Letter 2058](../2058-to-alexander-macmillan-54.qmd)
- [Letter 2060](../2060-alexander-macmillan-to-charlotte-mary-yonge-39.qmd)
- [Letter 2061](../2061-to-alexander-macmillan-55.qmd)
- [Letter 2064](../2064-alexander-macmillan-to-charlotte-mary-yonge-41.qmd)
- [Letter 2065](../2065-to-alexander-macmillan-56.qmd)
- [Letter 2068](../2068-alexander-macmillan-to-charlotte-mary-yonge-42.qmd)
- [Letter 2069](../2069-to-george-lillie-craik-2.qmd)
- [Letter 2072](../2072-alexander-macmillan-to-charlotte-mary-yonge-43.qmd)
- [Letter 2073](../2073-to-alexander-macmillan-57.qmd)
- [Letter 2074](../2074-to-alexander-macmillan-58.qmd)
- [Letter 2075](../2075-alexander-macmillan-to-charlotte-mary-yonge-44.qmd)
- [Letter 2076](../2076-to-alexander-macmillan-59.qmd)
- [Letter 2079](../2079-to-alexander-macmillan-60.qmd)
- [Letter 2080](../2080-to-alexander-macmillan-61.qmd)
- [Letter 2083](../2083-to-alexander-macmillan-62.qmd)
- [Letter 2084](../2084-to-alexander-macmillanm066-1865-12-08.qmd)
- [Letter 2085](../2085-to-alexander-macmillan-63.qmd)
- [Letter 2086](../2086-to-alexander-macmillan-64.qmd)
- [Letter 2087](../2087-to-alexander-macmillan-65.qmd)
- [Letter 2089](../2089-to-alexander-macmillan-66.qmd)
- [Letter 2095](../2095-to-alexander-macmillan-67.qmd)
- [Letter 2096](../2096-to-alexander-macmillan-68.qmd)
- [Letter 2100](../2100-to-alexander-macmillan-69.qmd)
- [Letter 2101](../2101-to-alexander-macmillan-70.qmd)
- [Letter 2103](../2103-to-alexander-macmillan-71.qmd)
- [Letter 2104](../2104-to-alexander-macmillan-72.qmd)
- [Letter 2108](../2108-to-alexander-macmillan-73.qmd)
- [Letter 2109](../2109-to-alexander-macmillan-74.qmd)
- [Letter 2118](../2118-to-alexander-macmillan-75.qmd)
- [Letter 2119](../2119-to-alexander-macmillan-76.qmd)
- [Letter 2121](../2121-to-alexander-macmillanm081-1866-04-26.qmd)
- [Letter 2128](../2128-to-alexander-macmillan-77.qmd)
- [Letter 2129](../2129-to-alexander-macmillan-78.qmd)
- [Letter 2133](../2133-to-alexander-macmillan-79.qmd)
- [Letter 2136](../2136-to-alexander-macmillan-80.qmd)
- [Letter 2137](../2137-to-alexander-macmillan-81.qmd)
- [Letter 2139](../2139-to-alexander-macmillan-82.qmd)
- [Letter 2144](../2144-to-alexander-macmillan-114.qmd)
- [Letter 2145](../2145-to-alexander-macmillan-83.qmd)
- [Letter 2146](../2146-to-alexander-macmillan-84.qmd)
- [Letter 2153](../2153-alexander-macmillan-to-charlotte-mary-yonge-45.qmd)
- [Letter 2156](../2156-to-alexander-macmillan-85.qmd)
- [Letter 2157](../2157-alexander-macmillan-to-charlotte-mary-yonge-46.qmd)
- [Letter 2159](../2159-frances-martin-to-alexander-macmillan-2.qmd)
- [Letter 2162](../2162-frances-martin-to-alexander-macmillan-3.qmd)
- [Letter 2165](../2165-frances-martin-to-alexander-macmillan-4.qmd)
- [Letter 2168](../2168-alexander-macmillan-to-charlotte-mary-yonge-47.qmd)
- [Letter 2170](../2170-alexander-macmillan-to-charlotte-mary-yonge-48.qmd)
- [Letter 2171](../2171-alexander-macmillan-to-charlotte-mary-yonge-49.qmd)
- [Letter 2172](../2172-alexander-macmillan-to-charlotte-mary-yonge-50.qmd)
- [Letter 2174](../2174-to-alexander-macmillan-86.qmd)
- [Letter 2175](../2175-alexander-macmillan-to-charlotte-mary-yonge-51.qmd)
- [Letter 2180](../2180-alexander-macmillan-to-charlotte-mary-yonge-52.qmd)
- [Letter 2181](../2181-to-alexander-macmillan-87.qmd)
- [Letter 2182](../2182-alexander-macmillan-to-charlotte-mary-yonge-53.qmd)
- [Letter 2183](../2183-to-alexander-macmillan-88.qmd)
- [Letter 2186](../2186-to-alexander-macmillan-89.qmd)
- [Letter 2188](../2188-to-alexander-macmillan-90.qmd)
- [Letter 2189](../2189-alexander-macmillan-to-charlotte-mary-yonge-54.qmd)
- [Letter 2191](../2191-alexander-macmillan-to-charlotte-mary-yonge-55.qmd)
- [Letter 2192](../2192-frances-martin-to-alexander-macmillan.qmd)
- [Letter 2193](../2193-to-alexander-macmillan-91.qmd)
- [Letter 2194](../2194-alexander-macmillan-to-charlotte-mary-yonge-56.qmd)
- [Letter 2196](../2196-alexander-macmillan-to-charlotte-mary-yonge-57.qmd)
- [Letter 2198](../2198-alexander-macmillan-to-charlotte-mary-yonge-58.qmd)
- [Letter 2199](../2199-alexander-macmillan-to-charlotte-mary-yonge-59.qmd)
- [Letter 2200](../2200-to-alexander-macmillan-92.qmd)
- [Letter 2213](../2213-to-alexander-macmillan-93.qmd)
- [Letter 2214](../2214-alexander-macmillan-to-charlotte-mary-yonge-60.qmd)
- [Letter 2216](../2216-alexander-macmillan-to-frances-martin.qmd)
- [Letter 2219](../2219-alexander-macmillan-to-charlotte-mary-yonge-61.qmd)
- [Letter 2226](../2226-alexander-macmillan-to-charlotte-mary-yonge-62.qmd)
- [Letter 2228](../2228-alexander-macmillan-to-charlotte-mary-yonge-63.qmd)
- [Letter 2229](../2229-alexander-macmillan-to-charlotte-mary-yonge-64.qmd)
- [Letter 2232](../2232-alexander-macmillan-to-charlotte-mary-yonge-65.qmd)
- [Letter 2233](../2233-alexander-macmillan-to-charlotte-mary-yonge-66.qmd)
- [Letter 2237](../2237-alexander-macmillan-to-charlotte-mary-yonge-69.qmd)
- [Letter 2238](../2238-alexander-macmillan-to-charlotte-mary-yonge-70.qmd)
- [Letter 2239](../2239-alexander-macmillan-to-charlotte-mary-yonge-71.qmd)
- [Letter 2241](../2241-alexander-macmillan-to-charlotte-mary-yonge-72.qmd)
- [Letter 2242](../2242-alexander-macmillan-to-charlotte-mary-yonge.qmd)
- [Letter 2243](../2243-to-alexander-macmillan-94.qmd)
- [Letter 2245](../2245-to-alexander-macmillan-95.qmd)
- [Letter 2246](../2246-to-alexander-macmillan-96.qmd)
- [Letter 2247](../2247-alexander-macmillan-to-charlotte-mary-yonge-73.qmd)
- [Letter 2248](../2248-to-alexander-macmillan-97.qmd)
- [Letter 2253](../2253-to-elizabeth-missing-sewell-8.qmd)
- [Letter 2254](../2254-alexander-macmillan-to-charlotte-mary-yonge-75.qmd)
- [Letter 2258](../2258-to-alexander-macmillan-98.qmd)
- [Letter 2269](../2269-to-alexander-macmillan-99.qmd)
- [Letter 2272](../2272-to-alexander-macmillan-100.qmd)
- [Letter 2278](../2278-to-alexander-macmillan-101.qmd)
- [Letter 2282](../2282-to-alexander-macmillan-102.qmd)
- [Letter 2283](../2283-to-alexander-macmillan-103.qmd)
- [Letter 2286](../2286-to-alexander-macmillan-104.qmd)
- [Letter 2292](../2292-to-alexander-macmillan-105.qmd)
- [Letter 2298](../2298-to-alexander-macmillan-106.qmd)
- [Letter 2308](../2308-to-alexander-macmillan-107.qmd)
- [Letter 2311](../2311-to-alexander-macmillan-108.qmd)
- [Letter 2313](../2313-to-alexander-macmillan-109.qmd)
- [Letter 2319](../2319-to-alexander-macmillan-110.qmd)
- [Letter 2345](../2345-to-alexander-macmillan-111.qmd)
- [Letter 2361](../2361-to-alexander-macmillan-112.qmd)
- [Letter 2363](../2363-to-alexander-macmillan-113.qmd)
- [Letter 2376](../2376-to-edward-augustus-freeman-2.qmd)
- [Letter 2380](../2380-to-alexander-macmillan-115.qmd)
- [Letter 2381](../2381-to-an-unknown-woman-or-to-alexander-macmillan.qmd)
- [Letter 2388](../2388-to-alexander-macmillan-116.qmd)
- [Letter 2396](../2396-to-alexander-macmillan-117.qmd)
- [Letter 2402](../2402-to-arthur-john-butler-12.qmd)
- [Letter 2406](../2406-to-elizabeth-missing-sewell-17.qmd)
- [Letter 2457](../2457-to-edward-augustus-freeman-6.qmd)
- [Letter 2486](../2486-to-alexander-macmillan-118.qmd)
- [Letter 2493](../2493-to-alexander-macmillan-119.qmd)
- [Letter 2494](../2494-to-alexander-macmillan-120.qmd)
- [Letter 2522](../2522-to-alexander-macmillan-121.qmd)
- [Letter 2578](../2578-to-alexander-macmillan-123.qmd)
- [Letter 2591](../2591-to-alexander-macmillan-124.qmd)
- [Letter 2594](../2594-to-alexander-macmillan-125.qmd)
- [Letter 2596](../2596-to-alexander-macmillan-126.qmd)
- [Letter 2597](../2597-to-alexander-macmillan-127.qmd)
- [Letter 2603](../2603-to-edward-augustus-freeman-11.qmd)
- [Letter 2609](../2609-to-alexander-macmillan-128.qmd)
- [Letter 2611](../2611-to-alexander-macmillan-129.qmd)
- [Letter 2612](../2612-to-elizabeth-wordsworth-11.qmd)
- [Letter 2632](../2632-to-alexander-macmillan-130.qmd)
- [Letter 2634](../2634-to-christabel-rose-coleridge-94.qmd)
- [Letter 2638](../2638-to-alexander-macmillan-131.qmd)
- [Letter 2649](../2649-to-alexander-macmillan-132.qmd)
- [Letter 2651](../2651-to-alexander-macmillan-133.qmd)
- [Letter 2657](../2657-to-alexander-macmillan-134.qmd)
- [Letter 2660](../2660-to-alexander-macmillan-135.qmd)
- [Letter 2676](../2676-to-alexander-macmillan-136.qmd)
- [Letter 2678](../2678-to-alexander-macmillan-137.qmd)
- [Letter 2679](../2679-to-alexander-macmillan-138.qmd)
- [Letter 2680](../2680-to-alexander-macmillan-139.qmd)
- [Letter 2681](../2681-to-alexander-macmillan-140.qmd)
- [Letter 2682](../2682-to-alexander-macmillan-141.qmd)
- [Letter 2684](../2684-to-alexander-macmillan-142.qmd)
- [Letter 2699](../2699-to-an-unknown-woman-50.qmd)
- [Letter 2703](../2703-to-an-unknown-woman-51.qmd)
- [Letter 2893](../2893-to-alexander-macmillan.qmd)
- [Letter 3218](../3218-to-john-athelstan-laurie-riley-2.qmd)
- [Letter 3554](../3554-to-alexander-macmillan-122.qmd)
- [Letter 19551](../19551-george-lillie-craik-to-charlotte-mary-yonge.qmd)
- [Letter 19572](../19572-alexander-macmillan-to-charlotte-mary-yonge.qmd)
- [Letter 19593](../19593-alexander-macmillan-to-charlotte-mary-yonge.qmd)
- [Letter 19637](../19637-alexander-macmillan-to-charlotte-mary-yonge.qmd)
- [Letter 19643](../19643-alexander-macmillan-to-charlotte-mary-yonge.qmd)
- [Letter 19651](../19651-alexander-macmillan-to-charlotte-mary-yonge.qmd)
- [Letter 19653](../19653-alexander-macmillan-to-charlotte-mary-yonge.qmd)
- [Letter 19655](../19655-alexander-macmillan-to-charlotte-mary-yonge.qmd)
- [Letter 19659](../19659-alexander-macmillan-to-charlotte-mary-yonge.qmd)
- [Letter 19661](../19661-alexander-macmillan-to-charlotte-mary-yonge.qmd)
- [Letter 19664](../19664-alexander-macmillan-to-charlotte-mary-yonge.qmd)
- [Letter 19667](../19667-alexander-macmillan-to-charlotte-mary-yonge.qmd)
- [Letter 19670](../19670-alexander-macmillan-to-charlotte-mary-yonge.qmd)
- [Letter 19672](../19672-alexander-macmillan-to-charlotte-mary-yonge.qmd)
- [Letter 19674](../19674-alexander-macmillan-to-charlotte-mary-yonge.qmd)
- [Letter 19676](../19676-alexander-macmillan-to-charlotte-mary-yonge.qmd)
- [Letter 19678](../19678-alexander-macmillan-to-charlotte-mary-yonge.qmd)

