---
title: "Margaret Helen (Moberly) Awdry"
person_id: 83
---

## Biographical Information

(May 1852-12 June 1939)

goddaughter of CMY

Youngest daughter of the Rt Rev George Moberly, she married (20 April 1876) Charles Awdry (1847-1912), whose brother William had earlier married her sister Emily.

## Letters Mentioning This Person

- [Letter 1889](../1889-to-margaret-helen-moberly-6.qmd)
- [Letter 1961](../1961-to-alice-arbuthnot-moberly.qmd)
- [Letter 2082](../2082-to-margaret-helen-moberly-7.qmd)
- [Letter 2203](../2203-to-margaret-helen-moberly.qmd)
- [Letter 2543](../2543-to-augusta-boevey-pode-4.qmd)
- [Letter 2990](../2990-to-the-reverend-dr-george-moberly.qmd)
- [Letter 2995](../2995-to-elizabeth-roberts-15.qmd)
- [Letter 3041](../3041-to-jemima-blackburn-2.qmd)
- [Letter 3044](../3044-frances-mary-yonge-to-alice-arbuthnot-moberly-2.qmd)
- [Letter 3048](../3048-to-mary-anne-dyson-19.qmd)
- [Letter 3062](../3062-to-anne-yonge-34.qmd)
- [Letter 3075](../3075-to-margaret-helen-moberly-2.qmd)
- [Letter 3145](../3145-to-margaret-helen-moberly-3.qmd)
- [Letter 3489](../3489-to-margaret-helen-moberly-4.qmd)
- [Letter 3490](../3490-to-margaret-helen-moberly-5.qmd)

