---
title: "Margaret Eliza Roberts"
person_id: 1244
---

## Biographical Information

(1833-1919 Montreux)

author of <i>Mademoiselle Mori</i>

She was educated by her stepfather, the Rev. Henry Latham (1794-1866 ODNB);  she was a contributor to <i>MP</i> (1864-92).  Her most successful work was  <i>Mademoiselle Mori:  A Tale of Modern Rome</i> (1860), which CMY encouraged Parker to print;  she published as ‘the author of <i>Mademoiselle</i> Mori’.  CMY had a  plan to co-author German history with her; she suffered a strain of the hip in 1873; and lived in Torquay.  She has titles in the <i>British Library Catalogue</i> 1857-1901.  A letter in the Bodleian from Roberts to Bullock calls Grace Latham her cousin, and perhaps there was a blood relationship with some of the Lathams. (ODNB; Blain, <i>Feminist Companion</i>;  Mary Harris, <i>Frances Mary Peard</i> says she died at Territet]

## Letters Mentioning This Person

- [Letter 1781](../1781-to-john-william-parker-jr-8.qmd)
- [Letter 1783](../1783-to-john-william-parker-jr.qmd)
- [Letter 1786](../1786-to-john-william-parker-jr-9.qmd)
- [Letter 1793](../1793-to-john-william-parker-jr-10.qmd)
- [Letter 1804](../1804-to-susanna-warren-2.qmd)
- [Letter 1934](../1934-to-frances-mary-peard-8.qmd)
- [Letter 2104](../2104-to-alexander-macmillan-72.qmd)
- [Letter 2106](../2106-to-elizabeth-missing-sewell-6.qmd)
- [Letter 2124](../2124-to-charles-lutwidge-dodgson.qmd)
- [Letter 2203](../2203-to-margaret-helen-moberly.qmd)
- [Letter 2249](../2249-to-edith-sophia-jacob-12.qmd)
- [Letter 2410](../2410-to-edith-sophia-jacob-19.qmd)
- [Letter 2412](../2412-to-edith-sophia-jacob-20.qmd)
- [Letter 2446](../2446-to-mary-anne-dyson-22.qmd)
- [Letter 2455](../2455-to-edward-augustus-freeman-4.qmd)
- [Letter 2456](../2456-to-edward-augustus-freeman-5.qmd)
- [Letter 2478](../2478-to-gertrude-louisa-legrand-jacob.qmd)
- [Letter 2515](../2515-to-elizabeth-wordsworth-7.qmd)
- [Letter 2570](../2570-to-christabel-rose-coleridge-85.qmd)
- [Letter 2733](../2733-to-christabel-rose-coleridge-104.qmd)
- [Letter 2845](../2845-to-elizabeth-barnett-19.qmd)
- [Letter 2891](../2891-to-miss-kirke.qmd)
- [Letter 3139](../3139-to-john-william-parker-jr-7.qmd)
- [Letter 3201](../3201-to-arthur-john-butler-7.qmd)
- [Letter 3394](../3394-to-sir-walter-besant-2.qmd)
- [Letter 3422](../3422-to-christabel-rose-coleridge-32.qmd)
- [Letter 3479](../3479-to-christabel-rose-coleridge-58.qmd)
- [Letter 19905](../19905-to-john-william-parker-jr.qmd)

