---
title: "Mary Anne Dyson"
person_id: 464
---

## Biographical Information

(28 March 1809-29 Sept 1878)

writer and schoolmistress

Life-long friend of CMY, she lived with her much older half-brother, the Rev. Charles Dyson, Rector of Dogmersfield, until his death in 1860, and latterly at Church Crookham.  Her will was proved by her nephew the Rev Francis Dyson, estate under £10,000. She was an invalid ‘confined her to a sofa and latterly even to her bed’ ; author of <i>Conversations with Cousin Rachel, Little Alice and her Sister, The White Kitten, Out in the Dark, Ivo and Verena</i>, [wills index, obit <i>MP</i> (1878, 2, 521-5]

## Letters Mentioning This Person

- [Letter 1791](../1791-to-anne-sturges-bourne-4.qmd)
- [Letter 1792](../1792-to-anne-sturges-bourne-5.qmd)
- [Letter 1795](../1795-to-miss-erskine-2.qmd)
- [Letter 1817](../1817-to-anne-sturges-bourne-6.qmd)
- [Letter 1818](../1818-to-anne-sturges-bourne-7.qmd)
- [Letter 1956](../1956-to-messrs-macmillan-3.qmd)
- [Letter 2004](../2004-to-elizabeth-missing-sewell-4.qmd)
- [Letter 2144](../2144-to-alexander-macmillan-114.qmd)
- [Letter 2203](../2203-to-margaret-helen-moberly.qmd)
- [Letter 2208](../2208-to-mary-ann-dyson-4.qmd)
- [Letter 2215](../2215-to-mary-ann-dyson-5.qmd)
- [Letter 2267](../2267-to-christabel-rose-coleridge-17.qmd)
- [Letter 2268](../2268-to-edith-sophia-jacob-16.qmd)
- [Letter 2271](../2271-to-mary-ann-dyson-6.qmd)
- [Letter 2275](../2275-to-mary-ann-dyson-7.qmd)
- [Letter 2293](../2293-to-mary-anne-moberly-5.qmd)
- [Letter 2300](../2300-to-mary-ann-dyson-8.qmd)
- [Letter 2317](../2317-to-mary-ann-dyson-9.qmd)
- [Letter 2328](../2328-to-mary-ann-dyson-10.qmd)
- [Letter 2329](../2329-to-mary-ann-dyson-11.qmd)
- [Letter 2330](../2330-to-mary-ann-dyson-2.qmd)
- [Letter 2331](../2331-to-mary-ann-dyson-12.qmd)
- [Letter 2332](../2332-to-mary-anne-dyson-13-2.qmd)
- [Letter 2333](../2333-to-mary-anne-dyson-10-3.qmd)
- [Letter 2334](../2334-to-mary-ann-dyson-10.qmd)
- [Letter 2335](../2335-to-mary-ann-dyson-12.qmd)
- [Letter 2348](../2348-to-edith-sophia-jacob-18.qmd)
- [Letter 2360](../2360-to-mary-anne-dyson-20.qmd)
- [Letter 2364](../2364-to-mary-yonge-34.qmd)
- [Letter 2401](../2401-to-elizabeth-missing-sewell-16.qmd)
- [Letter 2429](../2429-to-mary-anne-dyson-21.qmd)
- [Letter 2439](../2439-to-charlotte-cordelia-yonge.qmd)
- [Letter 2442](../2442-to-sir-william-heathcote-bt-6.qmd)
- [Letter 2443](../2443-to-sir-william-heathcote-bt-7.qmd)
- [Letter 2446](../2446-to-mary-anne-dyson-22.qmd)
- [Letter 2480](../2480-to-harriet-poole-2.qmd)
- [Letter 2499](../2499-to-mary-anne-dyson-23.qmd)
- [Letter 2525](../2525-to-mary-anne-dyson.qmd)
- [Letter 2561](../2561-to-mary-yonge-48.qmd)
- [Letter 2641](../2641-to-elizabeth-barnett-17.qmd)
- [Letter 2644](../2644-to-florence-wilford-8.qmd)
- [Letter 2645](../2645-to-mrs-curteis.qmd)
- [Letter 2926](../2926-to-elizabeth-barnett-24.qmd)
- [Letter 2958](../2958-to-mary-anne-dyson-2.qmd)
- [Letter 2960](../2960-to-mary-anne-dyson-3.qmd)
- [Letter 2962](../2962-frances-mary-yonge-to-mary-anne-dyson.qmd)
- [Letter 2963](../2963-to-mary-anne-dyson-4.qmd)
- [Letter 2964](../2964-to-mary-anne-dyson-5.qmd)
- [Letter 2966](../2966-to-mary-anne-dyson-6.qmd)
- [Letter 2967](../2967-to-mary-anne-dyson-7.qmd)
- [Letter 2968](../2968-to-mary-anne-dyson-8.qmd)
- [Letter 2969](../2969-to-mary-anne-dyson-9.qmd)
- [Letter 2970](../2970-to-mary-anne-dyson-10.qmd)
- [Letter 2971](../2971-to-mary-anne-dyson-11.qmd)
- [Letter 2972](../2972-to-mary-anne-dyson-12.qmd)
- [Letter 3006](../3006-to-mary-anne-dyson-13.qmd)
- [Letter 3007](../3007-to-mary-anne-dyson-14.qmd)
- [Letter 3018](../3018-to-elizabeth-roberts-29.qmd)
- [Letter 3019](../3019-to-mary-anne-dyson-15.qmd)
- [Letter 3020](../3020-to-elizabeth-barnett-4.qmd)
- [Letter 3028](../3028-to-mary-anne-dyson-16.qmd)
- [Letter 3029](../3029-to-mary-anne-dyson-17.qmd)
- [Letter 3030](../3030-to-mary-anne-dyson-18.qmd)
- [Letter 3048](../3048-to-mary-anne-dyson-19.qmd)
- [Letter 3061](../3061-to-anne-yonge-33.qmd)
- [Letter 3082](../3082-to-anna-butler-9.qmd)
- [Letter 3087](../3087-to-anne-sturges-bourne-2.qmd)
- [Letter 3097](../3097-sir-william-heathcote-to-caroline-elizabeth-heathcote.qmd)
- [Letter 3115](../3115-to-anna-butler-17.qmd)
- [Letter 3147](../3147-to-elizabeth-barnett-13.qmd)
- [Letter 3231](../3231-to-the-very-reverend-george-david-boyle.qmd)
- [Letter 3333](../3333-to-mary-elizabeth-christie-2.qmd)
- [Letter 3405](../3405-to-penelope-packe-2.qmd)
- [Letter 7883](../7883-to-john-duke-coleridge.qmd)
- [Letter 19394](../19394-to-mary-anne-dyson.qmd)

