---
title: "Charles Wooldridge"
person_id: 2094
---

## Biographical Information

(1832/3-1913)

solicitor

<i>The Times</i> (4 December 1913), 6, refers to his 32-year tenure of the office of Diocesan Registrar for Winchester.





He married (1856) Margaret Sophia Bromley (1834/5-1888).

## Letters Mentioning This Person

- [Letter 3283](../3283-charles-wooldridge-to-charlotte-mary-yonge-3.qmd)
- [Letter 3289](../3289-charles-wooldridge-to-charlotte-mary-yonge-4.qmd)
- [Letter 3290](../3290-to-charles-wooldridge-2.qmd)
- [Letter 3291](../3291-charles-wooldridge-to-charlotte-mary-yonge-5.qmd)
- [Letter 3292](../3292-to-charles-wooldridge-3.qmd)
- [Letter 3293](../3293-charles-wooldridge-to-charlotte-mary-yonge-6.qmd)
- [Letter 3294](../3294-to-charles-wooldridge-4.qmd)
- [Letter 3296](../3296-charles-wooldridge-to-charlotte-mary-yonge-7.qmd)
- [Letter 3297](../3297-charles-wooldridge-to-charlotte-mary-yonge-8.qmd)
- [Letter 3299](../3299-charles-wooldridge-to-charlotte-mary-yonge-9.qmd)
- [Letter 3306](../3306-charles-wooldridge-to-charlotte-mary-yonge-10.qmd)
- [Letter 3307](../3307-to-charles-wooldridge-5.qmd)
- [Letter 3309](../3309-to-charles-wooldridge-6.qmd)
- [Letter 3310](../3310-charles-wooldridge-to-charlotte-mary-yonge-2.qmd)
- [Letter 3311](../3311-to-charles-wooldridge-7.qmd)
- [Letter 3312](../3312-charles-wooldridge-to-charlotte-mary-yonge-11.qmd)
- [Letter 3313](../3313-to-charles-wooldridge.qmd)
- [Letter 3318](../3318-charles-wooldridge-to-charlotte-mary-yonge-12.qmd)

