---
title: "Anna Maria Keary"
person_id: 793
---

## Biographical Information

(3 March 1825-March 1879)

writer,  contributor to <i>MP</i> (1865-76)

Sixth child of the Rev. William Keary, Rector of Bilton, perpetual curate of Sailcoates, and rector of Nunnington. Her mother was daughter of Hall Plumer of Bilston Hall, brother of Sir Thomas Hall Plumer. She and her sister Eliza went to live in Addison Road 1854, later in Bedford Gardens.  She worked in a children's hospital and was rather deaf. They seem to have been related to the Johns family. IIn 1873 she seems to have taken part in the essay-writing part of the Gosling Society, but if she had a sobriquet it is not known.  [Eliza Keary <i>Memoir of Annie Keary</i>;Vital records index for death]

## Letters Mentioning This Person

- [Letter 1984](../1984-to-alexander-macmillan-24.qmd)
- [Letter 1989](../1989-to-ellen-julia-johns-5.qmd)
- [Letter 2006](../2006-to-alexander-macmillan-34.qmd)
- [Letter 2007](../2007-alexander-macmillan-to-charlotte-mary-yonge-18.qmd)
- [Letter 2008](../2008-to-alexander-macmillan-35.qmd)
- [Letter 2013](../2013-alexander-macmillan-to-charlotte-mary-yonge-20.qmd)
- [Letter 2103](../2103-to-alexander-macmillan-71.qmd)
- [Letter 2121](../2121-to-alexander-macmillanm081-1866-04-26.qmd)
- [Letter 2125](../2125-to-anna-maria-keary.qmd)
- [Letter 2201](../2201-to-christabel-rose-coleridge-12.qmd)
- [Letter 2419](../2419-to-christabel-rose-coleridge-67.qmd)
- [Letter 2421](../2421-to-christabel-rose-coleridge-68.qmd)
- [Letter 2475](../2475-to-christabel-rose-coleridge-79.qmd)
- [Letter 2575](../2575-to-miss-kekewich.qmd)
- [Letter 3484](../3484-to-ellen-julia-johns-2.qmd)
- [Letter 19875](../19875-to-anna-maria-keary.qmd)

