---
title: "Katherine Olive Helmore"
person_id: 675
---

## Biographical Information

(1844/5-1923)

member of the Gosling Society

She was daughter of the Rev. Thomas Helmore (1811-1890), Precentor of St. Mark's College Chelsea and master of the choristers of the Chapel Royal, and his wife Kate Wilson Pridham (1816/7-1886), sister of Mrs Derwent Coleridge.  She was a Gosling as ‘Cobweb’. [1881 census, will index;  Frederick Helmore <i>T. Helmore</i>]

## Letters Mentioning This Person

- [Letter 1819](../1819-to-katharine-olive-helmore-2.qmd)
- [Letter 1825](../1825-to-katharine-olive-helmore-3.qmd)
- [Letter 1849](../1849-to-katharine-olive-helmore-4.qmd)
- [Letter 1850](../1850-to-katharine-olive-helmore-5.qmd)
- [Letter 1851](../1851-to-henrietta-elizabeth-fursdon-4.qmd)
- [Letter 1853](../1853-to-katharine-olive-helmore-6.qmd)
- [Letter 1855](../1855-to-christabel-rose-coleridge-4.qmd)
- [Letter 1995](../1995-to-alexander-macmillan-29.qmd)
- [Letter 2023](../2023-to-katharine-olive-helmore-7.qmd)
- [Letter 2070](../2070-to-katharine-olive-helmore-8.qmd)
- [Letter 2078](../2078-to-christabel-rose-coleridge-7.qmd)
- [Letter 2107](../2107-to-katharine-olive-helmore.qmd)

