---
title: "Letters 1834-1849"
listing: false
decade_label: "1834-1849"
post_id: 3733
letter_id: "letters-1834-1849"
---

**INTRODUCTION TO LETTERS 1836-1849**

Charlotte Yonge was the elder child of William Crawley Yonge (1795-1854), an army officer who had retired on his marriage to Frances Mary Bargus (1795-1868), at the insistence of his wife’s mother, to live on a small landed property near Winchester which was her inheritance.  Charlotte had a younger brother, Julian Bargus Yonge (1830-1891).[1] Her parents were unrelated to one another, though their families were connected by a dense web of marriages with such intricacy that attempts to explain in prose are hopeless and a family tree is indispensable. Both parents were the children of clergymen of the Church of England.  That fact in itself does not explain, however, the intense and peculiar religious atmosphere in which she was brought up.

The parish of Otterbourne was joined to the neighbouring parish of Hursley, where the principal landowner was a serious young man named Sir William Heathcote, Bt. (1801-1881).  As an undergraduate at Oxford he had come under the influence of the Rev. John Keble (1792-1866), a scholar and theologian who had written a bestselling volume of poetry, *The Christian Year: Thoughts in Verse for the Sundays and Holydays Throughout the Year *(1827), and whose sermon in July 1833 denouncing state control of the Church of England was held by Newman to be the real start of the Oxford Movement.[2]* *In 1836 Heathcote succeeded, after several attempts, in securing Keble as Vicar of Hursley and Rector of Otterbourne.   This was to be one of the decisive events of Charlotte Yonge’s life.  Keble and Heathcote found in William Crawley Yonge an enthusiastic supporter of their efforts to reform the parishes and modernize their ecclesiastical and educational arrangements.  Their close alliance also included the curate in charge of Otterbourne, the Rev. William Bigg Wither, who was Heathcote’s cousin, and several other Hursley curates, especially the Rev. Peter Young, who was married to Keble’s adopted daughter, and the Rev. Robert Wilson, who was married to Heathcote’s niece.[3] These were the years in which the Tractarian or Oxford Movement (or, as its adherents called it, if they called it anything, the Church Movement) was defining itself as a High Church group within the Church of England emphasising continuity with the pre-Reformation Catholic Church.  Where evangelicals conceived of the individual’s relationship with God as the main locus of spiritual life, the Tractarians saw it in the public and collective church:

Christ’s Holy Catholic Church is a real outward visible body, having supernatural grace continually communicated through it by succession from the Apostles, in whose place the bishops are.[4]

Keble was widely recognised as the movement’s leader. He was reverenced by his followers, and, though he lived the quiet life of a country clergyman, he actively participated in almost all of the savagely fought religious controversies of the period.  He held an exalted view of the place of the clergyman in society: ‘the deputy of CHRIST, for reducing man to obedience of God’[5]; in the context of a few small villages, with the secular power concentrated in the hands of a few sympathetic landowners, it was possible to attempt to carry this ideal into practice, and this is what he proceeded to do during Yonge’s childhood and under her eyes, in a way that permanently affected her view of the world.

For the early Tractarians, the rural parish was a site of powerful significance for the expression of the ideal relations between church and state, individual and society, class and class (even though in fact as the movement developed many of its great successes took place in industrial parishes and in seaside resorts such as Bournemouth and Torquay).[6] The parish of Hursley with Otterbourne was one of many English rural parishes of the 1830s and 1840s in which a social experiment was carried out at considerable expense, with elaborate pains, in the mingled causes of education, religious revival, political repression and moral reform, from a variety of motives including fear of revolution, class guilt, altruism, religious devotion, anxiety about industrialization, nostalgic mediaevalism and enthusiasm for the works of Wordsworth and Sir Walter Scott.   England is scattered with brick schools for girls, boys and infants built in these years under the aegis of the National Society;  clergymen throughout the land, evangelical as well as Tractarian, were doing away with box pews, reviving daily services, and introducing Sunday Schools; the work done at Hursley resembled that done at Newton Ferrars by Yonge’s uncle John, at Bisley, Gloucestershire, by Keble’s brother, and by many others elsewhere; and in all these places eager girls like Charlotte Yonge were visiting cottages, teaching Sunday school, saving their pocket money for missions and church building, embroidering vestments and footstools and  making articles for innumerable fund-raising bazaars.  Hursley with Otterbourne, however, was held by many to be the perfect example of the form, ‘a beacon for those in search of the Tractarian message’[7]:  a parish in which landowner and clergyman were equally devoted to the cause, ‘the Church and the secular power working together in an almost ideal way,’[8] a place in which and from which it might be possible to change the world.  Keble’s reputation, and other factors, meant that it was celebrated and influential in a way quite incommensurate with its size.  It was within walking distance of a cathedral city and a major public school, between them employing numerous clergy, and easily reached by railway, so that it was much visited by Keble’s admirers; yet it was far enough away from any industrial centre that, at any rate in the early years, the landowners and the vicar could still dominate the population.  Quiet as Otterbourne was, Yonge was thus in some ways living at the centre of a series of events whose ultimate consequences were dramatic and far-reaching.[9]

This is not to imply either that the Hampshire village of the 1840s was a rural idyll, or that all the work of the Tractarians was undertaken with the full support and encouragement of the authorities and the local elite.  This educational and religious work took place during a time of agricultural depression and political unrest, and was made urgent by the fear of social revolution.  Hampshire now, with its prosperous-looking cottages full of rosy-cheeked stockbrokers commuting to London, has some of the prettiest villages and most expensive property in England (and some places, such as Otterbourne, which have been ruined by the motor car).  But rural Hampshire in the 1830s and 1840s was a place of cruel poverty for the vast majority of its population, who were mainly illiterate agricultural labourers, men, women and children.  In 1830/1 there was an uprising, known as the Captain Swing riots, in large parts of the south of England, especially in Wiltshire and Hampshire, in protest at low wages and the introduction of the new labour-saving threshing machines, which meant the loss of winter work to many starving families.  Charlotte Yonge, aged seven, was in Devon during the week in November 1830 when Hampshire was convulsed, but nonetheless the rising came very close to her.[10] At Hursley Park the Heathcote children were locked in the strong room when the labourers came and demanded money; although the worst rioting was in the north of the county many local landowners would have had similar stories. But, above all, two brothers of her own nurse Maria Mason were among those convicted by the Special Commission of 1831; members of a Radical and Musical Society in Sutton Scotney, they were considered particularly dangerous as rather better-educated and better-off than other participants:  being literate, they had helped circulate radical ideas by reading newspapers to others. They were given death sentences, commuted to transportation to Australia, from whence the elder, Joseph Mason (1799-1863) sent his grieving sister a series of detailed letters with descriptions of the country which enlivened Yonge’s childhood.  In her various memoirs she tends to gloss over this episode, emphasising that her aged grandmother, alone at Otterbourne House, was left in peace, but the riots made enough impression on her for her to fictionalize them in *My Young Alcides* (1875) and *The Carbonels *(1895).  Certainly the reaction of the government was instantaneous and draconian. The Heathcote/Keble/Yonge project to create a harmonious Christian community in Hursley and Otterbourne, in which religious and political authority were united and from which dissenting voices were as far as possible excluded or suppressed, took place against this background.[11] There were no Radical and Musical Societies in Hursley.

Yet despite the fact that much Tractarian activity was politically conservative, designed among other things to conciliate class conflict and promote social deference, it was a minority movement which was widely opposed both within the hierarchy of Church of England and by other members of the ruling class.  Some of the opposition came from those opponents of the established church (including dissenters) who deplored its stranglehold on education and public life.  Many political liberals, allied with the merchant interest, could not understand why the mediaeval Church, or the early Christian church, should be a model for a modern Church of England. There was also a visceral fear of Tractarianism’s Romanizing tendencies among large sections of the gentry and clergy.  The passing of the Catholic Emancipation Act and the repeal of the Test and Corporation Acts had only recently, in the late 1820s,  made it possible for non-Anglican Christians to hold public office, and this development was still widely opposed within the Church of England (including, of course, by the Tractarians). Many features of Tractarian thinking on such subjects as the mediaeval church, sacerdotalism, confession, asceticism, ritualism, symbolism, mysticism, church decoration, church architecture, celibacy and sisterhoods seemed to their contemporaries infallible signs of imminent conversion to Rome; an impression which was only confirmed by the secession of a large number of prominent Anglicans, of both sexes, lay and clerical,  between 1844 and 1850, of whom Newman and Manning are merely the best-known.  Though the Rev. Edward Bouverie Pusey was the main bogeyman of the anti-Tractarians, to whom the very word ‘Puseyite’ was a weapon, Keble too was a deeply controversial figure.  Yonge often repeated the story of how the Rev. Robert Wilson was advised by a sympathetic friend not to become one of Keble’s curates: ‘Now remember if you become Keble’s curate, you will lose all chance of preferment for life’.[12] R. W. Church, looking back on the situation of the Tractarian clergy in the 1840s, wrote that after Newman’s conversion ‘there was a badge affixed to them, and all who belonged to them, a badge of suspicion and discredit, and even shame, which made men beware of them.’[13] In 1841 the Rev. Peter Young, curate of Hursley, who has already been mentioned as husband of Keble’s adopted daughter, was refused a title to orders by the Bishop of Winchester, the Rt. Rev. Charles Sumner, for his suspiciously Popish views on the doctrine of the Real Presence; he was to remain a deacon for 15 years, unable to celebrate Holy Communion.[14] For all their devotion to the authority of the Church and their belief in the Apostolic Succession, many Tractarians chafed under the discipline of their bishops, and Bishop Sumner, so nearby and so powerful, was no friend to Keble and his party.

It made a great difference that the devotion to the authority of her parish priest and the prejudices of her family which marked Yonge all her life was nurtured in a period in which they were all participants in a much reviled extremist movement. As her first biographer drily observed, in her case the naturally rebellious feelings of youth were poured out in a cause in which all her teachers and associates were engaged:

She had those greatest joys of high-minded and enthusiastic youth, hero-worship, and the sense of being in the van of one of the great movements of the day; but whereas in many cases young people buy these joys by discord with their elders and by severance from home interests, in Charlotte’s case authority, family ties, faculty and aspiration all flowed in the same full and powerful stream, and for her the newest *youngest* thing was to do home and family duties more perfectly.   . . The fact was the keynote of her character, and produced that atmosphere of mingled ardour and submission in which she lived all her life.[15]

Her ardour for reform was channelled, remarkably soon,  into the work of fund-raising and propaganda;  from the age of fifteen she was writing educational fiction designed to suit Tractarian purposes, work which she continued for more than sixty years.

Questions of education, for all classes, were a central preoccupation for the Hursley authorities, who included another very important influence on Charlotte Yonge, the Rev. George Moberly, headmaster of Winchester College, who in about 1839 rented a farmhouse from Heathcote for his enormous family to spend holidays in. [16] He shared many scholarly interests with Keble, including his concern with the question of how moral training and higher education could best be combined.  Thus the brilliant girl at Otterbourne House, though she never went to school, had plenty of the company of professional educationists.  It is impossible to conclude that Charlotte Yonge was anything other than extremely well-educated.    Though her younger brother had the advantage of the best education money could buy, first at Eton and then at Balliol College, Oxford, Yonge was educated at home, mainly by her father.  But her unusual intellectual abilities seem to have been early recognised and encouraged by her family and friends:  she learnt Latin and mathematics from her father, she had lessons in French and Spanish from an émigré, and also, perhaps at a slightly later date, learnt Italian, German, Greek and Hebrew; she was also learned in botany and conchology, and had some knowledge of astronomy. Her mother, whose own abilities she held in high respect, taught her drawing.  It is likely that she drew on Keble’s help in her study of Greek and Hebrew; and that she had access not only to his library but to those of Heathcote and Moberly.[17] She seems to have been encouraged to read very widely, especially in history, and like most of her generation, she had an inordinate admiration for the prose and poetry of Walter Scott.  She was not musical.

Although deference to her elders was a pronounced feature of her character, her early life also included many important relationships with contemporaries.  The 15 Moberly children, all younger than Charlotte Yonge, played a large part in her life, and their presence nearby helped to bring about the preoccupation with the internal dynamics of very large families which is so characteristic of her fiction.  One could argue that she is the only novelist really to have overcome the technical difficulties involved in exploring the subject. This enthusiasm of hers was also fostered by some cousins of her own age, the ten children born to her mother’s elder half-sister, Alethea Bargus, and the head of her father’s family, the Rev. John Yonge of Puslinch.   At Puslinch, near Yealmpton in the south-west corner of Devon, where the Otterbourne Yonges made summer visits, she found an atmosphere totally different from the rather repressive life at home.  Her father’s cousin John was both squire and parson and no less pious than her own parents, but the house was full of children and there were dozens of other relations nearby.  These included two of her father’s brothers, the Rev. Duke Yonge, Vicar of Antony, and Dr James Yonge, a physician in Plymouth, confidential in dozens of county families and busy in Tory politics.  Another was a man of more than local importance and fame, her mother’s stepbrother, General Sir John Colborne, a Waterloo hero, who was created Lord Seaton in 1839 on return from Canada where he had commanded the army, and subsequently became governor of the Ionian Islands.[18] All had children near her own age. Back at Otterbourne, relations with these cousins were kept up by means of a copious correspondence, especially with her favourite, Anne Yonge, of Puslinch.

Another group of Devon cousins were the Coleridges, at Ottery St. Mary in East Devon, who were connected to the Puslinch Yonges by their common descent from the Duke family.[19] Sir John Taylor Coleridge, and his brother-in-law and fellow lawyer Sir John Patteson, who both lived between London and east Devon, both had children who became  life-long friends to Charlotte Yonge.  Sir John Coleridge’s children were John Duke Coleridge, the future Lord Chancellor, the Rev. Henry Coleridge and two daughters, Mary and Alethea. They too were knit closely in the weave of the Tractarian movement; a devoted friend of Keble, Coleridge supported him in many different fields, including personal finance, for years, and was chosen as his first biographer. This household was also a more broad-minded, metropolitan, sophisticated and politically liberal one than most of those Yonge visited, which makes it especially regrettable that there are not more letters recording this friendship.[20] It is not clear that Yonge knew the Pattesons well before she grew up, but her correspondence with her missionary cousin John Coleridge Patteson, who became Bishop of Melanesia, was to be one of the great pleasures of her middle years.

As well as Moberly’s pupils from Winchester College, including several of the Puslinch Yonges, who were invited out on school holidays to Otterbourne House, Yonge would have seen a good deal of Sir William’s schoolboy sons, and the upper-class pupils taught by Keble’s curates, all of whom were receiving an advanced education in Latin and Greek literature.  But it was not this aspect of education, important as it undoubtedly was to most of the people she knew, which fills her correspondence:  there is much more about the elementary education of the poor.  The 1830s and 1840s, which saw the publication of Yonge’s first fiction, were a time of widespread campaigning for the improvement of the education of the working classes, motivated less by a belief in education for its own sake than by the belief that literacy would promote Christianity.[21] Her earliest letters are full of the project to set up schools for the children of Otterbourne; like many other such schools these were soon assisted by the work of the National Society for Promoting the Education of the Poor in the Principles of the Established Church.[22] This charity was a lifelong enthusiasm of Yonge’s: her first book, published in 1839 when she was 15, was to raise money for the Otterbourne National School, and the Society’s imprint is also on two novels of hers dated 1900.  This interest was shared by almost all her close friends and associates.   When she was in her early twenties she met Mary Anne Dyson (1809-1878), invalid sister of the Rev. Charles Dyson, Rector of Dogmersfield, Hampshire, a village some twenty miles away from Winchester, who herself published some Tractarian fiction for children.  The Dysons were on terms of close friendship with the Kebles, the Moberlys, the Coleridges, the Mannings and the Wilberforces.[23] John Duke Coleridge,  who had spent many childhood holidays at Dogmersfield, wrote in an obituary of Mary Anne that she was ‘a person of rare gifts;  a character at once noble and beautiful;  her life was a constant and inspiring lesson to those who knew her’ and that what you remembered about the Dysons was ‘the simple goodness, the utter unworldliness, it is not too strong to say the holiness, of all three.’[24] However, the impression one gets of her dealings with Yonge is rather that, despite spending her life mainly on the sofa, she was a person of great force of character and determination: not for nothing Yonge nicknamed her ‘Driver,’ meaning slavedriver.  She was convinced that an unmarried woman with enough money, such as herself, had work to do in the world, and decided to set up a small school for middle-class girls,  those who were neither ladies nor servants, which she ran for many years until she was too ill to continue.  Looking back on this friendship after Dyson’s death, Yonge commented ‘I don’t know any one I owe so much to after my Father and Mother and Mr. Keble.’[25] The surviving letters Yonge wrote her vividly convey how well they agreed together, and how much they enjoyed their joint efforts in the common cause, and their discussions of literature and history, in which Charles and Elizabeth Dyson and Yonge’s parents, also took part.  Together they debated the role of the spinster lady in society, and there is no doubt that Dyson’s example, as a single woman who had found a means of doing useful work, was a powerful influence on Yonge. [26]

It seems that by about the time she first met Dyson in 1843 Yonge had finished her first full-length novel, *Abbeychurch* (1844), which was recommended by Keble to Mozley and Son, the Derby family printing firm of his friends the Rev. James Mozley and the Rev. Thomas Mozley, and was published by them in collaboration with James Burns, a London bookseller with a Tractarian connection.[27] It is the story of a young girl’s moral education in a lively bookish family, and, as Yonge acknowledged, it followed the example of some books for rather younger children written by another Tractarian insider, Harriett (Newman) Mozley: *The Fairy Bower* (1841) and *The Lost Brooch *(1841).  *Abbeychurch* already possesses some of the vivid characterization and lively dialogue of her better-known novels, but, as she came to feel herself, there is a moral rigidity which is absent from, or better-concealed in, the works of the following decade.[28] At about the same time as it came out, Yonge also began to write for Dyson’s girl pupils, and shortly afterwards to contribute fiction and other articles to the* Magazine for the Young*, a children’s publication, started in 1842 by Dyson and her brother and published by Burns*.*[29] *Abbeychurch* is addressed to teenage or adult readers of the educated upper middle-class, as was  *Scenes and Characters, or, Eighteen Months at Beechcroft *(1847), a novel in which Yonge revisited the characters originally imagined in *Le Château de Melville. *But several other early works were aimed at quite different audiences.   Two stories, *Midsummer Day, or, The Two Churches *(1847?)  and *Harriet and her Sister* (1848), were published by Burns and then by Mozley among their series of tuppenny reward books for schoolchildren. The *Langley School *stories, first published in the *Magazine for the Young*, which were based on Yonge’s own experiences teaching Sunday School in Otterbourne, were addressed to working-class children like the characters.[30] *Kings of England: A History for Young Children* (1848) was written for the pupils of Dyson’s school, who were lower middle-class girls in their teens, as was *Mrs. Elderney’s School* (written *c.* 1849), a serial about a small boarding-school for girls.[31] This pattern of rapid production of work of diverse kinds for different audiences was early established, and never departed from.  And each of these various works was conceived of by Yonge and those who knew her as work for the Church, *Pro Ecclesia Dei*.[32] In 1844, while staying with the Coleridges at Ottery St. Mary, she wrote a verbatim record of a conversation between herself, her host and hostess and their children:  they discussed *Abbeychurch,* Elizabeth Sewell’s* Amy Herbert* (1844)*, *Harriett Mozley’s *The Lost Brooch,* Lady Georgiana Fullerton’s *Ellen Middleton* (1844) and the poetry of Robert Southey.  As Christabel Coleridge commented in 1903:

It appears. . . that brilliant young men and learned judges were more ready to discuss with interest stories for little girls than would seem likely at the present day, and an interesting side-light is thrown on the fact that these children’s stories by Miss Sewell, Miss Newman (sister to the Cardinal), and by Charlotte herself were even then recognised as contributions to the great Church movement.[33]

Thus, from the very first childish productions, and in her first steps as a professional writer, Yonge had the thorough support and encouragement of her family and friends, and her writing was undertaken for a mixture of charitable and educational purposes, and was conceived of as part of a much larger programme of collective activity (including teaching, religious instruction, journalism, the erection of churches and schools, the establishment of various mutual aid societies and so on), consciously designed to achieve social change.   In many respects this continued to be true throughout her exceptionally long and productive career.

[1] In footnotes, from here on: Charlotte Mary Yonge=CMY; William Crawley Yonge= WCY; Frances Mary Yonge=FMY; Julian Bargus Yonge=JBY.

[2] Keble preached on ‘National Apostasy’ in the University Church of St. Mary’s, Oxford, on 14 July 1833 on the occasion of the opening of the Assize:  C. B. Faught, *[The Oxford Movement: A Thematic History of the Tractarians and their Times](../other_books/otherbook_64.qmd)* (University Park, PA: Pennsylvania State University: 2003) 5, 84.
[3]The Rev. William Bigg Wither was the son of Heathcote’s maternal uncle Harris Bigg Wither (who proposed to Jane Austen);  Caroline (Coxwell) Young was a cousin and adopted daughter of Keble’s wife;  Maria (Trench) Wilson was the niece of Heathcote’s first wife: R. F. Bigg Wither, *[Materials for a History of the Bigg Wither Family](../other_books/otherbook_18.qmd)* (Winchester: Warren 1907); *[Recollections of the Rev. Peter Young, M.A., late Rector of North Witham, Lincolnshire and Canon of Lincoln](../other_books/otherbook_187.qmd)*, edited by his daughter (Grimsby: Albert Gait 1903), 10;  Burke, *[Peerage](../other_books/otherbook_25.qmd),* *sub. *Egmont E..
[4]John Keble, *Sermons Occasional and Parochial* (1868) 361, quoted in Geoffrey Rowell, *[The Vision Glorious: Themes and Personalities of the Catholic Revival in Anglicanism](../other_books/otherbook_137.qmd)* (Oxford: Oxford University Press 1983), 8.
[5]John Keble, ‘Adherence to the Apostolical Succession the Safest Course’ *Tracts for the Times*, no 4 (1833) 7, quoted in Faught, *[Oxford Movement](../other_books/otherbook_64.qmd)*,* *16.

[6] Owen Chadwick, *[The Spirit of the Oxford Movement](../other_books/otherbook_33.qmd) *(Cambridge: Cambridge University Press 1990)*,* 25: ‘The mental picture of pastoral care was still, in the England of 1830, the parson in the country parish.’ On Tractarianism in urban areas see John Shelton Reed, *[Glorious Battle: The Cultural Politics of Victorian Anglo-Catholicism](../other_books/otherbook_134.qmd)* (Nashville, Tenn.: Vanderbilt University Press 1996) 96.

[7] Faught, *[Oxford Movement](../other_books/otherbook_64.qmd)*, 97.
[8]Charlotte M. Yonge, *[John Keble’s Parishes](../cmy_books/cmybook_247.qmd)* (London: Macmillan 1898), 125.

[9] Keble’s well-known statement in 1847, at a time when the relations between church and state were under intense discussion as the result of the Gorham case, indicates the confidence he and his followers felt that Hursley was a microcosm of an ideal England: ‘If the Church of England were to fail, it should be found in my parish.’ Quoted in Chadwick, *[Spirit of the Oxford Movement](../other_books/otherbook_33.qmd)*, 62.
[10]Coleridge, *[Life](../other_books/otherbook_40.qmd)*, 80-1; *[John Keble’s Parishes](../cmy_books/cmybook_247.qmd)*, 96-7; Charlotte M. Yonge, *[An Old Woman’s Outlook in a Hampshire Village](../cmy_books/cmybook_225.qmd)*, 65-7; *[Joseph Mason: Assigned Convict 1831-1837](../other_books/otherbook_115.qmd)* ed. David Kent and Norma Townsend (Melbourne: Melbourne University Press 1996), 3.  William Cobbett, whose writings were an inspiration to the rioters, had been a visitor to Otterbourne House before the Barguses bought it.

[11] On Sir William Heathcote’s refusal to let his farms to Dissenters see Frances Awdry, *[A Country Gentleman of the Nineteenth Century: Being a Short Memoir of the Right Honourable Sir William Heathcote, Bart., of Hursley 1801-1881](../other_books/otherbook_14.qmd)* (Winchester: Warren and London: Simpkin 1906), 96.;  CMY’s approval of this policy is expressed in her early novel *[The Two Guardians](../cmy_books/cmybook_13.qmd)* (1852).  John A. Vickers, *[The Religious Census of Hampshire 1851](../other_books/otherbook_174.qmd)*  (Hampshire: Hampshire County Council 1993), Hampshire Record Series 12, 136, shows that there were no Dissenting or Roman Catholic churches nearer than Twyford or Bishopstoke.  For discussion of the distinction between ‘open’ villages in which radicalism and Dissent could flourish and ‘closed’ villages such as Hursley, see David Kent, *[Popular Radicalism and the Swing Riots in Central Hampshire](../other_books/otherbook_101.qmd)*, Hampshire Papers 11 (1997), 3.

[12] *[John Keble’s Parishes](../cmy_books/cmybook_247.qmd)* 98.

[13] R. W. Church, *[The Oxford Movement: Twelve Years, 1833-1845](../other_books/otherbook_34.qmd)* cited by Faught, *[Oxford Movement](../other_books/otherbook_64.qmd)*, 97.

[14] *[Recollections of Peter Young](../other_books/otherbook_187.qmd)*, 9-10; *[John Keble’s Parishes](../cmy_books/cmybook_247.qmd)*, 107-8.

[15] Christabel Coleridge, *[Charlotte Mary Yonge: Her Life and Letters](../other_books/otherbook_40.qmd)* (London: Macmillan 1903), 145.
[16]C.A.E.Moberly, *[Dulce Domum: George Moberly, his Family and Friends](../other_books/otherbook_122.qmd)* (London: John Murray 1911) 5: ‘It was an actual daily intercourse . . which made the tie [between the Kebles, the Yonges and the Moberlys] so binding . . . we were in the habit (during the summer months) of seeing the [Kebles] at least three times a week.  During the other months whenever the Kebles and Yonges came into Winchester they . . .  made their headquarters in College Street. . . .  A cart . . . carrying milk, butter and bread to the school, every day throughout the year, passed through Otterbourne  . . By this means letters, books, and parcels of all sizes from Otterbourne were answered  . . .  without the medium of the post, before noon on the same day.  The Yonges were within a walk of the Kebles.’* *

[17] See James Darling, *[Catalogue of books in the library of Sir William Heathcote, Bart., M.P., at Hursley  Park, in the county of Southampton](../other_books/otherbook_48.qmd)* (London: Darling 1865, a revised version of the edition of 1834).  Mary Anne Moberly had been brought up in Italy and studied Dante; it seems likely that she was a source of Italian books.  It is also possible that CMY may have read books from the library of Winchester College.

[18] All three were also married to members of the family:  Duke Yonge to Cordelia Colborne (FMY’s stepsister);  James Yonge to Margaret Crawley (his and WCY’s first cousin); and John Colborne to Elizabeth Yonge, sister of the Rev. John Yonge of Puslinch.
[19]James Coleridge, the elder brother of S. T. Coleridge, had married Frances Duke Taylor, whose aunt Elizabeth Duke was grandmother to WCY and to the Rev. John Yonge of Puslinch. The children of James and Frances Coleridge (including Sir John Taylor Coleridge, Henry Nelson Coleridge, Dr James Duke Coleridge and Frances (Coleridge) Patteson), and their descendants, were thus related to CMY and the Yonges.  However, Christabel Coleridge, her biographer, the poet’s granddaughter, was not.

[20] Coleridge, *[Life](../other_books/otherbook_40.qmd)*, 200: ‘Owing to the destruction of the correspondence with Miss Mary Coleridge, it is inevitable that this third great friendship of Charlotte’s life should appear less prominent than was really the case.’  Some letters to Sir John Taylor Coleridge himself do however survive among a large collection of papers recently acquired by the British Library.

[21] See *[An Old Woman’s Outlook](../cmy_books/cmybook_225.qmd)* (1892), 83, ‘We have gone through the permission to learn the three R’s up to their becoming a necessity, and that greatest R of all – Religion - for the sake of which alone we taught in old times, has a hard matter to hold its own.’
[22]Founded in 1811, and still (2006) in existence as the National Society, Church of England, for Promoting Religious Education.
[23]This account is indebted to an unpublished paper by Alys Blakeway, ‘[Towards a study of Marianne Dyson](../other_books/otherbook_20.qmd),’ given to the Charlotte Yonge Society in April 2002.
[24]Lord Coleridge,  ‘[In Memoriam M.A.D.](../other_books/otherbook_38.qmd)’ *Monthly Packet,* 3rd series 2 (December 1878), 521, 523.

[25] MS Miss Barbara Dennis: To Florence Wilford (1 October 1878).

[26] The conversation between Yonge and Dyson is illuminated by Hampshire Record Office MS 9M55, .a much larger correspondence, of which both sides have been preserved, between Mary Anne Dyson and her friend and contemporary Anne Sturges Bourne, running from 1822 to 1878.

[27] CMY stated in [‘Lifelong Friends’](../cmy_books/cmybook_292.qmd) *MP* 4th series 8 (December 1894), 694-7, 695: ‘My mother told the story of [*[Abbeychurch](../cmy_books/cmybook_2.qmd)*] to Mrs. Keble, and this led to the manuscript being most kindly considered and recommended to Mozley.’  Burns’s name, however, appears first on the title page.

[28] In the introduction to the 1872 reprint she called it ‘my first crude attempt’; and she deplored its narrow-mindedness also in [‘Lifelong Friends’](../cmy_books/cmybook_292.qmd), 695.

[29] It was subsequently published by Burns and Mozley, and it was eventually marketed to better-off children than had originally been intended. Anne Mozley took over as the editor of  *[The Magazine for the Young](../organizations/other_79.qmd)* in about 1843 and edited it until 1875. Some of these works by CMY were published independently by James Burns, either alone or with Mozley. Burns became a Roman Catholic in 1847, and thereafter the Mozleys seem to have taken over his Anglican books, soon afterwards joining forces with Joseph Masters.  Between them these three published all CMY’s books of the 1840s, and each had a list with a strong Tractarian character.  These details are drawn from an unpublished paper by Ellen Jordan, [‘Charlotte Yonge’s First Publishers’](../other_books/otherbook_89.qmd) given to a meeting of the Charlotte Mary Yonge Fellowship in April 2006.

[30] *[Langley School](../cmy_books/cmybook_9.qmd)* (London and Derby: Mozley 1850).  The first fifteen chapters were serialized in *[The Magazine for the Young](../organizations/other_79.qmd)* September 1846-December 1848.

[31] *[Mrs Elderney’s School](../cmy_books/cmybook_12.qmd) *was published (January 1850-Jan 1852) in *The Magazine for the Young, *but never reprinted in volume form.
[32]‘For the Church of God’: ‘her favourite motto’: Coleridge, *[Life](../other_books/otherbook_40.qmd)*, 132; they are said to have been the dying words of John Whitgift (1530/1-1604), Archbishop of Canterbury.

[33] Coleridge, *[Life](../other_books/otherbook_40.qmd)*, 152, 373-.9


## Letters

{{< include _1834-1849_letters.md >}}
