---
title: "Letters 1850-1859"
listing: false
decade_label: "1850-1859"
post_id: 3735
letter_id: "letters-1850-1859"
---

**INTRODUCTION TO LETTERS 1850-1859**

During the first half of the 1850s three events took place which were of enormous significance to Yonge.  These were, chronologically, the foundation of the *Monthly Packet* in 1851, the publication of her bestselling novel *The Heir of Redclyffe* in 1853 and her father’s death in 1854.[1] In 1851 the firm of Mozley and Son founded a magazine for young people, *The Monthly Packet of Evening Readings for Younger Members of the English Church*, which Charlotte Yonge was to edit for more than forty years.   In 1853 the overnight success of *The Heir of Redclyffe* made her for the first time a very popular novelist with an international reputation earning significant amounts of money.  In 1854 her father, a man of dominating character to whom she and her mother were devoted, died suddenly and unexpectedly in his fifties. These three major events are all chronicled in detail in the correspondence.

The impact of her father’s death is charted in Yonge’s correspondence and also in an interesting series of letters written by her mother and her cousin Anne from the house of mourning, no doubt preserved by the Puslinch Yonges in his memory, which add significantly to our sense of the family dynamics.  Coleridge’s biography makes it sufficiently clear that Yonge was very strictly brought up, but Anne Yonge’s reaction to her uncle William’s death makes it very clear how unsympathetic and dictatorial she herself had found him, and how he was worshipped at home:

I think they have a kind of idea that he was never appreciated by the world at large in the degree they always felt he deserved, and all that is so continually being said of him is a kind of solace and satisfaction to them in itself, &amp; like a tribute paid to their superior judgement wh comes better late than not at all.  . . . It seems more than ever as if it was impossible to form a just or true estimate of a person’s character while he is still alive, or rather we allow what is disagreeable in outward manner &amp; deportment to exclude from our minds, the constant recollection of what the general tenor of a life may be, now in looking at Uncle William’s, one is struck by the number of good deeds he has performed for the sake of others  . . . Charlotte remarks how much Uncle Wm’s character had softened in the last few years, he took much more delight in beauty &amp; poetry of all sorts, besides being gentler in temper, and also less unparticular in his language.  She rejoices that Julian seemed so entirely to have conquered the kind of irritable feeling or approach to sulleness wh a reproof, rather too sharp for the occasion, used in times past to excite[2]

This gives a more vivid glimpse of possible tensions in life at Otterbourne House than anything surviving from Charlotte Yonge’s own pen. Some other letters Anne Yonge wrote home to Puslinch have also been included, which help document the visit she and Yonge made together in 1857 to the grand Dublin wedding of their cousin Jane Colborne.  This was one of only two occasions when Charlotte Yonge left mainland Britain (the other being her 1869 visit to France).  The episode shows that although for the last thirty years she lived an exceptionally retired life, her early years were less secluded, indeed not without moments of glamour, and that for the occasional scenes of high life in her fiction she could draw on the experience of intimate friends.   They also give some idea of how she reacted to her new celebrity status.  However, though they show her enjoying cheerful social life they do not alas cast any light on the interesting question of whether she ever fell in love.  The letters we have give few clues as to Yonge’s emotional life, but it was almost certainly of importance to her that during the 1850s she moved from being a marriageable girl to being a middle-aged spinster.  Many more letters survive for this period than for earlier years, but regrettably few of those which survive in manuscript are written to intimate friends, and the long and full correspondences with Mary Anne Dyson and Anne Yonge exist mainly in the selections made by Christabel Coleridge.  There can be little doubt that Coleridge avoided including any material which Yonge would have wanted to keep private; this would have included any material touching on love affairs, either her own or other people’s.[3]

Another taboo subject,  to which Coleridge makes only guarded reference, but which is several times more or less obliquely referred to in the correspondence, was the series of conversions to Rome among the Tractarians of the 1840s and 1850s. The letters reveal the aspirations and fears of these hectic years, though probably Coleridge tends if anything to underplay the pain and anxiety which surrounded the waves of conversions marked by the secessions of Newman in 1845 and of Manning in 1850.  The frightful blow represented by the loss of Newman was something of which all Keble’s friends must have been conscious;  his former curate the Rev. John Frewen Moor went so far as to point out to his fans, in a guide book to Hursley, the very gravel pit where Keble went to open Newman’s letter announcing his conversion to Rome.[4]

In a letter (24 June 1850), commenting on a recent conversion, Yonge states that nobody she knew well had converted, the nearest being John Francis Yonge (1814-1879), one of the Antony cousins, whom she had not seen since childhood.[5] This was no doubt technically true.  However, the shadow hung nonetheless over many of those closest to her, as her father’s letter (14 March 1849), about this nephew of his, indicates. The Antony Yonges were far from being the only family she knew well to be affected.   In October 1849 Sir William Heathcote’s eldest son, an army officer stationed in Ireland, the heir to Hursley Park and thus the prospective lay leader of the local community,

married in haste a young and devout Roman Catholic  lady who was quite unknown to all his relations, and whose different creed was naturally a great distress to his father, foreseeing as he did the fact that she would draw her husband after her.  In the letters of the next few years to Sir John Coleridge (whose second son was also under Roman Catholic influences, and also eventually joined the Roman Church) there is an undercurrent of deep sadness, and of anxiety lest others of the family should also secede.[6]

This was a blow not only to the Heathcotes personally but to the whole concept of Hursley as a parish in which clergyman and squire were in close alliance, on which depended the social and religious reform programme so dear to Yonge’s heart.  The earliest letter we have found which makes any reference to this event is dated 7 August 1876:  clearly this cannot accurately reflect its importance to the Yonges.[7] William Perceval Heathcote (1826-1903) was a few years her junior, and she had known him from childhood.  Sir John Taylor Coleridge’s son. the Rev. Henry Coleridge, later Father Coleridge S. J., a year older than Yonge, was probably an even more intimate friend:  he converted in 1852.  The Puslinch Yonges’ nearest neighbour, Edmund Bastard of Kitley, had converted by 1851.  Her first publisher, James Burns, had converted in 1847.[8] The cumulative impact of these conversions helps account for Yonge’s anxiety, revealed in the correspondence with her contributors, to avoid accusations of Romanism in the *Monthly Packet.*

* *you will consider me servile, but I really believe that the Packet must steer clear of Puseyite name and discussion, and do what it does silently.[9]

Also acutely vulnerable to the odium surrounding conversions to Rome, were another group of friends who become important from this period, the family of the Rev. William John Butler (1818-1894).  He had been one of Charles Dyson’s curates. As vicar of Wantage from 1846, he engaged, in the not altogether promising circumstances of a moderately-sized town, with no particular advantages in the way of local influence, in one of the most comprehensive and successful Tractarian projects.  He reformed schools, instituted extensive district visiting programmes, trained myriads of like-minded curates, and triumphantly founded, in 1850, of all institutions the most feared and reviled, a sisterhood, the Community of St. Mary the Virgin, which survives to this day, and of which Yonge herself was to become an Associate in 1869.[10] This controversial project was threatened in its first year of existence when its head, Elizabeth Lockhart, followed her mentor Archdeacon Manning into the Roman Catholic Church.   The Butler family became lifelong friends of Yonge and were stalwart supporters of the *Monthly Packet*, to which several of them contributed, notably his sister Anna Butler.  William Butler had married his second cousin, Emma Barnett, whose sister Elizabeth kept up a long correspondence with Yonge. Elizabeth Barnett lived in London with her father, the head of a banking house, but took a close interest in her sister’s family and her brother-in-law’s good works.[11] This large-scale collective enterprise, like the work at Hursley, was directly threatened by every additional conversion among the Tractarian community.

This was the context for the foundation of the *Monthly Packet. * It was a collaborative venture, emerging at a time of great tension, supported by the efforts of the connected group of Tractarian families who have already been named as sharing views on religious and social issues with the Yonges of Otterbourne.  Its object was to secure the loyalties of the next generation of Tractarians, by ensuring that their early associations were entwined with Church of England doctrine of the purest kind.  Keble himself had a singular devotion to the memory of his home in Fairford, and the habits of his father’s ministry; he was to pass on this kind of absolute loyalty to the religious traditions of childhood to Charlotte Yonge.  But even she, looking back on her own childhood, regretted that the available children’s books of the 1820s and 1830s had been tinged with dissent and evangelicalism.[12] This gap was now being supplied by the efforts of Yonge and others, but it was felt that a magazine suitable for children of the upper-class was wanted.  In about 1848 Yonge had been ‘asked to help in the revivification of the *Churchman’s Companion*.’[13] This was a magazine for adults of the educated classes, published by another Tractarian publisher, Joseph Masters; Yonge contributed two full-length works of fiction in the same vein as *Abbeychurch*:  *Henrietta’s Wish* (which ran in the *Churchman’s* from January 1849 until May 1850) and *The Two Guardians* ( July 1850-February 1852).  But it was not felt to be suitable reading for the young, as Coleridge explains:

Its tone was, however, extremely controversial, and it was given to insist more on the surface pecularities of the Church movement than the wiser members of that movement thought good.  The Dysons,. and possibly others, suggested the putting forth of a magazine for young people, suited to the schoolroom rather than the village school, and which should avoid personal controversy as unsuited to the young.  They speedily asked Charlotte to edit it, and she took to the idea with eagerness, planning it out, and in fact creating it, while she thought she was humbly following the suggestions of her elders.  The name was a difficulty.  ‘The Maidens’ Manual’ was suggested amid various others.  Among themselves they called it ‘The Codger’, saying that it was intended to please steady old codgers . . . [14]

The doctrine of reserve in communicating religious knowledge, was fundamental to the Tractarian world view.  This had been the subject of Isaac Williams’s Tract  80 (1838), which had roused a storm of protest.  It was this principle which consistently held Yonge back from the open discussion of controversial doctrines and practices of the kind which had been commonplace in improving stories for the young, especially of the evangelical school, and which the Tractarians considered irreverent. (This was the counterpart in literary criticism of their horror of evangelical preaching, with its rabble-rousing appeal to the emotions.[15])   The existence of a symbolic level of meaning, available to the penetrating, more sympathetic, initiated, older or cleverer reader, permitted controversial ideas to be touched on indirectly and discreetly.  This simultaneously met several different needs.  Theologically, it connected with Keble’s insistence on the mystical significance of the history of the early church and of the writings of the fathers.  Aesthetically, it chimed in with the mediaevalizing taste of the Tractarians, and their enthusiasm for the chivalry and religious literature of the Middle Ages. And it also had a practical use, as it permitted meanings to be encoded, either in buildings or in books, which if made explicit might have been called Puseyite and caused scandal.   The modern reader is only too likely to miss this dimension of Yonge’s work altogether.  Christabel Coleridge in her biography of Yonge seems to draw particular attention to this feature of Yonge’s thought, probably because even by 1903 she thought her readers needed reminding about early Victorian reading habits.[16]

There was a fundamental association between the emphasis on early experience and the emphasis on symbolism: children must learn prayers, stories and history, whose full significance they would only come to understand, if at all, much later.   Ethel May incoherently expresses this idea, in *The Daisy Chain*:

‘Why the last thing they did was to leave off reading the Prayer-book prayers morning and evening!  And it is much expected that next they will attack all learning by heart. . .   oh! if I could only say half what I have in my mind, they must see the error.  Why, these, these - what they call formal - these the ties - links on to the Church - on to what is good - if they don’t learn them soundly - rammed down hard - you know what I mean - so that they can’t remember the first - remember when they did not know them - they will never get to learn - know - understand when they can understand! . . . If they don't learn them by rote when they have strong memories. Yes, that's it!’ she continued; ‘they will not know them well enough to understand them when they are old enough!’

‘Who won't learn and understand what?’ said Richard.

‘Oh, Ritchie, Ritchie!  Why the children-- the Psalms-- the Gospels-- the things.  They ought to know them, love them, grow up to them, before they know the meaning, or they won't care.  Memory, association, affection, all those come when one is younger than comprehension! . . . so that one ought to know all good things-- fa-- with familiarity before one can understand, because understanding does not make one love.  Oh! one does that before, and, when the first little gleam, little bit of a sparklet of the meaning does come, then it is so valuable and so delightful.’

‘I never heard of a little bit of a sparklet before,’ said Richard, ‘but I think I do see what Ethel means; and it is like what I heard and liked in a university sermon some Sundays ago, saying that these lessons and holy words were to be impressed on us here from infancy on earth, that we might be always unravelling their meaning, and learn it fully at last-- where we hope to be.'  [*The Daisy Chain *Chapter 24.][17]

Thus the members of Yonge’s circle were thoroughly accustomed to the idea that a text might contain an idea or a lesson which would repose within it until at the appropriate moment its significance would emerge for a particular reader.  Her sense of the process of reception thus always includes the awareness that it will change over time, and that at any given moment a book or a passage will have diverse effects on different readers. For all the lifelike portrayal of family life and the lively dialogue which strike the reader of early works like *The Heir of Redclyffe*, such novels are meant to be read on the understanding that names, characters and events are suffused with symbolic meaning, and capable of being moralized by the attentive reader.  Meaning is therefore both multiple and latent.

Some of the most interesting of the letters of the 1850s are those judiciously selected by Coleridge to reveal the significance for Yonge’s writing and habits of thought of Tractarian reading practices.  She quotes a letter in which Yonge refers to ‘Mrs. Keble’s favourite part is the *Mondenfelsen* time’, glossing it in a footnote: ‘The time when Guy was banished to Redclyffe, in imitation of the banishment of Sintram to the Rocks of the Moon.’[18] Without labouring the point, she opens up the question of the relationship between *The Heir of Redclyffe* and La Motte Fouqué’s allegory *Sintram and his Companions, *showing how ready members of their circle were to make such connections, how habitual was their use of allegorical and analogical interpretation. [19] Annie Moberly was making a similar point in her family history, when she tried to explain why modern readings did not do justice to Charlotte Yonge’s work:

The comprehensiveness of the spiritual combat inspired all Charlotte Yonge’s undertakings. The idea embodied in La Motte Fouqué’s ‘Sintram’ gleamed through ‘The Heir of Redclyffe’.  A very fine engraving of  . .  Durer’s . . . The Knight and his Companions,’ which always hung over her writing-table, seemed to us to be the spiritual source to which many characters in her stories could be traced.[20]

In 1879, discussing with her publisher the plans for a collected edition of her novels, Yonge wrote:

It is rather difficult to arrange the order of these books. Heartsease was out before the Daisy Chain indeed those four  that I numbered first were meant to answer to the four Seasons, and ought to go together[21]

When the uniform edition was published the first four books were numbered 1. *The Heir of Redclyffe* (1853), 2. *Heartsease *(1854), 3. *Hopes and Fears* (1860) and 4. *Dynevor Terrace* (1857).  The model for this intriguing arrangement was undoubtedly La Motte Fouqué,  *Die Jahreszeiten* (1811-14), consisting of *Frühlings-Heft: Undine*;* **Sommer-Heft: Die beiden Hauptleute*;* Herbst-Heft: Aslauga's Ritter *and* Alpin und Jucunde*; and* **Winter-Heft: Sintram und seine Gefährten. * Nor is the parallel with La Motte Fouqué the only one which these novels invite the informed reader to make, for *The Heir of Redclyffe* also begs the reader to consider it in conjunction with several other books, including Malory’s *Morte Darthur,* Richardson’s *Sir Charles Grandison *and Manzoni’s *I Promessi Sposi*.[22] *Heartsease*, the story of a landowning family’s struggle with the legacy of the exploitation of West Indian slaves, includes a series of surely significant but unarticulated parallels with *Mansfield Park*.[23] The implications of such parallels merit further exploration.  To those who think of her as above all a novelist who excels in realistic detail it may be surprising, but it is undoubtedly true, that her work was shaped by the emphasis on the enigmatic, the mystical and the symbolic, which Keble's poems and theological writings had expressed, and which Owen Chadwick saw as the defining feature of the Oxford Movement; such ideas became fundamental to the way in which she and her circle read and wrote poetry and fiction, including children’s fiction.[24]

The letters about the composition and publication of *The Heir of Redclyffe* and her other writings reveal the existence of an extended circle of consultant readers including the Dysons, the Moberlys, the Butlers and the Kebles.  In these early years of her career, it is apparent that this preliminary discussion process was very important to her, and she often took the advice offered, deleting, for example, the final chapter of *Heartsease* in response to Keble’s comments.  In some ways this recalls the practice of the eighteenth-century novelist Samuel Richardson, a writer whom Yonge much admired, and some aspects of whose work she tried to emulate.  One might also see this kind of pre-publication reading group as representing a sort of publication in itself.   Certainly the advice which her readers were invited to offer was partly censorship, and the process of gradually including more readers in the circle of initiates provided a kind of buffer zone between the private and the public.  The work in progress moved slowly out of the family circle, into that of sympathetic and like-minded friends, and thence into the wider world where readers would not only be less likely to share Tractarian values but might also be actively prejudiced against anything that smacked of Puseyism.  The reading and discussion process was intended to guard against a whole series of hazards, from  bad grammar, intellectual pretension, inaccuracy, implausibility and inconsistency to the more serious dangers of vulgarity and irreverence.   More positively, it also represented an opportunity to test her work on readers who had been trained as she had in the habit of looking for allegorical or symbolic subtexts and for religious and literary analogues and patterns.  One finds evidence of this in her reaction to others’ readings of her work, in her accounts of her own reading and in the way she depicts readers in her fiction:

I am really getting fond of Philip, and mamma says people will think he is the good one to be rewarded, and Guy the bad one punished.  I say if stupid people really think so, it will be just what I should like, for it would be very like the different morals caught by different people from real life.  Have you had the third volume of Southey yet?  there is a most curious thing in it at the end about Thalaba, by which it appears that some one actually published a sketch tracing out the whole allegory of faith all through it.  Southey is pleased, but in a strange manner shows that he did not mean it, or even understand it when it was shown him!  I am sure this seems as if poets themselves were not the composers of their works, and how strikingly it joins with the grand right parts of the old Greeks.[25]

The sacramental vision of the natural world which underpins Keble’s *Christian Year* is thus extended to the interpretation of history and literature, not only to the works of Dante and Southey, but also those of Charlotte Yonge. Just as classical literature may be seen to anticipate Christian truths in ways its authors were ignorant of, so any author may potentially be the unconscious agent in a Divine plan. As the letters constantly remind us, Yonge was steeped in *The Christian Year*, quoting it as often as the Bible; its message that we can find teaching in ordinary daily life is embedded in her highly idiosyncratic version of domestic realism.  The central idea was expressed by another of the excitable, incoherent, socially inept heroines she based partly on herself:

all three fell into an eager talk, when suddenly there was a general lull, and the young lady’s voice was heard saying, ‘There is no heart or beauty in what is not symboli-’  and there she came to a full stop . . .  with a start of embarrassment  . . .[26]

Yet as early as 1860 Yonge was expressing in fiction a sense that the younger generation had little time for such exalted and mystical approaches, in the voice of Lucilla Sandbrook,

‘with her I always have a sense of *fluffiness*.  There is so much figurativeness and dreamy sentiment that one never gets to the firm clear surface.   . . .I say, Phoebe, were you never in an inward rage when she would say she would not *let* some fact be true, for the sake of some mythical romantic figment?  . .  . the last generation was that of mediaevalism, ecclesiology, symbolism, whatever you may call it.   . . . Ours is that of common sense.’[27]

In several later works she was to recur to the idea that the modern world was impatient with the enthusiasms and the aesthetics of her early period.[28]

During the 1850s Yonge published seven non-fictional titles and 18 works of fiction of various kinds.   She continued to address a variety of audiences, in a way which has tended to be concealed by the later collected editions of her works, which issued in the same binding works directed at adults and at children.  The foundation of the *Monthly Packet* led to the composition of a good deal of both fiction and non-fiction for its designated readers:  *The Castle-Builders * (1854) and  *The Daisy Chain* (1856), which both appeared there, being aimed at teenage girls;  and *The Little Duke* (1854) and *The Lances of Lynwood *(1855), at little boys still kept in the schoolroom with their sisters.  *Conversations on the Catechism* (1859-62) originated as a series in the magazine, which had been specifically envisaged as addressing those preparing for confirmation. The letters of this period are interesting in that they help to define Yonge’s initial sense of the identity of the magazine, which inevitably modified over the years, and was from time to time affected by the preoccupations of contributors as well as her own changing interests and views. The fifties were a vintage period for the *Packet.* Nearly fifty years later, when it finally collapsed, Yonge wrote touchingly to Christabel Coleridge, then her co-editor, who had been attempting to find a way of keeping it going:

Helen has been reading the early volumes which somehow she had never seen, and I find that they were almost entirely my best and most enduring things, such as I could hardly renew imitate, and if I did, they would be only stale.  No, I could not do the same, nor could you, though you can do better and deeper and the young and lively do things of their own not in old grooves of their predecessors.[29]

Despite, though, the inexorable demands of the monthly number, the *Packet *was far from monopolizing the work of this period. Other little books continued to appear, either for younger children,* *such as *The History of the Life and Death of the Good Knight Sir Tom Thumb * (1855), or for poorer ones, such as  *The Railroad Children* (1855) and  *Leonard the Lion-Heart* (1856), the latter still serialized in the *Magazine for the Young*.  The adult novels of this period, *The Two Guardians* (1852), *The Heir of Redclyffe* (1853), *Heartsease *(1854), *Dynevor Terrace* (1857) and *Hopes and Fears* (1860), were either not serialized at all or appeared in periodicals designed for a mixed audience including adults of both sexes.  Romance figures more largely in these novels than Yonge considered appropriate for the *Packet*;  and it is also probable that she was more concerned to incorporate into them a higher degree of formal organisation and a more complex symbolic scheme than was necessary or desirable in works aimed a younger audience.

Her activities as editor of the *Monthly Packet *are particularly well-documented because of the survival from this period of several groups of letters to contributors, especially Elizabeth Roberts, Ann Carter Smith and Anna Butler.  The character and aims of the magazine have been studied by Amy de Gruchy and the Roberts correspondence in particular by June Sturrock.[30] It is our hope that the publication of these letters in full will encourage further exploration of the subject.  They provide, for one thing, many clues as to the identity of anonymous contributors, and Helen Schinske’s work on indexing the *Monthly Packet*, which will soon appear, incorporating this evidence, will give a much clearer picture of the circle of authors around Yonge.   Charlotte Mitchell’s recent discovery of the complete record of Yonge’s bank account 1844-1901, in the archives of Messrs Hoare, although also of more general biographical interest, offers rather unexpectedly a great deal of information about the contributors and their rates of payment, since it appears that in the early days Yonge paid many of them by cheques on her personal account.[31] It is particularly interesting to reconstruct the circle of contributors to the *Packet*, because many of them are otherwise invisible in literary history owing to publishing anonymously.  Roberts, Smith and Butler, for example, were all fairly prolific authors and journalists, yet Butler has no entries in COPAC, Roberts one possible title, and Smith is represented by only two of her works.  The novels of Fanny Caroline Lefroy, another important early contributor, are only identifiable as such from  the catalogue of the Bodleian Library.   Henrietta Murray, a probable contributor in 1858 and briefly the editor of *Events of the Month*, Harriet Lucy Cox, Ellen Millington, Miss M. Ashwell, and Miss A. M. Goodrich are other writers whose full bibliographies are unknown.  Would that their correspondence with Yonge had also survived, and also that of rather better-known contributors such as Margaret Gatty, Margaret Roberts and Emily Taylor.

The surviving bank account has some evidence to offer about the enthusiasms of these years, and helps to illuminate the story told by the surviving letters, although of course it must be treated with caution, as there is no way of knowing whether or not it contains details of all the transactions Yonge was party to, and the picture is also complicated by the fact that she paid contributors to the *Monthly Packet* with Mozley’s money from her own account.[32] But it is clear that until 1853 there are fairly few entries in Yonge’s account, and those not for large sums of money.  The success of *The Heir of Redclyffe* evidently brought a dramatic rise in her income, which was £69 8*s. *9*d.* in 1852, £480 12*s. *10*d.* in 1853 and £1402 14*s.* 8*d. *in 1854.  Much later she wrote that her first earnings were all given away.[33] The ledger reveals how in some detail.

The hero of *The Heir of Redclyffe* makes a large donation to an embryo sisterhood which is being persecuted.  Yonge, in the same spirit, gave some of her first-fruits to the women’s arm of the Anglican monastic revival.  Lydia Sellon, whose efforts to found a sisterhood in Plymouth are several times mentioned in her letters, had £20 in October 1853, and further regular payments appear to 1857;  two to Miss C. Chambers in 1856 and 1857 may also relate to the Devonport Sisters of Mercy.[34] The Rev. William Butler, of Wantage, got £15 in 1854, £140 in 1855, £30 in 1857, £30 in 1858, £40 in 1859 and some at least of these were probably for his sisterhood.  The Penitents Home, Horbury, run by a sisterhood, got £20 in 1858.  The House of Charity, a High Church refuge for the homeless in Soho, was given £15 in 1853 and further payments in 1854, 1855, 1856 and 1858. Yonge also supported  projects nearer home, especially the kind of church-building and parish work which is so vividly evoked in early novels such as *The Daisy Chain*.  There are several small sums paid to the Rev. William Bigg Wither, curate of Otterbourne, and £100 to John Keble in 1857, very likely in connection with the rebuilding of Hursley Church.   She mentions in the letters Keble’s plan for a chapel in the outlying village of Pitt, to which she has devoted ‘that money of Guy’s’, and the ledger shows £185 for the Pitt Chapel in 1857 and another £115 in 1858.[35]

The charitable donations of these years register what Coleridge called ‘the romance of missionary enthusiasm’ which also features strongly in Yonge’s correspondence:

I hardly think it would be too much to say that her greatest enthusiasm was for the spread of the Christian Church in heathen lands, and her feeling about it was so unlike the usual and conventional one that it will be well to put it fully forward. Missionary enterprise was to her a splendid romance, a crusade in which subjects were won to Christendom as well as souls to Christ. She could not imagine dulness in connection with it.  Missionary travels were full of adventure and missionary achievements of glory.  It is known that all the profits of *The Daisy Chain* and part of those of the *Heir of Redclyffe* were devoted to the cause, but she gave a great deal more to it in money than can now be traced, and far more in time and in prayers than any one can ever realise.[36]

The largest sum which can be identified in the bank account of this period as being a donation to a missionary charity is the £163 10*s. *paid on 8 November 1859 to Falbes for Sir John Patteson, almost certainly representing the profits from *The Daisy Chain*, which were all eventually devoted to the Melanesian Mission, and no doubt the sum mentioned in his son Coleridge Patteson’s letter to her, which it was decided to spend on building St. Andrew’s College, Kohimarama.  In 1857 she paid  £20 to Goslings Bank for the Bells for Auckland Church;  this plan to raise money so that church bells would be heard ringing for the first time in New Zealand caught her imagination, and the fund is frequently mentioned in the letters and also in the *Monthly Packet*.  Letters to the Rev. Edward Coleridge, an Eton master closely connected with the New Zealand and Melanesian missions, suggests the possibility that the payments to the Rev. E. Coleridge of  £5 in 1853 and £20 in 1854 were also connected with New Zealand.[37] Although New Zealand and Melanesia were always of prime importance to her, there is also a sign of the interest in South Africa which developed later in the shape of £10in 1859  for the Lord Bishop of Cape Town. However,  not all her charitable donations are visible in the bank records; the sum of £146 10*s.*, profits from *The Heir of Redclyffe*, * *which she mentions presenting to Bishop Selwyn for the purchase of a new missionary ship to sail the South Seas, does not appear:  however he received the money, it was not by a cheque on her account.[38]

It is a pity that the only substantial surviving body of correspondence relating directly to Yonge’s missionary zeal should consist of  Coleridge Patteson’s letters to her, preserved because she printed them in his biography, the first of which appears in this section.[39] We can only deduce from the elaborate detail they contain how her own letters encouraged him to believe that she took a personal interest in the daily life of individual converts, living on the other side of the world.  His letters contrast very forcibly with the run of her surviving correspondence, and one can see that they must have been windows onto an utterly strange and exotic world, in which extraordinary feats of self-sacrifice and idealism provided ample fodder for her already well-developed capacity for hero-worship.

[1] To this list one could add her younger brother Julian’s service with the Army in the Crimean War, which seems to have permanently injured his health, his marriage to Frances Walter and the birth and death of his first child.  Charlotte and Julian Yonge spent their entire lives in close proximity, but their relationship is ill-documented;  the family’s characteristic reticence was compounded by the fact that his later financial disasters gave his descendants a positive interest in obscuring its details, but it appears all the same to have been of great importance to her.
[2]Anne Yonge to the Rev. John Yonge (March 1854).

[3] It is a striking fact that the letters to Anne Yonge surviving among the Puslinch papers do not include any of those published by Christabel Coleridge.  This is no doubt because the Anne Yonge correspondence which Coleridge saw belonged to Yonge’s niece Helen Yonge, whose papers are missing.   The fact that two of the surviving manuscript letters of the 1840s refer to the abortive engagements of Mary Coleridge and Jane Colborne suggests the possibility that those which remained at Puslinch were censored, perhaps after Anne Yonge’s death in 1869, as unsuitable for publication, and were therefore not returned to CMY.  All CMY’s papers  (which included the correspondences with Mary Anne Dyson and Anne Yonge returned to her on their deaths) were inherited by Helen Yonge, lent by her to Christabel Coleridge, and returned by the latter to her.  After that they disappear.  The theory advanced by Georgina Battiscombe, *[Charlotte Mary Yonge: The Story of an Uneventful Life](../other_books/otherbook_17.qmd)* (London: Constable 1933), 7, that Coleridge destroyed the papers, since often repeated, is disproved by a letter from Coleridge to Mary Yonge in the Plymouth and West Devon Record Office.

[4] John Frewen Moor, *[A Guide to the Village of Hursley, the Home of Keble, Author of 'The Christian Year'](../other_books/otherbook_124.qmd)* (Winchester: Savage 1869), 9.

[5] This was Dr. John Francis Yonge, M. D. (1814-1879). See William Crawley Yonge to John Yonge (14 March 1849).  Barbara Dennis, *[Charlotte Yonge (1823-1901) Novelist of the Oxford Movement](../other_books/otherbook_55.qmd)* (Lampeter: Edwin Mellen  1992) 48, 51n, states, on the authority of Yonge family tradition, that his elder brother the Rev. Duke John Yonge (1809-1846) also converted to Roman Catholicism.  But it is hard to reconcile what CMY wrote in 1850 with the conversion of two of the Antony cousins, one since dead, and it seems more likely that Dennis’s story relates to John Francis Yonge.

[6] Awdry, *[Heathcote](../other_books/otherbook_14.qmd)*, 93.  The event described here forcibly recalls the opening scene of CMY’s novel *[Heartsease, or, The Brother’s Wife](../cmy_books/cmybook_19.qmd)* (1854), which charts the reactions of an aristocratic family to the news of the clandestine marriage of the second son.

[7] MS Plymouth and  West Devon Area Record Office Acc No 308: 7-8-76, To Mary Yonge. (7 August 1876).

[8] Geoffrey Holt, ‘[Coleridge, Henry James (1822–1893)](../other_books/otherbook_82.qmd)’, *Oxford Dictionary of National Biography*, Oxford University Press, 2004; C. A. E. Moberly, *[Dulce Domum: George Moberly, His Family and Friends](../other_books/otherbook_122.qmd)* (London: Murray 1911), 94; Ellen Jordan, ‘[Charlotte Yonge’s First Publishers](../other_books/otherbook_89.qmd)’, unpublished paper given to the Charlotte Mary Yonge Fellowship (April 2005), 5.

[9] To Anna Butler (15 June 1857).

[10] A. J. Butler, *[Life and Letters of William John Butler, late Dean of Lincoln](../other_books/otherbook_26.qmd)* (1897); George Herring, [‘Butler, William John (1818–1894)’](../other_books/otherbook_581.qmd), *Oxford** Dictionary of National Biography*, Oxford  University Press, 2004; information from the Community of St. Mary the Virgin.

[11] The letters to Barnett were inherited by her niece, Emma (Butler) Knight, who lent them both to Coleridge and Romanes for their biographies, but we have not traced the originals.
[12]‘All the little Sunday books in those days were Mrs. Sherwood’s, Mrs Cameron’s, and Charlotte Elizabeth’s, and little did my mother guess how much Calvinism one could suck out of them, even while diligently reading the story and avoiding the lesson.’  Coleridge, *[Life](../other_books/otherbook_40.qmd)*, 97.

[13] [‘Lifelong Friends’](../cmy_books/cmybook_292.qmd) (1894).

[14] Coleridge, *[Life](../other_books/otherbook_40.qmd)*, 164.

[15] Owen Chadwick, *[The Spirit of the Oxford Movement](../other_books/otherbook_33.qmd)* (Cambridge: Cambridge University Press 1990), 26, 138.

[16] Gavin Budge, [‘Realism and Typology in Charlotte M. Yonge’s *The Heir of Redclyffe*’](../other_books/otherbook_22.qmd) *Victorian Literature and Culture *31 * *(2003), 193-223,  and  Elisabeth Jay,  [‘Charlotte Mary Yonge and Tractarian Aesthetics’](../other_books/otherbook_88.qmd)*Victorian Poetry* 44 (2006) 43-59, analyse CMY’s work in the context of Tractarian literary theory and reading practice.

[17] This idea was not original, nor exclusively the property of High Church Anglicans:  a similar idea is expressed in what was still in the mid-Victorian period one of the most popular textbooks for teaching children to read, Anna Laetitia Barbauld, *[Hymns in Prose for Children](../other_books/otherbook_15.qmd)* (London: Johnson 1781), vi-vii: ‘by deep strong and permanent associations, to lay the best foundation for practical devotion in future life.’

[18] Coleridge, *[Life](../other_books/otherbook_40.qmd)*, 191.  To Mary Anne Dyson (23 February 1853).

[19] Friedrich, Freiherr von la Motte Fouqué (1777-1843), German novelist, was the author of numerous allegorical romances*. * Newman and Keble both valued them highly, and they are frequently referred to in CMY’s fiction and correspondence.

[20] Moberly, *[Dulce Domum](../other_books/otherbook_122.qmd)*, 11.
[21]MS British Library Add MSS 54921: 80- 81, To Alexander Macmillan (29 January 1879).

[22] *[The Heir of Redclyffe](../cmy_books/cmybook_15.qmd)*, like *[The History of Sir Charles Grandison](../other_books/otherbook_362.qmd)* (1754) , is the story of a baronet who overcomes his inherited bad temper;  it is an experiment in the fictional portrayal of a good man;  Sir Guy Morville explicitly mentions his devotion to the earlier novel, and we are meant to understand a dialogue between the two books.

[23] This point is of interest, in the light of recent critical interpretations of *[Mansfield Park](../other_books/otherbook_582.qmd)*, as evidence that at least some early Victorian readers of the novel may have been capable of interrogating it from the anti-slavery point of view.

[24] ‘Probably it is this element of feeling which marks the vague distinction between the old-fashioned high churchmen and the Oxford men, the desire to use poetry as a vehicle of religious language, the sense of awe and mystery in religion, the profundity of reverence . . a concern for the evocative and the reverent, a sense of the whispering beauty and truth of divinity as its presence surrounded the soul.’  Chadwick, *[Spirit of the Oxford Movement](../other_books/otherbook_33.qmd)*, 19.

[25] To Mary Anne Dyson ( 1850).  Jay, [‘Tractarian Aesthetics’](../other_books/otherbook_88.qmd), 50, cites the parallel comment of Laura Edmonstone in *[The Heir of Redclyffe](../cmy_books/cmybook_15.qmd)*.

[26] Kate Caergwent, in *[The Pillars of the House](../cmy_books/cmybook_109.qmd)* (1873) Chapter 39*.*

[27] *[Hopes and Fears](../cmy_books/cmybook_37.qmd)* (1860), Chapter 26.

[28] Many of CMY’s subsequent works, including *[The Trial](../cmy_books/cmybook_53.qmd)* (1864) and *[The Two Sides of the Shield](../cmy_books/cmybook_184.qmd)* (1885) * *explicitly address this kind of generational conflict.  Budge, [‘Realism and Typology’](../other_books/otherbook_22.qmd), 203 ff, discusses the conflicts between realism and typology in her work.
[29]MS Mrs Clare Roels. To Christabel Rose Coleridge (19 
September 1899).
[30]L.A. De Gruchy ‘ [“*The Monthly Packet*” : a study of C.M. Yonge's Editorial Aims and Practice’](../other_books/otherbook_51.qmd). University of London MPhil thesis (1986); Amy de Gruchy. [‘*The Monthly Packet*.’](../other_books/otherbook_50.qmd) *Proceedings of the Inaugural Conference of the Charlotte Mary Yonge Society Fellowship.* (1995);  1–40. June Sturrock, [‘Establishing Identity: Editorial Correspondence from the Early Years of *The Monthly Packet*'](../other_books/otherbook_158.qmd) *Victorian Periodicals Review* 39.3 (2006) 266-279.

[31] We are extremely grateful to Messrs Hoare and Co. for permission to transcribe and to quote from the ledgers recording transactions in CMY’s bank account.

[32] Her statement to Elizabeth Roberts (31 January 1852) that ‘the publisher only promises me £30 for the year’, suggests that he may literally have paid her the sum which she then distributed among contributors including herself.  The account, however, does not definitely prove this.

[33] ‘for a long time it seemed a point of honour, and perhaps of duty, with me to spend none of it on myself.’ [‘Lifelong Friends’](../cmy_books/cmybook_292.qmd) (1894).

[34] On Lydia Sellon and her coadjutor Catherine Chambers see Peter G. Cobb, [‘Sellon, (Priscilla) Lydia (1821–1876)’](../other_books/otherbook_36.qmd), *Oxford Dictionary of National Biography*, Oxford University Press, 2004.
[35]To Anne Yonge (1 December 1854).

[36] Coleridge, *[Life](../other_books/otherbook_40.qmd)*, 184, 265-6.

[37] This may also partly represent money collected by her from *MP* readers.

[38] To Mary Anne Dyson (9 June 1854).

[39]  From the Rev. John Coleridge Patteson to Charlotte Mary Yonge (21 December 1859).


## Letters

{{< include _1850-1859_letters.md >}}
