---
title: "Letters 1870-1879"
listing: false
decade_label: "1870-1879"
post_id: 3740
letter_id: "letters-1870-1879"
---

**INTRODUCTION TO LETTERS 1870-1879**

At the opening of the 1870s Yonge’s mother was recently dead, but in other respects the pattern of her life seemed set to continue much as usual.  In a life so quiet and regular as hers, however, small changes were deeply felt, and to read her letters in bulk is to feel that from this point on she was increasingly often accommodating herself, with varying degrees of reluctance, to the arrival of unwelcome change.  However, though she appears now in some ways, as she did to many of her younger contemporaries, as a figure of exaggerated conservatism, it was fundamental to the character of her life that her activities were almost invariably conceived in a spirit of reform, and that she was concerned with the problems of the modern world.   For all her loyalty to the past, she was nearly always willing to acknowledge that things could not stand still, and that it was not desirable that they should. The idea is given forceful expression by one of her best-loved characters:

‘It’s not one youth in a hundred that if he is moderate enough to stop with what satisfied our - my -generation, has anything in him.  Why, as I saw it well put the other day - Ethel was delighted with the notion - King Arthur tried to work up the Round Table, and because Christian chivalry had raised that generation, comes the Quest of the Sancgreal to lead them higher.  ‘Tis one of the tests of life whether we will take to our Quest and let others take to it.  Tying them down to our Round Table does no good at all.’[1]

Continuity was very dear to her.  As editor of the same magazine for forty years, as teacher as the same village school for sixty years, as novelist who returned again and again to the same characters and their descendants (several in both 1847 and 1900), she was also deeply conscious of change.  If her vast historical reading had not made her an historical relativist, it had at least accustomed her to the fact that each generation revises the ideas of the past.  She was a fair-minded woman and a humble one, and that meant that on several issues she changed her ideas quite dramatically:  obvious examples being her views on the suitability for women of higher education, medical training and public speaking.  One could see that simply as a delayed and unwilling acceptance of the inevitable, but the way she repeatedly goes out of her way to express in her fiction a revision of an earlier position suggests that her engagement with progress was inspired by intellectual honesty, and was creatively stimulating.  Thus she was seldom in the vanguard, but her novels document, on a scale few of her contemporaries attempted,  what the experience of change felt like to those who lived from 1840 to 1900.[2] All her favourite subjects, the status and employment of women, the liturgical and ecclesiastical life, class relations and class status, the education of men and women of all classes, were affected by the huge social upheavals of the nineteenth century, and her treatment of them reflects this.

So what then were the changes with which she had to contend personally?  Two events of the 1870s had a significant impact on her private life, and in neither case do we know the full story.  In 1872 Gertrude Walter, the younger sister of her brother’s wife, who suffered from a disabling and progressive illness, came to live with her.  This certainly had the effect of limiting her movements, particularly in later years, and perhaps it also tended therefore to narrow her experience.   More important still was the financial crisis which overcame her brother Julian Yonge in 1876.  In the short term this led to her giving him a large sum of money and it appears also to have led ultimately to her assuming responsibility for the support of him, his wife and their six children.  There can be little doubt that a deliberate attempt was made by Yonge and her friends to suppress the details of this business as far as possible, but enough evidence survives to indicate that she lived with the consequences for the rest of her life.  The increasingly restricted life which she led may perhaps have had as much to do with the wish to save money as the need to look after Gertrude Walter. Other events of the decade which were important to her were the arrival in 1871 of a new curate, who was to become the first Vicar of Otterbourne in 1876 with its endowment as a separate parish; and the dissolution in 1877 of the Gosling Society.

To one so loyal to childhood associations the departure in 1870 of the Rev. William Bigg Wither, who had been curate in charge of Otterbourne since 1834, was inevitably a blow.  Coleridge’s biography and the surviving letters do not adequately account for this move on his part, but it seems not unlikely that there was some failure of sympathy between him and the Rev. James Gavin Young (1818/9-1906), who had become Vicar of Hursley and Rector of Otterbourne after Keble’s death in 1866, and whose name is mentioned by Yonge remarkably seldom.[3] Although she came to value the new curate of Otterbourne, the Rev. Walter Elgie, and took pleasure in his young family, his arrival precipitated a reform of the village schools. This process, as Elgie’s widow delicately explained, represented an implied criticism of the old order which hit Yonge hard:

The schools were always very near and dear to Miss Yonge’s heart;  she had taught in       them from childhood, and loved them, and was proud of them. Judge of the pain she  must have felt when told (however gently) that the schools were not up to date, that they should be under Government, and properly inspected.  It was a terrible blow! First the schoolmistress (an  excellent person, and much loved by her pupils) resigned         at once, then the schoolmaster did the same, and the whole village would have been  up in arms had it not been for Miss Yonge.  She saw that times were changed, that it was impossible to go on for ever in the same groove, and with a great and noble effort, she determined to support the new clergyman.[4]

Nearly twenty years later, after Elgie’s death, Yonge was to depict such a village drama, in *Our New Mistress, or, Changes at Brookfield Earl* (1888).  The ructions surrounding the transformation of a rural dame school, patronized by the gentry and the parson, into an institution staffed by government-trained teachers, are humorously depicted, but, though the novel favours the reformers, the conflict between reform and conservatism it depicts was no doubt one she felt within herself.

The demise of the Gosling Society was also connected to the rapid pace of contemporary educational reform.  After ten years the Gosling Society had lost most of its early members and some of its initial impetus; Yonge was inclined to lament the feebleness of the new recruits, and she seems to have known them less intimately than their predecessors.  In January 1873 an essay society, the Spiders, was started in the *Monthly Packet*, and after a few years in which the two organisations, private and public, ran simultaneously, it was decided in autumn 1877 to wind up the Goslings, who were invited to submit their essays as Spiders instead.  No doubt this decision was partly influenced by Yonge’s increasing anxiety about money, which made her inclined to withdraw from something so time-consuming which benefited a comparatively small number of girls.  However she also explained her decision in relation to the proliferation of similar operations: ‘It seems therefore time to break it up, since there are other essay societies in plenty now’[5] What had been innovative was now commonplace, and that was because the education of young women was now a topic of widespread concern.  Almost immediately she drew on her Gosling experiences in fiction:  the short novel* The Disturbing Element, or, Chronicles of the Blue-bell Society * (1878), in which an invalid spinster supervises some local girls for  public examinations, is a contribution to contemporary debate over the education of upper middle-class girls, a topic whose urgent importance is never disputed in her work.  As the letters show, she was highly conscious of the rapid changes taking place in this area.[6] The Cambridge Local Examinations were opened to women in 1865 and the Oxford Local Examinations in 1870, and Yonge seems to have approved.  In *The Pillars of the House* (1873) she had Robina somewhat anachronistically preparing for them in 1864 and in *Womankind* (1877), 33-4, she wrote: ‘No professional teacher now under twenty-five *ought* to be engaged for girls over fourteen, who cannot produce a certificate from a University.’ On the other hand she seems to have felt that examinations could inhibit wide-ranging reading and discussion of the kind, for example, that she was encouraging in the Goslings.  As early as *The Daisy Chain* (1856) she had contrasted the mere book-learning which Norman May’s school rivals have, disadvantaged by  ‘not living at home with their sisters and books’;  and a similar distinction is drawn with particular reference to the education of girls in *The Two Sides of the Shield* (1885) and in the story ‘Come to her Kingdom’ *MP* (Christmas 1889).

It has long been known that Julian Yonge became responsible for the debts of a coal company of which he was a director, and that in about 1876 his sister spent on his behalf a large sum of money.  Christabel Coleridge describes the episode briefly:

In 1875 Otterbourne and Hursley were divided, and Otterbourne was made into a separate parish. It was Charlotte’s intention and her great desire to give a large sum of money for the endowment of the new parish to which she was so much devoted;  but about the time when this was in contemplation, there occurred the failure of a company in which Mr. Julian Yonge had a considerable interest, and serious money losses were in  consequence incurred by the family.  Under these circumstances Mrs. Gibbs, of Tyntesfield, provided the sum necessary for the endowment of St.  Matthew’s, Otterbourne, and I have heard Charlotte say that since the interests of the parish did not suffer, she had only rejoiced in being able to devote her earnings to a yet nearer and dearer claim. [7]

Writing within a reticent tradition, while Julian Yonge’s widow and five of his six children were still living, one daughter Yonge’s literary executrix, Coleridge not surprisingly does not elaborate on the precise nature of the arrangements which were made.  There is more detail of this nerve-wracking period in the summer of 1876 in the letters Yonge wrote to Mary Yonge at Puslinch, although even those do not really give a clear picture either of Julian Yonge’s precise financial position or of the extent to which his sister subsequently made herself responsible for the support of his family.  In 1876 the family consisted of Julian, aged 46, his wife Frances, 37, and their children, Helen, 16, Arthur, 15, Alethea, 13, Maurice, 9,  George 5 and  Joanna, 3.  Her concern, one can hardly doubt, was to contrive somehow that things should go on apparently as before, that on the surface the family at Otterbourne House should continue to figure in parish life as it had done in her childhood, that her brother’s children should not lose caste.   The evidence which these collected letters present will leave the attentive reader with the impression that although in public this effort was successful, there was much private anxiety, humiliation and loss.  Julian Yonge is a shadowy figure, and there is not enough evidence to judge him.  Was his health genuinely shattered?  Was he a shameless leech on his sister? Did he limp on, acting the country gentleman, in circumstances where he should have retired quietly to a small town on the continent?  Her letters show him occasionally attempting to gain employment, and to place articles in periodicals, but the only definite sight we have of him earning money is as a translator, no very lucrative trade.[8] It is apparent from the correspondence with Macmillan  that the series of translations of French histories and biographies which appeared ‘edited by Charlotte M. Yonge’ were probably mostly translated by him.  There are only hints, however, of the strain which this must have put on relationships between the two houses.

The evidence from Yonge’s bank account does cast some light on these affairs, although much remains obscure.  In March 1876 she borrowed £500 from Hoares and paid it to Julian.  In July she borrowed a further £2500 which was paid to F. Cooper. This was presumably used to settle with Julian’s creditors.  Payments to Julian, his wife, his children and their schools continue to feature heavily in the bank account from this point on and it is also quite probable that other payments on their behalf are masked by the names of local tradesmen.

A possible source of information on this subject is unfortunately not as helpful as it might be.  Almost twice as many letters survive for the 1860s than for any other decade, and one reason for this is the copious quantity of letters to her principal publisher, Macmillan and Co, which survive in the vast archive in the British Library.  For some years in the 1860s enough letters survive to convince one that the entire correspondence has been preserved. However, with the end of that decade the pattern changes. Whether by accident or design, there are many fewer letters from the 1870s.  Yet that decade was highly important in her dealings with them.  As early as March 1875 she was concerned to know how much money she could raise on her copyrights (she still owned most of them),  and she recurred to the subject in February 1876, undoubtedly because of anxiety about Julian.  Whatever the missing letters might have told us, it is clear enough that in July 1877 she took the important step of selling to Macmillan the copyright of nineteen of her major works for £1000 and a royalty of 1/6 of the selling price.[9] Though she was actually to receive the sum in two payments of £500 in March 1878 and March 1879, and probably raised the money for Julian in the short term by selling government stock, it is hard to doubt that this was a reaction to his problems.  Oddly enough, it was this decision which led to the publication of her Collected Works, so that we probably have Julian Yonge to thank for the brown-and-gold volumes, and later the blue-and-gold volumes, whose mass production in the late nineteenth century kept Charlotte Yonge on the shelves of second-hand bookshops and introduced her work to many of her current readers.

These changes, and her reactions to them, are of more than merely biographical interest because the work she was doing at this time was so intimately connected with the various issues they raised on a whole range of subjects including money, class, education, women’s work, the landowner’s social role and  the relationship between Church and State.  Some critics have detected a decline in the quality of her writing in the 1870s, and have attributed it to the sudden need for money after Julian’s disaster.  Others have felt that Gertrude Walter’s presence was inhibiting to her.[10] It is certainly tempting to notice that she did some excellent work in the period just between her mother’s death and Gertrude’s arrival.   In 1873 she published both *The Pillars of the House, *one of  the most powerful of all her fictions,  and* *her moving *Life of John Coleridge Patteson*.[11] The two books have fundamental connections, both being much concerned with questions of self-sacrifice and ambition.   *Patteson* is avowedly a hagiography, the life of one whom Yonge regarded as a saint and martyr.  *The Pillars of the House* is a novel of domestic life, as copious and detailed as *The Daisy Chain*.  One is the true story of a young clergyman who goes out to convert the inhabitants of the Solomon Islands to Christianity and is killed there, and the other is an imaginary story of Felix Underwood, who as a boy becomes a bookseller’s clerk to help support his family and dies young having sacrificed his social position and his chances of romance to his duty.  Both men, of course, are conceived as shadows of the Divine Ideal, each is engaged on the imitation of Christ.  The first book shows that even in the modern world the chance exists to make the supreme sacrifice in preposterously exotic and uncomfortable surroundings,   The second shows that it is possible to be heroic in the most humdrum surroundings possible, to be a martyr to the snobbishness of a small provincial town, and by doing your duty in small things.  (It is an irony that the true story is so much the more romantic of the two.)   Different as the careers of Felix and the Bishop were, each deliberately gave up the life of a conventional upper-class Englishman which was his birthright.  Patteson turned away from the life of a brilliant well-connected young clergyman, from family life and friends, to be a missionary in the Pacific, yet Yonge’s account is so penetrated by the glory of the cause that she rarely conveys in her biography the real sacrifices he must have made.  In the novel, however we are made to feel the full measure of the loss of caste which is involved in Felix’s decision to leave school and become a tradesman, to give up the use of the style Esquire in his correspondence, to live above the shop and clean his own shoes.  Clearly, like so many Victorian novels, from *Great Expectations *to *John Halifax, Gentleman*, the book is concerned with the definition of true gentlemanliness.  Though Yonge does not abandon the idea that a family tradition of gentility is a support to a full moral life, she examines the moral issues around social status more critically than in her earlier work. In *The Pillars of the House* the humbling of the Underwoods, and the hard work which it has entailed, is an ordeal which is ultimately shown to have ennobled most of them, in particular Felix.   In both books the question of self-abnegation links to a theme which had long preoccupied her:  the evaluation of the social pressures which require upper-class men to be ambitious of worldly success.    This is of course a familiar pattern in women’s writing: she was by no means the first woman novelist to locate virtue in the feminine virtues of unselfishness, dutifulness and service, but her singular ability to show how a major spiritual battle can be played out in the most mundane circumstances gives her exploration of this theme exceptional vividness and force.   Again and again in her fiction clever, ambitious young men are humbled, and are made to recognise that the kind of self-abnegation which is required of their sisters is equally demanding and more Christ-like than male qualities such as competitiveness, love of glory and the desire to dominate others.  Norman May in *The Daisy Chain* is the archetype of the feminine hero who is offered the glittering prizes of worldly success and turns away from them to serve God, in his case by going out as a missionary to New Zealand.  The ultimate models for this story of  the man rejecting the public world to do good in private were probably the two idols of her childhood:  her father and John Keble, each of whom in their different ways had chosen family over career, and a kind of service which was not likely to gain public reward.

However, though the themes of *The Pillars of the House* are in a sense characteristic of all her work, so that one can see it as a culmination of the early period of her writing, its focus on the family of a struggling tradesman in a provincial town means that it covers a broader range of society than most of her earlier novels.  Though it is still enormously preoccupied with the question of gentility, its definition of the genteel is much less exclusive than before.  If one compares it with *Heartsease* (1854) it is striking how much less restrictive her sense has become of the ways in which an educated man or an educated woman might live.  She permits Geraldine Underwood the artist’s training she had deprecated in reality for poor Katie Johns, and the right of women to work is explored in relation to several different characters.* *

This sense of an opening-up of possibilities continued in the later work of this decade, which included two other substantial and interesting modern novels for adults: ** ***The Three Brides* (1876) and *Magnum Bonum* (1879).   The former is a study of the family dynamics of a matriarchy;  a situation in which a widowed invalid heiress lives in her own house with her five sons and three daughters-in-law.  The scene returns to the upper ranks of the landed gentry, and includes some unsympathetic caricatures of feminist campaigners.   June Sturrock has suggested that

In the 1870s - a decade in which she herself began to feel the need for money - Yonge      becomes increasingly engaged with the economic aspects of women’s work.[12]

Perhaps *The Three Brides*, though, is less concerned with work than with power relations between men and women and between the community and the individual: who ought properly to exercise power in society?  What do we do with husbands, fathers, clergymen, mayors, landowners, who do not use their power well? *Magnum Bonum* also imagines an oddly-shaped family which tests the available models of authority.  Instead of a brother and sister with ten younger siblings, as in *The Pillars of the House*, or the crippled mother surrounded by adoring sons of *The Three Brides*, its heroine is a bohemian, child-like widow who earns money as an artist and draws into her orbit a stray orphan and several nephews and nieces.  It is a pity that the novel’s core plot (a miracle cure which must be kept secret) should be so preposterous, because the large cast of characters are as vivid as ever, and Yonge keeps them moving about, socially and geographically, more than in any previous novel, suggesting that she was interested in the new kinds of identity created by a more fluid society.

The six other fictional works of the decade are as usual quite various in style: *The Caged Lion* (1870) and *Lady Hester* (1874), being historical tales  *P's and Q's* (1872) and *The Disturbing Element* (1878) modern stories for girls, *Burnt Out* (1879), addressed to village women, and  *My Young Alcides *(1875), based on the Labours of Hercules, illustrating Yonge’s continuing fascination with allegory and typology and their use in realist fiction.  Seventeen non-fictional works (at least) bearing her name were also published in this period;  the letters of this decade to Elizabeth Missing Sewell and Edward Augustus Freeman show how much of her attention was devoted to writing history textbooks.  But in an era in which the practice of history was being rapidly professionalised, the techniques which had hitherto sufficed when writing for the schoolroom were rapidly becoming out of date. Freeman’s own correspondence with Macmillan reveals his impatience with her amateurish approach, though he found her touchingly willing to take his criticism, the role of pupil being ever congenial to her:

I have no doubt that she knows the mere run of the story much better than I do;  but she never catches any of the points, never brings out the great landmarks, all on, on, on, and such sentences - Oh how long!  . .   What is to be done?  I shall be thoroughly ashamed to see my name as editor of such stuff . .  And all the time she is so good, a perfect saint for taking reproof.[13]

Her reaction to the scathing review by Mary Augusta Ward of *The Story of the Christians and the Moors in Spain *(1878)* *shows what Freeman meant about her humility.[14] Ten years earlier, the teenage Mary Arnold had been glad to receive Yonge’s comments on her essays for the Gosling Society:  now she was able to condescend to her former mentor’s ignorance. Ward’s suggestion that she was losing touch was one which would be made increasingly often as the years went on.

Why does Miss Yonge write so much and so hastily?  The present book is altogether unworthy of her, in spite of its cleverness, and ought to be a matter for real regret to those who are sensible of her past services to educational literature.

Although it does seem likely that Yonge’s remarkable productivity was stimulated by the need to provide for Julian’s family, it must be remembered that the composition of textbooks was scarcely the most lucrative work she could have undertaken: as before there was a strong philanthropic and conscientious motive behind everything she undertook.  However these criticisms were early signs of the decline which was to overtake her reputation in her later years.  Comparatively isolated from the company of her intellectual equals, a specialist in providing safe reading for the children of a clique, she was not well-positioned to escape being stigmatized as an amateur in an age of professionalization, or being patronized as a mere middle-aged provincial spinster.

[1] Dr. May, in *[The Pillars of the House](../cmy_books/cmybook_109.qmd)*, II, Ch. 35, 284.  He is talking specifically about the ritualism which was flourishing among the younger generation and which appalled some of the older Tractarians, but the spirit of the remark can be extended to Yonge’s attitude to other youthful enthusiasms.

[2] Georgina Battiscombe, *[Charlotte Mary Yonge: The Story of an Uneventful Life](../other_books/otherbook_17.qmd)* (London: Constable 1943), 123, makes this point: ‘This preoccupation with the problem of progress was to mark all the later books’.

[3] This inference may well be unjustified.  The population of Hursley, Otterbourne and Eastleigh grew dramatically during the second half of the nineteenth century, and  Otterbourne parish became independent of Hursley in 1876;  perhaps it was natural that CMY saw less of the Vicar of Hursley.  The Rev. James Young was the younger brother of Keble’s former curate the Rev. Peter Young.

[4] Catharine Elgie, in Christabel Coleridge, *[Charlotte Mary Yonge: Her Life and Letters](../other_books/otherbook_40.qmd)* (London: Macmillan 1903), 263.

[5] To Mary Penelope Fursdon (29 September 1877).

[6] To Edward Stuart Talbot (?1875), about the foundation of Lady Margaret Hall, Oxford; To Christabel Rose Coleridge (13 February 1877), about the Cambridge Local Examinations; and To Miss Barter (21 October 1877), about the foundation of Francis Holland School, Clarence Gate.

[7] Coleridge, *[Life](../other_books/otherbook_40.qmd)*, 273.

[8] See To Hezekiah Butterworth (24 February 1877);  To the Reverend Edward Atkinson (28 April 1877); To the Reverend Bartholomew Price  (1 June 1877).  The following advertisement, which seems to have been unsuccessful, also appeared in *The Times* (12 July 1876), 13b: ‘To Guardians - A comfortable HOME is offered for two or three sisters, over 16, in a gentleman’s family in Hampshire.  An excellent neighbourhood.  Good references will be given and required.  Address J. B., care of Miss Yonge, Otterbourne, Winchester.’

[9] BL Add MSS 54921: 26-27 (17 July 1877).  The receipts are BL Add MSS 54921: 54 (12 March 1878) and BL Add MSS 54921: 88 (8 March 1879).

[10] Battiscombe, *[Life](../other_books/otherbook_17.qmd)*, 145.

[11] *[The Pillars of the House](../cmy_books/cmybook_109.qmd)* was actually published in *MP* from January 1870-December 1873, but it was already half-written by January 1870.  See To Christabel Rose Coleridge (28 January 1870).  *[Patteson](../cmy_books/cmybook_102.qmd)* was begun in January 1872 and finished by October 1873.  The story that she said to the Moberlys ‘I have had a dreadful day, I have killed both the Bishop and Felix’ is told by Battiscombe, *[Life](../other_books/otherbook_17.qmd)*, 134-5.

[12] June Sturrock, ‘Women’s Work, Money and the Everyday - the Novels of the 1870s’ in *[Characters and Scenes: Studies in Charlotte M. Yonge](../other_books/otherbook_583.qmd)* ed. Julia Courtney and Clemence Schultze (Abingdon: Beechcroft 2007) 87-104, 87.
[13]Cecilia Bass, [‘Aunt Charlotte, Historian:  A Jaundiced View’](../other_books/otherbook_584.qmd) in *The Review of the Charlotte M. Yonge Fellowship* No. 9 (Summer 1999), 5, citing *[Letters to Macmillan](../other_books/otherbook_585.qmd)* ed. Simon Nowell-Smith (London: Macmillan 1967) 125-7.  Susan Walton , [‘Charlotte M. Yonge and the “historic harem” of Edward Augustus Freeman’](../other_books/otherbook_586.qmd) *Journal of Victorian Culture *11 (Autumn 2006) 226-55, makes the case that Freeman’s denigration of Yonge’s work was unjustified and explores the context in which history was becoming the preserve of male professionals.  Freeman reiterated the point about the length of CMY’s sentences in a letter to Edith Thompson, another contributor to the ‘Historical Course for Schools’ :  ‘each of Aunt Charlotte’s sentences needs to be broken into 1000 pieces . . . she gives me more trouble than all the rest of you put together’.  See Amanda Capern, [‘Anatomy of a Friendship:  E A Freeman and Edith Thompson’](../other_books/otherbook_587.qmd) *Paragon Review* (1997) 
at www.hull.ac.uk/oldlib/archives/paragon/1997/anatomy.html.

[14] To Alexander Macmillan (10 November 1878), referring to the signed [review](../other_books/otherbook_588.qmd) by Mary Augusta Ward in *Academy *(16 November 1878) 463-4, quoted here.  Laura Fasick, [‘The Quandary of Influence: The Case of Mary Ward and Charlotte Yonge’](../other_books/otherbook_589.qmd)* English Literature in Transition* 37 (1994) 141-154, discusses the context of Ward’s turn against Yonge.


## Letters

{{< include _1870-1879_letters.md >}}
