---
title: "Letters 1880-1889"
listing: false
decade_label: "1880-1889"
post_id: 3750
letter_id: "letters-1880-1889"
---

**INTRODUCTION TO LETTERS 1880-1889**

Charlotte Yonge was involved with several campaigning groups from childhood, but during the 1880s an increasing amount of her time appears to have been taken up by such work.  In the last quarter of the nineteenth century there was a marked increase in the development of women’s organisations.  These provided opportunities for women to participate in social, religious, political and educational work on a much larger scale than hitherto. Although many such organisations included radical elements, there were others which were perfectly congenial to those who, like Yonge, could only operate within institutions which were both socially and politically conservative and utterly respectable.  Of these the most important to her were probably the Girls’ Friendly Society and the Mothers’ Union. The G.F.S., founded in 1875 by Mary Elizabeth Townsend to help Anglican working-class girls, is mentioned with increasing frequency, especially in letters to Christabel Coleridge, who was herself much involved in its work. Another great enthusiasm was the Mothers’ Union, founded in 1885 by Mary Sumner, a clergyman’s wife like Mrs Townsend.  Yonge mentions in March 1881 that Mothers’ Meetings had begun in Otterbourne in the previous winter. At the same time she of course continued to have important relationships with societies and institutions which included both men and women.  The movement for the promotion of cooperation between clergy and laity of the Church of England, which led to the establishment in the 1860s of annual Church Congresses and Diocesan Conferences, had her full support, which is reflected in frequent allusions to such events. The names of other organisations litter the pages of her correspondence: the Diocesan Society for Higher Religious Education,  the Society of Watchers and Workers, the Society for the Propagation of the Gospel in Foreign Parts, the National Society for the Education of Children in the Principles of the Church of England. In fact it would be impractical to list all the various organisations, charities and societies which are from time to time mentioned favourably in the *Monthly Packet* or referred to in Yonge’s letters.  Her description of the amount of her time these activities occupied, considering that she continued with her Sunday and day school teaching, and her many other interests, make her continued publication rate (25 volumes of fiction this decade) simply staggering.

As well as supporting these groups actively by practical and committee work, she continued to use her literary earnings to contribute substantially to philanthropic projects. Her bank account shows regular subscriptions to the Hampshire Blind School, the Royal Hospital for Incurables, St. Augustine’s College (for missionaries), the National Society and the SPCK, as well as the large irregular payments to the Rev. William Selwyn, treasurer of the Melanesian Mission Fund, which probably represent the continuing income from *The Daisy Chain*, of the order of around £100 per annum. She also paid occasional quite large sums to Otterbourne School: £20 in 1885, £80 in 1886, £60 in 1887, £10 in 1889.  From 1884 she subscribed her annual guinea to the Society of Authors;  her support for this organisation is in keeping with her markedly professional approach to her own career and that of her many women writer protegées;  there is little in these letters to give support to the once-current view of her as a shy genteel amateur.

All the same, despite the continuing importance of her religious mission and her philanthropic social and educational work, there is no doubt that in her later years she was shouldering the burdens of her brother and his family at the same time. Her professionalism and her extraordinary output must have been partly shaped by the increasing personal importance of the money-spinning aspect of her work.  It appears that the affair of her brother Julian’s near-bankruptcy in the late 1870s, rather than being a disagreeable episode which was got over, had a permanent effect on her finances, and that it affected her outlook on life and the themes of her fiction.  The record is incomplete, of course.  However, a certain amount of information about the financial arrangements with Julian Yonge emerges from examination of the copy outletter book of Charles Wooldridge, a Winchester solicitor, which is Hampshire Record Office MS 70M92W.  More than a hundred letters to Charlotte Yonge, and others to her brother, her sister-in-law, her niece Helen and her nephew Maurice, exist for the period 1861-1901, the earliest letter to Charlotte Yonge being dated 6 July 1883.  They suggest that Julian Yonge had ceded his remaining property, which seems to have included some London houses in South Kensington as well as land and cottages in Otterbourne, to his sister in return for her intervention in his affairs.  The evidence from the account with Hoare’s Bank shows that throughout the 1880s she regularly paid large sums to her sister-in-law, and also made other payments which seem to relate to her nephews and nieces.  Unfortunately, the matter is not simple.  CMY had other bank accounts, and she lived at the end of her brother’s garden, so that this does not necessarily represent the sum total of the money she gave him one way or another.  Moreover, since the affairs of the two households were so involved it is far from clear that she was not for example, receiving rents on their behalf. Their other sources of income are not fully understood.[1] It should also be remembered that she was sharing a house with their other childless aunt, Gertrude Walter;  probably they collaborated on the support of their nephews and nieces.  It looks from the ledgers as if she was very generous, but we cannot be clear about the nature and extent of the arrangements.   All the same it seems worth showing that the record suggests that during the 1880s the task of supporting her brother and his growing family weighed on her to a significant extent, and that her earnings from writing were devoted as much to that task as to any charitable cause.

Between 1880 and 1889 Yonge paid her sister-in-law Frances irregular sums amounting to several hundred pounds each year, averaging just over £530 *p.a. *Other sums also seem to have been expended on behalf of her nephews and nieces.  The Mr Foster who was paid  £59 12*s* 8*d. *and* * £59 11*s* 9 *d. * in 1880, £61 13*s*. 5*d. * and £60 2*s.* 1*d. * in 1881 and £66 2*d. *in 1882 seems likely to have been Montague H. Foster, the proprietor of Stubbington House School, Fareham, where Maurice Yonge was a pupil during the 1881 census, and which specialised in preparing boys for the Royal Navy.  In 1881 payments begin to Julian and Frances’s 20 year-old son Arthur.[2] What profession he attempted to enter before he emigrated to America in about 1883 is not clear, but possibly he was a medical student.[3] In 1882 Charlotte Yonge also paid ££46 10*s. 8*d. and £58 18*s.*11*d.* to Wimbledon School which probably represent school fees for Maurice Yonge, then aged 15.[4] More payments followed to a total of £188 2*s.* 2*d.* in 1883 and £204 2*d.* in 1884, both in three tranches.   In 1885 she paid £36 15*s.* to George Yonge, aged 14, quite a large sum, perhaps a term’s school fees, and £10 to his eldest sister Helen, aged 25.  In 1886 she also paid £39 17*s*. to Oxford Military College, which was perhaps George’s school.[5] In 1888 she paid Maurice Yonge two payments of £7 each, perhaps an allowance.   In 1889 she again paid Maurice what looks like an allowance, and also gave George £20.  In addition in this year there appears the first of four biannual payments of £70 to J. Mansergh, which could represent the cost of apprenticing Maurice to the distinguished civil engineer James Mansergh (1834–1905).

Of course we would need to know the size of her income to judge how generous she was being here, and the difficulty is that the credit side of her bank account is not necessarily an accurate gauge of her income.  Although throughout the 1880s sums of above £1200 appear each year in her account, some of it represents money with with she was to pay contributors to *MP, *money which was therefore not really hers.  Some of it represents income from writing, some income from investments, and some capital realized by selling investments. Occasionally she realised assets, or borrowed money, but for what precise purpose it is hard to be sure.   However, there is enough evidence here to see that her income, out of which she paid some money to *MP *contributors, was considerable, but that her brother and his family represented by far the largest single drain on her resources.  Most of the surviving correspondence tells us little about her personal finances, but the letters to Mary Yonge and from Charles Wooldridge help create a picture, partly substantiated by the bank account, of a woman earning a fairly large income, with many responsibilities and some serious anxieties.

It is not hard to find in the fiction of the 1880s preoccupations which may be plausibly related to the fact that she was involved so closely in bringing up and equipping for life these nephews and nieces with impoverished prospects.  The class of lesser gentry to which they belonged had anyway been hard hit by the agricultural depression.  Simultaneously, the new wealth of the expanding middle class was eroding the comparative advantage even of the more prosperous gentlefolk.  Growing national prosperity meant that the younger generation required as necessities what had previously been regarded as luxuries.  The position of the Yonges of Otterbourne would have been precarious without the financial disaster, and as it was they all, including Charlotte Yonge herself, had to accommodate themselves to a world in which the marginal advantage of being born well-connected and armigerous was fast diminishing.  Julian’s sons did not follow him to Eton, but went to some of the cheaper and obscurer of the newly founded public schools which were smoothing over the differences between the children of rich tradesmen, professionals and lesser gentry, creating a new kind of ruling class based more on education and ideology than on birth.  Yonge’s novels of this period are often absorbed in patrolling boundaries between classes, but they acknowledge and chart the relaxation of old taboos. An American reader who appears to have objected to her unsympathetic portrayal of Americans and criticised the snobbishness of her English characters elicited an interesting reply, dated 30 April 1889, now in the Parrish Collection:**

I think since the general depression there has been much less fear of losing caste among Gentlemen than even when the ‘Pillars’ were written. One of my friends, a General’s daughter, could not be reconciled to Felix going into trade. On the other hand, an invalid American lady with whom I corresponded for many years could not understand the different positions of Dr May and Henry Ward . . .

These issues arise often in her later novels. During the 1880s Yonge published a number of books which were sequels or variations on works which had succeeded in earlier years.  *Stray Pearls* (1881) was a sequel to the popular historical novel *The Chaplet of Pearls* (1868).  *Lads and Lasses of Langley* (1881),  *Langley Little Ones* (1882) and *Langley Adventures* (1883), were stories of village children following *Langley School* (1850).  *The Two Sides of the Shield* (1885) revisited the much-loved Mohun family who had first appeared in *Scenes and Characters* (1847) and who ultimately derive from *Le Château de Melville* (1839); they also appear in *Beechcroft at Rockstone* (1888), alongside other old friends from *The Daisy Chain* (1856) and *The Pillars of the House* (1873).   There are indications in the letters that this approach was urged on her by her fans.  It doubtless also appealed to that side of her which was nostalgic for the  past, ‘the dear golden age of our lives’.[6] However, in the case of *The Two Sides of the Shield * and *Beechcroft at Rockstone, *novels of modern life about upper-class families, the sequels also enabled her to comment on the changes which she had witnessed in her lifetime, and especially to investigate the phenomenon which had been christened as early as 1868 ‘the girl of the period’.[7] The typical heroine of Yonge’s early work is a semi-autobiographical figure,  brimming with enthusiasm for missionary and social work, history, chivalry and church-building.  The question whether this heroine could be mapped onto the bicycling, exam-taking, scientifically-trained and emancipated young woman of the 1880s is increasingly a topic of her fiction, and is the main theme of the only other modern novel for adults of this decade, *Nuttie’s Father* (1885).  In this book she contrasts middle-class and mercantile society in a provincial town with the gentry society which in most of her fiction represents the norm, and valiantly attempts to celebrate the virtues of the former while remaining evidently more in sympathy with the latter.  Yonge seems to have herself felt this book was an unsuccessful experiment, but the fact that she attempted it at all indicates how her sense of her audience had expanded to encompass middle-class and urban readers as well as the squires and village people for whom she wrote her first fiction.[8] *Our New Mistress* (1888), whose heroine is a schoolmistress dealing with more or less troublesome pupil teachers, also shows Yonge focussing on lower middle-class and upwardly mobile characters in a way which is new.

That novel also reflects Yonge’s awareness, both as voluntary teacher and as educational writer, of practical issues (teacher training, discipline, examinations) in contemporary education policy.  During this decade alone she published (not counting several works to be used in Sunday schools and in religious teaching), at least eight textbooks: *English History Reading Books: Adapted to the Requirements of the New Code of 1880* (1881-3), *A Pictorial History of the World's Great Nations, From the Earliest Dates to the Present Time* (1882), *Historical Ballads, edited and annotated by C. M. Yonge;  Arranged to Meet the New Code of 1882, Schedule II., English* (1882-3), *Cameos from English History V: England and Spain* (1883),* Landmarks of Recent History, 1770-1883* (1883), *Shakespeare's Plays for Schools, abridged and annotated by C.M. Yonge (Standards vi and vii)* (1883-85), *Cameos from English History* *VI: Forty Years of Stewart Rule* (1887) and* Deacon's Book of Dates: A Manual of the World's Chief Historical Landmarks and an Outline of Universal History* (1888).  These appeared at a time of fierce educational controversy including opposition between, on the one hand, conservative Anglicans anxious to maintain control over Church of England schools for the working classes, and on the other, Gladstone’s second Liberal government of 1880-85, which began its educational work by making school compulsory for children between five and thirteen unless they had passed the fifth standard, and proceeded to reform the curriculum and the system of paying schools by exam results.[9] The trend towards a transfer of power to the local boards of education and the state was feared and resented by elements both in the Church of England and the Roman Catholic church.  Powerful Nonconformist elements in the Liberal party were keen to diminish the political power of the Anglican church, and in the election of November-December 1885 their opponents campaigned with some success by raising the threat of disestablishment.[10] Yonge’s view on this is not unexpected, but we have surprisingly forceful expressions of it here, which paradoxically is a reminder that the letters have to some extent been weeded deliberately.  To read only Christabel Coleridge’s selection would lead one to conclude that Yonge was too ladylike to comment on politics at all, and it is only because Ethel Romanes, in her much more slapdash and amateurish book, included excerpts from a whole series of letters to a young woman journalist named Gertrude Blackburne, that we learn of Yonge’s immensely strong feeling of opposition to Liberal education policy.  It is no surprise to find her supporting Church of England schools and deploring talk of disestablishment, but the strength of her expressions is startling, and is a useful warning that the comparative absence of controversial topics in her surviving correspondence does not necessarily prove that she never addressed them.

Alas!  Alas!  I feel they have given up to destruction all that is precious and holy.[11]

The letters of the 1880s tend to show, in fact, that far from being sheltered and isolated from the events of the decade which were to have such momentous consequences for life in Britain, she was in fact well aware of the seismic shifts in the balance of power, between rich and poor, men and women, Church and State, land and commerce, which were taking place around her.

[1] Much of Julian’s property was tied up in his marriage settlement, the income from which was requisitioned by his creditors.  It appears from Frances Yonge’s will that she also had an interest in a trust set up by a member of her mother’s family, the Coulthards.  A document relating to this is held by Messrs. Pennington, who were the Coulthards’ solicitors.  Unfortunately the relevant records of  Messrs. Houseman, who were CMY’s main solicitors, and Messrs. Crawley Arnold, who were Julian Yonge’s solicitors, have not been traced.  (Some of Houseman’s papers are in East Sussex Record Office, but nothing relating to the Yonges.)

[2] Several of the payments to Arthur are for £8, which might be a monthly allowance.

[3] The 1881 census lists only the youngest son George at Otterbourne House, but as his age is given as 19 and he is described as a medical student, when he was in fact only 10, it seems possible that Arthur, who was 19, was also present and that the two became one.

[4] Wimbledon School advertised in *The Times *(19 August 1879), 6d, that it afforded ‘a capital means of preparation for the different military competitive appointments’.

[5] This was a school for the sons of officers;  its fees were advertised in *The Times* (28 July 1887) 14a as ranging from 70 to 100 guineas, so this might represent a term’s fees.  George Yonge, aged 15, was probably a pupil there.

[6] To ?Charlotte Anne Elizabeth Moberly (October 1888).

[7] Eliza Lynn Linton, [‘The Girl of the Period’](../other_books/otherbook_591.qmd) *Saturday Review* (14 March 1868).  CMY, who was a keen reader of the *Saturday Review*, was using the phrase by 1872.

[8] ‘I don’t care much for Nuttie myself. I am getting too old to write of the swing of modern life; I don’t see enough of it.’ To Gertrude Mary Ireland Blackburne (?1885).

[9] W.H.G.Armytage, [‘A.J. Mundella as Vice-President of the Council, and the Schools Question, 1880-1885’](../other_books/otherbook_590.qmd) *English Historical Review *63 (Jan 1948) 52-82, 54.

[10] Alan Simon, [‘Church Disestablishment as a Factor in the General Election of 1885’](../other_books/otherbook_592.qmd) *The Historical Journal *18 (1975) 791-820, 815

[11] To Gertrude Mary Ireland Blackburne (?December 1885).


## Letters

{{< include _1880-1889_letters.md >}}
