---
title: "Letters 1890-1901"
listing: false
decade_label: "1890-1901"
post_id: 3752
letter_id: "letters-1890-1901"
---

**Introduction to the 1890s**

Charlotte Yonge went on living at Elderfield to the end of her life.  Christabel Coleridge’s biography rather implies that these last years were spent in a cloud of quiet cheerful domesticity, punctuated by visits from affectionate nieces, nephews and admirers. Perhaps that was how it seemed to Coleridge, but close scrutiny of the record suggests other readings of the situation.  The correspondence with Charles Wooldridge indicates that her brother’s family continued to be financially a worry, even after his death in 1891, which had closely followed the sale of Otterbourne House, which must have been a grief to her.  There is nothing in Coleridge’s biography about the marriage in October 1894 of her youngest niece Joanna Yonge, aged 21, to a man who had divorced his first wife;  no doubt letters deploring this event were written but they do not seem to have survived. Yonge was extremely upset by being ousted from the editorship of the *Monthly Packet* in 1893 because of its diminishing sales, and also by its final collapse in 1899.  She found Alexander Macmillan’s son and nephew less congenial to deal with than she had him.  She watched at close quarters the slow and painful death of Gertrude Walter.  However, unlike many old ladies, she still had wide interests and significant spheres of action.  As well as continuing to publish quantities of books and journalism, she was prominent in the Mothers’ Union and the Girls’ Friendly Society, she supported the Winchester Girls’ High School, she was active in Winchester Diocese and she still took part daily in the round of parish activities, from church decoration to schoolteaching, which had been the backbone of her routine for more than fifty years.  And from 1892 the Vicar of Otterbourne was the Rev. Henry Bowles, husband of her niece Alethea, whose young family she watched growing up:  she seems to have found these members of her family wholly congenial.

By the beginning of the 1890s most of Yonge’s readers could not remember a time when she had not published several books a year.  Her fiction and non-fiction were familiar in every corner of the empire.  Even in the house of the high-minded agnostic intellectual Leslie Stephen, her works were so familiar that the children’s newspaper, the *Hyde Park Gate News* contained, in the winter of 1891 when Virginia Woolf was nine, an Easy Alphabet for Infants, including ‘Y for Miss Yonge/	Who many things can tell . . .’ [1]  She was by now, immensely, internationally famous. However, there seems little doubt that she was already widely seen as a rather old-fashioned figure.  Christabel Coleridge contrived cleverly in the account of Yonge’s last decade in her biography to make a good deal of two occasions, in which Yonge, most untypically, made public appearances as herself (as opposed to as a worker for a charity):  the presentation to her (11 August 1893) of a book of autographs to commemorate her 70th birthday, and the inauguration (18 July 1899) of a Charlotte Yonge Scholarship at Winchester Girls’ High School.   Thus she managed to portray Yonge in her last years as surrounded with numerous youthful readers.  Though her work was undoubtedly still read by the young and her works were ubiquitous, it must have already been apparent that her longevity and respectability were tending to cloud judgment of her work, especially for a generation preoccupied with the gulf between itself and the early Victorians.  Several of her supporters commented on the way in which her late work was altering the way in which her early work was perceived, and on the prejudices which handicapped the assessment of her work. The feminist campaigner Bessie Rayner Parkes wrote in 1897 that to Charlotte Yonge 

justice has never been done by the literary critics. Her books have been 	injured in literary circles, by her loyal devotion to her convictions in regard to the Anglican Church.  But what would we not give for a record of the private life of England under the Tudors, with half the wit and insight of the *Heir of Redclyffe*?[2]

Annie Moberly wrote after Yonge’s death:

It is difficult for the present generation, which in these days has so much, to estimate the work accomplished by Miss Yonge.  Partly it judges of her and of her powers by the weaker work done in late middle life and old age;  partly it does not stop to think that when she began to write she had few rivals.[3]

And a novelist of the new generation like Arnold Bennett, then in his early thirties, could sneer at *The Heir of Redclyffe* confident that everyone knew of it, and confident that they would share his sense that it belonged to a past age.   [4]

Despite this undoubted tendency to treat her as an outmoded survival, she maintained an extraordinary rate of production, and much of her backlist remained in print at home and abroad, both in English and in translation.  Between 1890 and her death she continued to publish her usual annual Christmas story for the National Society, usually designed as a suitable reward book for good schoolchildren of all classes and both sexes: *The Slaves of Sabinus* (1890), *The Constable’s Tower* (1891), *The Cross Roads* (1892), *The Treasures in the Marshes* (1893), *The Cook and the Captive* (1894), *The Carbonels* (1895), *The Wardship of Steepcombe* (1896), *Founded on Paper* (1897), *The Patriots of Palestine* (1898), *The Herd-boy and his Hermit* (1899) and *The Making of a Missionary* (1900).   Of these the most interesting today are probably *The Carbonels* and its sequel *Founded on Paper*, which depict the religious and social changes in a thinly-disguised Otterbourne between the arrival of her parents in the early 1820s and the Diamond Jubilee of 1897.  They thus connect with other non-fictional works of this decade which mingle retrospection, reminiscence and local social history:  *Old Times at Otterbourne* (1891), *An Old Woman’s Outlook in a Hampshire Village* (1892), ‘A Real Childhood’ (*Mothers in Council*, 1892-3), and *John Keble’s Parishes* (1897), all of which contain, like *The Carbonels*, evidence both about herself and about the world she grew up in, and record her attitudes to the changes she had witnessed.   

As well as writing reward books for the National Society, Yonge also continued to write novels for educated adult readers, usually published by Macmillan.  There was little falling-off in the rate of production in this area either.  In her last decade she wrote both  novels which were sequels to earlier works, such as *The Long Vacation* (1895), *The Release* (1896) and *Modern Broods* (1900),  and novels which were not sequels, such as *The Two Penniless Princesses* (1891), *That Stick* (1892), *Grisly Grisell* (1893), *The Rubies of St Lô* (1894) and *The Pilgrimage of the Ben Beriah* (1897).    Her last novel, which never appeared in volume form, was ‘Forget-me-nots’, published in *Friendly Leaves* (January-November 1900), making a remarkable total of 20 works of fiction since 1890, or 21 if we include *Strolling Players* (1893), written with Christabel Coleridge.  To this we should add more than a dozen historical text-books, biographies and theological works. Yonge herself was rather deprecating about the late sequels, and several times suggested that they could only appeal to a dwindling band of elderly fans of her earlier work.  [5]   She also often commented on her increasing difficulty in seeing the point of view of the young and remaining in sympathy with it.  Still, the effort to do so is a marked feature of her latest work; as always, she was preoccupied with the effect of historical change on the relations between the generations.   Especially in *The Long Vacation* and *Modern Broods* she put it on the record that her views had changed about the propriety (or to use one of her favourite words, the maidenliness) of various activities, ranging from public speaking through bicycling to training as a doctor, which she had previously deplored for women.   She was ever conscious of the pace of change in her own lifetime, and she quite deliberately made her fiction a register of it.

It would though be misleading to suggest that she was not resistant to reform in some areas.  Much of her energy in the last decade of her life went into the Mothers’ Union and its journal *Mothers in Council*.  This organization was positively obsessed with the necessity for maintaining the influence of the old and the middle-aged upon the young, especially in the area of religious education. To read through the volumes of  *Mothers in Council* which came out under her editorship is to be introduced to much that seems now strikingly conservative and reactionary, in which Yonge’s contributions appear by contrast disarmingly sane and flexible.  All the same, her association with this pressure group probably exacerbated a tendency, not unexpected in a person in her seventies, to lament the dangers of the modern world, and to regret the past.  

The reasons for the decline in Yonge’s posthumous reputation need further investigation. The beginning of the twentieth century saw an extensive process of revaluation of literary property.  After the First World War, new maps of English literature were being created, and the past was extensively rewritten. Among thousands of small events was the publication of an article in which, in 1923, Virginia Woolf,  in her late forties, drew a line between her own novels and  those of Arnold Bennett, in his mid fifties.  [6]   Categories were invented for fiction which continue to affect readers nearly a century later. The disappearance of Yonge’s works from the canon of Victorian fiction is part of this process.  The Macmillan archive might contain definite evidence about the decisions which were taken about her books in the years after her death, and a thorough examination of comments from  contemporary writers would be valuable. It does seem clear that she was fairly swiftly relegated to the category of children’s writer and that her more powerful mid-Victorian novels, such as *The Heir of Redclyffe*, *Heartsease*, *The Pillars of the House* were not marketed to adults for long.  The hero of  E. Nesbit’s *The Wouldbegoods* (1901), patronizingly calls *The Daisy Chain* ‘a first-rate book for girls and little boys’.   Yonge was not of course alone among nineteenth-century writers in being infantilized by a younger generation of critics:  she might herself have said that she was happy to meet the same fate as her hero Walter Scott.  There were, though, reasons why she was especially vulnerable to changes in literary fashion.  Her association with strict propriety and religion was probably becoming a handicap rather than a recommendation, the First World War perhaps occurred at an unlucky time for her, nor was she fortunate in the personality and situation of her heirs, who could have stirred up more support for her work.  These factors, however, probably combined with trends in the climate of opinion already developing in the last decade of her life.  She had at least begun to outlive her reputation by the time she died.  

[1]*Hyde Park Gate News: The Stephen Family Newspaper* ed. Gill Lowe (London: Hesperus 2005), 8, 11. See also Quentin Bell, *Virginia Woolf: A Biography* 2 vols (London: Hogarth Press 1972) I, 29: ‘the sisters would sit together and Virginia would read aloud from Charlotte M. Yonge – they kept a score of the number of deaths in those very necrological novels.’  Woolf is known to have taken *The Heir of Redclyffe* to read on her honeymoon in Italy (rather a pessimistic choice given what happened on Guy Morville’s honeymoon in Italy) see Bell, *op.cit* II, 5 and *The Letters of Virginia Woolf 1881-1941* ed Nigel Nicolson and Joanne Trautmann, 6 vols (London: Hogarth Press 1976-85) II, 2, 6.  In the Victorian proposal scene in *Between the Acts* (1941) she draws on Norman’s proposal to Meta in *The Daisy Chain*.

[2] Bessie Rayner Belloc, *A Passing World* (London: Ward & Downey 1897), 31.

[3] Annie Moberly, *Dulce Domum*, 3.  See also the opinion of one of her own contemporaries, the novelist Emma Marshall, who wrote (2 May 1898), correctly predicting that the promoters of the Charlotte Yonge scholarship would have difficulty raising the £6000 they were aiming at: ‘The fashion for Miss Yonge's stories is over, yet we owe her much for the new departure of forty-five years ago.  The girls of these days must have something a little different from histories of large families, and their innocent joys and loves.’  Beatrice Marshall, *Emma Marshall: A Biographical Sketch* (London: Seeley 1901), 315-6.

[4] Arnold Bennett, ‘The Heir of Redclyffe’ *The Academy* (22 July 1899), 87: ‘It shows us what we of to-day have gained - in intellectual freedom and wider horizons . . .Its limited view, its sweeping omissions, its ignorance, its one-sidedness, its perversions, its impossible dialogue, its undramatic tediousness, its stilted English- these things were not noticed then.'  The article was reprinted in Bennett’s *Fame and Fiction* (1901).  The obituary by Edward H. Cooper, *Fortnightly Review* 69 (May 1901), 852-8,  defending Yonge against such attacks, was perhaps aimed, rather snobbishly, at Bennett in particular: ‘some witless young journalist trying to be smart according to his unhappy lights . . .I gather . .  that . . . the lower Fifth Form of the provincial Grammar School does not admire Miss Yonge's life work.’ [853]

[5] For example, To George Lillie Craik (22 May 1889) http://www.yongeletters.com/wordpress/2907/to-george-lillie-craik , and To Lady Frederick Bruce (27 February 1893) http://www.yongeletters.com/wordpress/3216/to-lady-frederick-bruce-3.  Christabel Coleridge wrote in an obituary ‘her later stories indeed are really intended as more news of old friends to her old readers – who constantly begged for them.’  ‘Miss Charlotte Yonge: A Personal Reminiscence’ *Sunday Magazine* (April 1901) 335-338, 338.
[6]Virginia Woolf, ‘Mr. Bennett and Mrs. Brown’ *New York Evening Post* (17 November 1923).
[7]E. Nesbit, *The Wouldbegoods* (London: Fisher Unwin 1901),  .


## Letters

{{< include _1890-1901_letters.md >}}
