---
title: "Ann Maria Carter Smith - Aggesden Vicarage, or, Bridget Storey's First Charge: A Tale for the Young"
book_id: 268
---

## Publication Information

**Date:** 1859

**Imprint:** London: Parker

## Letters Mentioning This Work

- [Letter 1778](../1778-to-ann-maria-carter-smith-27.qmd)
- [Letter 1779](../1779-to-ann-maria-carter-smith-28.qmd)
- [Letter 1781](../1781-to-john-william-parker-jr-8.qmd)
- [Letter 1785](../1785-to-ann-maria-carter-smith-32.qmd)
- [Letter 1788](../1788-to-ann-maria-carter-smith-34.qmd)
- [Letter 1800](../1800-to-ann-maria-carter-smith-36.qmd)
- [Letter 1820](../1820-to-ann-maria-carter-smith-40.qmd)
- [Letter 1821](../1821-to-ann-maria-carter-smith-41.qmd)
- [Letter 1878](../1878-to-ann-maria-carter-smith-55.qmd)
- [Letter 1879](../1879-to-ann-maria-carter-smith-56.qmd)
- [Letter 2727](../2727-to-christabel-rose-coleridge-103.qmd)
- [Letter 3126](../3126-to-ann-maria-carter-smith-15.qmd)
- [Letter 3127](../3127-to-ann-maria-carter-smith-16.qmd)
- [Letter 3128](../3128-to-ann-maria-carter-smith-17.qmd)
- [Letter 3129](../3129-to-ann-maria-carter-smith-18.qmd)
- [Letter 3130](../3130-to-ann-maria-carter-smith-19.qmd)
- [Letter 3131](../3131-to-ann-maria-carter-smith-20.qmd)
- [Letter 3136](../3136-to-ann-maria-carter-smith-23.qmd)
- [Letter 3138](../3138-to-ann-maria-carter-smith-24.qmd)
- [Letter 3142](../3142-to-ann-maria-carter-smith-25.qmd)
- [Letter 3143](../3143-to-ann-maria-carter-smith-26.qmd)

