---
title: "Elizabeth P. Roberts - 'A Garland for the Year'"
book_id: 225
---

## Publication Information

**Date:** (January-December 1852)

**Imprint:** <i>MP</i> 3-4

**Notes:** This series of papers on flowers associated with particular religious seasons and saints does not seem to have been published separately.

## Letters Mentioning This Work

- [Letter 2978](../2978-to-elizabeth-roberts-2.qmd)
- [Letter 2980](../2980-to-elizabeth-roberts-3.qmd)
- [Letter 2981](../2981-to-elizabeth-roberts-4.qmd)
- [Letter 2983](../2983-to-elizabeth-roberts-5.qmd)
- [Letter 2984](../2984-to-elizabeth-roberts-6.qmd)
- [Letter 2985](../2985-to-elizabeth-roberts-7.qmd)
- [Letter 2986](../2986-to-elizabeth-roberts-8.qmd)
- [Letter 2988](../2988-to-elizabeth-roberts-9.qmd)
- [Letter 2989](../2989-to-elizabeth-roberts-10.qmd)
- [Letter 2991](../2991-to-elizabeth-roberts-11.qmd)
- [Letter 2992](../2992-to-elizabeth-roberts-12.qmd)
- [Letter 2993](../2993-to-elizabeth-roberts-13.qmd)
- [Letter 2994](../2994-to-elizabeth-roberts-14.qmd)
- [Letter 2995](../2995-to-elizabeth-roberts-15.qmd)
- [Letter 2996](../2996-to-elizabeth-roberts-16.qmd)
- [Letter 2997](../2997-to-elizabeth-roberts-17.qmd)
- [Letter 2998](../2998-to-elizabeth-roberts-18.qmd)
- [Letter 2999](../2999-to-elizabeth-roberts-19.qmd)
- [Letter 3000](../3000-to-elizabeth-roberts-20.qmd)
- [Letter 3001](../3001-to-elizabeth-roberts-21.qmd)
- [Letter 3002](../3002-to-elizabeth-roberts-22.qmd)
- [Letter 3003](../3003-to-elizabeth-roberts-23.qmd)
- [Letter 3004](../3004-to-elizabeth-roberts-24.qmd)
- [Letter 3014](../3014-to-elizabeth-roberts-28.qmd)
- [Letter 3018](../3018-to-elizabeth-roberts-29.qmd)
- [Letter 3021](../3021-to-elizabeth-roberts-30.qmd)
- [Letter 3022](../3022-to-elizabeth-roberts-31.qmd)
- [Letter 3025](../3025-to-elizabeth-roberts-32.qmd)
- [Letter 3035](../3035-to-elizabeth-roberts-33.qmd)
- [Letter 3046](../3046-to-elizabeth-roberts-34.qmd)
- [Letter 3100](../3100-to-miss-moorsom.qmd)
- [Letter 3146](../3146-to-elizabeth-roberts-39.qmd)

