---
title: "Christabel Coleridge - Charlotte Mary Yonge: Her Life and Letters"
book_id: 40
---

## Publication Information

**Date:** 1903

**Imprint:** London: Macmillan

**Notes:** See also [Christabel Coleridge](../people/person_329.qmd).

## Letters Mentioning This Work

- [Letter 1791](../1791-to-anne-sturges-bourne-4.qmd)
- [Letter 2066](../2066-to-mary-ann-dyson-3.qmd)
- [Letter 2110](../2110-to-anne-yonge-43.qmd)
- [Letter 2111](../2111-to-anne-yonge-44.qmd)
- [Letter 2117](../2117-to-anne-yonge-45.qmd)
- [Letter 2208](../2208-to-mary-ann-dyson-4.qmd)
- [Letter 2209](../2209-to-florence-wilford-3.qmd)
- [Letter 2215](../2215-to-mary-ann-dyson-5.qmd)
- [Letter 2264](../2264-to-the-reverend-duke-yonge-2.qmd)
- [Letter 2271](../2271-to-mary-ann-dyson-6.qmd)
- [Letter 2275](../2275-to-mary-ann-dyson-7.qmd)
- [Letter 2280](../2280-to-caroline-elizabeth-cooke-trench-4.qmd)
- [Letter 2288](../2288-to-the-reverend-william-john-butler-2.qmd)
- [Letter 2296](../2296-to-anne-elizabeth-mary-anderson-morshead-2.qmd)
- [Letter 2300](../2300-to-mary-ann-dyson-8.qmd)
- [Letter 2304](../2304-to-sir-william-heathcote-bt-2.qmd)
- [Letter 2317](../2317-to-mary-ann-dyson-9.qmd)
- [Letter 2328](../2328-to-mary-ann-dyson-10.qmd)
- [Letter 2329](../2329-to-mary-ann-dyson-11.qmd)
- [Letter 2331](../2331-to-mary-ann-dyson-12.qmd)
- [Letter 2332](../2332-to-mary-anne-dyson-13-2.qmd)
- [Letter 2333](../2333-to-mary-anne-dyson-10-3.qmd)
- [Letter 2334](../2334-to-mary-ann-dyson-10.qmd)
- [Letter 2335](../2335-to-mary-ann-dyson-12.qmd)
- [Letter 2339](../2339-to-mary-yonge-7.qmd)
- [Letter 2341](../2341-to-mary-yonge-8.qmd)
- [Letter 2342](../2342-to-florence-wilford-5.qmd)
- [Letter 2347](../2347-to-anne-elizabeth-mary-anderson-morshead-3.qmd)
- [Letter 2360](../2360-to-mary-anne-dyson-20.qmd)
- [Letter 2385](../2385-to-sir-william-heathcote-bt-3.qmd)
- [Letter 2390](../2390-to-the-reverend-william-john-butler.qmd)
- [Letter 2425](../2425-to-frances-sophia-coleridge-patteson-6.qmd)
- [Letter 2429](../2429-to-mary-anne-dyson-21.qmd)
- [Letter 2435](../2435-to-sir-william-heathcote-bt-4.qmd)
- [Letter 2442](../2442-to-sir-william-heathcote-bt-6.qmd)
- [Letter 2444](../2444-to-sir-william-heathcote-bt-8.qmd)
- [Letter 2446](../2446-to-mary-anne-dyson-22.qmd)
- [Letter 2499](../2499-to-mary-anne-dyson-23.qmd)
- [Letter 2525](../2525-to-mary-anne-dyson.qmd)
- [Letter 2536](../2536-to-annie-louise-cazenove-2.qmd)
- [Letter 2641](../2641-to-elizabeth-barnett-17.qmd)
- [Letter 2689](../2689-to-cyril-hammond-elgie.qmd)
- [Letter 2729](../2729-to-florence-wilford-10.qmd)
- [Letter 2731](../2731-to-helena-mary-heathcote.qmd)
- [Letter 2766](../2766-to-john-duke-pode.qmd)
- [Letter 2825](../2825-to-florence-wilford-11.qmd)
- [Letter 2827](../2827-to-elizabeth-barnett-18.qmd)
- [Letter 2831](../2831-to-sophia-jane-harrison-2.qmd)
- [Letter 2836](../2836-to-george-lillie-craik-69.qmd)
- [Letter 2845](../2845-to-elizabeth-barnett-19.qmd)
- [Letter 2867](../2867-to-elizabeth-barnett-20.qmd)
- [Letter 2880](../2880-to-elizabeth-barnett-22.qmd)
- [Letter 2926](../2926-to-elizabeth-barnett-24.qmd)
- [Letter 2932](../2932-to-anne-yonge.qmd)
- [Letter 2933](../2933-to-anne-yonge-2.qmd)
- [Letter 2936](../2936-to-anne-yonge-4.qmd)
- [Letter 2938](../2938-to-anne-yonge-6.qmd)
- [Letter 2941](../2941-to-anne-yonge-9.qmd)
- [Letter 2958](../2958-to-mary-anne-dyson-2.qmd)
- [Letter 2960](../2960-to-mary-anne-dyson-3.qmd)
- [Letter 2964](../2964-to-mary-anne-dyson-5.qmd)
- [Letter 2966](../2966-to-mary-anne-dyson-6.qmd)
- [Letter 2969](../2969-to-mary-anne-dyson-9.qmd)
- [Letter 2975](../2975-to-elizabeth-barnett-3.qmd)
- [Letter 3006](../3006-to-mary-anne-dyson-13.qmd)
- [Letter 3029](../3029-to-mary-anne-dyson-17.qmd)
- [Letter 3030](../3030-to-mary-anne-dyson-18.qmd)
- [Letter 3042](../3042-to-jemima-blackburn-3.qmd)
- [Letter 3048](../3048-to-mary-anne-dyson-19.qmd)
- [Letter 3055](../3055-to-anne-yonge-31.qmd)
- [Letter 3077](../3077-to-anna-butler-7.qmd)
- [Letter 3109](../3109-to-frances-mary-yonge-2.qmd)
- [Letter 3124](../3124-to-caroline-elizabeth-cooke-trench-2.qmd)
- [Letter 3140](../3140-to-caroline-elizabeth-cooke-trench-3.qmd)
- [Letter 3147](../3147-to-elizabeth-barnett-13.qmd)
- [Letter 3149](../3149-dorothea-beale-to-charlotte-mary-yonge.qmd)
- [Letter 3164](../3164-to-florence-wilford-6.qmd)
- [Letter 3194](../3194-to-helen-emma-yonge-2.qmd)
- [Letter 3195](../3195-to-emma-frances-yonge.qmd)
- [Letter 3204](../3204-to-helen-emma-yonge.qmd)
- [Letter 3207](../3207-to-the-reverend-vere-awdry.qmd)
- [Letter 3216](../3216-to-lady-frederick-bruce-3.qmd)
- [Letter 3227](../3227-to-the-reverend-william-parsons-warburton-4.qmd)
- [Letter 3230](../3230-to-elizabeth-barnett-15.qmd)
- [Letter 3236](../3236-to-anne-elizabeth-mary-anderson-morshead-4.qmd)
- [Letter 3244](../3244-to-the-reverend-arthur-roland-maddison.qmd)
- [Letter 3259](../3259-to-charlotte-anne-elizabeth-moberly.qmd)
- [Letter 3325](../3325-to-ethel-romanes.qmd)
- [Letter 3332](../3332-to-daniel-conner-lathbury.qmd)
- [Letter 3333](../3333-to-mary-elizabeth-christie-2.qmd)
- [Letter 3334](../3334-to-mary-elizabeth-christie-3.qmd)
- [Letter 3336](../3336-to-edith-emma-knight.qmd)
- [Letter 3345](../3345-to-a-member-of-the-bigg-wither-family.qmd)
- [Letter 3349](../3349-to-marianne-bigg-wither-5.qmd)
- [Letter 3361](../3361-to-mary-elizabeth-christie.qmd)
- [Letter 3380](../3380-to-marianne-bigg-wither-2.qmd)
- [Letter 3399](../3399-to-marianne-bigg-wither-3.qmd)
- [Letter 3410](../3410-to-margaret-jane-mowbray.qmd)
- [Letter 3411](../3411-to-charlotte-fortescue-yonge-3.qmd)
- [Letter 3413](../3413-to-helena-heathcote-2.qmd)
- [Letter 3414](../3414-to-elizabeth-harcourt-mitchell.qmd)
- [Letter 3433](../3433-to-helena-heathcote.qmd)
- [Letter 3459](../3459-to-christabel-rose-coleridge-44.qmd)
- [Letter 3463](../3463-to-christabel-rose-coleridge-47.qmd)
- [Letter 3466](../3466-to-christabel-rose-coleridge-50.qmd)
- [Letter 3480](../3480-to-christabel-rose-coleridge-59.qmd)
- [Letter 3481](../3481-to-charlotte-fortescue-yonge.qmd)
- [Letter 3499](../3499-to-annie-louise-cazenove.qmd)
- [Letter 3523](../3523-to-anna-rachel-bramston-3.qmd)
- [Letter 3592](../3592-to-charlotte-anne-elizabeth-moberly-2.qmd)
- [Letter 19394](../19394-to-mary-anne-dyson.qmd)

