---
title: "Guardian, The"
other_id: 75
---

**Type:** periodical

## Description

This was a High Church weekly newspaper which ran 1846-1951, and is not to be confused with the daily newspaper formerly known as the <i>Manchester Guardian</i> which changed its name to <i>The Guardian </i>in 1959.  The High Church <i>Guardian</i> had been founded by a group of Tractarians including CMY’s friend Lord Blachford.  She herself seems to have regularly read it and also reviewed for it, but the precise extent of her involvement with it remains to be charted.

## Letters Mentioning This

- [Letter 1793](../1793-to-john-william-parker-jr-10.qmd)
- [Letter 1829](../1829-to-frances-sophia-coleridge-patteson-3.qmd)
- [Letter 2121](../2121-to-alexander-macmillanm081-1866-04-26.qmd)
- [Letter 2391](../2391-to-susanna-warren-7.qmd)
- [Letter 2474](../2474-to-edward-augustus-freeman-7.qmd)
- [Letter 2645](../2645-to-mrs-curteis.qmd)
- [Letter 2766](../2766-to-john-duke-pode.qmd)
- [Letter 2797](../2797-to-christabel-rose-coleridge-111.qmd)
- [Letter 2956](../2956-to-anne-yonge-23.qmd)
- [Letter 3181](../3181-to-penelope-packe-3.qmd)
- [Letter 3224](../3224-to-mary-yonge-13.qmd)
- [Letter 3260](../3260-to-anne-elizabeth-mary-anderson-morshead-5.qmd)
- [Letter 3332](../3332-to-daniel-conner-lathbury.qmd)
- [Letter 3337](../3337-to-mary-elizabeth-christie-4.qmd)
- [Letter 3339](../3339-to-elizabeth-wordsworth-3.qmd)
- [Letter 3386](../3386-to-christabel-rose-coleridge-25.qmd)
- [Letter 3394](../3394-to-sir-walter-besant-2.qmd)
- [Letter 3430](../3430-to-christabel-rose-coleridge-36.qmd)

