---
title: "Friendly Leaves"
other_id: 71
---

**Type:** periodical

## Description

This was a periodical published by the Girls’ Friendly Society, and aimed at the working-class girls who were its members.  It ran 1876-1951, renaming itself first <i>The G. F. S. Magazine </i>and then <i>The Townsend.</i> 





Its first editor was Mary Elizabeth Townsend, the GFS's founder, and subsequently byAnne Mercier. In 1885 Eliza Keary became editor, and was succeeded in 1890 by Henley I. Arden, who was succeeded in 1899 by Christabel Rose Coleridge.  It was published quarterly until 1877 when it became a monthly magazine.





The charity also published <i>The Girls' Friendly Society Associates' Journal</i> aimed at the upper-class ladies known as ‘associates’ as opposed to ‘members’, and a quarterly magazine, at first entitled <i>Friendly Work</i> and then the <i>Girls' Quarterly</i>, which was aimed at 'members' who were rather better educated than those reading <i>Friendly Leaves</i>.

## Letters Mentioning This

- [Letter 2570](../2570-to-christabel-rose-coleridge-85.qmd)
- [Letter 3421](../3421-to-christabel-rose-coleridge-31.qmd)
- [Letter 3502](../3502-to-an-unknown-woman-68.qmd)
- [Letter 9403](../9403-to-the-editor-of-the-i-girls-friendly-society-associates-journal-i-.qmd)
- [Letter 9425](../9425-to-the-editor-of-the-i-girls-friendly-society-associates-journal-i.qmd)

