---
title: "Macmillan's Sunday Library"
other_id: 145
---

**Type:** topic

## Description

See Ellen Jordan, ‘“I am too high church and too narrow”; Charlotte Yonge, Macmillan and the Sunday Library.’ <i>Charlotte M Yonge Fellowship Journal</i>. 6 (2003): 12-25.

## Letters Mentioning This

- [Letter 2007](../2007-alexander-macmillan-to-charlotte-mary-yonge-18.qmd)
- [Letter 2008](../2008-to-alexander-macmillan-35.qmd)
- [Letter 2010](../2010-alexander-macmillan-to-charlotte-mary-yonge-19.qmd)
- [Letter 2013](../2013-alexander-macmillan-to-charlotte-mary-yonge-20.qmd)
- [Letter 2096](../2096-to-alexander-macmillan-68.qmd)
- [Letter 2100](../2100-to-alexander-macmillan-69.qmd)
- [Letter 2101](../2101-to-alexander-macmillan-70.qmd)
- [Letter 2103](../2103-to-alexander-macmillan-71.qmd)
- [Letter 2108](../2108-to-alexander-macmillan-73.qmd)
- [Letter 2136](../2136-to-alexander-macmillan-80.qmd)
- [Letter 2139](../2139-to-alexander-macmillan-82.qmd)
- [Letter 2156](../2156-to-alexander-macmillan-85.qmd)
- [Letter 2159](../2159-frances-martin-to-alexander-macmillan-2.qmd)
- [Letter 2162](../2162-frances-martin-to-alexander-macmillan-3.qmd)
- [Letter 2165](../2165-frances-martin-to-alexander-macmillan-4.qmd)
- [Letter 2168](../2168-alexander-macmillan-to-charlotte-mary-yonge-47.qmd)
- [Letter 2182](../2182-alexander-macmillan-to-charlotte-mary-yonge-53.qmd)
- [Letter 2191](../2191-alexander-macmillan-to-charlotte-mary-yonge-55.qmd)
- [Letter 2192](../2192-frances-martin-to-alexander-macmillan.qmd)
- [Letter 2193](../2193-to-alexander-macmillan-91.qmd)
- [Letter 2194](../2194-alexander-macmillan-to-charlotte-mary-yonge-56.qmd)
- [Letter 2196](../2196-alexander-macmillan-to-charlotte-mary-yonge-57.qmd)
- [Letter 2204](../2204-george-lillie-craik-to-charlotte-mary-yonge.qmd)
- [Letter 2216](../2216-alexander-macmillan-to-frances-martin.qmd)
- [Letter 2219](../2219-alexander-macmillan-to-charlotte-mary-yonge-61.qmd)
- [Letter 2226](../2226-alexander-macmillan-to-charlotte-mary-yonge-62.qmd)
- [Letter 2228](../2228-alexander-macmillan-to-charlotte-mary-yonge-63.qmd)
- [Letter 2229](../2229-alexander-macmillan-to-charlotte-mary-yonge-64.qmd)
- [Letter 2237](../2237-alexander-macmillan-to-charlotte-mary-yonge-69.qmd)
- [Letter 2286](../2286-to-alexander-macmillan-104.qmd)
- [Letter 2313](../2313-to-alexander-macmillan-109.qmd)
- [Letter 2328](../2328-to-mary-ann-dyson-10.qmd)
- [Letter 2330](../2330-to-mary-ann-dyson-2.qmd)
- [Letter 2361](../2361-to-alexander-macmillan-112.qmd)
- [Letter 2381](../2381-to-an-unknown-woman-or-to-alexander-macmillan.qmd)
- [Letter 19634](../19634-alexander-macmillan-to-charlotte-mary-yonge.qmd)
- [Letter 19653](../19653-alexander-macmillan-to-charlotte-mary-yonge.qmd)
- [Letter 19667](../19667-alexander-macmillan-to-charlotte-mary-yonge.qmd)
- [Letter 19670](../19670-alexander-macmillan-to-charlotte-mary-yonge.qmd)

