---
title: "Magazine for the Young"
other_id: 79
---

**Type:** periodical

## Description

This periodical was founded by Mary Anne Dyson and her sister-in-law and published by James Burns, but edited from soon after the start by Anne Mozley (1809–1891), whose publisher brothers took over its publication in 1850; it ran 1842-1875. It was known in CMY’s circle as ‘the Pink Mag’;  it was a tiny duodecimo production with a pink paper cover.   CMY published in this periodical  ‘Chapters on Flowers’ (February 1850-December 1852), which later appeared as <i>The Herb of the Field </i>(1853); twenty-seven ‘Langley School’ stories (September 1846-December 1848), fifteen of which appeared as <i>Langley School</i>; ‘Mrs Elderney’s School’ which was never reprinted in volume form (January 1850-Jan 1852); ‘Thoughts on Pictures’ (1853), also never republished; <i>Friarswood Post Office</i> (August 1858-August 1859);  <i>Countess Kate</i> (October 1861-December 1862); and <i>New Ground </i>(January 1863-November 1866).

## Letters Mentioning This

- [Letter 1791](../1791-to-anne-sturges-bourne-4.qmd)
- [Letter 1807](../1807-to-an-unknown-man-5.qmd)
- [Letter 1827](../1827-to-florence-wilford-2.qmd)
- [Letter 2131](../2131-to-ann-maria-carter-smith-74.qmd)
- [Letter 2835](../2835-to-george-lillie-craik-68.qmd)
- [Letter 2956](../2956-to-anne-yonge-23.qmd)
- [Letter 3006](../3006-to-mary-anne-dyson-13.qmd)
- [Letter 3014](../3014-to-elizabeth-roberts-28.qmd)
- [Letter 3386](../3386-to-christabel-rose-coleridge-25.qmd)
- [Letter 3487](../3487-to-frances-mary-peard.qmd)
- [Letter 3514](../3514-to-an-unknown-person-4.qmd)

