---
title: "Mothers in Council"
other_id: 82
---

**Type:** periodical

## Description

This quarterly was edited by CMY 1890-1901.  It ran until 1930.  It was aimed at the educated members of the Mothers’ Union, as distinct from <i>The Mothers’ Union Journal</i>, which was aimed at the working-class mothers.

## Letters Mentioning This

- [Letter 3162](../3162-to-george-lillie-craik-8.qmd)
- [Letter 3184](../3184-to-the-archdeacon-of.qmd)
- [Letter 3205](../3205-to-lady-frederick-bruce-2.qmd)
- [Letter 3215](../3215-to-john-athelstan-laurie-riley.qmd)
- [Letter 3216](../3216-to-lady-frederick-bruce-3.qmd)
- [Letter 3220](../3220-to-messrs-isbister.qmd)
- [Letter 3319](../3319-to-an-unknown-woman-27.qmd)
- [Letter 3341](../3341-to-an-unknown-woman-29.qmd)
- [Letter 3358](../3358-to-louisa-fanny-field.qmd)
- [Letter 3365](../3365-to-the-reverend-william-parsons-warburton-5.qmd)
- [Letter 3381](../3381-to-the-countess-of-glasgow.qmd)
- [Letter 3396](../3396-to-mary-elizabeth-sumner-2.qmd)
- [Letter 3457](../3457-to-mrs-bothamly.qmd)
- [Letter 3458](../3458-to-christabel-rose-coleridge-43.qmd)
- [Letter 3459](../3459-to-christabel-rose-coleridge-44.qmd)
- [Letter 3473](../3473-to-christabel-rose-coleridge-55.qmd)
- [Letter 3594](../3594-to-christabel-rose-coleridge-3.qmd)
- [Letter 3609](../3609-to-an-unknown-woman-4.qmd)
- [Letter 18956](../18956-to-mary-elizabeth-hawker.qmd)
- [Letter 19268](../19268-to-anna-rachel-bramston.qmd)

