---
title: "Mothers’ Union, The"
other_id: 31
---

**Type:** organization

## Description

This was founded by Mary Elizabeth Sumner in 1885.  CMY became the first editor of <i>Mothers in Council</i>, the journal aimed at the upper-class ladies who supported it.

## Letters Mentioning This

- [Letter 2720](../2720-to-ann-maria-carter-smith-82.qmd)
- [Letter 2825](../2825-to-florence-wilford-11.qmd)
- [Letter 2858](../2858-to-mary-drew-3.qmd)
- [Letter 2897](../2897-to-lady-frederick-bruce.qmd)
- [Letter 2912](../2912-to-arthur-donald-innes-26.qmd)
- [Letter 2913](../2913-to-arthur-donald-innes-27.qmd)
- [Letter 3162](../3162-to-george-lillie-craik-8.qmd)
- [Letter 3165](../3165-to-florence-wilford-7.qmd)
- [Letter 3184](../3184-to-the-archdeacon-of.qmd)
- [Letter 3205](../3205-to-lady-frederick-bruce-2.qmd)
- [Letter 3215](../3215-to-john-athelstan-laurie-riley.qmd)
- [Letter 3358](../3358-to-louisa-fanny-field.qmd)
- [Letter 3365](../3365-to-the-reverend-william-parsons-warburton-5.qmd)
- [Letter 3386](../3386-to-christabel-rose-coleridge-25.qmd)
- [Letter 3391](../3391-to-frederick-orridge-macmillan-2.qmd)
- [Letter 3437](../3437-to-louisa-alethea-bowles.qmd)
- [Letter 3451](../3451-to-mary-yonge-30.qmd)
- [Letter 3461](../3461-to-christabel-rose-coleridge-46.qmd)
- [Letter 3545](../3545-to-miss-merriman.qmd)
- [Letter 3599](../3599-to-an-unknown-woman-3.qmd)
- [Letter 3604](../3604-to-cordelia-elizabeth-yonge.qmd)

