---
title: "Events of the Month"
other_id: 69
---

**Type:** periodical

## Description

This periodical was advertised as <i>Events of the Month: A Magazine of News, Literature, Science, and General Information; Designed for Youthful Readers</i> to be published by John and Charles Mozley, starting January 1st, 1864. Price sixpence.” It was edited by Henrietta Murray and ran from January 1864 to January 1865. CMY later described it to Macmillan (3 June 1864) as “a sort of school room Athenaeum”, and tried unsuccessfully to get him to take it over when the Mozleys abandoned it.(see Macmillan to CMY  17 January 1865).  ‘Lost [sic] Heartsease Leaves’ was published in it in January 1865.

## Letters Mentioning This

- [Letter 1911](../1911-to-ann-maria-carter-smith-64.qmd)
- [Letter 1923](../1923-to-henrietta-elizabeth-fursdon-10.qmd)
- [Letter 1925](../1925-to-florence-wilford.qmd)
- [Letter 1934](../1934-to-frances-mary-peard-8.qmd)
- [Letter 1958](../1958-to-alexander-macmillan-16.qmd)
- [Letter 1995](../1995-to-alexander-macmillan-29.qmd)
- [Letter 2002](../2002-alexander-macmillan-to-charlotte-mary-yonge-17.qmd)
- [Letter 2007](../2007-alexander-macmillan-to-charlotte-mary-yonge-18.qmd)
- [Letter 2008](../2008-to-alexander-macmillan-35.qmd)
- [Letter 2069](../2069-to-george-lillie-craik-2.qmd)
- [Letter 2402](../2402-to-arthur-john-butler-12.qmd)

