---
title: "Marriage between first cousins"
other_id: 101
---

**Type:** topic

## Description

CMY was against this, and such marriages are not encouraged in any of her novels, although they are a normal feature of nineteenth-century fiction by other writers (occurring for example without disapproval in <i>Mansfield Park</i> and <i>Middlemarch</i>), just as they were a commonplace feature of Victorian life.   The topic is mentioned (15, 20 March 1860) in letters to Ann Maria Carter Smith and discussed by CMY in ‘Three Generations’ <i>Mothers in Council</i> 5.17 (Jan 1895).  Her opinions were probably formed because of her family history.  In her autobiographical writing she observes of her grandmother’s family ‘the Crawleys were far too much addicted to marriages among cousins’.  This is in connection with the marriage of her uncle James Yonge to his first cousin Margaret Crawley;  his sisters Catharina and Charlotte also married Margaret’s brothers Charles and George.  James Yonge was a physician in Plymouth,  His three children all died within a year in 1830.  There was a growing scientific evidence against the excessive inbreeding, reinforced for the agriculture-minded landed gentry by the lessons drawn from experience with horses, dogs and farm animals.  Moreover there was also much discussion in religious circles of the prohibited degrees.  Pusey, giving evidence in 1847 to the Commission appointed to enquire into the state and operation of the law of marriage (which was much preoccupied with the deceased wife’s sister issue), cited St. Augustine’s view that the marriage of first cousins, though lawful, was near to incest (<i>Parliamentary Papers</i> 1848, 40).

## Letters Mentioning This

- [Letter 1787](../1787-to-ann-maria-carter-smith-33.qmd)
- [Letter 2556](../2556-to-mary-yonge-45.qmd)
- [Letter 3129](../3129-to-ann-maria-carter-smith-18.qmd)

