---
title: "Good Words"
other_id: 73
---

**Type:** periodical

## Description

Described by CMY as ‘so Scottish and Presbyterian’.  She wrote to Christabel Coleridge (11 August 1871) complaining that ‘respectable people’ could not be expected to read a love story by Matilda Betham-Edwards.  She advised Christabel (1 Jan 1872) to avoid writing for it.  <i>Good Words</i> was published from Jan 1860 to Apr 1911. According to Mrs Gatty it paid much better than the MP: 'Why does an orthodox parson’s wife write for <i>Good</i> Words? When orthodox magazines value her services at £1 per page and copyright reserved--instead of 2s.6d. (<i>Monthly Packet</i> !) --then you may wonder--<i>but not till</i> then.' (Maxwell, <i>Mrs.Gatty and Mrs.Ewing</i>, 132)

## Letters Mentioning This

- [Letter 1878](../1878-to-ann-maria-carter-smith-55.qmd)
- [Letter 1879](../1879-to-ann-maria-carter-smith-56.qmd)
- [Letter 2195](../2195-to-marianne-bigg-wither-6.qmd)
- [Letter 2251](../2251-to-edith-sophia-jacob-14.qmd)
- [Letter 2411](../2411-to-christabel-rose-coleridge-65.qmd)
- [Letter 2416](../2416-to-christabel-rose-coleridge-66.qmd)
- [Letter 2422](../2422-to-christabel-rose-coleridge-69.qmd)
- [Letter 2434](../2434-to-christabel-rose-coleridge-70.qmd)
- [Letter 2797](../2797-to-christabel-rose-coleridge-111.qmd)
- [Letter 3220](../3220-to-messrs-isbister.qmd)

