---
title: "Macmillan’s Magazine"
other_id: 78
---

**Type:** periodical

## Description

This magazine ran 1859-1907. Two of CMY’s historical novels were serialized in it: <i>The Dove in the Eagle’s Nest</i> (May-December 1865) and <i>The Chaplet of Pearls </i>(November 1867-December 1868), and her series of articles ‘Children’s Literature of the Last Century’ (May-October 1869), 229-37, 302-10, 448-56.

## Letters Mentioning This

- [Letter 1967](../1967-alexander-macmillan-to-julian-bargus-yonge.qmd)
- [Letter 1994](../1994-to-alexander-macmillan-28.qmd)
- [Letter 2013](../2013-alexander-macmillan-to-charlotte-mary-yonge-20.qmd)
- [Letter 2017](../2017-to-alexander-macmillan-38.qmd)
- [Letter 2018](../2018-alexander-macmillan-to-charlotte-mary-yonge-23.qmd)
- [Letter 2019](../2019-to-alexander-macmillan-39.qmd)
- [Letter 2022](../2022-alexander-macmillan-to-charlotte-mary-yonge-25.qmd)
- [Letter 2026](../2026-to-alexander-macmillan-41.qmd)
- [Letter 2028](../2028-to-alexander-macmillan-42.qmd)
- [Letter 2035](../2035-alexander-macmillan-to-charlotte-mary-yonge-30.qmd)
- [Letter 2036](../2036-to-alexander-macmillan-45.qmd)
- [Letter 2049](../2049-alexander-macmillan-to-charlotte-mary-yonge-35.qmd)
- [Letter 2054](../2054-to-alexander-macmillan-52.qmd)
- [Letter 2060](../2060-alexander-macmillan-to-charlotte-mary-yonge-39.qmd)
- [Letter 2096](../2096-to-alexander-macmillan-68.qmd)
- [Letter 2101](../2101-to-alexander-macmillan-70.qmd)
- [Letter 2103](../2103-to-alexander-macmillan-71.qmd)
- [Letter 2133](../2133-to-alexander-macmillan-79.qmd)
- [Letter 2139](../2139-to-alexander-macmillan-82.qmd)
- [Letter 2153](../2153-alexander-macmillan-to-charlotte-mary-yonge-45.qmd)
- [Letter 2156](../2156-to-alexander-macmillan-85.qmd)
- [Letter 2213](../2213-to-alexander-macmillan-93.qmd)
- [Letter 2227](../2227-to-dinah-maria-craik.qmd)
- [Letter 2298](../2298-to-alexander-macmillan-106.qmd)
- [Letter 2304](../2304-to-sir-william-heathcote-bt-2.qmd)
- [Letter 2311](../2311-to-alexander-macmillan-108.qmd)
- [Letter 2586](../2586-to-george-lillie-craik-27.qmd)
- [Letter 3466](../3466-to-christabel-rose-coleridge-50.qmd)
- [Letter 3543](../3543-to-edward-augustus-freeman-12.qmd)
- [Letter 19598](../19598-alexander-macmillan-to-charlotte-mary-yonge.qmd)

