---
title: "Churchman's Companion"
other_id: 62
---

**Type:** periodical

## Description

This periodical, which ran 1847-1883, was published by Joseph Masters, and considered in the Yonges’ circle rather too controversial in its treatment of religious topics to be suitable for young people. It thus inspired the foundation of the <i>Monthly Packet</i>. ‘Its tone was . . . extremely controversial, and it was given to insist more on the surface pecularities of the Church movement than the wiser members of that movement thought good.  The Dysons, and possibly others, suggested the putting forth of a magazine for young people, suited to the schoolroom rather than the village school, and which should avoid personal controversy as unsuited to the young.’ (Coleridge, <i>Life</i> 164).  CMY’s story <i>Henrietta’s Wish </i>was serialized in it (January 1849-May 1850) and also her <i>The Two Guardians</i> (July 1850-February 1852).  The editor until 1858 was the Rev. William Balmborough Flower.  He was followed by Masters' partner until 1863, when Felicia Skene took over, editing it to 1880.

## Letters Mentioning This

- [Letter 1782](../1782-to-ann-maria-carter-smith-30.qmd)
- [Letter 1841](../1841-to-ann-maria-carter-smith-48.qmd)
- [Letter 1843](../1843-to-ann-maria-carter-smith-49.qmd)
- [Letter 1925](../1925-to-florence-wilford.qmd)
- [Letter 2730](../2730-to-ann-maria-carter-smith-86.qmd)
- [Letter 2767](../2767-to-ann-maria-carter-smith-89.qmd)
- [Letter 3005](../3005-to-joseph-masters.qmd)
- [Letter 3126](../3126-to-ann-maria-carter-smith-15.qmd)
- [Letter 3363](../3363-to-frederick-orridge-macmillan-13.qmd)

