---
title: "Barnacle, The"
other_id: 89
---

**Type:** periodical

## Description

This was a manuscript magazine circulating among members of the Gosling Society.  The surviving issues  (incomplete series, 1863-1867)  are owned by Lady Margaret Hall, Oxford.  They are described by Julia Courtney, ‘<i>The Barnacle</i>: A manuscript magazine of the 1860s’, in <i>The Girl’s Own: Cultural Histories of the Anglo –American Girl 1830-1915</i> ed. Claudia Nelson and Lynne Vallone.  Arkansas and London, University of Georgia Press: 1994.

## Letters Mentioning This

- [Letter 1921](../1921-to-henrietta-elizabeth-fursdon-9.qmd)
- [Letter 1924](../1924-to-christabel-rose-coleridge-5.qmd)
- [Letter 2003](../2003-to-christabel-rose-coleridge-6.qmd)
- [Letter 2023](../2023-to-katharine-olive-helmore-7.qmd)
- [Letter 2070](../2070-to-katharine-olive-helmore-8.qmd)
- [Letter 2078](../2078-to-christabel-rose-coleridge-7.qmd)
- [Letter 2088](../2088-to-ellen-julia-johns-8.qmd)
- [Letter 2093](../2093-to-frances-mary-peard-9.qmd)
- [Letter 2107](../2107-to-katharine-olive-helmore.qmd)
- [Letter 2150](../2150-to-christabel-rose-coleridge-9.qmd)
- [Letter 2173](../2173-to-christabel-rose-coleridge-10.qmd)
- [Letter 2185](../2185-to-christabel-rose-coleridge-11.qmd)
- [Letter 2201](../2201-to-christabel-rose-coleridge-12.qmd)
- [Letter 2207](../2207-to-christabel-rose-coleridge-13.qmd)
- [Letter 2209](../2209-to-florence-wilford-3.qmd)
- [Letter 2234](../2234-to-christabel-rose-coleridge-15.qmd)
- [Letter 2267](../2267-to-christabel-rose-coleridge-17.qmd)
- [Letter 2289](../2289-to-christabel-rose-coleridge-60.qmd)
- [Letter 2291](../2291-to-christabel-rose-coleridge-18.qmd)
- [Letter 2422](../2422-to-christabel-rose-coleridge-69.qmd)
- [Letter 3562](../3562-to-christabel-rose-coleridge-21.qmd)
- [Letter 3574](../3574-to-an-unknown-person-6.qmd)
- [Letter 19298](../19298-to-henrietta-elizabeth-fursdon.qmd)

