---
title: "Church restoration"
other_id: 198
---

**Type:** topic

## Description

In Victorian England the question of the restoration of ancient churches involved several different considerations.  Just as there was an immense amount of new church building, in which the Tractarians took an enthusiastic part, so there was also a great deal of church rebuilding.  The Ecclesiological Society encouraged work which was Gothic, and supported on purist grounds the de-classicizing of many churches. Indeed it sometimes supported the removal of genuinely mediaeval work and its replacement by work which was consistent with the original period of the building.  As well as this aesthetic and historicizing element, there was also a movement to open up churches to the poor, by removing the room-like pews rented by the gentry.  And liturgical considerations meant that the Tractarians in some cases reinstated features of mediaeval churches, such as rood screens, which had been absent since the Reformation.  CMY's sense of reverence meant that she refers to these issues only in passing in her fiction, for example when Clement pulls down the church's black mourning drapery in <i>[The Pillars of the House](../cmy_books/cmybook_109.qmd)</i>, although other novels, from the Rev. F. E. Paget's <i>[Milford Malvoisin](../other_books/otherbook_517.qmd)</i> (1842) to Thomas Hardy's <i>[Under the Greenwood Tree](../other_books/otherbook_518.qmd)</i> (1872), give a good idea of the ructions which these changes involved.

## Letters Mentioning This

- [Letter 2231](../2231-to-ann-maria-carter-smith-77.qmd)

