---
title: "Ecclesiological Society, The"
other_id: 131
---

**Type:** organization

## Description

Founded as the Cambridge Camden Society in 1839, it changed its name to the Ecclesiological Society in 1845.  It acted as a pressure group to encourage the use of Gothic architecture in church buildings, and research and preservation of mediaeval buildings, mainly through its journal <i>The Ecclesiologist</i> and other publications.  See James White, <i>The Cambridge Movement: The Ecclesiologists and the Gothic Revival</i> (Cambridge: Cambridge University Press 1962).  The society still exists.





Although CMY and her circle were much influenced by the ideas about design propagated by the society, they were not totally in sympathy with the movement;  in <i>The Pillars of the House</i> Clement comments unsympathetically of a local antiquarian clergyman that he minds his ecclesiology more than his ecclesia.

## Letters Mentioning This

- [Letter 3014](../3014-to-elizabeth-roberts-28.qmd)

