---
title: "National Society, The"
other_id: 32
---

**Type:** organization

## Description

The National Society for Promoting the Education of the Poor in the Principles of the Established Church, now National Society, Church of England, for Promoting Religious Education.  This charity, which was enormously influential in the Victorian educational world, was founded in 1811, and started or  supported a very large number of Anglican schools for the working classes.  It also published textbooks and fiction, often used for school prizes, and CMY wrote many children’s books for them. See http://www.natsoc.org.uk/society/history/

## Letters Mentioning This

- [Letter 1804](../1804-to-susanna-warren-2.qmd)
- [Letter 2356](../2356-to-louisa-anne-gibbs.qmd)
- [Letter 2577](../2577-to-mr-hoskins.qmd)
- [Letter 2708](../2708-to-francis-turner-palgrave.qmd)
- [Letter 2713](../2713-to-the-reverend-william-parsons-warburton-9.qmd)
- [Letter 2728](../2728-to-ann-maria-carter-smith-85.qmd)
- [Letter 2740](../2740-to-mr-duncan-3.qmd)
- [Letter 2753](../2753-to-mr-duncan.qmd)
- [Letter 2838](../2838-to-george-lillie-craik-71.qmd)
- [Letter 2853](../2853-to-mr-duncan-4.qmd)
- [Letter 2868](../2868-to-edward-augustus-freeman-13.qmd)
- [Letter 2874](../2874-to-mary-drew-4.qmd)
- [Letter 2890](../2890-to-anne-sturges-bourne.qmd)
- [Letter 2910](../2910-to-edward-augustus-freeman-15.qmd)
- [Letter 2955](../2955-to-anne-yonge-22.qmd)
- [Letter 3191](../3191-to-an-unknown-man-14.qmd)
- [Letter 3197](../3197-to-elizabeth-barnett-14.qmd)
- [Letter 3213](../3213-to-george-lillie-craik-11.qmd)
- [Letter 3386](../3386-to-christabel-rose-coleridge-25.qmd)
- [Letter 3427](../3427-to-christabel-rose-coleridge-35.qmd)
- [Letter 3430](../3430-to-christabel-rose-coleridge-36.qmd)
- [Letter 3441](../3441-to-mary-drew-2.qmd)

