---
title: "Macmillan and Son"
other_id: 111
---

**Type:** organization

## Letters Mentioning This

- [Letter 1945](../1945-to-ann-maria-carter-smith-67.qmd)
- [Letter 1956](../1956-to-messrs-macmillan-3.qmd)
- [Letter 1972](../1972-to-messrs-macmillan-4.qmd)
- [Letter 2337](../2337-to-messrs-macmillan-5.qmd)
- [Letter 2521](../2521-to-edward-augustus-freeman-10.qmd)
- [Letter 2579](../2579-to-messrs-macmillan-6.qmd)
- [Letter 2652](../2652-to-messrs-macmillan-7.qmd)
- [Letter 2658](../2658-to-messrs-macmillan.qmd)
- [Letter 2698](../2698-to-an-unknown-woman-49.qmd)
- [Letter 2699](../2699-to-an-unknown-woman-50.qmd)
- [Letter 2762](../2762-to-the-reverend-bartholomew-price.qmd)
- [Letter 2771](../2771-to-christabel-rose-coleridge-107.qmd)
- [Letter 3178](../3178-to-arthur-donald-innes-14.qmd)
- [Letter 3271](../3271-to-george-lillie-craik-15.qmd)
- [Letter 3383](../3383-to-anna-meredith-barrett-lennard.qmd)
- [Letter 3394](../3394-to-sir-walter-besant-2.qmd)
- [Letter 3420](../3420-to-christabel-rose-coleridge-26.qmd)
- [Letter 3421](../3421-to-christabel-rose-coleridge-31.qmd)
- [Letter 3422](../3422-to-christabel-rose-coleridge-32.qmd)
- [Letter 3424](../3424-to-miss-e-m-walker.qmd)
- [Letter 3430](../3430-to-christabel-rose-coleridge-36.qmd)
- [Letter 3441](../3441-to-mary-drew-2.qmd)
- [Letter 7783](../7783-to-sir-john-taylor-coleridge.qmd)

