---
title: "Saturday Review, The"
other_id: 99
---

**Type:** periodical

## Description

This was a weekly magazine of conservative tendency, notorious for its trenchant reviews.  It was immediately successful on its foundation in 1855;  its first editor was John Douglas Cook (1808?-1868).

## Letters Mentioning This

- [Letter 1778](../1778-to-ann-maria-carter-smith-27.qmd)
- [Letter 1779](../1779-to-ann-maria-carter-smith-28.qmd)
- [Letter 1781](../1781-to-john-william-parker-jr-8.qmd)
- [Letter 1782](../1782-to-ann-maria-carter-smith-30.qmd)
- [Letter 1793](../1793-to-john-william-parker-jr-10.qmd)
- [Letter 1832](../1832-to-william-butler-bourn.qmd)
- [Letter 1883](../1883-to-ann-maria-carter-smith-58.qmd)
- [Letter 1901](../1901-to-frederick-james-furnivall-2.qmd)
- [Letter 1971](../1971-to-alexander-macmillan-17.qmd)
- [Letter 2210](../2210-to-the-reverend-arthur-rawson-ashwell.qmd)
- [Letter 2265](../2265-to-george-lillie-craik-5.qmd)
- [Letter 2333](../2333-to-mary-anne-dyson-10-3.qmd)
- [Letter 2474](../2474-to-edward-augustus-freeman-7.qmd)
- [Letter 2497](../2497-to-edward-augustus-freeman-8.qmd)
- [Letter 2521](../2521-to-edward-augustus-freeman-10.qmd)
- [Letter 2620](../2620-to-george-lillie-craik-35.qmd)
- [Letter 2630](../2630-to-christabel-rose-coleridge-93.qmd)
- [Letter 2733](../2733-to-christabel-rose-coleridge-104.qmd)
- [Letter 2801](../2801-to-gertrude-mary-ireland-blackburne-3.qmd)
- [Letter 3115](../3115-to-anna-butler-17.qmd)
- [Letter 3139](../3139-to-john-william-parker-jr-7.qmd)
- [Letter 9425](../9425-to-the-editor-of-the-i-girls-friendly-society-associates-journal-i.qmd)

