---
title: "Literary Churchman, The"
other_id: 76
---

**Type:** periodical

## Description

This periodical ran 1855-1892. CMY contributed to it a review of G. O. Trevelyan’s <i>Cawnpore</i> as well as one to <i>Macmillan’s Magazine </i>(letter 29 May 1865).  She contributed an obituary of Bishop Patteson in 1871: ‘one that I could do from my heart of those vague <i>In Memoriam</i> things’ (mentioned to Fanny Patteson, 8 December 1871), and wrote other unidentified contributions, some sufficiently substantial for her to propose their inclusion in a projected volume of essays (To Alexander Macmillan, 20 March 1869). Its editor 1864-1876 was the Rev. Arthur Rawson Ashwell (1824–1879),  of whom CMY thought very highly. He contributed both to <i>MP </i>and to the <i>Monthly Packet of Sunday Teaching. </i>

## Letters Mentioning This

- [Letter 1995](../1995-to-alexander-macmillan-29.qmd)
- [Letter 2036](../2036-to-alexander-macmillan-45.qmd)
- [Letter 2210](../2210-to-the-reverend-arthur-rawson-ashwell.qmd)
- [Letter 2268](../2268-to-edith-sophia-jacob-16.qmd)
- [Letter 2277](../2277-to-edith-sophia-jacob-17.qmd)
- [Letter 2283](../2283-to-alexander-macmillan-103.qmd)
- [Letter 2284](../2284-to-elizabeth-missing-sewell-9.qmd)
- [Letter 2304](../2304-to-sir-william-heathcote-bt-2.qmd)
- [Letter 2311](../2311-to-alexander-macmillan-108.qmd)
- [Letter 2425](../2425-to-frances-sophia-coleridge-patteson-6.qmd)
- [Letter 2761](../2761-to-an-unknown-man-20.qmd)
- [Letter 3136](../3136-to-ann-maria-carter-smith-23.qmd)
- [Letter 3521](../3521-to-miss-phillpotts.qmd)

