---
title: "Winchester College"
other_id: 50
---

**Type:** organization

## Description

A boys’ public school founded in 1382 by William of Wykeham, Bishop of Winchester.  In CMY’s youth it consisted of seventy scholars (chosen until 1855 by patronage rather than competition) living with the Second Master in College, and about 100 fee-paying boys living in ‘Commoners’ under the supervision of the Head Master. There were 120 commoners on George Moberly’s arrival as Head Master in 1836, and numbers had declined by the 1850s. Boarding houses did not exist until the 1850s.  The Warden of Winchester College, the head of the whole institution, who lived in lodgings on the site, was the Rev. Robert Speckott Barter (1790-1861), a much-loved figure.  Moberly resigned and was succeeded in 1867 by his son-in-law George Ridding.  On Barter’s death in 1861 he was succeeded by the Rev. Godfrey Bollis Lee (1817-1903).


http://www.winchestercollege.co.uk/history-of-the-college and ‘Winchester College and Commoners; Blackwood’s Magazine 95 (January 1864) 66-92.




## Letters Mentioning This

- [Letter 1815](../1815-from-frances-mary-yonge-to-anne-sturges-bourne.qmd)
- [Letter 1895](../1895-to-anne-yonge-38.qmd)
- [Letter 1896](../1896-to-anne-yonge-39.qmd)
- [Letter 1897](../1897-to-anne-yonge-40.qmd)
- [Letter 2185](../2185-to-christabel-rose-coleridge-11.qmd)
- [Letter 2190](../2190-to-edith-sophia-jacob-10.qmd)
- [Letter 2296](../2296-to-anne-elizabeth-mary-anderson-morshead-2.qmd)
- [Letter 2423](../2423-to-mary-eliza-bramston.qmd)
- [Letter 2467](../2467-to-blanche-catherine-medhurst-3.qmd)
- [Letter 2580](../2580-to-the-reverend-edward-atkinson.qmd)
- [Letter 2582](../2582-to-the-reverend-bartholomew-price-2.qmd)
- [Letter 2745](../2745-to-percy-harris.qmd)
- [Letter 2881](../2881-to-jean-ingelow.qmd)
- [Letter 2932](../2932-to-anne-yonge.qmd)
- [Letter 2957](../2957-anne-yonge-to-mary-yonge-2.qmd)
- [Letter 2963](../2963-to-mary-anne-dyson-4.qmd)
- [Letter 2995](../2995-to-elizabeth-roberts-15.qmd)
- [Letter 3048](../3048-to-mary-anne-dyson-19.qmd)
- [Letter 3054](../3054-to-elizabeth-roberts-35.qmd)
- [Letter 3125](../3125-to-anne-sturges-bourne-3.qmd)
- [Letter 3224](../3224-to-mary-yonge-13.qmd)
- [Letter 3409](../3409-to-mary-yonge-12.qmd)

