---
title: "Girls’ Friendly Society, The"
other_id: 23
---

**Type:** organization

## Description

This organization was founded by Mary Elizabeth Townsend in 1875, as a response to the forlorn condition of young women working away from home, usually as servants and shop assistants.  It established a network of diocesan societies, within which Associates  (ladies) provided support and facilities for Members (girls).  These were of very various kinds, including lodging, education, recreational facilities, convalescent homes, circulating libraries and employment bureaux. CMY was much involved in its work from its earliest years, and published a rare pamphlet, <i>THe Girls' Friendly Society: A Short Account of its Working in the Diocese of Winchester to the end of the year 1878</i> (1879), a copy of which is MS Lambeth Palace Library Tait 268 ff224-9.  At that date the diocese had 3,057 members and CMY was in charge of the circulating library.  The tribulations of those trying to administer the organization were amusingly described by CMY in MP in 1882 'A Conversation on the Girls' Friendly Society'. It ran <i>The Girls' Friendly Society Associates' Journal</i> for the Associates and <i>Friendly Leaves </i> for the Members.  CMY’s kitchen maid, Rosina Dewsall, took the exams of the Girls’ Friendly Society Reading Union. Its archive is held by the Women’s Library.  Brian Harrison, 'For Church, Queen and Family:  The Girls' Friendly Society 1874-1920' <i>Past and Present</i> 61 (1973) 107-138 is informative.  The charity still exists and its website is http://www.gfsplatform.org.uk/

## Letters Mentioning This

- [Letter 2563](../2563-to-anna-rachel-bramston-4.qmd)
- [Letter 2595](../2595-to-augusta-boevey-pode.qmd)
- [Letter 2710](../2710-to-an-unknown-woman-52.qmd)
- [Letter 2743](../2743-to-an-unknown-woman-55.qmd)
- [Letter 2769](../2769-to-catharine-elgie.qmd)
- [Letter 2775](../2775-to-lady-sophia-matilda-palmer1.qmd)
- [Letter 2783](../2783-to-christabel-rose-coleridge-110.qmd)
- [Letter 2825](../2825-to-florence-wilford-11.qmd)
- [Letter 2854](../2854-to-christabel-rose-coleridge-112.qmd)
- [Letter 2855](../2855-to-christabel-rose-coleridge-113.qmd)
- [Letter 2856](../2856-to-christabel-rose-coleridge-114.qmd)
- [Letter 2874](../2874-to-mary-drew-4.qmd)
- [Letter 2897](../2897-to-lady-frederick-bruce.qmd)
- [Letter 2927](../2927-to-an-unknown-woman-66.qmd)
- [Letter 3165](../3165-to-florence-wilford-7.qmd)
- [Letter 3167](../3167-to-an-unknown-woman-23.qmd)
- [Letter 3197](../3197-to-elizabeth-barnett-14.qmd)
- [Letter 3210](../3210-to-sarah-angelina-acland.qmd)
- [Letter 3250](../3250-to-mrs-egerton.qmd)
- [Letter 3357](../3357-to-mary-yonge-24.qmd)
- [Letter 3385](../3385-to-mary-yonge-4.qmd)
- [Letter 3408](../3408-to-mary-yonge-6.qmd)
- [Letter 3421](../3421-to-christabel-rose-coleridge-31.qmd)
- [Letter 3439](../3439-to-lady-brandreth.qmd)
- [Letter 3451](../3451-to-mary-yonge-30.qmd)
- [Letter 3456](../3456-to-mary-yonge-33.qmd)
- [Letter 3460](../3460-to-christabel-rose-coleridge-45.qmd)
- [Letter 3466](../3466-to-christabel-rose-coleridge-50.qmd)
- [Letter 3505](../3505-to-anne-mary-buston.qmd)
- [Letter 3526](../3526-to-the-rt-rev-edward-harold-browne.qmd)
- [Letter 3530](../3530-to-an-unknown-person-10.qmd)
- [Letter 3540](../3540-to-mrs-swinton.qmd)
- [Letter 3544](../3544-to-anne-elizabeth-mary-anderson-morshead-6.qmd)
- [Letter 3599](../3599-to-an-unknown-woman-3.qmd)
- [Letter 3610](../3610-to-the-reverend-william-parsons-warburton-2.qmd)
- [Letter 9343](../9343-to-the-editor-of-the-i-girls-friendly-society-associates-journal-i.qmd)
- [Letter 9348](../9348-to-the-editor-of-the-i-girls-friendly-society-associates-journal-i.qmd)
- [Letter 9355](../9355-to-the-editor-of-the-i-girls-friendly-society-associates-journal-i.qmd)
- [Letter 9362](../9362-to-the-editor-of-the-i-girls-friendly-society-associates-journal-i.qmd)
- [Letter 9369](../9369-to-the-editor-of-the-i-girls-friendly-society-associates-journal-i.qmd)
- [Letter 9374](../9374-to-the-editor-of-the-i-girls-friendly-society-associates-journal-i.qmd)
- [Letter 9379](../9379-to-the-editor-of-the-i-girls-friendly-society-associates-journal-i.qmd)
- [Letter 9389](../9389-to-the-editor-of-the-i-girls-friendly-society-associates-journal-i.qmd)
- [Letter 9398](../9398-to-the-editor-of-the-i-girls-friendly-society-associates-journal-i.qmd)
- [Letter 9425](../9425-to-the-editor-of-the-i-girls-friendly-society-associates-journal-i.qmd)

