---
title: "Philological Society's proposed Dictionary, The"
other_id: 151
---

**Type:** topic

## Description

IN 1860, the Committee of the Philological Society resolved to produce a


dictionary of four volumes, covering the entire English language from past to present.  CMY and her mother, encouraged by their cousin Henry Hucks Gibbs, were among the contributors of material in the 1860s, to what was, eventually, to become the New English Dictionary on Philological Principles.

## Letters Mentioning This

- [Letter 1848](../1848-to-the-reverend-william-george-henderson.qmd)
- [Letter 1880](../1880-to-the-reverend-henry-octavius-coxe-3.qmd)
- [Letter 1901](../1901-to-frederick-james-furnivall-2.qmd)
- [Letter 1952](../1952-to-frederick-james-furnivall-3.qmd)
- [Letter 1965](../1965-to-frederick-james-furnivall-4.qmd)
- [Letter 2356](../2356-to-louisa-anne-gibbs.qmd)
- [Letter 2498](../2498-to-frederick-james-furnivall-7.qmd)
- [Letter 2593](../2593-to-frederick-james-furnivall.qmd)
- [Letter 2918](../2918-james-augustus-henry-murray-to-charlotte-mary-yonge.qmd)
- [Letter 2919](../2919-to-james-augustus-henry-murray.qmd)

