---
title: "St. Andrew's College, Kohimarama"
other_id: 139
---

**Type:** organization

## Description

Founded by the Rev. John Coleridge Patteson in 1859 at the place now called Mission Bay, Auckland, as a school for boys and girls from the South Sea Islands.  It was named after the church of St. Andrew in <i>The Daisy Chain</i> and was built with CMY's donations from the profits of that novel.  However, it only lasted a short time in Auckland, which was too cold for the pupils, and removed to Norfolk Island. The missionaries had second thoughts about the name.  The building is currently (2007) occupied by a cafe.

## Letters Mentioning This

- [Letter 1951](../1951-from-the-right-reverend-john-coleridge-patteson-to-charlotte-mary-yonge-5.qmd)
- [Letter 2120](../2120-from-the-right-reverend-john-coleridge-patteson-to-charlotte-mary-yonge-8.qmd)
- [Letter 2134](../2134-the-right-reverend-john-coleridge-patteson-to-charlotte-mary-yonge-2.qmd)
- [Letter 2154](../2154-the-right-reverend-john-coleridge-patteson-to-charlotte-mary-yonge-5.qmd)
- [Letter 3144](../3144-from-the-reverend-john-coleridge-patteson-to-charlotte-mary-yonge-2.qmd)

