---
title: "Society for the Propagation of the Gospel, The"
other_id: 41
---

**Type:** organization

## Description

Founded in 1701, the SPG was the most congenial to High Church Anglicans of the missionary societies, the Church Missionary Society, being evangelical Anglican, and the London Missionary Society being non-denominational and including Nonconformists. The SPG archives are held in Lambeth Palace Library.  It is now the United Society for the Propagation of the Gospel, having merged with the Universities Mission to Central Africa in 1961. See http://www.uspg.org.uk/ Mentioned, No 64, No 82.

## Letters Mentioning This

- [Letter 2158](../2158-to-miss-cleveland-3.qmd)
- [Letter 2164](../2164-to-an-unknown-woman-15.qmd)
- [Letter 2215](../2215-to-mary-ann-dyson-5.qmd)
- [Letter 2616](../2616-to-christabel-rose-coleridge-90.qmd)
- [Letter 2675](../2675-to-c-b-woodman.qmd)
- [Letter 2857](../2857-to-the-reverend-john-frewen-moor-20.qmd)
- [Letter 2994](../2994-to-elizabeth-roberts-14.qmd)
- [Letter 3012](../3012-to-elizabeth-roberts-27.qmd)

