---
title: "Monthly Paper of Sunday Teaching, The"
other_id: 81
---

**Type:** periodical

## Description

This was edited by CMY throughout its existence, 1860-1875, and was intended to provide suitable material for Sunday School teachers, as she described it (21 May 1860) to Anne Sturges Bourne: ‘I am intending to set up a Monthly sheet of questions for Sunday Schools on the Gospels for each Sunday in the month, also questions on the Catechism, and a small sort of reading to the girl pupils, on some subject connected with the day - as the history of the preservation & MSS of the Bible on the 2nd Sunday in Advent - the full Jewish passover on the 1st after Easter - the Eastern shepherding ways on the Shepherd Sunday. Could you help me to any of these, adapted to the older classes of Sunday Schools just what you would say to your orphans. Not quite a sermon but more entertaining to young people. Septuagesima is to have the Isthmean games - and the 21st after Trinity the account of armour. Any other Sunday in the year, or any subject is open. I should be very glad of help, specially yours. Real anecdotes would do well, drawn into morals according with the Sunday, harvest or Christmas advice &c, but I forswear stories or I shall be eaten up and dissipated with them. It is to be on the model of the National Society’s Sunday School paper, only taking in churchisms which they are afraid of. The papers should not exceed a sheet of full sized note paper.’  Arthur Rawson Ashwell, Frances Mary Peard and Henrietta Fursdon are known contributors.

## Letters Mentioning This

- [Letter 1792](../1792-to-anne-sturges-bourne-5.qmd)
- [Letter 1860](../1860-to-frances-mary-peard-2.qmd)
- [Letter 1868](../1868-to-frances-mary-peard-12.qmd)
- [Letter 1872](../1872-to-frances-mary-peard-3.qmd)
- [Letter 1873](../1873-to-frances-mary-peard-4.qmd)
- [Letter 1983](../1983-to-an-unknown-man-8.qmd)
- [Letter 2101](../2101-to-alexander-macmillan-70.qmd)
- [Letter 2104](../2104-to-alexander-macmillan-72.qmd)
- [Letter 2139](../2139-to-alexander-macmillan-82.qmd)
- [Letter 2347](../2347-to-anne-elizabeth-mary-anderson-morshead-3.qmd)
- [Letter 2356](../2356-to-louisa-anne-gibbs.qmd)
- [Letter 2391](../2391-to-susanna-warren-7.qmd)
- [Letter 2538](../2538-to-augusta-boevey-pode-3.qmd)
- [Letter 3491](../3491-to-susanna-warren.qmd)
- [Letter 19162](../19162-to-frances-mary-peard.qmd)
- [Letter 19298](../19298-to-henrietta-elizabeth-fursdon.qmd)
- [Letter 19653](../19653-alexander-macmillan-to-charlotte-mary-yonge.qmd)

