---
title: "Christian Remembrancer, The"
other_id: 59
---

**Type:** periodical

## Description

This periodical had been published as a monthly magazine until 1844 when it was relaunched as a quarterly, at the height of the controversy over Newman’s conversion, as the organ of moderate Tractarian thought. Its editor from 1841 the Rev. William Scott (1813–1872), perpetual curate of Christ Church, Hoxton, and known as Scott of Hoxton; between 1844-55 he was joint editor with the Rev. James Bowling Mozley. It ran until 1868.  In 1853, John Duke Coleridge published ‘Miss Yonge’s Novels’, a largely favourable assessment which all the same led to his incurring the wrath of FMY and made his next visit to Otterbourne uncomfortable. CMY herself wrote several long articles for it in the 1860s, which she several times mentions in connection with attempts to have them published in a volume: on Elizabeth Sewell’s <i>Principles of Education</i>; on ghosts and folklore; on the Sanitary Commission in the American war; on Lord Seaton and his regiment;  on Eugenie de Guérin;  on  Alexandrine de la Ferronays; and on the Life of Bishop Mackenzie.

## Letters Mentioning This

- [Letter 1778](../1778-to-ann-maria-carter-smith-27.qmd)
- [Letter 2311](../2311-to-alexander-macmillan-108.qmd)
- [Letter 2586](../2586-to-george-lillie-craik-27.qmd)
- [Letter 2588](../2588-to-george-lillie-craik-28.qmd)
- [Letter 2945](../2945-to-anne-yonge-12.qmd)
- [Letter 2954](../2954-to-anne-yonge-21.qmd)
- [Letter 2972](../2972-to-mary-anne-dyson-12.qmd)
- [Letter 3000](../3000-to-elizabeth-roberts-20.qmd)
- [Letter 3002](../3002-to-elizabeth-roberts-22.qmd)

