---
title: "Otterbourne School"
other_id: 107
---

**Type:** organization

## Description

This institution, now Otterbourne Church of England Primary School, has its origins in the school founded by CMY’s mother in about 1826 ‘the room built of cement, with two tiny ones behind for kitchen and bed-  room for the mistress, and a brick floor’ (John Keble’s Parishes, 95). The schoolmistress, however, could not keep the boys in order, and so a separate boys’ room was built near the church. In 1838, when Otterbourne church was rebuilt on a new site, a boys’ school was ‘built on a corner of the ground intended as churchyard, and a larger room added to the girls', the expense being partly defrayed by a bazaar held at Winchester, and in part by Charlotte Yonge's first book’ (John Keble’s Parishes, 103). The National Society was also involved, and the school was sometimes called Otterbourne National School. In 1871 a new girls’ school and a master’s house was built to commemorate the service of the Rev. William Bigg Wither, curate of Otterbourne, and the school was moved ‘under government’ (Coleridge, Life, 263). The school’s archives 1872-1979 are held by Hampshire Archives.  A pamphlet by Lloyd Woodcock, Charlotte Yonge and Otterbourne Girls' and Infants' School, was published by Eastleigh and District Local History Society in 1987. For the school website see http://www.otterbourneprimaryschool.com/

## Letters Mentioning This

- [Letter 2429](../2429-to-mary-anne-dyson-21.qmd)
- [Letter 2438](../2438-to-christabel-rose-coleridge-71.qmd)
- [Letter 2543](../2543-to-augusta-boevey-pode-4.qmd)
- [Letter 2570](../2570-to-christabel-rose-coleridge-85.qmd)
- [Letter 2672](../2672-to-mary-eliza-bramston-2.qmd)
- [Letter 2701](../2701-to-the-reverend-william-parsons-warburton-8.qmd)
- [Letter 2718](../2718-to-the-reverend-william-parsons-warburton-10.qmd)
- [Letter 2939](../2939-to-anne-yonge-7.qmd)
- [Letter 2940](../2940-to-anne-yonge-8.qmd)
- [Letter 2964](../2964-to-mary-anne-dyson-5.qmd)
- [Letter 3036](../3036-anne-yonge-to-the-rev-john-yonge.qmd)
- [Letter 3039](../3039-anne-yonge-to-mary-yonge-3.qmd)
- [Letter 3607](../3607-to-anna-rachel-bramston-2.qmd)
- [Letter 14430](../14430-to-the-duke-of-newcastle-and-other-members-of-the-royal-commission-on-popular-education.qmd)

