---
title: "Melanesian Mission, The"
other_id: 30
---

**Type:** organization

## Description

This organization, originally the Melanesian Mission Fund, was founded in 1854 to purchase the <i>Southern Cross</i>. Its website today is www.melanesia.anglican.org/mmhome.html.  The British Museum holds an archive of photographs of the mission which it is putting online at www.britishmuseum.org in 2010.  CMY’s was deeply interested in missions, and she was especially devoted to the idea of evangelizing the South Seas.  She gave the mission the profits of her novel <i>[The Daisy Chain](../people/person_24.qmd)</i>, in which an episode takes place in Melanesia.  Her [biography](../cmy_books/cmybook_102.qmd) of Bishop Patteson brought her into contact with several members of the mission.

## Letters Mentioning This

- [Letter 1840](../1840-from-the-reverend-john-coleridge-patteson-to-charlotte-mary-yonge-3.qmd)
- [Letter 1885](../1885-from-the-right-reverend-john-coleridge-patteson-to-charlotte-mary-yonge-3.qmd)
- [Letter 1951](../1951-from-the-right-reverend-john-coleridge-patteson-to-charlotte-mary-yonge-5.qmd)
- [Letter 1954](../1954-from-the-right-reverend-john-coleridge-patteson-to-charlotte-mary-yonge-6.qmd)
- [Letter 2120](../2120-from-the-right-reverend-john-coleridge-patteson-to-charlotte-mary-yonge-8.qmd)
- [Letter 2164](../2164-to-an-unknown-woman-15.qmd)
- [Letter 2365](../2365-to-the-reverend-fielder.qmd)
- [Letter 2373](../2373-to-an-unknown-woman-36.qmd)
- [Letter 2485](../2485-to-an-unknown-woman-39.qmd)
- [Letter 2537](../2537-to-miss-peterson.qmd)
- [Letter 2811](../2811-to-an-unknown-woman-62.qmd)
- [Letter 3122](../3122-to-the-reverend-edward-coleridge-3.qmd)
- [Letter 3144](../3144-from-the-reverend-john-coleridge-patteson-to-charlotte-mary-yonge-2.qmd)
- [Letter 3226](../3226-to-the-right-reverend-john-richardson-selwyn.qmd)
- [Letter 3367](../3367-to-anna-meredith-barrett-lennard.qmd)
- [Letter 7798](../7798-to-sir-john-taylor-coleridge.qmd)

