---
title: "Monthly Packet, The"
other_id: 52
---

**Type:** periodical

## Description

This monthly magazine was edited by CMY 1851-1890; edited by CMY jointly with C. R. Coleridge 1891-3; edited by C. R. Coleridge and A. D. Innes 1894-9. It was markedly High Church and aimed at a juvenile audience, mainly conceived of as girls in their teens, though in the early days CMY also hoped to make it entertaining to boys who had not yet gone to public school, and there is evidence that it was also read by adults of both sexes.   The magazine has been digitized in the series <i>19th Century UK Periodicals</i> and is available at http://find.galegroup.com/ukpc/

## Letters Mentioning This

- [Letter 1782](../1782-to-ann-maria-carter-smith-30.qmd)
- [Letter 1788](../1788-to-ann-maria-carter-smith-34.qmd)
- [Letter 1790](../1790-to-anna-butler-18.qmd)
- [Letter 1793](../1793-to-john-william-parker-jr-10.qmd)
- [Letter 1794](../1794-to-john-william-parker-jr-11.qmd)
- [Letter 1800](../1800-to-ann-maria-carter-smith-36.qmd)
- [Letter 1807](../1807-to-an-unknown-man-5.qmd)
- [Letter 1813](../1813-to-ellen-r-garnett.qmd)
- [Letter 1814](../1814-to-susanna-warren-3.qmd)
- [Letter 1820](../1820-to-ann-maria-carter-smith-40.qmd)
- [Letter 1822](../1822-to-ann-maria-carter-smith-42.qmd)
- [Letter 1852](../1852-to-margaret-gatty-3.qmd)
- [Letter 1865](../1865-to-ann-maria-carter-smith-53.qmd)
- [Letter 1868](../1868-to-frances-mary-peard-12.qmd)
- [Letter 1870](../1870-to-frances-sophia-coleridge-patteson-5.qmd)
- [Letter 1877](../1877-to-an-unknown-man-6.qmd)
- [Letter 1878](../1878-to-ann-maria-carter-smith-55.qmd)
- [Letter 1879](../1879-to-ann-maria-carter-smith-56.qmd)
- [Letter 1881](../1881-to-ann-maria-carter-smith-57.qmd)
- [Letter 1884](../1884-to-ann-maria-carter-smith-59.qmd)
- [Letter 1907](../1907-to-alexander-macmillan-3.qmd)
- [Letter 1912](../1912-alexander-macmillan-to-charlotte-mary-yonge-3.qmd)
- [Letter 1915](../1915-to-ann-maria-carter-smith-65.qmd)
- [Letter 1920](../1920-to-the-reverend-algernon-wodehouse.qmd)
- [Letter 1922](../1922-to-margaret-gatty-4.qmd)
- [Letter 1926](../1926-to-alexander-macmillan-8.qmd)
- [Letter 1932](../1932-to-alexander-macmillan-10.qmd)
- [Letter 1949](../1949-to-louisa-twining.qmd)
- [Letter 1974](../1974-to-an-unknown-woman-76.qmd)
- [Letter 2028](../2028-to-alexander-macmillan-42.qmd)
- [Letter 2047](../2047-to-alexander-macmillan-50.qmd)
- [Letter 2050](../2050-to-alexander-macmillan-51.qmd)
- [Letter 2057](../2057-to-ellen-julia-johns-7.qmd)
- [Letter 2079](../2079-to-alexander-macmillan-60.qmd)
- [Letter 2081](../2081-to-susanna-warren-5.qmd)
- [Letter 2092](../2092-to-the-reverend-orby-shipley.qmd)
- [Letter 2102](../2102-to-margaret-gatty-5.qmd)
- [Letter 2104](../2104-to-alexander-macmillan-72.qmd)
- [Letter 2116](../2116-to-an-unknown-woman-13.qmd)
- [Letter 2136](../2136-to-alexander-macmillan-80.qmd)
- [Letter 2149](../2149-to-mrs-elder.qmd)
- [Letter 2152](../2152-to-edith-sophia-jacob-3.qmd)
- [Letter 2163](../2163-to-edith-sophia-jacob-6.qmd)
- [Letter 2177](../2177-to-ann-maria-carter-smith-76.qmd)
- [Letter 2179](../2179-to-an-unknown-man-11.qmd)
- [Letter 2187](../2187-to-harriet-poole.qmd)
- [Letter 2221](../2221-to-miss-manning.qmd)
- [Letter 2223](../2223-to-edith-sophia-jacob-11.qmd)
- [Letter 2243](../2243-to-alexander-macmillan-94.qmd)
- [Letter 2254](../2254-alexander-macmillan-to-charlotte-mary-yonge-75.qmd)
- [Letter 2265](../2265-to-george-lillie-craik-5.qmd)
- [Letter 2268](../2268-to-edith-sophia-jacob-16.qmd)
- [Letter 2296](../2296-to-anne-elizabeth-mary-anderson-morshead-2.qmd)
- [Letter 2311](../2311-to-alexander-macmillan-108.qmd)
- [Letter 2322](../2322-to-arthur-john-butler-3.qmd)
- [Letter 2343](../2343-to-miss-forrest.qmd)
- [Letter 2344](../2344-to-ellen-julia-johns-10.qmd)
- [Letter 2348](../2348-to-edith-sophia-jacob-18.qmd)
- [Letter 2377](../2377-to-arthur-john-butler-11.qmd)
- [Letter 2389](../2389-to-mary-augusta-arnold.qmd)
- [Letter 2390](../2390-to-the-reverend-william-john-butler.qmd)
- [Letter 2393](../2393-edward-hugessen-knatchbull-hugessen-to-charlotte-mary-yonge.qmd)
- [Letter 2395](../2395-to-bell-and-daldy.qmd)
- [Letter 2402](../2402-to-arthur-john-butler-12.qmd)
- [Letter 2408](../2408-to-elizabeth-wordsworth-2.qmd)
- [Letter 2437](../2437-to-sir-william-heathcote-bt-5.qmd)
- [Letter 2534](../2534-to-miss-frere.qmd)
- [Letter 2538](../2538-to-augusta-boevey-pode-3.qmd)
- [Letter 2546](../2546-to-elizabeth-missing-sewell-22.qmd)
- [Letter 2562](../2562-edward-augustus-freeman-to-charlotte-mary-yonge.qmd)
- [Letter 2574](../2574-to-hezekiah-butterworth.qmd)
- [Letter 2575](../2575-to-miss-kekewich.qmd)
- [Letter 2607](../2607-to-elizabeth-wordsworth-9.qmd)
- [Letter 2637](../2637-to-the-hon-sophia-matilda-palmer-6.qmd)
- [Letter 2638](../2638-to-alexander-macmillan-131.qmd)
- [Letter 2653](../2653-to-an-unknown-woman-44.qmd)
- [Letter 2659](../2659-to-george-lillie-craik-49.qmd)
- [Letter 2678](../2678-to-alexander-macmillan-137.qmd)
- [Letter 2730](../2730-to-ann-maria-carter-smith-86.qmd)
- [Letter 2747](../2747-to-horatia-katharine-frances-gatty-2.qmd)
- [Letter 2749](../2749-to-an-unknown-woman-56.qmd)
- [Letter 2755](../2755-elizabeth-jane-oswald-to-charlotte-mary-yonge.qmd)
- [Letter 2758](../2758-to-ann-maria-carter-smith-88.qmd)
- [Letter 2764](../2764-to-george-lillie-craik-55.qmd)
- [Letter 2766](../2766-to-john-duke-pode.qmd)
- [Letter 2769](../2769-to-catharine-elgie.qmd)
- [Letter 2777](../2777-to-an-unknown-woman-60.qmd)
- [Letter 2783](../2783-to-christabel-rose-coleridge-110.qmd)
- [Letter 2789](../2789-to-ann-maria-carter-smith-91.qmd)
- [Letter 2793](../2793-to-george-lillie-craik-58.qmd)
- [Letter 2794](../2794-to-george-lillie-craik-59.qmd)
- [Letter 2802](../2802-to-the-reverend-richard-st-john-tyrwhitt-3.qmd)
- [Letter 2830](../2830-to-george-lillie-craik-65.qmd)
- [Letter 2837](../2837-to-george-lillie-craik-70.qmd)
- [Letter 2842](../2842-to-mary-louisa-molesworth.qmd)
- [Letter 2858](../2858-to-mary-drew-3.qmd)
- [Letter 2859](../2859-to-christabel-rose-coleridge-115.qmd)
- [Letter 2866](../2866-to-anna-georgina-macaulay.qmd)
- [Letter 2875](../2875-to-walter-smith.qmd)
- [Letter 2876](../2876-to-beatrix-feodore-cresswell.qmd)
- [Letter 2877](../2877-to-anna-butler-19.qmd)
- [Letter 2884](../2884-to-arthur-donald-innes-21.qmd)
- [Letter 2887](../2887-to-arthur-donald-innes-22.qmd)
- [Letter 2889](../2889-to-an-unknown-woman-64.qmd)
- [Letter 2895](../2895-to-arthur-donald-innes-24.qmd)
- [Letter 2901](../2901-to-george-lillie-craik-76.qmd)
- [Letter 2904](../2904-to-miss-durton.qmd)
- [Letter 2914](../2914-to-arthur-donald-innes-28.qmd)
- [Letter 2930](../2930-to-an-unknown-woman-67.qmd)
- [Letter 2964](../2964-to-mary-anne-dyson-5.qmd)
- [Letter 2971](../2971-to-mary-anne-dyson-11.qmd)
- [Letter 2973](../2973-to-elizabeth-barnett-2.qmd)
- [Letter 2975](../2975-to-elizabeth-barnett-3.qmd)
- [Letter 2978](../2978-to-elizabeth-roberts-2.qmd)
- [Letter 2980](../2980-to-elizabeth-roberts-3.qmd)
- [Letter 2981](../2981-to-elizabeth-roberts-4.qmd)
- [Letter 2983](../2983-to-elizabeth-roberts-5.qmd)
- [Letter 2985](../2985-to-elizabeth-roberts-7.qmd)
- [Letter 2995](../2995-to-elizabeth-roberts-15.qmd)
- [Letter 3001](../3001-to-elizabeth-roberts-21.qmd)
- [Letter 3004](../3004-to-elizabeth-roberts-24.qmd)
- [Letter 3008](../3008-to-elizabeth-roberts-25.qmd)
- [Letter 3018](../3018-to-elizabeth-roberts-29.qmd)
- [Letter 3022](../3022-to-elizabeth-roberts-31.qmd)
- [Letter 3023](../3023-to-anna-butler-2.qmd)
- [Letter 3024](../3024-to-anna-butler-3.qmd)
- [Letter 3038](../3038-to-anna-butler-4.qmd)
- [Letter 3040](../3040-to-anna-butler-5.qmd)
- [Letter 3043](../3043-to-ellen-j-millington.qmd)
- [Letter 3052](../3052-to-jemima-blackburn-5.qmd)
- [Letter 3068](../3068-to-anna-butler-6.qmd)
- [Letter 3074](../3074-to-ann-maria-carter-smith-3.qmd)
- [Letter 3077](../3077-to-anna-butler-7.qmd)
- [Letter 3083](../3083-to-anna-butler-10.qmd)
- [Letter 3088](../3088-to-ann-maria-carter-smith-5.qmd)
- [Letter 3090](../3090-to-ann-maria-carter-smith-7.qmd)
- [Letter 3091](../3091-to-anna-butler-14.qmd)
- [Letter 3094](../3094-to-ann-maria-carter-smith-9.qmd)
- [Letter 3098](../3098-to-harriet-dyke-acland-troyte.qmd)
- [Letter 3101](../3101-to-anna-butler-15.qmd)
- [Letter 3102](../3102-to-anna-butler-16.qmd)
- [Letter 3105](../3105-to-ann-maria-carter-smith-11.qmd)
- [Letter 3116](../3116-to-elizabeth-roberts-38.qmd)
- [Letter 3117](../3117-to-an-unknown-woman-9.qmd)
- [Letter 3120](../3120-to-the-reverend-upton-richards.qmd)
- [Letter 3126](../3126-to-ann-maria-carter-smith-15.qmd)
- [Letter 3128](../3128-to-ann-maria-carter-smith-17.qmd)
- [Letter 3142](../3142-to-ann-maria-carter-smith-25.qmd)
- [Letter 3146](../3146-to-elizabeth-roberts-39.qmd)
- [Letter 3154](../3154-to-arthur-donald-innes-5.qmd)
- [Letter 3155](../3155-to-arthur-donald-innes-6.qmd)
- [Letter 3156](../3156-to-arthur-donald-innes-7.qmd)
- [Letter 3157](../3157-to-arthur-donald-innes-8.qmd)
- [Letter 3160](../3160-to-george-lillie-craik-7.qmd)
- [Letter 3164](../3164-to-florence-wilford-6.qmd)
- [Letter 3168](../3168-to-arthur-donald-innes-10.qmd)
- [Letter 3174](../3174-to-arthur-donald-innes-11.qmd)
- [Letter 3175](../3175-to-arthur-donald-innes-12.qmd)
- [Letter 3176](../3176-to-arthur-donald-innes-13.qmd)
- [Letter 3189](../3189-to-arthur-donald-innes-16.qmd)
- [Letter 3190](../3190-to-christabel-rose-coleridge-29.qmd)
- [Letter 3208](../3208-to-oscar-fay-adams.qmd)
- [Letter 3209](../3209-to-arthur-donald-innes-17.qmd)
- [Letter 3210](../3210-to-sarah-angelina-acland.qmd)
- [Letter 3211](../3211-to-george-lillie-craik-9.qmd)
- [Letter 3213](../3213-to-george-lillie-craik-11.qmd)
- [Letter 3216](../3216-to-lady-frederick-bruce-3.qmd)
- [Letter 3236](../3236-to-anne-elizabeth-mary-anderson-morshead-4.qmd)
- [Letter 3263](../3263-to-anne-isabella-ritchie-2.qmd)
- [Letter 3266](../3266-to-arthur-john-butler-9.qmd)
- [Letter 3284](../3284-to-an-unknown-woman-26.qmd)
- [Letter 3300](../3300-to-frederick-orridge-macmillan-or-alexander-macmillan-3.qmd)
- [Letter 3301](../3301-to-frederick-orridge-macmillan-or-alexander-macmillan.qmd)
- [Letter 3315](../3315-to-frederick-orridge-macmillan-9.qmd)
- [Letter 3347](../3347-to-an-unknown-man-perhaps-editor-of-a-biographical-dictionary.qmd)
- [Letter 3394](../3394-to-sir-walter-besant-2.qmd)
- [Letter 3407](../3407-to-lady-leconfield.qmd)
- [Letter 3409](../3409-to-mary-yonge-12.qmd)
- [Letter 3411](../3411-to-charlotte-fortescue-yonge-3.qmd)
- [Letter 3412](../3412-to-christabel-rose-coleridge-28.qmd)
- [Letter 3416](../3416-to-christabel-rose-coleridge-22.qmd)
- [Letter 3418](../3418-to-christabel-rose-coleridge-24.qmd)
- [Letter 3421](../3421-to-christabel-rose-coleridge-31.qmd)
- [Letter 3422](../3422-to-christabel-rose-coleridge-32.qmd)
- [Letter 3423](../3423-to-christabel-rose-coleridge-33.qmd)
- [Letter 3427](../3427-to-christabel-rose-coleridge-35.qmd)
- [Letter 3467](../3467-to-mrs-c-e-barrett-lennard.qmd)
- [Letter 3486](../3486-to-%e2%80%98bath-brick%e2%80%99-a-member-of-the-spider-society.qmd)
- [Letter 3493](../3493-the-reverend-john-mason-neale-to-charlotte-mary-yonge.qmd)
- [Letter 3502](../3502-to-an-unknown-woman-68.qmd)
- [Letter 3518](../3518-to-elizabeth-barnett-10.qmd)
- [Letter 3521](../3521-to-miss-phillpotts.qmd)
- [Letter 3529](../3529-to-miss-routledge.qmd)
- [Letter 3531](../3531-to-an-unknown-woman-71.qmd)
- [Letter 3542](../3542-to-an-unknown-woman-21.qmd)
- [Letter 3547](../3547-to-margaret-gatty.qmd)
- [Letter 3548](../3548-to-frances-sophia-coleridge-patteson.qmd)
- [Letter 3549](../3549-to-mrs-baker.qmd)
- [Letter 3576](../3576-to-the-author-of-%e2%80%98ella%e2%80%99s-dream%e2%80%99.qmd)
- [Letter 3583](../3583-to-an-unknown-woman-2.qmd)
- [Letter 3586](../3586-to-an-unknown-man-2.qmd)
- [Letter 3601](../3601-to-ann-maria-carter-smith-2.qmd)
- [Letter 3606](../3606-to-mary-elizabeth-webster.qmd)
- [Letter 3608](../3608-to-agnes-cox.qmd)
- [Letter 3611](../3611-to-an-unknown-woman-5.qmd)
- [Letter 7267](../7267-to-mr-chandler.qmd)
- [Letter 9418](../9418-to-the-editor-of-the-i-girls-friendly-society-associates-journal-i.qmd)
- [Letter 14540](../14540-to-fanny-harrison.qmd)
- [Letter 18751](../18751-to-susan-dabney-smedes.qmd)
- [Letter 19054](../19054-to-alice-hilda-godman.qmd)
- [Letter 19282](../19282-to-george-lillie-craik.qmd)
- [Letter 19373](../19373-to-an-unknown-woman.qmd)

