---
title: "Girls' Friendly Society Associates' Journal, The"
other_id: 72
---

**Type:** periodical

## Description

This periodical (1883-1919) was aimed at the upper-class associates, not at the Members of the GFS, for whom the sister journals <i>Friendly Leaves</i> and <i>Friendly Work</i> existed.  Between 1881-3 it was entitled the <i>Girls' Friendly Society Advertiser</i>.  It contains references to CMY's presence at meetings and comments by her, some letters from her (included in this edition) and articles signed by her.





An obituary of CMY, describing her GFS work, signed C. C. and probably the work of Christabel Coleridge, appeared in the issue for May 1901, p.75.

## Letters Mentioning This

- [Letter 3443](../3443-to-christabel-rose-coleridge-38.qmd)
- [Letter 9343](../9343-to-the-editor-of-the-i-girls-friendly-society-associates-journal-i.qmd)
- [Letter 9348](../9348-to-the-editor-of-the-i-girls-friendly-society-associates-journal-i.qmd)
- [Letter 9355](../9355-to-the-editor-of-the-i-girls-friendly-society-associates-journal-i.qmd)
- [Letter 9362](../9362-to-the-editor-of-the-i-girls-friendly-society-associates-journal-i.qmd)
- [Letter 9369](../9369-to-the-editor-of-the-i-girls-friendly-society-associates-journal-i.qmd)
- [Letter 9374](../9374-to-the-editor-of-the-i-girls-friendly-society-associates-journal-i.qmd)
- [Letter 9379](../9379-to-the-editor-of-the-i-girls-friendly-society-associates-journal-i.qmd)
- [Letter 9389](../9389-to-the-editor-of-the-i-girls-friendly-society-associates-journal-i.qmd)
- [Letter 9398](../9398-to-the-editor-of-the-i-girls-friendly-society-associates-journal-i.qmd)
- [Letter 9403](../9403-to-the-editor-of-the-i-girls-friendly-society-associates-journal-i-.qmd)
- [Letter 9418](../9418-to-the-editor-of-the-i-girls-friendly-society-associates-journal-i.qmd)
- [Letter 9425](../9425-to-the-editor-of-the-i-girls-friendly-society-associates-journal-i.qmd)

