---
title: "Church of the Resurrection, Eastleigh"
other_id: 188
---

**Type:** place

## Description

Built in 1868 with a donation of £500 from CMY.  The architect was G. E. Street.  It was destroyed by fire in 1985 and reconstructed as social housing flats in 2003.





See Tim Lambert, <i>A Brief History of Eastleigh, Hampshire</i> at www.localhistories.org/eastleigh





The <i>Hampshire Advertiser</i> (15 August 1868), 3, noted: 


The consecration of the Church of the Resurrection, Eastliegh, took place on Thursday, by the Bishop of Mauritius. The church has been erected principally by the liberality of Miss Yonge, of Otterbourne, and Mr. - Chamberlaine, of Eastleigh Parish, together with other contributors.  The Rev. W. A. Longlands, of Eling, near Southampton, has been appointed incumbent.  A choir of amateurs has been trained by Mr. Somerford, of Winchester  Cathedral. .  .  The services were intoned, or read, by the Rev. W. A. Longlands, incumbent, the Rev. W. Harrison, Vicar, Eastmeon, the Ven. Archdeacon Jacob, of Winchester, the Rev. R. F. Wilson, &c.

## Letters Mentioning This

- [Letter 2174](../2174-to-alexander-macmillan-86.qmd)
- [Letter 2175](../2175-alexander-macmillan-to-charlotte-mary-yonge-51.qmd)
- [Letter 2191](../2191-alexander-macmillan-to-charlotte-mary-yonge-55.qmd)
- [Letter 2195](../2195-to-marianne-bigg-wither-6.qmd)
- [Letter 2206](../2206-to-robert-brett.qmd)
- [Letter 2210](../2210-to-the-reverend-arthur-rawson-ashwell.qmd)
- [Letter 2249](../2249-to-edith-sophia-jacob-12.qmd)
- [Letter 2260](../2260-to-edith-sophia-jacob-15.qmd)
- [Letter 2264](../2264-to-the-reverend-duke-yonge-2.qmd)
- [Letter 2284](../2284-to-elizabeth-missing-sewell-9.qmd)
- [Letter 2290](../2290-to-sophia-jane-harrison.qmd)
- [Letter 2294](../2294-to-christabel-rose-coleridge-19.qmd)
- [Letter 2372](../2372-to-mary-yonge-36.qmd)

