---
title: "'Bethlehem'"
other_id: 177
---

**Type:** topic

## Description

This was a book project concerted between CMY and her publisher Alexander Macmillan, of which some seems to have been written and none published.

## Letters Mentioning This

- [Letter 2013](../2013-alexander-macmillan-to-charlotte-mary-yonge-20.qmd)
- [Letter 2014](../2014-to-alexander-macmillan-37.qmd)
- [Letter 2015](../2015-alexander-macmillan-to-charlotte-mary-yonge-21.qmd)
- [Letter 2016](../2016-alexander-macmillan-to-charlotte-mary-yonge-22.qmd)
- [Letter 2017](../2017-to-alexander-macmillan-38.qmd)
- [Letter 2018](../2018-alexander-macmillan-to-charlotte-mary-yonge-23.qmd)
- [Letter 2019](../2019-to-alexander-macmillan-39.qmd)
- [Letter 2020](../2020-alexander-macmillan-to-charlotte-mary-yonge-24.qmd)
- [Letter 2021](../2021-to-alexander-macmillan-40.qmd)
- [Letter 2022](../2022-alexander-macmillan-to-charlotte-mary-yonge-25.qmd)
- [Letter 2026](../2026-to-alexander-macmillan-41.qmd)
- [Letter 2027](../2027-alexander-macmillan-to-charlotte-mary-yonge-26.qmd)
- [Letter 2028](../2028-to-alexander-macmillan-42.qmd)
- [Letter 2029](../2029-alexander-macmillan-to-charlotte-mary-yonge-27.qmd)
- [Letter 2030](../2030-to-alexander-macmillan-43.qmd)
- [Letter 2032](../2032-alexander-macmillan-to-charlotte-mary-yonge-28.qmd)
- [Letter 2033](../2033-alexander-macmillan-to-charlotte-mary-yonge-29.qmd)
- [Letter 2034](../2034-to-alexander-macmillan-44.qmd)
- [Letter 2035](../2035-alexander-macmillan-to-charlotte-mary-yonge-30.qmd)
- [Letter 2037](../2037-alexander-macmillan-to-charlotte-mary-yonge-31.qmd)
- [Letter 2039](../2039-to-alexander-macmillan-46.qmd)
- [Letter 2042](../2042-to-alexander-macmillan-48.qmd)

