---
title: "Gosling Society, The"
other_id: 104
---

**Type:** topic

## Description

The Gosling Society was an essay society run by CMY which operated 1859-1877








In 1859 CMY was encouraged by her cousin [Mary Coleridge](../people/person_351.qmd) to start an essay society for a group of young girls who were in need of more mental stimulation than the life of a Victorian daughter at home afforded them.  They called her Mother Goose and they became the Goslings.  Each girl adopted a fancy pen-name such as  ‘Hedge Rose’ or ‘Shamrock’.  Each wrote two essays a month for her, and the best essays were circulated among them all.  





The foundation of the Gosling Society reflects the anxiety felt by many Victorians about the restricted educational opportunities for women.   Its existence coincided with the dramatic expansion of schools and universities open to women.  It doesn’t seem that any of the Goslings benefited personally from these developments, but, as Julia Courtney has argued in ['The Barnacle: A Manuscript Magazine'](../other_books/otherbook_190.qmd), they were of the generation who helped to bring such schools and universities into being.  Several of them followed Yonge’s example and became writers themselves.





Charlotte Yonge herself was not a wholehearted supporter of schools and universities for women, though her attitude mellowed over the years, but her intellectual standards were high, and members were required to research and compose two essays a month on such topics as ‘The distinguished Christian characters of Milan’  or ‘What parallel stories does folklore in different countries present to the adventures of Ulysses in the Odyssey?’ or ‘The citizen of Athens’.





Membership


The earliest known members of the Society were Mary’s niece Mildred Coleridge,  two other cousins of hers, Paulina Martyn and Christabel Coleridge, two Devon neighbours, Charlotte and Henrietta Fursdon, and Charlotte Yonge’s friend and neighbour Emily Moberly.  Many of them were related to each other;  all were drawn from a narrow social circle, mainly from clerical and gentry families.  They were probably all consciously High Church, and several of them, like Yonge herself, became Associate members of the Wantage sisterhood. Over the years the membership fluctuated as girls grew up, lost interest or married, but it seems to have usually included about ten young women.  During the 1860s three other older women, Frances Peard, Florence Wilford, and Emily Synge, were recruited, the first certainly in response to Mary Coleridge’s loss of interest as Mildred grew up.   





A list of the society's members will be found at http://www.dur.ac.uk/c.e.schultze/context/goslings.html





Sources


The only modern scholarly study is by Julia Courtney, ‘The Barnacle: A manuscript magazine of the 1860s’, in <i>The Girl’s Own: Cultural Histories of the Anglo –American Girl 1830-1915</i> ed.Claudia Nelson and Lynne Vallone.  (Arkansas and London: University of Georgia Press: 1994).





The main evidence about the Gosling Society comes from the surviving volumes of its manuscript magazine, <i>The Barnacle</i> (incomplete series, 1863-1867), in the library of Lady Margaret Hall, Oxford.   These have circulation lists at the front, which, in conjunction with two other surviving circulation lists for 1869 and 1876 (private collection), provide most of the information about membership.





There are interesting references to the Society in Christabel Coleridge's  <i>[Life](../other_books/otherbook_40.qmd)</i> of CMY and Mary J. Y. Harris's, <i>[Memoirs of Frances Mary Peard](../other_books/otherbook_318.qmd)</i>.





One of Yonge’s stories, <i>[The Disturbing Element, or, Chronicles of the Bluebell Society](../cmy_books/cmybook_125.qmd)</i> (1878) is about a middle-aged spinster who runs a reading group for a group of girls in a small resort in south Devon.  It seems to draw on some of her experiences with the Goslings.





Another fictional source is a story which appeared in <i>MP</i> (Christmas 1872), 1-3, entitled 'Our Essay Society, or, A Wet Day with the Spiders'.  It may be by CMY, but is probably the work of Christabel Coleridge.  It reminisces fondly about the society's early days.  In the story the society the members are Spiders rather than Goslings, and that name was later adopted by the much larger essay society run out of <i>MP</i>.





There is also some discussion of essay societies in  Yonge’s regular column on ‘Hints on Reading’ in <i>MP</i> 30 (August 1865), 221-2.




## Letters Mentioning This

- [Letter 1819](../1819-to-katharine-olive-helmore-2.qmd)
- [Letter 1825](../1825-to-katharine-olive-helmore-3.qmd)
- [Letter 1842](../1842-to-henrietta-elizabeth-fursdon-2.qmd)
- [Letter 1844](../1844-to-henrietta-elizabeth-fursdon-3.qmd)
- [Letter 1849](../1849-to-katharine-olive-helmore-4.qmd)
- [Letter 1850](../1850-to-katharine-olive-helmore-5.qmd)
- [Letter 1853](../1853-to-katharine-olive-helmore-6.qmd)
- [Letter 1857](../1857-to-charlotte-sophia-fursdon.qmd)
- [Letter 1858](../1858-to-henrietta-elizabeth-fursdon-5.qmd)
- [Letter 1867](../1867-to-henrietta-elizabeth-fursdon-6.qmd)
- [Letter 1882](../1882-to-henrietta-elizabeth-fursdon-7.qmd)
- [Letter 1921](../1921-to-henrietta-elizabeth-fursdon-9.qmd)
- [Letter 1923](../1923-to-henrietta-elizabeth-fursdon-10.qmd)
- [Letter 1924](../1924-to-christabel-rose-coleridge-5.qmd)
- [Letter 1942](../1942-to-ann-catherine-johns.qmd)
- [Letter 1996](../1996-to-the-reverend-john-frewen-moor-13.qmd)
- [Letter 2003](../2003-to-christabel-rose-coleridge-6.qmd)
- [Letter 2005](../2005-to-ellen-julia-johns-3.qmd)
- [Letter 2009](../2009-to-ellen-julia-johns-4.qmd)
- [Letter 2013](../2013-alexander-macmillan-to-charlotte-mary-yonge-20.qmd)
- [Letter 2023](../2023-to-katharine-olive-helmore-7.qmd)
- [Letter 2057](../2057-to-ellen-julia-johns-7.qmd)
- [Letter 2070](../2070-to-katharine-olive-helmore-8.qmd)
- [Letter 2078](../2078-to-christabel-rose-coleridge-7.qmd)
- [Letter 2088](../2088-to-ellen-julia-johns-8.qmd)
- [Letter 2093](../2093-to-frances-mary-peard-9.qmd)
- [Letter 2098](../2098-to-christabel-rose-coleridge-8.qmd)
- [Letter 2107](../2107-to-katharine-olive-helmore.qmd)
- [Letter 2148](../2148-to-edith-coleridge.qmd)
- [Letter 2150](../2150-to-christabel-rose-coleridge-9.qmd)
- [Letter 2173](../2173-to-christabel-rose-coleridge-10.qmd)
- [Letter 2185](../2185-to-christabel-rose-coleridge-11.qmd)
- [Letter 2201](../2201-to-christabel-rose-coleridge-12.qmd)
- [Letter 2207](../2207-to-christabel-rose-coleridge-13.qmd)
- [Letter 2234](../2234-to-christabel-rose-coleridge-15.qmd)
- [Letter 2255](../2255-to-christabel-rose-coleridge-16.qmd)
- [Letter 2288](../2288-to-the-reverend-william-john-butler-2.qmd)
- [Letter 2289](../2289-to-christabel-rose-coleridge-60.qmd)
- [Letter 2291](../2291-to-christabel-rose-coleridge-18.qmd)
- [Letter 2294](../2294-to-christabel-rose-coleridge-19.qmd)
- [Letter 2296](../2296-to-anne-elizabeth-mary-anderson-morshead-2.qmd)
- [Letter 2299](../2299-to-henrietta-elizabeth-fursdon-11.qmd)
- [Letter 2306](../2306-to-christabel-rose-coleridge-20.qmd)
- [Letter 2307](../2307-to-the-members-of-the-gosling-society.qmd)
- [Letter 2327](../2327-to-henrietta-elizabeth-fursdon.qmd)
- [Letter 2369](../2369-to-christabel-rose-coleridge-61.qmd)
- [Letter 2371](../2371-to-mary-penelope-fursdon-2.qmd)
- [Letter 2374](../2374-to-christabel-rose-coleridge-62.qmd)
- [Letter 2379](../2379-to-christabel-rose-coleridge-63.qmd)
- [Letter 2382](../2382-to-christabel-rose-coleridge-64.qmd)
- [Letter 2384](../2384-to-mary-penelope-fursdon-3.qmd)
- [Letter 2411](../2411-to-christabel-rose-coleridge-65.qmd)
- [Letter 2417](../2417-to-mary-penelope-fursdon-4.qmd)
- [Letter 2419](../2419-to-christabel-rose-coleridge-67.qmd)
- [Letter 2421](../2421-to-christabel-rose-coleridge-68.qmd)
- [Letter 2422](../2422-to-christabel-rose-coleridge-69.qmd)
- [Letter 2427](../2427-to-miss-cassell.qmd)
- [Letter 2434](../2434-to-christabel-rose-coleridge-70.qmd)
- [Letter 2438](../2438-to-christabel-rose-coleridge-71.qmd)
- [Letter 2458](../2458-to-christabel-rose-coleridge-74.qmd)
- [Letter 2459](../2459-to-christabel-rose-coleridge-75.qmd)
- [Letter 2461](../2461-to-christabel-rose-coleridge-76.qmd)
- [Letter 2462](../2462-to-mary-penelope-fursdon-5.qmd)
- [Letter 2466](../2466-to-christabel-rose-coleridge-78.qmd)
- [Letter 2475](../2475-to-christabel-rose-coleridge-79.qmd)
- [Letter 2510](../2510-to-christabel-rose-coleridge-80.qmd)
- [Letter 2520](../2520-to-edith-emma-butler.qmd)
- [Letter 2532](../2532-to-christabel-rose-coleridge-81.qmd)
- [Letter 2548](../2548-to-mary-penelope-fursdon.qmd)
- [Letter 2570](../2570-to-christabel-rose-coleridge-85.qmd)
- [Letter 2590](../2590-to-christabel-rose-coleridge-89.qmd)
- [Letter 2600](../2600-from-charlotte-mary-yonge-and-christabel-rose-coleridge-to-mary-penelope-fursdon-and-the-other-members-of-the-gosling-society.qmd)
- [Letter 2649](../2649-to-alexander-macmillan-132.qmd)
- [Letter 2705](../2705-to-margaret-macmillan.qmd)
- [Letter 2733](../2733-to-christabel-rose-coleridge-104.qmd)
- [Letter 3164](../3164-to-florence-wilford-6.qmd)
- [Letter 3407](../3407-to-lady-leconfield.qmd)
- [Letter 3562](../3562-to-christabel-rose-coleridge-21.qmd)
- [Letter 7883](../7883-to-john-duke-coleridge.qmd)
- [Letter 19298](../19298-to-henrietta-elizabeth-fursdon.qmd)
- [Letter 19839](../19839-to-a-member-of-the-gosling-society.qmd)

