---
title: "Keble's funeral"
other_id: 184
---

**Type:** topic

## Description

Keble's funeral, which CMY described as a 'gathering of the good' took place on Friday 6 April 1866 at the church of All Saints, Hursley.  [Charlotte Keble](../people/person_795.qmd) was not present as she was lying dangerously ill in Bournemouth.





A large congregation is recorded in the accounts in <i>John Bull</i> (7 April 1866) 234  and the <i>Pall Mall Gazette</i> (7 April 1866) 8. The six former curates who carried the coffin were the Rev. Peter Young, the Rev. William Bigg Wither, the Rev. Robert Francis Wilson, the Rev. C. Le Geyt, the Rev. F. C. Alderson and the Rev. S. Scroggs. The Bishop of Salisbury (Walter Kerr Hamilton) was the only English bishop present, illustrating the suspicion in which the Tractarians were still held in many circles, though Bishop Forbes of Brechin was there.  Cathedral clergy who did come included the Very Rev. Dr Hook, the Dean of Chichester, the Very Rev. Thomas Garnier, the aged Dean of Winchester, and the Ven. Philip Jacob, the Archdeacon of Winchester.   Sir William Heathcote was there with his son-in-law Thomas Cooke Trench, as were Earl Nelson, Sir Frederic Rogers, General Wilbraham, Robert Brett, the Hon. Colin Lindsay and William Butterfield.  Other well-known Tractarian clergy included the Rev. W. J. Butler, the Rev. R. W. Church, the Rev. C. F. Lowder, Dr. Pusey, Dr. Moberly, the Ven. Sir George Prevost, the Rev. William Upton Richards and the Rev. Henry Parry Liddon,


