---
title: "rate of payment of MP contributors"
other_id: 102
---

**Type:** topic

## Letters Mentioning This

- [Letter 1778](../1778-to-ann-maria-carter-smith-27.qmd)
- [Letter 1834](../1834-to-ann-maria-carter-smith-46.qmd)
- [Letter 1854](../1854-to-ann-maria-carter-smith-51.qmd)
- [Letter 1865](../1865-to-ann-maria-carter-smith-53.qmd)
- [Letter 1869](../1869-to-ann-maria-carter-smith-54.qmd)
- [Letter 1883](../1883-to-ann-maria-carter-smith-58.qmd)
- [Letter 1893](../1893-to-ann-maria-carter-smith-62.qmd)
- [Letter 1937](../1937-to-ann-maria-carter-smith-66.qmd)
- [Letter 2633](../2633-to-linda-villari-2.qmd)
- [Letter 2985](../2985-to-elizabeth-roberts-7.qmd)
- [Letter 2986](../2986-to-elizabeth-roberts-8.qmd)
- [Letter 2991](../2991-to-elizabeth-roberts-11.qmd)
- [Letter 2993](../2993-to-elizabeth-roberts-13.qmd)
- [Letter 3004](../3004-to-elizabeth-roberts-24.qmd)
- [Letter 3014](../3014-to-elizabeth-roberts-28.qmd)
- [Letter 3074](../3074-to-ann-maria-carter-smith-3.qmd)
- [Letter 3090](../3090-to-ann-maria-carter-smith-7.qmd)
- [Letter 3114](../3114-to-ann-maria-carter-smith-14.qmd)
- [Letter 3116](../3116-to-elizabeth-roberts-38.qmd)
- [Letter 3131](../3131-to-ann-maria-carter-smith-20.qmd)
- [Letter 3391](../3391-to-frederick-orridge-macmillan-2.qmd)
- [Letter 3508](../3508-to-an-unknown-woman-19.qmd)

