---
title: "Society for the Promotion of Christian Knowledge, The"
other_id: 40
---

**Type:** organization

## Description

This charity, founded to promote Christianity at home and abroad in 1698, has long had and still has a substantial publishing arm.  CMY planned to get it to publish a series of county histories (3, 5 November 1860).  Unlike many of her friends, she did not write for it.  Its archives are held in Cambridge University Library.  See http://www.spck.org.uk/about-spck/archives/

## Letters Mentioning This

- [Letter 1804](../1804-to-susanna-warren-2.qmd)
- [Letter 1805](../1805-to-elizabeth-roberts.qmd)
- [Letter 2008](../2008-to-alexander-macmillan-35.qmd)
- [Letter 2356](../2356-to-louisa-anne-gibbs.qmd)
- [Letter 2521](../2521-to-edward-augustus-freeman-10.qmd)
- [Letter 2572](../2572-to-christabel-rose-coleridge-86.qmd)
- [Letter 2573](../2573-to-christabel-rose-coleridge-87.qmd)
- [Letter 2577](../2577-to-mr-hoskins.qmd)
- [Letter 2653](../2653-to-an-unknown-woman-44.qmd)
- [Letter 2749](../2749-to-an-unknown-woman-56.qmd)
- [Letter 3239](../3239-to-an-unknown-woman-18.qmd)
- [Letter 3386](../3386-to-christabel-rose-coleridge-25.qmd)
- [Letter 3391](../3391-to-frederick-orridge-macmillan-2.qmd)
- [Letter 3430](../3430-to-christabel-rose-coleridge-36.qmd)
- [Letter 3469](../3469-to-christabel-rose-coleridge-52.qmd)
- [Letter 3470](../3470-to-christabel-rose-coleridge-53.qmd)
- [Letter 3471](../3471-to-christabel-rose-coleridge-54.qmd)
- [Letter 3491](../3491-to-susanna-warren.qmd)

